import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/** Reviewed vocabulary for the existing B1/B2/C1 u28 and u29 units. */
export const ENGLISH_B1_B2_C1_U28_U29_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u28: [
      reviewed({ word: "clarification", translation: "توضيح", pos: "noun", ipa: "/ˌklærɪfɪˈkeɪʃən/", definition: "an explanation that makes something easier to understand", example: "I asked for clarification before starting the task.", exampleTranslation: "طلبت توضيحًا قبل بدء المهمة.", category: "work and communication", tags: ["workplace", "communication"], synonyms: ["explanation", "elaboration"] }),
      reviewed({ word: "punctuality", translation: "الالتزام بالمواعيد", pos: "noun", ipa: "/ˌpʌŋktʃuˈæləti/", definition: "the quality of arriving or acting at the agreed time", example: "Punctuality is important when a team is working to a deadline.", exampleTranslation: "يُعد الالتزام بالمواعيد مهمًا عندما يعمل فريق وفق موعد نهائي.", category: "work and communication", tags: ["workplace", "time"], synonyms: ["timeliness", "promptness"] }),
      reviewed({ word: "employee appraisal", translation: "تقييم الموظف", pos: "noun", ipa: "/ɪmˈplɔɪiː əˈpreɪzəl/", definition: "a formal assessment of an employee's work and progress", example: "The employee appraisal included goals for the next year.", exampleTranslation: "شمل تقييم الموظف أهدافًا للسنة المقبلة.", category: "work and communication", tags: ["workplace", "performance"], synonyms: ["staff assessment", "work evaluation"] }),
      reviewed({ word: "team briefing", translation: "إحاطة للفريق", pos: "noun", ipa: "/tiːm ˈbriːfɪŋ/", definition: "a short meeting in which a team receives information and instructions", example: "The manager gave a team briefing before the busy shift.", exampleTranslation: "قدم المدير إحاطة للفريق قبل المناوبة المزدحمة.", category: "work and communication", tags: ["meetings", "teamwork"], synonyms: ["team update", "staff briefing"] }),
      reviewed({ word: "follow-up email", translation: "رسالة متابعة بالبريد الإلكتروني", pos: "noun", ipa: "/ˈfɒləʊ ʌp ˈiːmeɪl/", definition: "an email sent after a conversation or meeting to confirm information or next steps", example: "I sent a follow-up email summarising our agreement.", exampleTranslation: "أرسلت رسالة متابعة بالبريد الإلكتروني ألخص فيها اتفاقنا.", category: "work and communication", tags: ["email", "communication"], synonyms: ["confirmation email", "post-meeting message"] }),
      reviewed({ word: "office etiquette", translation: "آداب المكتب", pos: "noun", ipa: "/ˈɒfɪs ˈetɪket/", definition: "accepted rules for polite and professional behaviour at work", example: "The induction session explained basic office etiquette.", exampleTranslation: "شرحت جلسة التعريف آداب المكتب الأساسية.", category: "work and communication", tags: ["workplace", "professionalism"], synonyms: ["workplace manners", "professional etiquette"] }),
      reviewed({ word: "handover note", translation: "مذكرة تسليم", pos: "noun", ipa: "/ˈhændəʊvə nəʊt/", definition: "a written message that passes important information from one worker or shift to another", example: "The handover note listed the client's requests and the unfinished tasks.", exampleTranslation: "أدرجت مذكرة التسليم طلبات العميل والمهام غير المكتملة.", category: "work and communication", tags: ["workplace", "documentation"], synonyms: ["shift note", "transfer note"] }),
      reviewed({ word: "active listening", translation: "الاستماع النشط", pos: "noun", ipa: "/ˌæktɪv ˈlɪsənɪŋ/", definition: "giving full attention to a speaker and showing that you understand", example: "Active listening helped the colleagues resolve the misunderstanding.", exampleTranslation: "ساعد الاستماع النشط الزميلين على حل سوء الفهم.", category: "work and communication", tags: ["communication", "teamwork"], synonyms: ["attentive listening", "engaged listening"] }),
    ],
    u29: [
      reviewed({ word: "recycling bin", translation: "حاوية إعادة التدوير", pos: "noun", ipa: "/ˈriːsaɪklɪŋ bɪn/", definition: "a container for materials that can be processed and used again", example: "Please put the empty bottle in the recycling bin.", exampleTranslation: "يرجى وضع الزجاجة الفارغة في حاوية إعادة التدوير.", category: "environment and community", tags: ["recycling", "community"], synonyms: ["recycling container", "recovery bin"] }),
      reviewed({ word: "renewable energy", translation: "طاقة متجددة", pos: "noun", ipa: "/rɪˌnjuːəbəl ˈenədʒi/", definition: "energy produced from sources that naturally replace themselves", example: "The community centre now uses renewable energy.", exampleTranslation: "يستخدم المركز المجتمعي الآن طاقة متجددة.", category: "environment and community", tags: ["energy", "sustainability"], synonyms: ["clean energy", "sustainable energy"] }),
      reviewed({ word: "local campaign", translation: "حملة محلية", pos: "noun", ipa: "/ˈləʊkəl kæmˈpeɪn/", definition: "an organised local effort to achieve a social or environmental goal", example: "A local campaign encouraged residents to reduce plastic waste.", exampleTranslation: "شجعت حملة محلية السكان على تقليل النفايات البلاستيكية.", category: "environment and community", tags: ["community", "action"], synonyms: ["community campaign", "local initiative"] }),
      reviewed({ word: "composting", translation: "تحويل النفايات العضوية إلى سماد", pos: "noun", ipa: "/ˈkɒmpɒstɪŋ/", definition: "the process of turning organic waste into material that improves soil", example: "Composting keeps food waste out of the rubbish collection.", exampleTranslation: "يبقي تحويل النفايات العضوية إلى سماد بقايا الطعام خارج جمع النفايات.", category: "environment and community", tags: ["waste", "gardening"], synonyms: ["organic recycling", "compost production"] }),
      reviewed({ word: "noise pollution", translation: "تلوث ضوضائي", pos: "noun", ipa: "/nɔɪz pəˈluːʃən/", definition: "harmful or disturbing levels of unwanted sound", example: "Residents asked the council to address noise pollution near the school.", exampleTranslation: "طلب السكان من المجلس معالجة التلوث الضوضائي قرب المدرسة.", category: "environment and community", tags: ["pollution", "community"], synonyms: ["sound pollution", "excessive noise"] }),
      reviewed({ word: "community garden", translation: "حديقة مجتمعية", pos: "noun", ipa: "/kəˈmjuːnəti ˈɡɑːdən/", definition: "a garden cared for and used by people living in a local area", example: "Volunteers grow vegetables in the community garden.", exampleTranslation: "يزرع المتطوعون الخضروات في الحديقة المجتمعية.", category: "environment and community", tags: ["community", "nature"], synonyms: ["shared garden", "neighbourhood garden"] }),
      reviewed({ word: "wildlife protection", translation: "حماية الحياة البرية", pos: "noun", ipa: "/ˈwaɪldlaɪf prəˈtekʃən/", definition: "actions taken to keep wild animals and plants safe", example: "The new reserve supports wildlife protection and education.", exampleTranslation: "يدعم المحمي الجديد حماية الحياة البرية والتعليم.", category: "environment and community", tags: ["wildlife", "conservation"], synonyms: ["wildlife conservation", "nature protection"] }),
      reviewed({ word: "litter pick", translation: "حملة جمع النفايات", pos: "noun", ipa: "/ˈlɪtə pɪk/", definition: "an organised activity in which people collect rubbish from a public place", example: "The youth club organised a litter pick along the river.", exampleTranslation: "نظم نادي الشباب حملة لجمع النفايات على طول النهر.", category: "environment and community", tags: ["community", "clean-up"], synonyms: ["clean-up event", "rubbish collection"] }),
    ],
  },
  B2: {
    u28: [
      reviewed({ word: "digital economy", translation: "اقتصاد رقمي", pos: "noun", ipa: "/ˌdɪdʒɪtəl ɪˈkɒnəmi/", definition: "economic activity based largely on digital technologies and online services", example: "The digital economy has created new forms of employment.", exampleTranslation: "أوجد الاقتصاد الرقمي أشكالًا جديدة من العمل.", category: "economy and technology", tags: ["economy", "technology"], synonyms: ["online economy", "digital marketplace"] }),
      reviewed({ word: "labour market", translation: "سوق العمل", pos: "noun", ipa: "/ˈleɪbə ˌmɑːkɪt/", definition: "the system in which employers and workers meet and jobs are offered", example: "Automation is changing the skills demanded by the labour market.", exampleTranslation: "تغير الأتمتة المهارات التي يطلبها سوق العمل.", category: "economy and technology", tags: ["employment", "economy"], synonyms: ["job market", "employment market"] }),
      reviewed({ word: "cost-effective", translation: "فعال من حيث التكلفة", pos: "adjective", ipa: "/ˌkɒst ɪˈfektɪv/", definition: "producing a good result without costing more than necessary", example: "Cloud services can be a cost-effective option for small firms.", exampleTranslation: "يمكن أن تكون الخدمات السحابية خيارًا فعالًا من حيث التكلفة للشركات الصغيرة.", category: "economy and technology", tags: ["business", "efficiency"], synonyms: ["economical", "good value"], antonyms: ["costly"] }),
      reviewed({ word: "data-driven", translation: "قائم على البيانات", pos: "adjective", ipa: "/ˈdeɪtə drɪvən/", definition: "based on the collection and analysis of information", example: "The company adopted a data-driven approach to product design.", exampleTranslation: "اعتمدت الشركة نهجًا قائمًا على البيانات في تصميم المنتجات.", category: "economy and technology", tags: ["data", "business"], synonyms: ["evidence-based", "analytics-led"] }),
      reviewed({ word: "technological unemployment", translation: "البطالة التكنولوجية", pos: "noun", ipa: "/ˌteknəlɒdʒɪkəl ʌnɪmˈplɔɪmənt/", definition: "joblessness caused when technology replaces tasks previously done by workers", example: "Policy makers are debating how to reduce technological unemployment.", exampleTranslation: "يناقش واضعو السياسات كيفية تقليل البطالة التكنولوجية.", category: "economy and technology", tags: ["employment", "automation"], synonyms: ["automation-related unemployment", "technology-driven job loss"] }),
      reviewed({ word: "profit margin", translation: "هامش الربح", pos: "noun", ipa: "/ˈprɒfɪt ˌmɑːdʒɪn/", definition: "the amount of profit made in relation to the revenue from a product or service", example: "The retailer improved its profit margin by reducing delivery costs.", exampleTranslation: "حسّن بائع التجزئة هامش ربحه بخفض تكاليف التوصيل.", category: "economy and technology", tags: ["business", "finance"], synonyms: ["profit ratio", "earnings margin"] }),
      reviewed({ word: "planned obsolescence", translation: "التقادم المخطط", pos: "noun", ipa: "/ˌplænd ˌɒbsəˈlesəns/", definition: "the practice of designing products to become outdated or unusable after a limited time", example: "Consumers criticised the device for planned obsolescence.", exampleTranslation: "انتقد المستهلكون الجهاز بسبب التقادم المخطط.", category: "economy and technology", tags: ["technology", "consumption"], synonyms: ["designed obsolescence", "short product life"] }),
      reviewed({ word: "cloud computing", translation: "حوسبة سحابية", pos: "noun", ipa: "/klaʊd kəmˈpjuːtɪŋ/", definition: "the use of remote internet-based servers to store and process data", example: "Cloud computing allows the firm to expand without buying more servers.", exampleTranslation: "تتيح الحوسبة السحابية للشركة التوسع دون شراء مزيد من الخوادم.", category: "economy and technology", tags: ["technology", "business"], synonyms: ["cloud services", "remote computing"] }),
    ],
    u29: [
      reviewed({ word: "cultural stereotype", translation: "صورة نمطية ثقافية", pos: "noun", ipa: "/ˈkʌltʃərəl ˈsteriətaɪp/", definition: "a simplified and often unfair belief about a cultural group", example: "The documentary challenges a cultural stereotype about migration.", exampleTranslation: "يتحدى الفيلم الوثائقي صورة نمطية ثقافية عن الهجرة.", category: "culture and media", tags: ["culture", "representation"], synonyms: ["cultural cliché", "generalisation"] }),
      reviewed({ word: "editorial bias", translation: "تحيز تحريري", pos: "noun", ipa: "/ˌedɪˈtɔːriəl baɪəs/", definition: "a tendency in a publication to present issues in a particular unfair way", example: "Readers should consider possible editorial bias in the report.", exampleTranslation: "ينبغي للقراء أن يضعوا التحيز التحريري المحتمل في التقرير في الحسبان.", category: "culture and media", tags: ["media", "critical reading"], synonyms: ["press bias", "publisher bias"] }),
      reviewed({ word: "public opinion", translation: "الرأي العام", pos: "noun", ipa: "/ˌpʌblɪk əˈpɪnjən/", definition: "the views generally held by people in a society", example: "The campaign used interviews to measure public opinion.", exampleTranslation: "استخدمت الحملة المقابلات لقياس الرأي العام.", category: "culture and media", tags: ["media", "society"], synonyms: ["popular view", "public sentiment"] }),
      reviewed({ word: "visual representation", translation: "تمثيل بصري", pos: "noun", ipa: "/ˈvɪʒuəl ˌreprɪzenˈteɪʃən/", definition: "the way a person, idea, or event is shown through images", example: "The exhibition questions the visual representation of rural life.", exampleTranslation: "يتساءل المعرض عن التمثيل البصري للحياة الريفية.", category: "culture and media", tags: ["art", "media"], synonyms: ["image portrayal", "visual depiction"] }),
      reviewed({ word: "target audience", translation: "الجمهور المستهدف", pos: "noun", ipa: "/ˈtɑːɡɪt ˌɔːdiəns/", definition: "the particular group of people for whom a message or product is intended", example: "The programme was redesigned for a younger target audience.", exampleTranslation: "أُعيد تصميم البرنامج لجمهور مستهدف أصغر سنًا.", category: "culture and media", tags: ["media", "communication"], synonyms: ["intended audience", "target group"] }),
      reviewed({ word: "media narrative", translation: "سردية إعلامية", pos: "noun", ipa: "/ˈmiːdiə ˈnærətɪv/", definition: "a particular way in which media organisations frame and tell a story", example: "The media narrative changed after new evidence emerged.", exampleTranslation: "تغيرت السردية الإعلامية بعد ظهور أدلة جديدة.", category: "culture and media", tags: ["media", "news"], synonyms: ["news narrative", "media framing"] }),
      reviewed({ word: "documentary film", translation: "فيلم وثائقي", pos: "noun", ipa: "/ˌdɒkjəˈmentəri fɪlm/", definition: "a film that presents factual information about real people or events", example: "The documentary film explores the history of the neighbourhood.", exampleTranslation: "يستكشف الفيلم الوثائقي تاريخ الحي.", category: "culture and media", tags: ["film", "culture"], synonyms: ["non-fiction film", "factual film"] }),
      reviewed({ word: "viral sensation", translation: "ظاهرة واسعة الانتشار", pos: "noun", ipa: "/ˈvaɪrəl senˈseɪʃən/", definition: "a piece of content or event that becomes extremely popular online very quickly", example: "The short video became a viral sensation within two days.", exampleTranslation: "أصبح الفيديو القصير ظاهرة واسعة الانتشار خلال يومين.", category: "culture and media", tags: ["media", "internet"], synonyms: ["online phenomenon", "viral hit"] }),
    ],
  },
  C1: {
    u28: [
      reviewed({ word: "empirical finding", translation: "نتيجة تجريبية", pos: "noun", ipa: "/ɪmˈpɪrɪkəl ˈfaɪndɪŋ/", definition: "a conclusion reached from observed or measured evidence", example: "The empirical finding contradicted the original prediction.", exampleTranslation: "ناقضت النتيجة التجريبية التوقع الأصلي.", category: "research and argument", tags: ["research", "evidence"], synonyms: ["observed result", "experimental result"] }),
      reviewed({ word: "evidential basis", translation: "أساس استدلالي", pos: "noun", ipa: "/ˌevɪˈdenʃəl ˈbeɪsɪs/", definition: "the evidence on which a claim, decision, or argument is based", example: "The recommendation has a weak evidential basis.", exampleTranslation: "للتوصية أساس استدلالي ضعيف.", category: "research and argument", tags: ["evidence", "argument"], synonyms: ["evidence base", "supporting basis"] }),
      reviewed({ word: "scholarly consensus", translation: "إجماع أكاديمي", pos: "noun", ipa: "/ˈskɒləli kənˈsensəs/", definition: "the broad agreement reached by specialists in an academic field", example: "The article distinguishes scholarly consensus from personal opinion.", exampleTranslation: "يميز المقال بين الإجماع الأكاديمي والرأي الشخصي.", category: "research and argument", tags: ["research", "academia"], synonyms: ["academic agreement", "expert consensus"] }),
      reviewed({ word: "fallacious reasoning", translation: "استدلال مغالط", pos: "noun", ipa: "/fəˈleɪʃəs ˈriːzənɪŋ/", definition: "a way of reasoning that appears logical but contains a misleading error", example: "The examiner identified fallacious reasoning in the final paragraph.", exampleTranslation: "حدد الممتحن استدلالًا مغالطًا في الفقرة الأخيرة.", category: "research and argument", tags: ["logic", "argument"], synonyms: ["flawed reasoning", "invalid logic"] }),
      reviewed({ word: "conclusive proof", translation: "دليل حاسم", pos: "noun", ipa: "/kənˈkluːsɪv pruːf/", definition: "evidence strong enough to settle a question or remove reasonable doubt", example: "The dataset does not provide conclusive proof of causation.", exampleTranslation: "لا تقدم مجموعة البيانات دليلًا حاسمًا على السببية.", category: "research and argument", tags: ["evidence", "logic"], synonyms: ["decisive evidence", "definitive proof"] }),
      reviewed({ word: "substantiate a claim", translation: "يثبت ادعاءً", pos: "verb", ipa: "/səbˈstænʃieɪ ə kleɪm/", definition: "to support a claim with evidence or convincing information", example: "The researcher used archived records to substantiate the claim.", exampleTranslation: "استخدم الباحث سجلات مؤرشفة لإثبات الادعاء.", category: "research and argument", tags: ["research", "evidence"], synonyms: ["support a claim", "verify an assertion"] }),
      reviewed({ word: "corroborate findings", translation: "يؤكد النتائج بأدلة إضافية", pos: "verb", ipa: "/kəˈrɒbəreɪt ˈfaɪndɪŋz/", definition: "to confirm research results by providing additional evidence", example: "A second study was conducted to corroborate the findings.", exampleTranslation: "أُجريت دراسة ثانية لتأكيد النتائج بأدلة إضافية.", category: "research and argument", tags: ["research", "verification"], synonyms: ["confirm results", "validate findings"] }),
      reviewed({ word: "paradigm shift", translation: "تحول نموذجي", pos: "noun", ipa: "/ˈpærədaɪm ʃɪft/", definition: "a fundamental change in the way a subject is understood or approached", example: "The discovery led to a paradigm shift in climate research.", exampleTranslation: "أدى الاكتشاف إلى تحول نموذجي في أبحاث المناخ.", category: "research and argument", tags: ["research", "theory"], synonyms: ["conceptual revolution", "fundamental change"] }),
    ],
    u29: [
      reviewed({ word: "moral ambiguity", translation: "غموض أخلاقي", pos: "noun", ipa: "/ˈmɒrəl ˌæmbɪˈɡjuːəti/", definition: "a situation in which the right or wrong course of action is not clear", example: "The novel uses moral ambiguity to challenge the reader's judgement.", exampleTranslation: "تستخدم الرواية الغموض الأخلاقي لتحدي حكم القارئ.", category: "society and ethics", tags: ["ethics", "literature"], synonyms: ["ethical uncertainty", "moral complexity"] }),
      reviewed({ word: "social stratification", translation: "التقسيم الطبقي الاجتماعي", pos: "noun", ipa: "/ˌsəʊʃəl ˌstrætɪfɪˈkeɪʃən/", definition: "the division of society into layers based on wealth, status, or power", example: "The study examines how education can reproduce social stratification.", exampleTranslation: "تدرس الدراسة كيف يمكن للتعليم إعادة إنتاج التقسيم الطبقي الاجتماعي.", category: "society and ethics", tags: ["society", "inequality"], synonyms: ["class structure", "social hierarchy"] }),
      reviewed({ word: "systemic inequality", translation: "عدم مساواة بنيوي", pos: "noun", ipa: "/sɪˈstemɪk ˌɪnɪˈkwɒləti/", definition: "inequality produced or maintained by the structures and institutions of society", example: "The report examines systemic inequality in access to healthcare.", exampleTranslation: "يفحص التقرير عدم المساواة البنيوي في الوصول إلى الرعاية الصحية.", category: "society and ethics", tags: ["society", "justice"], synonyms: ["structural inequality", "institutional inequality"] }),
      reviewed({ word: "utilitarian approach", translation: "نهج نفعي", pos: "noun", ipa: "/ˌjuːtɪlɪˈteəriən əˈprəʊtʃ/", definition: "an approach that judges an action by its overall consequences for people's wellbeing", example: "A utilitarian approach may support the policy if it benefits most citizens.", exampleTranslation: "قد يؤيد النهج النفعي السياسة إذا أفادت معظم المواطنين.", category: "society and ethics", tags: ["ethics", "philosophy"], synonyms: ["consequentialist approach", "greatest-good approach"] }),
      reviewed({ word: "civic duty", translation: "واجب مدني", pos: "noun", ipa: "/ˈsɪvɪk ˈdjuːti/", definition: "a responsibility that citizens are expected to fulfil for the good of society", example: "The essay asks whether paying taxes should be viewed as a civic duty.", exampleTranslation: "يسأل المقال عما إذا كان دفع الضرائب ينبغي أن يُنظر إليه بوصفه واجبًا مدنيًا.", category: "society and ethics", tags: ["citizenship", "responsibility"], synonyms: ["civic responsibility", "public obligation"] }),
      reviewed({ word: "egalitarian society", translation: "مجتمع قائم على المساواة", pos: "noun", ipa: "/ɪˌɡælɪˈteəriən səˈsaɪəti/", definition: "a society that aims to minimise differences in status, rights, and opportunities", example: "The policy is presented as a step towards a more egalitarian society.", exampleTranslation: "تُقدَّم السياسة بوصفها خطوة نحو مجتمع أكثر مساواة.", category: "society and ethics", tags: ["society", "equality"], synonyms: ["equal society", "socially equal community"] }),
      reviewed({ word: "marginalized communities", translation: "مجتمعات مهمشة", pos: "noun", ipa: "/ˈmɑːdʒɪnəlaɪzd kəˈmjuːnətiz/", definition: "groups pushed to the edges of society and denied equal access to power or resources", example: "The consultation included representatives of marginalized communities.", exampleTranslation: "شملت المشاورات ممثلين عن المجتمعات المهمشة.", category: "society and ethics", tags: ["society", "inclusion"], synonyms: ["excluded groups", "disadvantaged communities"] }),
      reviewed({ word: "collective responsibility", translation: "مسؤولية جماعية", pos: "noun", ipa: "/kəˌlektɪv rɪˌspɒnsəˈbɪləti/", definition: "a responsibility shared by members of a group or society", example: "Climate policy raises questions about collective responsibility.", exampleTranslation: "تثير سياسة المناخ أسئلة حول المسؤولية الجماعية.", category: "society and ethics", tags: ["ethics", "society"], synonyms: ["shared responsibility", "common obligation"] }),
    ],
  },
};
