// Additional English curriculum units u36-u37 for every CEFR level.
// Deterministic local curriculum data; APIs may enrich it but never generate it.
type Word = { word: string; translation: string; pos: string; example: string; exampleTranslation: string };
type Unit = { id: string; title: string; description: string; words: Word[]; phrases: { phrase: string; translation: string }[]; dialogue: { speaker: string; text: string; translation: string }[]; reading: { title: string; text: string; translation: string } };
const w = (word: string, translation: string, pos: string, example: string, exampleTranslation: string): Word => ({ word, translation, pos, example, exampleTranslation });
const u = (id: string, title: string, description: string, words: Word[]): Unit => ({
  id, title, description, words,
  phrases: words.slice(0, 4).map((item) => ({ phrase: item.example, translation: item.exampleTranslation })),
  dialogue: [0, 1, 2, 3].map((index) => ({ speaker: index % 2 === 0 ? "A" : "B", text: words[index]!.example, translation: words[index]!.exampleTranslation })),
  reading: { title, text: words.slice(0, 4).map((item) => item.example).join(" "), translation: words.slice(0, 4).map((item) => item.exampleTranslation).join(" ") },
});

export const ADDITIONAL_EN_PART7_UNITS: Record<string, Unit[]> = {
  A0: [
    u("u36", "School and Class", "Name classroom objects and talk about school.", [
      w("school", "escuela", "noun", "School starts on Monday.", "La escuela empieza el lunes."), w("classroom", "aula", "noun", "The classroom is bright.", "El aula es luminosa."), w("pen", "bolígrafo", "noun", "The pen is on the table.", "El bolígrafo está sobre la mesa."), w("paper", "papel", "noun", "The paper is white.", "El papel es blanco."), w("teacher", "profesor", "noun", "The teacher speaks slowly.", "El profesor habla despacio."), w("pupil", "alumno", "noun", "The pupil reads a book.", "El alumno lee un libro."), w("learn", "aprender", "verb", "I want to learn Finnish.", "Quiero aprender finés."), w("write", "escribir", "verb", "I write my name.", "Escribo mi nombre."),
    ]),
    u("u37", "The Body and Health", "Name body parts and describe simple sensations.", [
      w("head", "cabeza", "noun", "My head hurts.", "Me duele la cabeza."), w("eye", "ojo", "noun", "The eye is blue.", "El ojo es azul."), w("hand", "mano", "noun", "Wash your hands.", "Lávate las manos."), w("leg", "pierna", "noun", "The leg is strong.", "La pierna es fuerte."), w("mouth", "boca", "noun", "Open your mouth.", "Abre la boca."), w("pain", "dolor", "noun", "I have pain.", "Tengo dolor."), w("rest", "descansar", "verb", "I need to rest.", "Necesito descansar."), w("breathe", "respirar", "verb", "Breathe calmly.", "Respira tranquilamente."),
    ]),
  ],
  A1: [
    u("u36", "Weather and Seasons", "Describe the weather and plan activities.", [
      w("spring", "primavera", "noun", "Spring begins soon.", "La primavera empieza pronto."), w("summer", "verano", "noun", "Summer is warm.", "El verano es cálido."), w("autumn", "otoño", "noun", "In autumn the leaves fall.", "En otoño caen las hojas."), w("winter", "invierno", "noun", "Winter is cold.", "El invierno es frío."), w("snow", "nieve", "noun", "Snow covers the road.", "La nieve cubre la carretera."), w("wind", "viento", "noun", "The wind is strong.", "El viento es fuerte."), w("shine", "brillar", "verb", "The sun is shining.", "El sol brilla."), w("prepare", "prepararse", "verb", "We prepare for rain.", "Nos preparamos para la lluvia."),
    ]),
    u("u37", "The Doctor and Appointments", "Book an appointment and describe common health problems.", [
      w("appointment", "cita", "noun", "I need a doctor's appointment.", "Necesito una cita con el médico."), w("reception", "recepción", "noun", "The reception opens at eight.", "La recepción abre a las ocho."), w("patient", "paciente", "noun", "The patient waits in the room.", "El paciente espera en la sala."), w("symptom", "síntoma", "noun", "The symptom started yesterday.", "El síntoma empezó ayer."), w("medicine", "medicina", "noun", "The medicine helps with the pain.", "La medicina ayuda con el dolor."), w("fever", "fiebre", "noun", "I have a fever.", "Tengo fiebre."), w("book", "reservar", "verb", "I want to book an appointment.", "Quiero reservar una cita."), w("get better", "mejorarse", "verb", "I hope to get better soon.", "Espero mejorar pronto."),
    ]),
  ],
  A2: [
    u("u36", "Housing and Neighbourhoods", "Describe a home and discuss a neighbourhood.", [
      w("apartment", "apartamento", "noun", "The apartment is near the centre.", "El apartamento está cerca del centro."), w("rent", "alquiler", "noun", "The rent is paid monthly.", "El alquiler se paga mensualmente."), w("neighbour", "vecino", "noun", "The neighbour often helps.", "El vecino suele ayudar."), w("balcony", "balcón", "noun", "You can see the park from the balcony.", "Se puede ver el parque desde el balcón."), w("lift", "ascensor", "noun", "The lift does not work.", "El ascensor no funciona."), w("noise", "ruido", "noun", "Noise is disturbing at night.", "El ruido molesta por la noche."), w("move", "mudarse", "verb", "We are moving to a new apartment.", "Nos mudamos a un apartamento nuevo."), w("repair", "reparar", "verb", "The owner repairs the door.", "El propietario repara la puerta."),
    ]),
    u("u37", "Services and Forms", "Handle everyday tasks at an office or service desk.", [
      w("service", "servicio", "noun", "The service is fast.", "El servicio es rápido."), w("form", "formulario", "noun", "Fill in this form.", "Rellena este formulario."), w("certificate", "certificado", "noun", "I need a new certificate.", "Necesito un certificado nuevo."), w("application", "solicitud", "noun", "The application is ready.", "La solicitud está lista."), w("office", "oficina", "noun", "The office closes at four.", "La oficina cierra a las cuatro."), w("number", "número", "noun", "Take a waiting number.", "Toma un número de espera."), w("request", "solicitar", "verb", "Can I request help?", "¿Puedo solicitar ayuda?"), w("fill in", "rellenar", "verb", "I fill in the application online.", "Relleno la solicitud en línea."),
    ]),
  ],
  B1: [
    u("u36", "Study and Problem Solving", "Describe study methods and solve learning challenges.", [
      w("task", "tarea", "noun", "The task must be submitted tomorrow.", "La tarea debe entregarse mañana."), w("solution", "solución", "noun", "We found a good solution.", "Encontramos una buena solución."), w("challenge", "desafío", "noun", "The new topic is a challenge.", "El tema nuevo es un desafío."), w("skill", "habilidad", "noun", "Language skill develops through practice.", "La habilidad lingüística se desarrolla con la práctica."), w("feedback", "comentarios", "noun", "The teacher gives useful feedback.", "El profesor da comentarios útiles."), w("notes", "apuntes", "noun", "I take notes during the lecture.", "Tomo apuntes durante la conferencia."), w("solve", "resolver", "verb", "We try to solve the problem.", "Intentamos resolver el problema."), w("apply", "aplicar", "verb", "I apply the rule in an example.", "Aplico la regla en un ejemplo."),
    ]),
    u("u37", "Culture and Celebrations", "Talk about cultural customs and shared celebrations.", [
      w("celebration", "celebración", "noun", "The celebration begins in the evening.", "La celebración empieza por la tarde."), w("custom", "costumbre", "noun", "This custom is old.", "Esta costumbre es antigua."), w("tradition", "tradición", "noun", "Tradition connects generations.", "La tradición conecta generaciones."), w("guest", "invitado", "noun", "The guests arrive soon.", "Los invitados llegan pronto."), w("gift", "regalo", "noun", "The gift is beautifully wrapped.", "El regalo está envuelto con cuidado."), w("music", "música", "noun", "Music can be heard in the street.", "Se oye música en la calle."), w("celebrate", "celebrar", "verb", "We celebrate graduation.", "Celebramos la graduación."), w("respect", "respetar", "verb", "We respect the local custom.", "Respetamos la costumbre local."),
    ]),
  ],
  B2: [
    u("u36", "Economy and Entrepreneurship", "Discuss companies, markets, and financial risks.", [
      w("company", "empresa", "noun", "The company is growing quickly.", "La empresa crece rápidamente."), w("turnover", "facturación", "noun", "Turnover increased last year.", "La facturación aumentó el año pasado."), w("customer", "cliente", "noun", "The customer is waiting for an answer.", "El cliente espera una respuesta."), w("competition", "competencia", "noun", "Competition is intense.", "La competencia es intensa."), w("investment", "inversión", "noun", "An investment requires planning.", "Una inversión requiere planificación."), w("debt", "deuda", "noun", "The debt must be repaid.", "La deuda debe devolverse."), w("establish", "fundar", "verb", "She established a new company.", "Ella fundó una empresa nueva."), w("increase", "aumentar", "verb", "The company increases production.", "La empresa aumenta la producción."),
    ]),
    u("u37", "Science and Innovation", "Explain scientific observations and new solutions.", [
      w("invention", "invento", "noun", "The invention changed daily life.", "El invento cambió la vida diaria."), w("research", "investigación", "noun", "The research takes three years.", "La investigación dura tres años."), w("laboratory", "laboratorio", "noun", "The laboratory is well equipped.", "El laboratorio está bien equipado."), w("data", "datos", "noun", "The data contains thousands of answers.", "Los datos contienen miles de respuestas."), w("theory", "teoría", "noun", "The theory explains the observation.", "La teoría explica la observación."), w("application", "aplicación", "noun", "The application saves energy.", "La aplicación ahorra energía."), w("develop", "desarrollar", "verb", "The team develops a new method.", "El equipo desarrolla un método nuevo."), w("prove", "demostrar", "verb", "The results do not yet prove the claim.", "Los resultados aún no demuestran la afirmación."),
    ]),
  ],
  C1: [
    u("u36", "Media and Rhetoric", "Analyse arguments, persuasion, and public debate.", [
      w("rhetoric", "retórica", "noun", "Rhetoric influences the audience.", "La retórica influye en el público."), w("argument", "argumento", "noun", "The argument is based on evidence.", "El argumento se basa en pruebas."), w("audience", "público", "noun", "The audience asked difficult questions.", "El público hizo preguntas difíciles."), w("framing", "encuadre", "noun", "Framing changes the interpretation of the topic.", "El encuadre cambia la interpretación del tema."), w("headline", "titular", "noun", "The headline simplified the issue.", "El titular simplificó el asunto."), w("source criticism", "crítica de fuentes", "noun", "Source criticism is part of research.", "La crítica de fuentes forma parte de la investigación."), w("persuade", "persuadir", "verb", "The writer persuades the reader.", "El escritor persuade al lector."), w("exaggerate", "exagerar", "verb", "The headline exaggerates the risk.", "El titular exagera el riesgo."),
    ]),
    u("u37", "Migration and Belonging", "Consider migration, integration, and belonging to a community.", [
      w("migration", "migración", "noun", "Migration changes the structure of a city.", "La migración cambia la estructura de una ciudad."), w("immigrant", "inmigrante", "noun", "The immigrant builds a new life.", "El inmigrante construye una vida nueva."), w("integration", "integración", "noun", "Integration takes time.", "La integración lleva tiempo."), w("belonging", "pertenencia", "noun", "Belonging strengthens security.", "La pertenencia fortalece la seguridad."), w("prejudice", "prejuicio", "noun", "Prejudice can prevent cooperation.", "El prejuicio puede impedir la cooperación."), w("diversity", "diversidad", "noun", "Diversity enriches the community.", "La diversidad enriquece la comunidad."), w("adapt", "adaptarse", "verb", "People adapt to a new environment.", "Las personas se adaptan a un entorno nuevo."), w("include", "incluir", "verb", "Decisions should include residents.", "Las decisiones deberían incluir a los residentes."),
    ]),
  ],
  C2: [
    u("u36", "Language and Philosophy", "Reflect on language, meaning, and interpretation.", [
      w("meaning", "significado", "noun", "Meaning emerges in context.", "El significado surge en el contexto."), w("reference", "referencia", "noun", "A reference connects the text to history.", "Una referencia conecta el texto con la historia."), w("concept", "concepto", "noun", "A concept requires a precise definition.", "Un concepto requiere una definición precisa."), w("ambiguity", "ambigüedad", "noun", "Ambiguity can be intentional.", "La ambigüedad puede ser intencionada."), w("interpretation", "interpretación", "noun", "Interpretation depends on the reader.", "La interpretación depende del lector."), w("truth value", "valor de verdad", "noun", "A sentence can have a contested truth value.", "Una oración puede tener un valor de verdad discutido."), w("define", "definir", "verb", "The writer redefines the concept.", "El escritor redefine el concepto."), w("signify", "significar", "verb", "A word can signify different things.", "Una palabra puede significar cosas diferentes."),
    ]),
    u("u37", "Global Governance", "Evaluate international institutions and shared solutions.", [
      w("governance", "gobernanza", "noun", "Global governance requires cooperation.", "La gobernanza mundial requiere cooperación."), w("institution", "institución", "noun", "An institution maintains rules.", "Una institución mantiene las normas."), w("treaty", "tratado", "noun", "The treaty binds states.", "El tratado obliga a los Estados."), w("sovereignty", "soberanía", "noun", "Sovereignty limits collective decision-making.", "La soberanía limita la toma de decisiones colectiva."), w("accountability", "rendición de cuentas", "noun", "Accountability increases trust.", "La rendición de cuentas aumenta la confianza."), w("diplomacy", "diplomacia", "noun", "Diplomacy can prevent conflict.", "La diplomacia puede prevenir conflictos."), w("coordinate", "coordinar", "verb", "Countries coordinate their actions.", "Los países coordinan sus acciones."), w("ratify", "ratificar", "verb", "Parliament ratifies the treaty.", "El Parlamento ratifica el tratado."),
    ]),
  ],
};
