import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/**
 * Reviewed vocabulary for the six existing B1/B2/C1 u6 and u7 units with
 * the smallest remaining banks. This bank contains vocabulary only; it never
 * creates, renames, removes, or duplicates a curriculum unit or lesson.
 */
export const ENGLISH_B1_B2_C1_U6_U7_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u6: [
      reviewed({ word: "inbox rule", translation: "قاعدة صندوق الوارد", pos: "noun", ipa: "/ˈɪnbɑːks ruːl/", definition: "an instruction that automatically sorts or manages incoming email", example: "I created an inbox rule to move newsletters into a separate folder.", exampleTranslation: "أنشأت قاعدة لصندوق الوارد لنقل النشرات إلى مجلد منفصل.", category: "internet and email", tags: ["technology", "email"], synonyms: ["mail filter rule", "email sorting rule"] }),
      reviewed({ word: "attachment preview", translation: "معاينة المرفق", pos: "noun", ipa: "/əˈtætʃmənt ˈpriːvjuː/", definition: "a view of a file attached to an email before it is downloaded or opened", example: "The attachment preview showed that the document had the wrong version.", exampleTranslation: "أظهرت معاينة المرفق أن المستند كان بالإصدار الخطأ.", category: "internet and email", tags: ["technology", "email"], synonyms: ["file preview", "email attachment view"] }),
      reviewed({ word: "video call", translation: "مكالمة فيديو", pos: "noun", ipa: "/ˈvɪdioʊ kɔːl/", definition: "a call in which participants communicate using live video and sound", example: "We arranged a video call because the team works in different cities.", exampleTranslation: "رتبنا مكالمة فيديو لأن الفريق يعمل في مدن مختلفة.", category: "internet and email", tags: ["technology", "communication"], synonyms: ["video conference", "online call"] }),
      reviewed({ word: "user account", translation: "حساب المستخدم", pos: "noun", ipa: "/ˈjuːzər əˌkaʊnt/", definition: "a personal record that gives someone access to an online service", example: "The service asked me to confirm my email before activating the user account.", exampleTranslation: "طلبت الخدمة مني تأكيد بريدي قبل تفعيل حساب المستخدم.", category: "internet and email", tags: ["technology", "accounts"], synonyms: ["online account", "member account"] }),
      reviewed({ word: "password reset", translation: "إعادة تعيين كلمة المرور", pos: "noun", ipa: "/ˈpæswɜːrd ˌriːset/", definition: "the process of creating a new password after the old one is forgotten or compromised", example: "The password reset link expired before I could use it.", exampleTranslation: "انتهت صلاحية رابط إعادة تعيين كلمة المرور قبل أن أتمكن من استخدامه.", category: "internet and email", tags: ["technology", "security"], synonyms: ["password recovery", "credential reset"] }),
      reviewed({ word: "two-factor authentication", translation: "المصادقة الثنائية", pos: "noun", ipa: "/ˌtuː fæktər ɔːˌθentɪˈkeɪʃən/", definition: "a security process requiring two different forms of proof of identity", example: "Two-factor authentication protected the account even after the password was exposed.", exampleTranslation: "حمت المصادقة الثنائية الحساب حتى بعد انكشاف كلمة المرور.", category: "internet and email", tags: ["technology", "security"], synonyms: ["two-step verification", "2FA"] }),
      reviewed({ word: "cloud storage", translation: "تخزين سحابي", pos: "noun", ipa: "/ˈklaʊd ˌstɔːrɪdʒ/", definition: "a service that stores files on remote internet-connected computers", example: "Cloud storage made it easier to share the presentation with the whole class.", exampleTranslation: "جعل التخزين السحابي مشاركة العرض مع الصف كله أسهل.", category: "internet and email", tags: ["technology", "files"], synonyms: ["online storage", "remote file storage"] }),
      reviewed({ word: "phishing attempt", translation: "محاولة تصيد احتيالي", pos: "noun", ipa: "/ˈfɪʃɪŋ əˌtempt/", definition: "an effort to trick someone into revealing private information through a false message or website", example: "The strange link was a phishing attempt, so she reported the message.", exampleTranslation: "كان الرابط الغريب محاولة تصيد احتيالي، فأبلغت عن الرسالة.", category: "internet and email", tags: ["technology", "security"], synonyms: ["online scam attempt", "fraudulent message"] }),
    ],
    u7: [
      reviewed({ word: "traditional craft", translation: "حرفة تقليدية", pos: "noun", ipa: "/trəˈdɪʃənəl kræft/", definition: "a skill of making objects that is passed through a culture or community", example: "The museum offers workshops in a traditional craft from the region.", exampleTranslation: "يقدم المتحف ورشًا في حرفة تقليدية من المنطقة.", category: "tradition and custom", tags: ["culture", "community"], synonyms: ["heritage craft", "traditional handicraft"] }),
      reviewed({ word: "ritual practice", translation: "ممارسة طقسية", pos: "noun", ipa: "/ˈrɪtʃuəl ˌpræktɪs/", definition: "a repeated action with a recognised cultural, social, or religious meaning", example: "The ritual practice marks the beginning of the harvest season.", exampleTranslation: "تعلن الممارسة الطقسية بداية موسم الحصاد.", category: "tradition and custom", tags: ["culture", "rituals"], synonyms: ["ceremonial practice", "customary ritual"] }),
      reviewed({ word: "family custom", translation: "عادة عائلية", pos: "noun", ipa: "/ˈfæməli ˌkʌstəm/", definition: "a tradition followed by members of one family", example: "Cooking together on the first evening of the holiday is a family custom.", exampleTranslation: "يعد الطبخ معًا في أول مساء من العطلة عادة عائلية.", category: "tradition and custom", tags: ["family", "culture"], synonyms: ["family tradition", "household custom"] }),
      reviewed({ word: "oral tradition", translation: "تقليد شفهي", pos: "noun", ipa: "/ˈɔːrəl trəˌdɪʃən/", definition: "stories, knowledge, or beliefs passed from one generation to another by speaking", example: "The song survives through an oral tradition rather than written records.", exampleTranslation: "تستمر الأغنية بفضل تقليد شفهي لا السجلات المكتوبة.", category: "tradition and custom", tags: ["culture", "language"], synonyms: ["spoken tradition", "oral heritage"] }),
      reviewed({ word: "intergenerational knowledge", translation: "معرفة متوارثة بين الأجيال", pos: "noun", ipa: "/ˌɪntərˌdʒenəˈreɪʃənəl ˈnɑːlɪdʒ/", definition: "knowledge shared between older and younger generations", example: "The project records intergenerational knowledge about local plants.", exampleTranslation: "يوثق المشروع المعرفة المتوارثة بين الأجيال حول النباتات المحلية.", category: "tradition and custom", tags: ["culture", "community"], synonyms: ["inherited knowledge", "shared generational knowledge"] }),
      reviewed({ word: "local festival", translation: "مهرجان محلي", pos: "noun", ipa: "/ˈloʊkəl ˌfestɪvəl/", definition: "a public celebration connected with a particular place or community", example: "The local festival attracts visitors with music, food, and street theatre.", exampleTranslation: "يجذب المهرجان المحلي الزوار بالموسيقى والطعام ومسرح الشارع.", category: "tradition and custom", tags: ["culture", "events"], synonyms: ["community festival", "regional celebration"] }),
      reviewed({ word: "regional cuisine", translation: "مطبخ إقليمي", pos: "noun", ipa: "/ˈriːdʒənəl kwɪˈziːn/", definition: "the characteristic food and cooking of a particular area", example: "The restaurant introduces visitors to regional cuisine and seasonal ingredients.", exampleTranslation: "يعرّف المطعم الزوار بالمطبخ الإقليمي والمكونات الموسمية.", category: "tradition and custom", tags: ["culture", "food"], synonyms: ["local cuisine", "regional food"] }),
      reviewed({ word: "community heritage", translation: "تراث مجتمعي", pos: "noun", ipa: "/kəˈmjuːnəti ˈherɪtɪdʒ/", definition: "the places, practices, and memories valued and protected by a community", example: "Young volunteers helped preserve the community heritage of the old quarter.", exampleTranslation: "ساعد متطوعون شباب في الحفاظ على التراث المجتمعي للحي القديم.", category: "tradition and custom", tags: ["culture", "community"], synonyms: ["shared heritage", "local heritage"] }),
    ],
  },
  B2: {
    u6: [
      reviewed({ word: "carbon footprint", translation: "بصمة كربونية", pos: "noun", ipa: "/ˈkɑːrbən ˌfʊtprɪnt/", definition: "the total amount of greenhouse gases produced by a person, activity, or organisation", example: "The company is measuring its carbon footprint before setting reduction targets.", exampleTranslation: "تقيس الشركة بصمتها الكربونية قبل تحديد أهداف الخفض.", category: "climate and recycling", tags: ["environment", "climate"], synonyms: ["carbon impact", "greenhouse-gas footprint"] }),
      reviewed({ word: "renewable energy source", translation: "مصدر طاقة متجددة", pos: "noun", ipa: "/rɪˈnuːəbəl ˈenərdʒi sɔːrs/", definition: "a source of energy that is naturally replaced, such as wind or sunlight", example: "The island depends on a renewable energy source during the summer.", exampleTranslation: "تعتمد الجزيرة على مصدر طاقة متجددة خلال الصيف.", category: "climate and recycling", tags: ["environment", "energy"], synonyms: ["clean energy source", "sustainable energy source"] }),
      reviewed({ word: "climate adaptation", translation: "التكيف المناخي", pos: "noun", ipa: "/ˈklaɪmət ˌædæpˈteɪʃən/", definition: "changes made to reduce harm from the effects of a changing climate", example: "Climate adaptation includes protecting homes from rising flood risk.", exampleTranslation: "يشمل التكيف المناخي حماية المنازل من ازدياد خطر الفيضانات.", category: "climate and recycling", tags: ["environment", "policy"], synonyms: ["climate adjustment", "adaptation to climate change"] }),
      reviewed({ word: "urban heat island", translation: "جزيرة حرارية حضرية", pos: "noun", ipa: "/ˌɜːrbən ˈhiːt ˌaɪlənd/", definition: "an urban area that is hotter than nearby rural areas because buildings and roads retain heat", example: "Trees can reduce the urban heat island effect in dense neighbourhoods.", exampleTranslation: "يمكن للأشجار تقليل أثر الجزيرة الحرارية الحضرية في الأحياء المكتظة.", category: "climate and recycling", tags: ["environment", "cities"], synonyms: ["urban heat effect", "city heat island"] }),
      reviewed({ word: "waste reduction", translation: "تقليل النفايات", pos: "noun", ipa: "/ˈweɪst rɪˌdʌkʃən/", definition: "the practice of producing and throwing away less material", example: "Waste reduction begins when shops avoid unnecessary packaging.", exampleTranslation: "يبدأ تقليل النفايات عندما تتجنب المتاجر التغليف غير الضروري.", category: "climate and recycling", tags: ["environment", "recycling"], synonyms: ["waste minimisation", "cutting waste"] }),
      reviewed({ word: "wildlife conservation", translation: "حماية الحياة البرية", pos: "noun", ipa: "/ˈwaɪldlaɪf ˌkɑːnsərˈveɪʃən/", definition: "the protection of wild animals, plants, and the places where they live", example: "Wildlife conservation depends on protecting connected habitats.", exampleTranslation: "تعتمد حماية الحياة البرية على حماية المواطن المترابطة.", category: "climate and recycling", tags: ["environment", "nature"], synonyms: ["wildlife protection", "nature conservation"] }),
      reviewed({ word: "circular economy", translation: "اقتصاد دائري", pos: "noun", ipa: "/ˌsɜːrkjələr ɪˈkɑːnəmi/", definition: "an economic system designed to reuse materials and avoid unnecessary waste", example: "A circular economy keeps products and materials in use for as long as possible.", exampleTranslation: "يبقي الاقتصاد الدائري المنتجات والمواد قيد الاستخدام لأطول مدة ممكنة.", category: "climate and recycling", tags: ["environment", "economy"], synonyms: ["closed-loop economy", "circular production model"] }),
      reviewed({ word: "green transport", translation: "نقل أخضر", pos: "noun", ipa: "/ɡriːn ˈtrænspɔːrt/", definition: "transport that produces relatively little pollution or greenhouse gas", example: "Investment in green transport can make clean travel more affordable.", exampleTranslation: "يمكن للاستثمار في النقل الأخضر أن يجعل السفر النظيف أقل تكلفة.", category: "climate and recycling", tags: ["environment", "transport"], synonyms: ["low-carbon transport", "sustainable transport"] }),
    ],
    u7: [
      reviewed({ word: "electoral reform", translation: "إصلاح انتخابي", pos: "noun", ipa: "/ɪˈlektərəl rɪˌfɔːrm/", definition: "a change intended to improve the way elections are organised or conducted", example: "The committee proposed electoral reform to make representation more proportional.", exampleTranslation: "اقترحت اللجنة إصلاحًا انتخابيًا لجعل التمثيل أكثر تناسبًا.", category: "government and parliament", tags: ["politics", "elections"], synonyms: ["election reform", "electoral change"] }),
      reviewed({ word: "coalition government", translation: "حكومة ائتلافية", pos: "noun", ipa: "/koʊəˈlɪʃən ˈɡʌvərnmənt/", definition: "a government formed by two or more political parties working together", example: "The coalition government had to negotiate a common programme.", exampleTranslation: "اضطرت الحكومة الائتلافية إلى التفاوض على برنامج مشترك.", category: "government and parliament", tags: ["politics", "government"], synonyms: ["coalition administration", "multi-party government"] }),
      reviewed({ word: "constituency boundary", translation: "حدود الدائرة الانتخابية", pos: "noun", ipa: "/kənˈstɪtʃuənsi ˌbaʊndəri/", definition: "the geographical limit of an area represented by an elected official", example: "The review may change the constituency boundary before the next election.", exampleTranslation: "قد تغير المراجعة حدود الدائرة الانتخابية قبل الانتخابات القادمة.", category: "government and parliament", tags: ["politics", "elections"], synonyms: ["electoral boundary", "district boundary"] }),
      reviewed({ word: "legislative committee", translation: "لجنة تشريعية", pos: "noun", ipa: "/ˈledʒɪsleɪtɪv kəˌmɪti/", definition: "a group in a parliament that examines proposed laws or public policy", example: "The legislative committee invited experts to comment on the bill.", exampleTranslation: "دعت اللجنة التشريعية خبراء للتعليق على مشروع القانون.", category: "government and parliament", tags: ["politics", "law"], synonyms: ["parliamentary committee", "law-making committee"] }),
      reviewed({ word: "civic consultation", translation: "مشاورة مدنية", pos: "noun", ipa: "/ˈsɪvɪk ˌkɑːnsəlˈteɪʃən/", definition: "a process of asking residents and civic groups for views before a public decision", example: "The city opened a civic consultation before redesigning the central square.", exampleTranslation: "فتحت المدينة مشاورة مدنية قبل إعادة تصميم الساحة المركزية.", category: "government and parliament", tags: ["politics", "community"], synonyms: ["community consultation", "civic review"] }),
      reviewed({ word: "civil liberties", translation: "الحريات المدنية", pos: "noun", ipa: "/ˌsɪvəl ˈlɪbərtiz/", definition: "basic individual freedoms protected from unjustified government interference", example: "The court considered whether the new measure threatened civil liberties.", exampleTranslation: "نظرت المحكمة فيما إذا كان الإجراء الجديد يهدد الحريات المدنية.", category: "government and parliament", tags: ["politics", "rights"], synonyms: ["individual freedoms", "civil rights and freedoms"] }),
      reviewed({ word: "constitutional amendment", translation: "تعديل دستوري", pos: "noun", ipa: "/ˌkɑːnstəˈtuːʃənəl əˈmendmənt/", definition: "an official change to a constitution", example: "The constitutional amendment requires approval by both houses of parliament.", exampleTranslation: "يتطلب التعديل الدستوري موافقة مجلسي البرلمان.", category: "government and parliament", tags: ["politics", "law"], synonyms: ["constitutional change", "amendment to the constitution"] }),
      reviewed({ word: "voter turnout", translation: "نسبة إقبال الناخبين", pos: "noun", ipa: "/ˈvoʊtər ˌtɜːrnaʊt/", definition: "the proportion of eligible voters who take part in an election", example: "Voter turnout was higher in districts where registration was made easier.", exampleTranslation: "كانت نسبة إقبال الناخبين أعلى في الدوائر التي أصبح التسجيل فيها أسهل.", category: "government and parliament", tags: ["politics", "elections"], synonyms: ["electoral participation", "voting participation rate"] }),
    ],
  },
  C1: {
    u6: [
      reviewed({ word: "market differentiator", translation: "عنصر تمييز سوقي", pos: "noun", ipa: "/ˈmɑːrkɪt ˌdɪfəˈrenʃieɪtər/", definition: "a feature that makes a product or organisation distinct from its competitors", example: "Fast repair service became the company’s strongest market differentiator.", exampleTranslation: "أصبحت خدمة الإصلاح السريع أقوى عنصر تمييز سوقي للشركة.", category: "result and strategy", tags: ["business", "strategy"], synonyms: ["competitive differentiator", "distinctive market feature"] }),
      reviewed({ word: "sector presence", translation: "الحضور في القطاع", pos: "noun", ipa: "/ˈsektər ˈprezəns/", definition: "the extent to which an organisation is established and visible in a particular market sector", example: "The partnership strengthened the firm’s sector presence in smaller cities.", exampleTranslation: "عززت الشراكة حضور الشركة في القطاع في المدن الأصغر.", category: "result and strategy", tags: ["business", "markets"], synonyms: ["market position", "presence in the sector"] }),
      reviewed({ word: "strategic priority", translation: "أولوية استراتيجية", pos: "noun", ipa: "/strəˈtiːdʒɪk praɪˈɔːrəti/", definition: "an important long-term concern that guides an organisation’s decisions and resources", example: "Improving access became a strategic priority for the organisation.", exampleTranslation: "أصبح تحسين الوصول أولوية استراتيجية للمنظمة.", category: "result and strategy", tags: ["business", "planning"], synonyms: ["strategic focus", "priority goal"] }),
      reviewed({ word: "performance indicator", translation: "مؤشر أداء", pos: "noun", ipa: "/pərˈfɔːrməns ˌɪndɪˈkeɪtər/", definition: "a measurable sign used to evaluate progress or success", example: "The team selected one performance indicator for each strategic objective.", exampleTranslation: "اختار الفريق مؤشر أداء واحدًا لكل هدف استراتيجي.", category: "result and strategy", tags: ["business", "measurement"], synonyms: ["success measure", "performance metric"] }),
      reviewed({ word: "risk threshold", translation: "عتبة المخاطر", pos: "noun", ipa: "/ˈrɪsk ˌθreʃhoʊld/", definition: "the level of risk at which an organisation must take action or reconsider a decision", example: "The new risk threshold triggered a review of the investment plan.", exampleTranslation: "أطلقت عتبة المخاطر الجديدة مراجعة لخطة الاستثمار.", category: "result and strategy", tags: ["business", "risk"], synonyms: ["risk limit", "risk tolerance level"] }),
      reviewed({ word: "resource allocation", translation: "تخصيص الموارد", pos: "noun", ipa: "/ˈriːsɔːrs ˌæləˈkeɪʃən/", definition: "the process of deciding how money, people, or time should be distributed", example: "Transparent resource allocation made the priorities easier to defend.", exampleTranslation: "جعل تخصيص الموارد بشفافية الدفاع عن الأولويات أسهل.", category: "result and strategy", tags: ["business", "planning"], synonyms: ["resource distribution", "allocation of resources"] }),
      reviewed({ word: "scenario planning", translation: "تخطيط السيناريوهات", pos: "noun", ipa: "/səˈnɑːrioʊ ˌplænɪŋ/", definition: "a method of preparing for several possible future situations", example: "Scenario planning helped the organisation prepare for supply disruptions.", exampleTranslation: "ساعد تخطيط السيناريوهات المنظمة على الاستعداد لتعطل الإمدادات.", category: "result and strategy", tags: ["business", "planning"], synonyms: ["contingency planning", "future-scenario analysis"] }),
      reviewed({ word: "long-term viability", translation: "الجدوى طويلة الأجل", pos: "noun", ipa: "/ˌlɔːŋ tɜːrm ˌvaɪəˈbɪləti/", definition: "the ability of a plan, organisation, or system to remain successful over time", example: "The review questioned the long-term viability of the funding model.", exampleTranslation: "شككت المراجعة في الجدوى طويلة الأجل لنموذج التمويل.", category: "result and strategy", tags: ["business", "evaluation"], synonyms: ["long-term sustainability", "future viability"] }),
    ],
    u7: [
      reviewed({ word: "research finding", translation: "نتيجة بحثية", pos: "noun", ipa: "/rɪˈsɜːrtʃ ˌfaɪndɪŋ/", definition: "a result or conclusion produced by a research study", example: "The research finding supports the theory but does not prove it conclusively.", exampleTranslation: "تدعم النتيجة البحثية النظرية، لكنها لا تثبتها بشكل قاطع.", category: "hypothesis and experiment", tags: ["research", "evidence"], synonyms: ["study result", "research result"] }),
      reviewed({ word: "experimental variable", translation: "متغير تجريبي", pos: "noun", ipa: "/ɪkˌsperɪˈmentəl ˈveriəbəl/", definition: "a factor in an experiment that can change or be measured", example: "The researchers changed one experimental variable while keeping the others constant.", exampleTranslation: "غير الباحثون متغيرًا تجريبيًا واحدًا مع إبقاء المتغيرات الأخرى ثابتة.", category: "hypothesis and experiment", tags: ["research", "science"], synonyms: ["study variable", "experimental factor"] }),
      reviewed({ word: "replicate a study", translation: "يكرر دراسة", pos: "verb", ipa: "/ˈreplɪkeɪt ə ˌstʌdi/", definition: "to repeat a research study to see whether similar results are obtained", example: "A second team tried to replicate the study with a larger sample.", exampleTranslation: "حاول فريق ثانٍ تكرار الدراسة بعينة أكبر.", category: "hypothesis and experiment", tags: ["research", "verification"], synonyms: ["repeat an experiment", "reproduce a study"] }),
      reviewed({ word: "peer review process", translation: "عملية مراجعة الأقران", pos: "noun", ipa: "/ˌpɪr rɪˈvjuː ˌprɑːses/", definition: "the assessment of research by other specialists before publication", example: "The peer review process identified a weakness in the sampling method.", exampleTranslation: "حددت عملية مراجعة الأقران ضعفًا في طريقة أخذ العينات.", category: "hypothesis and experiment", tags: ["research", "publication"], synonyms: ["scholarly review", "expert review process"] }),
      reviewed({ word: "research hypothesis", translation: "فرضية بحثية", pos: "noun", ipa: "/rɪˈsɜːrtʃ haɪˈpɑːθəsɪs/", definition: "a testable proposed explanation for an observed pattern or question", example: "The research hypothesis predicted that sleep would affect memory performance.", exampleTranslation: "تنبأت الفرضية البحثية بأن النوم سيؤثر في أداء الذاكرة.", category: "hypothesis and experiment", tags: ["research", "science"], synonyms: ["testable hypothesis", "study hypothesis"] }),
      reviewed({ word: "field observation", translation: "ملاحظة ميدانية", pos: "noun", ipa: "/fiːld ˌɑːbzərˈveɪʃən/", definition: "the systematic recording of behaviour or conditions in a real-world setting", example: "Field observation revealed how people actually used the public space.", exampleTranslation: "كشفت الملاحظة الميدانية كيف استخدم الناس المكان العام فعليًا.", category: "hypothesis and experiment", tags: ["research", "observation"], synonyms: ["on-site observation", "real-world observation"] }),
      reviewed({ word: "sampling protocol", translation: "بروتوكول أخذ العينات", pos: "noun", ipa: "/ˈsæmplɪŋ ˌproʊtəkɑːl/", definition: "a documented procedure for selecting, collecting, and handling research samples", example: "The laboratory published its sampling protocol to improve reproducibility.", exampleTranslation: "نشرت المختبرات بروتوكول أخذ العينات لتحسين قابلية تكرار النتائج.", category: "hypothesis and experiment", tags: ["research", "statistics"], synonyms: ["sampling procedure", "sample collection protocol"] }),
      reviewed({ word: "methodological limitation", translation: "قيد منهجي", pos: "noun", ipa: "/ˌmeθədəˈlɑːdʒɪkəl ˌlɪmɪˈteɪʃən/", definition: "a feature of a research method that restricts how confidently results can be interpreted", example: "The authors acknowledged the methodological limitation in the final section.", exampleTranslation: "أقر المؤلفون بالقيد المنهجي في القسم الأخير.", category: "hypothesis and experiment", tags: ["research", "evaluation"], synonyms: ["method limitation", "research constraint"] }),
    ],
  },
};
