// Additional Finnish curriculum units u38-u39 for every CEFR level.
// Deterministic local curriculum data; APIs may enrich it but never generate it.
type Word = { word: string; translation: string; pos: string; example: string; exampleTranslation: string };
type Unit = { id: string; title: string; description: string; words: Word[]; phrases: { phrase: string; translation: string }[]; dialogue: { speaker: string; text: string; translation: string }[]; reading: { title: string; text: string; translation: string } };
const w = (word: string, translation: string, pos: string, example: string, exampleTranslation: string): Word => ({ word, translation, pos, example, exampleTranslation });
const u = (id: string, title: string, description: string, words: Word[]): Unit => ({
  id, title, description, words,
  phrases: words.slice(0, 4).map((item) => ({ phrase: item.example, translation: item.exampleTranslation })),
  dialogue: [0, 1, 2, 3].map((index) => ({ speaker: index % 2 === 0 ? "A" : "B", text: words[index]!.example, translation: words[index]!.exampleTranslation })),
  reading: { title, text: words.slice(0, 4).map((item) => item.example).join(" "), translation: words.slice(0, 4).map((item) => item.exampleTranslation).join(" ") },
});

export const ADDITIONAL_FI_PART8_UNITS: Record<string, Unit[]> = {
  A0: [
    u("u38", "Ruoka ja keittiö", "Nimeä tavallisia ruokia ja keittiön esineitä.", [
      w("leipä", "bread", "noun", "Leipä on pöydällä.", "The bread is on the table."), w("maito", "milk", "noun", "Juon maitoa.", "I drink milk."), w("omena", "apple", "noun", "Omena on punainen.", "The apple is red."), w("keitto", "soup", "noun", "Keitto on kuumaa.", "The soup is hot."), w("lautanen", "plate", "noun", "Lautanen on puhdas.", "The plate is clean."), w("lusikka", "spoon", "noun", "Lusikka on kupissa.", "The spoon is in the cup."), w("syödä", "eat", "verb", "Haluan syödä.", "I want to eat."), w("juoda", "drink", "verb", "Juon vettä.", "I drink water."),
    ]),
    u("u39", "Koti ja arki", "Kuvaile kotia ja tavallisia päivittäisiä toimia.", [
      w("koti", "home", "noun", "Koti on lämmin.", "The home is warm."), w("huone", "room", "noun", "Huone on pieni.", "The room is small."), w("ovi", "door", "noun", "Ovi on auki.", "The door is open."), w("ikkuna", "window", "noun", "Ikkuna on kiinni.", "The window is closed."), w("tuoli", "chair", "noun", "Tuoli on keittiössä.", "The chair is in the kitchen."), w("sänky", "bed", "noun", "Sänky on mukava.", "The bed is comfortable."), w("siivota", "clean", "verb", "Siivoan huoneen.", "I clean the room."), w("nukkua", "sleep", "verb", "Lapsi nukkuu.", "The child sleeps."),
    ]),
  ],
  A1: [
    u("u38", "Vapaa-aika ja harrastukset", "Kerro vapaa-ajasta ja suunnittele harrastuksia.", [
      w("harrastus", "hobby", "noun", "Lukeminen on harrastukseni.", "Reading is my hobby."), w("kirja", "book", "noun", "Lainaan kirjan kirjastosta.", "I borrow a book from the library."), w("elokuva", "film", "noun", "Katsoimme hauskan elokuvan.", "We watched a funny film."), w("musiikki", "music", "noun", "Kuuntelen musiikkia illalla.", "I listen to music in the evening."), w("peli", "game", "noun", "Peli alkaa pian.", "The game starts soon."), w("puisto", "park", "noun", "Kävelemme puistossa.", "We walk in the park."), w("harjoitella", "practise", "verb", "Harjoittelen joka päivä.", "I practise every day."), w("rentoutua", "relax", "verb", "Haluan rentoutua viikonloppuna.", "I want to relax at the weekend."),
    ]),
    u("u39", "Matka ja hotelli", "Varaa majoitus ja kysy matkan perustietoja.", [
      w("matka", "trip", "noun", "Matka alkaa huomenna.", "The trip starts tomorrow."), w("hotelli", "hotel", "noun", "Hotelli on aseman lähellä.", "The hotel is near the station."), w("huone", "room", "noun", "Huone on toisessa kerroksessa.", "The room is on the second floor."), w("varaus", "reservation", "noun", "Minulla on varaus.", "I have a reservation."), w("laukku", "bag", "noun", "Laukku on raskas.", "The bag is heavy."), w("kartta", "map", "noun", "Katson karttaa.", "I look at the map."), w("saapua", "arrive", "verb", "Saavumme illalla.", "We arrive in the evening."), w("lähteä", "leave", "verb", "Juna lähtee kymmeneltä.", "The train leaves at ten."),
    ]),
  ],
  A2: [
    u("u38", "Työ ja työpäivä", "Kuvaile työtehtäviä ja keskustele työpäivän järjestämisestä.", [
      w("työpaikka", "workplace", "noun", "Työpaikka on keskustassa.", "The workplace is in the centre."), w("kokous", "meeting", "noun", "Kokous alkaa kello yhdeksän.", "The meeting begins at nine."), w("aikataulu", "schedule", "noun", "Aikataulu muuttui tänään.", "The schedule changed today."), w("kollega", "colleague", "noun", "Kollega auttaa minua.", "A colleague helps me."), w("projekti", "project", "noun", "Projekti valmistuu kesällä.", "The project will be completed in summer."), w("palkka", "salary", "noun", "Palkka maksetaan kuun lopussa.", "The salary is paid at the end of the month."), w("suunnitella", "plan", "verb", "Suunnittelemme uuden projektin.", "We plan a new project."), w("onnistua", "succeed", "verb", "Tiimi onnistui tehtävässä.", "The team succeeded in the task."),
    ]),
    u("u39", "Ympäristö ja kulutus", "Keskustele luonnosta, kierrätyksestä ja vastuullisista valinnoista.", [
      w("ympäristö", "environment", "noun", "Ympäristö tarvitsee suojelua.", "The environment needs protection."), w("luonto", "nature", "noun", "Luonto on lähellä kaupunkia.", "Nature is close to the city."), w("jätteet", "waste", "noun", "Jätteet lajitellaan kotona.", "Waste is sorted at home."), w("kierrätys", "recycling", "noun", "Kierrätys säästää materiaalia.", "Recycling saves material."), w("energia", "energy", "noun", "Aurinko antaa energiaa.", "The sun provides energy."), w("kulutus", "consumption", "noun", "Kulutus on liian suurta.", "Consumption is too high."), w("säästää", "save", "verb", "Säästämme vettä.", "We save water."), w("suojella", "protect", "verb", "Meidän pitää suojella metsää.", "We must protect the forest."),
    ]),
  ],
  B1: [
    u("u38", "Viestintä ja yhteistyö", "Kuvaile yhteistyötä, palautetta ja selkeää viestintää.", [
      w("viestintä", "communication", "noun", "Selkeä viestintä ehkäisee virheitä.", "Clear communication prevents mistakes."), w("yhteistyö", "cooperation", "noun", "Yhteistyö sujui hyvin.", "The cooperation went well."), w("mielipide", "opinion", "noun", "Hän kertoi mielipiteensä.", "She shared her opinion."), w("ehdotus", "proposal", "noun", "Ehdotus sai kannatusta.", "The proposal received support."), w("väärinkäsitys", "misunderstanding", "noun", "Väärinkäsitys ratkaistiin nopeasti.", "The misunderstanding was resolved quickly."), w("luottamus", "trust", "noun", "Luottamus rakentuu vähitellen.", "Trust develops gradually."), w("selittää", "explain", "verb", "Voitko selittää asian?", "Can you explain the matter?"), w("sopia", "agree", "verb", "Sovimme uudesta ajasta.", "We agreed on a new time."),
    ]),
    u("u39", "Media ja uutiset", "Ymmärrä uutisia ja arvioi tiedon luotettavuutta.", [
      w("uutinen", "news item", "noun", "Uutinen levisi nopeasti.", "The news item spread quickly."), w("toimittaja", "journalist", "noun", "Toimittaja haastatteli asiantuntijaa.", "The journalist interviewed an expert."), w("lähde", "source", "noun", "Lähde pitää tarkistaa.", "The source must be checked."), w("haastattelu", "interview", "noun", "Haastattelu julkaistaan huomenna.", "The interview will be published tomorrow."), w("väite", "claim", "noun", "Väite vaatii todisteita.", "The claim requires evidence."), w("otsikko", "headline", "noun", "Otsikko herätti keskustelua.", "The headline sparked discussion."), w("julkaista", "publish", "verb", "Lehti julkaisee raportin.", "The paper publishes the report."), w("verrata", "compare", "verb", "Vertaamme eri lähteitä.", "We compare different sources."),
    ]),
  ],
  B2: [
    u("u38", "Kaupunkisuunnittelu", "Arvioi kaupunkitilaa, asumista ja liikenteen ratkaisuja.", [
      w("kaupunkisuunnittelu", "urban planning", "noun", "Kaupunkisuunnittelu vaikuttaa arkeen.", "Urban planning affects daily life."), w("infrastruktuuri", "infrastructure", "noun", "Infrastruktuuri vaatii investointeja.", "Infrastructure requires investment."), w("julkinen liikenne", "public transport", "noun", "Julkinen liikenne vähentää ruuhkia.", "Public transport reduces congestion."), w("kaavoitus", "zoning", "noun", "Kaavoitus ohjaa rakentamista.", "Zoning guides construction."), w("viheralue", "green space", "noun", "Viheralue lisää hyvinvointia.", "Green space improves well-being."), w("ruuhka", "congestion", "noun", "Ruuhka hidasti matkaa.", "Congestion slowed the journey."), w("tiivistää", "densify", "verb", "Kaupunki tiivistää keskustaa.", "The city densifies the centre."), w("tasapainottaa", "balance", "verb", "Päätös tasapainottaa eri tarpeita.", "The decision balances different needs."),
    ]),
    u("u39", "Ilmasto ja yhteiskunta", "Pohdi ilmastonmuutoksen vaikutuksia ja yhteisiä ratkaisuja.", [
      w("ilmastonmuutos", "climate change", "noun", "Ilmastonmuutos vaikuttaa kaikkiin.", "Climate change affects everyone."), w("päästö", "emission", "noun", "Päästöjä pitää vähentää.", "Emissions must be reduced."), w("sopeutuminen", "adaptation", "noun", "Sopeutuminen vaatii suunnittelua.", "Adaptation requires planning."), w("haavoittuvuus", "vulnerability", "noun", "Haavoittuvuus ei jakaudu tasaisesti.", "Vulnerability is not distributed equally."), w("oikeudenmukaisuus", "fairness", "noun", "Oikeudenmukaisuus on tärkeä tavoite.", "Fairness is an important goal."), w("politiikka", "policy", "noun", "Politiikka ohjaa investointeja.", "Policy guides investments."), w("vähentää", "reduce", "verb", "Toimenpide vähentää riskejä.", "The measure reduces risks."), w("ennakoida", "anticipate", "verb", "Päätöksissä pitää ennakoida seurauksia.", "Decisions must anticipate consequences."),
    ]),
  ],
  C1: [
    u("u38", "Koulutus ja eriarvoisuus", "Analysoi koulutuksen, mahdollisuuksien ja yhteiskunnallisen aseman suhteita.", [
      w("koulutusjärjestelmä", "education system", "noun", "Koulutusjärjestelmä vaikuttaa mahdollisuuksiin.", "The education system affects opportunities."), w("eriarvoisuus", "inequality", "noun", "Eriarvoisuus näkyy eri alueilla.", "Inequality appears in different regions."), w("saavutettavuus", "accessibility", "noun", "Saavutettavuus kuuluu hyvään palveluun.", "Accessibility is part of a good service."), w("valikointi", "selection", "noun", "Valikointi voi vahvistaa eroja.", "Selection can reinforce differences."), w("apuraha", "scholarship", "noun", "Apuraha mahdollisti tutkimuksen.", "The scholarship made the research possible."), w("taustatekijä", "background factor", "noun", "Taustatekijä vaikuttaa tulokseen.", "A background factor affects the result."), w("mahdollistaa", "enable", "verb", "Palvelu mahdollistaa osallistumisen.", "The service enables participation."), w("syrjäyttää", "exclude", "verb", "Korkea hinta voi syrjäyttää ihmisiä.", "A high price can exclude people."),
    ]),
    u("u39", "Taide ja tulkinta", "Puhu taiteen merkityksestä, tulkinnasta ja kulttuurisesta kontekstista.", [
      w("taideteos", "work of art", "noun", "Taideteos herättää kysymyksiä.", "The work of art raises questions."), w("tulkinta", "interpretation", "noun", "Tulkinta riippuu näkökulmasta.", "Interpretation depends on perspective."), w("symboli", "symbol", "noun", "Symboli toistuu romaanissa.", "The symbol recurs in the novel."), w("konteksti", "context", "noun", "Konteksti muuttaa merkitystä.", "Context changes meaning."), w("estetiikka", "aesthetics", "noun", "Estetiikka tutkii kauneuden käsitteitä.", "Aesthetics studies concepts of beauty."), w("yleisö", "audience", "noun", "Yleisö reagoi eri tavoin.", "The audience reacts in different ways."), w("kuvata", "portray", "verb", "Teos kuvaa muutosta.", "The work portrays change."), w("tulkita", "interpret", "verb", "Lukija tulkitsee kohtauksen uudelleen.", "The reader interprets the scene anew."),
    ]),
  ],
  C2: [
    u("u38", "Tieto ja epävarmuus", "Pohdi tiedon rajoja, epävarmuutta ja perustelujen laatua.", [
      w("epistemologia", "epistemology", "noun", "Epistemologia tutkii tiedon ehtoja.", "Epistemology studies the conditions of knowledge."), w("perustelu", "justification", "noun", "Väite tarvitsee perustelun.", "A claim needs justification."), w("epävarmuus", "uncertainty", "noun", "Epävarmuus kuuluu ennusteisiin.", "Uncertainty belongs to forecasts."), w("todiste", "evidence", "noun", "Todiste vahvistaa johtopäätöstä.", "Evidence strengthens the conclusion."), w("ennakko-oletus", "presupposition", "noun", "Ennakko-oletus voi jäädä huomaamatta.", "A presupposition can go unnoticed."), w("ristiriita", "contradiction", "noun", "Ristiriita vaatii lisäselvitystä.", "A contradiction requires further clarification."), w("kyseenalaistaa", "question", "verb", "Tutkija kyseenalaistaa lähtökohdan.", "The researcher questions the premise."), w("todentaa", "verify", "verb", "Tulokset pitää todentaa itsenäisesti.", "The results must be independently verified."),
    ]),
    u("u39", "Etiikka ja teknologia", "Arvioi teknologian, vastuun ja moraalisten valintojen jännitteitä.", [
      w("tekoäly", "artificial intelligence", "noun", "Tekoäly muuttaa työn tekemistä.", "Artificial intelligence changes how work is done."), w("yksityisyys", "privacy", "noun", "Yksityisyys tarvitsee suojaa.", "Privacy needs protection."), w("algoritmi", "algorithm", "noun", "Algoritmi järjestää tietoa.", "An algorithm organizes information."), w("vastuu", "responsibility", "noun", "Vastuu ei katoa automaatiolla.", "Responsibility does not disappear through automation."), w("valvonta", "surveillance", "noun", "Valvonta herättää eettisiä kysymyksiä.", "Surveillance raises ethical questions."), w("vinouma", "bias", "noun", "Vinouma vääristää tulosta.", "Bias distorts the result."), w("säädellä", "regulate", "verb", "Laki säätelee teknologian käyttöä.", "The law regulates the use of technology."), w("ennakoida", "anticipate", "verb", "Yhteiskunnan pitää ennakoida riskejä.", "Society must anticipate risks."),
    ]),
  ],
};
