// Professional English enrichment unit u60 for every CEFR level.
// Reference PDFs informed gap analysis only; they are not runtime imports.
import type { ReadingText, VocabularyItem } from "./learn-data";

type PhraseSpec = { phrase: string; translation: string };
type LineSpec = { speaker: string; text: string; translation: string };
type WordSpec = {
  word: string; translation: string; pos: string; ipa: string; definition: string;
  example: string; exampleTranslation: string; synonyms: string[]; antonyms: string[];
  collocations: string[]; wordFamily: string[]; tags: string[]; category: string;
};
type UnitSeed = {
  id: string; title: string; description: string; words: VocabularyItem[];
  phrases: PhraseSpec[]; dialogue: LineSpec[]; reading: ReadingText & { title: string };
};

const w = (spec: WordSpec): VocabularyItem => ({ ...spec });
const u = (title: string, description: string, words: VocabularyItem[], phrases: PhraseSpec[], dialogue: LineSpec[], reading: ReadingText & { title: string }): UnitSeed => ({ id: "u60", title, description, words, phrases, dialogue, reading });

export const ADDITIONAL_EN_PART21_UNITS: Record<string, UnitSeed[]> = {
  A0: [
    u("Playground Fun", "Name playground equipment and describe safe, simple movements.", [
      w({ word: "sandbox", translation: "arenero", pos: "noun", ipa: "/ˈsændbɑːks/", definition: "a box or area filled with sand for children to play in", example: "The children play in the sandbox.", exampleTranslation: "Los niños juegan en el arenero.", synonyms: ["sandpit"], antonyms: [], collocations: ["play in a sandbox", "sandbox toys"], wordFamily: ["sand", "sandbox"], tags: ["playground", "children"], category: "place" }),
      w({ word: "helmet", translation: "casco", pos: "noun", ipa: "/ˈhelmɪt/", definition: "hard protective covering worn on the head", example: "Wear a helmet on the scooter.", exampleTranslation: "Ponte un casco en el patinete.", synonyms: ["head protection"], antonyms: [], collocations: ["wear a helmet", "safety helmet"], wordFamily: ["helmet", "helmeted"], tags: ["safety", "playground"], category: "object" }),
      w({ word: "hoop", translation: "aro", pos: "noun", ipa: "/huːp/", definition: "a circular band used for play or sport", example: "Roll the hoop along the path.", exampleTranslation: "Haz rodar el aro por el camino.", synonyms: ["ring"], antonyms: [], collocations: ["jump through a hoop", "plastic hoop"], wordFamily: ["hoop", "hooped"], tags: ["playground", "games"], category: "object" }),
      w({ word: "seesaw", translation: "balancín", pos: "noun", ipa: "/ˈsiːsɔː/", definition: "a playground board that moves up and down", example: "Mia sits on the seesaw.", exampleTranslation: "Mia se sienta en el balancín.", synonyms: ["teeter-totter"], antonyms: [], collocations: ["ride a seesaw", "playground seesaw"], wordFamily: ["see", "saw", "seesaw"], tags: ["playground", "movement"], category: "equipment" }),
      w({ word: "kick", translation: "dar una patada", pos: "verb", ipa: "/kɪk/", definition: "to hit something with the foot", example: "Kick the ball gently.", exampleTranslation: "Patea la pelota suavemente.", synonyms: ["tap", "boot"], antonyms: ["catch"], collocations: ["kick a ball", "kick gently"], wordFamily: ["kick", "kicker"], tags: ["playground", "action"], category: "movement" }),
      w({ word: "crawl", translation: "gatear", pos: "verb", ipa: "/krɔːl/", definition: "to move on hands and knees or very close to the ground", example: "The baby can crawl across the mat.", exampleTranslation: "El bebé puede gatear por la colchoneta.", synonyms: ["creep", "move slowly"], antonyms: ["stand"], collocations: ["crawl under a bar", "crawl on hands and knees"], wordFamily: ["crawl", "crawler"], tags: ["movement", "children"], category: "action" }),
      w({ word: "hop", translation: "saltar a la pata coja", pos: "verb", ipa: "/hɑːp/", definition: "to jump on one foot", example: "Hop over the line.", exampleTranslation: "Salta a la pata coja sobre la línea.", synonyms: ["jump", "skip"], antonyms: ["stop"], collocations: ["hop on one foot", "hop over"], wordFamily: ["hop", "hopper"], tags: ["movement", "games"], category: "action" }),
      w({ word: "playground", translation: "parque infantil", pos: "noun", ipa: "/ˈpleɪɡraʊnd/", definition: "an outdoor area where children play", example: "Our playground is behind the school.", exampleTranslation: "Nuestro parque infantil está detrás de la escuela.", synonyms: ["play area"], antonyms: [], collocations: ["visit the playground", "safe playground"], wordFamily: ["play", "playground"], tags: ["places", "children"], category: "place" }),
    ], [
      { phrase: "Put on your helmet.", translation: "Ponte el casco." }, { phrase: "Wait for your turn.", translation: "Espera tu turno." }, { phrase: "Do not push.", translation: "No empujes." }, { phrase: "Can I play with you?", translation: "¿Puedo jugar contigo?" },
    ], [
      { speaker: "A", text: "Can I use the hoop?", translation: "¿Puedo usar el aro?" }, { speaker: "B", text: "Yes, but wait for your turn.", translation: "Sí, pero espera tu turno." }, { speaker: "A", text: "I will wear my helmet first.", translation: "Primero me pondré el casco." }, { speaker: "B", text: "Good. Let us play safely.", translation: "Bien. Vamos a jugar con seguridad." },
    ], { title: "A Safe Afternoon", text: "Leo goes to the playground after school. He hops over a line, rolls a hoop, and plays near the sandbox. Before he rides his scooter, he puts on a helmet and waits for his turn.", translation: "Leo va al parque infantil después de la escuela. Salta a la pata coja sobre una línea, hace rodar un aro y juega cerca del arenero. Antes de montar en su patinete, se pone un casco y espera su turno." }),
  ],
  A1: [
    u("At the Library", "Borrow books, ask for help, and talk about simple library rules.", [
      w({ word: "library", translation: "biblioteca", pos: "noun", ipa: "/ˈlaɪbreri/", definition: "a place where people can read or borrow books", example: "The library closes at six.", exampleTranslation: "La biblioteca cierra a las seis.", synonyms: ["book centre"], antonyms: [], collocations: ["public library", "visit the library"], wordFamily: ["library", "librarian"], tags: ["education", "places"], category: "place" }),
      w({ word: "borrow", translation: "pedir prestado", pos: "verb", ipa: "/ˈbɑːroʊ/", definition: "to take and use something for a time before returning it", example: "Can I borrow this book?", exampleTranslation: "¿Puedo pedir prestado este libro?", synonyms: ["take on loan"], antonyms: ["return", "lend"], collocations: ["borrow a book", "borrow from the library"], wordFamily: ["borrow", "borrower"], tags: ["library", "action"], category: "action" }),
      w({ word: "lend", translation: "prestar", pos: "verb", ipa: "/lend/", definition: "to let someone use something that belongs to you", example: "The library lends books for three weeks.", exampleTranslation: "La biblioteca presta libros durante tres semanas.", synonyms: ["loan", "let someone use"], antonyms: ["borrow"], collocations: ["lend a book", "lend money"], wordFamily: ["lend", "lender"], tags: ["library", "action"], category: "action" }),
      w({ word: "catalogue", translation: "catálogo", pos: "noun", ipa: "/ˈkætəlɔːɡ/", definition: "a list of books or items arranged so they can be found", example: "Search the catalogue for a travel guide.", exampleTranslation: "Busca una guía de viajes en el catálogo.", synonyms: ["list", "index"], antonyms: [], collocations: ["library catalogue", "online catalogue"], wordFamily: ["catalogue", "catalogue"], tags: ["library", "information"], category: "document" }),
      w({ word: "membership", translation: "membresía", pos: "noun", ipa: "/ˈmembərʃɪp/", definition: "the state of belonging to an organisation", example: "Library membership is free for children.", exampleTranslation: "La membresía de la biblioteca es gratuita para los niños.", synonyms: ["enrolment", "subscription"], antonyms: ["nonmembership"], collocations: ["library membership", "membership card"], wordFamily: ["member", "membership"], tags: ["library", "services"], category: "status" }),
      w({ word: "librarian", translation: "bibliotecario", pos: "noun", ipa: "/laɪˈbreriən/", definition: "a person who works in and manages a library", example: "Ask the librarian for a history book.", exampleTranslation: "Pregunta al bibliotecario por un libro de historia.", synonyms: ["library worker"], antonyms: [], collocations: ["helpful librarian", "ask a librarian"], wordFamily: ["library", "librarian"], tags: ["library", "people"], category: "person" }),
      w({ word: "author", translation: "autor", pos: "noun", ipa: "/ˈɔːθər/", definition: "a person who writes a book or other text", example: "The author will speak this evening.", exampleTranslation: "El autor hablará esta tarde.", synonyms: ["writer", "novelist"], antonyms: ["reader"], collocations: ["famous author", "book author"], wordFamily: ["author", "authorship", "authorial"], tags: ["books", "people"], category: "person" }),
      w({ word: "due date", translation: "fecha de devolución", pos: "noun", ipa: "/ˈduː deɪt/", definition: "the date by which something must be returned or completed", example: "The due date is next Monday.", exampleTranslation: "La fecha de devolución es el próximo lunes.", synonyms: ["return date", "deadline"], antonyms: [], collocations: ["book due date", "check the due date"], wordFamily: ["due", "date"], tags: ["library", "time"], category: "date" }),
    ], [
      { phrase: "Where can I find this book?", translation: "¿Dónde puedo encontrar este libro?" }, { phrase: "I would like to join the library.", translation: "Me gustaría apuntarme a la biblioteca." }, { phrase: "How long can I borrow it?", translation: "¿Durante cuánto tiempo puedo pedirlo prestado?" }, { phrase: "When is it due?", translation: "¿Cuándo hay que devolverlo?" },
    ], [
      { speaker: "A", text: "Could you help me find this author?", translation: "¿Podría ayudarme a encontrar a este autor?" }, { speaker: "B", text: "Of course. Search the catalogue on that computer.", translation: "Claro. Busca en el catálogo de ese ordenador." }, { speaker: "A", text: "Can I borrow the book today?", translation: "¿Puedo pedir prestado el libro hoy?" }, { speaker: "B", text: "Yes. Your due date is the third of May.", translation: "Sí. Tu fecha de devolución es el tres de mayo." },
    ], { title: "A Quiet Place to Learn", text: "Sam joins the local library and receives a membership card. A librarian helps him search the catalogue for a book by his favourite author. Sam borrows it and writes the due date in his notebook.", translation: "Sam se apunta a la biblioteca local y recibe una tarjeta de membresía. Un bibliotecario le ayuda a buscar en el catálogo un libro de su autor favorito. Sam lo pide prestado y escribe la fecha de devolución en su cuaderno." }),
  ],
  A2: [
    u("Simple Home Repairs", "Name household tools and give or follow basic repair instructions.", [
      w({ word: "toolbox", translation: "caja de herramientas", pos: "noun", ipa: "/ˈtuːlbɑːks/", definition: "a box used for keeping tools", example: "The toolbox is under the stairs.", exampleTranslation: "La caja de herramientas está debajo de las escaleras.", synonyms: ["tool case"], antonyms: [], collocations: ["open a toolbox", "basic toolbox"], wordFamily: ["tool", "toolbox"], tags: ["home", "objects"], category: "container" }),
      w({ word: "screwdriver", translation: "destornillador", pos: "noun", ipa: "/ˈskruːdraɪvər/", definition: "a tool used for turning screws", example: "Use a screwdriver to tighten the handle.", exampleTranslation: "Usa un destornillador para apretar el mango.", synonyms: ["driver"], antonyms: [], collocations: ["flat-head screwdriver", "use a screwdriver"], wordFamily: ["screw", "drive", "screwdriver"], tags: ["home", "tools"], category: "tool" }),
      w({ word: "hammer", translation: "martillo", pos: "noun", ipa: "/ˈhæmər/", definition: "a tool with a heavy head used for hitting nails", example: "The hammer is beside the box.", exampleTranslation: "El martillo está junto a la caja.", synonyms: ["mallet"], antonyms: [], collocations: ["use a hammer", "hammer a nail"], wordFamily: ["hammer", "hammering"], tags: ["home", "tools"], category: "tool" }),
      w({ word: "leak", translation: "fuga", pos: "noun", ipa: "/liːk/", definition: "a small hole or opening through which liquid escapes", example: "There is a leak under the sink.", exampleTranslation: "Hay una fuga debajo del fregadero.", synonyms: ["drip", "seepage"], antonyms: ["seal"], collocations: ["water leak", "find a leak"], wordFamily: ["leak", "leaky"], tags: ["home", "problems"], category: "problem" }),
      w({ word: "tighten", translation: "apretar", pos: "verb", ipa: "/ˈtaɪtən/", definition: "to make something firm by turning or pulling it", example: "Tighten the screw carefully.", exampleTranslation: "Aprieta el tornillo con cuidado.", synonyms: ["secure", "fasten"], antonyms: ["loosen"], collocations: ["tighten a screw", "tighten a bolt"], wordFamily: ["tight", "tighten", "tightness"], tags: ["home", "action"], category: "action" }),
      w({ word: "unplug", translation: "desenchufar", pos: "verb", ipa: "/ʌnˈplʌɡ/", definition: "to remove a plug from an electrical socket", example: "Unplug the lamp before cleaning it.", exampleTranslation: "Desenchufa la lámpara antes de limpiarla.", synonyms: ["disconnect"], antonyms: ["plug in", "connect"], collocations: ["unplug a device", "unplug safely"], wordFamily: ["plug", "unplugged"], tags: ["home", "safety"], category: "action" }),
      w({ word: "replace", translation: "reemplazar", pos: "verb", ipa: "/rɪˈpleɪs/", definition: "to put a new thing where an old one was", example: "We need to replace the broken bulb.", exampleTranslation: "Tenemos que reemplazar la bombilla rota.", synonyms: ["renew", "substitute"], antonyms: ["keep", "remove"], collocations: ["replace a part", "replace a bulb"], wordFamily: ["place", "replace", "replacement"], tags: ["home", "action"], category: "action" }),
      w({ word: "repair", translation: "reparar", pos: "verb", ipa: "/rɪˈper/", definition: "to fix something that is damaged or not working", example: "Can you repair the dripping tap?", exampleTranslation: "¿Puedes reparar el grifo que gotea?", synonyms: ["fix", "mend"], antonyms: ["damage", "break"], collocations: ["repair a machine", "home repair"], wordFamily: ["repair", "repairable", "repairer"], tags: ["home", "action"], category: "action" }),
    ], [
      { phrase: "Turn off the water first.", translation: "Cierra el agua primero." }, { phrase: "Which tool should I use?", translation: "¿Qué herramienta debo usar?" }, { phrase: "Be careful with the electricity.", translation: "Ten cuidado con la electricidad." }, { phrase: "The problem is easy to repair.", translation: "El problema es fácil de reparar." },
    ], [
      { speaker: "A", text: "There is a leak under the sink.", translation: "Hay una fuga debajo del fregadero." }, { speaker: "B", text: "Turn off the water and open the toolbox.", translation: "Cierra el agua y abre la caja de herramientas." }, { speaker: "A", text: "Should I use the screwdriver?", translation: "¿Debo usar el destornillador?" }, { speaker: "B", text: "Yes, then tighten the fitting and check it again.", translation: "Sí, luego aprieta la pieza y compruébala otra vez." },
    ], { title: "Fixing a Small Problem", text: "When Omar finds a leak under the sink, he turns off the water. He opens the toolbox and uses a screwdriver to tighten a fitting. The leak continues, so he replaces the seal and checks the repair before using the tap again.", translation: "Cuando Omar encuentra una fuga debajo del fregadero, cierra el agua. Abre la caja de herramientas y usa un destornillador para apretar una pieza. La fuga continúa, así que reemplaza el sello y comprueba la reparación antes de volver a usar el grifo." }),
  ],
  B1: [
    u("Meetings and Collaboration", "Participate in meetings, clarify responsibilities, and reach workable agreements.", [
      w({ word: "facilitate", translation: "facilitar", pos: "verb", ipa: "/fəˈsɪlɪteɪt/", definition: "to make an activity or process easier", example: "The coordinator will facilitate the discussion.", exampleTranslation: "El coordinador facilitará el debate.", synonyms: ["enable", "help"], antonyms: ["hinder"], collocations: ["facilitate a meeting", "facilitate learning"], wordFamily: ["facility", "facilitate", "facilitator"], tags: ["work", "communication"], category: "action" }),
      w({ word: "facilitator", translation: "facilitador", pos: "noun", ipa: "/fəˈsɪlɪteɪtər/", definition: "a person who helps a group communicate and work effectively", example: "The facilitator keeps the meeting focused.", exampleTranslation: "El facilitador mantiene la reunión centrada.", synonyms: ["moderator", "coordinator"], antonyms: [], collocations: ["trained facilitator", "meeting facilitator"], wordFamily: ["facilitate", "facilitator"], tags: ["work", "people"], category: "role" }),
      w({ word: "mediation", translation: "mediación", pos: "noun", ipa: "/ˌmiːdiˈeɪʃən/", definition: "help from a neutral person to settle a disagreement", example: "The teams agreed to mediation.", exampleTranslation: "Los equipos aceptaron la mediación.", synonyms: ["conciliation", "intervention"], antonyms: ["conflict"], collocations: ["formal mediation", "mediation process"], wordFamily: ["mediate", "mediator", "mediation"], tags: ["work", "conflict"], category: "process" }),
      w({ word: "concession", translation: "concesión", pos: "noun", ipa: "/kənˈseʃən/", definition: "something accepted or given up to reach an agreement", example: "Both sides made a concession.", exampleTranslation: "Ambas partes hicieron una concesión.", synonyms: ["compromise", "allowance"], antonyms: ["demand"], collocations: ["make a concession", "major concession"], wordFamily: ["concede", "concession"], tags: ["work", "negotiation"], category: "agreement" }),
      w({ word: "rapport", translation: "buena relación", pos: "noun", ipa: "/ræˈpɔːr/", definition: "a friendly and trusting relationship", example: "Good rapport helps the team share ideas.", exampleTranslation: "Una buena relación ayuda al equipo a compartir ideas.", synonyms: ["understanding", "connection"], antonyms: ["distance"], collocations: ["build rapport", "excellent rapport"], wordFamily: ["rapport"], tags: ["work", "people"], category: "relationship" }),
      w({ word: "alignment", translation: "alineación", pos: "noun", ipa: "/əˈlaɪnmənt/", definition: "a state in which people or plans support the same goal", example: "The workshop created alignment across departments.", exampleTranslation: "El taller creó alineación entre departamentos.", synonyms: ["agreement", "coordination"], antonyms: ["disagreement"], collocations: ["strategic alignment", "reach alignment"], wordFamily: ["align", "aligned", "alignment"], tags: ["work", "planning"], category: "agreement" }),
      w({ word: "clarify", translation: "aclarar", pos: "verb", ipa: "/ˈklærəfaɪ/", definition: "to make an idea or statement easier to understand", example: "Could you clarify the final responsibility?", exampleTranslation: "¿Podrías aclarar la responsabilidad final?", synonyms: ["explain", "illuminate"], antonyms: ["confuse"], collocations: ["clarify a point", "clarify expectations"], wordFamily: ["clear", "clarify", "clarification"], tags: ["work", "communication"], category: "action" }),
      w({ word: "minutes", translation: "acta", pos: "noun", ipa: "/ˈmɪnɪts/", definition: "an official written record of what was said and decided in a meeting", example: "The secretary circulated the minutes.", exampleTranslation: "El secretario distribuyó el acta.", synonyms: ["record", "notes"], antonyms: [], collocations: ["take minutes", "meeting minutes"], wordFamily: ["minute", "minutes"], tags: ["work", "meetings"], category: "document" }),
    ], [
      { phrase: "Let us return to the main point.", translation: "Volvamos al punto principal." }, { phrase: "Could you clarify that?", translation: "¿Podrías aclarar eso?" }, { phrase: "We need a workable agreement.", translation: "Necesitamos un acuerdo viable." }, { phrase: "I will record that action.", translation: "Registraré esa acción." },
    ], [
      { speaker: "A", text: "The discussion is becoming difficult.", translation: "El debate se está volviendo difícil." }, { speaker: "B", text: "I can facilitate it if we clarify the shared goal.", translation: "Puedo facilitarlo si aclaramos el objetivo común." }, { speaker: "A", text: "I can make a concession on the schedule.", translation: "Puedo hacer una concesión sobre el calendario." }, { speaker: "B", text: "That should create alignment and improve rapport.", translation: "Eso debería crear alineación y mejorar la relación." },
    ], { title: "Finding Common Ground", text: "A project meeting begins with disagreement about the schedule. The facilitator asks everyone to clarify their priorities and restate the shared objective. Through mediation, each group makes a small concession, and the final minutes record an agreement that creates alignment.", translation: "Una reunión de proyecto comienza con un desacuerdo sobre el calendario. El facilitador pide a todos que aclaren sus prioridades y vuelvan a expresar el objetivo común. Mediante la mediación, cada grupo hace una pequeña concesión y el acta final registra un acuerdo que crea alineación." }),
  ],
  B2: [
    u("Reading the Media", "Evaluate online information, identify persuasive techniques, and check claims before sharing them.", [
      w({ word: "fact-check", translation: "verificar datos", pos: "verb", ipa: "/ˈfækt tʃek/", definition: "to investigate whether a statement is accurate", example: "Journalists fact-check the claim before publication.", exampleTranslation: "Los periodistas verifican los datos de la afirmación antes de publicarla.", synonyms: ["verify", "check"], antonyms: ["guess"], collocations: ["fact-check a claim", "independent fact-check"], wordFamily: ["fact", "check", "fact-checker"], tags: ["media", "research"], category: "action" }),
      w({ word: "clickbait", translation: "cebo de clics", pos: "noun", ipa: "/ˈklɪkbeɪt/", definition: "a sensational headline designed to make people click a link", example: "The article used clickbait instead of useful information.", exampleTranslation: "El artículo usó cebo de clics en lugar de información útil.", synonyms: ["sensational headline"], antonyms: ["plain reporting"], collocations: ["clickbait title", "avoid clickbait"], wordFamily: ["click", "bait", "clickbait"], tags: ["media", "internet"], category: "technique" }),
      w({ word: "credibility", translation: "credibilidad", pos: "noun", ipa: "/ˌkredəˈbɪləti/", definition: "the quality of being trusted or believed", example: "The source lost credibility after correcting several errors.", exampleTranslation: "La fuente perdió credibilidad después de corregir varios errores.", synonyms: ["trustworthiness", "reliability"], antonyms: ["unreliability"], collocations: ["establish credibility", "source credibility"], wordFamily: ["credible", "credibility", "credibly"], tags: ["media", "evaluation"], category: "quality" }),
      w({ word: "algorithm", translation: "algoritmo", pos: "noun", ipa: "/ˈælɡərɪðəm/", definition: "a set of rules used by a computer to solve a problem or select information", example: "The platform's algorithm recommends similar videos.", exampleTranslation: "El algoritmo de la plataforma recomienda vídeos similares.", synonyms: ["procedure", "set of rules"], antonyms: [], collocations: ["search algorithm", "recommendation algorithm"], wordFamily: ["algorithm", "algorithmic"], tags: ["technology", "media"], category: "system" }),
      w({ word: "contextualize", translation: "contextualizar", pos: "verb", ipa: "/kənˈtekstʃuəlaɪz/", definition: "to place information within the situation that gives it meaning", example: "The report contextualizes the figures with regional data.", exampleTranslation: "El informe contextualiza las cifras con datos regionales.", synonyms: ["interpret", "situate"], antonyms: ["isolate"], collocations: ["contextualize evidence", "contextualize a quote"], wordFamily: ["context", "contextual", "contextualize"], tags: ["media", "analysis"], category: "action" }),
      w({ word: "satire", translation: "sátira", pos: "noun", ipa: "/ˈsætaɪər/", definition: "a form of humour that criticises people or institutions", example: "The programme uses satire to question political promises.", exampleTranslation: "El programa usa la sátira para cuestionar las promesas políticas.", synonyms: ["parody", "mockery"], antonyms: ["praise"], collocations: ["political satire", "satirical programme"], wordFamily: ["satire", "satirical", "satirize"], tags: ["media", "culture"], category: "genre" }),
      w({ word: "sponsored", translation: "patrocinado", pos: "adjective", ipa: "/ˈspɑːnsərd/", definition: "paid for or supported by an organisation, often in advertising", example: "The sponsored post clearly names its advertiser.", exampleTranslation: "La publicación patrocinada nombra claramente a su anunciante.", synonyms: ["paid", "promoted"], antonyms: ["independent"], collocations: ["sponsored content", "sponsored post"], wordFamily: ["sponsor", "sponsored", "sponsorship"], tags: ["media", "business"], category: "description" }),
      w({ word: "misleading", translation: "engañoso", pos: "adjective", ipa: "/mɪsˈliːdɪŋ/", definition: "giving a wrong idea or impression", example: "The graph is misleading because it hides the scale.", exampleTranslation: "El gráfico es engañoso porque oculta la escala.", synonyms: ["deceptive", "confusing"], antonyms: ["accurate", "clear"], collocations: ["misleading claim", "misleading graph"], wordFamily: ["lead", "mislead", "misleading"], tags: ["media", "critical thinking"], category: "quality" }),
    ], [
      { phrase: "Check the claim before sharing it.", translation: "Comprueba la afirmación antes de compartirla." }, { phrase: "Who is the original source?", translation: "¿Cuál es la fuente original?" }, { phrase: "The headline is deliberately sensational.", translation: "El titular es deliberadamente sensacionalista." }, { phrase: "Look at the evidence in context.", translation: "Mira las pruebas en su contexto." },
    ], [
      { speaker: "A", text: "This post has thousands of shares.", translation: "Esta publicación tiene miles de compartidos." }, { speaker: "B", text: "Popularity does not prove credibility. Let us fact-check it.", translation: "La popularidad no demuestra credibilidad. Vamos a verificarla." }, { speaker: "A", text: "The headline may be clickbait.", translation: "El titular puede ser cebo de clics." }, { speaker: "B", text: "Then we should contextualize the claim before responding.", translation: "Entonces deberíamos contextualizar la afirmación antes de responder." },
    ], { title: "Pause Before Sharing", text: "A dramatic post spreads quickly through a social platform. Its clickbait headline uses a misleading graph, while the algorithm recommends it to more users. A careful reader checks the original source, contextualizes the numbers, and distinguishes sponsored content from independent reporting before sharing the story.", translation: "Una publicación dramática se difunde rápidamente por una plataforma social. Su titular de cebo de clics usa un gráfico engañoso, mientras el algoritmo la recomienda a más usuarios. Un lector cuidadoso comprueba la fuente original, contextualiza los números y distingue el contenido patrocinado de la información independiente antes de compartir la historia." }),
  ],
  C1: [
    u("Putting Policy into Practice", "Analyse how public policies move from formal decisions to measurable implementation.", [
      w({ word: "legislation", translation: "legislación", pos: "noun", ipa: "/ˌledʒɪˈsleɪʃən/", definition: "laws considered or made by a government", example: "The new legislation protects renters.", exampleTranslation: "La nueva legislación protege a los inquilinos.", synonyms: ["law", "statute"], antonyms: ["lawlessness"], collocations: ["pass legislation", "draft legislation"], wordFamily: ["legislate", "legislator", "legislation"], tags: ["government", "society"], category: "law" }),
      w({ word: "bureaucracy", translation: "burocracia", pos: "noun", ipa: "/bjʊˈrɑːkrəsi/", definition: "a system of administration with many rules and official procedures", example: "Excessive bureaucracy delayed the programme.", exampleTranslation: "La burocracia excesiva retrasó el programa.", synonyms: ["administration", "officialdom"], antonyms: ["simplicity"], collocations: ["government bureaucracy", "reduce bureaucracy"], wordFamily: ["bureaucrat", "bureaucratic", "bureaucracy"], tags: ["government", "systems"], category: "system" }),
      w({ word: "enforce", translation: "hacer cumplir", pos: "verb", ipa: "/ɪnˈfɔːrs/", definition: "to make people obey a law or rule", example: "The agency must enforce the safety standard.", exampleTranslation: "La agencia debe hacer cumplir la norma de seguridad.", synonyms: ["implement", "apply"], antonyms: ["ignore"], collocations: ["enforce a law", "strictly enforce"], wordFamily: ["force", "enforce", "enforcement"], tags: ["government", "law"], category: "action" }),
      w({ word: "allocate", translation: "asignar", pos: "verb", ipa: "/ˈæləkeɪt/", definition: "to distribute money, time, or resources for a particular purpose", example: "The council allocated funds to rural clinics.", exampleTranslation: "El consejo asignó fondos a clínicas rurales.", synonyms: ["assign", "distribute"], antonyms: ["withhold"], collocations: ["allocate resources", "allocate a budget"], wordFamily: ["locate", "allocate", "allocation"], tags: ["government", "planning"], category: "action" }),
      w({ word: "compliance", translation: "cumplimiento", pos: "noun", ipa: "/kəmˈplaɪəns/", definition: "the act of obeying a rule, request, or law", example: "The audit measures compliance with the standard.", exampleTranslation: "La auditoría mide el cumplimiento de la norma.", synonyms: ["obedience", "conformity"], antonyms: ["defiance"], collocations: ["regulatory compliance", "ensure compliance"], wordFamily: ["comply", "compliant", "compliance"], tags: ["government", "law"], category: "condition" }),
      w({ word: "mandate", translation: "mandato", pos: "noun", ipa: "/ˈmændeɪt/", definition: "an official order or authority to do something", example: "The agency received a mandate to improve access.", exampleTranslation: "La agencia recibió el mandato de mejorar el acceso.", synonyms: ["directive", "authority"], antonyms: ["prohibition"], collocations: ["legal mandate", "public mandate"], wordFamily: ["mandate", "mandatory"], tags: ["government", "policy"], category: "authority" }),
      w({ word: "feasibility", translation: "viabilidad", pos: "noun", ipa: "/ˌfiːzəˈbɪləti/", definition: "the degree to which a plan is practical and possible", example: "The feasibility study examined costs and staffing.", exampleTranslation: "El estudio de viabilidad examinó los costes y el personal.", synonyms: ["practicality", "workability"], antonyms: ["impossibility"], collocations: ["feasibility study", "assess feasibility"], wordFamily: ["feasible", "feasibility"], tags: ["policy", "planning"], category: "quality" }),
      w({ word: "disburse", translation: "desembolsar", pos: "verb", ipa: "/dɪsˈbɜːrs/", definition: "to pay out money, especially from an official fund", example: "The department will disburse grants in June.", exampleTranslation: "El departamento desembolsará las subvenciones en junio.", synonyms: ["pay out", "release"], antonyms: ["withhold"], collocations: ["disburse funds", "disburse a grant"], wordFamily: ["purse", "disburse", "disbursement"], tags: ["government", "finance"], category: "action" }),
    ], [
      { phrase: "How will the policy be enforced?", translation: "¿Cómo se hará cumplir la política?" }, { phrase: "The proposal requires a feasibility study.", translation: "La propuesta requiere un estudio de viabilidad." }, { phrase: "Resources must be allocated fairly.", translation: "Los recursos deben asignarse justamente." }, { phrase: "Compliance will be reviewed annually.", translation: "El cumplimiento se revisará anualmente." },
    ], [
      { speaker: "A", text: "The legislation has passed, but implementation is slow.", translation: "La legislación ha sido aprobada, pero la implementación es lenta." }, { speaker: "B", text: "The agency needs a clear mandate and sufficient funds.", translation: "La agencia necesita un mandato claro y fondos suficientes." }, { speaker: "A", text: "Can it disburse grants before the review?", translation: "¿Puede desembolsar subvenciones antes de la revisión?" }, { speaker: "B", text: "Only after the feasibility and compliance checks are complete.", translation: "Solo después de completar las comprobaciones de viabilidad y cumplimiento." },
    ], { title: "From Law to Results", text: "Passing legislation is only the first stage of public policy. Administrators must interpret the mandate, reduce unnecessary bureaucracy, allocate resources, and enforce the rules consistently. A feasibility review and transparent compliance measures help show whether the policy produces its intended results.", translation: "Aprobar legislación es solo la primera etapa de una política pública. Los administradores deben interpretar el mandato, reducir la burocracia innecesaria, asignar recursos y hacer cumplir las normas de manera coherente. Una revisión de viabilidad y medidas transparentes de cumplimiento ayudan a mostrar si la política produce los resultados previstos." }),
  ],
  C2: [
    u("Translation and Equivalence", "Examine how translators handle cultural meaning, register, idioms, and unavoidable choices.", [
      w({ word: "translator", translation: "traductor", pos: "noun", ipa: "/trænzˈleɪtər/", definition: "a person who changes written or spoken language into another language", example: "The translator preserved the humour of the original.", exampleTranslation: "El traductor conservó el humor del original.", synonyms: ["interpreter", "language specialist"], antonyms: [], collocations: ["professional translator", "literary translator"], wordFamily: ["translate", "translation", "translator"], tags: ["language", "work"], category: "person" }),
      w({ word: "literal", translation: "literal", pos: "adjective", ipa: "/ˈlɪtərəl/", definition: "following the exact words rather than the intended or figurative meaning", example: "A literal translation makes the idiom sound strange.", exampleTranslation: "Una traducción literal hace que el modismo suene extraño.", synonyms: ["word-for-word", "exact"], antonyms: ["figurative", "adapted"], collocations: ["literal meaning", "literal translation"], wordFamily: ["literal", "literally", "literality"], tags: ["translation", "meaning"], category: "approach" }),
      w({ word: "idiom", translation: "modismo", pos: "noun", ipa: "/ˈɪdiəm/", definition: "a fixed expression whose meaning is not simply the meaning of its words", example: "The translator explained the idiom in a note.", exampleTranslation: "El traductor explicó el modismo en una nota.", synonyms: ["expression", "set phrase"], antonyms: [], collocations: ["common idiom", "translate an idiom"], wordFamily: ["idiom", "idiomatic"], tags: ["translation", "language"], category: "expression" }),
      w({ word: "rendition", translation: "versión traducida", pos: "noun", ipa: "/renˈdɪʃən/", definition: "a particular version or interpretation of a text or performance", example: "Her rendition captures the poem's restrained tone.", exampleTranslation: "Su versión capta el tono contenido del poema.", synonyms: ["version", "interpretation"], antonyms: [], collocations: ["faithful rendition", "new rendition"], wordFamily: ["render", "rendition"], tags: ["translation", "literature"], category: "version" }),
      w({ word: "untranslatable", translation: "intraducible", pos: "adjective", ipa: "/ˌʌntrænzˈleɪtəbəl/", definition: "too closely tied to one language or culture to be translated exactly", example: "The pun is almost untranslatable.", exampleTranslation: "El juego de palabras es casi intraducible.", synonyms: ["inexpressible", "culture-bound"], antonyms: ["translatable"], collocations: ["seem untranslatable", "untranslatable pun"], wordFamily: ["translate", "translatable", "untranslatable"], tags: ["translation", "culture"], category: "quality" }),
      w({ word: "transliterate", translation: "transliterar", pos: "verb", ipa: "/trænzˈlɪtəreɪt/", definition: "to represent the letters of one writing system using another", example: "The editor transliterated the name into the Latin alphabet.", exampleTranslation: "El editor transliteró el nombre al alfabeto latino.", synonyms: ["romanize", "transcribe"], antonyms: [], collocations: ["transliterate a name", "transliterate a script"], wordFamily: ["letter", "transliterate", "transliteration"], tags: ["translation", "writing"], category: "action" }),
      w({ word: "calque", translation: "calco lingüístico", pos: "noun", ipa: "/kælk/", definition: "a word or expression translated closely from another language", example: "The new phrase is a calque from German.", exampleTranslation: "La nueva expresión es un calco lingüístico del alemán.", synonyms: ["loan translation"], antonyms: [], collocations: ["semantic calque", "linguistic calque"], wordFamily: ["calque", "calqued"], tags: ["translation", "linguistics"], category: "formation" }),
      w({ word: "paraphrase", translation: "paráfrasis", pos: "noun", ipa: "/ˈpærəfreɪz/", definition: "a restatement of an idea using different words", example: "The student gave a clear paraphrase of the difficult passage.", exampleTranslation: "El estudiante hizo una paráfrasis clara del pasaje difícil.", synonyms: ["rewording", "restatement"], antonyms: ["quotation"], collocations: ["provide a paraphrase", "paraphrase a sentence"], wordFamily: ["phrase", "paraphrase", "paraphrasing"], tags: ["translation", "writing"], category: "technique" }),
    ], [
      { phrase: "The meaning cannot be translated word for word.", translation: "El significado no puede traducirse palabra por palabra." }, { phrase: "This idiom needs a cultural explanation.", translation: "Este modismo necesita una explicación cultural." }, { phrase: "Which rendition best preserves the tone?", translation: "¿Qué versión conserva mejor el tono?" }, { phrase: "The translator chose a natural equivalent.", translation: "El traductor eligió un equivalente natural." },
    ], [
      { speaker: "A", text: "Why not use a literal translation here?", translation: "¿Por qué no usar una traducción literal aquí?" }, { speaker: "B", text: "The idiom is culture-bound and would sound unnatural.", translation: "El modismo está ligado a la cultura y sonaría poco natural." }, { speaker: "A", text: "Could we paraphrase it instead?", translation: "¿Podríamos parafrasearlo en su lugar?" }, { speaker: "B", text: "Yes, or use a rendition that preserves its pragmatic effect.", translation: "Sí, o usar una versión que conserve su efecto pragmático." },
    ], { title: "Choosing What to Preserve", text: "A translator rarely transfers words without making choices. An idiom may be untranslatable literally, a proper name may need transliteration, and a calque may sound unfamiliar in the target language. A strong rendition therefore balances semantic precision, cultural resonance, register, and the reader's expectations.", translation: "Un traductor rara vez transfiere palabras sin tomar decisiones. Un modismo puede ser intraducible literalmente, un nombre propio puede necesitar transliteración y un calco puede sonar poco familiar en la lengua meta. Por eso, una buena versión equilibra la precisión semántica, la resonancia cultural, el registro y las expectativas del lector." }),
  ],
};
