import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/**
 * Reviewed enrichment for the next existing B1/B2/C1 units.
 * This bank contains vocabulary only; it never declares or creates units.
 */
export const ENGLISH_B1_B2_C1_NEXT_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u50: [
      reviewed({ word: "participatory budgeting", translation: "الموازنة التشاركية", pos: "noun", ipa: "/pɑːrˌtɪsəpətɔːri ˈbʌdʒɪtɪŋ/", definition: "a process in which residents help decide how public money is spent", example: "Participatory budgeting allowed residents to choose which park improvements came first.", exampleTranslation: "أتاحت الموازنة التشاركية للسكان اختيار تحسينات الحديقة التي تأتي أولًا.", category: "community decisions", tags: ["community", "citizenship"], synonyms: ["community budgeting", "citizen-led budgeting"] }),
      reviewed({ word: "civic forum", translation: "منتدى مدني", pos: "noun", ipa: "/ˈsɪvɪk ˌfɔːrəm/", definition: "a public meeting where people discuss issues affecting their community", example: "The civic forum gave residents a chance to question the transport plan.", exampleTranslation: "منح المنتدى المدني السكان فرصة لطرح أسئلة حول خطة النقل.", category: "community decisions", tags: ["community", "discussion"], synonyms: ["public forum", "citizens' meeting"] }),
      reviewed({ word: "stakeholder mapping", translation: "رسم خريطة أصحاب المصلحة", pos: "noun", ipa: "/ˈsteɪkhoʊldər ˌmæpɪŋ/", definition: "the process of identifying people or groups affected by a decision", example: "Stakeholder mapping showed that the proposal affected renters as well as shop owners.", exampleTranslation: "أظهر رسم خريطة أصحاب المصلحة أن المقترح يؤثر في المستأجرين وأصحاب المتاجر أيضًا.", category: "community decisions", tags: ["community", "planning"], synonyms: ["interest-group analysis", "stakeholder analysis"] }),
      reviewed({ word: "public hearing", translation: "جلسة استماع عامة", pos: "noun", ipa: "/ˌpʌblɪk ˈhɪrɪŋ/", definition: "an official meeting where members of the public can express views on a proposal", example: "Residents spoke at the public hearing before the council voted.", exampleTranslation: "تحدث السكان في جلسة الاستماع العامة قبل أن يصوت المجلس.", category: "community decisions", tags: ["community", "government"], synonyms: ["open hearing", "public consultation"] }),
      reviewed({ word: "deliberation", translation: "مداولة / تداول", pos: "noun", ipa: "/dɪˌlɪbəˈreɪʃən/", definition: "careful discussion before reaching a decision", example: "After several hours of deliberation, the committee reached a shared recommendation.", exampleTranslation: "بعد عدة ساعات من المداولة، توصلت اللجنة إلى توصية مشتركة.", category: "community decisions", tags: ["discussion", "decisions"], synonyms: ["careful discussion", "consideration"] }),
      reviewed({ word: "consensus-building", translation: "بناء التوافق", pos: "noun", ipa: "/kənˈsensəs ˌbɪldɪŋ/", definition: "the process of helping a group develop broad agreement", example: "Consensus-building took time because the neighbourhood had different priorities.", exampleTranslation: "استغرق بناء التوافق وقتًا لأن للحي أولويات مختلفة.", category: "community decisions", tags: ["community", "cooperation"], synonyms: ["agreement-building", "reaching common ground"] }),
      reviewed({ word: "policy trade-off", translation: "مفاضلة في السياسة", pos: "noun", ipa: "/ˈpɑːləsi ˈtreɪd ɔːf/", definition: "a situation in which gaining one policy benefit requires accepting another disadvantage", example: "The policy trade-off was lower traffic in exchange for fewer parking spaces.", exampleTranslation: "كانت المفاضلة في السياسة هي تقليل حركة المرور مقابل عدد أقل من مواقف السيارات.", category: "community decisions", tags: ["policy", "decisions"], synonyms: ["policy compromise", "competing priority"] }),
      reviewed({ word: "local initiative", translation: "مبادرة محلية", pos: "noun", ipa: "/ˈloʊkəl ɪˈnɪʃətɪv/", definition: "an action or project started by people in a particular local area", example: "A local initiative turned an empty plot into a shared vegetable garden.", exampleTranslation: "حوّلت مبادرة محلية قطعة أرض مهجورة إلى حديقة خضروات مشتركة.", category: "community decisions", tags: ["community", "action"], synonyms: ["neighbourhood project", "grassroots initiative"] }),
    ],
    u51: [
      reviewed({ word: "hindsight", translation: "معرفة لاحقة / رؤية بأثر رجعي", pos: "noun", ipa: "/ˈhaɪndsaɪt/", definition: "understanding of a situation only after it has happened", example: "In hindsight, the team should have tested the equipment earlier.", exampleTranslation: "معرفةً لاحقة، كان ينبغي للفريق اختبار المعدات في وقت أبكر.", category: "learning from experience", tags: ["reflection", "learning"], synonyms: ["retrospective understanding", "after-the-event insight"] }),
      reviewed({ word: "turning point", translation: "نقطة تحوّل", pos: "noun", ipa: "/ˈtɜːrnɪŋ pɔɪnt/", definition: "a moment when a situation begins to change in an important way", example: "The first successful presentation was a turning point in her confidence.", exampleTranslation: "كان العرض الناجح الأول نقطة تحول في ثقتها بنفسها.", category: "learning from experience", tags: ["progress", "change"], synonyms: ["decisive moment", "watershed"] }),
      reviewed({ word: "reflective practice", translation: "ممارسة تأملية", pos: "noun", ipa: "/rɪˌflektɪv ˈpræktɪs/", definition: "the habit of examining one’s actions to improve future performance", example: "Reflective practice helped the teacher adapt the next lesson.", exampleTranslation: "ساعدت الممارسة التأملية المعلم على تكييف الدرس التالي.", category: "learning from experience", tags: ["reflection", "development"], synonyms: ["structured reflection", "professional reflection"] }),
      reviewed({ word: "lessons learned", translation: "الدروس المستفادة", pos: "noun", ipa: "/ˌlesənz ˈlɜːrnd/", definition: "knowledge gained from reviewing what happened in a project or experience", example: "The team recorded its lessons learned before starting the next project.", exampleTranslation: "سجل الفريق الدروس المستفادة قبل بدء المشروع التالي.", category: "learning from experience", tags: ["learning", "projects"], synonyms: ["learning points", "takeaways"] }),
      reviewed({ word: "adaptive strategy", translation: "استراتيجية تكيفية", pos: "noun", ipa: "/əˈdæptɪv ˈstrætədʒi/", definition: "a plan that changes in response to new information or circumstances", example: "An adaptive strategy allowed the group to respond to unexpected delays.", exampleTranslation: "سمحت استراتيجية تكيفية للمجموعة بالاستجابة للتأخيرات غير المتوقعة.", category: "learning from experience", tags: ["adaptation", "planning"], synonyms: ["flexible plan", "responsive approach"] }),
      reviewed({ word: "transferable skill", translation: "مهارة قابلة للنقل", pos: "noun", ipa: "/trænsˈfɜːrəbəl skɪl/", definition: "an ability that can be useful in different jobs, subjects, or situations", example: "Clear writing is a transferable skill that supports many careers.", exampleTranslation: "الكتابة الواضحة مهارة قابلة للنقل تدعم مسارات مهنية كثيرة.", category: "learning from experience", tags: ["skills", "career"], synonyms: ["portable skill", "cross-context skill"] }),
      reviewed({ word: "learning curve", translation: "منحنى التعلم", pos: "noun", ipa: "/ˈlɜːrnɪŋ kɜːrv/", definition: "the rate at which someone becomes more skilled at a new activity", example: "There was a steep learning curve when the office changed its software.", exampleTranslation: "كان هناك منحنى تعلم حاد عندما غيّر المكتب برامجه.", category: "learning from experience", tags: ["learning", "work"], synonyms: ["skill-development curve", "progress rate"] }),
      reviewed({ word: "resilience", translation: "القدرة على الصمود", pos: "noun", ipa: "/rɪˈzɪliəns/", definition: "the ability to recover and continue after difficulty or failure", example: "Her resilience helped her return to the course after a disappointing result.", exampleTranslation: "ساعدتها قدرتها على الصمود على العودة إلى الدورة بعد نتيجة مخيبة.", category: "learning from experience", tags: ["resilience", "wellbeing"], synonyms: ["adaptability", "emotional strength"] }),
    ],
  },
  B2: {
    u50: [
      reviewed({ word: "market positioning", translation: "التموضع السوقي", pos: "noun", ipa: "/ˈmɑːrkɪt pəˈzɪʃənɪŋ/", definition: "the way a company presents a product in relation to competing products", example: "Clear market positioning helped the new service appeal to small businesses.", exampleTranslation: "ساعد التموضع السوقي الواضح الخدمة الجديدة على جذب الشركات الصغيرة.", category: "business strategy", tags: ["business", "marketing"], synonyms: ["brand positioning", "market stance"] }),
      reviewed({ word: "competitive advantage", translation: "ميزة تنافسية", pos: "noun", ipa: "/kəmˌpetətɪv ədˈvæntɪdʒ/", definition: "a quality that enables a company to perform better than its competitors", example: "Reliable customer support became the company’s main competitive advantage.", exampleTranslation: "أصبح دعم العملاء الموثوق الميزة التنافسية الرئيسية للشركة.", category: "business strategy", tags: ["business", "competition"], synonyms: ["market edge", "competitive strength"] }),
      reviewed({ word: "revenue stream", translation: "مصدر إيرادات", pos: "noun", ipa: "/ˈrevənuː striːm/", definition: "a source from which a business regularly earns money", example: "The subscription service created a stable revenue stream.", exampleTranslation: "أنشأت خدمة الاشتراك مصدر إيرادات مستقرًا.", category: "business strategy", tags: ["business", "finance"], synonyms: ["income source", "sales channel"] }),
      reviewed({ word: "operating margin", translation: "هامش التشغيل", pos: "noun", ipa: "/ˈɑːpəreɪtɪŋ ˈmɑːrdʒɪn/", definition: "the proportion of revenue left after operating costs are paid", example: "The company improved its operating margin by reducing unnecessary costs.", exampleTranslation: "حسنت الشركة هامش التشغيل بخفض التكاليف غير الضرورية.", category: "business strategy", tags: ["business", "finance"], synonyms: ["operating profit margin", "profitability margin"] }),
      reviewed({ word: "strategic objective", translation: "هدف استراتيجي", pos: "noun", ipa: "/strəˌtiːdʒɪk əbˈdʒektɪv/", definition: "a major result an organisation plans to achieve over time", example: "Expanding access was a strategic objective of the five-year plan.", exampleTranslation: "كان توسيع الوصول هدفًا استراتيجيًا للخطة الخمسية.", category: "business strategy", tags: ["business", "planning"], synonyms: ["long-term goal", "strategic aim"] }),
      reviewed({ word: "customer segmentation", translation: "تقسيم العملاء إلى شرائح", pos: "noun", ipa: "/ˈkʌstəmər ˌseɡmənˈteɪʃən/", definition: "the practice of dividing customers into groups with similar needs or characteristics", example: "Customer segmentation revealed that students preferred a lower-cost plan.", exampleTranslation: "كشف تقسيم العملاء إلى شرائح أن الطلاب يفضلون خطة أقل تكلفة.", category: "business strategy", tags: ["business", "marketing"], synonyms: ["market segmentation", "customer grouping"] }),
      reviewed({ word: "risk appetite", translation: "الرغبة في المخاطرة", pos: "noun", ipa: "/rɪsk ˈæpətaɪt/", definition: "the amount and type of risk an organisation is willing to accept", example: "The board reviewed its risk appetite before approving the overseas investment.", exampleTranslation: "راجع مجلس الإدارة رغبته في المخاطرة قبل الموافقة على الاستثمار الخارجي.", category: "business strategy", tags: ["business", "risk"], synonyms: ["risk tolerance", "willingness to take risk"] }),
      reviewed({ word: "growth forecast", translation: "توقع النمو", pos: "noun", ipa: "/ɡroʊθ ˈfɔːrkæst/", definition: "an estimate of how much a company or market is expected to grow", example: "The revised growth forecast reflected weaker demand in the region.", exampleTranslation: "عكس توقع النمو المعدل طلبًا أضعف في المنطقة.", category: "business strategy", tags: ["business", "planning"], synonyms: ["growth projection", "expansion estimate"] }),
    ],
    u51: [
      reviewed({ word: "negotiation tactic", translation: "تكتيك تفاوضي", pos: "noun", ipa: "/nɪˌɡoʊʃiˈeɪʃən ˈtæktɪk/", definition: "a specific method used to influence the result of a negotiation", example: "Delaying the decision was a negotiation tactic rather than a sign of agreement.", exampleTranslation: "كان تأجيل القرار تكتيكًا تفاوضيًا وليس علامة على الاتفاق.", category: "negotiating an agreement", tags: ["negotiation", "communication"], synonyms: ["bargaining tactic", "negotiating method"] }),
      reviewed({ word: "reservation point", translation: "نقطة الانسحاب", pos: "noun", ipa: "/ˌrezərˈveɪʃən pɔɪnt/", definition: "the least favourable deal a person is willing to accept", example: "The buyer set a reservation point before entering the meeting.", exampleTranslation: "حدد المشتري نقطة انسحاب قبل دخول الاجتماع.", category: "negotiating an agreement", tags: ["negotiation", "decisions"], synonyms: ["walk-away point", "minimum acceptable offer"] }),
      reviewed({ word: "mutual concession", translation: "تنازل متبادل", pos: "noun", ipa: "/ˌmjuːtʃuəl kənˈseʃən/", definition: "a compromise in which each side gives up something to reach agreement", example: "The final deal depended on a mutual concession over delivery dates.", exampleTranslation: "اعتمد الاتفاق النهائي على تنازل متبادل بشأن مواعيد التسليم.", category: "negotiating an agreement", tags: ["negotiation", "compromise"], synonyms: ["reciprocal compromise", "shared concession"] }),
      reviewed({ word: "settlement terms", translation: "شروط التسوية", pos: "noun", ipa: "/ˈsetəlmənt tɜːrmz/", definition: "the conditions agreed to resolve a dispute or complete an arrangement", example: "Both parties reviewed the settlement terms with their advisers.", exampleTranslation: "راجع الطرفان شروط التسوية مع مستشاريهما.", category: "negotiating an agreement", tags: ["negotiation", "contracts"], synonyms: ["resolution conditions", "agreed terms"] }),
      reviewed({ word: "bargaining power", translation: "القوة التفاوضية", pos: "noun", ipa: "/ˈbɑːrɡənɪŋ ˌpaʊər/", definition: "the ability of one side in a negotiation to influence the outcome", example: "A shortage of suppliers increased the contractor’s bargaining power.", exampleTranslation: "زاد نقص الموردين القوة التفاوضية للمقاول.", category: "negotiating an agreement", tags: ["negotiation", "business"], synonyms: ["negotiating leverage", "influence at the table"] }),
      reviewed({ word: "good-faith bargaining", translation: "تفاوض بحسن نية", pos: "noun", ipa: "/ˌɡʊd ˈfeɪθ ˈbɑːrɡənɪŋ/", definition: "negotiation carried out honestly and with a genuine intention to reach agreement", example: "Good-faith bargaining requires both sides to consider reasonable proposals.", exampleTranslation: "يتطلب التفاوض بحسن نية أن ينظر الطرفان في المقترحات المعقولة.", category: "negotiating an agreement", tags: ["negotiation", "ethics"], synonyms: ["honest negotiation", "genuine bargaining"] }),
      reviewed({ word: "fallback position", translation: "موقف بديل", pos: "noun", ipa: "/ˈfɔːlbæk pəˌzɪʃən/", definition: "an alternative plan used if the preferred agreement cannot be reached", example: "The team prepared a fallback position in case the supplier rejected the offer.", exampleTranslation: "أعد الفريق موقفًا بديلًا في حال رفض المورد العرض.", category: "negotiating an agreement", tags: ["negotiation", "planning"], synonyms: ["backup position", "alternative plan"] }),
      reviewed({ word: "implementation schedule", translation: "جدول التنفيذ", pos: "noun", ipa: "/ˌɪmplɪmenˈteɪʃən ˈskedʒuːl/", definition: "a timetable showing when the parts of an agreement will be carried out", example: "The contract included an implementation schedule with three review dates.", exampleTranslation: "تضمن العقد جدول تنفيذ بثلاثة مواعيد للمراجعة.", category: "negotiating an agreement", tags: ["negotiation", "projects"], synonyms: ["delivery timetable", "execution plan"] }),
    ],
  },
  C1: {
    u50: [
      reviewed({ word: "institutional framework", translation: "إطار مؤسسي", pos: "noun", ipa: "/ˌɪnstɪˈtuːʃənəl ˈfreɪmwɜːrk/", definition: "the system of organisations, rules, and procedures that shapes public action", example: "The reform changed the institutional framework for regulating elections.", exampleTranslation: "غيّر الإصلاح الإطار المؤسسي لتنظيم الانتخابات.", category: "political institutions", tags: ["politics", "government"], synonyms: ["governance framework", "institutional system"] }),
      reviewed({ word: "separation of powers", translation: "فصل السلطات", pos: "noun", ipa: "/ˌsepəˈreɪʃən əv ˈpaʊərz/", definition: "the division of state authority among different branches of government", example: "The separation of powers is intended to prevent excessive concentration of authority.", exampleTranslation: "يهدف فصل السلطات إلى منع التركيز المفرط للسلطة.", category: "political institutions", tags: ["politics", "law"], synonyms: ["division of powers", "checks between branches"] }),
      reviewed({ word: "legislative oversight", translation: "رقابة تشريعية", pos: "noun", ipa: "/ˈledʒɪsleɪtɪv ˈoʊvərsaɪt/", definition: "the process by which a legislature examines the actions of the executive", example: "Legislative oversight exposed weaknesses in the emergency procurement process.", exampleTranslation: "كشفت الرقابة التشريعية نقاط ضعف في عملية الشراء الطارئة.", category: "political institutions", tags: ["politics", "accountability"], synonyms: ["parliamentary scrutiny", "legislative supervision"] }),
      reviewed({ word: "constitutional mandate", translation: "تفويض دستوري", pos: "noun", ipa: "/ˌkɑːnstəˈtuːʃənəl ˈmændeɪt/", definition: "an authority or duty granted by a constitution", example: "The commission acted within its constitutional mandate.", exampleTranslation: "تصرفت اللجنة ضمن تفويضها الدستوري.", category: "political institutions", tags: ["politics", "law"], synonyms: ["constitutional authority", "charter-based duty"] }),
      reviewed({ word: "executive branch", translation: "السلطة التنفيذية", pos: "noun", ipa: "/ɪɡˈzekjətɪv bræntʃ/", definition: "the branch of government responsible for implementing laws and managing public administration", example: "The executive branch proposed a budget for the coming year.", exampleTranslation: "اقترحت السلطة التنفيذية ميزانية للعام المقبل.", category: "political institutions", tags: ["politics", "government"], synonyms: ["executive authority", "administrative branch"] }),
      reviewed({ word: "judicial independence", translation: "استقلال القضاء", pos: "noun", ipa: "/dʒuːˈdɪʃəl ˌɪndɪˈpendəns/", definition: "the principle that courts should decide cases without political interference", example: "Judicial independence is essential for public confidence in the rule of law.", exampleTranslation: "يُعد استقلال القضاء ضروريًا لثقة الجمهور في سيادة القانون.", category: "political institutions", tags: ["politics", "law"], synonyms: ["independent judiciary", "court autonomy"] }),
      reviewed({ word: "electoral accountability", translation: "مساءلة انتخابية", pos: "noun", ipa: "/ɪˌlektərəl əˌkaʊntəˈbɪləti/", definition: "the idea that elected officials are answerable to voters for their performance", example: "Electoral accountability depends on informed voters and transparent results.", exampleTranslation: "تعتمد المساءلة الانتخابية على ناخبين مطلعين ونتائج شفافة.", category: "political institutions", tags: ["politics", "democracy"], synonyms: ["voter accountability", "democratic answerability"] }),
      reviewed({ word: "checks and balances", translation: "ضوابط وتوازنات", pos: "noun", ipa: "/ˌtʃeks ənd ˈbælənsɪz/", definition: "arrangements that allow different institutions to limit one another’s power", example: "Checks and balances can reduce the risk of unilateral decisions.", exampleTranslation: "يمكن للضوابط والتوازنات أن تقلل خطر القرارات الأحادية.", category: "political institutions", tags: ["politics", "accountability"], synonyms: ["institutional restraints", "power controls"] }),
    ],
    u51: [
      reviewed({ word: "research paradigm", translation: "نموذج بحثي", pos: "noun", ipa: "/rɪˈsɜːrtʃ ˌpærədaɪm/", definition: "a broad set of assumptions that guides how research questions and evidence are understood", example: "The research paradigm influenced which kinds of evidence the team considered valid.", exampleTranslation: "أثر النموذج البحثي في أنواع الأدلة التي اعتبرها الفريق صالحة.", category: "research design", tags: ["research", "theory"], synonyms: ["research worldview", "methodological paradigm"] }),
      reviewed({ word: "sampling bias", translation: "تحيز أخذ العينات", pos: "noun", ipa: "/ˈsæmplɪŋ baɪəs/", definition: "a distortion caused when a sample does not represent the wider population", example: "Sampling bias made the survey results less reliable for rural participants.", exampleTranslation: "جعل تحيز أخذ العينات نتائج الاستبيان أقل موثوقية للمشاركين في المناطق الريفية.", category: "research design", tags: ["research", "data"], synonyms: ["sample bias", "selection distortion"] }),
      reviewed({ word: "validity evidence", translation: "دليل الصلاحية", pos: "noun", ipa: "/vəˈlɪdəti ˈevɪdəns/", definition: "evidence showing that a measure supports the interpretation made from its results", example: "The researchers presented validity evidence for the new assessment scale.", exampleTranslation: "قدم الباحثون دليل الصلاحية لمقياس التقييم الجديد.", category: "research design", tags: ["research", "measurement"], synonyms: ["evidence of validity", "measurement support"] }),
      reviewed({ word: "construct validity", translation: "صلاحية البناء النظري", pos: "noun", ipa: "/ˈkɑːnstrʌkt vəˈlɪdəti/", definition: "the extent to which a measure represents the theoretical concept it is intended to measure", example: "The study tested the construct validity of its measure of social trust.", exampleTranslation: "اختبرت الدراسة صلاحية البناء النظري لمقياسها للثقة الاجتماعية.", category: "research design", tags: ["research", "measurement"], synonyms: ["concept validity", "theoretical validity"] }),
      reviewed({ word: "causal pathway", translation: "مسار سببي", pos: "noun", ipa: "/ˈkɔːzəl ˈpæθweɪ/", definition: "the sequence of processes through which one factor produces a change in another", example: "The model describes a causal pathway linking early support to later achievement.", exampleTranslation: "يصف النموذج مسارًا سببيًا يربط بين الدعم المبكر والإنجاز اللاحق.", category: "research design", tags: ["research", "analysis"], synonyms: ["cause-and-effect pathway", "mechanism of influence"] }),
      reviewed({ word: "longitudinal design", translation: "تصميم طولي", pos: "noun", ipa: "/ˌlɑːndʒəˈtuːdənəl dɪˈzaɪn/", definition: "a research design that follows the same participants or variables over time", example: "A longitudinal design revealed how attitudes changed across five years.", exampleTranslation: "كشف التصميم الطولي كيف تغيرت المواقف خلال خمس سنوات.", category: "research design", tags: ["research", "time"], synonyms: ["long-term study design", "panel design"] }),
      reviewed({ word: "pilot study", translation: "دراسة تجريبية أولية", pos: "noun", ipa: "/ˈpaɪlət ˌstʌdi/", definition: "a small preliminary study used to test methods before a larger investigation", example: "The pilot study revealed that two questions were difficult to understand.", exampleTranslation: "كشفت الدراسة التجريبية الأولية أن سؤالين كانا صعبي الفهم.", category: "research design", tags: ["research", "methods"], synonyms: ["preliminary study", "feasibility study"] }),
      reviewed({ word: "coding scheme", translation: "نظام ترميز", pos: "noun", ipa: "/ˈkoʊdɪŋ skiːm/", definition: "a set of categories and rules used to classify research data", example: "The team revised its coding scheme after comparing several interview transcripts.", exampleTranslation: "راجع الفريق نظام الترميز بعد مقارنة عدة نصوص للمقابلات.", category: "research design", tags: ["research", "qualitative"], synonyms: ["coding framework", "classification scheme"] }),
    ],
  },
};
