import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/** Reviewed vocabulary for the existing B1/B2/C1 u26 and u27 units. */
export const ENGLISH_B1_B2_C1_U26_U27_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u26: [
      reviewed({ word: "acquaintance", translation: "معرفة", pos: "noun", ipa: "/əˈkweɪntəns/", definition: "a person you know slightly but not as a close friend", example: "An old acquaintance invited me to the family celebration.", exampleTranslation: "دعاني أحد المعارف القدامى إلى احتفال العائلة.", category: "friendship and family", tags: ["relationships", "social life"], synonyms: ["contact", "associate"] }),
      reviewed({ word: "relative", translation: "قريب", pos: "noun", ipa: "/ˈrelətɪv/", definition: "a member of your family", example: "Every relative brought a dish to the family meal.", exampleTranslation: "أحضر كل قريب طبقًا إلى وجبة العائلة.", category: "friendship and family", tags: ["family", "relationships"], synonyms: ["family member", "relation"] }),
      reviewed({ word: "childhood", translation: "الطفولة", pos: "noun", ipa: "/ˈtʃaɪldhʊd/", definition: "the period of a person's life when they are a child", example: "They have been friends since childhood.", exampleTranslation: "إنهما صديقان منذ الطفولة.", category: "friendship and family", tags: ["family", "life stages"], synonyms: ["early years", "youth"] }),
      reviewed({ word: "family bond", translation: "رابطة عائلية", pos: "noun", ipa: "/ˈfæməli bɒnd/", definition: "a strong connection between members of a family", example: "Shared traditions helped strengthen their family bond.", exampleTranslation: "ساعدت التقاليد المشتركة على تقوية رابطتهم العائلية.", category: "friendship and family", tags: ["family", "connection"], synonyms: ["family connection", "kinship"] }),
      reviewed({ word: "mutual understanding", translation: "تفاهم متبادل", pos: "noun", ipa: "/ˌmjuːtʃuəl ˌʌndəˈstændɪŋ/", definition: "a shared awareness of each person's feelings, needs, or intentions", example: "Honest conversation created mutual understanding between the two friends.", exampleTranslation: "أوجد الحوار الصادق تفاهمًا متبادلًا بين الصديقين.", category: "friendship and family", tags: ["communication", "relationships"], synonyms: ["shared understanding", "rapport"] }),
      reviewed({ word: "dependable", translation: "موثوق", pos: "adjective", ipa: "/dɪˈpendəbəl/", definition: "able to be trusted to do what is expected", example: "She is a dependable friend who always keeps her promises.", exampleTranslation: "إنها صديقة موثوقة تفي بوعودها دائمًا.", category: "friendship and family", tags: ["character", "trust"], synonyms: ["reliable", "trustworthy"], antonyms: ["unreliable"] }),
      reviewed({ word: "make amends", translation: "يصلح ما أفسده", pos: "verb", ipa: "/meɪk əˈmendz/", definition: "to do something to show that you are sorry for causing harm or upset", example: "He apologised and tried to make amends after the argument.", exampleTranslation: "اعتذر وحاول إصلاح ما أفسده بعد الشجار.", category: "friendship and family", tags: ["conflict", "apology"], synonyms: ["repair the relationship", "put things right"] }),
      reviewed({ word: "confidant", translation: "موضع ثقة", pos: "noun", ipa: "/ˈkɒnfɪdænt/", definition: "a trusted person with whom you share private thoughts and feelings", example: "Her sister became her closest confidant during the difficult year.", exampleTranslation: "أصبحت أختها موضع ثقتها الأقرب خلال السنة الصعبة.", category: "friendship and family", tags: ["trust", "friendship"], synonyms: ["trusted friend", "companion"] }),
    ],
    u27: [
      reviewed({ word: "alarm clock", translation: "منبّه", pos: "noun", ipa: "/əˈlɑːm klɒk/", definition: "a clock that makes a sound at a set time to wake someone", example: "I set my alarm clock before going to bed.", exampleTranslation: "ضبطت المنبّه قبل الذهاب إلى النوم.", category: "daily routine", tags: ["morning", "time"], synonyms: ["alarm", "wake-up clock"] }),
      reviewed({ word: "daybreak", translation: "بزوغ الفجر", pos: "noun", ipa: "/ˈdeɪbreɪk/", definition: "the first light of the day before the sun has fully risen", example: "The fishermen left the harbour at daybreak.", exampleTranslation: "غادر الصيادون الميناء عند بزوغ الفجر.", category: "daily routine", tags: ["morning", "time"], synonyms: ["dawn", "sunrise"] }),
      reviewed({ word: "midday", translation: "منتصف النهار", pos: "noun", ipa: "/ˌmɪdˈdeɪ/", definition: "twelve o'clock in the middle of the day", example: "The temperature is usually highest around midday.", exampleTranslation: "تكون درجة الحرارة عادة في أعلى مستوياتها قرب منتصف النهار.", category: "daily routine", tags: ["time", "afternoon"], synonyms: ["noon", "twelve o'clock"] }),
      reviewed({ word: "lunchtime", translation: "وقت الغداء", pos: "noun", ipa: "/ˈlʌntʃtaɪm/", definition: "the time of day when people usually eat lunch", example: "The café is busiest at lunchtime.", exampleTranslation: "يكون المقهى أكثر ازدحامًا وقت الغداء.", category: "daily routine", tags: ["meals", "schedule"], synonyms: ["lunch hour", "midday meal"] }),
      reviewed({ word: "afternoon slump", translation: "خمول فترة بعد الظهر", pos: "noun", ipa: "/ˌɑːftəˈnuːn slʌmp/", definition: "a period of low energy during the afternoon", example: "A short walk helps me overcome the afternoon slump.", exampleTranslation: "يساعدني المشي القصير على التغلب على خمول فترة بعد الظهر.", category: "daily routine", tags: ["energy", "afternoon"], synonyms: ["afternoon tiredness", "energy dip"] }),
      reviewed({ word: "evening wind-down", translation: "الاسترخاء المسائي", pos: "noun", ipa: "/ˈiːvnɪŋ waɪnd daʊn/", definition: "a calm period used to relax before going to sleep", example: "Reading is part of my evening wind-down.", exampleTranslation: "تُعد القراءة جزءًا من استرخائي المسائي.", category: "daily routine", tags: ["evening", "relaxation"], synonyms: ["bedtime relaxation", "quiet evening"] }),
      reviewed({ word: "sleep schedule", translation: "جدول النوم", pos: "noun", ipa: "/sliːp ˈʃedjuːl/", definition: "the regular times when a person goes to sleep and wakes up", example: "Travelling across time zones disrupted her sleep schedule.", exampleTranslation: "أدى السفر عبر المناطق الزمنية إلى اضطراب جدول نومها.", category: "daily routine", tags: ["sleep", "health"], synonyms: ["sleep routine", "bedtime pattern"] }),
      reviewed({ word: "well-rested", translation: "حاصل على قسط كاف من الراحة", pos: "adjective", ipa: "/ˌwel ˈrestɪd/", definition: "having had enough sleep or relaxation", example: "I feel well-rested after following the new routine.", exampleTranslation: "أشعر أنني حصلت على قسط كاف من الراحة بعد اتباع الروتين الجديد.", category: "daily routine", tags: ["sleep", "health"], synonyms: ["refreshed", "rejuvenated"], antonyms: ["exhausted"] }),
    ],
  },
  B2: {
    u26: [
      reviewed({ word: "high-rise development", translation: "تطوير مبانٍ شاهقة", pos: "noun", ipa: "/ˈhaɪ raɪz dɪˈveləpmənt/", definition: "a planned project involving tall buildings in an urban area", example: "The high-rise development will include homes, shops, and public spaces.", exampleTranslation: "سيشمل تطوير المباني الشاهقة مساكن ومتاجر ومساحات عامة.", category: "urbanization", tags: ["cities", "housing"], synonyms: ["tower-block project", "vertical development"] }),
      reviewed({ word: "metropolitan expansion", translation: "التوسع الحضري للمدينة الكبرى", pos: "noun", ipa: "/ˌmetrəˈpɒlɪtən ɪkˈspænʃən/", definition: "the growth of a large city into surrounding areas", example: "Metropolitan expansion has placed pressure on nearby farmland.", exampleTranslation: "فرض التوسع الحضري للمدينة الكبرى ضغطًا على الأراضي الزراعية القريبة.", category: "urbanization", tags: ["cities", "planning"], synonyms: ["city growth", "urban expansion"] }),
      reviewed({ word: "population density", translation: "الكثافة السكانية", pos: "noun", ipa: "/ˌpɒpjəˈleɪʃən ˈdensəti/", definition: "the number of people living in a particular area", example: "High population density can make public transport more efficient.", exampleTranslation: "يمكن أن تجعل الكثافة السكانية العالية النقل العام أكثر كفاءة.", category: "urbanization", tags: ["cities", "population"], synonyms: ["population concentration", "crowding"] }),
      reviewed({ word: "pedestrian zone", translation: "منطقة للمشاة", pos: "noun", ipa: "/pəˈdestriən zəʊn/", definition: "an area of a town where vehicles are restricted and people walk", example: "The historic centre became a pedestrian zone at weekends.", exampleTranslation: "أصبح المركز التاريخي منطقة للمشاة في عطلات نهاية الأسبوع.", category: "urbanization", tags: ["transport", "public space"], synonyms: ["car-free area", "walking district"] }),
      reviewed({ word: "skyline", translation: "أفق المدينة", pos: "noun", ipa: "/ˈskaɪlaɪn/", definition: "the outline of buildings and land seen against the sky", example: "The new tower has changed the city's skyline.", exampleTranslation: "غيّر البرج الجديد أفق المدينة.", category: "urbanization", tags: ["cities", "architecture"], synonyms: ["city outline", "urban profile"] }),
      reviewed({ word: "residential district", translation: "حي سكني", pos: "noun", ipa: "/ˌrezɪˈdenʃəl ˈdɪstrɪkt/", definition: "an area of a town mainly made up of homes", example: "The residential district needs a new health centre.", exampleTranslation: "يحتاج الحي السكني إلى مركز صحي جديد.", category: "urbanization", tags: ["housing", "cities"], synonyms: ["housing area", "neighbourhood"] }),
      reviewed({ word: "traffic gridlock", translation: "اختناق مروري تام", pos: "noun", ipa: "/ˈtræfɪk ˈɡrɪdlɒk/", definition: "a situation in which traffic is completely unable to move", example: "A broken bridge caused traffic gridlock across the eastern districts.", exampleTranslation: "تسبب جسر مكسور في اختناق مروري تام عبر الأحياء الشرقية.", category: "urbanization", tags: ["transport", "infrastructure"], synonyms: ["complete traffic jam", "standstill"] }),
      reviewed({ word: "public amenity", translation: "مرفق عام", pos: "noun", ipa: "/ˌpʌblɪk əˈmiːnəti/", definition: "a useful facility or service provided for people in a community", example: "The plan protects green space as a public amenity.", exampleTranslation: "تحمي الخطة المساحات الخضراء بوصفها مرفقًا عامًا.", category: "urbanization", tags: ["cities", "public services"], synonyms: ["community facility", "public resource"] }),
    ],
    u27: [
      reviewed({ word: "host country", translation: "البلد المضيف", pos: "noun", ipa: "/həʊst ˈkʌntri/", definition: "a country that receives people who have come from another country", example: "The host country offered language classes to new arrivals.", exampleTranslation: "قدّم البلد المضيف دروسًا لغوية للقادمين الجدد.", category: "migration and refuge", tags: ["migration", "society"], synonyms: ["receiving country", "destination country"] }),
      reviewed({ word: "forced displacement", translation: "النزوح القسري", pos: "noun", ipa: "/fɔːst dɪsˈpleɪsmənt/", definition: "the movement of people away from their homes against their will", example: "The conflict caused forced displacement across the region.", exampleTranslation: "تسبب النزاع في نزوح قسري في أنحاء المنطقة.", category: "migration and refuge", tags: ["refugees", "conflict"], synonyms: ["involuntary migration", "uprooting"] }),
      reviewed({ word: "border crossing", translation: "معبر حدودي", pos: "noun", ipa: "/ˈbɔːdə ˌkrɒsɪŋ/", definition: "a place where people or vehicles can legally pass between countries", example: "The border crossing was closed after heavy snowfall.", exampleTranslation: "أُغلق المعبر الحدودي بعد تساقط الثلوج بكثافة.", category: "migration and refuge", tags: ["borders", "travel"], synonyms: ["frontier checkpoint", "border post"] }),
      reviewed({ word: "resettlement", translation: "إعادة التوطين", pos: "noun", ipa: "/ˌriːˈsetəlmənt/", definition: "the process of moving people to a new place where they can live permanently", example: "The resettlement programme gave families access to housing.", exampleTranslation: "أتاح برنامج إعادة التوطين للعائلات الوصول إلى السكن.", category: "migration and refuge", tags: ["refugees", "housing"], synonyms: ["relocation", "re-establishment"] }),
      reviewed({ word: "persecution", translation: "اضطهاد", pos: "noun", ipa: "/ˌpɜːsɪˈkjuːʃən/", definition: "unfair or cruel treatment of people because of their identity or beliefs", example: "The family fled the country to escape persecution.", exampleTranslation: "فرّت العائلة من البلاد هربًا من الاضطهاد.", category: "migration and refuge", tags: ["rights", "refugees"], synonyms: ["oppression", "harassment"] }),
      reviewed({ word: "remittance", translation: "حوالة مالية", pos: "noun", ipa: "/rɪˈmɪtəns/", definition: "money sent by someone working in one country to people in another country", example: "Remittances help many households pay for education and healthcare.", exampleTranslation: "تساعد الحوالات المالية أسرًا كثيرة على دفع تكاليف التعليم والرعاية الصحية.", category: "migration and refuge", tags: ["migration", "finance"], synonyms: ["money transfer", "funds sent home"] }),
      reviewed({ word: "transnational diaspora", translation: "شتات عابر للحدود", pos: "noun", ipa: "/ˌtrænzˈnæʃənəl daɪˈæspərə/", definition: "a dispersed population whose members maintain connections across several countries", example: "The transnational diaspora supports cultural projects in both countries.", exampleTranslation: "يدعم الشتات العابر للحدود مشاريع ثقافية في البلدين.", category: "migration and refuge", tags: ["identity", "culture"], synonyms: ["global diaspora", "overseas community"] }),
      reviewed({ word: "naturalisation", translation: "التجنيس", pos: "noun", ipa: "/ˌnætʃərəlaɪˈzeɪʃən/", definition: "the legal process by which a person becomes a citizen of a country", example: "After years of residence, she applied for naturalisation.", exampleTranslation: "بعد سنوات من الإقامة، تقدمت بطلب التجنيس.", category: "migration and refuge", tags: ["citizenship", "law"], synonyms: ["citizenship application", "legal integration"] }),
    ],
  },
  C1: {
    u26: [
      reviewed({ word: "state apparatus", translation: "جهاز الدولة", pos: "noun", ipa: "/steɪt ˌæpəˈrætəs/", definition: "the institutions and organisations through which a state exercises authority", example: "The reform aims to make the state apparatus more accountable.", exampleTranslation: "يهدف الإصلاح إلى جعل جهاز الدولة أكثر خضوعًا للمساءلة.", category: "power and state", tags: ["government", "institutions"], synonyms: ["state machinery", "government apparatus"] }),
      reviewed({ word: "executive authority", translation: "السلطة التنفيذية", pos: "noun", ipa: "/ɪɡˈzekjətɪv ɔːˈθɒrəti/", definition: "the power to implement laws and manage the administration of a state", example: "The constitution limits executive authority during emergencies.", exampleTranslation: "يحد الدستور السلطة التنفيذية أثناء حالات الطوارئ.", category: "power and state", tags: ["government", "constitution"], synonyms: ["executive power", "administrative authority"] }),
      reviewed({ word: "constitutional court", translation: "محكمة دستورية", pos: "noun", ipa: "/ˌkɒnstɪˈtjuːʃənəl kɔːt/", definition: "a court that decides whether laws and government actions comply with a constitution", example: "The constitutional court reviewed the disputed legislation.", exampleTranslation: "راجعت المحكمة الدستورية التشريع المتنازع عليه.", category: "power and state", tags: ["law", "constitution"], synonyms: ["constitutional tribunal", "supreme constitutional court"] }),
      reviewed({ word: "coercive power", translation: "قوة قسرية", pos: "noun", ipa: "/kəʊˈɜːsɪv paʊə/", definition: "the ability to make people act through threats, force, or penalties", example: "A democratic state should not rely solely on coercive power.", exampleTranslation: "لا ينبغي للدولة الديمقراطية أن تعتمد على القوة القسرية وحدها.", category: "power and state", tags: ["authority", "rights"], synonyms: ["force-based authority", "compulsion"] }),
      reviewed({ word: "political patronage", translation: "محسوبية سياسية", pos: "noun", ipa: "/pəˌlɪtɪkəl ˈpætrənɪdʒ/", definition: "the practice of giving jobs or advantages to supporters of a political group", example: "The report criticised political patronage in public appointments.", exampleTranslation: "انتقد التقرير المحسوبية السياسية في التعيينات العامة.", category: "power and state", tags: ["politics", "governance"], synonyms: ["political favouritism", "clientelism"] }),
      reviewed({ word: "civic autonomy", translation: "استقلالية مدنية", pos: "noun", ipa: "/ˈsɪvɪk ɔːˈtɒnəmi/", definition: "the ability of citizens and civic groups to organise and act independently", example: "Independent associations are essential to civic autonomy.", exampleTranslation: "تُعد الجمعيات المستقلة أساسية للاستقلالية المدنية.", category: "power and state", tags: ["citizenship", "civil society"], synonyms: ["civic independence", "community self-governance"] }),
      reviewed({ word: "regime change", translation: "تغيير النظام", pos: "noun", ipa: "/reɪˈʒiːm tʃeɪndʒ/", definition: "the replacement of one governing system or leadership by another", example: "The transition after regime change required a new constitutional settlement.", exampleTranslation: "تطلب الانتقال بعد تغيير النظام تسوية دستورية جديدة.", category: "power and state", tags: ["politics", "transitions"], synonyms: ["governmental transition", "change of government"] }),
      reviewed({ word: "territorial jurisdiction", translation: "اختصاص إقليمي", pos: "noun", ipa: "/ˌterɪˈtɔːriəl ˌdʒʊərɪsˈdɪkʃən/", definition: "the legal authority of a state or court over a particular geographical area", example: "The case raised questions about territorial jurisdiction.", exampleTranslation: "أثارت القضية أسئلة حول الاختصاص الإقليمي.", category: "power and state", tags: ["law", "sovereignty"], synonyms: ["geographical jurisdiction", "territorial authority"] }),
    ],
    u27: [
      reviewed({ word: "implied meaning", translation: "المعنى الضمني", pos: "noun", ipa: "/ɪmˈplaɪd ˈmiːnɪŋ/", definition: "an idea communicated indirectly rather than stated openly", example: "The implied meaning becomes clearer when the final paragraph is considered.", exampleTranslation: "يصبح المعنى الضمني أوضح عند النظر في الفقرة الأخيرة.", category: "interpretation and text", tags: ["meaning", "reading"], synonyms: ["unstated meaning", "implication"] }),
      reviewed({ word: "literal meaning", translation: "المعنى الحرفي", pos: "noun", ipa: "/ˈlɪtərəl ˈmiːnɪŋ/", definition: "the basic meaning of words without metaphor or interpretation", example: "The literal meaning differs from the ironic message of the sentence.", exampleTranslation: "يختلف المعنى الحرفي عن الرسالة الساخرة للجملة.", category: "interpretation and text", tags: ["meaning", "language"], synonyms: ["surface meaning", "explicit meaning"] }),
      reviewed({ word: "semantic field", translation: "حقل دلالي", pos: "noun", ipa: "/sɪˈmæntɪk fiːld/", definition: "a group of words connected by a particular area of meaning", example: "The poem draws on a semantic field associated with journeys.", exampleTranslation: "تستند القصيدة إلى حقل دلالي مرتبط بالرحلات.", category: "interpretation and text", tags: ["semantics", "analysis"], synonyms: ["lexical field", "meaning group"] }),
      reviewed({ word: "authorial intent", translation: "قصد المؤلف", pos: "noun", ipa: "/ɔːˈθɔːriəl ɪnˈtent/", definition: "what an author intended to communicate through a text", example: "The introduction gives useful clues about authorial intent.", exampleTranslation: "تقدم المقدمة دلائل مفيدة على قصد المؤلف.", category: "interpretation and text", tags: ["authors", "reading"], synonyms: ["writer's intention", "author's purpose"] }),
      reviewed({ word: "textual coherence", translation: "اتساق نصي", pos: "noun", ipa: "/ˈtekstʃuəl kəʊˈhɪərəns/", definition: "the quality of a text whose ideas and parts form a clear, connected whole", example: "Clear transitions improve the textual coherence of the essay.", exampleTranslation: "تحسن الروابط الواضحة الاتساق النصي للمقال.", category: "interpretation and text", tags: ["writing", "discourse"], synonyms: ["textual unity", "logical flow"] }),
      reviewed({ word: "interpretive openness", translation: "انفتاح تأويلي", pos: "noun", ipa: "/ɪnˈtɜːprətɪv ˈəʊpənnəs/", definition: "the extent to which a text permits more than one reasonable interpretation", example: "The novel's interpretive openness encourages debate among readers.", exampleTranslation: "يشجع الانفتاح التأويلي للرواية النقاش بين القراء.", category: "interpretation and text", tags: ["interpretation", "literature"], synonyms: ["ambiguity of interpretation", "multiple readings"] }),
      reviewed({ word: "hermeneutic lens", translation: "منظور تأويلي", pos: "noun", ipa: "/ˌhɜːməˈnjuːtɪk lenz/", definition: "a particular theory or perspective used to interpret a text", example: "A historical hermeneutic lens reveals assumptions that modern readers may miss.", exampleTranslation: "يكشف المنظور التأويلي التاريخي افتراضات قد يغفل عنها القراء المعاصرون.", category: "interpretation and text", tags: ["hermeneutics", "analysis"], synonyms: ["interpretive perspective", "reading framework"] }),
      reviewed({ word: "textual nuance", translation: "دقة نصية", pos: "noun", ipa: "/ˈtekstʃuəl ˈnjuːɑːns/", definition: "a small but meaningful distinction in the wording or interpretation of a text", example: "The translation preserves an important textual nuance.", exampleTranslation: "تحافظ الترجمة على دقة نصية مهمة.", category: "interpretation and text", tags: ["translation", "close reading"], synonyms: ["subtle distinction", "fine textual detail"] }),
    ],
  },
};
