import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/** Reviewed vocabulary for the existing B1/B2/C1 u18 and u19 units. */
export const ENGLISH_B1_B2_C1_U18_U19_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u18: [
      reviewed({ word: "embargoed release", translation: "إصدار محظور النشر", pos: "noun", ipa: "/ɪmˈbɑːrɡoʊd rɪˈliːs/", definition: "information supplied for publication only after an agreed time", example: "The newspaper respected the embargoed release until the investigation was announced.", exampleTranslation: "احترمت الصحيفة حظر نشر الأخبار حتى أُعلن عن التحقيق.", category: "news and media", tags: ["news", "media"], synonyms: ["publication ban", "reporting restriction"] }),
      reviewed({ word: "editorial desk", translation: "هيئة التحرير", pos: "noun", ipa: "/ˌedɪˈtɔːriəl desk/", definition: "the office or team responsible for selecting, checking, and preparing published material", example: "The editorial desk checked the figures before publishing the report.", exampleTranslation: "تحققت غرفة الأخبار من الأرقام قبل نشر التقرير.", category: "news and media", tags: ["news", "work"], synonyms: ["news office", "editorial office"] }),
      reviewed({ word: "source protection", translation: "حماية المصدر", pos: "noun", ipa: "/sɔːrs prəˈtekʃən/", definition: "the practice of keeping a journalist’s confidential informant safe and unidentified", example: "Source protection allowed the journalist to report the story without naming the informant.", exampleTranslation: "أتاحت حماية المصدر للصحفي نشر القصة دون ذكر اسم المخبر.", category: "news and media", tags: ["journalism", "privacy"], synonyms: ["confidential-source protection", "informant protection"] }),
      reviewed({ word: "public-service channel", translation: "قناة خدمة عامة", pos: "noun", ipa: "/ˈpʌblɪk ˈsɜːrvɪs ˈtʃænəl/", definition: "a broadcasting channel established to serve the public rather than only commercial interests", example: "The public-service channel provided election coverage in several languages.", exampleTranslation: "قدمت هيئة البث العامة تغطية انتخابية بعدة لغات.", category: "news and media", tags: ["media", "society"], synonyms: ["public-service broadcaster", "public media organisation"] }),
      reviewed({ word: "daily news brief", translation: "موجز إخباري يومي", pos: "noun", ipa: "/ˈdeɪli njuːz briːf/", definition: "a short broadcast or publication giving the latest important news", example: "The evening daily news brief included a report from the affected area.", exampleTranslation: "تضمنت النشرة الإخبارية المسائية تقريرًا من المنطقة المتضررة.", category: "news and media", tags: ["news", "broadcasting"], synonyms: ["news update", "news report"] }),
      reviewed({ word: "published correction", translation: "تصحيح منشور", pos: "noun", ipa: "/ˈpʌblɪʃt kəˈrekʃən/", definition: "a public statement that corrects an error in a published report", example: "The editor added a published correction after discovering an incorrect date.", exampleTranslation: "أضاف المحرر إشعار تصحيح بعد اكتشاف تاريخ غير صحيح.", category: "news and media", tags: ["news", "accuracy"], synonyms: ["error correction", "corrective statement"] }),
      reviewed({ word: "investigative lead", translation: "خيط تحقيقي", pos: "noun", ipa: "/ɪnˈvestɪɡətɪv liːd/", definition: "a piece of information that may help a journalist uncover a wider story", example: "A small payment record became an investigative lead for the reporter.", exampleTranslation: "أصبح سجل دفع صغير خيطًا تحقيقيًا للصحفي.", category: "news and media", tags: ["journalism", "investigation"], synonyms: ["reporting lead", "story lead"] }),
      reviewed({ word: "news correspondent", translation: "مراسل إخباري", pos: "noun", ipa: "/njuːz ˌkɔːrəˈspɑːndənt/", definition: "a journalist who reports from a particular place or on a particular subject", example: "The news correspondent described the situation from the border.", exampleTranslation: "وصف المراسل الإخباري الوضع من الحدود.", category: "news and media", tags: ["news", "journalism"], synonyms: ["news reporter", "field correspondent"] }),
    ],
    u19: [
      reviewed({ word: "content creator", translation: "منشئ محتوى", pos: "noun", ipa: "/ˈkɑːntent kriˈeɪtər/", definition: "a person who produces material for an online audience", example: "The content creator explained how she checks information before sharing it.", exampleTranslation: "شرح منشئ المحتوى كيف يتحقق من المعلومات قبل مشاركتها.", category: "social media and profile", tags: ["social media", "digital life"], synonyms: ["online creator", "digital content producer"] }),
      reviewed({ word: "engagement rate", translation: "معدل التفاعل", pos: "noun", ipa: "/ɪnˈɡeɪdʒmənt reɪt/", definition: "a measure of how actively an audience reacts to online content", example: "The campaign achieved a higher engagement rate than the previous one.", exampleTranslation: "حققت الحملة معدل تفاعل أعلى من الحملة السابقة.", category: "social media and profile", tags: ["social media", "metrics"], synonyms: ["interaction rate", "audience response rate"] }),
      reviewed({ word: "direct message", translation: "رسالة مباشرة", pos: "noun", ipa: "/dəˌrekt ˈmesɪdʒ/", definition: "a private message sent through a social platform", example: "Please send the address by direct message rather than posting it publicly.", exampleTranslation: "أرسل العنوان برسالة مباشرة بدلًا من نشره علنًا.", category: "social media and profile", tags: ["social media", "communication"], synonyms: ["private message", "personal message"] }),
      reviewed({ word: "user-generated content", translation: "محتوى ينشئه المستخدمون", pos: "noun", ipa: "/ˌjuːzər ˈdʒenəreɪtɪd ˈkɑːntent/", definition: "text, images, or videos produced and shared by members of an online service", example: "The website labels user-generated content so visitors know who created it.", exampleTranslation: "يضع الموقع تسمية على المحتوى الذي ينشئه المستخدمون حتى يعرف الزوار من أنشأه.", category: "social media and profile", tags: ["social media", "content"], synonyms: ["community-created content", "user-created media"] }),
      reviewed({ word: "online identity", translation: "هوية إلكترونية", pos: "noun", ipa: "/ˌɑːnlaɪn aɪˈdentəti/", definition: "the way a person is represented and recognised on the internet", example: "Young users should learn how to protect their online identity.", exampleTranslation: "ينبغي للمستخدمين الشباب تعلم كيفية حماية هويتهم الإلكترونية.", category: "social media and profile", tags: ["social media", "privacy"], synonyms: ["digital identity", "internet identity"] }),
      reviewed({ word: "visibility control", translation: "تحكم في الظهور", pos: "noun", ipa: "/ˌvɪzəˈbɪləti kənˈtroʊl/", definition: "an option that controls who can see or use information on an online account", example: "Check your visibility control before accepting new followers.", exampleTranslation: "تحقق من إعداد الخصوصية قبل قبول متابعين جدد.", category: "social media and profile", tags: ["social media", "privacy"], synonyms: ["privacy control", "account privacy option"] }),
      reviewed({ word: "screen-time limit", translation: "حد وقت الشاشة", pos: "noun", ipa: "/ˈskriːn taɪm ˌlɪmɪt/", definition: "a restriction on how long someone may use a digital device or service", example: "A screen-time limit helped him use social media more deliberately.", exampleTranslation: "ساعده حد وقت الشاشة على استخدام وسائل التواصل الاجتماعي بوعي أكبر.", category: "social media and profile", tags: ["social media", "wellbeing"], synonyms: ["device-use limit", "screen-use restriction"] }),
      reviewed({ word: "account suspension", translation: "تعليق الحساب", pos: "noun", ipa: "/əˈkaʊnt səˈspenʃən/", definition: "the temporary blocking of an online account because of a rule or security concern", example: "The platform issued an account suspension after repeated harmful posts.", exampleTranslation: "فرضت المنصة تعليقًا للحساب بعد منشورات ضارة متكررة.", category: "social media and profile", tags: ["social media", "rules"], synonyms: ["account restriction", "temporary account ban"] }),
    ],
  },
  B2: {
    u18: [
      reviewed({ word: "emotional exhaustion", translation: "إنهاك عاطفي", pos: "noun", ipa: "/ɪˈmoʊʃənəl ɪɡˈzɔːstʃən/", definition: "a state of feeling mentally and emotionally drained after prolonged pressure", example: "Emotional exhaustion can make ordinary decisions feel unusually difficult.", exampleTranslation: "يمكن للإنهاك العاطفي أن يجعل القرارات العادية تبدو صعبة على نحو غير معتاد.", category: "mental health and stress", tags: ["mental health", "stress"], synonyms: ["emotional fatigue", "mental depletion"] }),
      reviewed({ word: "pressure response", translation: "استجابة الضغط", pos: "noun", ipa: "/ˈpreʃər rɪˈspɑːns/", definition: "the physical and mental reaction to a demanding or threatening situation", example: "Slow breathing can reduce the body’s pressure response.", exampleTranslation: "يمكن للتنفس البطيء أن يقلل استجابة الجسم للضغط النفسي.", category: "mental health and stress", tags: ["stress", "health"], synonyms: ["stress reaction", "response to pressure"] }),
      reviewed({ word: "panic disorder", translation: "اضطراب الهلع", pos: "noun", ipa: "/ˈpænɪk dɪsˌɔːrdər/", definition: "a condition involving recurring unexpected panic attacks and concern about having more", example: "A clinician explained that panic disorder can be treated with professional support.", exampleTranslation: "شرح الطبيب أن اضطراب الهلع يمكن علاجه بالدعم المتخصص.", category: "mental health and stress", tags: ["mental health", "anxiety"], synonyms: ["recurrent panic condition", "panic-related disorder"] }),
      reviewed({ word: "therapeutic alliance", translation: "تحالف علاجي", pos: "noun", ipa: "/ˌθerəˈpjuːtɪk əˈlaɪəns/", definition: "the cooperative relationship between a person and a mental-health professional", example: "A strong therapeutic alliance can help people discuss difficult experiences safely.", exampleTranslation: "يمكن لتحالف علاجي قوي أن يساعد الناس على مناقشة التجارب الصعبة بأمان.", category: "mental health and stress", tags: ["therapy", "support"], synonyms: ["therapy relationship", "treatment partnership"] }),
      reviewed({ word: "coping technique", translation: "تقنية للتكيف", pos: "noun", ipa: "/ˈkoʊpɪŋ tekˈniːk/", definition: "a practical method for managing a difficult emotion or situation", example: "Writing a short plan became a useful coping technique during busy weeks.", exampleTranslation: "أصبحت كتابة خطة قصيرة استراتيجية مفيدة للتكيف خلال الأسابيع المزدحمة.", category: "mental health and stress", tags: ["stress", "wellbeing"], synonyms: ["coping method", "stress-management strategy"] }),
      reviewed({ word: "mental health provision", translation: "خدمات الصحة النفسية", pos: "noun", ipa: "/ˈmentəl helθ prəˈvɪʒən/", definition: "the services and support made available for people’s psychological wellbeing", example: "The report called for better mental health provision in rural areas.", exampleTranslation: "دعا التقرير إلى تحسين خدمات الصحة النفسية في المناطق الريفية.", category: "mental health and stress", tags: ["mental health", "policy"], synonyms: ["mental-health services", "psychological support provision"] }),
      reviewed({ word: "psychological wellbeing", translation: "الرفاه النفسي", pos: "noun", ipa: "/ˌsaɪkəˈlɑːdʒɪkəl ˌwelˈbiːɪŋ/", definition: "a state of healthy emotional functioning and overall mental balance", example: "Meaningful social contact contributes to psychological wellbeing.", exampleTranslation: "يسهم التواصل الاجتماعي الهادف في الرفاه النفسي.", category: "mental health and stress", tags: ["mental health", "wellbeing"], synonyms: ["mental wellbeing", "emotional wellbeing"] }),
      reviewed({ word: "wellness recovery plan", translation: "خطة تعافٍ للصحة", pos: "noun", ipa: "/ˈwelnəs rɪˈkʌvəri plæn/", definition: "an organised set of steps for returning to health or stability after difficulty", example: "The patient and counsellor agreed on a gradual wellness recovery plan.", exampleTranslation: "اتفق المريض والمرشد على خطة تعافٍ تدريجية.", category: "mental health and stress", tags: ["health", "support"], synonyms: ["rehabilitation plan", "wellbeing plan"] }),
    ],
    u19: [
      reviewed({ word: "leadership style", translation: "أسلوب القيادة", pos: "noun", ipa: "/ˈliːdərʃɪp staɪl/", definition: "the characteristic way a leader guides, supports, and makes decisions with a group", example: "Her inclusive leadership style encouraged quieter colleagues to contribute.", exampleTranslation: "شجع أسلوب قيادتها الشامل الزملاء الأكثر هدوءًا على المشاركة.", category: "leadership and team", tags: ["leadership", "teamwork"], synonyms: ["leadership approach", "management style"] }),
      reviewed({ word: "goal coherence", translation: "اتساق الأهداف", pos: "noun", ipa: "/ɡoʊl ˈkoʊhɪrəns/", definition: "the condition in which plans, resources, and actions support the same wider goals", example: "Goal coherence prevented separate departments from working towards conflicting targets.", exampleTranslation: "منع اتساق الأهداف الأقسام المنفصلة من العمل نحو أهداف متعارضة.", category: "leadership and team", tags: ["leadership", "planning"], synonyms: ["goal alignment", "strategic coordination"] }),
      reviewed({ word: "team autonomy", translation: "استقلالية الفريق", pos: "noun", ipa: "/tiːm ɔːˈtɑːnəmi/", definition: "the freedom a team has to organise its work and make appropriate decisions", example: "Team autonomy increased when the manager clarified the limits of responsibility.", exampleTranslation: "ازدادت استقلالية الفريق عندما أوضح المدير حدود المسؤولية.", category: "leadership and team", tags: ["teamwork", "management"], synonyms: ["team independence", "collective decision freedom"] }),
      reviewed({ word: "responsibility clarity", translation: "وضوح المسؤوليات", pos: "noun", ipa: "/rɪˌspɑːnsəˈbɪləti ˈklerəti/", definition: "a clear understanding of what each person is expected to do", example: "Responsibility clarity reduced duplication and delays during the project.", exampleTranslation: "قلل وضوح المسؤوليات التكرار والتأخير أثناء المشروع.", category: "leadership and team", tags: ["teamwork", "work"], synonyms: ["clarity of responsibility", "role definition"] }),
      reviewed({ word: "organisational change", translation: "تغيير مؤسسي", pos: "noun", ipa: "/ˌɔːrɡənəˈzeɪʃənəl tʃeɪndʒ/", definition: "a significant alteration to how an organisation is structured or operates", example: "Organisational change is easier when leaders explain its purpose honestly.", exampleTranslation: "يكون التغيير المؤسسي أسهل عندما يشرح القادة غايته بصدق.", category: "leadership and team", tags: ["leadership", "change"], synonyms: ["institutional change", "organisational transformation"] }),
      reviewed({ word: "workplace morale", translation: "معنويات مكان العمل", pos: "noun", ipa: "/ˈwɜːrkpleɪs məˈræl/", definition: "the general level of confidence, enthusiasm, and satisfaction among employees", example: "Transparent communication improved workplace morale after the reorganisation.", exampleTranslation: "حسن التواصل الشفاف معنويات مكان العمل بعد إعادة التنظيم.", category: "leadership and team", tags: ["work", "teamwork"], synonyms: ["staff morale", "employee spirit"] }),
      reviewed({ word: "executive decision", translation: "قرار تنفيذي", pos: "noun", ipa: "/ɪɡˈzekjətɪv dɪˈsɪʒən/", definition: "a major decision made by a senior leader or governing executive", example: "The executive decision followed several weeks of consultation.", exampleTranslation: "جاء القرار التنفيذي بعد عدة أسابيع من التشاور.", category: "leadership and team", tags: ["leadership", "decisions"], synonyms: ["senior-management decision", "leadership decision"] }),
      reviewed({ word: "leadership succession", translation: "تعاقب القيادة", pos: "noun", ipa: "/ˈliːdərʃɪp səkˈseʃən/", definition: "the process of preparing for a change from one leader to another", example: "A leadership succession plan protected the organisation from sudden disruption.", exampleTranslation: "حمت خطة تعاقب القيادة المنظمة من الاضطراب المفاجئ.", category: "leadership and team", tags: ["leadership", "planning"], synonyms: ["leadership transition", "succession process"] }),
    ],
  },
  C1: {
    u18: [
      reviewed({ word: "discursive hegemony", translation: "هيمنة خطابية", pos: "noun", ipa: "/dɪˈskɜːrsɪv hɪˈdʒeməni/", definition: "the dominance of one way of speaking or framing ideas over competing interpretations", example: "The essay examines how discursive hegemony can make an unequal system appear natural.", exampleTranslation: "تبحث المقالة كيف يمكن للهيمنة الخطابية أن تجعل نظامًا غير متكافئ يبدو طبيعيًا.", category: "power and discourse", tags: ["discourse", "power"], synonyms: ["discursive dominance", "dominant discourse"] }),
      reviewed({ word: "ideological framing", translation: "تأطير أيديولوجي", pos: "noun", ipa: "/ˌaɪdiəˈlɑːdʒɪkəl ˈfreɪmɪŋ/", definition: "the presentation of an issue through assumptions about values, interests, or social order", example: "Ideological framing influenced how the policy was described to the public.", exampleTranslation: "أثر التأطير الأيديولوجي في طريقة وصف السياسة للجمهور.", category: "power and discourse", tags: ["discourse", "ideology"], synonyms: ["ideological presentation", "ideological framing of an issue"] }),
      reviewed({ word: "power dynamic", translation: "ديناميكية السلطة", pos: "noun", ipa: "/ˈpaʊər daɪˌnæmɪk/", definition: "the way influence and control are distributed and exercised within a relationship or group", example: "The study reveals a power dynamic between institutions and marginalised communities.", exampleTranslation: "تكشف الدراسة ديناميكية سلطة بين المؤسسات والمجتمعات المهمشة.", category: "power and discourse", tags: ["power", "society"], synonyms: ["power relationship", "distribution of influence"] }),
      reviewed({ word: "political agency", translation: "فاعلية سياسية", pos: "noun", ipa: "/pəˈlɪtɪkəl ˈeɪdʒənsi/", definition: "the capacity of people or groups to act and influence political conditions", example: "The movement gave young residents a stronger sense of political agency.", exampleTranslation: "منحت الحركة السكان الشباب إحساسًا أقوى بالفاعلية السياسية.", category: "power and discourse", tags: ["politics", "agency"], synonyms: ["political capacity", "capacity for political action"] }),
      reviewed({ word: "symbolic violence", translation: "عنف رمزي", pos: "noun", ipa: "/sɪmˈbɑːlɪk ˈvaɪələns/", definition: "the subtle imposition of meanings or social hierarchies that makes domination seem legitimate", example: "The researcher links symbolic violence to assumptions about whose speech is considered educated.", exampleTranslation: "يربط الباحث العنف الرمزي بالافتراضات حول الكلام الذي يُعد متعلمًا.", category: "power and discourse", tags: ["power", "culture"], synonyms: ["symbolic domination", "cultural domination"] }),
      reviewed({ word: "persuasive technique", translation: "تقنية إقناعية", pos: "noun", ipa: "/pərˈsweɪsɪv tekˈniːk/", definition: "a deliberate technique used to make language more persuasive or memorable", example: "The repeated question is a persuasive technique that directs the audience’s attention.", exampleTranslation: "السؤال المتكرر أسلوب بلاغي يوجه انتباه الجمهور.", category: "power and discourse", tags: ["rhetoric", "language"], synonyms: ["rhetorical technique", "figure of speech"] }),
      reviewed({ word: "social reproduction", translation: "إعادة الإنتاج الاجتماعي", pos: "noun", ipa: "/ˌsoʊʃəl ˌriːprəˈdʌkʃən/", definition: "the continuation of social structures, inequalities, and cultural patterns across generations", example: "The article considers how schooling contributes to social reproduction.", exampleTranslation: "تنظر المقالة في كيفية إسهام التعليم في إعادة الإنتاج الاجتماعي.", category: "power and discourse", tags: ["society", "inequality"], synonyms: ["reproduction of social structures", "social continuity"] }),
      reviewed({ word: "counter-narrative", translation: "سردية مضادة", pos: "noun", ipa: "/ˈkaʊntər ˌnærətɪv/", definition: "an account that challenges a dominant story or interpretation", example: "The memoir offers a counter-narrative to the official history.", exampleTranslation: "تقدم المذكرات سردية مضادة للتاريخ الرسمي.", category: "power and discourse", tags: ["discourse", "identity"], synonyms: ["alternative narrative", "challenging account"] }),
    ],
    u19: [
      reviewed({ word: "epistemic injustice", translation: "ظلم معرفي", pos: "noun", ipa: "/ɪˌpɪˈstiːmɪk ɪnˈdʒʌstɪs/", definition: "an unfairness that prevents someone from being recognised as a credible knower or from interpreting experience fully", example: "The testimony describes epistemic injustice when officials dismiss the community’s knowledge.", exampleTranslation: "تصف الشهادة ظلمًا معرفيًا عندما يرفض المسؤولون معرفة المجتمع.", category: "post-truth and information", tags: ["knowledge", "justice"], synonyms: ["injustice in knowing", "credibility injustice"] }),
      reviewed({ word: "evidential standard", translation: "معيار الإثبات", pos: "noun", ipa: "/ˌevɪˈdenʃəl ˈstændərd/", definition: "the level and quality of proof required before a claim is accepted", example: "The report applies a higher evidential standard to extraordinary claims.", exampleTranslation: "يطبق التقرير معيار إثبات أعلى على الادعاءات الاستثنائية.", category: "post-truth and information", tags: ["evidence", "analysis"], synonyms: ["standard of evidence", "proof threshold"] }),
      reviewed({ word: "information cascade", translation: "تتابع معلوماتي", pos: "noun", ipa: "/ˌɪnfərˈmeɪʃən kæˈskeɪd/", definition: "a process in which people repeat a belief because others appear to accept it", example: "An information cascade spread the rumour before anyone checked the original source.", exampleTranslation: "نشر تتابع معلوماتي الإشاعة قبل أن يتحقق أحد من المصدر الأصلي.", category: "post-truth and information", tags: ["information", "social media"], synonyms: ["belief cascade", "social information cascade"] }),
      reviewed({ word: "synthetic media", translation: "وسائط اصطناعية", pos: "noun", ipa: "/sɪnˈθetɪk ˈmiːdiə/", definition: "audio, images, or video generated or significantly altered by computer systems", example: "The platform introduced labels for synthetic media used in political advertising.", exampleTranslation: "قدمت المنصة تسميات للوسائط الاصطناعية المستخدمة في الإعلانات السياسية.", category: "post-truth and information", tags: ["media", "technology"], synonyms: ["AI-generated media", "computer-generated media"] }),
      reviewed({ word: "source credibility", translation: "مصداقية المصدر", pos: "noun", ipa: "/sɔːrs ˌkredəˈbɪləti/", definition: "the degree to which a source is considered trustworthy and reliable", example: "Readers should assess source credibility before sharing a dramatic claim.", exampleTranslation: "ينبغي للقراء تقييم مصداقية المصدر قبل مشاركة ادعاء مثير.", category: "post-truth and information", tags: ["information", "media literacy"], synonyms: ["source reliability", "credibility of a source"] }),
      reviewed({ word: "algorithmic amplification", translation: "تضخيم خوارزمي", pos: "noun", ipa: "/ˌælɡəˈrɪðmɪk ˌæmplɪfɪˈkeɪʃən/", definition: "the increase in visibility a platform’s algorithm gives to particular content", example: "Algorithmic amplification can make sensational posts appear more widely than careful analysis.", exampleTranslation: "يمكن للتضخيم الخوارزمي أن يجعل المنشورات المثيرة تظهر على نطاق أوسع من التحليل المتأني.", category: "post-truth and information", tags: ["technology", "media"], synonyms: ["algorithm-driven promotion", "automated content amplification"] }),
      reviewed({ word: "verification protocol", translation: "بروتوكول التحقق", pos: "noun", ipa: "/ˌverɪfɪˈkeɪʃən ˈproʊtəkɔːl/", definition: "a defined sequence of checks used to establish whether information is reliable", example: "The editorial desk adopted a verification protocol for images received from social media.", exampleTranslation: "اعتمدت غرفة الأخبار بروتوكول تحقق للصور الواردة من وسائل التواصل الاجتماعي.", category: "post-truth and information", tags: ["verification", "journalism"], synonyms: ["fact-checking procedure", "verification process"] }),
      reviewed({ word: "dataset lineage", translation: "تسلسل مصدر البيانات", pos: "noun", ipa: "/ˈdeɪtə ˈlɪniɪdʒ/", definition: "the documented origin, history, and transformations of a data set", example: "Clear dataset lineage made the research findings easier to audit.", exampleTranslation: "جعل توثيق أصل البيانات ومصدرها نتائج البحث أسهل في التدقيق.", category: "post-truth and information", tags: ["data", "research"], synonyms: ["data lineage", "data origin record"] }),
    ],
  },
};
