import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/** Reviewed vocabulary for the existing B1/B2/C1 u20 and u21 units. */
export const ENGLISH_B1_B2_C1_U20_U21_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u20: [
      reviewed({ word: "machine learning", translation: "تعلّم الآلة", pos: "noun", ipa: "/məˈʃiːn ˌlɜːrnɪŋ/", definition: "a way of making computers learn patterns from data", example: "Machine learning helps the app recommend useful routes.", exampleTranslation: "يساعد تعلّم الآلة التطبيق على اقتراح طرق مفيدة.", category: "artificial intelligence and robots", tags: ["AI", "technology"], synonyms: ["data-driven learning", "automated learning"] }),
      reviewed({ word: "decision procedure", translation: "إجراء لاتخاذ القرار", pos: "noun", ipa: "/dɪˈsɪʒən prəˈsiːdʒər/", definition: "a defined set of steps that a computer follows to solve a problem", example: "The decision procedure compares several routes before choosing one.", exampleTranslation: "يقارن إجراء اتخاذ القرار عدة طرق قبل اختيار أحدها.", category: "artificial intelligence and robots", tags: ["AI", "computing"], synonyms: ["set of instructions", "computational procedure"] }),
      reviewed({ word: "neural network", translation: "شبكة عصبية", pos: "noun", ipa: "/ˈnʊrəl ˈnetwɜːrk/", definition: "a computer system designed to recognise patterns in a way inspired by the brain", example: "The neural network improved after it processed more examples.", exampleTranslation: "تحسنت الشبكة العصبية بعد أن عالجت أمثلة أكثر.", category: "artificial intelligence and robots", tags: ["AI", "science"], synonyms: ["artificial neural network", "pattern-learning system"] }),
      reviewed({ word: "robotics", translation: "علم الروبوتات", pos: "noun", ipa: "/roʊˈbɑːtɪks/", definition: "the science and engineering of designing and using robots", example: "She joined a robotics club to build a small vehicle.", exampleTranslation: "انضمت إلى نادٍ لعلم الروبوتات لبناء مركبة صغيرة.", category: "artificial intelligence and robots", tags: ["robots", "engineering"], synonyms: ["robot engineering", "robot technology"] }),
      reviewed({ word: "sensor", translation: "مستشعر", pos: "noun", ipa: "/ˈsensər/", definition: "a device that detects changes such as movement, light, or temperature", example: "A sensor tells the robot when an object is nearby.", exampleTranslation: "يخبر المستشعر الروبوت عندما يكون جسم قريبًا.", category: "artificial intelligence and robots", tags: ["robots", "hardware"], synonyms: ["detector", "measuring device"] }),
      reviewed({ word: "training data", translation: "بيانات التدريب", pos: "noun", ipa: "/ˈtreɪnɪŋ ˌdeɪtə/", definition: "information used to teach a computer system how to recognise patterns", example: "The quality of the training data affects the system’s results.", exampleTranslation: "تؤثر جودة بيانات التدريب في نتائج النظام.", category: "artificial intelligence and robots", tags: ["AI", "data"], synonyms: ["learning data", "model-training data"] }),
      reviewed({ word: "robotic arm", translation: "ذراع آلية", pos: "noun", ipa: "/roʊˈbɑːtɪk ɑːrm/", definition: "a mechanical arm that can move and perform tasks automatically", example: "The robotic arm placed the parts together with great precision.", exampleTranslation: "وضعت الذراع الآلية القطع معًا بدقة كبيرة.", category: "artificial intelligence and robots", tags: ["robots", "manufacturing"], synonyms: ["automated arm", "mechanical arm"] }),
      reviewed({ word: "speech recognition", translation: "التعرّف على الكلام", pos: "noun", ipa: "/spiːtʃ ˌrekəɡˈnɪʃən/", definition: "technology that allows a computer to understand spoken words", example: "Speech recognition lets users control the device without touching it.", exampleTranslation: "يتيح التعرّف على الكلام للمستخدمين التحكم في الجهاز دون لمسه.", category: "artificial intelligence and robots", tags: ["AI", "communication"], synonyms: ["voice recognition", "speech-to-text technology"] }),
    ],
    u21: [
      reviewed({ word: "protagonist", translation: "الشخصية الرئيسية", pos: "noun", ipa: "/proʊˈtæɡənɪst/", definition: "the main character whose experiences drive a story", example: "The protagonist leaves home to discover the truth about her family.", exampleTranslation: "تغادر الشخصية الرئيسية منزلها لاكتشاف حقيقة عائلتها.", category: "literature and novels", tags: ["reading", "characters"], synonyms: ["main character", "central character"] }),
      reviewed({ word: "plot twist", translation: "تحوّل مفاجئ في الحبكة", pos: "noun", ipa: "/plɑːt twɪst/", definition: "an unexpected change in the direction of a story", example: "The final plot twist changed the reader’s understanding of every earlier scene.", exampleTranslation: "غيّر التحول المفاجئ في الحبكة فهم القارئ لكل مشهد سابق.", category: "literature and novels", tags: ["reading", "storytelling"], synonyms: ["unexpected turn", "surprise development"] }),
      reviewed({ word: "fiction", translation: "أدب خيالي", pos: "noun", ipa: "/ˈfɪkʃən/", definition: "writing about imagined people and events", example: "The library has a large section devoted to contemporary fiction.", exampleTranslation: "تضم المكتبة قسمًا كبيرًا مخصصًا للأدب الخيالي المعاصر.", category: "literature and novels", tags: ["books", "genres"], synonyms: ["imaginary literature", "creative prose"] }),
      reviewed({ word: "chapter", translation: "فصل من كتاب", pos: "noun", ipa: "/ˈtʃæptər/", definition: "one of the main sections into which a book is divided", example: "The first chapter introduces the village and its unusual traditions.", exampleTranslation: "يقدم الفصل الأول القرية وتقاليدها غير المعتادة.", category: "literature and novels", tags: ["books", "reading"], synonyms: ["section", "part"] }),
      reviewed({ word: "setting", translation: "زمان ومكان الأحداث", pos: "noun", ipa: "/ˈsetɪŋ/", definition: "the time and place in which a story happens", example: "The setting moves from a coastal town to a crowded capital.", exampleTranslation: "ينتقل زمان ومكان الأحداث من بلدة ساحلية إلى عاصمة مزدحمة.", category: "literature and novels", tags: ["storytelling", "context"], synonyms: ["background", "story environment"] }),
      reviewed({ word: "paperback", translation: "كتاب بغلاف ورقي", pos: "noun", ipa: "/ˈpeɪpərbæk/", definition: "a book with a flexible paper or card cover", example: "I bought the paperback because it was easier to carry.", exampleTranslation: "اشتريت الكتاب ذا الغلاف الورقي لأنه أسهل في الحمل.", category: "literature and novels", tags: ["books", "formats"], synonyms: ["softcover", "paper-covered book"] }),
      reviewed({ word: "literary genre", translation: "نوع أدبي", pos: "noun", ipa: "/ˈlɪtəreri ʒɑːnrə/", definition: "a category of literature with particular features or themes", example: "Mystery is a literary genre built around questions and discoveries.", exampleTranslation: "تُعد الرواية البوليسية نوعًا أدبيًا يقوم على الأسئلة والاكتشافات.", category: "literature and novels", tags: ["books", "genres"], synonyms: ["literary category", "genre"] }),
      reviewed({ word: "point of view", translation: "وجهة نظر السرد", pos: "noun", ipa: "/pɔɪnt əv vjuː/", definition: "the position or perspective from which a story is told", example: "The novel changes point of view between two members of the same family.", exampleTranslation: "تغير الرواية وجهة نظر السرد بين فردين من العائلة نفسها.", category: "literature and novels", tags: ["reading", "narration"], synonyms: ["narrative perspective", "story perspective"] }),
    ],
  },
  B2: {
    u20: [
      reviewed({ word: "wealth gap", translation: "فجوة الثروة", pos: "noun", ipa: "/welθ ɡæp/", definition: "the unequal distribution of wealth between different people or groups", example: "The report examines how the wealth gap affects access to education.", exampleTranslation: "يدرس التقرير كيف تؤثر فجوة الثروة في الوصول إلى التعليم.", category: "inequality and migration", tags: ["economics", "society"], synonyms: ["wealth inequality", "economic divide"] }),
      reviewed({ word: "border control", translation: "مراقبة الحدود", pos: "noun", ipa: "/ˈbɔːrdər kənˈtroʊl/", definition: "measures used to monitor borders and regulate movement between countries", example: "Stricter border control caused long delays at the crossing.", exampleTranslation: "تسببت مراقبة الحدود الأكثر صرامة في تأخيرات طويلة عند المعبر.", category: "inequality and migration", tags: ["migration", "government"], synonyms: ["immigration control", "border security"] }),
      reviewed({ word: "systemic discrimination", translation: "تمييز منهجي", pos: "noun", ipa: "/sɪˈstemɪk dɪˌskrɪmɪˈneɪʃən/", definition: "unfair treatment built into the policies and practices of institutions", example: "The inquiry found evidence of systemic discrimination in the housing sector.", exampleTranslation: "وجد التحقيق أدلة على تمييز منهجي في قطاع الإسكان.", category: "inequality and migration", tags: ["inequality", "justice"], synonyms: ["structural discrimination", "institutional bias"] }),
      reviewed({ word: "social integration", translation: "اندماج اجتماعي", pos: "noun", ipa: "/ˈsoʊʃəl ˌɪntɪˈɡreɪʃən/", definition: "the process by which newcomers become part of the wider social structure", example: "Language education can support social integration without erasing cultural identity.", exampleTranslation: "يمكن لتعليم اللغة دعم الاندماج الاجتماعي دون محو الهوية الثقافية.", category: "inequality and migration", tags: ["migration", "society"], synonyms: ["social inclusion", "community integration"] }),
      reviewed({ word: "undocumented immigrant", translation: "مهاجر غير موثق", pos: "noun", ipa: "/ʌnˈdɑːkjəmentɪd ˈɪmɪɡrənt/", definition: "a person living in a country without the documents required for legal residence", example: "The report discusses the legal risks faced by undocumented immigrants.", exampleTranslation: "يناقش التقرير المخاطر القانونية التي يواجهها المهاجرون غير الموثقين.", category: "inequality and migration", tags: ["migration", "law"], synonyms: ["unauthorised migrant", "irregular migrant"] }),
      reviewed({ word: "economic disparity", translation: "تفاوت اقتصادي", pos: "noun", ipa: "/ˌekəˈnɑːmɪk dɪˈspærəti/", definition: "a significant difference in economic conditions between groups or places", example: "Economic disparity between rural and urban areas remains a serious concern.", exampleTranslation: "لا يزال التفاوت الاقتصادي بين المناطق الريفية والحضرية مصدر قلق خطير.", category: "inequality and migration", tags: ["economics", "inequality"], synonyms: ["economic inequality", "financial imbalance"] }),
      reviewed({ word: "remittance economy", translation: "اقتصاد التحويلات المالية", pos: "noun", ipa: "/rɪˈmɪtəns ɪˈkɑːnəmi/", definition: "an economy significantly supported by money sent home by people working abroad", example: "The remittance economy helps many families pay for housing and education.", exampleTranslation: "يساعد اقتصاد التحويلات المالية عائلات كثيرة على دفع تكاليف السكن والتعليم.", category: "inequality and migration", tags: ["migration", "finance"], synonyms: ["migrant-transfer economy", "remittance-based economy"] }),
      reviewed({ word: "displacement pressure", translation: "ضغط النزوح", pos: "noun", ipa: "/dɪsˈpleɪsmənt ˈpreʃər/", definition: "conditions that force people to leave their homes or communities", example: "Rising rents created displacement pressure in the historic district.", exampleTranslation: "خلقت الإيجارات المرتفعة ضغط نزوح في الحي التاريخي.", category: "inequality and migration", tags: ["migration", "housing"], synonyms: ["forced-movement pressure", "relocation pressure"] }),
    ],
    u21: [
      reviewed({ word: "subconscious", translation: "العقل الباطن", pos: "noun", ipa: "/ˌsʌbˈkɑːnʃəs/", definition: "the part of the mind that influences feelings and behaviour without full awareness", example: "A childhood memory in the subconscious can shape adult choices.", exampleTranslation: "يمكن لذكرى طفولة في العقل الباطن أن تشكل اختيارات البالغين.", category: "consciousness and mind", tags: ["psychology", "mind"], synonyms: ["unconscious mind", "inner mental process"] }),
      reviewed({ word: "cognitive function", translation: "وظيفة إدراكية", pos: "noun", ipa: "/ˈkɑːɡnətɪv ˈfʌŋkʃən/", definition: "a mental activity involved in acquiring, processing, or using knowledge", example: "Sleep plays an important role in maintaining cognitive function.", exampleTranslation: "يؤدي النوم دورًا مهمًا في الحفاظ على الوظيفة الإدراكية.", category: "consciousness and mind", tags: ["psychology", "brain"], synonyms: ["mental ability", "intellectual function"] }),
      reviewed({ word: "mental state", translation: "حالة ذهنية", pos: "noun", ipa: "/ˈmentəl steɪt/", definition: "a person’s psychological and emotional condition at a particular time", example: "The same event can feel different depending on a person’s mental state.", exampleTranslation: "يمكن أن يبدو الحدث نفسه مختلفًا حسب الحالة الذهنية للشخص.", category: "consciousness and mind", tags: ["psychology", "wellbeing"], synonyms: ["state of mind", "psychological condition"] }),
      reviewed({ word: "sensory input", translation: "مدخلات حسية", pos: "noun", ipa: "/ˈsensəri ˈɪnpʊt/", definition: "information received by the brain through the senses", example: "The brain combines sensory input to create a picture of the world.", exampleTranslation: "يجمع الدماغ المدخلات الحسية ليكوّن صورة عن العالم.", category: "consciousness and mind", tags: ["brain", "senses"], synonyms: ["sensory information", "perceptual input"] }),
      reviewed({ word: "subjective experience", translation: "تجربة ذاتية", pos: "noun", ipa: "/səbˈdʒektɪv ɪkˈspɪriəns/", definition: "the personal way in which an individual experiences and interprets an event", example: "Pain is a subjective experience that is difficult to compare precisely.", exampleTranslation: "الألم تجربة ذاتية يصعب مقارنتها بدقة.", category: "consciousness and mind", tags: ["psychology", "perspective"], synonyms: ["personal experience", "individual perception"] }),
      reviewed({ word: "reflective cognition", translation: "إدراك تأملي", pos: "noun", ipa: "/rɪˈflektɪv kɑːɡˈnɪʃən/", definition: "awareness and understanding of one’s own thinking and learning processes", example: "Reflective cognition helps students notice which study methods work for them.", exampleTranslation: "يساعد الإدراك التأملي الطلاب على ملاحظة أساليب الدراسة النافعة لهم.", category: "consciousness and mind", tags: ["learning", "psychology"], synonyms: ["thinking about thinking", "self-monitoring"] }),
      reviewed({ word: "attentional focus", translation: "تركيز الانتباه", pos: "noun", ipa: "/əˈtenʃənəl ˈfoʊkəs/", definition: "the direction and concentration of mental attention on a particular object or task", example: "Noise can quickly interrupt attentional focus during a difficult task.", exampleTranslation: "يمكن للضوضاء أن تقاطع تركيز الانتباه سريعًا أثناء مهمة صعبة.", category: "consciousness and mind", tags: ["attention", "psychology"], synonyms: ["focus of attention", "mental concentration"] }),
      reviewed({ word: "mind-body problem", translation: "مشكلة العقل والجسد", pos: "noun", ipa: "/ˈmaɪnd ˈbɑːdi ˌprɑːbləm/", definition: "the philosophical question of how mental experience relates to the physical body", example: "The lecture introduced the mind-body problem through examples from neuroscience.", exampleTranslation: "قدمت المحاضرة مشكلة العقل والجسد من خلال أمثلة من علم الأعصاب.", category: "consciousness and mind", tags: ["philosophy", "mind"], synonyms: ["mind-body question", "mind-brain problem"] }),
    ],
  },
  C1: {
    u20: [
      reviewed({ word: "logical fallacy", translation: "مغالطة منطقية", pos: "noun", ipa: "/ˈlɑːdʒɪkəl ˈfæləsi/", definition: "a flaw in reasoning that weakens or invalidates an argument", example: "The article identifies a logical fallacy in the claim that one example proves a general rule.", exampleTranslation: "تحدد المقالة مغالطة منطقية في الادعاء بأن مثالًا واحدًا يثبت قاعدة عامة.", category: "rhetoric and argumentation", tags: ["logic", "debate"], synonyms: ["flawed reasoning", "invalid inference"] }),
      reviewed({ word: "deductive reasoning", translation: "استدلال استنتاجي", pos: "noun", ipa: "/dɪˈdʌktɪv ˈriːzənɪŋ/", definition: "reasoning that derives a conclusion from general principles or premises", example: "The lecturer contrasted deductive reasoning with reasoning from observation.", exampleTranslation: "قارن المحاضر بين الاستدلال الاستنتاجي والاستدلال القائم على الملاحظة.", category: "rhetoric and argumentation", tags: ["logic", "analysis"], synonyms: ["deduction", "formal inference"] }),
      reviewed({ word: "emotive language", translation: "لغة عاطفية", pos: "noun", ipa: "/ɪˈmoʊtɪv ˈlæŋɡwɪdʒ/", definition: "language deliberately chosen to create a strong emotional reaction", example: "The editorial uses emotive language to turn a policy disagreement into a moral crisis.", exampleTranslation: "تستخدم الافتتاحية لغة عاطفية لتحويل خلاف سياسي إلى أزمة أخلاقية.", category: "rhetoric and argumentation", tags: ["rhetoric", "language"], synonyms: ["loaded language", "emotional wording"] }),
      reviewed({ word: "equivocation", translation: "مواربة أو غموض متعمد", pos: "noun", ipa: "/ɪˌkwɪvəˈkeɪʃən/", definition: "the use of deliberately unclear language to avoid a direct commitment", example: "The minister’s equivocation left the audience unsure about the government’s position.", exampleTranslation: "تركت مواربة الوزير الجمهور غير متأكد من موقف الحكومة.", category: "rhetoric and argumentation", tags: ["rhetoric", "communication"], synonyms: ["evasion", "deliberate ambiguity"] }),
      reviewed({ word: "syllogistic reasoning", translation: "استدلال قياسي", pos: "noun", ipa: "/ˌsɪləˈdʒɪstɪk ˈriːzənɪŋ/", definition: "reasoning in which two statements are used to support a logically related conclusion", example: "The students analysed the syllogistic reasoning behind the legal argument.", exampleTranslation: "حلل الطلاب الاستدلال القياسي وراء الحجة القانونية.", category: "rhetoric and argumentation", tags: ["logic", "philosophy"], synonyms: ["syllogism", "formal deductive reasoning"] }),
      reviewed({ word: "argumentative concession", translation: "إقرار جدلي", pos: "noun", ipa: "/ˌɑːrɡjuˈmentətɪv kənˈseʃən/", definition: "an acknowledgement of part of an opposing view before presenting a stronger response", example: "The argumentative concession made the writer’s rebuttal more credible.", exampleTranslation: "جعل الإقرار الجدلي رد الكاتب أكثر مصداقية.", category: "rhetoric and argumentation", tags: ["argument", "writing"], synonyms: ["strategic concession", "acknowledged objection"] }),
      reviewed({ word: "evidential obligation", translation: "الالتزام الإثباتي", pos: "noun", ipa: "/ˌevɪˈdenʃəl ˌɑːbləˈɡeɪʃən/", definition: "the responsibility to provide enough evidence to support a claim", example: "The evidential obligation lies with anyone making the extraordinary claim.", exampleTranslation: "يقع الالتزام الإثباتي على كل من يقدم الادعاء الاستثنائي.", category: "rhetoric and argumentation", tags: ["evidence", "debate"], synonyms: ["proof obligation", "evidential responsibility"] }),
      reviewed({ word: "discursive strategy", translation: "استراتيجية خطابية", pos: "noun", ipa: "/dɪˈskɜːrsɪv ˈstrætədʒi/", definition: "a deliberate way of using language to shape interpretation or influence an audience", example: "Repetition was the speaker’s main discursive strategy for presenting the proposal as inevitable.", exampleTranslation: "كان التكرار الاستراتيجية الخطابية الرئيسية للمتحدث لتقديم المقترح بوصفه حتميًا.", category: "rhetoric and argumentation", tags: ["discourse", "persuasion"], synonyms: ["rhetorical strategy", "language strategy"] }),
    ],
    u21: [
      reviewed({ word: "evocative", translation: "مثير للذكريات", pos: "adjective", ipa: "/ɪˈvɑːkətɪv/", definition: "bringing vivid memories, images, or feelings to mind", example: "The evocative photograph brought the old neighbourhood back to life.", exampleTranslation: "أعادت الصورة المثيرة للذكريات الحي القديم إلى الحياة.", category: "memory and nostalgia", tags: ["memory", "feelings"], synonyms: ["reminiscent", "suggestive"] }),
      reviewed({ word: "sentimental value", translation: "قيمة عاطفية", pos: "noun", ipa: "/ˌsentɪˈmentəl ˈvæljuː/", definition: "personal importance based on an object’s connection with memories or relationships", example: "The letter has little market value but considerable sentimental value.", exampleTranslation: "للرسالة قيمة سوقية قليلة لكنها تحمل قيمة عاطفية كبيرة.", category: "memory and nostalgia", tags: ["emotion", "objects"], synonyms: ["emotional value", "personal significance"] }),
      reviewed({ word: "retrospective", translation: "استعادي", pos: "adjective", ipa: "/ˌretrəˈspektɪv/", definition: "looking back at past events, work, or experiences", example: "The retrospective essay questions whether the decision was as successful as it first appeared.", exampleTranslation: "تتساءل المقالة الاستعادية عما إذا كان القرار ناجحًا كما بدا أول مرة.", category: "memory and nostalgia", tags: ["reflection", "time"], synonyms: ["backward-looking", "reflective"] }),
      reviewed({ word: "mnemonic device", translation: "وسيلة لتسهيل الحفظ", pos: "noun", ipa: "/nɪˈmɑːnɪk dɪˈvaɪs/", definition: "a technique or pattern used to make information easier to remember", example: "The lecturer introduced a mnemonic device for remembering the stages of the theory.", exampleTranslation: "قدم المحاضر وسيلة لتسهيل الحفظ لتذكر مراحل النظرية.", category: "memory and nostalgia", tags: ["memory", "learning"], synonyms: ["memory aid", "memorisation technique"] }),
      reviewed({ word: "rosy retrospection", translation: "استرجاع وردي للماضي", pos: "noun", ipa: "/ˈroʊzi ˌretrəˈspekʃən/", definition: "the tendency to remember the past as more positive than it actually was", example: "Rosy retrospection made the difficult journey seem effortless years later.", exampleTranslation: "جعل الاسترجاع الوردي للماضي الرحلة الصعبة تبدو سهلة بعد سنوات.", category: "memory and nostalgia", tags: ["psychology", "bias"], synonyms: ["idealised recollection", "nostalgic bias"] }),
      reviewed({ word: "memory consolidation", translation: "ترسيخ الذاكرة", pos: "noun", ipa: "/ˈmeməri kənˌsɑːləˈdeɪʃən/", definition: "the process by which a new memory becomes more stable over time", example: "Sleep appears to support memory consolidation after intensive learning.", exampleTranslation: "يبدو أن النوم يدعم ترسيخ الذاكرة بعد التعلم المكثف.", category: "memory and nostalgia", tags: ["psychology", "learning"], synonyms: ["memory stabilisation", "long-term memory formation"] }),
      reviewed({ word: "involuntary memory", translation: "ذاكرة لا إرادية", pos: "noun", ipa: "/ɪnˈvɑːləntəri ˈmeməri/", definition: "a memory that returns to the mind without a deliberate attempt to recall it", example: "The smell of bread triggered an involuntary memory of her childhood kitchen.", exampleTranslation: "أثارت رائحة الخبز ذاكرة لا إرادية لمطبخ طفولتها.", category: "memory and nostalgia", tags: ["memory", "senses"], synonyms: ["spontaneous memory", "unbidden recollection"] }),
      reviewed({ word: "cultural remembrance", translation: "استذكار ثقافي", pos: "noun", ipa: "/ˈkʌltʃərəl rɪˈmembrəns/", definition: "the ways a community preserves and publicly recalls important aspects of its past", example: "The annual ceremony is a form of cultural remembrance after the conflict.", exampleTranslation: "يمثل الاحتفال السنوي شكلًا من الاستذكار الثقافي بعد الصراع.", category: "memory and nostalgia", tags: ["culture", "history"], synonyms: ["collective commemoration", "cultural memory practice"] }),
    ],
  },
};
