import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/** Reviewed vocabulary for the existing B1/B2/C1 u30 and u31 units. */
export const ENGLISH_B1_B2_C1_U30_U31_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u30: [
      reviewed({ word: "root cause", translation: "السبب الجذري", pos: "noun", ipa: "/ruːt kɔːz/", definition: "the basic reason why a problem happens", example: "The team investigated the root cause instead of treating only the symptom.", exampleTranslation: "بحث الفريق في السبب الجذري بدلًا من معالجة العرض فقط.", category: "problem solving", tags: ["problems", "analysis"], synonyms: ["underlying cause", "fundamental reason"] }),
      reviewed({ word: "troubleshooting", translation: "استكشاف الأخطاء وإصلاحها", pos: "noun", ipa: "/ˈtrʌbəlʃuːtɪŋ/", definition: "the process of finding and fixing the cause of a problem", example: "The guide offers troubleshooting steps for common software problems.", exampleTranslation: "يقدم الدليل خطوات لاستكشاف أخطاء البرامج الشائعة وإصلاحها.", category: "problem solving", tags: ["technology", "solutions"], synonyms: ["fault finding", "problem diagnosis"] }),
      reviewed({ word: "fallback strategy", translation: "استراتيجية بديلة", pos: "noun", ipa: "/ˈfɔːlbæk ˈstrætədʒi/", definition: "a different plan used when the preferred plan cannot work", example: "We prepared a fallback strategy in case the supplier was late.", exampleTranslation: "أعددنا استراتيجية بديلة في حال تأخر المورّد.", category: "problem solving", tags: ["planning", "solutions"], synonyms: ["backup plan", "alternative approach"] }),
      reviewed({ word: "trial and error", translation: "المحاولة والخطأ", pos: "noun", ipa: "/ˌtraɪəl ən ˈerə/", definition: "a method of solving a problem by trying different possibilities until one works", example: "Learning the new software involved some trial and error.", exampleTranslation: "تضمن تعلم البرنامج الجديد بعض المحاولة والخطأ.", category: "problem solving", tags: ["learning", "solutions"], synonyms: ["experimentation", "testing alternatives"] }),
      reviewed({ word: "workable solution", translation: "حل قابل للتطبيق", pos: "noun", ipa: "/ˈwɜːkəbəl səˈluːʃən/", definition: "a solution that is practical and likely to succeed", example: "After several suggestions, the group found a workable solution.", exampleTranslation: "بعد عدة اقتراحات، وجد الفريق حلًا قابلًا للتطبيق.", category: "problem solving", tags: ["solutions", "teamwork"], synonyms: ["practical answer", "viable solution"] }),
      reviewed({ word: "warning sign", translation: "علامة تحذير", pos: "noun", ipa: "/ˈwɔːnɪŋ saɪn/", definition: "a fact or event that suggests a problem may soon occur", example: "A sudden drop in quality was a warning sign.", exampleTranslation: "كان الانخفاض المفاجئ في الجودة علامة تحذير.", category: "problem solving", tags: ["risk", "prevention"], synonyms: ["red flag", "early signal"] }),
      reviewed({ word: "deal with", translation: "يتعامل مع", pos: "verb", ipa: "/diːl wɪð/", definition: "to take action to manage or solve a situation or problem", example: "The manager dealt with the complaint calmly.", exampleTranslation: "تعامل المدير مع الشكوى بهدوء.", category: "problem solving", tags: ["action", "communication"], synonyms: ["handle", "manage"] }),
      reviewed({ word: "overcome an obstacle", translation: "يتغلب على عقبة", pos: "verb", ipa: "/ˌəʊvəˈkʌm ən ˈɒbstəkəl/", definition: "to succeed despite something that makes progress difficult", example: "The volunteers overcame an obstacle by sharing the equipment.", exampleTranslation: "تغلب المتطوعون على عقبة من خلال مشاركة المعدات.", category: "problem solving", tags: ["challenges", "solutions"], synonyms: ["surmount a difficulty", "get past a barrier"] }),
    ],
    u31: [
      reviewed({ word: "sense of belonging", translation: "شعور بالانتماء", pos: "noun", ipa: "/sens əv bɪˈlɒŋɪŋ/", definition: "the feeling of being accepted as a member of a group or community", example: "The festival gave newcomers a stronger sense of belonging.", exampleTranslation: "منح المهرجان الوافدين الجدد شعورًا أقوى بالانتماء.", category: "culture and identity", tags: ["identity", "community"], synonyms: ["feeling of inclusion", "social belonging"] }),
      reviewed({ word: "cultural diversity", translation: "تنوع ثقافي", pos: "noun", ipa: "/ˈkʌltʃərəl daɪˈvɜːsəti/", definition: "the presence of different cultures and ways of life in a society", example: "The school celebrates cultural diversity through food and music.", exampleTranslation: "تحتفل المدرسة بالتنوع الثقافي من خلال الطعام والموسيقى.", category: "culture and identity", tags: ["culture", "society"], synonyms: ["cultural variety", "multiculturalism"] }),
      reviewed({ word: "family roots", translation: "جذور عائلية", pos: "noun", ipa: "/ˈfæməli ruːts/", definition: "the family history and origins from which a person comes", example: "She travelled abroad to learn more about her family roots.", exampleTranslation: "سافرت إلى الخارج لتتعرف أكثر على جذورها العائلية.", category: "culture and identity", tags: ["family", "identity"], synonyms: ["ancestry", "family origins"] }),
      reviewed({ word: "cultural festival", translation: "مهرجان ثقافي", pos: "noun", ipa: "/ˈkʌltʃərəl ˈfestɪvəl/", definition: "an organised event that celebrates the traditions of a culture or community", example: "The cultural festival brought music, dance, and crafts to the town.", exampleTranslation: "جلب المهرجان الثقافي الموسيقى والرقص والحرف إلى البلدة.", category: "culture and identity", tags: ["celebrations", "traditions"], synonyms: ["heritage festival", "cultural celebration"] }),
      reviewed({ word: "open-minded", translation: "منفتح الفكر", pos: "adjective", ipa: "/ˌəʊpən ˈmaɪndɪd/", definition: "willing to consider ideas and ways of life that are different from your own", example: "An open-minded attitude makes cultural exchange more respectful.", exampleTranslation: "يجعل الموقف المنفتح ثقافيًا التبادل الثقافي أكثر احترامًا.", category: "culture and identity", tags: ["attitudes", "culture"], synonyms: ["tolerant", "receptive"], antonyms: ["narrow-minded"] }),
      reviewed({ word: "local dialect", translation: "لهجة محلية", pos: "noun", ipa: "/ˈləʊkəl ˈdaɪəlekt/", definition: "a form of a language spoken in a particular area", example: "Older residents still use the local dialect at home.", exampleTranslation: "لا يزال السكان الأكبر سنًا يستخدمون اللهجة المحلية في المنزل.", category: "culture and identity", tags: ["language", "community"], synonyms: ["regional speech", "local variety"] }),
      reviewed({ word: "ancestral storytelling", translation: "رواية قصص الأجداد", pos: "noun", ipa: "/ænˈsestrəl ˈstɔːritelɪŋ/", definition: "the practice of passing family or community stories from one generation to another", example: "Ancestral storytelling keeps memories of the community alive.", exampleTranslation: "تحافظ رواية قصص الأجداد على ذكريات المجتمع حية.", category: "culture and identity", tags: ["traditions", "history"], synonyms: ["heritage storytelling", "oral family history"] }),
      reviewed({ word: "intercultural contact", translation: "تواصل بين الثقافات", pos: "noun", ipa: "/ˌɪntəˈkʌltʃərəl ˈkɒntækt/", definition: "interaction between people from different cultural backgrounds", example: "Intercultural contact can challenge assumptions about other communities.", exampleTranslation: "يمكن للتواصل بين الثقافات أن يتحدى الافتراضات عن المجتمعات الأخرى.", category: "culture and identity", tags: ["culture", "communication"], synonyms: ["cross-cultural interaction", "cultural contact"] }),
    ],
  },
  B2: {
    u30: [
      reviewed({ word: "controlled variable", translation: "متغير مضبوط", pos: "noun", ipa: "/kənˈtrəʊld ˈveəriəbəl/", definition: "a factor kept the same in an experiment so that its effects can be excluded", example: "The temperature was treated as a controlled variable in the experiment.", exampleTranslation: "عُوملت درجة الحرارة بوصفها متغيرًا مضبوطًا في التجربة.", category: "science and evidence", tags: ["science", "experiments"], synonyms: ["constant variable", "control factor"] }),
      reviewed({ word: "reproducible result", translation: "نتيجة قابلة للتكرار", pos: "noun", ipa: "/ˌriːprəˈdjuːsəbəl rɪˈzʌlt/", definition: "a result that can be obtained again when the same method is used", example: "A reproducible result gives scientists greater confidence in a claim.", exampleTranslation: "تمنح النتيجة القابلة للتكرار العلماء ثقة أكبر في الادعاء.", category: "science and evidence", tags: ["science", "reliability"], synonyms: ["repeatable finding", "consistent result"] }),
      reviewed({ word: "sampling uncertainty", translation: "عدم يقين العينة", pos: "noun", ipa: "/ˈsɑːmplɪŋ ʌnˈsɜːtənti/", definition: "the uncertainty caused by studying a sample rather than an entire population", example: "The researchers reported sampling uncertainty alongside their estimate.", exampleTranslation: "أبلغ الباحثون عن عدم يقين العينة إلى جانب تقديرهم.", category: "science and evidence", tags: ["statistics", "uncertainty"], synonyms: ["sample uncertainty", "sampling error"] }),
      reviewed({ word: "peer-reviewed study", translation: "دراسة محكّمة", pos: "noun", ipa: "/ˌpɪə rɪˈvjuːd ˈstʌdi/", definition: "a scientific study assessed by other specialists before publication", example: "The claim was supported by a peer-reviewed study.", exampleTranslation: "دُعم الادعاء بدراسة محكّمة.", category: "science and evidence", tags: ["research", "evidence"], synonyms: ["refereed study", "reviewed research"] }),
      reviewed({ word: "research sample", translation: "عينة بحثية", pos: "noun", ipa: "/rɪˈsɜːtʃ ˈsɑːmpəl/", definition: "the smaller group selected to represent a population in a study", example: "The research sample included participants from three regions.", exampleTranslation: "شملت العينة البحثية مشاركين من ثلاث مناطق.", category: "science and evidence", tags: ["research", "statistics"], synonyms: ["study sample", "sample group"] }),
      reviewed({ word: "anomalous result", translation: "نتيجة شاذة", pos: "noun", ipa: "/əˈnɒmələs rɪˈzʌlt/", definition: "a result that differs unexpectedly from the general pattern", example: "The anomalous result was checked before it was removed from the analysis.", exampleTranslation: "فُحصت النتيجة الشاذة قبل استبعادها من التحليل.", category: "science and evidence", tags: ["data", "experiments"], synonyms: ["outlier", "unexpected finding"] }),
      reviewed({ word: "expert agreement", translation: "اتفاق الخبراء", pos: "noun", ipa: "/ˈekspɜːt əˈɡriːmənt/", definition: "a shared conclusion reached by specialists in a field", example: "The policy reflects expert agreement about the risks.", exampleTranslation: "تعكس السياسة اتفاق الخبراء بشأن المخاطر.", category: "science and evidence", tags: ["science", "consensus"], synonyms: ["specialist agreement", "expert accord"] }),
      reviewed({ word: "experimental control", translation: "ضبط تجريبي", pos: "noun", ipa: "/ɪkˌsperɪˈmentəl kənˈtrəʊl/", definition: "a procedure used to limit the influence of unwanted factors in an experiment", example: "The experimental control made the comparison more reliable.", exampleTranslation: "جعل الضبط التجريبي المقارنة أكثر موثوقية.", category: "science and evidence", tags: ["experiments", "method"], synonyms: ["experimental safeguard", "control procedure"] }),
    ],
    u31: [
      reviewed({ word: "mutually beneficial", translation: "مفيد للطرفين", pos: "adjective", ipa: "/ˌmjuːtʃuəli ˌbenɪˈfɪʃəl/", definition: "helpful or advantageous to both sides in an arrangement", example: "The companies reached a mutually beneficial agreement.", exampleTranslation: "توصلت الشركتان إلى اتفاق مفيد للطرفين.", category: "business and negotiation", tags: ["negotiation", "agreements"], synonyms: ["win-win", "advantageous to both"] }),
      reviewed({ word: "revised offer", translation: "عرض معدّل", pos: "noun", ipa: "/rɪˈvaɪzd ˈɒfə/", definition: "a new proposal changed after discussion or negotiation", example: "The buyer accepted the revised offer the next day.", exampleTranslation: "قبل المشتري العرض المعدّل في اليوم التالي.", category: "business and negotiation", tags: ["offers", "negotiation"], synonyms: ["amended proposal", "updated bid"] }),
      reviewed({ word: "terms and conditions", translation: "الشروط والأحكام", pos: "noun", ipa: "/tɜːmz ən kənˈdɪʃənz/", definition: "the detailed rules that form part of an agreement", example: "Please read the terms and conditions before signing.", exampleTranslation: "يرجى قراءة الشروط والأحكام قبل التوقيع.", category: "business and negotiation", tags: ["contracts", "agreements"], synonyms: ["contract terms", "agreement conditions"] }),
      reviewed({ word: "breach of contract", translation: "خرق العقد", pos: "noun", ipa: "/briːtʃ əv ˈkɒntrækt/", definition: "a failure to do something required by a legal agreement", example: "Late delivery could constitute a breach of contract.", exampleTranslation: "قد يشكل التأخر في التسليم خرقًا للعقد.", category: "business and negotiation", tags: ["contracts", "law"], synonyms: ["contract violation", "failure to perform"] }),
      reviewed({ word: "payment schedule", translation: "جدول السداد", pos: "noun", ipa: "/ˈpeɪmənt ˈʃedjuːl/", definition: "a plan showing when and how payments will be made", example: "The payment schedule was extended to help the small business.", exampleTranslation: "مُدّد جدول السداد لمساعدة الشركة الصغيرة.", category: "business and negotiation", tags: ["finance", "contracts"], synonyms: ["repayment plan", "payment timetable"] }),
      reviewed({ word: "non-negotiable", translation: "غير قابل للتفاوض", pos: "adjective", ipa: "/ˌnɒn nɪˈɡəʊʃiəbəl/", definition: "not open to discussion or change", example: "The safety requirement is non-negotiable.", exampleTranslation: "متطلب السلامة غير قابل للتفاوض.", category: "business and negotiation", tags: ["negotiation", "requirements"], synonyms: ["fixed", "inflexible"] }),
      reviewed({ word: "negotiating leverage", translation: "نفوذ تفاوضي", pos: "noun", ipa: "/nɪˈɡəʊʃieɪtɪŋ ˈliːvərɪdʒ/", definition: "an advantage that gives one side more influence in a negotiation", example: "The alternative supplier gave the buyer useful negotiating leverage.", exampleTranslation: "منح المورّد البديل المشتري نفوذًا تفاوضيًا مفيدًا.", category: "business and negotiation", tags: ["negotiation", "strategy"], synonyms: ["bargaining power", "negotiating advantage"] }),
      reviewed({ word: "compromise cost", translation: "تكلفة التسوية", pos: "noun", ipa: "/ˈkɒmprəmaɪz kɒst/", definition: "the disadvantage or sacrifice accepted in order to reach an agreement", example: "Both sides discussed the compromise cost before accepting the deal.", exampleTranslation: "ناقش الطرفان تكلفة التسوية قبل قبول الصفقة.", category: "business and negotiation", tags: ["negotiation", "trade-offs"], synonyms: ["cost of compromise", "negotiation sacrifice"] }),
    ],
  },
  C1: {
    u30: [
      reviewed({ word: "policy mechanism", translation: "آلية سياسية", pos: "noun", ipa: "/ˈpɒləsi ˈmekənɪzəm/", definition: "a specific method through which a policy produces its intended effect", example: "The report explains the policy mechanism behind the tax reform.", exampleTranslation: "يشرح التقرير الآلية السياسية الكامنة وراء الإصلاح الضريبي.", category: "public policy", tags: ["policy", "governance"], synonyms: ["policy instrument", "implementation mechanism"] }),
      reviewed({ word: "rules adherence", translation: "الالتزام بالقواعد", pos: "noun", ipa: "/ruːlz ədˈhɪərəns/", definition: "the practice of following established rules or requirements", example: "The audit measured rules adherence across local agencies.", exampleTranslation: "قاس التدقيق الالتزام بالقواعد في الوكالات المحلية.", category: "public policy", tags: ["regulation", "governance"], synonyms: ["rule compliance", "regulatory observance"] }),
      reviewed({ word: "government spending", translation: "الإنفاق الحكومي", pos: "noun", ipa: "/ˈɡʌvənmənt ˈspendɪŋ/", definition: "money used by a government to provide services or pursue policy goals", example: "Government spending was redirected towards preventive healthcare.", exampleTranslation: "وُجّه الإنفاق الحكومي نحو الرعاية الصحية الوقائية.", category: "public policy", tags: ["finance", "government"], synonyms: ["public spending", "state expenditure"] }),
      reviewed({ word: "budget distribution", translation: "توزيع الميزانية", pos: "noun", ipa: "/ˈbʌdʒɪt ˌdɪstrɪˈbjuːʃən/", definition: "the way available public money is divided among programmes or services", example: "The committee reviewed the budget distribution before voting.", exampleTranslation: "راجعَت اللجنة توزيع الميزانية قبل التصويت.", category: "public policy", tags: ["budget", "governance"], synonyms: ["fund allocation", "budget division"] }),
      reviewed({ word: "unforeseen effect", translation: "أثر غير متوقع", pos: "noun", ipa: "/ˌʌnfəˈsiːn ɪˈfekt/", definition: "a result of a policy or action that was not predicted in advance", example: "The reform had an unforeseen effect on small employers.", exampleTranslation: "كان للإصلاح أثر غير متوقع على أصحاب العمل الصغار.", category: "public policy", tags: ["policy", "impact"], synonyms: ["unanticipated consequence", "unexpected outcome"] }),
      reviewed({ word: "policy intervention", translation: "تدخل سياسي", pos: "noun", ipa: "/ˈpɒləsi ˌɪntəˈvenʃən/", definition: "an action taken by a government to influence a social or economic situation", example: "The study compares two policy interventions aimed at reducing poverty.", exampleTranslation: "تقارن الدراسة بين تدخلين سياسيين يهدفان إلى الحد من الفقر.", category: "public policy", tags: ["policy", "reform"], synonyms: ["government action", "policy measure"] }),
      reviewed({ word: "impact assessment", translation: "تقييم الأثر", pos: "noun", ipa: "/ˈɪmpækt əˌsesmənt/", definition: "a systematic study of the likely effects of a plan or decision", example: "An impact assessment was published before the transport scheme began.", exampleTranslation: "نُشر تقييم للأثر قبل بدء مشروع النقل.", category: "public policy", tags: ["evaluation", "planning"], synonyms: ["effects analysis", "consequence assessment"] }),
      reviewed({ word: "citizen feedback session", translation: "جلسة ملاحظات المواطنين", pos: "noun", ipa: "/ˈsɪtɪzən ˈfiːdbæk ˈseʃən/", definition: "a meeting in which members of the public give views before a decision is made", example: "The ministry held a citizen feedback session on the proposed law.", exampleTranslation: "عقدت الوزارة جلسة لملاحظات المواطنين بشأن القانون المقترح.", category: "public policy", tags: ["democracy", "governance"], synonyms: ["public feedback meeting", "community input session"] }),
    ],
    u31: [
      reviewed({ word: "reading lens", translation: "منظور قرائي", pos: "noun", ipa: "/ˈriːdɪŋ lenz/", definition: "a particular perspective used to understand and analyse a text or set of evidence", example: "The researcher used a historical reading lens to examine the interview data.", exampleTranslation: "استخدم الباحث منظورًا قرائيًا تاريخيًا لفحص بيانات المقابلات.", category: "research and interpretation", tags: ["analysis", "interpretation"], synonyms: ["interpretive perspective", "analytical lens"] }),
      reviewed({ word: "textual evidence", translation: "دليل نصي", pos: "noun", ipa: "/ˈtekstʃuəl ˈevɪdəns/", definition: "words or passages from a text used to support an interpretation", example: "The essay cites textual evidence for its reading of the poem.", exampleTranslation: "يستشهد المقال بدليل نصي لقراءته للقصيدة.", category: "research and interpretation", tags: ["text", "evidence"], synonyms: ["passage-based evidence", "textual support"] }),
      reviewed({ word: "epistemic uncertainty", translation: "عدم يقين معرفي", pos: "noun", ipa: "/ɪˌpɪstɪmɪk ʌnˈsɜːtənti/", definition: "uncertainty about what can be known or how reliable knowledge is", example: "The author acknowledges epistemic uncertainty rather than overstating the result.", exampleTranslation: "يقر المؤلف بعدم اليقين المعرفي بدلًا من المبالغة في النتيجة.", category: "research and interpretation", tags: ["knowledge", "research"], synonyms: ["knowledge uncertainty", "limits of knowing"] }),
      reviewed({ word: "analytical distinction", translation: "تمييز تحليلي", pos: "noun", ipa: "/ˌænəˈlɪtɪkəl dɪˈstɪŋkʃən/", definition: "a difference drawn between ideas in order to examine them more precisely", example: "The chapter makes an analytical distinction between context and cause.", exampleTranslation: "يميز الفصل تحليليًا بين السياق والسبب.", category: "research and interpretation", tags: ["analysis", "argument"], synonyms: ["conceptual distinction", "analytical separation"] }),
      reviewed({ word: "situate in context", translation: "يضع في سياقه", pos: "verb", ipa: "/ˈsɪtʃueɪt ɪn ˈkɒntekst/", definition: "to understand or explain something in relation to its wider historical or social setting", example: "The article situates the theory in context before criticising it.", exampleTranslation: "يضع المقال النظرية في سياقها قبل نقدها.", category: "research and interpretation", tags: ["context", "analysis"], synonyms: ["contextualise", "place historically"] }),
      reviewed({ word: "inferential leap", translation: "قفزة استدلالية", pos: "noun", ipa: "/ˌɪnfəˈrenʃəl liːp/", definition: "a conclusion that goes further than the available evidence reasonably allows", example: "The reviewer warned that the final claim involved an inferential leap.", exampleTranslation: "حذر المراجع من أن الادعاء النهائي يتضمن قفزة استدلالية.", category: "research and interpretation", tags: ["reasoning", "evidence"], synonyms: ["unsupported inference", "logical jump"] }),
      reviewed({ word: "caveat", translation: "تحفظ", pos: "noun", ipa: "/ˈkæviæt/", definition: "a warning or condition that should be considered when interpreting a statement", example: "The conclusion is useful, with the caveat that the sample was small.", exampleTranslation: "الاستنتاج مفيد، مع التحفظ بأن العينة كانت صغيرة.", category: "research and interpretation", tags: ["qualifications", "evidence"], synonyms: ["qualification", "reservation"] }),
      reviewed({ word: "research constraint", translation: "قيد بحثي", pos: "noun", ipa: "/rɪˈsɜːtʃ kənˈstreɪnt/", definition: "a limitation that restricts how a study can be designed or interpreted", example: "Time was the main research constraint in the project.", exampleTranslation: "كان الوقت القيد البحثي الرئيسي في المشروع.", category: "research and interpretation", tags: ["research", "method"], synonyms: ["study limitation", "research restriction"] }),
    ],
  },
};
