// Additional English curriculum units u34-u35 for every CEFR level.
// Deterministic local curriculum data; APIs may enrich it but never generate it.
type Word = { word: string; translation: string; pos: string; example: string; exampleTranslation: string };
type Unit = { id: string; title: string; description: string; words: Word[]; phrases: { phrase: string; translation: string }[]; dialogue: { speaker: string; text: string; translation: string }[]; reading: { title: string; text: string; translation: string } };
const w = (word: string, translation: string, pos: string, example: string, exampleTranslation: string): Word => ({ word, translation, pos, example, exampleTranslation });
const u = (id: string, title: string, description: string, words: Word[]): Unit => ({
  id, title, description, words,
  phrases: words.slice(0, 4).map((item) => ({ phrase: item.example, translation: item.exampleTranslation })),
  dialogue: [0, 1, 2, 3].map((index) => ({ speaker: index % 2 === 0 ? "A" : "B", text: words[index]!.example, translation: words[index]!.exampleTranslation })),
  reading: { title, text: words.slice(0, 4).map((item) => item.example).join(" "), translation: words.slice(0, 4).map((item) => item.exampleTranslation).join(" ") },
});

export const ADDITIONAL_EN_PART6_UNITS: Record<string, Unit[]> = {
  A0: [
    u("u34", "Home and Objects", "Name rooms and common objects at home.", [
      w("home", "casa", "noun", "My home is small.", "Mi casa es pequeña."),
      w("door", "puerta", "noun", "The door is open.", "La puerta está abierta."),
      w("chair", "silla", "noun", "The chair is next to the table.", "La silla está junto a la mesa."),
      w("table", "mesa", "noun", "The book is on the table.", "El libro está sobre la mesa."),
      w("lamp", "lámpara", "noun", "The lamp is bright.", "La lámpara es luminosa."),
      w("book", "libro", "noun", "I am reading a book.", "Estoy leyendo un libro."),
      w("bag", "bolso", "noun", "The bag is on the floor.", "El bolso está en el suelo."),
      w("clock", "reloj", "noun", "The clock is on the wall.", "El reloj está en la pared."),
    ]),
    u("u35", "Colours and Clothes", "Describe colours and simple clothes.", [
      w("red", "rojo", "adjective", "I have a red shirt.", "Tengo una camisa roja."),
      w("blue", "azul", "adjective", "The sky is blue.", "El cielo es azul."),
      w("green", "verde", "adjective", "The tree is green.", "El árbol es verde."),
      w("black", "negro", "adjective", "She has a black coat.", "Ella tiene un abrigo negro."),
      w("shirt", "camisa", "noun", "The shirt is clean.", "La camisa está limpia."),
      w("trousers", "pantalones", "noun", "The trousers are new.", "Los pantalones son nuevos."),
      w("shoe", "zapato", "noun", "The shoe is on the foot.", "El zapato está en el pie."),
      w("hat", "sombrero", "noun", "The hat protects the head.", "El sombrero protege la cabeza."),
    ]),
  ],
  A1: [
    u("u34", "Food and Shopping", "Talk about food and buy everyday products.", [
      w("apple", "manzana", "noun", "The apple is sweet.", "La manzana es dulce."),
      w("bread", "pan", "noun", "I buy fresh bread.", "Compro pan fresco."),
      w("milk", "leche", "noun", "The milk is in the fridge.", "La leche está en la nevera."),
      w("cheese", "queso", "noun", "I like this cheese.", "Me gusta este queso."),
      w("price", "precio", "noun", "What is the price of this?", "¿Cuál es el precio de esto?"),
      w("cheap", "barato", "adjective", "This apple is cheap.", "Esta manzana es barata."),
      w("expensive", "caro", "adjective", "The restaurant is expensive.", "El restaurante es caro."),
      w("pay", "pagar", "verb", "I can pay by card.", "Puedo pagar con tarjeta."),
    ]),
    u("u35", "Directions and Movement", "Ask for and give simple directions.", [
      w("left", "izquierda", "noun", "Turn left.", "Gira a la izquierda."),
      w("right", "derecha", "noun", "Turn right.", "Gira a la derecha."),
      w("straight", "recto", "adverb", "Go straight ahead.", "Sigue recto."),
      w("near", "cerca", "adverb", "The station is near.", "La estación está cerca."),
      w("far", "lejos", "adverb", "The airport is far away.", "El aeropuerto está lejos."),
      w("bridge", "puente", "noun", "The bridge is over the river.", "El puente está sobre el río."),
      w("intersection", "cruce", "noun", "The intersection is next.", "El cruce está a continuación."),
      w("find", "encontrar", "verb", "You will find the museum easily.", "Encontrarás el museo fácilmente."),
    ]),
  ],
  A2: [
    u("u34", "Nature and Weather", "Describe nature and changing weather.", [
      w("forest", "bosque", "noun", "We walked in the forest.", "Caminamos por el bosque."),
      w("lake", "lago", "noun", "The lake is calm.", "El lago está tranquilo."),
      w("shore", "orilla", "noun", "There are many people on the shore.", "Hay muchas personas en la orilla."),
      w("cloud", "nube", "noun", "A dark cloud is approaching.", "Se acerca una nube oscura."),
      w("storm", "tormenta", "noun", "The storm began in the evening.", "La tormenta empezó por la tarde."),
      w("sunny", "soleado", "adjective", "Tomorrow will be sunny.", "Mañana estará soleado."),
      w("rain", "llover", "verb", "It is raining outside.", "Está lloviendo afuera."),
      w("protect", "proteger", "verb", "We must protect nature.", "Debemos proteger la naturaleza."),
    ]),
    u("u35", "Decisions and Plans", "Explain plans and give reasons for everyday decisions.", [
      w("goal", "objetivo", "noun", "My goal is to learn Finnish.", "Mi objetivo es aprender finés."),
      w("plan", "plan", "noun", "The plan changed quickly.", "El plan cambió rápidamente."),
      w("choice", "elección", "noun", "The choice was not easy.", "La elección no fue fácil."),
      w("reason", "razón", "noun", "What is the reason for the decision?", "¿Cuál es la razón de la decisión?"),
      w("alternative", "alternativa", "noun", "This is a good alternative.", "Esta es una buena alternativa."),
      w("decide", "decidir", "verb", "We decided to stay home.", "Decidimos quedarnos en casa."),
      w("compare", "comparar", "verb", "I compare two offers.", "Comparo dos ofertas."),
      w("succeed", "tener éxito", "verb", "She succeeded in the task.", "Ella tuvo éxito en la tarea."),
    ]),
  ],
  B1: [
    u("u34", "Media and Opinions", "Discuss news and express reasoned opinions.", [
      w("source", "fuente", "noun", "Check the source of the news.", "Comprueba la fuente de la noticia."),
      w("opinion", "opinión", "noun", "He expressed his opinion.", "Él expresó su opinión."),
      w("claim", "afirmación", "noun", "A claim needs evidence.", "Una afirmación necesita pruebas."),
      w("evidence", "prueba", "noun", "The report contains new evidence.", "El informe contiene nuevas pruebas."),
      w("perspective", "perspectiva", "noun", "The issue can be viewed from another perspective.", "El asunto puede verse desde otra perspectiva."),
      w("doubt", "dudar", "verb", "I may doubt the claim.", "Puedo dudar de la afirmación."),
      w("justify", "justificar", "verb", "She justified her decision.", "Ella justificó su decisión."),
      w("influence", "influir", "verb", "The media influences opinions.", "Los medios influyen en las opiniones."),
    ]),
    u("u35", "Volunteering and Community", "Explain how people can help their community.", [
      w("community", "comunidad", "noun", "The community organises an event.", "La comunidad organiza un evento."),
      w("volunteer", "voluntario", "noun", "The volunteer helps children.", "El voluntario ayuda a los niños."),
      w("help", "ayuda", "noun", "Help is needed quickly.", "Se necesita ayuda rápidamente."),
      w("organisation", "organización", "noun", "The organisation supports families.", "La organización apoya a las familias."),
      w("donation", "donación", "noun", "The donation supports the work.", "La donación apoya el trabajo."),
      w("participate", "participar", "verb", "Everyone can participate.", "Todos pueden participar."),
      w("support", "apoyar", "verb", "Neighbours support one another.", "Los vecinos se apoyan."),
      w("organise", "organizar", "verb", "Young people organise a concert.", "Los jóvenes organizan un concierto."),
    ]),
  ],
  B2: [
    u("u34", "Research and Evidence", "Analyse research methods and the quality of evidence.", [
      w("hypothesis", "hipótesis", "noun", "The study tests a hypothesis.", "El estudio prueba una hipótesis."),
      w("methodology", "metodología", "noun", "The methodology is described precisely.", "La metodología se describe con precisión."),
      w("sample", "muestra", "noun", "The sample was quite small.", "La muestra era bastante pequeña."),
      w("result", "resultado", "noun", "The result supports the earlier theory.", "El resultado apoya la teoría anterior."),
      w("limitation", "limitación", "noun", "The study has a clear limitation.", "El estudio tiene una limitación clara."),
      w("validate", "validar", "verb", "Additional tests can validate the model.", "Las pruebas adicionales pueden validar el modelo."),
      w("observe", "observar", "verb", "The researchers observed a change.", "Los investigadores observaron un cambio."),
      w("generalise", "generalizar", "verb", "The result cannot be generalised to everyone.", "El resultado no puede generalizarse a todos."),
    ]),
    u("u35", "Business and Negotiation", "Practise agreements, offers, and cooperation.", [
      w("contract", "contrato", "noun", "The contract will be signed tomorrow.", "El contrato se firmará mañana."),
      w("offer", "oferta", "noun", "The offer is valid for a week.", "La oferta es válida durante una semana."),
      w("negotiation", "negociación", "noun", "The negotiation lasted two hours.", "La negociación duró dos horas."),
      w("partner", "socio", "noun", "We trust the new partner.", "Confiamos en el nuevo socio."),
      w("risk", "riesgo", "noun", "The project involves financial risk.", "El proyecto implica un riesgo financiero."),
      w("negotiate", "negociar", "verb", "The parties negotiate the price.", "Las partes negocian el precio."),
      w("agree", "acordar", "verb", "We agreed on shared goals.", "Acordamos objetivos comunes."),
      w("forecast", "prever", "verb", "Experts forecast growth.", "Los expertos prevén crecimiento."),
    ]),
  ],
  C1: [
    u("u34", "Law and Public Policy", "Evaluate laws, regulation, and public decisions.", [
      w("legislation", "legislación", "noun", "New legislation changes the practice.", "La nueva legislación cambia la práctica."),
      w("regulation", "regulación", "noun", "Regulation protects consumers.", "La regulación protege a los consumidores."),
      w("obligation", "obligación", "noun", "The company has a specific obligation.", "La empresa tiene una obligación concreta."),
      w("right", "derecho", "noun", "Everyone has a right to information.", "Todos tienen derecho a la información."),
      w("impact", "impacto", "noun", "The decision has a broad impact.", "La decisión tiene un impacto amplio."),
      w("enact", "promulgar", "verb", "Parliament enacts a new law.", "El Parlamento promulga una nueva ley."),
      w("enforce", "hacer cumplir", "verb", "Authorities enforce the rules.", "Las autoridades hacen cumplir las normas."),
      w("evaluate", "evaluar", "verb", "The committee evaluates the policy's effects.", "El comité evalúa los efectos de la política."),
    ]),
    u("u35", "Language and Culture", "Explore how language expresses identity and culture.", [
      w("identity", "identidad", "noun", "Language is part of identity.", "La lengua es parte de la identidad."),
      w("dialect", "dialecto", "noun", "The region has its own dialect.", "La región tiene su propio dialecto."),
      w("idiom", "modismo", "noun", "The idiom cannot be translated directly.", "El modismo no puede traducirse directamente."),
      w("meaning", "significado", "noun", "The meaning of a word depends on context.", "El significado de una palabra depende del contexto."),
      w("tradition", "tradición", "noun", "The tradition passes from one generation to another.", "La tradición pasa de una generación a otra."),
      w("express", "expresar", "verb", "Art expresses shared experiences.", "El arte expresa experiencias compartidas."),
      w("interpret", "interpretar", "verb", "A reader can interpret the text differently.", "Un lector puede interpretar el texto de otra manera."),
      w("preserve", "preservar", "verb", "The school helps preserve the language.", "La escuela ayuda a preservar la lengua."),
    ]),
  ],
  C2: [
    u("u34", "Knowledge and Reality", "Reflect on the relationship between knowledge, truth, and perception.", [
      w("knowledge", "conocimiento", "noun", "Knowledge is often based on experience.", "El conocimiento suele basarse en la experiencia."),
      w("truth", "verdad", "noun", "Defining truth is not easy.", "Definir la verdad no es fácil."),
      w("perception", "percepción", "noun", "Perception can be limited.", "La percepción puede ser limitada."),
      w("reality", "realidad", "noun", "Language constructs part of reality.", "El lenguaje construye parte de la realidad."),
      w("justification", "justificación", "noun", "A claim needs justification.", "Una afirmación necesita justificación."),
      w("question", "cuestionar", "verb", "Philosophy questions assumptions.", "La filosofía cuestiona los supuestos."),
      w("infer", "inferir", "verb", "We can infer something from the result.", "Podemos inferir algo del resultado."),
      w("demonstrate", "demostrar", "verb", "The example demonstrates the problem.", "El ejemplo demuestra el problema."),
    ]),
    u("u35", "Global Ethics", "Discuss responsibility, justice, and a shared future.", [
      w("responsibility", "responsabilidad", "noun", "Shared responsibility requires cooperation.", "La responsabilidad compartida requiere cooperación."),
      w("justice", "justicia", "noun", "Justice does not always mean identical treatment.", "La justicia no siempre significa un trato idéntico."),
      w("human dignity", "dignidad humana", "noun", "Human dignity belongs to everyone.", "La dignidad humana pertenece a todos."),
      w("solidarity", "solidaridad", "noun", "Solidarity helps in a crisis.", "La solidaridad ayuda en una crisis."),
      w("interdependence", "interdependencia", "noun", "Global interdependence appears in trade.", "La interdependencia mundial aparece en el comercio."),
      w("defend", "defender", "verb", "The law defends the most vulnerable.", "La ley defiende a las personas más vulnerables."),
      w("share", "compartir", "verb", "We must share resources fairly.", "Debemos compartir los recursos de forma justa."),
      w("reconcile", "conciliar", "verb", "Dialogue can reconcile conflicting values.", "El diálogo puede conciliar valores enfrentados."),
    ]),
  ],
};
