// Professional English enrichment unit u59 for every CEFR level.
// Reference PDFs informed topic selection only; they are not runtime imports.
import type { ReadingText, VocabularyItem } from "./learn-data";

type PhraseSpec = { phrase: string; translation: string };
type LineSpec = { speaker: string; text: string; translation: string };
type WordSpec = {
  word: string; translation: string; pos: string; ipa: string; definition: string;
  example: string; exampleTranslation: string; synonyms: string[]; antonyms: string[];
  collocations: string[]; wordFamily: string[]; tags: string[]; category: string;
};
type UnitSeed = {
  id: string; title: string; description: string; words: VocabularyItem[];
  phrases: PhraseSpec[]; dialogue: LineSpec[]; reading: ReadingText & { title: string };
};

const w = (spec: WordSpec): VocabularyItem => ({ ...spec });
const u = (title: string, description: string, words: VocabularyItem[], phrases: PhraseSpec[], dialogue: LineSpec[], reading: ReadingText & { title: string }): UnitSeed => ({ id: "u59", title, description, words, phrases, dialogue, reading });

export const ADDITIONAL_EN_PART20_UNITS: Record<string, UnitSeed[]> = {
  A0: [
    u("Classroom Basics", "Name common classroom objects and follow simple learning instructions.", [
      w({ word: "desk", translation: "pupitre", pos: "noun", ipa: "/desk/", definition: "a table used for studying or writing", example: "My book is on the desk.", exampleTranslation: "Mi libro está en el pupitre.", synonyms: ["table"], antonyms: [], collocations: ["school desk", "sit at a desk"], wordFamily: ["desk", "desktop"], tags: ["school", "objects"], category: "object" }),
      w({ word: "ruler", translation: "regla", pos: "noun", ipa: "/ˈruːlər/", definition: "a straight tool used for measuring or drawing lines", example: "Use a ruler to draw a line.", exampleTranslation: "Usa una regla para dibujar una línea.", synonyms: ["measuring rule"], antonyms: [], collocations: ["plastic ruler", "use a ruler"], wordFamily: ["rule", "ruler"], tags: ["school", "tools"], category: "object" }),
      w({ word: "eraser", translation: "borrador", pos: "noun", ipa: "/ɪˈreɪsər/", definition: "a small object used to remove pencil marks", example: "The eraser is beside my pencil.", exampleTranslation: "El borrador está junto a mi lápiz.", synonyms: ["rubber"], antonyms: [], collocations: ["rubber eraser", "use an eraser"], wordFamily: ["erase", "eraser"], tags: ["school", "objects"], category: "object" }),
      w({ word: "glue", translation: "pegamento", pos: "noun", ipa: "/ɡluː/", definition: "a substance used to join things together", example: "The glue is on the art table.", exampleTranslation: "El pegamento está en la mesa de arte.", synonyms: ["adhesive"], antonyms: [], collocations: ["bottle of glue", "use glue"], wordFamily: ["glue", "gluey"], tags: ["school", "art"], category: "material" }),
      w({ word: "scissors", translation: "tijeras", pos: "noun", ipa: "/ˈsɪzərz/", definition: "a tool with two sharp blades used for cutting", example: "The scissors are in the box.", exampleTranslation: "Las tijeras están en la caja.", synonyms: ["cutting tool"], antonyms: [], collocations: ["pair of scissors", "cut with scissors"], wordFamily: ["scissor", "scissors"], tags: ["school", "tools"], category: "object" }),
      w({ word: "point", translation: "señalar", pos: "verb", ipa: "/pɔɪnt/", definition: "to show someone or something with a finger or object", example: "Please point to the answer.", exampleTranslation: "Señala la respuesta, por favor.", synonyms: ["indicate", "show"], antonyms: [], collocations: ["point to a word", "point at the picture"], wordFamily: ["point", "pointer"], tags: ["school", "action"], category: "action" }),
      w({ word: "colour", translation: "colorear", pos: "verb", ipa: "/ˈkʌlər/", definition: "to add a colour to a picture or object", example: "Colour the circle blue.", exampleTranslation: "Colorea el círculo de azul.", synonyms: ["paint", "shade"], antonyms: [], collocations: ["colour a picture", "bright colour"], wordFamily: ["colour", "colourful"], tags: ["school", "art"], category: "action" }),
      w({ word: "answer", translation: "respuesta", pos: "noun", ipa: "/ˈænsər/", definition: "something said or written in reply to a question", example: "Write one answer here.", exampleTranslation: "Escribe una respuesta aquí.", synonyms: ["reply", "response"], antonyms: ["question"], collocations: ["correct answer", "write an answer"], wordFamily: ["answer", "answerable"], tags: ["school", "communication"], category: "communication" }),
    ], [
      { phrase: "Open your book, please.", translation: "Abre tu libro, por favor." }, { phrase: "Listen and repeat.", translation: "Escucha y repite." }, { phrase: "Draw a straight line.", translation: "Dibuja una línea recta." }, { phrase: "What is the answer?", translation: "¿Cuál es la respuesta?" },
    ], [
      { speaker: "A", text: "Where is my ruler?", translation: "¿Dónde está mi regla?" }, { speaker: "B", text: "It is beside your desk.", translation: "Está junto a tu pupitre." }, { speaker: "A", text: "Can I use the scissors?", translation: "¿Puedo usar las tijeras?" }, { speaker: "B", text: "Yes. Please listen to the teacher.", translation: "Sí. Escucha al profesor, por favor." },
    ], { title: "A Busy Classroom", text: "Nora puts her book on the desk. She uses a ruler, an eraser, glue, and scissors for an art task. The teacher asks her to point to a picture, colour it, and write one answer.", translation: "Nora pone su libro en el pupitre. Usa una regla, un borrador, pegamento y tijeras para una tarea de arte. El profesor le pide que señale una imagen, la coloree y escriba una respuesta." }),
  ],
  A1: [
    u("Sending a Letter", "Handle a simple visit to a post office and describe sending ordinary mail.", [
      w({ word: "stamp", translation: "sello", pos: "noun", ipa: "/stæmp/", definition: "a small piece of paper showing that postage has been paid", example: "Put a stamp on the envelope.", exampleTranslation: "Pon un sello en el sobre.", synonyms: ["postage stamp"], antonyms: [], collocations: ["buy a stamp", "stamp collection"], wordFamily: ["stamp", "stamped"], tags: ["mail", "errands"], category: "object" }),
      w({ word: "postcard", translation: "postal", pos: "noun", ipa: "/ˈpoʊstkɑːrd/", definition: "a card sent by mail without an envelope", example: "I sent a postcard from the coast.", exampleTranslation: "Envié una postal desde la costa.", synonyms: ["mail card"], antonyms: [], collocations: ["send a postcard", "picture postcard"], wordFamily: ["post", "postcard"], tags: ["mail", "travel"], category: "document" }),
      w({ word: "envelope", translation: "sobre", pos: "noun", ipa: "/ˈenvəloʊp/", definition: "a paper container used for a letter", example: "The address is on the envelope.", exampleTranslation: "La dirección está en el sobre.", synonyms: ["cover"], antonyms: [], collocations: ["address an envelope", "sealed envelope"], wordFamily: ["envelop", "envelope"], tags: ["mail", "documents"], category: "object" }),
      w({ word: "parcel", translation: "paquete", pos: "noun", ipa: "/ˈpɑːrsəl/", definition: "a package sent or received by mail", example: "A parcel arrived this morning.", exampleTranslation: "Un paquete llegó esta mañana.", synonyms: ["package", "packet"], antonyms: [], collocations: ["send a parcel", "small parcel"], wordFamily: ["parcel", "parcelled"], tags: ["mail", "delivery"], category: "object" }),
      w({ word: "postbox", translation: "buzón", pos: "noun", ipa: "/ˈpoʊstbɑːks/", definition: "a public box where letters are collected", example: "The red postbox is near the station.", exampleTranslation: "El buzón rojo está cerca de la estación.", synonyms: ["mailbox"], antonyms: [], collocations: ["empty a postbox", "public postbox"], wordFamily: ["post", "postbox"], tags: ["mail", "places"], category: "place" }),
      w({ word: "postage", translation: "franqueo", pos: "noun", ipa: "/ˈpoʊstɪdʒ/", definition: "the money needed to send something by mail", example: "The postage costs two euros.", exampleTranslation: "El franqueo cuesta dos euros.", synonyms: ["mail charge"], antonyms: [], collocations: ["pay postage", "postage cost"], wordFamily: ["post", "postage"], tags: ["mail", "money"], category: "cost" }),
      w({ word: "deliver", translation: "entregar", pos: "verb", ipa: "/dɪˈlɪvər/", definition: "to take something to a person or place", example: "They deliver parcels every afternoon.", exampleTranslation: "Entregan paquetes cada tarde.", synonyms: ["bring", "transport"], antonyms: ["collect"], collocations: ["deliver a letter", "home delivery"], wordFamily: ["deliver", "delivery", "deliverer"], tags: ["mail", "action"], category: "action" }),
      w({ word: "counter", translation: "mostrador", pos: "noun", ipa: "/ˈkaʊntər/", definition: "a long surface where customers are served", example: "Please take this form to the counter.", exampleTranslation: "Lleva este formulario al mostrador, por favor.", synonyms: ["service desk"], antonyms: [], collocations: ["service counter", "stand at the counter"], wordFamily: ["count", "counter"], tags: ["mail", "services"], category: "place" }),
    ], [
      { phrase: "I would like to send this letter.", translation: "Quisiera enviar esta carta." }, { phrase: "How much is the postage?", translation: "¿Cuánto cuesta el franqueo?" }, { phrase: "Where can I buy a stamp?", translation: "¿Dónde puedo comprar un sello?" }, { phrase: "When will the parcel arrive?", translation: "¿Cuándo llegará el paquete?" },
    ], [
      { speaker: "A", text: "Could you help me send this parcel?", translation: "¿Podría ayudarme a enviar este paquete?" }, { speaker: "B", text: "Certainly. Please complete this form at the counter.", translation: "Por supuesto. Complete este formulario en el mostrador, por favor." }, { speaker: "A", text: "How much is the postage?", translation: "¿Cuánto cuesta el franqueo?" }, { speaker: "B", text: "It is six euros, including the stamp.", translation: "Son seis euros, incluido el sello." },
    ], { title: "A Visit to the Post Office", text: "Eva writes a postcard and puts it in an envelope. At the post office, she completes a form at the counter and pays the postage. The clerk adds a stamp and explains that the parcel will be delivered on Friday.", translation: "Eva escribe una postal y la pone en un sobre. En la oficina de correos, completa un formulario en el mostrador y paga el franqueo. El empleado añade un sello y explica que el paquete se entregará el viernes." }),
  ],
  A2: [
    u("Emergency Help", "Report an accident, describe danger, and ask for immediate assistance.", [
      w({ word: "emergency", translation: "emergencia", pos: "noun", ipa: "/ɪˈmɜːrdʒənsi/", definition: "a sudden serious situation needing immediate action", example: "Call this number in an emergency.", exampleTranslation: "Llama a este número en una emergencia.", synonyms: ["crisis", "urgent situation"], antonyms: ["safety"], collocations: ["medical emergency", "emergency number"], wordFamily: ["emerge", "emergency"], tags: ["safety", "health"], category: "situation" }),
      w({ word: "ambulance", translation: "ambulancia", pos: "noun", ipa: "/ˈæmbjələns/", definition: "a vehicle that takes sick or injured people to hospital", example: "An ambulance arrived quickly.", exampleTranslation: "Una ambulancia llegó rápidamente.", synonyms: ["emergency vehicle"], antonyms: [], collocations: ["call an ambulance", "ambulance crew"], wordFamily: ["ambulance"], tags: ["safety", "health"], category: "vehicle" }),
      w({ word: "injured", translation: "herido", pos: "adjective", ipa: "/ˈɪndʒərd/", definition: "hurt because of an accident or attack", example: "The cyclist was injured but awake.", exampleTranslation: "El ciclista estaba herido pero consciente.", synonyms: ["hurt", "wounded"], antonyms: ["unhurt"], collocations: ["seriously injured", "injured person"], wordFamily: ["injure", "injured", "injury"], tags: ["safety", "body"], category: "condition" }),
      w({ word: "alarm", translation: "alarma", pos: "noun", ipa: "/əˈlɑːrm/", definition: "a warning sound or device for danger", example: "The fire alarm is ringing.", exampleTranslation: "La alarma de incendios está sonando.", synonyms: ["warning", "signal"], antonyms: ["silence"], collocations: ["sound an alarm", "alarm system"], wordFamily: ["alarm", "alarming"], tags: ["safety", "buildings"], category: "warning" }),
      w({ word: "rescue", translation: "rescate", pos: "noun", ipa: "/ˈreskjuː/", definition: "the act of saving someone from danger", example: "The rescue took two hours.", exampleTranslation: "El rescate duró dos horas.", synonyms: ["saving", "救援"], antonyms: ["abandonment"], collocations: ["rescue team", "mountain rescue"], wordFamily: ["rescue", "rescuer"], tags: ["safety", "action"], category: "action" }),
      w({ word: "witness", translation: "testigo", pos: "noun", ipa: "/ˈwɪtnəs/", definition: "a person who sees an event happen", example: "A witness called the police.", exampleTranslation: "Un testigo llamó a la policía.", synonyms: ["observer", "bystander"], antonyms: [], collocations: ["eye witness", "witness an accident"], wordFamily: ["witness"], tags: ["safety", "people"], category: "person" }),
      w({ word: "escape", translation: "escapar", pos: "verb", ipa: "/ɪˈskeɪp/", definition: "to get away from a dangerous place or situation", example: "Leave the building and do not try to escape alone.", exampleTranslation: "Sal del edificio y no intentes escapar solo.", synonyms: ["get away", "flee"], antonyms: ["remain", "stay"], collocations: ["escape from danger", "escape route"], wordFamily: ["escape", "escapable"], tags: ["safety", "movement"], category: "action" }),
      w({ word: "first aid", translation: "primeros auxilios", pos: "noun", ipa: "/ˌfɜːrst ˈeɪd/", definition: "basic medical help given before professional care", example: "She learned first aid at school.", exampleTranslation: "Aprendió primeros auxilios en la escuela.", synonyms: ["immediate care"], antonyms: [], collocations: ["give first aid", "first-aid kit"], wordFamily: ["first", "aid", "aider"], tags: ["safety", "health"], category: "care" }),
    ], [
      { phrase: "There has been an accident.", translation: "Ha habido un accidente." }, { phrase: "Please call an ambulance.", translation: "Llama a una ambulancia, por favor." }, { phrase: "Is anyone injured?", translation: "¿Hay alguien herido?" }, { phrase: "Stay calm and move to safety.", translation: "Mantén la calma y muévete a un lugar seguro." },
    ], [
      { speaker: "A", text: "There has been an accident near the bridge.", translation: "Ha habido un accidente cerca del puente." }, { speaker: "B", text: "Is anyone injured? I will call an ambulance.", translation: "¿Hay alguien herido? Llamaré a una ambulancia." }, { speaker: "A", text: "A witness is giving first aid.", translation: "Un testigo está dando primeros auxilios." }, { speaker: "B", text: "Good. Keep away from the danger and wait for help.", translation: "Bien. Aléjate del peligro y espera ayuda." },
    ], { title: "Calling for Help", text: "On the way home, Lina sees an accident. One person is injured, so she calls the emergency number. A witness gives first aid while an alarm warns people to move away from danger. The ambulance arrives and the rescue team takes control.", translation: "De camino a casa, Lina ve un accidente. Una persona está herida, así que llama al número de emergencias. Un testigo da primeros auxilios mientras una alarma avisa a la gente que se aleje del peligro. Llega la ambulancia y el equipo de rescate toma el control." }),
  ],
  B1: [
    u("Community Volunteering", "Discuss civic participation, charitable work, and practical support for neighbours.", [
      w({ word: "volunteer", translation: "voluntario", pos: "noun", ipa: "/ˌvɑːlənˈtɪr/", definition: "a person who freely gives time to help others", example: "Each volunteer welcomes visitors at the shelter.", exampleTranslation: "Cada voluntario recibe a los visitantes en el refugio.", synonyms: ["helper", "unpaid worker"], antonyms: ["recipient"], collocations: ["volunteer work", "local volunteer"], wordFamily: ["volunteer", "voluntary"], tags: ["community", "work"], category: "person" }),
      w({ word: "charity", translation: "organización benéfica", pos: "noun", ipa: "/ˈtʃærəti/", definition: "an organisation that helps people or causes in need", example: "The charity provides meals in winter.", exampleTranslation: "La organización benéfica proporciona comidas en invierno.", synonyms: ["non-profit", "aid organisation"], antonyms: [], collocations: ["charity event", "support a charity"], wordFamily: ["charity", "charitable"], tags: ["community", "society"], category: "organisation" }),
      w({ word: "donate", translation: "donar", pos: "verb", ipa: "/ˈdoʊneɪt/", definition: "to give money or goods to help a person or cause", example: "Residents donate clothes to the centre.", exampleTranslation: "Los residentes donan ropa al centro.", synonyms: ["give", "contribute"], antonyms: ["take"], collocations: ["donate money", "donate goods"], wordFamily: ["donate", "donation", "donor"], tags: ["community", "money"], category: "action" }),
      w({ word: "community", translation: "comunidad", pos: "noun", ipa: "/kəˈmjuːnəti/", definition: "the people living in a particular area or sharing an interest", example: "The community meets every month.", exampleTranslation: "La comunidad se reúne cada mes.", synonyms: ["neighbourhood", "society"], antonyms: ["isolation"], collocations: ["local community", "community centre"], wordFamily: ["commune", "community", "communal"], tags: ["society", "people"], category: "group" }),
      w({ word: "elderly", translation: "anciano", pos: "adjective", ipa: "/ˈeldərli/", definition: "old, especially when talking about people who need care", example: "The project supports elderly neighbours.", exampleTranslation: "El proyecto apoya a los vecinos ancianos.", synonyms: ["older", "senior"], antonyms: ["young"], collocations: ["elderly people", "care for the elderly"], wordFamily: ["old", "elderly"], tags: ["community", "age"], category: "people" }),
      w({ word: "shelter", translation: "refugio", pos: "noun", ipa: "/ˈʃeltər/", definition: "a place that provides protection or a home for people or animals", example: "The shelter needs more blankets.", exampleTranslation: "El refugio necesita más mantas.", synonyms: ["refuge", "safe place"], antonyms: ["exposure"], collocations: ["homeless shelter", "animal shelter"], wordFamily: ["shelter", "sheltered"], tags: ["community", "care"], category: "place" }),
      w({ word: "support", translation: "apoyar", pos: "verb", ipa: "/səˈpɔːrt/", definition: "to help someone emotionally, practically, or financially", example: "Neighbours support the food programme.", exampleTranslation: "Los vecinos apoyan el programa de alimentos.", synonyms: ["assist", "help"], antonyms: ["oppose"], collocations: ["support a cause", "emotional support"], wordFamily: ["support", "supportive"], tags: ["community", "communication"], category: "action" }),
      w({ word: "outreach", translation: "acción comunitaria", pos: "noun", ipa: "/ˈaʊtriːtʃ/", definition: "efforts to reach and help people in a community", example: "The outreach team visits isolated families.", exampleTranslation: "El equipo de acción comunitaria visita a familias aisladas.", synonyms: ["community service", "engagement"], antonyms: ["withdrawal"], collocations: ["outreach programme", "community outreach"], wordFamily: ["reach", "outreach"], tags: ["community", "society"], category: "service" }),
    ], [
      { phrase: "How can I help the community?", translation: "¿Cómo puedo ayudar a la comunidad?" }, { phrase: "We are collecting donations.", translation: "Estamos recogiendo donaciones." }, { phrase: "The shelter needs more volunteers.", translation: "El refugio necesita más voluntarios." }, { phrase: "Every small contribution matters.", translation: "Cada pequeña contribución importa." },
    ], [
      { speaker: "A", text: "What does the charity need this week?", translation: "¿Qué necesita la organización benéfica esta semana?" }, { speaker: "B", text: "It needs volunteers and donations for the elderly.", translation: "Necesita voluntarios y donaciones para los ancianos." }, { speaker: "A", text: "I can support the outreach programme on Saturday.", translation: "Puedo apoyar el programa de acción comunitaria el sábado." }, { speaker: "B", text: "Excellent. The whole community will benefit.", translation: "Excelente. Toda la comunidad se beneficiará." },
    ], { title: "A Neighbourhood That Helps", text: "A local charity has opened an outreach programme for elderly residents and families without stable housing. Volunteers sort donated food, support the shelter, and listen to people who need practical help. The project shows how a community can turn concern into organised action.", translation: "Una organización benéfica local ha abierto un programa de acción comunitaria para residentes ancianos y familias sin vivienda estable. Los voluntarios clasifican alimentos donados, apoyan al refugio y escuchan a las personas que necesitan ayuda práctica. El proyecto muestra cómo una comunidad puede convertir la preocupación en acción organizada." }),
  ],
  B2: [
    u("Personal Finance", "Analyse borrowing, saving, investment, and financial risk in everyday decisions.", [
      w({ word: "mortgage", translation: "hipoteca", pos: "noun", ipa: "/ˈmɔːrɡɪdʒ/", definition: "a long-term loan used to buy a house or property", example: "They took out a mortgage to buy a flat.", exampleTranslation: "Pidieron una hipoteca para comprar un piso.", synonyms: ["home loan"], antonyms: [], collocations: ["pay a mortgage", "mortgage rate"], wordFamily: ["mortgage"], tags: ["finance", "housing"], category: "loan" }),
      w({ word: "dividend", translation: "dividendo", pos: "noun", ipa: "/ˈdɪvɪdend/", definition: "money paid regularly to shareholders from a company's profits", example: "The fund paid a modest dividend.", exampleTranslation: "El fondo pagó un dividendo moderado.", synonyms: ["share payment"], antonyms: [], collocations: ["annual dividend", "pay a dividend"], wordFamily: ["divide", "dividend"], tags: ["finance", "investment"], category: "return" }),
      w({ word: "revenue", translation: "ingresos", pos: "noun", ipa: "/ˈrevənuː/", definition: "the money a business receives from its sales or activities", example: "The company increased its annual revenue.", exampleTranslation: "La empresa aumentó sus ingresos anuales.", synonyms: ["income", "sales"], antonyms: ["expense"], collocations: ["generate revenue", "annual revenue"], wordFamily: ["revenue"], tags: ["finance", "business"], category: "money" }),
      w({ word: "expenditure", translation: "gasto", pos: "noun", ipa: "/ɪkˈspendɪtʃər/", definition: "money that is spent on something", example: "Public expenditure must be monitored carefully.", exampleTranslation: "El gasto público debe vigilarse cuidadosamente.", synonyms: ["spending", "expense"], antonyms: ["income"], collocations: ["public expenditure", "reduce expenditure"], wordFamily: ["expend", "expenditure"], tags: ["finance", "government"], category: "money" }),
      w({ word: "portfolio", translation: "cartera de inversiones", pos: "noun", ipa: "/pɔːrtˈfoʊlioʊ/", definition: "a collection of investments owned by a person or organisation", example: "She diversified her investment portfolio.", exampleTranslation: "Diversificó su cartera de inversiones.", synonyms: ["holdings", "collection"], antonyms: [], collocations: ["investment portfolio", "diversify a portfolio"], wordFamily: ["portfolio"], tags: ["finance", "investment"], category: "assets" }),
      w({ word: "liquidity", translation: "liquidez", pos: "noun", ipa: "/lɪˈkwɪdəti/", definition: "the ease with which an asset can be turned into cash", example: "Cash offers greater liquidity than property.", exampleTranslation: "El efectivo ofrece mayor liquidez que la propiedad.", synonyms: ["cash availability"], antonyms: ["illiquidity"], collocations: ["provide liquidity", "liquidity risk"], wordFamily: ["liquid", "liquidity"], tags: ["finance", "risk"], category: "quality" }),
      w({ word: "solvency", translation: "solvencia", pos: "noun", ipa: "/ˈsɑːlvənsi/", definition: "the ability to pay debts over the long term", example: "The audit examined the bank's solvency.", exampleTranslation: "La auditoría examinó la solvencia del banco.", synonyms: ["financial stability"], antonyms: ["insolvency"], collocations: ["maintain solvency", "solvency ratio"], wordFamily: ["solve", "solvent", "solvency"], tags: ["finance", "business"], category: "stability" }),
      w({ word: "compound", translation: "acumular intereses", pos: "verb", ipa: "/kəmˈpaʊnd/", definition: "to calculate interest on both money and earlier interest", example: "Small deposits compound over many years.", exampleTranslation: "Los pequeños depósitos acumulan intereses durante muchos años.", synonyms: ["accumulate", "build up"], antonyms: ["reduce"], collocations: ["compound interest", "compound annually"], wordFamily: ["compound", "compounding"], tags: ["finance", "time"], category: "growth" }),
    ], [
      { phrase: "What is the long-term cost of the loan?", translation: "¿Cuál es el coste a largo plazo del préstamo?" }, { phrase: "We need to balance risk and return.", translation: "Necesitamos equilibrar el riesgo y el rendimiento." }, { phrase: "The company reported higher revenue.", translation: "La empresa informó de mayores ingresos." }, { phrase: "Keep enough cash for emergencies.", translation: "Guarda suficiente efectivo para las emergencias." },
    ], [
      { speaker: "A", text: "Should we invest all our savings in one company?", translation: "¿Deberíamos invertir todos nuestros ahorros en una sola empresa?" }, { speaker: "B", text: "No. A diversified portfolio reduces concentration risk.", translation: "No. Una cartera diversificada reduce el riesgo de concentración." }, { speaker: "A", text: "What about liquidity?", translation: "¿Y la liquidez?" }, { speaker: "B", text: "We should keep some cash while the investment compounds.", translation: "Deberíamos guardar algo de efectivo mientras la inversión acumula intereses." },
    ], { title: "A Sustainable Financial Plan", text: "Before taking on a mortgage, Daniel reviews his expenditure, income, and emergency savings. He studies the liquidity and solvency of several investments, then builds a diversified portfolio. Rather than chasing a quick return, he chooses assets that can compound steadily without placing his household under unnecessary risk.", translation: "Antes de asumir una hipoteca, Daniel revisa sus gastos, ingresos y ahorros de emergencia. Estudia la liquidez y solvencia de varias inversiones y luego crea una cartera diversificada. En lugar de buscar un rendimiento rápido, elige activos que puedan acumular intereses de forma constante sin someter a su hogar a un riesgo innecesario." }),
  ],
  C1: [
    u("Cognitive Bias and Decisions", "Discuss how mental shortcuts and assumptions influence judgement and evidence-based choices.", [
      w({ word: "overconfidence", translation: "exceso de confianza", pos: "noun", ipa: "/ˌoʊvərˈkɑːnfɪdəns/", definition: "too much belief in one's own ability or judgement", example: "Overconfidence made the team ignore useful warnings.", exampleTranslation: "El exceso de confianza hizo que el equipo ignorara advertencias útiles.", synonyms: ["self-assurance", "certainty"], antonyms: ["self-doubt"], collocations: ["dangerous overconfidence", "overconfidence bias"], wordFamily: ["confide", "confident", "overconfidence"], tags: ["psychology", "thinking"], category: "bias" }),
      w({ word: "intuition", translation: "intuición", pos: "noun", ipa: "/ˌɪntuˈɪʃən/", definition: "a feeling of knowing something without conscious reasoning", example: "Her intuition warned her to examine the figures again.", exampleTranslation: "Su intuición le advirtió que revisara las cifras otra vez.", synonyms: ["instinct", "sixth sense"], antonyms: ["analysis"], collocations: ["trust one's intuition", "professional intuition"], wordFamily: ["intuit", "intuitive", "intuition"], tags: ["psychology", "decisions"], category: "judgement" }),
      w({ word: "rationale", translation: "fundamento", pos: "noun", ipa: "/ˌræʃəˈnæl/", definition: "the reasons or logical basis for a decision", example: "The report explains the rationale behind the policy.", exampleTranslation: "El informe explica el fundamento de la política.", synonyms: ["reasoning", "logic"], antonyms: ["irrationality"], collocations: ["clear rationale", "provide a rationale"], wordFamily: ["reason", "rational", "rationale"], tags: ["thinking", "writing"], category: "reasoning" }),
      w({ word: "subjective", translation: "subjetivo", pos: "adjective", ipa: "/səbˈdʒektɪv/", definition: "based on personal feelings rather than external facts", example: "The rating is partly subjective.", exampleTranslation: "La valoración es en parte subjetiva.", synonyms: ["personal", "individual"], antonyms: ["objective"], collocations: ["subjective judgement", "subjective experience"], wordFamily: ["subject", "subjective", "subjectivity"], tags: ["thinking", "research"], category: "quality" }),
      w({ word: "systemic", translation: "sistémico", pos: "adjective", ipa: "/sɪˈstemɪk/", definition: "relating to a whole system rather than one part", example: "The researchers found systemic problems in the process.", exampleTranslation: "Los investigadores encontraron problemas sistémicos en el proceso.", synonyms: ["structural", "institutional"], antonyms: ["isolated"], collocations: ["systemic bias", "systemic change"], wordFamily: ["system", "systemic", "systematically"], tags: ["society", "analysis"], category: "systems" }),
      w({ word: "framing", translation: "encuadre", pos: "noun", ipa: "/ˈfreɪmɪŋ/", definition: "the way information is presented to influence how it is understood", example: "The framing of the question changed the responses.", exampleTranslation: "El encuadre de la pregunta cambió las respuestas.", synonyms: ["presentation", "angle"], antonyms: [], collocations: ["political framing", "framing effect"], wordFamily: ["frame", "framing"], tags: ["psychology", "media"], category: "communication" }),
      w({ word: "correlation", translation: "correlación", pos: "noun", ipa: "/ˌkɔːrəˈleɪʃən/", definition: "a relationship in which two things change together", example: "The study found a correlation, not proof of causation.", exampleTranslation: "El estudio encontró una correlación, no una prueba de causalidad.", synonyms: ["association", "connection"], antonyms: [], collocations: ["strong correlation", "correlation between variables"], wordFamily: ["correlate", "correlation"], tags: ["research", "statistics"], category: "relationship" }),
      w({ word: "causation", translation: "causalidad", pos: "noun", ipa: "/kɔːˈzeɪʃən/", definition: "the relationship in which one event produces another", example: "The evidence does not establish causation.", exampleTranslation: "Las pruebas no establecen causalidad.", synonyms: ["cause and effect"], antonyms: [], collocations: ["prove causation", "causal relationship"], wordFamily: ["cause", "causal", "causation"], tags: ["research", "reasoning"], category: "relationship" }),
    ], [
      { phrase: "What is the rationale for this decision?", translation: "¿Cuál es el fundamento de esta decisión?" }, { phrase: "Correlation does not prove causation.", translation: "La correlación no demuestra causalidad." }, { phrase: "We should question our assumptions.", translation: "Deberíamos cuestionar nuestras suposiciones." }, { phrase: "The result may reflect a framing effect.", translation: "El resultado puede reflejar un efecto de encuadre." },
    ], [
      { speaker: "A", text: "Why did the committee reject the evidence?", translation: "¿Por qué rechazó el comité las pruebas?" }, { speaker: "B", text: "The decision may reflect overconfidence and subjective judgement.", translation: "La decisión puede reflejar exceso de confianza y juicio subjetivo." }, { speaker: "A", text: "Does the study show causation?", translation: "¿Muestra causalidad el estudio?" }, { speaker: "B", text: "No. It shows a correlation, so we need a stronger rationale.", translation: "No. Muestra una correlación, así que necesitamos un fundamento más sólido." },
    ], { title: "Thinking About Thinking", text: "A public organisation reviews why an earlier decision failed. The panel identifies overconfidence, a persuasive framing effect, and a tendency to confuse correlation with causation. By separating intuition from evidence and making its rationale explicit, the organisation can reduce systemic errors in future decisions.", translation: "Una organización pública revisa por qué fracasó una decisión anterior. El panel identifica exceso de confianza, un efecto de encuadre persuasivo y una tendencia a confundir correlación con causalidad. Al separar la intuición de las pruebas y hacer explícito su fundamento, la organización puede reducir errores sistémicos en decisiones futuras." }),
  ],
  C2: [
    u("Meaning, Signs, and Interpretation", "Analyse advanced relationships among language, cultural signs, implied meaning, and interpretation.", [
      w({ word: "implicature", translation: "implicatura", pos: "noun", ipa: "/ˈɪmplɪkətʃər/", definition: "a meaning suggested by an utterance rather than directly stated", example: "The refusal carries an implicature of disagreement.", exampleTranslation: "La negativa contiene una implicatura de desacuerdo.", synonyms: ["implication", "suggested meaning"], antonyms: ["explicitness"], collocations: ["conversational implicature", "infer an implicature"], wordFamily: ["imply", "implicit", "implicature"], tags: ["linguistics", "pragmatics"], category: "meaning" }),
      w({ word: "entailment", translation: "implicación lógica", pos: "noun", ipa: "/ɪnˈteɪlmənt/", definition: "a relationship in which one statement must be true if another is true", example: "The second sentence is an entailment of the first.", exampleTranslation: "La segunda oración es una implicación lógica de la primera.", synonyms: ["logical consequence", "implication"], antonyms: [], collocations: ["semantic entailment", "logical entailment"], wordFamily: ["entail", "entailing", "entailment"], tags: ["linguistics", "logic"], category: "meaning" }),
      w({ word: "metonymy", translation: "metonimia", pos: "noun", ipa: "/məˈtɑːnəmi/", definition: "a figure of speech using a related term to refer to something", example: "The White House is a metonymy for the administration.", exampleTranslation: "La Casa Blanca es una metonimia de la administración.", synonyms: ["substitution", "figure of speech"], antonyms: [], collocations: ["political metonymy", "metonymic expression"], wordFamily: ["metonym", "metonymic", "metonymy"], tags: ["rhetoric", "meaning"], category: "device" }),
      w({ word: "intertextuality", translation: "intertextualidad", pos: "noun", ipa: "/ˌɪntərtekstʃuˈæləti/", definition: "the way a text gains meaning through links with other texts", example: "The novel uses intertextuality to echo an ancient myth.", exampleTranslation: "La novela usa intertextualidad para evocar un mito antiguo.", synonyms: ["textual connection", "allusion"], antonyms: [], collocations: ["literary intertextuality", "intertextual reference"], wordFamily: ["text", "intertextual", "intertextuality"], tags: ["literature", "linguistics"], category: "relation" }),
      w({ word: "paratext", translation: "paratexto", pos: "noun", ipa: "/ˈpærətekst/", definition: "material around a main text that shapes how it is read", example: "The title and notes form part of the book's paratext.", exampleTranslation: "El título y las notas forman parte del paratexto del libro.", synonyms: ["supplementary text", "framing material"], antonyms: [], collocations: ["editorial paratext", "paratextual feature"], wordFamily: ["text", "paratext", "paratextual"], tags: ["literature", "publishing"], category: "text" }),
      w({ word: "multimodality", translation: "multimodalidad", pos: "noun", ipa: "/ˌmʌlti moʊˈdæləti/", definition: "the use of several communication modes such as words, images, and sound", example: "The campaign's multimodality makes it persuasive.", exampleTranslation: "La multimodalidad de la campaña la hace persuasiva.", synonyms: ["mixed-mode communication"], antonyms: ["monomodality"], collocations: ["digital multimodality", "multimodal text"], wordFamily: ["mode", "multimodal", "multimodality"], tags: ["media", "communication"], category: "style" }),
      w({ word: "ideology", translation: "ideología", pos: "noun", ipa: "/ˌaɪdiˈɑːlədʒi/", definition: "a system of ideas and beliefs shaping how society is understood", example: "The advertisement presents a clear ideology of success.", exampleTranslation: "El anuncio presenta una ideología clara del éxito.", synonyms: ["worldview", "doctrine"], antonyms: [], collocations: ["dominant ideology", "ideological assumption"], wordFamily: ["idea", "ideological", "ideology"], tags: ["society", "critical thinking"], category: "belief" }),
      w({ word: "salience", translation: "prominencia", pos: "noun", ipa: "/ˈseɪliəns/", definition: "the quality of being especially noticeable or important", example: "Repetition increases the salience of the slogan.", exampleTranslation: "La repetición aumenta la prominencia del eslogan.", synonyms: ["prominence", "noticeability"], antonyms: ["inconspicuousness"], collocations: ["semantic salience", "increase salience"], wordFamily: ["salient", "salience"], tags: ["linguistics", "rhetoric"], category: "attention" }),
    ], [
      { phrase: "The utterance implies more than it states.", translation: "El enunciado implica más de lo que afirma." }, { phrase: "This conclusion is logically entailed.", translation: "Esta conclusión está lógicamente implicada." }, { phrase: "The title frames the reading.", translation: "El título encuadra la lectura." }, { phrase: "Images and words work multimodally.", translation: "Las imágenes y las palabras funcionan de manera multimodal." },
    ], [
      { speaker: "A", text: "Is the speaker's meaning completely explicit?", translation: "¿Es completamente explícito el significado del hablante?" }, { speaker: "B", text: "No. The implicature depends on shared context.", translation: "No. La implicatura depende del contexto compartido." }, { speaker: "A", text: "What makes the campaign persuasive?", translation: "¿Qué hace persuasiva a la campaña?" }, { speaker: "B", text: "Its multimodality, ideology, and highly salient images work together.", translation: "Su multimodalidad, ideología e imágenes muy prominentes funcionan juntas." },
    ], { title: "Beyond the Literal", text: "Interpretation rarely stops at literal wording. An utterance can generate an implicature, while a proposition may entail another through logic. In literary and digital texts, intertextuality, paratext, multimodality, and ideology guide attention and shape what becomes salient to readers.", translation: "La interpretación rara vez se detiene en las palabras literales. Un enunciado puede generar una implicatura, mientras que una proposición puede implicar otra mediante la lógica. En textos literarios y digitales, la intertextualidad, el paratexto, la multimodalidad y la ideología guían la atención y determinan lo que se vuelve prominente para los lectores." }),
  ],
};
