import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/** Reviewed vocabulary for the existing B1, B2, and C1 u5 units. */
export const ENGLISH_B1_B2_C1_U5_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u5: [
      reviewed({ word: "data consent", translation: "موافقة على استخدام البيانات", pos: "noun", ipa: "/ˈdeɪtə kənˌsent/", definition: "permission for an organisation to collect or use a person’s information", example: "The app asks for data consent before it records the user’s location.", exampleTranslation: "يطلب التطبيق موافقة على استخدام البيانات قبل تسجيل موقع المستخدم.", category: "technology and daily life", tags: ["technology", "privacy"], synonyms: ["consent to data use", "information consent"] }),
      reviewed({ word: "user-friendly design", translation: "تصميم سهل الاستخدام", pos: "noun", ipa: "/ˌjuːzər ˈfrendli dɪˌzaɪn/", definition: "a design that is easy for people to understand and use", example: "The website became more popular after a user-friendly design was introduced.", exampleTranslation: "أصبح الموقع أكثر شعبية بعد اعتماد تصميم سهل الاستخدام.", category: "technology and daily life", tags: ["technology", "design"], synonyms: ["accessible design", "easy-to-use design"] }),
      reviewed({ word: "battery life", translation: "عمر البطارية", pos: "noun", ipa: "/ˈbætəri laɪf/", definition: "the length of time a battery can power a device before it needs charging", example: "Long battery life is important when people travel without a charger.", exampleTranslation: "يعد عمر البطارية الطويل مهمًا عندما يسافر الناس دون شاحن.", category: "technology and daily life", tags: ["technology", "devices"], synonyms: ["battery duration", "power duration"] }),
      reviewed({ word: "voice assistant", translation: "مساعد صوتي", pos: "noun", ipa: "/ˈvɔɪs əˌsɪstənt/", definition: "software that responds to spoken instructions", example: "She used a voice assistant to set a reminder for her appointment.", exampleTranslation: "استخدمت مساعدًا صوتيًا لضبط تذكير بموعدها.", category: "technology and daily life", tags: ["technology", "communication"], synonyms: ["voice-controlled assistant", "speech assistant"] }),
      reviewed({ word: "software compatibility", translation: "توافق البرمجيات", pos: "noun", ipa: "/ˈsɔːftwer kəmˌpætəˈbɪləti/", definition: "the ability of different software programs to work together", example: "Check software compatibility before moving the files to a new device.", exampleTranslation: "تحقق من توافق البرمجيات قبل نقل الملفات إلى جهاز جديد.", category: "technology and daily life", tags: ["technology", "software"], synonyms: ["program compatibility", "system compatibility"] }),
      reviewed({ word: "digital wellbeing", translation: "الرفاهية الرقمية", pos: "noun", ipa: "/ˈdɪdʒɪtəl ˌwelˈbiːɪŋ/", definition: "a healthy and balanced way of using digital devices and services", example: "The school introduced a lesson about digital wellbeing and healthy screen habits.", exampleTranslation: "قدمت المدرسة درسًا عن الرفاهية الرقمية والعادات الصحية أمام الشاشة.", category: "technology and daily life", tags: ["technology", "health"], synonyms: ["digital health", "healthy technology use"] }),
      reviewed({ word: "connectivity issue", translation: "مشكلة في الاتصال", pos: "noun", ipa: "/ˌkɑːnekˈtɪvəti ˈɪʃuː/", definition: "a problem that prevents a device or service from connecting to a network", example: "A connectivity issue interrupted the video call twice.", exampleTranslation: "تسببت مشكلة في الاتصال في انقطاع مكالمة الفيديو مرتين.", category: "technology and daily life", tags: ["technology", "communication"], synonyms: ["connection problem", "network issue"] }),
      reviewed({ word: "online accessibility", translation: "إمكانية الوصول عبر الإنترنت", pos: "noun", ipa: "/ˌɑːnlaɪn əkˌsesəˈbɪləti/", definition: "the extent to which online content can be used by people with different needs and abilities", example: "Captions and clear menus improve online accessibility.", exampleTranslation: "تحسن الترجمة النصية والقوائم الواضحة إمكانية الوصول عبر الإنترنت.", category: "technology and daily life", tags: ["technology", "inclusion"], synonyms: ["web accessibility", "digital accessibility"] }),
    ],
  },
  B2: {
    u5: [
      reviewed({ word: "experimental design", translation: "تصميم تجريبي", pos: "noun", ipa: "/ɪkˌsperɪˈmentəl dɪˌzaɪn/", definition: "the planned structure of a study used to test a question or hypothesis", example: "A careful experimental design helps researchers separate useful results from chance.", exampleTranslation: "يساعد التصميم التجريبي الدقيق الباحثين على فصل النتائج المفيدة عن الصدفة.", category: "research and innovation", tags: ["research", "science"], synonyms: ["study design", "trial design"] }),
      reviewed({ word: "breakthrough discovery", translation: "اكتشاف نوعي", pos: "noun", ipa: "/ˈbreɪkθruː dɪˌskʌvəri/", definition: "a discovery that produces a major advance in knowledge or technology", example: "The breakthrough discovery could change how the disease is treated.", exampleTranslation: "قد يغير الاكتشاف النوعي طريقة علاج المرض.", category: "research and innovation", tags: ["research", "innovation"], synonyms: ["major discovery", "scientific breakthrough"] }),
      reviewed({ word: "prototype testing", translation: "اختبار النموذج الأولي", pos: "noun", ipa: "/ˈproʊtətaɪp ˌtestɪŋ/", definition: "the process of examining an early version of a product or system", example: "Prototype testing revealed a safety problem before the device was released.", exampleTranslation: "كشف اختبار النموذج الأولي عن مشكلة تتعلق بالسلامة قبل طرح الجهاز.", category: "research and innovation", tags: ["technology", "development"], synonyms: ["prototype evaluation", "early-stage testing"] }),
      reviewed({ word: "machine learning model", translation: "نموذج تعلم آلي", pos: "noun", ipa: "/məˈʃiːn ˈlɜːrnɪŋ ˌmɑːdəl/", definition: "a system trained on data to identify patterns or make predictions", example: "The machine learning model improved after engineers supplied more varied data.", exampleTranslation: "تحسن نموذج التعلم الآلي بعد أن زوده المهندسون ببيانات أكثر تنوعًا.", category: "research and innovation", tags: ["technology", "artificial intelligence"], synonyms: ["learning algorithm", "predictive model"] }),
      reviewed({ word: "technological advance", translation: "تقدم تكنولوجي", pos: "noun", ipa: "/ˌteknəˈlɑːdʒɪkəl ədˈvæns/", definition: "an improvement that makes technology more capable or effective", example: "The technological advance reduced the energy needed to run the system.", exampleTranslation: "قلل التقدم التكنولوجي الطاقة اللازمة لتشغيل النظام.", category: "research and innovation", tags: ["technology", "progress"], synonyms: ["technical progress", "technological improvement"] }),
      reviewed({ word: "research reproducibility", translation: "قابلية تكرار البحث", pos: "noun", ipa: "/rɪˈsɜːrtʃ ˌriːprəˌduːsəˈbɪləti/", definition: "the extent to which a study can produce the same results when repeated", example: "The team published its code to improve research reproducibility.", exampleTranslation: "نشر الفريق شفرته لتحسين قابلية تكرار البحث.", category: "research and innovation", tags: ["research", "quality"], synonyms: ["study reproducibility", "reproducible research"] }),
      reviewed({ word: "innovation pipeline", translation: "مسار الابتكار", pos: "noun", ipa: "/ˌɪnəˈveɪʃən ˌpaɪplaɪn/", definition: "the sequence of stages through which a new idea is developed and introduced", example: "Several promising ideas are moving through the company’s innovation pipeline.", exampleTranslation: "تمر عدة أفكار واعدة عبر مسار الابتكار في الشركة.", category: "research and innovation", tags: ["innovation", "business"], synonyms: ["development pipeline", "innovation process"] }),
      reviewed({ word: "automated system", translation: "نظام مؤتمت", pos: "noun", ipa: "/ˈɔːtəmeɪtɪd ˌsɪstəm/", definition: "a system that performs tasks with little or no direct human control", example: "The automated system checks thousands of records every hour.", exampleTranslation: "يفحص النظام المؤتمت آلاف السجلات كل ساعة.", category: "research and innovation", tags: ["technology", "automation"], synonyms: ["automatic system", "computerized system"] }),
    ],
  },
  C1: {
    u5: [
      reviewed({ word: "line of reasoning", translation: "مسار الاستدلال", pos: "noun", ipa: "/ˌlaɪn əv ˈriːzənɪŋ/", definition: "the connected series of ideas used to support a conclusion", example: "The author’s line of reasoning becomes clearer in the final section.", exampleTranslation: "يصبح مسار استدلال الكاتب أوضح في القسم الأخير.", category: "academic writing", tags: ["writing", "argument"], synonyms: ["reasoning process", "logical progression"] }),
      reviewed({ word: "citation convention", translation: "قاعدة التوثيق", pos: "noun", ipa: "/saɪˈteɪʃən kənˌvenʃən/", definition: "an accepted rule for presenting sources in academic work", example: "Students must follow the citation convention required by the department.", exampleTranslation: "يجب على الطلاب اتباع قاعدة التوثيق التي يطلبها القسم.", category: "academic writing", tags: ["writing", "referencing"], synonyms: ["referencing convention", "citation rule"] }),
      reviewed({ word: "scope condition", translation: "شرط النطاق", pos: "noun", ipa: "/skoʊp kənˌdɪʃən/", definition: "a statement describing the limits within which a claim applies", example: "The researcher added a scope condition to avoid making an overly broad claim.", exampleTranslation: "أضاف الباحث شرط نطاق لتجنب تقديم ادعاء واسع أكثر من اللازم.", category: "academic writing", tags: ["writing", "analysis"], synonyms: ["scope limitation", "applicability condition"] }),
      reviewed({ word: "interpretive lens", translation: "منظور تفسيري", pos: "noun", ipa: "/ɪnˈtɜːrprətɪv lenz/", definition: "a particular perspective used to understand or analyse a text or issue", example: "The article applies a historical interpretive lens to the novel.", exampleTranslation: "تطبق المقالة منظورًا تفسيريًا تاريخيًا على الرواية.", category: "academic writing", tags: ["writing", "interpretation"], synonyms: ["analytical perspective", "interpretive perspective"] }),
      reviewed({ word: "conceptual nuance", translation: "دقة مفاهيمية", pos: "noun", ipa: "/kənˈseptʃuəl ˈnuːɑːns/", definition: "a subtle difference in the meaning or use of an idea", example: "The revised paragraph captures the conceptual nuance more accurately.", exampleTranslation: "تلتقط الفقرة المنقحة الدقة المفاهيمية بصورة أدق.", category: "academic writing", tags: ["writing", "concepts"], synonyms: ["conceptual subtlety", "fine distinction"] }),
      reviewed({ word: "qualified conclusion", translation: "خلاصة مقيّدة", pos: "noun", ipa: "/ˈkwɑːlɪfaɪd kənˌkluːʒən/", definition: "a conclusion that recognises limits, uncertainty, or conditions", example: "The evidence supports a qualified conclusion rather than a definite answer.", exampleTranslation: "يدعم الدليل خلاصة مقيّدة بدلًا من إجابة قطعية.", category: "academic writing", tags: ["writing", "argument"], synonyms: ["cautious conclusion", "limited conclusion"] }),
      reviewed({ word: "counterclaim analysis", translation: "تحليل الادعاء المضاد", pos: "noun", ipa: "/ˈkaʊntərklem əˌnæləsɪs/", definition: "the examination of an opposing claim and the evidence supporting it", example: "Strong counterclaim analysis makes the essay more balanced.", exampleTranslation: "يجعل تحليل الادعاء المضاد المقالة أكثر توازنًا.", category: "academic writing", tags: ["writing", "argument"], synonyms: ["opposing-claim analysis", "rebuttal analysis"] }),
      reviewed({ word: "thematic coherence", translation: "اتساق موضوعي", pos: "noun", ipa: "/θiːˈmætɪk koʊˈhɪrəns/", definition: "the quality of having ideas that remain connected to a central theme", example: "Clear signposting helps maintain thematic coherence throughout the chapter.", exampleTranslation: "يساعد التوجيه الواضح على الحفاظ على الاتساق الموضوعي في الفصل كله.", category: "academic writing", tags: ["writing", "structure"], synonyms: ["thematic unity", "coherence of themes"] }),
    ],
  },
};
