import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/** Reviewed vocabulary for the six existing B1/B2/C1 u3 and u4 units. */
export const ENGLISH_B1_B2_C1_U3_U4_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u3: [
      reviewed({ word: "employment agreement", translation: "اتفاقية توظيف", pos: "noun", ipa: "/ɪmˈplɔɪmənt əˌɡriːmənt/", definition: "a formal document describing the terms of a person’s job", example: "She read the employment agreement before signing it.", exampleTranslation: "قرأت اتفاقية التوظيف قبل توقيعها.", category: "work and career", tags: ["work", "contracts"], synonyms: ["work agreement", "employment contract"] }),
      reviewed({ word: "career development", translation: "تطور مهني", pos: "noun", ipa: "/kəˈrɪr dɪˌveləpmənt/", definition: "the process of gaining skills and experience for future work", example: "The company offers training for career development.", exampleTranslation: "تقدم الشركة تدريبًا للتطور المهني.", category: "work and career", tags: ["work", "learning"], synonyms: ["professional development", "career growth"] }),
      reviewed({ word: "salary progression", translation: "تدرج الراتب", pos: "noun", ipa: "/ˈsæləri prəˌɡreʃən/", definition: "the way a person’s pay increases over the course of a career", example: "The interview included questions about salary progression.", exampleTranslation: "تضمنت المقابلة أسئلة عن تدرج الراتب.", category: "work and career", tags: ["work", "finance"], synonyms: ["pay progression", "salary growth"] }),
      reviewed({ word: "workplace adviser", translation: "مستشار مكان العمل", pos: "noun", ipa: "/ˈwɜːrkpleɪs ədˌvaɪzər/", definition: "a person who gives guidance about work, employment, or workplace problems", example: "The workplace adviser explained the new policy clearly.", exampleTranslation: "شرح مستشار مكان العمل السياسة الجديدة بوضوح.", category: "work and career", tags: ["work", "support"], synonyms: ["employment adviser", "workplace consultant"] }),
      reviewed({ word: "vocational qualification", translation: "مؤهل مهني", pos: "noun", ipa: "/voʊˈkeɪʃənəl ˌkwɑːləfɪˈkeɪʃən/", definition: "a qualification that prepares someone for a particular job or trade", example: "A vocational qualification helped him enter the construction industry.", exampleTranslation: "ساعده مؤهل مهني على دخول قطاع البناء.", category: "work and career", tags: ["work", "education"], synonyms: ["professional certificate", "trade qualification"] }),
      reviewed({ word: "notice requirement", translation: "شرط الإشعار المسبق", pos: "noun", ipa: "/ˈnoʊtɪs rɪˌkwaɪərmənt/", definition: "the period or rule requiring advance warning before leaving a job", example: "The notice requirement is four weeks for new employees.", exampleTranslation: "شرط الإشعار المسبق أربعة أسابيع للموظفين الجدد.", category: "work and career", tags: ["work", "contracts"], synonyms: ["notice rule", "required notice period"] }),
      reviewed({ word: "workplace induction", translation: "تهيئة مكان العمل", pos: "noun", ipa: "/ˈwɜːrkpleɪs ɪnˌdʌkʃən/", definition: "an introduction that helps a new employee understand a workplace", example: "The workplace induction covered safety rules and team responsibilities.", exampleTranslation: "شملت تهيئة مكان العمل قواعد السلامة ومسؤوليات الفريق.", category: "work and career", tags: ["work", "training"], synonyms: ["employee orientation", "work induction"] }),
      reviewed({ word: "job stability", translation: "استقرار وظيفي", pos: "noun", ipa: "/ˈdʒɑːb stəˌbɪləti/", definition: "the likelihood that a person can keep a job for a long time", example: "Many applicants value job stability more than a higher starting salary.", exampleTranslation: "يقدر كثير من المتقدمين الاستقرار الوظيفي أكثر من راتب بداية أعلى.", category: "work and career", tags: ["work", "employment"], synonyms: ["employment security", "job security"] }),
    ],
    u4: [
      reviewed({ word: "cultural belonging", translation: "الانتماء الثقافي", pos: "noun", ipa: "/ˈkʌltʃərəl bɪˈlɔːŋɪŋ/", definition: "the feeling of being connected to a culture or community", example: "Music can give young people a strong sense of cultural belonging.", exampleTranslation: "يمكن للموسيقى أن تمنح الشباب شعورًا قويًا بالانتماء الثقافي.", category: "culture and lifestyles", tags: ["culture", "identity"], synonyms: ["cultural connection", "sense of belonging"] }),
      reviewed({ word: "community solidarity", translation: "تضامن مجتمعي", pos: "noun", ipa: "/kəˈmjuːnəti ˌsɑːləˈdærəti/", definition: "support and unity among people in a community", example: "The crisis brought out a remarkable sense of community solidarity.", exampleTranslation: "أبرزت الأزمة شعورًا ملحوظًا بالتضامن المجتمعي.", category: "culture and lifestyles", tags: ["culture", "community"], synonyms: ["community unity", "social solidarity"] }),
      reviewed({ word: "cross-cultural dialogue", translation: "حوار بين الثقافات", pos: "noun", ipa: "/ˌkrɔːs ˈkʌltʃərəl ˈdaɪəlɔːɡ/", definition: "communication intended to improve understanding between different cultures", example: "The festival creates opportunities for cross-cultural dialogue.", exampleTranslation: "يخلق المهرجان فرصًا للحوار بين الثقافات.", category: "culture and lifestyles", tags: ["culture", "communication"], synonyms: ["intercultural dialogue", "dialogue across cultures"] }),
      reviewed({ word: "neighbourhood centre", translation: "مركز الحي", pos: "noun", ipa: "/ˈneɪbərhʊd ˌsentər/", definition: "a local building where people meet and take part in activities", example: "The neighbourhood centre runs language and cooking classes.", exampleTranslation: "ينظم مركز الحي دروسًا في اللغة والطبخ.", category: "culture and lifestyles", tags: ["community", "daily life"], synonyms: ["community centre", "local activity centre"] }),
      reviewed({ word: "migration story", translation: "قصة هجرة", pos: "noun", ipa: "/maɪˈɡreɪʃən ˌstɔːri/", definition: "an account of a person or family moving from one place to another", example: "The exhibition presents each family’s migration story.", exampleTranslation: "يعرض المعرض قصة هجرة كل عائلة.", category: "culture and lifestyles", tags: ["culture", "society"], synonyms: ["migration experience", "immigration story"] }),
      reviewed({ word: "integration measure", translation: "إجراء للاندماج", pos: "noun", ipa: "/ˌɪntɪˈɡreɪʃən ˌmeʒər/", definition: "an action intended to help people participate fully in a society", example: "Free language classes are an important integration measure.", exampleTranslation: "تعد دروس اللغة المجانية إجراءً مهمًا للاندماج.", category: "culture and lifestyles", tags: ["society", "policy"], synonyms: ["integration initiative", "inclusion measure"] }),
      reviewed({ word: "inclusive society", translation: "مجتمع شامل", pos: "noun", ipa: "/ɪnˈkluːsɪv səˈsaɪəti/", definition: "a society in which people with different backgrounds can participate equally", example: "Schools can help build a more inclusive society.", exampleTranslation: "يمكن للمدارس أن تساعد في بناء مجتمع أكثر شمولًا.", category: "culture and lifestyles", tags: ["society", "community"], synonyms: ["inclusive community", "open society"] }),
      reviewed({ word: "population shift", translation: "تحول سكاني", pos: "noun", ipa: "/ˌpɑːpjəˈleɪʃən ʃɪft/", definition: "a significant change in where or how groups of people live", example: "The population shift has changed the character of the town.", exampleTranslation: "غيّر التحول السكاني طابع البلدة.", category: "culture and lifestyles", tags: ["society", "demography"], synonyms: ["demographic change", "population change"] }),
    ],
  },
  B2: {
    u3: [
      reviewed({ word: "research protocol", translation: "بروتوكول بحثي", pos: "noun", ipa: "/rɪˈsɜːrtʃ ˌproʊtəkɑːl/", definition: "a detailed plan describing how a research study will be conducted", example: "The research protocol explains how participants will be recruited.", exampleTranslation: "يشرح البروتوكول البحثي كيفية اختيار المشاركين.", category: "technology and ethics", tags: ["research", "ethics"], synonyms: ["study protocol", "research plan"] }),
      reviewed({ word: "evidence collection", translation: "جمع الأدلة", pos: "noun", ipa: "/ˈevɪdəns kəˌlekʃən/", definition: "the process of gathering information to support an investigation or decision", example: "Careful evidence collection is essential before the algorithm is evaluated.", exampleTranslation: "يعد جمع الأدلة بعناية ضروريًا قبل تقييم الخوارزمية.", category: "technology and ethics", tags: ["research", "evidence"], synonyms: ["data gathering", "evidence gathering"] }),
      reviewed({ word: "control factor", translation: "عامل ضابط", pos: "noun", ipa: "/kənˈtroʊl ˌfæktər/", definition: "a factor kept constant so that its effect does not distort a study", example: "The researchers treated temperature as a control factor.", exampleTranslation: "عامل الباحثون درجة الحرارة عاملًا ضابطًا.", category: "technology and ethics", tags: ["research", "science"], synonyms: ["controlled factor", "constant factor"] }),
      reviewed({ word: "causal link", translation: "رابط سببي", pos: "noun", ipa: "/ˈkɔːzəl lɪŋk/", definition: "a connection in which one event or factor produces another", example: "The report does not prove a causal link between screen time and sleep.", exampleTranslation: "لا يثبت التقرير وجود رابط سببي بين وقت الشاشة والنوم.", category: "technology and ethics", tags: ["research", "analysis"], synonyms: ["causal relationship", "cause-and-effect link"] }),
      reviewed({ word: "statistical evidence", translation: "دليل إحصائي", pos: "noun", ipa: "/stəˈtɪstɪkəl ˈevɪdəns/", definition: "numerical information used to support or assess a claim", example: "The policy should be based on statistical evidence rather than anecdote.", exampleTranslation: "ينبغي أن تستند السياسة إلى دليل إحصائي لا إلى حكاية فردية.", category: "technology and ethics", tags: ["research", "data"], synonyms: ["quantitative evidence", "statistical support"] }),
      reviewed({ word: "research consent", translation: "موافقة بحثية", pos: "noun", ipa: "/rɪˈsɜːrtʃ kənˈsent/", definition: "permission given by a participant after receiving information about a study", example: "Every participant gave research consent before the interview.", exampleTranslation: "قدم كل مشارك موافقة بحثية قبل المقابلة.", category: "technology and ethics", tags: ["research", "ethics"], synonyms: ["informed consent", "participant consent"] }),
      reviewed({ word: "replicable outcome", translation: "نتيجة قابلة للتكرار", pos: "noun", ipa: "/ˈreplɪkəbəl ˈaʊtkʌm/", definition: "a result that can be obtained again under similar conditions", example: "A replicable outcome gives researchers greater confidence in the finding.", exampleTranslation: "تمنح النتيجة القابلة للتكرار الباحثين ثقة أكبر في النتيجة.", category: "technology and ethics", tags: ["research", "quality"], synonyms: ["reproducible result", "repeatable finding"] }),
      reviewed({ word: "ethical safeguard", translation: "ضمانة أخلاقية", pos: "noun", ipa: "/ˈeθɪkəl ˈseɪfɡɑːrd/", definition: "a rule or measure that protects people from ethical harm", example: "The review board requested an additional ethical safeguard.", exampleTranslation: "طلبت لجنة المراجعة ضمانة أخلاقية إضافية.", category: "technology and ethics", tags: ["technology", "ethics"], synonyms: ["ethical protection", "safeguard for participants"] }),
    ],
    u4: [
      reviewed({ word: "city transport network", translation: "شبكة نقل المدينة", pos: "noun", ipa: "/ˈsɪti ˈtrænspɔːrt ˌnetwɜːrk/", definition: "the connected system of buses, trains, and routes serving a city", example: "The city transport network needs investment outside the centre.", exampleTranslation: "تحتاج شبكة نقل المدينة إلى استثمار خارج المركز.", category: "politics and society", tags: ["society", "transport"], synonyms: ["urban transport system", "municipal transport network"] }),
      reviewed({ word: "housing pressure", translation: "ضغط الإسكان", pos: "noun", ipa: "/ˈhaʊzɪŋ ˌpreʃər/", definition: "strong demand for homes that makes housing harder to obtain or afford", example: "Housing pressure has increased as more people move to the capital.", exampleTranslation: "ازداد ضغط الإسكان مع انتقال مزيد من الناس إلى العاصمة.", category: "politics and society", tags: ["society", "housing"], synonyms: ["housing demand", "pressure on housing"] }),
      reviewed({ word: "traffic control", translation: "تنظيم المرور", pos: "noun", ipa: "/ˈtræfɪk kənˌtroʊl/", definition: "the management of vehicles and movement on roads", example: "New traffic control measures reduced delays near the stadium.", exampleTranslation: "قللت إجراءات تنظيم المرور الجديدة التأخيرات قرب الملعب.", category: "politics and society", tags: ["society", "transport"], synonyms: ["traffic management", "road traffic control"] }),
      reviewed({ word: "pedestrian district", translation: "منطقة مخصصة للمشاة", pos: "noun", ipa: "/pəˈdestriən ˌdɪstrɪkt/", definition: "an area where people walk and motor vehicles are restricted", example: "The council plans to extend the pedestrian district.", exampleTranslation: "يخطط المجلس لتوسيع المنطقة المخصصة للمشاة.", category: "politics and society", tags: ["society", "cities"], synonyms: ["pedestrian zone", "car-free district"] }),
      reviewed({ word: "municipal council", translation: "مجلس بلدي", pos: "noun", ipa: "/mjuːˈnɪsɪpəl ˈkaʊnsəl/", definition: "an elected body responsible for governing a town or city", example: "The municipal council approved the new housing plan.", exampleTranslation: "وافق المجلس البلدي على خطة الإسكان الجديدة.", category: "politics and society", tags: ["politics", "cities"], synonyms: ["city council", "local council"] }),
      reviewed({ word: "social inclusion", translation: "إدماج اجتماعي", pos: "noun", ipa: "/ˈsoʊʃəl ɪnˌkluːʒən/", definition: "the process of ensuring that all groups can participate in society", example: "Public libraries can contribute to social inclusion.", exampleTranslation: "يمكن للمكتبات العامة أن تسهم في الإدماج الاجتماعي.", category: "politics and society", tags: ["society", "rights"], synonyms: ["social integration", "inclusion in society"] }),
      reviewed({ word: "population change", translation: "تغير سكاني", pos: "noun", ipa: "/ˌpɑːpjəˈleɪʃən tʃeɪndʒ/", definition: "a change in the size, age, or distribution of a population", example: "Population change is influencing the demand for schools and hospitals.", exampleTranslation: "يؤثر التغير السكاني في الطلب على المدارس والمستشفيات.", category: "politics and society", tags: ["society", "demography"], synonyms: ["demographic shift", "population trend"] }),
      reviewed({ word: "civic participation", translation: "مشاركة مدنية", pos: "noun", ipa: "/ˈsɪvɪk pɑːrˌtɪsɪˈpeɪʃən/", definition: "involvement in activities and decisions that affect a community", example: "Online forums have increased civic participation among younger residents.", exampleTranslation: "زادت المنتديات الإلكترونية المشاركة المدنية بين السكان الأصغر سنًا.", category: "politics and society", tags: ["politics", "community"], synonyms: ["civic engagement", "community participation"] }),
    ],
  },
  C1: {
    u3: [
      reviewed({ word: "public health plan", translation: "خطة صحة عامة", pos: "noun", ipa: "/ˈpʌblɪk helθ plæn/", definition: "an organised strategy for protecting and improving the health of a population", example: "The public health plan focuses on prevention rather than emergency treatment.", exampleTranslation: "تركز خطة الصحة العامة على الوقاية لا على العلاج الطارئ.", category: "science and society", tags: ["health", "policy"], synonyms: ["population health strategy", "public health strategy"] }),
      reviewed({ word: "treatment result", translation: "نتيجة العلاج", pos: "noun", ipa: "/ˈtriːtmənt rɪˌzʌlt/", definition: "the effect or outcome of a medical treatment", example: "The researchers compared the treatment result after six months.", exampleTranslation: "قارن الباحثون نتيجة العلاج بعد ستة أشهر.", category: "science and society", tags: ["health", "research"], synonyms: ["treatment outcome", "clinical result"] }),
      reviewed({ word: "healthcare provision", translation: "توفير الرعاية الصحية", pos: "noun", ipa: "/ˈhelθker prəˌvɪʒən/", definition: "the organisation and delivery of health services", example: "Rural healthcare provision remains a major policy challenge.", exampleTranslation: "يبقى توفير الرعاية الصحية في المناطق الريفية تحديًا سياسيًا كبيرًا.", category: "science and society", tags: ["health", "policy"], synonyms: ["health service provision", "delivery of healthcare"] }),
      reviewed({ word: "medical ethics review", translation: "مراجعة الأخلاقيات الطبية", pos: "noun", ipa: "/ˈmedɪkəl ˈeθɪks rɪˌvjuː/", definition: "an assessment of whether a medical study or practice meets ethical standards", example: "The project cannot begin until it passes medical ethics review.", exampleTranslation: "لا يمكن للمشروع أن يبدأ قبل اجتيازه مراجعة الأخلاقيات الطبية.", category: "science and society", tags: ["health", "ethics"], synonyms: ["clinical ethics review", "medical ethics assessment"] }),
      reviewed({ word: "preventive treatment", translation: "علاج وقائي", pos: "noun", ipa: "/prɪˈventɪv ˈtriːtmənt/", definition: "medical care intended to prevent illness or reduce future risk", example: "Preventive treatment can reduce the need for hospital care.", exampleTranslation: "يمكن للعلاج الوقائي أن يقلل الحاجة إلى رعاية المستشفى.", category: "science and society", tags: ["health", "prevention"], synonyms: ["preventive care", "prophylactic treatment"] }),
      reviewed({ word: "clinical evidence base", translation: "قاعدة الأدلة السريرية", pos: "noun", ipa: "/ˈklɪnɪkəl ˈevɪdəns beɪs/", definition: "the body of reliable research supporting a medical practice", example: "The clinical evidence base for the new therapy is still developing.", exampleTranslation: "لا تزال قاعدة الأدلة السريرية للعلاج الجديد قيد التطور.", category: "science and society", tags: ["health", "research"], synonyms: ["medical evidence base", "clinical research evidence"] }),
      reviewed({ word: "patient protection", translation: "حماية المرضى", pos: "noun", ipa: "/ˈpeɪʃənt prəˌtekʃən/", definition: "measures taken to protect patients from avoidable harm", example: "Patient protection must remain central to the design of the trial.", exampleTranslation: "يجب أن تبقى حماية المرضى محور تصميم التجربة.", category: "science and society", tags: ["health", "ethics"], synonyms: ["patient safety", "protection of patients"] }),
      reviewed({ word: "health inequality", translation: "تفاوت صحي", pos: "noun", ipa: "/helθ ˌɪnɪˈkwɑːləti/", definition: "an unfair difference in health between groups of people", example: "The study links health inequality to income and access to services.", exampleTranslation: "تربط الدراسة التفاوت الصحي بالدخل والوصول إلى الخدمات.", category: "science and society", tags: ["health", "society"], synonyms: ["health disparity", "inequality in health"] }),
    ],
    u4: [
      reviewed({ word: "treaty obligation", translation: "التزام تعاهدي", pos: "noun", ipa: "/ˈtriːti ˌɑːbləˈɡeɪʃən/", definition: "a duty created by an international agreement", example: "The government argued that the measure fulfilled a treaty obligation.", exampleTranslation: "جادلت الحكومة بأن الإجراء وفى بالتزام تعاهدي.", category: "global economy", tags: ["politics", "law"], synonyms: ["obligation under a treaty", "international treaty duty"] }),
      reviewed({ word: "diplomatic liaison", translation: "حلقة وصل دبلوماسية", pos: "noun", ipa: "/ˌdɪpləˈmætɪk liˈeɪzɑːn/", definition: "a person or channel that maintains communication between governments", example: "A diplomatic liaison helped prevent a misunderstanding between the ministries.", exampleTranslation: "ساعدت حلقة وصل دبلوماسية في منع سوء فهم بين الوزارتين.", category: "global economy", tags: ["politics", "diplomacy"], synonyms: ["diplomatic contact", "government liaison"] }),
      reviewed({ word: "strategic alliance", translation: "تحالف استراتيجي", pos: "noun", ipa: "/strəˈtiːdʒɪk əˈlaɪəns/", definition: "a formal partnership formed to pursue important long-term interests", example: "The two countries formed a strategic alliance on energy research.", exampleTranslation: "شكل البلدان تحالفًا استراتيجيًا في أبحاث الطاقة.", category: "global economy", tags: ["politics", "strategy"], synonyms: ["strategic partnership", "long-term alliance"] }),
      reviewed({ word: "regional stability", translation: "استقرار إقليمي", pos: "noun", ipa: "/ˈriːdʒənəl stəˈbɪləti/", definition: "a condition in which a region remains peaceful and politically secure", example: "Trade cooperation can contribute to regional stability.", exampleTranslation: "يمكن للتعاون التجاري أن يسهم في الاستقرار الإقليمي.", category: "global economy", tags: ["politics", "security"], synonyms: ["regional security", "stability in the region"] }),
      reviewed({ word: "external policy", translation: "سياسة خارجية", pos: "noun", ipa: "/ɪkˈstɜːrnəl ˈpɑːləsi/", definition: "a government’s approach to relations with other countries", example: "The crisis forced the cabinet to reconsider its external policy.", exampleTranslation: "أجبرت الأزمة مجلس الوزراء على إعادة النظر في سياسته الخارجية.", category: "global economy", tags: ["politics", "government"], synonyms: ["foreign policy", "international policy"] }),
      reviewed({ word: "national priority", translation: "أولوية وطنية", pos: "noun", ipa: "/ˈnæʃənəl praɪˈɔːrəti/", definition: "an issue considered especially important for a country", example: "Food security has become a national priority.", exampleTranslation: "أصبح الأمن الغذائي أولوية وطنية.", category: "global economy", tags: ["politics", "policy"], synonyms: ["countrywide priority", "state priority"] }),
      reviewed({ word: "political authority", translation: "سلطة سياسية", pos: "noun", ipa: "/pəˈlɪtɪkəl əˈθɔːrəti/", definition: "the recognised power to make and enforce political decisions", example: "The agreement challenged the political authority of the central government.", exampleTranslation: "تحدى الاتفاق السلطة السياسية للحكومة المركزية.", category: "global economy", tags: ["politics", "government"], synonyms: ["political power", "governing authority"] }),
      reviewed({ word: "peace settlement", translation: "تسوية سلمية", pos: "noun", ipa: "/ˈpiːs ˌsetəlmənt/", definition: "a formal agreement that ends or reduces an armed conflict", example: "The peace settlement created a framework for rebuilding the region.", exampleTranslation: "أنشأت التسوية السلمية إطارًا لإعادة بناء المنطقة.", category: "global economy", tags: ["politics", "conflict"], synonyms: ["peace agreement", "settlement of a conflict"] }),
    ],
  },
};
