import type { VocabularyItem } from "./learn-data";

/**
 * Additional English vocabulary keyed by existing CEFR level and unit id.
 * This bank enriches lessons in place; it never creates or renames units.
 */
export const ENGLISH_UNIT_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  A0: {
    u56: [
      { word: "ruler", translation: "regla", pos: "noun", ipa: "/ˈruːlər/", definition: "a straight tool used to measure or draw lines", example: "The ruler is next to my pencil.", exampleTranslation: "La regla está junto a mi lápiz.", synonyms: ["measuring stick"], antonyms: [], collocations: ["school ruler", "use a ruler"], wordFamily: ["rule", "ruler"], tags: ["school", "objects"], category: "object" },
      { word: "notebook", translation: "cuaderno", pos: "noun", ipa: "/ˈnoʊtbʊk/", definition: "a book of blank pages for writing notes", example: "I write new words in my notebook.", exampleTranslation: "Escribo palabras nuevas en mi cuaderno.", synonyms: ["exercise book", "notepad"], antonyms: [], collocations: ["school notebook", "open a notebook"], wordFamily: ["note", "notebook"], tags: ["school", "writing"], category: "object" },
      { word: "eraser", translation: "goma de borrar", pos: "noun", ipa: "/ɪˈreɪsər/", definition: "a small object used to remove pencil marks", example: "Use an eraser for this mark.", exampleTranslation: "Usa una goma de borrar para esta marca.", synonyms: ["rubber"], antonyms: [], collocations: ["pencil eraser", "use an eraser"], wordFamily: ["erase", "eraser", "erasable"], tags: ["school", "objects"], category: "object" },
      { word: "question", translation: "pregunta", pos: "noun", ipa: "/ˈkwestʃən/", definition: "words used to ask for information", example: "The student asks a question.", exampleTranslation: "El estudiante hace una pregunta.", synonyms: ["query", "inquiry"], antonyms: ["answer"], collocations: ["ask a question", "simple question"], wordFamily: ["question", "questioner", "questioning"], tags: ["school", "communication"], category: "communication" },
    ],
  },
  A1: {
    u56: [
      { word: "reschedule", translation: "reprogramar", pos: "verb", ipa: "/ˌriːˈskedʒuːl/", definition: "to arrange an event for a different time", example: "Can we reschedule the appointment for Friday?", exampleTranslation: "¿Podemos reprogramar la cita para el viernes?", synonyms: ["rearrange", "rebook"], antonyms: [], collocations: ["reschedule a meeting", "reschedule an appointment"], wordFamily: ["schedule", "reschedule", "rescheduling"], tags: ["time", "communication"], category: "action" },
      { word: "reception", translation: "recepción", pos: "noun", ipa: "/rɪˈsepʃən/", definition: "the place where visitors are welcomed and helped", example: "Please ask at reception.", exampleTranslation: "Pregunta en recepción, por favor.", synonyms: ["front desk", "welcome desk"], antonyms: [], collocations: ["clinic reception", "reception desk"], wordFamily: ["receive", "reception", "receptionist"], tags: ["places", "communication"], category: "place" },
      { word: "afternoon", translation: "tarde", pos: "noun", ipa: "/ˌæftərˈnuːn/", definition: "the part of the day between midday and evening", example: "The clinic is open in the afternoon.", exampleTranslation: "La clínica está abierta por la tarde.", synonyms: ["after lunch"], antonyms: ["morning"], collocations: ["this afternoon", "afternoon appointment"], wordFamily: ["afternoon"], tags: ["time", "routine"], category: "time" },
      { word: "reminder", translation: "recordatorio", pos: "noun", ipa: "/rɪˈmaɪndər/", definition: "a message that helps you remember something", example: "The clinic sent a reminder by text.", exampleTranslation: "La clínica envió un recordatorio por mensaje.", synonyms: ["prompt", "notice"], antonyms: [], collocations: ["send a reminder", "appointment reminder"], wordFamily: ["remind", "reminder"], tags: ["time", "communication"], category: "message" },
    ],
  },
  A2: {
    u56: [
      { word: "browser", translation: "navegador", pos: "noun", ipa: "/ˈbraʊzər/", definition: "a program used to view websites", example: "Open the link in your browser.", exampleTranslation: "Abre el enlace en tu navegador.", synonyms: ["web browser"], antonyms: [], collocations: ["web browser", "browser window"], wordFamily: ["browse", "browser", "browsing"], tags: ["technology", "internet"], category: "software" },
      { word: "screen", translation: "pantalla", pos: "noun", ipa: "/skriːn/", definition: "the flat surface on a device that shows images and text", example: "The message appears on my screen.", exampleTranslation: "El mensaje aparece en mi pantalla.", synonyms: ["display", "monitor"], antonyms: [], collocations: ["phone screen", "screen size"], wordFamily: ["screen", "screening"], tags: ["technology", "devices"], category: "object" },
      { word: "secure", translation: "seguro", pos: "adjective", ipa: "/sɪˈkjʊər/", definition: "protected from danger, loss, or unwanted access", example: "Use a secure connection for online banking.", exampleTranslation: "Usa una conexión segura para la banca en línea.", synonyms: ["safe", "protected"], antonyms: ["unsafe", "vulnerable"], collocations: ["secure connection", "secure account"], wordFamily: ["secure", "security", "securely"], tags: ["technology", "safety"], category: "quality" },
      { word: "subscribe", translation: "suscribirse", pos: "verb", ipa: "/səbˈskraɪb/", definition: "to agree to receive a service or regular updates", example: "You can subscribe to the weekly newsletter.", exampleTranslation: "Puedes suscribirte al boletín semanal.", synonyms: ["sign up", "enrol"], antonyms: ["unsubscribe"], collocations: ["subscribe to a newsletter", "subscribe online"], wordFamily: ["subscribe", "subscriber", "subscription"], tags: ["technology", "communication"], category: "action" },
    ],
  },
  B1: {
    u56: [
      { word: "milestone", translation: "hito", pos: "noun", ipa: "/ˈmaɪlstoʊn/", definition: "an important stage or event in a process", example: "Finishing the prototype was an important milestone.", exampleTranslation: "Terminar el prototipo fue un hito importante.", synonyms: ["landmark", "turning point"], antonyms: [], collocations: ["major milestone", "reach a milestone"], wordFamily: ["milestone"], tags: ["work", "planning"], category: "progress" },
      { word: "negotiate", translation: "negociar", pos: "verb", ipa: "/nɪˈɡoʊʃieɪt/", definition: "to discuss in order to reach an agreement", example: "The teams negotiated a realistic deadline.", exampleTranslation: "Los equipos negociaron una fecha límite realista.", synonyms: ["bargain", "discuss"], antonyms: ["refuse"], collocations: ["negotiate a contract", "negotiate terms"], wordFamily: ["negotiate", "negotiation", "negotiator"], tags: ["work", "communication"], category: "action" },
      { word: "facilitate", translation: "facilitar", pos: "verb", ipa: "/fəˈsɪlɪteɪt/", definition: "to make an action or process easier", example: "The shared document facilitated collaboration.", exampleTranslation: "El documento compartido facilitó la colaboración.", synonyms: ["enable", "assist"], antonyms: ["hinder", "obstruct"], collocations: ["facilitate discussion", "facilitate learning"], wordFamily: ["facilitate", "facilitation", "facilitator"], tags: ["work", "communication"], category: "action" },
      { word: "efficient", translation: "eficiente", pos: "adjective", ipa: "/ɪˈfɪʃənt/", definition: "working well without wasting time or resources", example: "The new process is more efficient.", exampleTranslation: "El nuevo proceso es más eficiente.", synonyms: ["effective", "productive"], antonyms: ["inefficient", "wasteful"], collocations: ["efficient system", "work efficiently"], wordFamily: ["efficiency", "efficient", "efficiently"], tags: ["work", "quality"], category: "quality" },
    ],
  },
  B2: {
    u56: [
      { word: "generalisability", translation: "generalización", pos: "noun", ipa: "/ˌdʒenərəlaɪzəˈbɪləti/", definition: "the extent to which a study's results apply beyond its sample", example: "The diverse sample improves the generalisability of the findings.", exampleTranslation: "La muestra diversa mejora la generalización de los resultados.", synonyms: ["applicability", "transferability"], antonyms: [], collocations: ["limited generalisability", "assess generalisability"], wordFamily: ["generalise", "generalisation", "generalisable"], tags: ["science", "research"], category: "quality" },
      { word: "robustness", translation: "solidez", pos: "noun", ipa: "/ˈroʊbʌstnəs/", definition: "the ability to remain reliable under different conditions", example: "The researchers tested the robustness of the result.", exampleTranslation: "Los investigadores comprobaron la solidez del resultado.", synonyms: ["reliability", "strength"], antonyms: ["fragility"], collocations: ["test robustness", "robustness check"], wordFamily: ["robust", "robustness"], tags: ["science", "thinking"], category: "quality" },
      { word: "dataset", translation: "conjunto de datos", pos: "noun", ipa: "/ˈdeɪtəset/", definition: "a structured collection of information used for analysis", example: "The dataset contains results from three surveys.", exampleTranslation: "El conjunto de datos contiene resultados de tres encuestas.", synonyms: ["data set", "data collection"], antonyms: [], collocations: ["large dataset", "analyse a dataset"], wordFamily: ["data", "dataset"], tags: ["science", "data"], category: "research" },
      { word: "finding", translation: "hallazgo", pos: "noun", ipa: "/ˈfaɪndɪŋ/", definition: "a result or conclusion discovered through research", example: "The main finding was unexpected.", exampleTranslation: "El hallazgo principal fue inesperado.", synonyms: ["result", "discovery"], antonyms: [], collocations: ["key finding", "research finding"], wordFamily: ["find", "finding"], tags: ["science", "research"], category: "result" },
    ],
  },
  C1: {
    u56: [
      { word: "verification", translation: "verificación", pos: "noun", ipa: "/ˌverɪfɪˈkeɪʃən/", definition: "the process of checking that information is accurate", example: "The claim requires independent verification.", exampleTranslation: "La afirmación requiere una verificación independiente.", synonyms: ["confirmation", "validation"], antonyms: [], collocations: ["fact verification", "independent verification"], wordFamily: ["verify", "verification"], tags: ["media", "research"], category: "process" },
      { word: "allegation", translation: "acusación", pos: "noun", ipa: "/ˌæləˈɡeɪʃən/", definition: "a claim that someone has done something wrong, not yet proved", example: "The newspaper reported the allegation cautiously.", exampleTranslation: "El periódico informó de la acusación con cautela.", synonyms: ["claim", "accusation"], antonyms: [], collocations: ["serious allegation", "deny an allegation"], wordFamily: ["allege", "allegation"], tags: ["media", "law"], category: "claim" },
      { word: "impartial", translation: "imparcial", pos: "adjective", ipa: "/ɪmˈpɑːrʃəl/", definition: "not supporting one side more than another", example: "A credible report should be accurate and impartial.", exampleTranslation: "Un informe creíble debe ser preciso e imparcial.", synonyms: ["neutral", "unbiased"], antonyms: ["partial", "biased"], collocations: ["impartial analysis", "remain impartial"], wordFamily: ["part", "partial", "impartiality"], tags: ["media", "ethics"], category: "quality" },
      { word: "transparency", translation: "transparencia", pos: "noun", ipa: "/trænsˈperənsi/", definition: "the practice of making processes and information open to inspection", example: "Transparency helps readers evaluate a source.", exampleTranslation: "La transparencia ayuda a los lectores a evaluar una fuente.", synonyms: ["openness", "clarity"], antonyms: ["secrecy", "opacity"], collocations: ["editorial transparency", "greater transparency"], wordFamily: ["transparent", "transparency"], tags: ["media", "ethics"], category: "principle" },
    ],
  },
  C2: {
    u56: [
      { word: "deixis", translation: "deixis", pos: "noun", ipa: "/ˈdeɪksɪs/", definition: "the use of words whose meaning depends on the situation or speaker", example: "Words such as 'here' and 'now' are examples of deixis.", exampleTranslation: "Palabras como «aquí» y «ahora» son ejemplos de deixis.", synonyms: ["indexical reference", "contextual reference"], antonyms: [], collocations: ["spatial deixis", "temporal deixis"], wordFamily: ["deictic", "deixis"], tags: ["linguistics", "pragmatics"], category: "meaning" },
      { word: "presuppose", translation: "presuponer", pos: "verb", ipa: "/ˌpriːsəˈpoʊz/", definition: "to assume that something is true before it is proved", example: "The argument presupposes that the data is complete.", exampleTranslation: "El argumento presupone que los datos están completos.", synonyms: ["assume", "take for granted"], antonyms: ["question"], collocations: ["presuppose a condition", "presuppose knowledge"], wordFamily: ["presuppose", "presupposition"], tags: ["linguistics", "thinking"], category: "reasoning" },
      { word: "entailment", translation: "implicación lógica", pos: "noun", ipa: "/ɪnˈteɪlmənt/", definition: "a meaning or conclusion that must follow from a statement", example: "The entailment depends on the meaning of the verb.", exampleTranslation: "La implicación lógica depende del significado del verbo.", synonyms: ["implication", "consequence"], antonyms: [], collocations: ["logical entailment", "semantic entailment"], wordFamily: ["entail", "entailment"], tags: ["linguistics", "logic"], category: "meaning" },
      { word: "polysemy", translation: "polisemia", pos: "noun", ipa: "/pəˈlɪsəmi/", definition: "the fact that one word has several related meanings", example: "The polysemy of the word makes the sentence interesting.", exampleTranslation: "La polisemia de la palabra hace interesante la oración.", synonyms: ["multiple meaning", "semantic variation"], antonyms: [], collocations: ["lexical polysemy", "polysemy in language"], wordFamily: ["polysemous", "polysemy"], tags: ["linguistics", "semantics"], category: "meaning" },
    ],
  },
};
