// Additional English curriculum units u32-u33 for every CEFR level.
// Deterministic local curriculum data; APIs may enrich it but never generate it.
type Word = { word: string; translation: string; pos: string; example: string; exampleTranslation: string };
type Unit = { id: string; title: string; description: string; words: Word[]; phrases: { phrase: string; translation: string }[]; dialogue: { speaker: string; text: string; translation: string }[]; reading: { title: string; text: string; translation: string } };
const w = (word: string, translation: string, pos: string, example: string, exampleTranslation: string): Word => ({ word, translation, pos, example, exampleTranslation });
const u = (id: string, title: string, description: string, words: Word[]): Unit => ({
  id, title, description, words,
  phrases: words.slice(0, 4).map((item) => ({ phrase: item.example, translation: item.exampleTranslation })),
  dialogue: [
    { speaker: "A", text: words[0]!.example, translation: words[0]!.exampleTranslation },
    { speaker: "B", text: words[1]!.example, translation: words[1]!.exampleTranslation },
    { speaker: "A", text: words[2]!.example, translation: words[2]!.exampleTranslation },
    { speaker: "B", text: words[3]!.example, translation: words[3]!.exampleTranslation },
  ],
  reading: { title, text: words.slice(0, 4).map((item) => item.example).join(" "), translation: words.slice(0, 4).map((item) => item.exampleTranslation).join(" ") },
});

export const ADDITIONAL_EN_PART5_UNITS: Record<string, Unit[]> = {
  A0: [
    u("u32", "Daily Time", "Say the time and describe simple parts of the day.", [
      w("morning", "mañana", "noun", "I study in the morning.", "Estudio por la mañana."),
      w("afternoon", "tarde", "noun", "We meet in the afternoon.", "Nos reunimos por la tarde."),
      w("evening", "tarde-noche", "noun", "The evening is quiet.", "La tarde-noche es tranquila."),
      w("night", "noche", "noun", "I sleep at night.", "Duermo por la noche."),
      w("today", "hoy", "adverb", "Today is Monday.", "Hoy es lunes."),
      w("tomorrow", "mañana", "adverb", "See you tomorrow.", "Nos vemos mañana."),
      w("early", "temprano", "adverb", "I wake up early.", "Me despierto temprano."),
      w("late", "tarde", "adverb", "The bus is late.", "El autobús llega tarde."),
    ]),
    u("u33", "Simple Feelings", "Express a few basic feelings and needs.", [
      w("happy", "feliz", "adjective", "I am happy today.", "Estoy feliz hoy."),
      w("sad", "triste", "adjective", "She feels sad.", "Ella se siente triste."),
      w("tired", "cansado", "adjective", "I am tired after work.", "Estoy cansado después del trabajo."),
      w("hungry", "hambriento", "adjective", "The children are hungry.", "Los niños tienen hambre."),
      w("thirsty", "sediento", "adjective", "I am thirsty.", "Tengo sed."),
      w("cold", "frío", "adjective", "My hands are cold.", "Tengo las manos frías."),
      w("hot", "caliente", "adjective", "The tea is hot.", "El té está caliente."),
      w("afraid", "asustado", "adjective", "The child is afraid.", "El niño está asustado."),
    ]),
  ],
  A1: [
    u("u32", "Home Routines", "Describe chores and simple routines at home.", [
      w("clean", "limpiar", "verb", "I clean the kitchen on Saturday.", "Limpio la cocina el sábado."),
      w("wash", "lavar", "verb", "We wash the dishes after dinner.", "Lavamos los platos después de cenar."),
      w("cook", "cocinar", "verb", "My brother cooks lunch.", "Mi hermano cocina el almuerzo."),
      w("tidy", "ordenar", "verb", "Please tidy your room.", "Por favor, ordena tu habitación."),
      w("floor", "suelo", "noun", "The floor is clean.", "El suelo está limpio."),
      w("window", "ventana", "noun", "Open the window, please.", "Abre la ventana, por favor."),
      w("towel", "toalla", "noun", "The towel is in the bathroom.", "La toalla está en el baño."),
      w("key", "llave", "noun", "I left my key at home.", "Dejé mi llave en casa."),
    ]),
    u("u33", "Free Time", "Talk about hobbies and what you do after work or school.", [
      w("hobby", "afición", "noun", "Reading is my favourite hobby.", "Leer es mi afición favorita."),
      w("music", "música", "noun", "I listen to music every day.", "Escucho música todos los días."),
      w("film", "película", "noun", "We watched a funny film.", "Vimos una película divertida."),
      w("dance", "bailar", "verb", "They dance at the weekend.", "Bailan el fin de semana."),
      w("draw", "dibujar", "verb", "She likes to draw animals.", "A ella le gusta dibujar animales."),
      w("play", "jugar", "verb", "The children play outside.", "Los niños juegan afuera."),
      w("relax", "relajarse", "verb", "I relax with a book.", "Me relajo con un libro."),
      w("weekend", "fin de semana", "noun", "Our weekend starts on Friday.", "Nuestro fin de semana empieza el viernes."),
    ]),
  ],
  A2: [
    u("u32", "Learning Strategies", "Discuss ways to learn and remember new information.", [
      w("method", "método", "noun", "This method helps me remember words.", "Este método me ayuda a recordar palabras."),
      w("practice", "práctica", "noun", "Regular practice builds confidence.", "La práctica regular aumenta la confianza."),
      w("mistake", "error", "noun", "Every mistake can teach us something.", "Cada error puede enseñarnos algo."),
      w("progress", "progreso", "noun", "I can see my progress this month.", "Puedo ver mi progreso este mes."),
      w("review", "repasar", "verb", "I review the lesson before bed.", "Repaso la lección antes de dormir."),
      w("memorise", "memorizar", "verb", "She memorises five words a day.", "Ella memoriza cinco palabras al día."),
      w("imagine", "imaginar", "verb", "Imagine the word in a sentence.", "Imagina la palabra en una frase."),
      w("concentrate", "concentrarse", "verb", "It is easier to concentrate in a quiet room.", "Es más fácil concentrarse en una habitación tranquila."),
    ]),
    u("u33", "Travel Experiences", "Describe trips, sights, and experiences abroad.", [
      w("sight", "lugar de interés", "noun", "The old bridge is a famous sight.", "El puente antiguo es un lugar de interés famoso."),
      w("journey", "viaje", "noun", "The journey took four hours.", "El viaje duró cuatro horas."),
      w("guide", "guía", "noun", "Our guide explained the history.", "Nuestro guía explicó la historia."),
      w("crowd", "multitud", "noun", "A large crowd waited outside.", "Una gran multitud esperaba afuera."),
      w("explore", "explorar", "verb", "We explored the old town on foot.", "Exploramos el casco antiguo a pie."),
      w("recommend", "recomendar", "verb", "I recommend this small museum.", "Recomiendo este pequeño museo."),
      w("believe", "creer", "verb", "I could not believe the view.", "No podía creer la vista."),
      w("return", "volver", "verb", "We returned home on Sunday.", "Volvimos a casa el domingo."),
    ]),
  ],
  B1: [
    u("u32", "Communication at Work", "Handle workplace messages, meetings, and deadlines.", [
      w("deadline", "fecha límite", "noun", "The deadline is next Friday.", "La fecha límite es el próximo viernes."),
      w("schedule", "programar", "verb", "We scheduled a meeting for noon.", "Programamos una reunión para el mediodía."),
      w("agenda", "orden del día", "noun", "The agenda has three points.", "El orden del día tiene tres puntos."),
      w("update", "actualización", "noun", "Please send me an update.", "Por favor, envíame una actualización."),
      w("clarify", "aclarar", "verb", "Could you clarify the last point?", "¿Podrías aclarar el último punto?"),
      w("confirm", "confirmar", "verb", "Please confirm your availability.", "Por favor, confirma tu disponibilidad."),
      w("postpone", "posponer", "verb", "We had to postpone the meeting.", "Tuvimos que posponer la reunión."),
      w("attend", "asistir", "verb", "All team members attended the call.", "Todos los miembros del equipo asistieron a la llamada."),
    ]),
    u("u33", "Health and Lifestyle", "Discuss habits that support physical and mental health.", [
      w("well-being", "bienestar", "noun", "Sleep is important for well-being.", "Dormir es importante para el bienestar."),
      w("stress", "estrés", "noun", "Too much stress affects concentration.", "Demasiado estrés afecta a la concentración."),
      w("routine", "rutina", "noun", "A stable routine can help.", "Una rutina estable puede ayudar."),
      w("balance", "equilibrio", "noun", "Work-life balance matters.", "El equilibrio entre trabajo y vida importa."),
      w("prevent", "prevenir", "verb", "Exercise can prevent some problems.", "El ejercicio puede prevenir algunos problemas."),
      w("recover", "recuperarse", "verb", "She recovered quickly after the illness.", "Ella se recuperó rápidamente después de la enfermedad."),
      w("reduce", "reducir", "verb", "Walking can reduce stress.", "Caminar puede reducir el estrés."),
      w("maintain", "mantener", "verb", "It is hard to maintain a new habit.", "Es difícil mantener un hábito nuevo."),
    ]),
  ],
  B2: [
    u("u32", "Urban Development", "Debate how cities can grow fairly and sustainably.", [
      w("infrastructure", "infraestructura", "noun", "The city needs better infrastructure.", "La ciudad necesita mejor infraestructura."),
      w("housing", "vivienda", "noun", "Affordable housing is difficult to find.", "Es difícil encontrar vivienda asequible."),
      w("density", "densidad", "noun", "High density changes neighbourhoods.", "La alta densidad cambia los barrios."),
      w("commute", "desplazamiento diario", "noun", "My commute takes forty minutes.", "Mi desplazamiento diario dura cuarenta minutos."),
      w("expand", "expandir", "verb", "The city plans to expand the tram network.", "La ciudad planea expandir la red de tranvías."),
      w("regenerate", "regenerar", "verb", "The project will regenerate an old district.", "El proyecto regenerará un distrito antiguo."),
      w("displace", "desplazar", "verb", "New buildings may displace local residents.", "Los nuevos edificios pueden desplazar a los residentes locales."),
      w("prioritise", "dar prioridad", "verb", "Planners should prioritise pedestrians.", "Los urbanistas deberían dar prioridad a los peatones."),
    ]),
    u("u33", "Digital Citizenship", "Evaluate responsibility, privacy, and behaviour online.", [
      w("identity", "identidad", "noun", "Protect your digital identity.", "Protege tu identidad digital."),
      w("privacy", "privacidad", "noun", "Online privacy requires attention.", "La privacidad en línea requiere atención."),
      w("consent", "consentimiento", "noun", "The app must ask for consent.", "La aplicación debe pedir consentimiento."),
      w("misinformation", "desinformación", "noun", "Misinformation spreads quickly.", "La desinformación se propaga rápidamente."),
      w("verify", "verificar", "verb", "Always verify a surprising claim.", "Verifica siempre una afirmación sorprendente."),
      w("report", "denunciar", "verb", "Users can report harmful content.", "Los usuarios pueden denunciar contenido dañino."),
      w("encrypt", "cifrar", "verb", "The service encrypts personal data.", "El servicio cifra los datos personales."),
      w("moderate", "moderar", "verb", "Platforms must moderate abusive comments.", "Las plataformas deben moderar los comentarios abusivos."),
    ]),
  ],
  C1: [
    u("u32", "Education and Access", "Analyse how education systems create opportunity or inequality.", [
      w("attainment", "logro educativo", "noun", "Educational attainment varies widely.", "El logro educativo varía mucho."),
      w("curriculum", "plan de estudios", "noun", "The curriculum includes practical skills.", "El plan de estudios incluye habilidades prácticas."),
      w("equity", "equidad", "noun", "Equity is different from treating everyone identically.", "La equidad es distinta de tratar a todos de forma idéntica."),
      w("barrier", "barrera", "noun", "Cost remains a barrier to study.", "El coste sigue siendo una barrera para estudiar."),
      w("facilitate", "facilitar", "verb", "Libraries facilitate independent learning.", "Las bibliotecas facilitan el aprendizaje independiente."),
      w("broaden", "ampliar", "verb", "Travel can broaden a student's perspective.", "Viajar puede ampliar la perspectiva de un estudiante."),
      w("assess", "evaluar", "verb", "Teachers assess progress in several ways.", "Los profesores evalúan el progreso de varias formas."),
      w("discriminate", "discriminar", "verb", "A fair system must not discriminate.", "Un sistema justo no debe discriminar."),
    ]),
    u("u33", "Climate Adaptation", "Discuss how communities respond to environmental change.", [
      w("adaptation", "adaptación", "noun", "Climate adaptation needs long-term planning.", "La adaptación climática necesita planificación a largo plazo."),
      w("drought", "sequía", "noun", "The region suffered a severe drought.", "La región sufrió una sequía grave."),
      w("flooding", "inundación", "noun", "Flooding damaged several roads.", "Las inundaciones dañaron varias carreteras."),
      w("emission", "emisión", "noun", "The policy aims to cut emissions.", "La política pretende reducir las emisiones."),
      w("anticipate", "anticipar", "verb", "Cities must anticipate extreme weather.", "Las ciudades deben anticipar el clima extremo."),
      w("mitigate", "mitigar", "verb", "Trees can mitigate urban heat.", "Los árboles pueden mitigar el calor urbano."),
      w("restore", "restaurar", "verb", "Wetlands help restore natural protection.", "Los humedales ayudan a restaurar la protección natural."),
      w("implement", "implementar", "verb", "Local authorities implemented a warning system.", "Las autoridades locales implementaron un sistema de alerta."),
    ]),
  ],
  C2: [
    u("u32", "Interpretation and Power", "Examine how interpretation shapes institutions and public life.", [
      w("discourse", "discurso", "noun", "Political discourse can frame a problem narrowly.", "El discurso político puede encuadrar un problema de forma limitada."),
      w("ideology", "ideología", "noun", "Ideology influences what counts as evidence.", "La ideología influye en lo que cuenta como evidencia."),
      w("narrative", "narrativa", "noun", "The narrative dominated public debate.", "La narrativa dominó el debate público."),
      w("legitimacy", "legitimidad", "noun", "Institutions need public legitimacy.", "Las instituciones necesitan legitimidad pública."),
      w("expose", "poner de manifiesto", "verb", "The report exposes a hidden assumption.", "El informe pone de manifiesto un supuesto oculto."),
      w("contest", "cuestionar", "verb", "Citizens contested the official narrative.", "Los ciudadanos cuestionaron la narrativa oficial."),
      w("legitimise", "legitimar", "verb", "Statistics can legitimise a policy.", "Las estadísticas pueden legitimar una política."),
      w("reframe", "replantear", "verb", "The essay reframes the debate.", "El ensayo replantea el debate."),
    ]),
    u("u33", "Ethics of Technology", "Evaluate difficult choices created by advanced technology.", [
      w("autonomy", "autonomía", "noun", "Automation can challenge human autonomy.", "La automatización puede desafiar la autonomía humana."),
      w("bias", "sesgo", "noun", "The model may reproduce social bias.", "El modelo puede reproducir el sesgo social."),
      w("transparency", "transparencia", "noun", "Transparency is essential for accountability.", "La transparencia es esencial para la rendición de cuentas."),
      w("surveillance", "vigilancia", "noun", "Mass surveillance raises serious concerns.", "La vigilancia masiva plantea preocupaciones serias."),
      w("regulate", "regular", "verb", "Governments struggle to regulate new systems.", "Los gobiernos tienen dificultades para regular sistemas nuevos."),
      w("safeguard", "proteger", "verb", "Rules should safeguard vulnerable people.", "Las normas deben proteger a las personas vulnerables."),
      w("disclose", "revelar", "verb", "Companies should disclose how data is used.", "Las empresas deberían revelar cómo se utilizan los datos."),
      w("weigh", "sopesar", "verb", "Decision-makers must weigh competing values.", "Los responsables deben sopesar valores contrapuestos."),
    ]),
  ],
};
