import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/** Reviewed vocabulary for the six existing B1/B2/C1 u14 and u15 units. */
export const ENGLISH_B1_B2_C1_U14_U15_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u14: [
      reviewed({ word: "habitat recovery", translation: "تعافي الموطن الطبيعي", pos: "noun", ipa: "/ˈhæbɪtæt rɪˈkʌvəri/", definition: "the process by which a natural home for plants and animals becomes healthy again", example: "Habitat recovery depends on protecting the wetlands from further damage.", exampleTranslation: "يعتمد تعافي الموطن الطبيعي على حماية الأراضي الرطبة من مزيد من الضرر.", category: "environment and nature", tags: ["environment", "conservation"], synonyms: ["ecosystem recovery", "habitat restoration"] }),
      reviewed({ word: "water conservation", translation: "الحفاظ على المياه", pos: "noun", ipa: "/ˈwɔːtər ˌkɑːnsərˈveɪʃən/", definition: "the careful use and protection of water resources", example: "Water conservation is especially important during long periods without rain.", exampleTranslation: "يعد الحفاظ على المياه مهمًا خصوصًا خلال الفترات الطويلة دون أمطار.", category: "environment and nature", tags: ["environment", "resources"], synonyms: ["water protection", "water saving"] }),
      reviewed({ word: "low-carbon lifestyle", translation: "نمط حياة منخفض الكربون", pos: "noun", ipa: "/ˌloʊ ˈkɑːrbən ˈlaɪfstaɪl/", definition: "a way of living that produces relatively few greenhouse-gas emissions", example: "Cycling and eating less meat can support a low-carbon lifestyle.", exampleTranslation: "يمكن لركوب الدراجة وتقليل تناول اللحوم أن يدعما نمط حياة منخفض الكربون.", category: "environment and nature", tags: ["environment", "daily life"], synonyms: ["low-emission lifestyle", "sustainable lifestyle"] }),
      reviewed({ word: "climate awareness", translation: "الوعي المناخي", pos: "noun", ipa: "/ˈklaɪmət əˌwernəs/", definition: "understanding of climate change and its effects on people and nature", example: "The school campaign aims to increase climate awareness among teenagers.", exampleTranslation: "تهدف الحملة المدرسية إلى زيادة الوعي المناخي بين المراهقين.", category: "environment and nature", tags: ["environment", "education"], synonyms: ["climate understanding", "environmental awareness"] }),
      reviewed({ word: "plastic reduction", translation: "الحد من البلاستيك", pos: "noun", ipa: "/ˈplæstɪk rɪˌdʌkʃən/", definition: "the process of using and throwing away less plastic", example: "Plastic reduction begins with reusable bags and bottles.", exampleTranslation: "يبدأ الحد من البلاستيك باستخدام الأكياس والزجاجات القابلة لإعادة الاستخدام.", category: "environment and nature", tags: ["environment", "waste"], synonyms: ["plastic reduction effort", "cutting plastic use"] }),
      reviewed({ word: "wildlife corridor", translation: "ممر للحياة البرية", pos: "noun", ipa: "/ˈwaɪldlaɪf ˌkɔːrɪdɔːr/", definition: "a strip of natural land that allows animals to move between habitats", example: "The wildlife corridor helps animals cross the road safely.", exampleTranslation: "يساعد ممر الحياة البرية الحيوانات على عبور الطريق بأمان.", category: "environment and nature", tags: ["environment", "animals"], synonyms: ["animal corridor", "ecological corridor"] }),
      reviewed({ word: "organic farming", translation: "الزراعة العضوية", pos: "noun", ipa: "/ɔːrˈɡænɪk ˈfɑːrmɪŋ/", definition: "farming that avoids most artificial chemicals and focuses on natural processes", example: "Organic farming can improve soil quality when it is managed carefully.", exampleTranslation: "يمكن للزراعة العضوية تحسين جودة التربة عندما تدار بعناية.", category: "environment and nature", tags: ["environment", "food"], synonyms: ["organic agriculture", "natural farming"] }),
      reviewed({ word: "environmental footprint", translation: "البصمة البيئية", pos: "noun", ipa: "/ɪnˌvaɪrənˈmentəl ˈfʊtprɪnt/", definition: "the effect that a person, product, or activity has on the natural world", example: "Buying local food may reduce the environmental footprint of a meal.", exampleTranslation: "قد يقلل شراء الطعام المحلي البصمة البيئية للوجبة.", category: "environment and nature", tags: ["environment", "consumption"], synonyms: ["ecological footprint", "environmental impact"] }),
    ],
    u15: [
      reviewed({ word: "emotional support", translation: "دعم عاطفي", pos: "noun", ipa: "/ɪˈmoʊʃənəl səˈpɔːrt/", definition: "care and encouragement given to someone who is experiencing difficulty", example: "Close friends can provide emotional support during a stressful period.", exampleTranslation: "يمكن للأصدقاء المقربين تقديم دعم عاطفي خلال فترة مرهقة.", category: "friendship and trust", tags: ["relationships", "emotions"], synonyms: ["emotional care", "personal support"] }),
      reviewed({ word: "healthy disagreement", translation: "اختلاف صحي", pos: "noun", ipa: "/ˈhelθi ˌdɪsəˈɡriːmənt/", definition: "a respectful difference of opinion that does not damage a relationship", example: "A healthy disagreement can help both people understand the issue better.", exampleTranslation: "يمكن للاختلاف الصحي أن يساعد الطرفين على فهم القضية بصورة أفضل.", category: "friendship and trust", tags: ["relationships", "communication"], synonyms: ["constructive disagreement", "respectful difference"] }),
      reviewed({ word: "trust building", translation: "بناء الثقة", pos: "noun", ipa: "/trʌst ˈbɪldɪŋ/", definition: "the gradual process of developing confidence in another person", example: "Honest conversations are important for trust building.", exampleTranslation: "تعد المحادثات الصادقة مهمة لبناء الثقة.", category: "friendship and trust", tags: ["relationships", "trust"], synonyms: ["building confidence", "trust development"] }),
      reviewed({ word: "relationship conflict", translation: "نزاع في العلاقة", pos: "noun", ipa: "/rɪˈleɪʃənʃɪp ˈkɑːnflɪkt/", definition: "a serious disagreement between people who have a personal relationship", example: "The friends sought advice to resolve their relationship conflict.", exampleTranslation: "طلب الأصدقاء المشورة لحل النزاع في علاقتهم.", category: "friendship and trust", tags: ["relationships", "conflict"], synonyms: ["interpersonal conflict", "relationship dispute"] }),
      reviewed({ word: "active empathy", translation: "تعاطف فعّال", pos: "noun", ipa: "/ˈæktɪv ˈempəθi/", definition: "the deliberate effort to understand and respond to another person’s feelings", example: "Active empathy means listening carefully instead of immediately giving advice.", exampleTranslation: "يعني التعاطف الفعال الإصغاء بعناية بدلًا من تقديم النصيحة فورًا.", category: "friendship and trust", tags: ["relationships", "empathy"], synonyms: ["engaged empathy", "empathetic listening"] }),
      reviewed({ word: "social connection", translation: "رابطة اجتماعية", pos: "noun", ipa: "/ˈsoʊʃəl kəˌnekʃən/", definition: "a meaningful relationship or sense of belonging with other people", example: "Shared activities can strengthen social connection in a new community.", exampleTranslation: "يمكن للأنشطة المشتركة تقوية الرابطة الاجتماعية في مجتمع جديد.", category: "friendship and trust", tags: ["relationships", "community"], synonyms: ["social bond", "human connection"] }),
      reviewed({ word: "friendship bond", translation: "رابطة الصداقة", pos: "noun", ipa: "/ˈfrendʃɪp bɑːnd/", definition: "the emotional connection that holds friends together", example: "Years of shared experiences created a strong friendship bond.", exampleTranslation: "خلقت سنوات التجارب المشتركة رابطة صداقة قوية.", category: "friendship and trust", tags: ["relationships", "friendship"], synonyms: ["bond of friendship", "friendship connection"] }),
      reviewed({ word: "personal boundary", translation: "حد شخصي", pos: "noun", ipa: "/ˈpɜːrsənəl ˈbaʊndəri/", definition: "a limit that protects a person’s comfort, privacy, or time", example: "Respecting a personal boundary is an important part of trust.", exampleTranslation: "يعد احترام الحد الشخصي جزءًا مهمًا من الثقة.", category: "friendship and trust", tags: ["relationships", "respect"], synonyms: ["personal limit", "relationship boundary"] }),
    ],
  },
  B2: {
    u14: [
      reviewed({ word: "digital identity", translation: "هوية رقمية", pos: "noun", ipa: "/ˈdɪdʒɪtəl aɪˈdentəti/", definition: "the collection of information that represents a person or organisation online", example: "Users should protect their digital identity with strong passwords.", exampleTranslation: "ينبغي للمستخدمين حماية هويتهم الرقمية بكلمات مرور قوية.", category: "technology and digitalization", tags: ["technology", "identity"], synonyms: ["online identity", "digital profile"] }),
      reviewed({ word: "online harassment", translation: "مضايقة عبر الإنترنت", pos: "noun", ipa: "/ˌɑːnlaɪn həˈræsmənt/", definition: "repeated threatening or abusive behaviour directed at someone online", example: "The platform introduced a reporting tool to address online harassment.", exampleTranslation: "قدمَت المنصة أداة للإبلاغ لمعالجة المضايقة عبر الإنترنت.", category: "technology and digitalization", tags: ["technology", "safety"], synonyms: ["cyber harassment", "online abuse"] }),
      reviewed({ word: "content moderation", translation: "الإشراف على المحتوى", pos: "noun", ipa: "/ˈkɑːntent ˌmɑːdəˈreɪʃən/", definition: "the process of reviewing and managing material posted on a digital service", example: "Content moderation is difficult when millions of posts appear every day.", exampleTranslation: "يصبح الإشراف على المحتوى صعبًا عندما تظهر ملايين المنشورات يوميًا.", category: "technology and digitalization", tags: ["technology", "media"], synonyms: ["content review", "platform moderation"] }),
      reviewed({ word: "platform economy", translation: "اقتصاد المنصات", pos: "noun", ipa: "/ˈplætfɔːrm ɪˈkɑːnəmi/", definition: "an economy organised around digital platforms that connect users, workers, or businesses", example: "The platform economy has changed how many people provide services.", exampleTranslation: "غير اقتصاد المنصات طريقة تقديم كثير من الناس للخدمات.", category: "technology and digitalization", tags: ["technology", "economy"], synonyms: ["digital platform economy", "platform-based economy"] }),
      reviewed({ word: "creator economy", translation: "اقتصاد المبدعين", pos: "noun", ipa: "/kriˈeɪtər ɪˈkɑːnəmi/", definition: "economic activity generated by people who create digital content or products", example: "The creator economy allows independent artists to reach global audiences.", exampleTranslation: "يتيح اقتصاد المبدعين للفنانين المستقلين الوصول إلى جماهير عالمية.", category: "technology and digitalization", tags: ["technology", "business"], synonyms: ["content-creator economy", "digital creator market"] }),
      reviewed({ word: "algorithmic transparency", translation: "شفافية الخوارزميات", pos: "noun", ipa: "/ˌælɡəˈrɪðmɪk trænˈspærənsi/", definition: "the extent to which people can understand how an algorithm makes decisions", example: "Algorithmic transparency can help users challenge unfair automated decisions.", exampleTranslation: "يمكن لشفافية الخوارزميات أن تساعد المستخدمين على الطعن في القرارات الآلية غير العادلة.", category: "technology and digitalization", tags: ["technology", "ethics"], synonyms: ["algorithm transparency", "transparent algorithms"] }),
      reviewed({ word: "data literacy", translation: "الثقافة البيانية", pos: "noun", ipa: "/ˈdeɪtə ˌlɪtərəsi/", definition: "the ability to read, understand, question, and use data effectively", example: "Data literacy is essential when people compare statistics online.", exampleTranslation: "تعد الثقافة البيانية ضرورية عندما يقارن الناس الإحصاءات عبر الإنترنت.", category: "technology and digitalization", tags: ["technology", "education"], synonyms: ["data competence", "statistical literacy"] }),
      reviewed({ word: "privacy-preserving design", translation: "تصميم يحافظ على الخصوصية", pos: "noun", ipa: "/ˈpraɪvəsi prɪˌzɜːrvɪŋ dɪˌzaɪn/", definition: "a design approach that protects personal information from unnecessary collection or exposure", example: "Privacy-preserving design should be considered from the first stage of development.", exampleTranslation: "ينبغي مراعاة التصميم الذي يحافظ على الخصوصية منذ المرحلة الأولى للتطوير.", category: "technology and digitalization", tags: ["technology", "privacy"], synonyms: ["privacy-aware design", "privacy-by-design approach"] }),
    ],
    u15: [
      reviewed({ word: "museum exhibition", translation: "معرض متحفي", pos: "noun", ipa: "/mjuˈziːəm ˌeksəˈbɪʃən/", definition: "a public display of objects or works in a museum", example: "The museum exhibition explores the history of regional painting.", exampleTranslation: "يستكشف المعرض المتحفي تاريخ الرسم الإقليمي.", category: "art and cultural heritage", tags: ["art", "museums"], synonyms: ["museum display", "gallery exhibition"] }),
      reviewed({ word: "artistic medium", translation: "وسيط فني", pos: "noun", ipa: "/ɑːrˈtɪstɪk ˈmiːdiəm/", definition: "the material or form used by an artist to create a work", example: "Photography became her preferred artistic medium.", exampleTranslation: "أصبح التصوير الفوتوغرافي وسيطها الفني المفضل.", category: "art and cultural heritage", tags: ["art", "creation"], synonyms: ["art medium", "creative medium"] }),
      reviewed({ word: "cultural curator", translation: "قيّم ثقافي", pos: "noun", ipa: "/ˈkʌltʃərəl kjʊˈreɪtər/", definition: "a specialist who selects, organises, and explains cultural or artistic material", example: "The cultural curator designed a programme linking the objects to local history.", exampleTranslation: "صمم القيّم الثقافي برنامجًا يربط القطع بالتاريخ المحلي.", category: "art and cultural heritage", tags: ["art", "culture"], synonyms: ["heritage curator", "cultural collections specialist"] }),
      reviewed({ word: "visual narrative", translation: "سرد بصري", pos: "noun", ipa: "/ˈvɪʒuəl ˈnærətɪv/", definition: "a story or argument communicated mainly through images", example: "The photographs create a visual narrative about migration.", exampleTranslation: "تصنع الصور سردًا بصريًا عن الهجرة.", category: "art and cultural heritage", tags: ["art", "storytelling"], synonyms: ["visual storytelling", "image-based narrative"] }),
      reviewed({ word: "performance art", translation: "فن الأداء", pos: "noun", ipa: "/pərˈfɔːrməns ɑːrt/", definition: "art that uses live action, movement, or events as its main medium", example: "The festival includes performance art in public spaces.", exampleTranslation: "يتضمن المهرجان فن الأداء في الأماكن العامة.", category: "art and cultural heritage", tags: ["art", "performance"], synonyms: ["live art", "performative art"] }),
      reviewed({ word: "creative practice", translation: "ممارسة إبداعية", pos: "noun", ipa: "/kriˈeɪtɪv ˈpræktɪs/", definition: "the methods and regular activities through which an artist develops work", example: "Keeping a sketchbook is part of the designer’s creative practice.", exampleTranslation: "يعد الاحتفاظ بدفتر رسم جزءًا من الممارسة الإبداعية للمصمم.", category: "art and cultural heritage", tags: ["art", "creation"], synonyms: ["creative process", "artistic practice"] }),
      reviewed({ word: "heritage conservation", translation: "صون التراث", pos: "noun", ipa: "/ˈherɪtɪdʒ ˌkɑːnsərˈveɪʃən/", definition: "the protection and careful maintenance of important cultural objects or places", example: "Heritage conservation keeps historic buildings available for future generations.", exampleTranslation: "يحافظ صون التراث على إتاحة المباني التاريخية للأجيال القادمة.", category: "art and cultural heritage", tags: ["art", "heritage"], synonyms: ["heritage preservation", "cultural conservation"] }),
      reviewed({ word: "artistic interpretation", translation: "تفسير فني", pos: "noun", ipa: "/ɑːrˈtɪstɪk ɪnˌtɜːrprəˈteɪʃən/", definition: "an artist’s particular understanding and presentation of a subject", example: "The new artistic interpretation gives the old myth a modern meaning.", exampleTranslation: "يمنح التفسير الفني الجديد الأسطورة القديمة معنى معاصرًا.", category: "art and cultural heritage", tags: ["art", "interpretation"], synonyms: ["artistic reading", "creative interpretation"] }),
    ],
  },
  C1: {
    u14: [
      reviewed({ word: "executive accountability", translation: "مساءلة السلطة التنفيذية", pos: "noun", ipa: "/ɪɡˈzekjətɪv əˌkaʊntəˈbɪləti/", definition: "the duty of executive leaders to explain and take responsibility for their decisions", example: "Parliament strengthened executive accountability after the investigation.", exampleTranslation: "عزز البرلمان مساءلة السلطة التنفيذية بعد التحقيق.", category: "government and opposition", tags: ["government", "accountability"], synonyms: ["government accountability", "executive responsibility"] }),
      reviewed({ word: "policy oversight", translation: "رقابة على السياسات", pos: "noun", ipa: "/ˈpɑːləsi ˈoʊvərsaɪt/", definition: "the process of monitoring how public policies are designed and carried out", example: "Independent committees provide policy oversight between elections.", exampleTranslation: "تقدم اللجان المستقلة رقابة على السياسات بين الانتخابات.", category: "government and opposition", tags: ["government", "policy"], synonyms: ["policy supervision", "public-policy review"] }),
      reviewed({ word: "administrative reform", translation: "إصلاح إداري", pos: "noun", ipa: "/ədˈmɪnəˌstreɪtɪv rɪˈfɔːrm/", definition: "a planned change intended to make public administration more effective or fair", example: "The minister proposed administrative reform to reduce delays.", exampleTranslation: "اقترح الوزير إصلاحًا إداريًا لتقليل التأخير.", category: "government and opposition", tags: ["government", "reform"], synonyms: ["bureaucratic reform", "administrative change"] }),
      reviewed({ word: "institutional capacity", translation: "القدرة المؤسسية", pos: "noun", ipa: "/ˌɪnstəˈtuːʃənəl kəˈpæsəti/", definition: "the ability of an institution to perform its responsibilities effectively", example: "The policy will fail without sufficient institutional capacity.", exampleTranslation: "ستفشل السياسة دون قدرة مؤسسية كافية.", category: "government and opposition", tags: ["government", "institutions"], synonyms: ["institutional capability", "organisational capacity"] }),
      reviewed({ word: "public mandate", translation: "تفويض شعبي", pos: "noun", ipa: "/ˈpʌblɪk ˈmændeɪt/", definition: "the authority that voters give a government to act on their behalf", example: "The new administration claimed a strong public mandate for reform.", exampleTranslation: "ادعت الإدارة الجديدة امتلاك تفويض شعبي قوي للإصلاح.", category: "government and opposition", tags: ["government", "democracy"], synonyms: ["electoral mandate", "popular mandate"] }),
      reviewed({ word: "regulatory capture", translation: "استحواذ المصالح على الجهة التنظيمية", pos: "noun", ipa: "/ˈreɡjələtɔːri ˈkæptʃər/", definition: "a situation in which a regulator serves the interests of the industry it should control", example: "The report warned that weak rules could lead to regulatory capture.", exampleTranslation: "حذر التقرير من أن القواعد الضعيفة قد تؤدي إلى استحواذ المصالح على الجهة التنظيمية.", category: "government and opposition", tags: ["government", "regulation"], synonyms: ["regulatory takeover", "industry capture"] }),
      reviewed({ word: "democratic legitimacy", translation: "شرعية ديمقراطية", pos: "noun", ipa: "/ˌdeməˈkrætɪk lɪˈdʒɪtəməsi/", definition: "the acceptance of political authority because it is based on democratic principles", example: "Transparent elections are central to democratic legitimacy.", exampleTranslation: "تعد الانتخابات الشفافة محورية للشرعية الديمقراطية.", category: "government and opposition", tags: ["government", "democracy"], synonyms: ["democratic authority", "popular legitimacy"] }),
      reviewed({ word: "parliamentary oversight", translation: "رقابة برلمانية", pos: "noun", ipa: "/ˌpɑːrləˈmentəri ˈoʊvərsaɪt/", definition: "the examination of government actions by a parliament", example: "Parliamentary oversight exposed weaknesses in the procurement process.", exampleTranslation: "كشفت الرقابة البرلمانية نقاط ضعف في عملية الشراء الحكومي.", category: "government and opposition", tags: ["government", "parliament"], synonyms: ["legislative supervision", "parliamentary scrutiny"] }),
    ],
    u15: [
      reviewed({ word: "migration pathway", translation: "مسار الهجرة", pos: "noun", ipa: "/maɪˈɡreɪʃən ˈpæθweɪ/", definition: "a legal or practical route through which people move to another country", example: "The proposal creates a migration pathway for skilled workers.", exampleTranslation: "ينشئ المقترح مسار هجرة للعمال المهرة.", category: "immigration and refugees", tags: ["migration", "policy"], synonyms: ["migration route", "legal migration channel"] }),
      reviewed({ word: "asylum procedure", translation: "إجراءات اللجوء", pos: "noun", ipa: "/əˈsaɪləm prəˌsiːdʒər/", definition: "the official process for deciding whether a person should receive protection in another country", example: "A fair asylum procedure should give applicants time to present evidence.", exampleTranslation: "ينبغي لإجراءات اللجوء العادلة أن تمنح المتقدمين وقتًا لتقديم الأدلة.", category: "immigration and refugees", tags: ["migration", "law"], synonyms: ["asylum process", "refugee-status procedure"] }),
      reviewed({ word: "integration challenge", translation: "تحدي الاندماج", pos: "noun", ipa: "/ˌɪntɪˈɡreɪʃən ˈtʃælɪndʒ/", definition: "a difficulty that affects the full participation of newcomers in a society", example: "Language access is a major integration challenge for new arrivals.", exampleTranslation: "يعد الوصول إلى اللغة تحديًا كبيرًا للاندماج بالنسبة إلى الوافدين الجدد.", category: "immigration and refugees", tags: ["migration", "society"], synonyms: ["integration difficulty", "inclusion challenge"] }),
      reviewed({ word: "diaspora community", translation: "جالية مهاجرة", pos: "noun", ipa: "/daɪˈæspərə kəˌmjuːnəti/", definition: "a community of people living outside their ancestral homeland", example: "The diaspora community organised language classes for newly arrived families.", exampleTranslation: "نظمت الجالية المهاجرة دروسًا لغوية للعائلات الوافدة حديثًا.", category: "immigration and refugees", tags: ["migration", "community"], synonyms: ["diaspora group", "migrant community"] }),
      reviewed({ word: "border governance", translation: "حوكمة الحدود", pos: "noun", ipa: "/ˈbɔːrdər ˈɡʌvərnəns/", definition: "the systems and policies used to manage movement across national borders", example: "Effective border governance must balance security with human rights.", exampleTranslation: "يجب أن توازن حوكمة الحدود الفعالة بين الأمن وحقوق الإنسان.", category: "immigration and refugees", tags: ["migration", "governance"], synonyms: ["border management", "frontier governance"] }),
      reviewed({ word: "refugee protection", translation: "حماية اللاجئين", pos: "noun", ipa: "/ˌrefjuˈdʒiː prəˈtekʃən/", definition: "legal and practical measures that keep refugees safe and uphold their rights", example: "Refugee protection requires cooperation between governments and aid agencies.", exampleTranslation: "تتطلب حماية اللاجئين تعاونًا بين الحكومات ووكالات الإغاثة.", category: "immigration and refugees", tags: ["migration", "human rights"], synonyms: ["refugee safeguarding", "protection for refugees"] }),
      reviewed({ word: "social cohesion policy", translation: "سياسة التماسك الاجتماعي", pos: "noun", ipa: "/ˈsoʊʃəl koʊˈhiːʒən ˌpɑːləsi/", definition: "a public policy designed to strengthen trust and cooperation among different groups", example: "The city adopted a social cohesion policy after consultation with local communities.", exampleTranslation: "اعتمدت المدينة سياسة للتماسك الاجتماعي بعد التشاور مع المجتمعات المحلية.", category: "immigration and refugees", tags: ["migration", "society"], synonyms: ["social integration policy", "community cohesion policy"] }),
      reviewed({ word: "citizenship status", translation: "وضع المواطنة", pos: "noun", ipa: "/ˈsɪtɪzənʃɪp ˌsteɪtəs/", definition: "a person’s official legal position as a citizen or non-citizen of a country", example: "Citizenship status can affect access to political rights and public services.", exampleTranslation: "يمكن لوضع المواطنة أن يؤثر في الوصول إلى الحقوق السياسية والخدمات العامة.", category: "immigration and refugees", tags: ["migration", "law"], synonyms: ["nationality status", "legal citizenship position"] }),
    ],
  },
};
