// Additional English curriculum units u38-u39 for every CEFR level.
// Deterministic local curriculum data; APIs may enrich it but never generate it.
type Word = { word: string; translation: string; pos: string; example: string; exampleTranslation: string };
type Unit = { id: string; title: string; description: string; words: Word[]; phrases: { phrase: string; translation: string }[]; dialogue: { speaker: string; text: string; translation: string }[]; reading: { title: string; text: string; translation: string } };
const w = (word: string, translation: string, pos: string, example: string, exampleTranslation: string): Word => ({ word, translation, pos, example, exampleTranslation });
const u = (id: string, title: string, description: string, words: Word[]): Unit => ({
  id, title, description, words,
  phrases: words.slice(0, 4).map((item) => ({ phrase: item.example, translation: item.exampleTranslation })),
  dialogue: [0, 1, 2, 3].map((index) => ({ speaker: index % 2 === 0 ? "A" : "B", text: words[index]!.example, translation: words[index]!.exampleTranslation })),
  reading: { title, text: words.slice(0, 4).map((item) => item.example).join(" "), translation: words.slice(0, 4).map((item) => item.exampleTranslation).join(" ") },
});

export const ADDITIONAL_EN_PART8_UNITS: Record<string, Unit[]> = {
  A0: [
    u("u38", "Food and the Kitchen", "Name common foods and kitchen objects.", [
      w("bread", "pan", "noun", "The bread is on the table.", "El pan está sobre la mesa."), w("milk", "leche", "noun", "I drink milk.", "Bebo leche."), w("apple", "manzana", "noun", "The apple is red.", "La manzana es roja."), w("soup", "sopa", "noun", "The soup is hot.", "La sopa está caliente."), w("plate", "plato", "noun", "The plate is clean.", "El plato está limpio."), w("spoon", "cuchara", "noun", "The spoon is in the cup.", "La cuchara está en la taza."), w("eat", "comer", "verb", "I want to eat.", "Quiero comer."), w("drink", "beber", "verb", "I drink water.", "Bebo agua."),
    ]),
    u("u39", "Home and Daily Life", "Describe a home and simple daily actions.", [
      w("home", "casa", "noun", "The home is warm.", "La casa es cálida."), w("room", "habitación", "noun", "The room is small.", "La habitación es pequeña."), w("door", "puerta", "noun", "The door is open.", "La puerta está abierta."), w("window", "ventana", "noun", "The window is closed.", "La ventana está cerrada."), w("chair", "silla", "noun", "The chair is in the kitchen.", "La silla está en la cocina."), w("bed", "cama", "noun", "The bed is comfortable.", "La cama es cómoda."), w("clean", "limpiar", "verb", "I clean the room.", "Limpio la habitación."), w("sleep", "dormir", "verb", "The child sleeps.", "El niño duerme."),
    ]),
  ],
  A1: [
    u("u38", "Free Time and Hobbies", "Talk about free time and plan hobbies.", [
      w("hobby", "afición", "noun", "Reading is my hobby.", "Leer es mi afición."), w("book", "libro", "noun", "I borrow a book from the library.", "Pido prestado un libro de la biblioteca."), w("film", "película", "noun", "We watched a funny film.", "Vimos una película divertida."), w("music", "música", "noun", "I listen to music in the evening.", "Escucho música por la tarde."), w("game", "juego", "noun", "The game starts soon.", "El juego empieza pronto."), w("park", "parque", "noun", "We walk in the park.", "Caminamos por el parque."), w("practise", "practicar", "verb", "I practise every day.", "Practico todos los días."), w("relax", "relajarse", "verb", "I want to relax at the weekend.", "Quiero relajarme el fin de semana."),
    ]),
    u("u39", "Travel and Hotels", "Book accommodation and ask for basic travel information.", [
      w("trip", "viaje", "noun", "The trip starts tomorrow.", "El viaje empieza mañana."), w("hotel", "hotel", "noun", "The hotel is near the station.", "El hotel está cerca de la estación."), w("room", "habitación", "noun", "The room is on the second floor.", "La habitación está en el segundo piso."), w("reservation", "reserva", "noun", "I have a reservation.", "Tengo una reserva."), w("bag", "bolsa", "noun", "The bag is heavy.", "La bolsa es pesada."), w("map", "mapa", "noun", "I look at the map.", "Miro el mapa."), w("arrive", "llegar", "verb", "We arrive in the evening.", "Llegamos por la tarde."), w("leave", "salir", "verb", "The train leaves at ten.", "El tren sale a las diez."),
    ]),
  ],
  A2: [
    u("u38", "Work and the Working Day", "Describe work tasks and organise a working day.", [
      w("workplace", "lugar de trabajo", "noun", "The workplace is in the centre.", "El lugar de trabajo está en el centro."), w("meeting", "reunión", "noun", "The meeting begins at nine.", "La reunión empieza a las nueve."), w("schedule", "horario", "noun", "The schedule changed today.", "El horario cambió hoy."), w("colleague", "colega", "noun", "A colleague helps me.", "Un colega me ayuda."), w("project", "proyecto", "noun", "The project will be completed in summer.", "El proyecto terminará en verano."), w("salary", "salario", "noun", "The salary is paid at the end of the month.", "El salario se paga a final de mes."), w("plan", "planificar", "verb", "We plan a new project.", "Planificamos un proyecto nuevo."), w("succeed", "tener éxito", "verb", "The team succeeded in the task.", "El equipo tuvo éxito en la tarea."),
    ]),
    u("u39", "Environment and Consumption", "Discuss nature, recycling, and responsible choices.", [
      w("environment", "medio ambiente", "noun", "The environment needs protection.", "El medio ambiente necesita protección."), w("nature", "naturaleza", "noun", "Nature is close to the city.", "La naturaleza está cerca de la ciudad."), w("waste", "residuos", "noun", "Waste is sorted at home.", "Los residuos se separan en casa."), w("recycling", "reciclaje", "noun", "Recycling saves material.", "El reciclaje ahorra materiales."), w("energy", "energía", "noun", "The sun provides energy.", "El sol proporciona energía."), w("consumption", "consumo", "noun", "Consumption is too high.", "El consumo es demasiado alto."), w("save", "ahorrar", "verb", "We save water.", "Ahorramos agua."), w("protect", "proteger", "verb", "We must protect the forest.", "Debemos proteger el bosque."),
    ]),
  ],
  B1: [
    u("u38", "Communication and Cooperation", "Describe teamwork, feedback, and clear communication.", [
      w("communication", "comunicación", "noun", "Clear communication prevents mistakes.", "La comunicación clara evita errores."), w("cooperation", "cooperación", "noun", "The cooperation went well.", "La cooperación funcionó bien."), w("opinion", "opinión", "noun", "She shared her opinion.", "Ella compartió su opinión."), w("proposal", "propuesta", "noun", "The proposal received support.", "La propuesta recibió apoyo."), w("misunderstanding", "malentendido", "noun", "The misunderstanding was resolved quickly.", "El malentendido se resolvió rápidamente."), w("trust", "confianza", "noun", "Trust develops gradually.", "La confianza se desarrolla gradualmente."), w("explain", "explicar", "verb", "Can you explain the matter?", "¿Puedes explicar el asunto?"), w("agree", "acordar", "verb", "We agreed on a new time.", "Acordamos una nueva hora."),
    ]),
    u("u39", "Media and News", "Understand news and assess the reliability of information.", [
      w("news item", "noticia", "noun", "The news item spread quickly.", "La noticia se difundió rápidamente."), w("journalist", "periodista", "noun", "The journalist interviewed an expert.", "El periodista entrevistó a un experto."), w("source", "fuente", "noun", "The source must be checked.", "La fuente debe comprobarse."), w("interview", "entrevista", "noun", "The interview will be published tomorrow.", "La entrevista se publicará mañana."), w("claim", "afirmación", "noun", "The claim requires evidence.", "La afirmación requiere pruebas."), w("headline", "titular", "noun", "The headline sparked discussion.", "El titular provocó debate."), w("publish", "publicar", "verb", "The paper publishes the report.", "El periódico publica el informe."), w("compare", "comparar", "verb", "We compare different sources.", "Comparamos diferentes fuentes."),
    ]),
  ],
  B2: [
    u("u38", "Urban Planning", "Evaluate urban space, housing, and transport solutions.", [
      w("urban planning", "urbanismo", "noun", "Urban planning affects daily life.", "El urbanismo afecta a la vida diaria."), w("infrastructure", "infraestructura", "noun", "Infrastructure requires investment.", "La infraestructura requiere inversión."), w("public transport", "transporte público", "noun", "Public transport reduces congestion.", "El transporte público reduce la congestión."), w("zoning", "zonificación", "noun", "Zoning guides construction.", "La zonificación orienta la construcción."), w("green space", "zona verde", "noun", "Green space improves well-being.", "Las zonas verdes mejoran el bienestar."), w("congestion", "congestión", "noun", "Congestion slowed the journey.", "La congestión ralentizó el viaje."), w("densify", "densificar", "verb", "The city densifies the centre.", "La ciudad densifica el centro."), w("balance", "equilibrar", "verb", "The decision balances different needs.", "La decisión equilibra diferentes necesidades."),
    ]),
    u("u39", "Climate and Society", "Consider climate change, its effects, and shared solutions.", [
      w("climate change", "cambio climático", "noun", "Climate change affects everyone.", "El cambio climático afecta a todos."), w("emission", "emisión", "noun", "Emissions must be reduced.", "Las emisiones deben reducirse."), w("adaptation", "adaptación", "noun", "Adaptation requires planning.", "La adaptación requiere planificación."), w("vulnerability", "vulnerabilidad", "noun", "Vulnerability is not distributed equally.", "La vulnerabilidad no se distribuye por igual."), w("fairness", "justicia", "noun", "Fairness is an important goal.", "La justicia es un objetivo importante."), w("policy", "política pública", "noun", "Policy guides investments.", "La política pública orienta las inversiones."), w("reduce", "reducir", "verb", "The measure reduces risks.", "La medida reduce los riesgos."), w("anticipate", "anticipar", "verb", "Decisions must anticipate consequences.", "Las decisiones deben anticipar las consecuencias."),
    ]),
  ],
  C1: [
    u("u38", "Education and Inequality", "Analyse education, opportunity, and social position.", [
      w("education system", "sistema educativo", "noun", "The education system affects opportunities.", "El sistema educativo afecta a las oportunidades."), w("inequality", "desigualdad", "noun", "Inequality appears in different regions.", "La desigualdad aparece en diferentes regiones."), w("accessibility", "accesibilidad", "noun", "Accessibility is part of a good service.", "La accesibilidad forma parte de un buen servicio."), w("selection", "selección", "noun", "Selection can reinforce differences.", "La selección puede reforzar las diferencias."), w("scholarship", "beca", "noun", "The scholarship made the research possible.", "La beca hizo posible la investigación."), w("background factor", "factor de contexto", "noun", "A background factor affects the result.", "Un factor de contexto afecta al resultado."), w("enable", "permitir", "verb", "The service enables participation.", "El servicio permite la participación."), w("exclude", "excluir", "verb", "A high price can exclude people.", "Un precio alto puede excluir a personas."),
    ]),
    u("u39", "Art and Interpretation", "Discuss art, interpretation, and cultural context.", [
      w("work of art", "obra de arte", "noun", "The work of art raises questions.", "La obra de arte plantea preguntas."), w("interpretation", "interpretación", "noun", "Interpretation depends on perspective.", "La interpretación depende de la perspectiva."), w("symbol", "símbolo", "noun", "The symbol recurs in the novel.", "El símbolo se repite en la novela."), w("context", "contexto", "noun", "Context changes meaning.", "El contexto cambia el significado."), w("aesthetics", "estética", "noun", "Aesthetics studies concepts of beauty.", "La estética estudia conceptos de belleza."), w("audience", "público", "noun", "The audience reacts in different ways.", "El público reacciona de diferentes maneras."), w("portray", "representar", "verb", "The work portrays change.", "La obra representa el cambio."), w("interpret", "interpretar", "verb", "The reader interprets the scene anew.", "El lector interpreta la escena de nuevo."),
    ]),
  ],
  C2: [
    u("u38", "Knowledge and Uncertainty", "Reflect on the limits of knowledge and the quality of justification.", [
      w("epistemology", "epistemología", "noun", "Epistemology studies the conditions of knowledge.", "La epistemología estudia las condiciones del conocimiento."), w("justification", "justificación", "noun", "A claim needs justification.", "Una afirmación necesita justificación."), w("uncertainty", "incertidumbre", "noun", "Uncertainty belongs to forecasts.", "La incertidumbre forma parte de las previsiones."), w("evidence", "pruebas", "noun", "Evidence strengthens the conclusion.", "Las pruebas refuerzan la conclusión."), w("presupposition", "presuposición", "noun", "A presupposition can go unnoticed.", "Una presuposición puede pasar inadvertida."), w("contradiction", "contradicción", "noun", "A contradiction requires further clarification.", "Una contradicción requiere más aclaración."), w("question", "cuestionar", "verb", "The researcher questions the premise.", "El investigador cuestiona la premisa."), w("verify", "verificar", "verb", "The results must be independently verified.", "Los resultados deben verificarse de forma independiente."),
    ]),
    u("u39", "Ethics and Technology", "Evaluate technology, responsibility, and moral tensions.", [
      w("artificial intelligence", "inteligencia artificial", "noun", "Artificial intelligence changes how work is done.", "La inteligencia artificial cambia la forma de trabajar."), w("privacy", "privacidad", "noun", "Privacy needs protection.", "La privacidad necesita protección."), w("algorithm", "algoritmo", "noun", "An algorithm organizes information.", "Un algoritmo organiza la información."), w("responsibility", "responsabilidad", "noun", "Responsibility does not disappear through automation.", "La responsabilidad no desaparece con la automatización."), w("surveillance", "vigilancia", "noun", "Surveillance raises ethical questions.", "La vigilancia plantea preguntas éticas."), w("bias", "sesgo", "noun", "Bias distorts the result.", "El sesgo distorsiona el resultado."), w("regulate", "regular", "verb", "The law regulates the use of technology.", "La ley regula el uso de la tecnología."), w("anticipate", "anticipar", "verb", "Society must anticipate risks.", "La sociedad debe anticipar los riesgos."),
    ]),
  ],
};
