import type { VocabularyItem } from "./learn-data";

const reviewed = (
  word: string,
  translation: string,
  pos: VocabularyItem["pos"],
  ipa: string,
  definition: string,
  example: string,
  exampleTranslation: string,
  category: string,
  tags: string[],
  synonyms: string[],
  collocations: string[],
  wordFamily: string[],
): VocabularyItem => ({
  word,
  translation,
  translationLang: "ar",
  pos,
  ipa,
  definition,
  example,
  exampleTranslation,
  category,
  tags,
  synonyms,
  antonyms: [],
  collocations,
  wordFamily,
});

/**
 * Reviewed enrichment for the six existing B1/B2/C1 u8 and u9 units with the
 * smallest runtime vocabulary banks. Vocabulary is appended through the
 * existing merge path; no unit, lesson, or identifier is declared here.
 */
export const ENGLISH_B1_B2_C1_U8_U9_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u8: [
      reviewed("cover letter", "خطاب التقديم", "noun", "/ˈkʌvər ˌletər/", "a letter sent with a job application to explain a candidate’s suitability", "She tailored her cover letter to the skills listed in the advert.", "خصصت خطاب تقديمها وفق المهارات المذكورة في الإعلان.", "employment", ["work", "applications"], ["application letter", "motivation letter"], ["write a cover letter", "tailor a cover letter"], ["cover", "covering"]),
      reviewed("job reference", "تزكية وظيفية", "noun", "/ˈdʒɑːb ˌrefərəns/", "a statement from someone who can describe an applicant’s work or character", "The employer asked for a job reference from her former manager.", "طلب صاحب العمل تزكية وظيفية من مديرها السابق.", "employment", ["work", "applications"], ["employment reference", "professional reference"], ["provide a job reference", "request a reference"], ["refer", "referee"]),
      reviewed("probationary period", "فترة الاختبار الوظيفي", "noun", "/prəˈbeɪʃəneri ˌpɪəriəd/", "a trial period at the beginning of a job during which performance is assessed", "During the probationary period, she received weekly feedback from her supervisor.", "خلال فترة الاختبار الوظيفي، تلقت ملاحظات أسبوعية من مشرفتها.", "employment", ["work", "performance"], ["trial period", "probation"], ["complete a probationary period", "pass probation"], ["probation", "probationary"]),
      reviewed("salary negotiation", "التفاوض على الراتب", "noun", "/ˈsæləri nɪˌɡoʊʃiˈeɪʃən/", "a discussion about the pay and conditions offered for a job", "Good preparation gave him confidence during the salary negotiation.", "منحه الاستعداد الجيد الثقة أثناء التفاوض على الراتب.", "employment", ["work", "money"], ["pay negotiation", "wage discussion"], ["enter salary negotiation", "negotiate a salary"], ["negotiate", "negotiator"]),
      reviewed("performance appraisal", "تقييم الأداء", "noun", "/pərˈfɔːrməns əˌpreɪzəl/", "a formal assessment of how well an employee has worked", "Her performance appraisal highlighted both her achievements and her training needs.", "أبرز تقييم أدائها إنجازاتها واحتياجاتها التدريبية.", "employment", ["work", "feedback"], ["performance assessment", "staff evaluation"], ["conduct an appraisal", "annual performance appraisal"], ["appraise", "appraisal"]),
      reviewed("workplace accommodation", "تكييف مكان العمل", "noun", "/ˈwɜːrkpleɪs əˌkɑːməˈdeɪʃən/", "a reasonable change that helps an employee work effectively", "The company arranged a workplace accommodation for an employee with limited mobility.", "رتبت الشركة تكييفًا في مكان العمل لموظف محدود الحركة.", "employment", ["work", "inclusion"], ["work adjustment", "reasonable accommodation"], ["request an accommodation", "provide workplace accommodation"], ["accommodate", "accommodating"]),
      reviewed("professional networking", "بناء العلاقات المهنية", "noun", "/prəˈfeʃənəl ˈnetˌwɜːrkɪŋ/", "the activity of forming useful work-related relationships", "Professional networking helped her learn about opportunities that were not advertised online.", "ساعدها بناء العلاقات المهنية على معرفة فرص لم تُعلن عبر الإنترنت.", "employment", ["work", "relationships"], ["career networking", "professional relationship-building"], ["build a network", "attend a networking event"], ["network", "networker"]),
      reviewed("notice period", "مدة الإخطار", "noun", "/ˈnoʊtɪs ˌpɪəriəd/", "the time an employee must continue working after announcing a resignation", "He gave a month’s notice period before leaving the company.", "قدم إشعارًا مدته شهر قبل مغادرة الشركة.", "employment", ["work", "contracts"], ["required notice", "resignation notice"], ["give notice", "serve a notice period"], ["notify", "notification"]),
    ],
    u9: [
      reviewed("breaking news", "خبر عاجل", "noun", "/ˈbreɪkɪŋ ˌnuːz/", "important news that is being reported as events are still developing", "The channel interrupted its programme to announce breaking news.", "قطعَت القناة برنامجها للإعلان عن خبر عاجل.", "journalism", ["media", "events"], ["developing news", "urgent report"], ["report breaking news", "breaking-news bulletin"], ["break", "breaking"]),
      reviewed("news outlet", "وسيلة إخبارية", "noun", "/ˈnuːz ˌaʊtlet/", "an organisation that publishes or broadcasts news", "The reporter compared accounts from more than one news outlet.", "قارن الصحفي روايات أكثر من وسيلة إخبارية.", "journalism", ["media", "sources"], ["news organisation", "media outlet"], ["independent news outlet", "local news outlet"], ["outlet", "outlets"]),
      reviewed("anonymous source", "مصدر مجهول", "noun", "/əˌnɑːnɪməs ˈsɔːrs/", "a person who provides information without having their name published", "The article quoted an anonymous source but explained why the source was protected.", "اقتبس المقال من مصدر مجهول، لكنه أوضح سبب حماية المصدر.", "journalism", ["media", "privacy"], ["unnamed source", "confidential source"], ["protect an anonymous source", "cite a source"], ["anonymity", "anonymously"]),
      reviewed("editorial policy", "سياسة التحرير", "noun", "/ˌedɪˈtɔːriəl ˈpɑːləsi/", "the principles a news organisation uses when selecting and presenting stories", "The newspaper’s editorial policy requires evidence for serious allegations.", "تتطلب سياسة تحرير الصحيفة أدلة على الادعاءات الخطيرة.", "journalism", ["media", "standards"], ["editorial guidelines", "news policy"], ["follow editorial policy", "publish under a policy"], ["edit", "editorial"]),
      reviewed("investigative reporting", "صحافة استقصائية", "noun", "/ɪnˌvestɪɡətɪv rɪˈpɔːrtɪŋ/", "journalism that examines hidden or complex issues through detailed research", "Investigative reporting revealed how public money had been spent.", "كشفت الصحافة الاستقصائية كيف أُنفقت الأموال العامة.", "journalism", ["media", "research"], ["investigative journalism", "in-depth reporting"], ["conduct investigative reporting", "investigative report"], ["investigate", "investigation"]),
      reviewed("news embargo", "حظر نشر مؤقت", "noun", "/ˈnuːz emˌbɑːrɡoʊ/", "an agreement that prevents information from being published before a specified time", "The ministry placed a news embargo on the report until Monday morning.", "فرضت الوزارة حظر نشر مؤقتًا على التقرير حتى صباح الاثنين.", "journalism", ["media", "timing"], ["publication restriction", "release embargo"], ["lift an embargo", "observe a news embargo"], ["embargo", "embargoed"]),
      reviewed("public interest", "المصلحة العامة", "noun", "/ˌpʌblɪk ˈɪntrəst/", "the welfare or concern of the community as a whole", "The editor argued that publishing the investigation served the public interest.", "جادل المحرر بأن نشر التحقيق يخدم المصلحة العامة.", "journalism", ["media", "society"], ["community interest", "public good"], ["serve the public interest", "matter of public interest"], ["interest", "interested"]),
      reviewed("correction notice", "إشعار تصحيح", "noun", "/kəˈrekʃən ˌnoʊtɪs/", "a public statement that identifies and fixes an error in a published report", "The website added a correction notice after discovering an incorrect figure.", "أضاف الموقع إشعار تصحيح بعد اكتشاف رقم غير صحيح.", "journalism", ["media", "accuracy"], ["erratum", "correction statement"], ["publish a correction", "issue a correction notice"], ["correct", "corrective"]),
    ],
  },
  B2: {
    u8: [
      reviewed("learning outcome", "ناتج التعلم", "noun", "/ˈlɜːrnɪŋ ˌaʊtkʌm/", "a specific skill or understanding that a course is designed to develop", "Each learning outcome is linked to an assessment task.", "يرتبط كل ناتج تعلم بمهمة تقييم.", "education", ["study", "assessment"], ["educational outcome", "course objective"], ["define a learning outcome", "achieve learning outcomes"], ["learn", "learner"]),
      reviewed("academic transcript", "كشف الدرجات الأكاديمي", "noun", "/ˌækəˈdemɪk ˈtrænskrɪpt/", "an official record of a student’s courses and grades", "The university requested an academic transcript with the application.", "طلبت الجامعة كشف الدرجات الأكاديمي مع الطلب.", "education", ["study", "records"], ["grade record", "academic record"], ["submit a transcript", "official academic transcript"], ["transcribe", "transcription"]),
      reviewed("coursework assessment", "تقييم أعمال المقرر", "noun", "/ˈkɔːrswɜːrk əˌsesmənt/", "the evaluation of assignments completed during a course rather than in one final exam", "Coursework assessment encouraged students to revise their arguments over time.", "شجع تقييم أعمال المقرر الطلاب على مراجعة حججهم مع مرور الوقت.", "education", ["study", "assessment"], ["continuous assessment", "assignment-based assessment"], ["complete coursework", "coursework assessment criteria"], ["assess", "assessment"]),
      reviewed("field of study", "مجال الدراسة", "noun", "/ˌfiːld əv ˈstʌdi/", "an academic subject or area in which someone specialises", "Her field of study combines environmental science and public policy.", "يجمع مجال دراستها بين علوم البيئة والسياسة العامة.", "education", ["study", "subjects"], ["academic discipline", "area of study"], ["choose a field", "specialise in a field of study"], ["study", "student"]),
      reviewed("degree requirement", "متطلب الدرجة العلمية", "noun", "/dɪˈɡriː rɪˌkwaɪərmənt/", "a condition that must be met to complete an academic degree", "The research project is a degree requirement for final-year students.", "يُعد مشروع البحث متطلبًا للدرجة العلمية لطلاب السنة النهائية.", "education", ["study", "qualifications"], ["graduation requirement", "academic requirement"], ["meet a requirement", "degree requirement"], ["require", "required"]),
      reviewed("tuition waiver", "إعفاء من الرسوم الدراسية", "noun", "/tuˈɪʃən ˌweɪvər/", "official permission not to pay some or all tuition fees", "The scholarship included a tuition waiver for the first year.", "شملت المنحة إعفاءً من الرسوم الدراسية للسنة الأولى.", "education", ["study", "finance"], ["fee exemption", "tuition exemption"], ["receive a waiver", "tuition waiver programme"], ["waive", "waiver"]),
      reviewed("research supervisor", "مشرف البحث", "noun", "/rɪˈsɜːrtʃ ˌsuːpərˈvaɪzər/", "an academic who guides a student’s research project", "Her research supervisor helped her narrow the question and improve the method.", "ساعدها مشرف البحث على تضييق السؤال وتحسين المنهج.", "education", ["study", "research"], ["academic adviser", "research mentor"], ["meet a supervisor", "supervise research"], ["supervise", "supervision"]),
      reviewed("graduate seminar", "حلقة دراسية لطلاب الدراسات العليا", "noun", "/ˈɡrædʒuət ˌsemɪˌnɑːr/", "an advanced discussion class for postgraduate students", "The graduate seminar focused on competing explanations of social change.", "ركزت حلقة الدراسات العليا على تفسيرات متنافسة للتغير الاجتماعي.", "education", ["study", "discussion"], ["postgraduate seminar", "advanced discussion class"], ["attend a seminar", "lead a graduate seminar"], ["graduate", "graduation"]),
    ],
    u9: [
      reviewed("clinical trial", "تجربة سريرية", "noun", "/ˈklɪnɪkəl ˌtraɪəl/", "a carefully controlled study that tests a medical treatment in people", "The treatment entered a clinical trial after promising laboratory results.", "دخل العلاج تجربة سريرية بعد نتائج مخبرية واعدة.", "healthcare", ["medicine", "research"], ["medical trial", "clinical study"], ["conduct a trial", "clinical trial data"], ["clinic", "clinical"]),
      reviewed("dosage instruction", "تعليمات الجرعة", "noun", "/ˈdoʊsɪdʒ ɪnˌstrʌkʃən/", "information explaining how much medicine to take and how often", "Always read the dosage instruction before taking the medicine.", "اقرأ دائمًا تعليمات الجرعة قبل تناول الدواء.", "healthcare", ["medicine", "safety"], ["dose guidance", "medication instruction"], ["follow instructions", "dosage instruction label"], ["dose", "dosage"]),
      reviewed("treatment plan", "خطة العلاج", "noun", "/ˈtriːtmənt plæn/", "an organised set of medical actions designed for a particular patient", "The doctor explained the treatment plan and its possible alternatives.", "شرح الطبيب خطة العلاج وبدائلها المحتملة.", "healthcare", ["medicine", "care"], ["care plan", "medical plan"], ["design a plan", "follow a treatment plan"], ["treat", "treatment"]),
      reviewed("patient consent", "موافقة المريض", "noun", "/ˈpeɪʃənt kənˌsent/", "a patient’s informed agreement to a medical examination or treatment", "The procedure could not begin until the patient consent had been recorded.", "لم يكن بالإمكان بدء الإجراء حتى تُسجل موافقة المريض.", "healthcare", ["medicine", "rights"], ["informed consent", "medical authorisation"], ["obtain consent", "give patient consent"], ["consent", "consensual"]),
      reviewed("diagnostic test", "فحص تشخيصي", "noun", "/ˌdaɪəɡˈnɑːstɪk ˈtest/", "a test used to identify or rule out a medical condition", "The diagnostic test helped the team identify the cause of the symptoms.", "ساعد الفحص التشخيصي الفريق على تحديد سبب الأعراض.", "healthcare", ["medicine", "diagnosis"], ["medical test", "diagnostic examination"], ["order a test", "diagnostic test result"], ["diagnose", "diagnosis"]),
      reviewed("healthcare provider", "مقدم الرعاية الصحية", "noun", "/ˈhelθker prəˌvaɪdər/", "a professional or organisation that delivers medical care", "The healthcare provider offered an interpreter during the consultation.", "وفر مقدم الرعاية الصحية مترجمًا أثناء الاستشارة.", "healthcare", ["medicine", "services"], ["medical provider", "care provider"], ["contact a provider", "healthcare provider network"], ["provide", "provision"]),
      reviewed("follow-up appointment", "موعد متابعة", "noun", "/ˈfɑːloʊ ʌp əˌpɔɪntmənt/", "a later medical visit used to review progress after an earlier consultation", "The nurse arranged a follow-up appointment for two weeks later.", "رتبت الممرضة موعد متابعة بعد أسبوعين.", "healthcare", ["medicine", "care"], ["review appointment", "return visit"], ["schedule a follow-up", "attend an appointment"], ["follow up", "appointment"]),
      reviewed("preventive screening", "فحص وقائي", "noun", "/prɪˈventɪv ˈskriːnɪŋ/", "testing carried out to detect a health risk before symptoms appear", "Preventive screening can identify some conditions at an earlier stage.", "يمكن للفحص الوقائي اكتشاف بعض الحالات في مرحلة مبكرة.", "healthcare", ["medicine", "prevention"], ["health screening", "early detection test"], ["offer screening", "undergo preventive screening"], ["prevent", "prevention"]),
    ],
  },
  C1: {
    u8: [
      reviewed("admissible evidence", "دليل مقبول قانونيًا", "noun", "/ədˌmɪsəbəl ˈevɪdəns/", "evidence that a court allows to be presented and considered", "The judge ruled that the recording was admissible evidence.", "حكم القاضي بأن التسجيل دليل مقبول قانونيًا.", "law", ["justice", "courts"], ["acceptable evidence", "legally permitted evidence"], ["admit evidence", "admissible evidence"], ["admit", "admissibility"]),
      reviewed("cross-examination", "استجواب مضاد", "noun", "/ˌkrɔːs ɪɡˌzæməˈneɪʃən/", "the questioning of a witness by the opposing lawyer in a trial", "The cross-examination exposed inconsistencies in the witness’s account.", "كشف الاستجواب المضاد تناقضات في رواية الشاهد.", "law", ["justice", "courts"], ["opposing examination", "witness questioning"], ["conduct cross-examination", "cross-examination question"], ["examine", "examination"]),
      reviewed("prosecutorial discretion", "السلطة التقديرية للنيابة", "noun", "/ˌprɑːsɪˈkjuːtəriəl dɪˈskreʃən/", "the authority of prosecutors to decide how and whether to pursue a case", "Prosecutorial discretion must be exercised consistently and without discrimination.", "يجب ممارسة السلطة التقديرية للنيابة باتساق ومن دون تمييز.", "law", ["justice", "government"], ["prosecution discretion", "charging discretion"], ["exercise discretion", "prosecutorial decision"], ["prosecute", "prosecution"]),
      reviewed("witness testimony", "شهادة الشاهد", "noun", "/ˈwɪtnəs ˌtestɪˈmoʊni/", "a formal statement given by a witness in a legal proceeding", "The court compared the witness testimony with the documentary record.", "قارنَت المحكمة شهادة الشاهد بالسجل الوثائقي.", "law", ["justice", "courts"], ["witness statement", "oral evidence"], ["give testimony", "witness testimony"], ["testify", "testimonial"]),
      reviewed("court ruling", "حكم قضائي", "noun", "/ˈkɔːrt ˌruːlɪŋ/", "an official decision made by a court", "The court ruling clarified how the regulation should be interpreted.", "وضح الحكم القضائي كيفية تفسير اللائحة.", "law", ["justice", "courts"], ["judicial decision", "court judgment"], ["issue a ruling", "comply with a ruling"], ["rule", "ruling"]),
      reviewed("reasonable doubt", "شك معقول", "noun", "/ˌriːzənəbəl ˈdaʊt/", "a level of uncertainty that prevents a criminal conviction", "The defence argued that the evidence left reasonable doubt about the identification.", "جادل الدفاع بأن الأدلة تركت شكًا معقولًا بشأن تحديد الهوية.", "law", ["justice", "proof"], ["legitimate doubt", "substantial uncertainty"], ["raise reasonable doubt", "beyond reasonable doubt"], ["reason", "reasonable"]),
      reviewed("administrative law challenge", "طعن في قرار إداري", "noun", "/ədˈmɪnɪstrətɪv lɔː ˈtʃælɪndʒ/", "a legal challenge to the lawfulness or fairness of a public authority’s decision", "The organisation brought an administrative law challenge against the licensing decision.", "رفعت المنظمة طعنًا في قرار إداري يتعلق بقرار الترخيص.", "law", ["justice", "government"], ["public-law challenge", "legal challenge"], ["bring a challenge", "administrative law challenge"], ["administer", "administrative"]),
      reviewed("evidentiary standard", "معيار الإثبات", "noun", "/ˌevɪˈdenʃəri ˈstændərd/", "the level of proof required before a legal conclusion can be reached", "The evidentiary standard is higher in a criminal case than in a civil claim.", "يكون معيار الإثبات أعلى في القضية الجنائية منه في الدعوى المدنية.", "law", ["justice", "proof"], ["standard of proof", "proof threshold"], ["meet a standard", "evidentiary standard"], ["evidence", "evidential"]),
    ],
    u9: [
      reviewed("bargaining position", "موقف تفاوضي", "noun", "/ˈbɑːrɡənɪŋ pəˌzɪʃən/", "the advantages and constraints a person or group brings to a negotiation", "The union strengthened its bargaining position by presenting a united proposal.", "عززَت النقابة موقفها التفاوضي بتقديم مقترح موحد.", "negotiation", ["work", "conflict"], ["negotiating position", "bargaining strength"], ["strengthen a position", "take a bargaining position"], ["bargain", "bargaining"]),
      reviewed("binding clause", "بند ملزم", "noun", "/ˈbaɪndɪŋ klɔːz/", "a section of an agreement that creates an obligation the parties must follow", "The contract contains a binding clause on confidentiality.", "يتضمن العقد بندًا ملزمًا بشأن السرية.", "negotiation", ["contracts", "law"], ["enforceable clause", "contractual obligation"], ["include a clause", "binding clause"], ["bind", "binding"]),
      reviewed("mediation process", "عملية وساطة", "noun", "/miːdiˈeɪʃən ˌprɑːses/", "a structured process in which a neutral person helps parties reach an agreement", "The mediation process allowed both sides to discuss the dispute privately.", "أتاحت عملية الوساطة للطرفين مناقشة النزاع على انفراد.", "negotiation", ["conflict", "agreement"], ["conciliation process", "facilitated negotiation"], ["enter mediation", "mediation process"], ["mediate", "mediator"]),
      reviewed("diplomatic channel", "قناة دبلوماسية", "noun", "/ˌdɪpləˈmætɪk ˈtʃænəl/", "an official or discreet route for communication between governments", "The two governments used a diplomatic channel to prevent the dispute from escalating.", "استخدمت الحكومتان قناة دبلوماسية لمنع تصعيد النزاع.", "negotiation", ["politics", "communication"], ["official channel", "back-channel communication"], ["open a channel", "use diplomatic channels"], ["diplomacy", "diplomatic"]),
      reviewed("implementation deadline", "موعد نهائي للتنفيذ", "noun", "/ˌɪmplɪmenˈteɪʃən ˈdedlaɪn/", "the final date by which an agreed measure must be put into effect", "The parties set an implementation deadline and assigned responsibility for each step.", "حدد الطرفان موعدًا نهائيًا للتنفيذ وعيّنا مسؤولية كل خطوة.", "negotiation", ["agreements", "planning"], ["execution deadline", "delivery date"], ["meet a deadline", "set an implementation deadline"], ["implement", "implementation"]),
      reviewed("negotiating mandate", "تفويض تفاوضي", "noun", "/nɪˈɡoʊʃiˌeɪtɪŋ ˈmændeɪt/", "the authority and limits given to someone who negotiates on behalf of a group", "The envoy returned for approval after reaching the edge of the negotiating mandate.", "عاد المبعوث لطلب الموافقة بعد بلوغ حدود التفويض التفاوضي.", "negotiation", ["politics", "authority"], ["negotiation authority", "negotiating brief"], ["receive a mandate", "operate within a mandate"], ["mandate", "mandated"]),
      reviewed("good-faith negotiation", "تفاوض بحسن نية", "noun", "/ˌɡʊd ˈfeɪθ nɪˌɡoʊʃiˈeɪʃən/", "a negotiation conducted honestly with a genuine willingness to reach a fair agreement", "Good-faith negotiation requires both sides to disclose the practical limits of their proposals.", "يتطلب التفاوض بحسن نية أن يكشف الطرفان الحدود العملية لمقترحاتهما.", "negotiation", ["ethics", "agreement"], ["honest negotiation", "constructive bargaining"], ["negotiate in good faith", "good-faith negotiation"], ["negotiate", "negotiator"]),
      reviewed("dispute settlement", "تسوية النزاع", "noun", "/dɪˈspjuːt ˌsetəlmənt/", "the process of bringing a disagreement to an agreed conclusion", "The agreement established an independent panel for dispute settlement.", "أنشأ الاتفاق لجنة مستقلة لتسوية النزاع.", "negotiation", ["conflict", "law"], ["conflict settlement", "dispute resolution"], ["pursue settlement", "dispute settlement mechanism"], ["settle", "settlement"]),
    ],
  },
};
