// Additional Finnish curriculum units u34-u35 for every CEFR level.
// Deterministic local curriculum data; APIs may enrich it but never generate it.
type Word = { word: string; translation: string; pos: string; example: string; exampleTranslation: string };
type Unit = { id: string; title: string; description: string; words: Word[]; phrases: { phrase: string; translation: string }[]; dialogue: { speaker: string; text: string; translation: string }[]; reading: { title: string; text: string; translation: string } };
const w = (word: string, translation: string, pos: string, example: string, exampleTranslation: string): Word => ({ word, translation, pos, example, exampleTranslation });
const u = (id: string, title: string, description: string, words: Word[]): Unit => ({
  id, title, description, words,
  phrases: words.slice(0, 4).map((item) => ({ phrase: item.example, translation: item.exampleTranslation })),
  dialogue: [0, 1, 2, 3].map((index) => ({ speaker: index % 2 === 0 ? "A" : "B", text: words[index]!.example, translation: words[index]!.exampleTranslation })),
  reading: { title, text: words.slice(0, 4).map((item) => item.example).join(" "), translation: words.slice(0, 4).map((item) => item.exampleTranslation).join(" ") },
});

export const ADDITIONAL_FI_PART6_UNITS: Record<string, Unit[]> = {
  A0: [
    u("u34", "Koti ja esineet", "Nimeä kodin huoneita ja tavallisia esineitä.", [
      w("koti", "home", "noun", "Kotini on pieni.", "My home is small."),
      w("ovi", "door", "noun", "Ovi on auki.", "The door is open."),
      w("tuoli", "chair", "noun", "Tuoli on pöydän vieressä.", "The chair is next to the table."),
      w("pöytä", "table", "noun", "Kirja on pöydällä.", "The book is on the table."),
      w("lamppu", "lamp", "noun", "Lamppu on kirkas.", "The lamp is bright."),
      w("kirja", "book", "noun", "Luen kirjaa.", "I am reading a book."),
      w("laukku", "bag", "noun", "Laukku on lattialla.", "The bag is on the floor."),
      w("kello", "clock", "noun", "Kello on seinällä.", "The clock is on the wall."),
    ]),
    u("u35", "Värit ja vaatteet", "Kuvaile värejä ja yksinkertaisia vaatteita.", [
      w("punainen", "red", "adjective", "Minulla on punainen paita.", "I have a red shirt."),
      w("sininen", "blue", "adjective", "Taivas on sininen.", "The sky is blue."),
      w("vihreä", "green", "adjective", "Puu on vihreä.", "The tree is green."),
      w("musta", "black", "adjective", "Hänellä on musta takki.", "She has a black coat."),
      w("paita", "shirt", "noun", "Paita on puhdas.", "The shirt is clean."),
      w("housut", "trousers", "noun", "Housut ovat uudet.", "The trousers are new."),
      w("kenkä", "shoe", "noun", "Kenkä on jalassa.", "The shoe is on the foot."),
      w("hattu", "hat", "noun", "Hattu suojaa päätä.", "The hat protects the head."),
    ]),
  ],
  A1: [
    u("u34", "Ruoka ja ostokset", "Keskustele ruoasta ja osta tavallisia tuotteita.", [
      w("omena", "apple", "noun", "Omena on makea.", "The apple is sweet."),
      w("leipä", "bread", "noun", "Ostan tuoretta leipää.", "I buy fresh bread."),
      w("maito", "milk", "noun", "Maito on jääkaapissa.", "The milk is in the fridge."),
      w("juusto", "cheese", "noun", "Pidän tästä juustosta.", "I like this cheese."),
      w("hinta", "price", "noun", "Mikä on tämän hinta?", "What is the price of this?"),
      w("halpa", "cheap", "adjective", "Tämä omena on halpa.", "This apple is cheap."),
      w("kallis", "expensive", "adjective", "Ravintola on kallis.", "The restaurant is expensive."),
      w("maksaa", "pay", "verb", "Voin maksaa kortilla.", "I can pay by card."),
    ]),
    u("u35", "Suunnat ja liikkuminen", "Kysy ja anna helppoja reittiohjeita.", [
      w("vasen", "left", "noun", "Käänny vasemmalle.", "Turn left."),
      w("oikea", "right", "noun", "Käänny oikealle.", "Turn right."),
      w("suoraan", "straight", "adverb", "Mene suoraan eteenpäin.", "Go straight ahead."),
      w("lähellä", "near", "adverb", "Asema on lähellä.", "The station is near."),
      w("kaukana", "far", "adverb", "Lentokenttä on kaukana.", "The airport is far away."),
      w("silta", "bridge", "noun", "Silta on joen yli.", "The bridge is over the river."),
      w("risteys", "intersection", "noun", "Risteys on seuraava.", "The intersection is next."),
      w("löytää", "find", "verb", "Löydät museon helposti.", "You will find the museum easily."),
    ]),
  ],
  A2: [
    u("u34", "Luonto ja sää", "Kuvaile luontoa ja vaihtelevaa säätä.", [
      w("metsä", "forest", "noun", "Kävelimme metsässä.", "We walked in the forest."),
      w("järvi", "lake", "noun", "Järvi on tyyni.", "The lake is calm."),
      w("ranta", "shore", "noun", "Rannalla on paljon ihmisiä.", "There are many people on the shore."),
      w("pilvi", "cloud", "noun", "Tumma pilvi lähestyy.", "A dark cloud is approaching."),
      w("myrsky", "storm", "noun", "Myrsky alkoi illalla.", "The storm began in the evening."),
      w("aurinkoinen", "sunny", "adjective", "Huomenna on aurinkoista.", "Tomorrow will be sunny."),
      w("sataa", "rain", "verb", "Ulkona sataa.", "It is raining outside."),
      w("suojella", "protect", "verb", "Meidän pitää suojella luontoa.", "We must protect nature."),
    ]),
    u("u35", "Päätökset ja suunnitelmat", "Selitä suunnitelmia ja perustele arkisia päätöksiä.", [
      w("tavoite", "goal", "noun", "Tavoitteeni on oppia suomea.", "My goal is to learn Finnish."),
      w("suunnitelma", "plan", "noun", "Suunnitelma muuttui nopeasti.", "The plan changed quickly."),
      w("valinta", "choice", "noun", "Valinta ei ollut helppo.", "The choice was not easy."),
      w("syy", "reason", "noun", "Mikä on päätöksen syy?", "What is the reason for the decision?"),
      w("vaihtoehto", "alternative", "noun", "Tämä on hyvä vaihtoehto.", "This is a good alternative."),
      w("päättää", "decide", "verb", "Päätimme jäädä kotiin.", "We decided to stay home."),
      w("verrata", "compare", "verb", "Vertaan kahta tarjousta.", "I compare two offers."),
      w("onnistua", "succeed", "verb", "Hän onnistui tehtävässä.", "She succeeded in the task."),
    ]),
  ],
  B1: [
    u("u34", "Media ja mielipiteet", "Keskustele uutisista ja ilmaise perusteltuja mielipiteitä.", [
      w("lähde", "source", "noun", "Tarkista uutisen lähde.", "Check the source of the news."),
      w("mielipide", "opinion", "noun", "Hän ilmaisi mielipiteensä.", "He expressed his opinion."),
      w("väite", "claim", "noun", "Väite tarvitsee todisteita.", "A claim needs evidence."),
      w("todiste", "evidence", "noun", "Raportti sisältää uuden todisteen.", "The report contains new evidence."),
      w("näkökulma", "perspective", "noun", "Asiaa voi katsoa toisesta näkökulmasta.", "The issue can be viewed from another perspective."),
      w("epäillä", "doubt", "verb", "Saan epäillä väitettä.", "I may doubt the claim."),
      w("perustella", "justify", "verb", "Hän perusteli päätöksensä.", "She justified her decision."),
      w("vaikuttaa", "influence", "verb", "Media vaikuttaa mielipiteisiin.", "The media influences opinions."),
    ]),
    u("u35", "Vapaaehtoistyö ja yhteisö", "Kerro, miten ihmiset voivat auttaa yhteisöään.", [
      w("yhteisö", "community", "noun", "Yhteisö järjestää tapahtuman.", "The community organises an event."),
      w("vapaaehtoinen", "volunteer", "noun", "Vapaaehtoinen auttaa lapsia.", "The volunteer helps children."),
      w("apu", "help", "noun", "Apua tarvitaan nopeasti.", "Help is needed quickly."),
      w("järjestö", "organisation", "noun", "Järjestö tukee perheitä.", "The organisation supports families."),
      w("lahjoitus", "donation", "noun", "Lahjoitus auttaa toimintaa.", "The donation supports the work."),
      w("osallistua", "participate", "verb", "Kaikki voivat osallistua.", "Everyone can participate."),
      w("tukea", "support", "verb", "Naapurit tukevat toisiaan.", "Neighbours support one another."),
      w("järjestää", "organise", "verb", "Nuoret järjestävät konsertin.", "Young people organise a concert."),
    ]),
  ],
  B2: [
    u("u34", "Tutkimus ja näyttö", "Analysoi tutkimuksen menetelmiä ja näytön laatua.", [
      w("hypoteesi", "hypothesis", "noun", "Tutkimus testaa hypoteesia.", "The study tests a hypothesis."),
      w("menetelmä", "methodology", "noun", "Menetelmä kuvataan tarkasti.", "The methodology is described precisely."),
      w("otos", "sample", "noun", "Otos oli melko pieni.", "The sample was quite small."),
      w("tulos", "result", "noun", "Tulos tukee aiempaa teoriaa.", "The result supports the earlier theory."),
      w("rajoitus", "limitation", "noun", "Tutkimuksella on selvä rajoitus.", "The study has a clear limitation."),
      w("todentaa", "validate", "verb", "Lisätestit voivat todentaa mallin.", "Additional tests can validate the model."),
      w("havaita", "observe", "verb", "Tutkijat havaitsivat muutoksen.", "The researchers observed a change."),
      w("yleistää", "generalise", "verb", "Tulosta ei voi yleistää kaikkiin.", "The result cannot be generalised to everyone."),
    ]),
    u("u35", "Liiketoiminta ja neuvottelu", "Harjoittele sopimista, tarjouksia ja yhteistyötä.", [
      w("sopimus", "contract", "noun", "Sopimus allekirjoitetaan huomenna.", "The contract will be signed tomorrow."),
      w("tarjous", "offer", "noun", "Tarjous on voimassa viikon.", "The offer is valid for a week."),
      w("neuvottelu", "negotiation", "noun", "Neuvottelu kesti kaksi tuntia.", "The negotiation lasted two hours."),
      w("kumppani", "partner", "noun", "Luotamme uuteen kumppaniin.", "We trust the new partner."),
      w("riski", "risk", "noun", "Hanke sisältää taloudellisen riskin.", "The project involves financial risk."),
      w("neuvotella", "negotiate", "verb", "Osapuolet neuvottelevat hinnasta.", "The parties negotiate the price."),
      w("sopia", "agree", "verb", "Sovimme yhteisistä tavoitteista.", "We agreed on shared goals."),
      w("ennustaa", "forecast", "verb", "Asiantuntijat ennustavat kasvua.", "Experts forecast growth."),
    ]),
  ],
  C1: [
    u("u34", "Laki ja julkinen politiikka", "Arvioi lakeja, sääntelyä ja julkisia päätöksiä.", [
      w("lainsäädäntö", "legislation", "noun", "Uusi lainsäädäntö muuttaa käytäntöä.", "New legislation changes the practice."),
      w("sääntely", "regulation", "noun", "Sääntely suojaa kuluttajia.", "Regulation protects consumers."),
      w("velvoite", "obligation", "noun", "Yrityksellä on tietty velvoite.", "The company has a specific obligation."),
      w("oikeus", "right", "noun", "Jokaisella on oikeus tietoon.", "Everyone has a right to information."),
      w("vaikutus", "impact", "noun", "Päätöksellä on laaja vaikutus.", "The decision has a broad impact."),
      w("säätää", "enact", "verb", "Parlamentti säätää uuden lain.", "Parliament enacts a new law."),
      w("valvoa", "enforce", "verb", "Viranomaiset valvovat sääntöjä.", "Authorities enforce the rules."),
      w("arvioida", "evaluate", "verb", "Komitea arvioi politiikan vaikutuksia.", "The committee evaluates the policy's effects."),
    ]),
    u("u35", "Kieli ja kulttuuri", "Tutki, miten kieli ilmaisee identiteettiä ja kulttuuria.", [
      w("identiteetti", "identity", "noun", "Kieli on osa identiteettiä.", "Language is part of identity."),
      w("murrea", "dialect", "noun", "Alueella puhutaan omaa murretta.", "The region has its own dialect."),
      w("sanonta", "idiom", "noun", "Sanonta ei käänny suoraan.", "The idiom cannot be translated directly."),
      w("merkitys", "meaning", "noun", "Sanan merkitys riippuu asiayhteydestä.", "The meaning of a word depends on context."),
      w("perinne", "tradition", "noun", "Perinne siirtyy sukupolvelta toiselle.", "The tradition passes from one generation to another."),
      w("ilmaista", "express", "verb", "Taide ilmaisee yhteisiä kokemuksia.", "Art expresses shared experiences."),
      w("tulkita", "interpret", "verb", "Lukija voi tulkita tekstin eri tavalla.", "A reader can interpret the text differently."),
      w("säilyttää", "preserve", "verb", "Koulu auttaa säilyttämään kielen.", "The school helps preserve the language."),
    ]),
  ],
  C2: [
    u("u34", "Tieto ja todellisuus", "Pohdi tiedon, totuuden ja havaintojen suhdetta.", [
      w("tieto", "knowledge", "noun", "Tieto perustuu usein kokemukseen.", "Knowledge is often based on experience."),
      w("totuus", "truth", "noun", "Totuuden määrittely ei ole helppoa.", "Defining truth is not easy."),
      w("havainto", "perception", "noun", "Havainto voi olla rajallinen.", "Perception can be limited."),
      w("todellisuus", "reality", "noun", "Kieli rakentaa osan todellisuudesta.", "Language constructs part of reality."),
      w("perustelu", "justification", "noun", "Väite tarvitsee perustelun.", "A claim needs justification."),
      w("kyseenalaistaa", "question", "verb", "Filosoofia kyseenalaistaa oletuksia.", "Philosophy questions assumptions."),
      w("päätellä", "infer", "verb", "Voimme päätellä tuloksesta jotakin.", "We can infer something from the result."),
      w("osoittaa", "demonstrate", "verb", "Esimerkki osoittaa ongelman.", "The example demonstrates the problem."),
    ]),
    u("u35", "Globaali etiikka", "Keskustele vastuusta, oikeudenmukaisuudesta ja yhteisestä tulevaisuudesta.", [
      w("vastuu", "responsibility", "noun", "Yhteinen vastuu vaatii yhteistyötä.", "Shared responsibility requires cooperation."),
      w("oikeudenmukaisuus", "justice", "noun", "Oikeudenmukaisuus ei tarkoita aina samaa kohtelua.", "Justice does not always mean identical treatment."),
      w("ihmisarvo", "human dignity", "noun", "Ihmisarvo kuuluu kaikille.", "Human dignity belongs to everyone."),
      w("solidaarisuus", "solidarity", "noun", "Solidaarisuus auttaa kriisissä.", "Solidarity helps in a crisis."),
      w("riippuvuus", "interdependence", "noun", "Maailman riippuvuus näkyy kaupankäynnissä.", "Global interdependence appears in trade."),
      w("puolustaa", "defend", "verb", "Laki puolustaa heikoimpia.", "The law defends the most vulnerable."),
      w("jakaa", "share", "verb", "Meidän täytyy jakaa resurssit reilusti.", "We must share resources fairly."),
      w("sovittaa", "reconcile", "verb", "Dialogi voi sovittaa ristiriitaisia arvoja.", "Dialogue can reconcile conflicting values."),
    ]),
  ],
};
