import type { VocabularyItem } from "./learn-data";

/**
 * Additional English vocabulary keyed by existing CEFR level and unit id.
 * This bank enriches lessons in place; it never creates or renames units.
 */
export const ENGLISH_UNIT_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  A0: {
    u54: [
      { word: "raincoat", translation: "impermeable", pos: "noun", ipa: "/ˈreɪnkoʊt/", definition: "a coat that keeps you dry in the rain", example: "Take your raincoat because the sky is dark.", exampleTranslation: "Lleva tu impermeable porque el cielo está oscuro.", synonyms: ["waterproof coat"], antonyms: [], collocations: ["wear a raincoat", "yellow raincoat"], wordFamily: ["rain", "raincoat", "rainy"], tags: ["weather", "clothes"], category: "clothing" },
      { word: "breeze", translation: "brisa", pos: "noun", ipa: "/briːz/", definition: "a light wind", example: "A cool breeze comes through the window.", exampleTranslation: "Una brisa fresca entra por la ventana.", synonyms: ["light wind", "wind"], antonyms: ["stillness"], collocations: ["cool breeze", "gentle breeze"], wordFamily: ["breeze", "breezy"], tags: ["weather", "nature"], category: "weather" },
      { word: "forecast", translation: "pronóstico", pos: "noun", ipa: "/ˈfɔːrkæst/", definition: "a statement about what the weather will be like", example: "The forecast says it will rain tomorrow.", exampleTranslation: "El pronóstico dice que lloverá mañana.", synonyms: ["prediction", "outlook"], antonyms: [], collocations: ["weather forecast", "check the forecast"], wordFamily: ["forecast"], tags: ["weather", "time"], category: "weather" },
      { word: "puddle", translation: "charco", pos: "noun", ipa: "/ˈpʌdəl/", definition: "a small pool of water on the ground", example: "The child jumped over a puddle.", exampleTranslation: "El niño saltó sobre un charco.", synonyms: ["pool", "pool of water"], antonyms: [], collocations: ["deep puddle", "jump in a puddle"], wordFamily: ["puddle"], tags: ["weather", "outdoors"], category: "nature" },
      { word: "rainbow", translation: "arcoíris", pos: "noun", ipa: "/ˈreɪnboʊ/", definition: "a curved band of colours seen in the sky after rain", example: "A bright rainbow appeared after the storm.", exampleTranslation: "Un arcoíris brillante apareció después de la tormenta.", synonyms: ["arc", "coloured arc"], antonyms: [], collocations: ["bright rainbow", "see a rainbow"], wordFamily: ["rain", "rainbow"], tags: ["weather", "nature"], category: "nature" },
      { word: "cloudy", translation: "nublado", pos: "adjective", ipa: "/ˈklaʊdi/", definition: "covered with clouds", example: "It is cloudy but not cold today.", exampleTranslation: "Hoy está nublado, pero no hace frío.", synonyms: ["overcast", "grey"], antonyms: ["clear", "sunny"], collocations: ["cloudy sky", "cloudy day"], wordFamily: ["cloud", "cloudy"], tags: ["weather", "nature"], category: "weather" },
      { word: "sunny", translation: "soleado", pos: "adjective", ipa: "/ˈsʌni/", definition: "bright because the sun is shining", example: "It is sunny and warm today.", exampleTranslation: "Hoy hace sol y calor.", synonyms: ["bright", "clear"], antonyms: ["cloudy", "dark"], collocations: ["sunny day", "bright sunshine"], wordFamily: ["sun", "sunny", "sunshine"], tags: ["weather", "nature"], category: "weather" },
      { word: "chilly", translation: "fresco", pos: "adjective", ipa: "/ˈtʃɪli/", definition: "slightly cold", example: "The morning air is chilly.", exampleTranslation: "El aire de la mañana es fresco.", synonyms: ["cool", "cold"], antonyms: ["warm", "hot"], collocations: ["chilly morning", "feel chilly"], wordFamily: ["chill", "chilly"], tags: ["weather", "feelings"], category: "temperature" },
      { word: "stormy", translation: "tormentoso", pos: "adjective", ipa: "/ˈstɔːrmi/", definition: "with strong wind, rain, or thunder", example: "The sea is dangerous on a stormy day.", exampleTranslation: "El mar es peligroso en un día tormentoso.", synonyms: ["rough", "thunderous"], antonyms: ["calm", "peaceful"], collocations: ["stormy weather", "stormy night"], wordFamily: ["storm", "stormy"], tags: ["weather", "nature"], category: "weather" },
    ],
    u55: [
      { word: "drawer", translation: "cajón", pos: "noun", ipa: "/drɔːr/", definition: "a sliding box in a piece of furniture used for storage", example: "The scissors are in the top drawer.", exampleTranslation: "Las tijeras están en el cajón de arriba.", synonyms: ["compartment"], antonyms: [], collocations: ["desk drawer", "open a drawer"], wordFamily: ["draw", "drawer"], tags: ["home", "objects"], category: "furniture" },
      { word: "umbrella", translation: "paraguas", pos: "noun", ipa: "/ʌmˈbrelə/", definition: "a folding object used to protect you from rain", example: "I keep an umbrella by the door.", exampleTranslation: "Guardo un paraguas junto a la puerta.", synonyms: ["parasol"], antonyms: [], collocations: ["carry an umbrella", "folding umbrella"], wordFamily: ["umbrella"], tags: ["weather", "objects"], category: "object" },
      { word: "shelf", translation: "estante", pos: "noun", ipa: "/ʃelf/", definition: "a flat surface attached to a wall or inside furniture for storing things", example: "The blue book is on the top shelf.", exampleTranslation: "El libro azul está en el estante de arriba.", synonyms: ["rack", "bookcase shelf"], antonyms: [], collocations: ["top shelf", "kitchen shelf"], wordFamily: ["shelf", "shelving"], tags: ["home", "objects"], category: "furniture" },
      { word: "mirror", translation: "espejo", pos: "noun", ipa: "/ˈmɪrər/", definition: "a piece of glass that shows a reflection", example: "There is a mirror beside the front door.", exampleTranslation: "Hay un espejo junto a la puerta principal.", synonyms: ["looking glass", "reflector"], antonyms: [], collocations: ["wall mirror", "look in the mirror"], wordFamily: ["mirror", "mirrored"], tags: ["home", "objects"], category: "object" },
      { word: "blanket", translation: "manta", pos: "noun", ipa: "/ˈblæŋkɪt/", definition: "a warm cover used on a bed", example: "I need a warm blanket tonight.", exampleTranslation: "Necesito una manta caliente esta noche.", synonyms: ["cover", "bedcover"], antonyms: [], collocations: ["warm blanket", "wool blanket"], wordFamily: ["blanket", "blanketed"], tags: ["home", "clothes"], category: "object" },
      { word: "towel", translation: "toalla", pos: "noun", ipa: "/ˈtaʊəl/", definition: "a piece of cloth used for drying the body or things", example: "Please bring a clean towel.", exampleTranslation: "Trae una toalla limpia, por favor.", synonyms: ["cloth", "hand towel"], antonyms: [], collocations: ["clean towel", "bath towel"], wordFamily: ["towel", "towelled"], tags: ["home", "body"], category: "object" },
      { word: "pillow", translation: "almohada", pos: "noun", ipa: "/ˈpɪloʊ/", definition: "a soft cushion used to support your head in bed", example: "I put a clean pillow on the bed.", exampleTranslation: "Pongo una almohada limpia en la cama.", synonyms: ["cushion", "headrest"], antonyms: [], collocations: ["soft pillow", "pillow cover"], wordFamily: ["pillow"], tags: ["home", "sleep"], category: "object" },
      { word: "lamp", translation: "lámpara", pos: "noun", ipa: "/læmp/", definition: "a device that gives light", example: "Turn on the lamp beside the sofa.", exampleTranslation: "Enciende la lámpara junto al sofá.", synonyms: ["light", "light fitting"], antonyms: [], collocations: ["desk lamp", "turn on a lamp"], wordFamily: ["lamp", "lamplight"], tags: ["home", "objects"], category: "device" },
      { word: "comb", translation: "peine", pos: "noun", ipa: "/koʊm/", definition: "a tool with narrow teeth used to arrange hair", example: "I keep a small comb in my bag.", exampleTranslation: "Guardo un peine pequeño en mi bolso.", synonyms: ["hair comb"], antonyms: [], collocations: ["use a comb", "wooden comb"], wordFamily: ["comb", "combed"], tags: ["home", "body"], category: "object" },
    ],
    u56: [
      { word: "ruler", translation: "regla", pos: "noun", ipa: "/ˈruːlər/", definition: "a straight tool used to measure or draw lines", example: "The ruler is next to my pencil.", exampleTranslation: "La regla está junto a mi lápiz.", synonyms: ["measuring stick"], antonyms: [], collocations: ["school ruler", "use a ruler"], wordFamily: ["rule", "ruler"], tags: ["school", "objects"], category: "object" },
      { word: "notebook", translation: "cuaderno", pos: "noun", ipa: "/ˈnoʊtbʊk/", definition: "a book of blank pages for writing notes", example: "I write new words in my notebook.", exampleTranslation: "Escribo palabras nuevas en mi cuaderno.", synonyms: ["exercise book", "notepad"], antonyms: [], collocations: ["school notebook", "open a notebook"], wordFamily: ["note", "notebook"], tags: ["school", "writing"], category: "object" },
      { word: "eraser", translation: "goma de borrar", pos: "noun", ipa: "/ɪˈreɪsər/", definition: "a small object used to remove pencil marks", example: "Use an eraser for this mark.", exampleTranslation: "Usa una goma de borrar para esta marca.", synonyms: ["rubber"], antonyms: [], collocations: ["pencil eraser", "use an eraser"], wordFamily: ["erase", "eraser", "erasable"], tags: ["school", "objects"], category: "object" },
      { word: "question", translation: "pregunta", pos: "noun", ipa: "/ˈkwestʃən/", definition: "words used to ask for information", example: "The student asks a question.", exampleTranslation: "El estudiante hace una pregunta.", synonyms: ["query", "inquiry"], antonyms: ["answer"], collocations: ["ask a question", "simple question"], wordFamily: ["question", "questioner", "questioning"], tags: ["school", "communication"], category: "communication" },
      { word: "scissors", translation: "tijeras", pos: "noun", ipa: "/ˈsɪzərz/", definition: "a tool with two sharp blades used for cutting", example: "Use the scissors to cut the paper.", exampleTranslation: "Usa las tijeras para cortar el papel.", synonyms: ["shears", "snips"], antonyms: [], collocations: ["pair of scissors", "sharp scissors"], wordFamily: ["scissor", "scissors"], tags: ["school", "objects"], category: "tool" },
      { word: "glue", translation: "pegamento", pos: "noun", ipa: "/ɡluː/", definition: "a substance used to stick things together", example: "Put some glue on the card.", exampleTranslation: "Pon un poco de pegamento en la tarjeta.", synonyms: ["adhesive", "paste"], antonyms: [], collocations: ["bottle of glue", "glue stick"], wordFamily: ["glue", "glued"], tags: ["school", "objects"], category: "material" },
      { word: "chalk", translation: "tiza", pos: "noun", ipa: "/tʃɔːk/", definition: "a soft white or coloured stick used for writing on a board", example: "The teacher wrote the word in chalk.", exampleTranslation: "El profesor escribió la palabra con tiza.", synonyms: ["chalk stick"], antonyms: [], collocations: ["piece of chalk", "chalkboard"], wordFamily: ["chalk", "chalky"], tags: ["school", "writing"], category: "material" },
      { word: "folder", translation: "carpeta", pos: "noun", ipa: "/ˈfoʊldər/", definition: "a cover used for keeping papers together", example: "Keep your homework in the green folder.", exampleTranslation: "Guarda tus deberes en la carpeta verde.", synonyms: ["file", "binder"], antonyms: [], collocations: ["school folder", "file folder"], wordFamily: ["fold", "folder", "folded"], tags: ["school", "writing"], category: "object" },
      { word: "marker", translation: "rotulador", pos: "noun", ipa: "/ˈmɑːrkər/", definition: "a pen with a thick tip used for writing or drawing", example: "Use a blue marker for the title.", exampleTranslation: "Usa un rotulador azul para el título.", synonyms: ["felt-tip", "highlighter"], antonyms: [], collocations: ["permanent marker", "marker pen"], wordFamily: ["mark", "marker", "marked"], tags: ["school", "writing"], category: "tool" },
      { word: "blackboard", translation: "pizarra", pos: "noun", ipa: "/ˈblækbɔːrd/", definition: "a dark board used by a teacher for writing", example: "The teacher writes the date on the blackboard.", exampleTranslation: "El profesor escribe la fecha en la pizarra.", synonyms: ["chalkboard", "board"], antonyms: [], collocations: ["write on the blackboard", "classroom blackboard"], wordFamily: ["black", "board", "blackboard"], tags: ["school", "writing"], category: "object" },
      { word: "backpack", translation: "mochila", pos: "noun", ipa: "/ˈbækpæk/", definition: "a bag carried on your back", example: "My backpack has two notebooks.", exampleTranslation: "Mi mochila tiene dos cuadernos.", synonyms: ["rucksack", "schoolbag"], antonyms: [], collocations: ["school backpack", "carry a backpack"], wordFamily: ["back", "pack", "backpack"], tags: ["school", "travel"], category: "container" },
    ],
  },
  A1: {
    u54: [
      { word: "destination", translation: "destino", pos: "noun", ipa: "/ˌdestɪˈneɪʃən/", definition: "the place where someone or something is going", example: "Our destination is the city centre.", exampleTranslation: "Nuestro destino es el centro de la ciudad.", synonyms: ["endpoint", "arrival point"], antonyms: ["departure"], collocations: ["final destination", "reach a destination"], wordFamily: ["destine", "destination"], tags: ["travel", "places"], category: "travel" },
      { word: "cancellation", translation: "cancelación", pos: "noun", ipa: "/ˌkænsəˈleɪʃən/", definition: "the act of stopping an event or service that was planned", example: "The airline sent a message about the flight cancellation.", exampleTranslation: "La aerolínea envió un mensaje sobre la cancelación del vuelo.", synonyms: ["call-off", "withdrawal"], antonyms: ["confirmation"], collocations: ["flight cancellation", "cancellation notice"], wordFamily: ["cancel", "cancellation", "cancelled"], tags: ["travel", "communication"], category: "event" },
      { word: "luggage", translation: "equipaje", pos: "noun", ipa: "/ˈlʌɡɪdʒ/", definition: "bags and cases carried when travelling", example: "Please keep your luggage with you.", exampleTranslation: "Mantén tu equipaje contigo, por favor.", synonyms: ["baggage", "bags"], antonyms: [], collocations: ["hand luggage", "collect luggage"], wordFamily: ["luggage"], tags: ["travel", "objects"], category: "travel" },
      { word: "journey", translation: "viaje", pos: "noun", ipa: "/ˈdʒɜːrni/", definition: "the act of travelling from one place to another", example: "The journey takes two hours by train.", exampleTranslation: "El viaje dura dos horas en tren.", synonyms: ["trip", "voyage"], antonyms: [], collocations: ["long journey", "journey home"], wordFamily: ["journey"], tags: ["travel", "time"], category: "travel" },
      { word: "carriage", translation: "vagón", pos: "noun", ipa: "/ˈkærɪdʒ/", definition: "one of the separate sections of a train", example: "The quiet carriage is at the front of the train.", exampleTranslation: "El vagón silencioso está en la parte delantera del tren.", synonyms: ["coach", "railcar"], antonyms: [], collocations: ["train carriage", "quiet carriage"], wordFamily: ["carry", "carriage"], tags: ["travel", "transport"], category: "transport" },
      { word: "passenger", translation: "pasajero", pos: "noun", ipa: "/ˈpæsɪndʒər/", definition: "a person travelling in a vehicle", example: "Every passenger must show a ticket.", exampleTranslation: "Cada pasajero debe mostrar un billete.", synonyms: ["traveller", "rider"], antonyms: ["driver"], collocations: ["train passenger", "passenger seat"], wordFamily: ["pass", "passenger"], tags: ["travel", "transport"], category: "person" },
      { word: "arrival", translation: "llegada", pos: "noun", ipa: "/əˈraɪvəl/", definition: "the act of reaching a place", example: "We will call you after our arrival.", exampleTranslation: "Te llamaremos después de nuestra llegada.", synonyms: ["coming", "entrance"], antonyms: ["departure"], collocations: ["arrival time", "arrival hall"], wordFamily: ["arrive", "arrival"], tags: ["travel", "time"], category: "event" },
      { word: "crossing", translation: "paso de peatones", pos: "noun", ipa: "/ˈkrɔːsɪŋ/", definition: "a place where people can cross a road safely", example: "Wait at the crossing until the light changes.", exampleTranslation: "Espera en el paso hasta que cambie el semáforo.", synonyms: ["crosswalk", "pedestrian crossing"], antonyms: [], collocations: ["road crossing", "use a crossing"], wordFamily: ["cross", "crossing"], tags: ["travel", "safety"], category: "place" },
    ],
    u55: [
      { word: "bandage", translation: "vendaje", pos: "noun", ipa: "/ˈbændɪdʒ/", definition: "a strip of material used to cover and protect a wound", example: "Put a clean bandage on the cut.", exampleTranslation: "Pon un vendaje limpio sobre el corte.", synonyms: ["dressing", "strip"], antonyms: [], collocations: ["clean bandage", "apply a bandage"], wordFamily: ["bandage", "bandaged"], tags: ["health", "body"], category: "medical object" },
      { word: "syrup", translation: "jarabe", pos: "noun", ipa: "/ˈsɪrəp/", definition: "a thick sweet liquid, often used as medicine", example: "The pharmacist recommended a cough syrup.", exampleTranslation: "El farmacéutico recomendó un jarabe para la tos.", synonyms: ["medicine", "liquid medicine"], antonyms: [], collocations: ["cough syrup", "a spoonful of syrup"], wordFamily: ["syrup"], tags: ["health", "medicine"], category: "medicine" },
      { word: "bruise", translation: "moretón", pos: "noun", ipa: "/bruːz/", definition: "a dark mark on the skin caused by an injury", example: "The bruise on my arm is getting lighter.", exampleTranslation: "El moretón de mi brazo se está aclarando.", synonyms: ["contusion", "mark"], antonyms: [], collocations: ["bad bruise", "bruise easily"], wordFamily: ["bruise", "bruised"], tags: ["health", "body"], category: "symptom" },
      { word: "symptom", translation: "síntoma", pos: "noun", ipa: "/ˈsɪmptəm/", definition: "a change in the body that shows an illness may be present", example: "A sore throat can be a symptom of a cold.", exampleTranslation: "El dolor de garganta puede ser un síntoma de un resfriado.", synonyms: ["sign", "indication"], antonyms: [], collocations: ["common symptom", "symptom of an illness"], wordFamily: ["symptom", "symptomatic"], tags: ["health", "body"], category: "health" },
      { word: "thermometer", translation: "termómetro", pos: "noun", ipa: "/θərˈmɑːmɪtər/", definition: "an instrument used to measure temperature", example: "The thermometer shows that I have a fever.", exampleTranslation: "El termómetro muestra que tengo fiebre.", synonyms: ["temperature gauge"], antonyms: [], collocations: ["digital thermometer", "use a thermometer"], wordFamily: ["thermal", "thermometer"], tags: ["health", "objects"], category: "medical tool" },
      { word: "pharmacy", translation: "farmacia", pos: "noun", ipa: "/ˈfɑːrməsi/", definition: "a shop or place where medicines are prepared and sold", example: "The pharmacy closes at six o'clock.", exampleTranslation: "La farmacia cierra a las seis.", synonyms: ["chemist", "drugstore"], antonyms: [], collocations: ["local pharmacy", "pharmacy counter"], wordFamily: ["pharmacist", "pharmacy"], tags: ["health", "places"], category: "place" },
      { word: "pill", translation: "pastilla", pos: "noun", ipa: "/pɪl/", definition: "a small piece of medicine that you swallow", example: "Take one pill after the meal.", exampleTranslation: "Toma una pastilla después de la comida.", synonyms: ["tablet", "medication"], antonyms: [], collocations: ["take a pill", "pain pill"], wordFamily: ["pill", "pills"], tags: ["health", "medicine"], category: "medicine" },
      { word: "treatment", translation: "tratamiento", pos: "noun", ipa: "/ˈtriːtmənt/", definition: "medical care given to help an illness or injury", example: "The doctor explained the treatment.", exampleTranslation: "El médico explicó el tratamiento.", synonyms: ["care", "therapy"], antonyms: [], collocations: ["medical treatment", "begin treatment"], wordFamily: ["treat", "treatment"], tags: ["health", "medicine"], category: "care" },
    ],
    u56: [
      { word: "reschedule", translation: "reprogramar", pos: "verb", ipa: "/ˌriːˈskedʒuːl/", definition: "to arrange an event for a different time", example: "Can we reschedule the appointment for Friday?", exampleTranslation: "¿Podemos reprogramar la cita para el viernes?", synonyms: ["rearrange", "rebook"], antonyms: [], collocations: ["reschedule a meeting", "reschedule an appointment"], wordFamily: ["schedule", "reschedule", "rescheduling"], tags: ["time", "communication"], category: "action" },
      { word: "reception", translation: "recepción", pos: "noun", ipa: "/rɪˈsepʃən/", definition: "the place where visitors are welcomed and helped", example: "Please ask at reception.", exampleTranslation: "Pregunta en recepción, por favor.", synonyms: ["front desk", "welcome desk"], antonyms: [], collocations: ["clinic reception", "reception desk"], wordFamily: ["receive", "reception", "receptionist"], tags: ["places", "communication"], category: "place" },
      { word: "afternoon", translation: "tarde", pos: "noun", ipa: "/ˌæftərˈnuːn/", definition: "the part of the day between midday and evening", example: "The clinic is open in the afternoon.", exampleTranslation: "La clínica está abierta por la tarde.", synonyms: ["after lunch"], antonyms: ["morning"], collocations: ["this afternoon", "afternoon appointment"], wordFamily: ["afternoon"], tags: ["time", "routine"], category: "time" },
      { word: "reminder", translation: "recordatorio", pos: "noun", ipa: "/rɪˈmaɪndər/", definition: "a message that helps you remember something", example: "The clinic sent a reminder by text.", exampleTranslation: "La clínica envió un recordatorio por mensaje.", synonyms: ["prompt", "notice"], antonyms: [], collocations: ["send a reminder", "appointment reminder"], wordFamily: ["remind", "reminder"], tags: ["time", "communication"], category: "message" },
      { word: "waiting room", translation: "sala de espera", pos: "noun", ipa: "/ˈweɪtɪŋ ruːm/", definition: "a room where people wait before an appointment", example: "Please sit in the waiting room.", exampleTranslation: "Siéntese en la sala de espera, por favor.", synonyms: ["reception area", "lobby"], antonyms: [], collocations: ["doctor's waiting room", "sit in the waiting room"], wordFamily: ["wait", "waiting"], tags: ["health", "places"], category: "place" },
      { word: "availability", translation: "disponibilidad", pos: "noun", ipa: "/əˌveɪləˈbɪləti/", definition: "the time when someone or something is free and ready to be used", example: "Please check the doctor's availability before booking.", exampleTranslation: "Comprueba la disponibilidad del médico antes de reservar.", synonyms: ["free time", "accessibility"], antonyms: ["unavailability"], collocations: ["check availability", "limited availability"], wordFamily: ["available", "availability"], tags: ["health", "time"], category: "planning" },
      { word: "patient", translation: "paciente", pos: "noun", ipa: "/ˈpeɪʃənt/", definition: "a person receiving medical care", example: "The patient is waiting to see the doctor.", exampleTranslation: "El paciente espera para ver al médico.", synonyms: ["medical patient", "client"], antonyms: [], collocations: ["hospital patient", "patient record"], wordFamily: ["patience", "patient"], tags: ["health", "people"], category: "person" },
      { word: "urgent", translation: "urgente", pos: "adjective", ipa: "/ˈɜːrdʒənt/", definition: "needing attention very soon", example: "The nurse marked the request as urgent.", exampleTranslation: "La enfermera marcó la solicitud como urgente.", synonyms: ["pressing", "immediate"], antonyms: ["routine", "optional"], collocations: ["urgent appointment", "urgent request"], wordFamily: ["urge", "urgent", "urgently"], tags: ["health", "time"], category: "priority" },
      { word: "booking", translation: "reserva", pos: "noun", ipa: "/ˈbʊkɪŋ/", definition: "an arrangement to have a service at a particular time", example: "I made a booking for Monday morning.", exampleTranslation: "Hice una reserva para el lunes por la mañana.", synonyms: ["reservation", "appointment"], antonyms: ["cancellation"], collocations: ["make a booking", "booking confirmation"], wordFamily: ["book", "booking"], tags: ["time", "communication"], category: "arrangement" },
      { word: "queue", translation: "cola", pos: "noun", ipa: "/kjuː/", definition: "a line of people waiting for something", example: "There was a long queue at the reception desk.", exampleTranslation: "Había una cola larga en la recepción.", synonyms: ["line", "waiting line"], antonyms: [], collocations: ["join a queue", "long queue"], wordFamily: ["queue", "queued"], tags: ["places", "time"], category: "group" },
    ],
  },
  A2: {
    u54: [
      { word: "landmark", translation: "monumento", pos: "noun", ipa: "/ˈlændmɑːrk/", definition: "a well-known place or building that helps people recognise a location", example: "The bridge is a famous city landmark.", exampleTranslation: "El puente es un monumento famoso de la ciudad.", synonyms: ["monument", "reference point"], antonyms: [], collocations: ["historic landmark", "famous landmark"], wordFamily: ["land", "landmark"], tags: ["travel", "places"], category: "place" },
      { word: "overnight", translation: "durante la noche", pos: "adverb", ipa: "/ˌoʊvərˈnaɪt/", definition: "during one night or from one evening until the next morning", example: "We took an overnight train to the coast.", exampleTranslation: "Tomamos un tren nocturno hasta la costa.", synonyms: ["at night", "night-long"], antonyms: ["during the day"], collocations: ["overnight stay", "overnight train"], wordFamily: ["night", "overnight"], tags: ["travel", "time"], category: "time" },
      { word: "hostel", translation: "albergue", pos: "noun", ipa: "/ˈhɑːstəl/", definition: "a cheap place where travellers can stay", example: "We booked a small hostel near the station.", exampleTranslation: "Reservamos un pequeño albergue cerca de la estación.", synonyms: ["youth hostel", "lodging"], antonyms: [], collocations: ["budget hostel", "stay in a hostel"], wordFamily: ["host", "hostel"], tags: ["travel", "places"], category: "accommodation" },
      { word: "guidebook", translation: "guía de viaje", pos: "noun", ipa: "/ˈɡaɪdbʊk/", definition: "a book with information for visitors to a place", example: "The guidebook recommends a quiet museum.", exampleTranslation: "La guía de viaje recomienda un museo tranquilo.", synonyms: ["travel guide", "handbook"], antonyms: [], collocations: ["travel guidebook", "read a guidebook"], wordFamily: ["guide", "guidebook"], tags: ["travel", "reading"], category: "book" },
      { word: "sightseeing", translation: "turismo", pos: "noun", ipa: "/ˈsaɪtsiːɪŋ/", definition: "the activity of visiting interesting places as a tourist", example: "We spent the afternoon sightseeing.", exampleTranslation: "Pasamos la tarde haciendo turismo.", synonyms: ["touring", "visiting"], antonyms: [], collocations: ["go sightseeing", "sightseeing tour"], wordFamily: ["sight", "sightseeing"], tags: ["travel", "leisure"], category: "activity" },
      { word: "travel insurance", translation: "seguro de viaje", pos: "noun", ipa: "/ˈtrævəl ɪnˌʃʊrəns/", definition: "insurance that covers some problems during a trip", example: "Travel insurance can cover lost luggage.", exampleTranslation: "El seguro de viaje puede cubrir el equipaje perdido.", synonyms: ["trip insurance", "cover"], antonyms: [], collocations: ["buy travel insurance", "travel insurance policy"], wordFamily: ["travel", "insure", "insurance"], tags: ["travel", "money"], category: "service" },
    ],
    u55: [
      { word: "concentrate", translation: "concentrarse", pos: "verb", ipa: "/ˈkɑːnsəntreɪt/", definition: "to give all your attention to one thing", example: "I concentrate better in a quiet room.", exampleTranslation: "Me concentro mejor en una habitación tranquila.", synonyms: ["focus", "pay attention"], antonyms: ["distract"], collocations: ["concentrate on a task", "concentrate fully"], wordFamily: ["concentrate", "concentration", "concentrated"], tags: ["learning", "thinking"], category: "mental action" },
      { word: "distraction", translation: "distracción", pos: "noun", ipa: "/dɪˈstrækʃən/", definition: "something that takes your attention away from what you are doing", example: "Put your phone away to avoid distraction.", exampleTranslation: "Guarda el teléfono para evitar distracciones.", synonyms: ["interruption", "diversion"], antonyms: ["focus", "concentration"], collocations: ["avoid distraction", "major distraction"], wordFamily: ["distract", "distraction", "distracted"], tags: ["learning", "routine"], category: "challenge" },
      { word: "memorise", translation: "memorizar", pos: "verb", ipa: "/ˈmeməraɪz/", definition: "to learn something so that you can remember it", example: "I use a story to memorise the new words.", exampleTranslation: "Uso una historia para memorizar las palabras nuevas.", synonyms: ["learn by heart", "remember"], antonyms: ["forget"], collocations: ["memorise a list", "memorise vocabulary"], wordFamily: ["memory", "memorise", "memorisation"], tags: ["learning", "memory"], category: "learning action" },
      { word: "revision", translation: "repaso", pos: "noun", ipa: "/rɪˈvɪʒən/", definition: "the activity of studying something again", example: "A short revision session helps before the test.", exampleTranslation: "Una sesión breve de repaso ayuda antes del examen.", synonyms: ["review", "study"], antonyms: [], collocations: ["revision session", "exam revision"], wordFamily: ["revise", "revision"], tags: ["learning", "routine"], category: "learning" },
      { word: "dictionary", translation: "diccionario", pos: "noun", ipa: "/ˈdɪkʃəneri/", definition: "a book or tool that explains the meanings of words", example: "I check the dictionary when a word is unfamiliar.", exampleTranslation: "Consulto el diccionario cuando una palabra no me resulta familiar.", synonyms: ["lexicon", "wordbook"], antonyms: [], collocations: ["online dictionary", "check a dictionary"], wordFamily: ["diction", "dictionary"], tags: ["learning", "reading"], category: "reference" },
      { word: "progress", translation: "progreso", pos: "noun", ipa: "/ˈprɑːɡres/", definition: "movement towards a better or more advanced state", example: "Daily practice shows steady progress.", exampleTranslation: "La práctica diaria muestra un progreso constante.", synonyms: ["development", "improvement"], antonyms: ["decline"], collocations: ["make progress", "steady progress"], wordFamily: ["progress", "progressive"], tags: ["learning", "goals"], category: "development" },
    ],
    u56: [
      { word: "browser", translation: "navegador", pos: "noun", ipa: "/ˈbraʊzər/", definition: "a program used to view websites", example: "Open the link in your browser.", exampleTranslation: "Abre el enlace en tu navegador.", synonyms: ["web browser"], antonyms: [], collocations: ["web browser", "browser window"], wordFamily: ["browse", "browser", "browsing"], tags: ["technology", "internet"], category: "software" },
      { word: "screen", translation: "pantalla", pos: "noun", ipa: "/skriːn/", definition: "the flat surface on a device that shows images and text", example: "The message appears on my screen.", exampleTranslation: "El mensaje aparece en mi pantalla.", synonyms: ["display", "monitor"], antonyms: [], collocations: ["phone screen", "screen size"], wordFamily: ["screen", "screening"], tags: ["technology", "devices"], category: "object" },
      { word: "secure", translation: "seguro", pos: "adjective", ipa: "/sɪˈkjʊər/", definition: "protected from danger, loss, or unwanted access", example: "Use a secure connection for online banking.", exampleTranslation: "Usa una conexión segura para la banca en línea.", synonyms: ["safe", "protected"], antonyms: ["unsafe", "vulnerable"], collocations: ["secure connection", "secure account"], wordFamily: ["secure", "security", "securely"], tags: ["technology", "safety"], category: "quality" },
      { word: "subscribe", translation: "suscribirse", pos: "verb", ipa: "/səbˈskraɪb/", definition: "to agree to receive a service or regular updates", example: "You can subscribe to the weekly newsletter.", exampleTranslation: "Puedes suscribirte al boletín semanal.", synonyms: ["sign up", "enrol"], antonyms: ["unsubscribe"], collocations: ["subscribe to a newsletter", "subscribe online"], wordFamily: ["subscribe", "subscriber", "subscription"], tags: ["technology", "communication"], category: "action" },
    ],
  },
  B1: {
    u54: [
      { word: "portfolio", translation: "portafolio", pos: "noun", ipa: "/pɔːrtˈfoʊlioʊ/", definition: "a collection of work that shows someone's skills or experience", example: "She brought a design portfolio to the interview.", exampleTranslation: "Llevó un portafolio de diseño a la entrevista.", synonyms: ["body of work", "collection"], antonyms: [], collocations: ["design portfolio", "professional portfolio"], wordFamily: ["portfolio"], tags: ["work", "education"], category: "career" },
      { word: "vacancy", translation: "puesto vacante", pos: "noun", ipa: "/ˈveɪkənsi/", definition: "a job that is available for someone to fill", example: "The company advertised a vacancy in sales.", exampleTranslation: "La empresa anunció un puesto vacante en ventas.", synonyms: ["opening", "available position"], antonyms: ["appointment"], collocations: ["job vacancy", "fill a vacancy"], wordFamily: ["vacant", "vacancy"], tags: ["work", "jobs"], category: "career" },
    ],
    u55: [
      { word: "clarify", translation: "aclarar", pos: "verb", ipa: "/ˈklærəfaɪ/", definition: "to make an idea or situation easier to understand", example: "Could you clarify the final requirement?", exampleTranslation: "¿Podrías aclarar el último requisito?", synonyms: ["explain", "clear up"], antonyms: ["confuse"], collocations: ["clarify a point", "clarify expectations"], wordFamily: ["clear", "clarify", "clarification"], tags: ["communication", "work"], category: "action" },
      { word: "stakeholder", translation: "parte interesada", pos: "noun", ipa: "/ˈsteɪkhoʊldər/", definition: "a person or group affected by a project or decision", example: "We invited every stakeholder to the planning meeting.", exampleTranslation: "Invitamos a todas las partes interesadas a la reunión de planificación.", synonyms: ["interested party", "participant"], antonyms: [], collocations: ["key stakeholder", "stakeholder interest"], wordFamily: ["stake", "stakeholder"], tags: ["work", "groups"], category: "person" },
    ],
    u56: [
      { word: "milestone", translation: "hito", pos: "noun", ipa: "/ˈmaɪlstoʊn/", definition: "an important stage or event in a process", example: "Finishing the prototype was an important milestone.", exampleTranslation: "Terminar el prototipo fue un hito importante.", synonyms: ["landmark", "turning point"], antonyms: [], collocations: ["major milestone", "reach a milestone"], wordFamily: ["milestone"], tags: ["work", "planning"], category: "progress" },
      { word: "negotiate", translation: "negociar", pos: "verb", ipa: "/nɪˈɡoʊʃieɪt/", definition: "to discuss in order to reach an agreement", example: "The teams negotiated a realistic deadline.", exampleTranslation: "Los equipos negociaron una fecha límite realista.", synonyms: ["bargain", "discuss"], antonyms: ["refuse"], collocations: ["negotiate a contract", "negotiate terms"], wordFamily: ["negotiate", "negotiation", "negotiator"], tags: ["work", "communication"], category: "action" },
      { word: "facilitate", translation: "facilitar", pos: "verb", ipa: "/fəˈsɪlɪteɪt/", definition: "to make an action or process easier", example: "The shared document facilitated collaboration.", exampleTranslation: "El documento compartido facilitó la colaboración.", synonyms: ["enable", "assist"], antonyms: ["hinder", "obstruct"], collocations: ["facilitate discussion", "facilitate learning"], wordFamily: ["facilitate", "facilitation", "facilitator"], tags: ["work", "communication"], category: "action" },
      { word: "efficient", translation: "eficiente", pos: "adjective", ipa: "/ɪˈfɪʃənt/", definition: "working well without wasting time or resources", example: "The new process is more efficient.", exampleTranslation: "El nuevo proceso es más eficiente.", synonyms: ["effective", "productive"], antonyms: ["inefficient", "wasteful"], collocations: ["efficient system", "work efficiently"], wordFamily: ["efficiency", "efficient", "efficiently"], tags: ["work", "quality"], category: "quality" },
    ],
  },
  B2: {
    u54: [
      { word: "inflation", translation: "inflación", pos: "noun", ipa: "/ɪnˈfleɪʃən/", definition: "a general rise in prices that reduces the value of money", example: "High inflation makes everyday goods more expensive.", exampleTranslation: "La inflación alta encarece los productos cotidianos.", synonyms: ["price rise", "rising prices"], antonyms: ["deflation"], collocations: ["high inflation", "control inflation"], wordFamily: ["inflate", "inflation", "inflationary"], tags: ["economy", "money"], category: "economy" },
      { word: "revenue", translation: "ingresos", pos: "noun", ipa: "/ˈrevənuː/", definition: "money received by a business or organisation from its activities", example: "Online sales increased the company's revenue.", exampleTranslation: "Las ventas en línea aumentaron los ingresos de la empresa.", synonyms: ["income", "turnover"], antonyms: ["expenditure"], collocations: ["annual revenue", "generate revenue"], wordFamily: ["revenue"], tags: ["economy", "business"], category: "finance" },
    ],
    u55: [
      { word: "incentive", translation: "incentivo", pos: "noun", ipa: "/ɪnˈsentɪv/", definition: "something that encourages a person to act in a particular way", example: "The discount is an incentive to buy early.", exampleTranslation: "El descuento es un incentivo para comprar pronto.", synonyms: ["motivation", "encouragement"], antonyms: ["deterrent"], collocations: ["financial incentive", "offer an incentive"], wordFamily: ["incentivise", "incentive"], tags: ["economy", "work"], category: "motivation" },
      { word: "compliance", translation: "cumplimiento", pos: "noun", ipa: "/kəmˈplaɪəns/", definition: "the act of following a rule, law, or request", example: "The audit checks compliance with safety regulations.", exampleTranslation: "La auditoría comprueba el cumplimiento de las normas de seguridad.", synonyms: ["obedience", "conformity"], antonyms: ["defiance"], collocations: ["regulatory compliance", "ensure compliance"], wordFamily: ["comply", "compliance", "compliant"], tags: ["law", "business"], category: "policy" },
    ],
    u56: [
      { word: "generalisability", translation: "generalización", pos: "noun", ipa: "/ˌdʒenərəlaɪzəˈbɪləti/", definition: "the extent to which a study's results apply beyond its sample", example: "The diverse sample improves the generalisability of the findings.", exampleTranslation: "La muestra diversa mejora la generalización de los resultados.", synonyms: ["applicability", "transferability"], antonyms: [], collocations: ["limited generalisability", "assess generalisability"], wordFamily: ["generalise", "generalisation", "generalisable"], tags: ["science", "research"], category: "quality" },
      { word: "robustness", translation: "solidez", pos: "noun", ipa: "/ˈroʊbʌstnəs/", definition: "the ability to remain reliable under different conditions", example: "The researchers tested the robustness of the result.", exampleTranslation: "Los investigadores comprobaron la solidez del resultado.", synonyms: ["reliability", "strength"], antonyms: ["fragility"], collocations: ["test robustness", "robustness check"], wordFamily: ["robust", "robustness"], tags: ["science", "thinking"], category: "quality" },
      { word: "dataset", translation: "conjunto de datos", pos: "noun", ipa: "/ˈdeɪtəset/", definition: "a structured collection of information used for analysis", example: "The dataset contains results from three surveys.", exampleTranslation: "El conjunto de datos contiene resultados de tres encuestas.", synonyms: ["data set", "data collection"], antonyms: [], collocations: ["large dataset", "analyse a dataset"], wordFamily: ["data", "dataset"], tags: ["science", "data"], category: "research" },
      { word: "finding", translation: "hallazgo", pos: "noun", ipa: "/ˈfaɪndɪŋ/", definition: "a result or conclusion discovered through research", example: "The main finding was unexpected.", exampleTranslation: "El hallazgo principal fue inesperado.", synonyms: ["result", "discovery"], antonyms: [], collocations: ["key finding", "research finding"], wordFamily: ["find", "finding"], tags: ["science", "research"], category: "result" },
    ],
  },
  C1: {
    u54: [
      { word: "diplomatic", translation: "diplomático", pos: "adjective", ipa: "/ˌdɪpləˈmætɪk/", definition: "connected with relations between countries or careful communication", example: "The minister used diplomatic language during the meeting.", exampleTranslation: "El ministro utilizó un lenguaje diplomático durante la reunión.", synonyms: ["tactful", "international"], antonyms: ["undiplomatic"], collocations: ["diplomatic relations", "diplomatic response"], wordFamily: ["diplomat", "diplomatic", "diplomacy"], tags: ["politics", "communication"], category: "quality" },
      { word: "coalition", translation: "coalición", pos: "noun", ipa: "/ˌkoʊəˈlɪʃən/", definition: "a temporary alliance of people, groups, or countries", example: "Several parties formed a coalition government.", exampleTranslation: "Varios partidos formaron un gobierno de coalición.", synonyms: ["alliance", "partnership"], antonyms: ["opposition"], collocations: ["coalition government", "form a coalition"], wordFamily: ["coalition"], tags: ["politics", "society"], category: "governance" },
    ],
    u55: [
      { word: "questionnaire", translation: "cuestionario", pos: "noun", ipa: "/ˌkwestʃəˈner/", definition: "a written set of questions used to collect information", example: "The researchers sent a questionnaire to every participant.", exampleTranslation: "Los investigadores enviaron un cuestionario a cada participante.", synonyms: ["survey", "form"], antonyms: [], collocations: ["research questionnaire", "complete a questionnaire"], wordFamily: ["question", "questionnaire", "questioning"], tags: ["research", "communication"], category: "research" },
      { word: "reliability", translation: "fiabilidad", pos: "noun", ipa: "/rɪˌlaɪəˈbɪləti/", definition: "the quality of being dependable and consistent", example: "The study discusses the reliability of its measurements.", exampleTranslation: "El estudio analiza la fiabilidad de sus mediciones.", synonyms: ["dependability", "consistency"], antonyms: ["unreliability"], collocations: ["test reliability", "measurement reliability"], wordFamily: ["rely", "reliable", "reliability"], tags: ["research", "quality"], category: "quality" },
    ],
    u56: [
      { word: "verification", translation: "verificación", pos: "noun", ipa: "/ˌverɪfɪˈkeɪʃən/", definition: "the process of checking that information is accurate", example: "The claim requires independent verification.", exampleTranslation: "La afirmación requiere una verificación independiente.", synonyms: ["confirmation", "validation"], antonyms: [], collocations: ["fact verification", "independent verification"], wordFamily: ["verify", "verification"], tags: ["media", "research"], category: "process" },
      { word: "allegation", translation: "acusación", pos: "noun", ipa: "/ˌæləˈɡeɪʃən/", definition: "a claim that someone has done something wrong, not yet proved", example: "The newspaper reported the allegation cautiously.", exampleTranslation: "El periódico informó de la acusación con cautela.", synonyms: ["claim", "accusation"], antonyms: [], collocations: ["serious allegation", "deny an allegation"], wordFamily: ["allege", "allegation"], tags: ["media", "law"], category: "claim" },
      { word: "impartial", translation: "imparcial", pos: "adjective", ipa: "/ɪmˈpɑːrʃəl/", definition: "not supporting one side more than another", example: "A credible report should be accurate and impartial.", exampleTranslation: "Un informe creíble debe ser preciso e imparcial.", synonyms: ["neutral", "unbiased"], antonyms: ["partial", "biased"], collocations: ["impartial analysis", "remain impartial"], wordFamily: ["part", "partial", "impartiality"], tags: ["media", "ethics"], category: "quality" },
      { word: "transparency", translation: "transparencia", pos: "noun", ipa: "/trænsˈperənsi/", definition: "the practice of making processes and information open to inspection", example: "Transparency helps readers evaluate a source.", exampleTranslation: "La transparencia ayuda a los lectores a evaluar una fuente.", synonyms: ["openness", "clarity"], antonyms: ["secrecy", "opacity"], collocations: ["editorial transparency", "greater transparency"], wordFamily: ["transparent", "transparency"], tags: ["media", "ethics"], category: "principle" },
    ],
  },
  C2: {
    u54: [
      { word: "paradox", translation: "paradoja", pos: "noun", ipa: "/ˈpærədɑːks/", definition: "a statement or situation that seems contradictory but may contain a truth", example: "The paradox challenges a simple explanation.", exampleTranslation: "La paradoja desafía una explicación sencilla.", synonyms: ["contradiction", "puzzle"], antonyms: ["consistency"], collocations: ["apparent paradox", "logical paradox"], wordFamily: ["paradox", "paradoxical"], tags: ["philosophy", "thinking"], category: "reasoning" },
      { word: "axiom", translation: "axioma", pos: "noun", ipa: "/ˈæksiəm/", definition: "a principle accepted as true and used as a basis for reasoning", example: "The theory begins with a simple axiom.", exampleTranslation: "La teoría comienza con un axioma sencillo.", synonyms: ["principle", "self-evident truth"], antonyms: ["hypothesis"], collocations: ["fundamental axiom", "accept an axiom"], wordFamily: ["axiom", "axiomatic"], tags: ["philosophy", "logic"], category: "principle" },
    ],
    u55: [
      { word: "incongruity", translation: "incongruencia", pos: "noun", ipa: "/ˌɪnkənˈɡruːəti/", definition: "a lack of harmony or agreement between things", example: "The incongruity between the words and the action was striking.", exampleTranslation: "La incongruencia entre las palabras y la acción era llamativa.", synonyms: ["mismatch", "inconsistency"], antonyms: ["harmony"], collocations: ["striking incongruity", "notice an incongruity"], wordFamily: ["congruent", "incongruity"], tags: ["rhetoric", "thinking"], category: "analysis" },
      { word: "counterargument", translation: "contraargumento", pos: "noun", ipa: "/ˌkaʊntərˈɑːrɡjəmənt/", definition: "an argument made to oppose or challenge another argument", example: "The essay presents a strong counterargument.", exampleTranslation: "El ensayo presenta un contraargumento sólido.", synonyms: ["rebuttal", "objection"], antonyms: ["supporting argument"], collocations: ["address a counterargument", "strong counterargument"], wordFamily: ["argue", "argument", "counterargument"], tags: ["rhetoric", "writing"], category: "argument" },
    ],
    u56: [
      { word: "deixis", translation: "deixis", pos: "noun", ipa: "/ˈdeɪksɪs/", definition: "the use of words whose meaning depends on the situation or speaker", example: "Words such as 'here' and 'now' are examples of deixis.", exampleTranslation: "Palabras como «aquí» y «ahora» son ejemplos de deixis.", synonyms: ["indexical reference", "contextual reference"], antonyms: [], collocations: ["spatial deixis", "temporal deixis"], wordFamily: ["deictic", "deixis"], tags: ["linguistics", "pragmatics"], category: "meaning" },
      { word: "presuppose", translation: "presuponer", pos: "verb", ipa: "/ˌpriːsəˈpoʊz/", definition: "to assume that something is true before it is proved", example: "The argument presupposes that the data is complete.", exampleTranslation: "El argumento presupone que los datos están completos.", synonyms: ["assume", "take for granted"], antonyms: ["question"], collocations: ["presuppose a condition", "presuppose knowledge"], wordFamily: ["presuppose", "presupposition"], tags: ["linguistics", "thinking"], category: "reasoning" },
      { word: "entailment", translation: "implicación lógica", pos: "noun", ipa: "/ɪnˈteɪlmənt/", definition: "a meaning or conclusion that must follow from a statement", example: "The entailment depends on the meaning of the verb.", exampleTranslation: "La implicación lógica depende del significado del verbo.", synonyms: ["implication", "consequence"], antonyms: [], collocations: ["logical entailment", "semantic entailment"], wordFamily: ["entail", "entailment"], tags: ["linguistics", "logic"], category: "meaning" },
      { word: "polysemy", translation: "polisemia", pos: "noun", ipa: "/pəˈlɪsəmi/", definition: "the fact that one word has several related meanings", example: "The polysemy of the word makes the sentence interesting.", exampleTranslation: "La polisemia de la palabra hace interesante la oración.", synonyms: ["multiple meaning", "semantic variation"], antonyms: [], collocations: ["lexical polysemy", "polysemy in language"], wordFamily: ["polysemous", "polysemy"], tags: ["linguistics", "semantics"], category: "meaning" },
    ],
  },
};
