import type { VocabularyItem } from "./learn-data";

type ReviewedSeed = {
  word: string;
  translation: string;
  pos: string;
  ipa: string;
  definition: string;
  example: string;
  exampleTranslation: string;
  category: string;
  tags: string[];
  synonyms?: string[];
  antonyms?: string[];
  collocations?: string[];
  wordFamily?: string[];
};

const reviewed = (seed: ReviewedSeed): VocabularyItem => ({
  ...seed,
  translationLang: "ar",
  synonyms: seed.synonyms ?? [seed.word],
  antonyms: seed.antonyms ?? [],
  collocations: seed.collocations ?? [seed.word],
  wordFamily: seed.wordFamily ?? [seed.word],
});

/**
 * Reviewed English enrichment batch based on the A1-C1 reference PDFs.
 *
 * These are deliberately kept separate from the legacy enrichment bank so that
 * provenance and review status remain visible. Entries are appended to existing
 * units by curriculum-en.ts; no unit, lesson, or existing record is replaced.
 * Arabic is used as the explicit source translation language for this batch so
 * it does not introduce another legacy Spanish translation.
 */
export const ENGLISH_REVIEWED_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  A1: {    u54: [
      {
        word: "about",
        translation: "حول / تقريبًا",
        translationLang: "ar",
        pos: "preposition",
        ipa: "/əˈbaʊt/",
        definition: "used to describe the subject of something or an approximate amount",
        example: "We talked about the new bus route.",
        exampleTranslation: "تحدثنا عن مسار الحافلة الجديد.",
        synonyms: ["concerning", "approximately"],
        antonyms: [],
        collocations: ["talk about a route", "about ten minutes"],
        wordFamily: ["about"],
        tags: ["transport", "communication"],
        category: "preposition",
      },
      {
        word: "above",
        translation: "فوق / أعلى من",
        translationLang: "ar",
        pos: "preposition",
        ipa: "/əˈbʌv/",
        definition: "in or to a higher position than something else",
        example: "The departure board is above the ticket office.",
        exampleTranslation: "لوحة المغادرة فوق مكتب التذاكر.",
        synonyms: ["over", "higher than"],
        antonyms: ["below"],
        collocations: ["above the door", "above the platform"],
        wordFamily: ["above"],
        tags: ["transport", "places"],
        category: "preposition",
      },
      {
        word: "across",
        translation: "عبر / على الجانب المقابل",
        translationLang: "ar",
        pos: "preposition",
        ipa: "/əˈkrɔːs/",
        definition: "from one side of a place to the other side",
        example: "The bus stop is across the road.",
        exampleTranslation: "موقف الحافلة على الجانب الآخر من الطريق.",
        synonyms: ["over", "from side to side"],
        antonyms: [],
        collocations: ["across the road", "walk across the street"],
        wordFamily: ["across"],
        tags: ["transport", "directions"],
        category: "preposition",
      },
    ],
  },
  A2: {
    u55: [
      {
        word: "ability",
        translation: "قدرة / مهارة",
        translationLang: "ar",
        pos: "noun",
        ipa: "/əˈbɪləti/",
        definition: "the skill or power to do something",
        example: "Regular practice can improve your ability to remember words.",
        exampleTranslation: "يمكن أن تحسن الممارسة المنتظمة قدرتك على تذكر الكلمات.",
        synonyms: ["skill", "capacity"],
        antonyms: ["inability"],
        collocations: ["develop an ability", "ability to learn"],
        wordFamily: ["able", "ability", "unable"],
        tags: ["learning", "skills"],
        category: "learning",
      },
      {
        word: "accept",
        translation: "يقبل",
        translationLang: "ar",
        pos: "verb",
        ipa: "/əkˈsept/",
        definition: "to agree to take or receive something, or to agree that something is true",
        example: "You should accept helpful feedback from your teacher.",
        exampleTranslation: "ينبغي أن تقبل الملاحظات المفيدة من معلمك.",
        synonyms: ["agree to", "receive"],
        antonyms: ["refuse", "reject"],
        collocations: ["accept advice", "accept an invitation"],
        wordFamily: ["accept", "acceptable", "acceptance"],
        tags: ["learning", "communication"],
        category: "action",
      },
      {
        word: "achieve",
        translation: "يحقق",
        translationLang: "ar",
        pos: "verb",
        ipa: "/əˈtʃiːv/",
        definition: "to succeed in doing or getting something after effort",
        example: "She achieved her learning goal after several weeks of practice.",
        exampleTranslation: "حققت هدفها التعليمي بعد عدة أسابيع من التدريب.",
        synonyms: ["accomplish", "reach"],
        antonyms: ["fail"],
        collocations: ["achieve a goal", "achieve success"],
        wordFamily: ["achieve", "achievement", "achievable"],
        tags: ["learning", "goals"],
        category: "progress",
      },
    ],
    u56: [
    ],
  },
  B1: {
    u52: [
      reviewed({ word: "newsroom", translation: "غرفة الأخبار", pos: "noun", ipa: "/ˈnuːzruːm/", definition: "the office or department where news is collected, checked, and prepared", example: "The newsroom checked the eyewitness account before publishing it.", exampleTranslation: "تحققت غرفة الأخبار من رواية الشاهد قبل نشرها.", category: "news and media", tags: ["media", "work"], synonyms: ["news office", "editorial department"] }),
      reviewed({ word: "readership", translation: "جمهور القراء", pos: "noun", ipa: "/ˈriːdərʃɪp/", definition: "the people who regularly read a particular publication or source", example: "The magazine increased its readership with clearer explanations.", exampleTranslation: "زادت المجلة جمهور قرائها بفضل شروحات أوضح.", category: "news and media", tags: ["media", "communication"], synonyms: ["readers", "audience"] }),
      reviewed({ word: "caption", translation: "تعليق توضيحي للصورة", pos: "noun", ipa: "/ˈkæpʃən/", definition: "a short text that explains a picture, chart, or video", example: "The caption identified where and when the photograph was taken.", exampleTranslation: "حدد التعليق التوضيحي للصورة مكان التقاطها ووقته.", category: "news and media", tags: ["media", "writing"], synonyms: ["description", "label"] }),
      reviewed({ word: "eyewitness", translation: "شاهد عيان", pos: "noun", ipa: "/ˈaɪwɪtnəs/", definition: "a person who saw an event happen", example: "An eyewitness described the sequence of events to the reporter.", exampleTranslation: "وصف شاهد عيان تسلسل الأحداث للصحفي.", category: "news and media", tags: ["media", "evidence"], synonyms: ["witness", "observer"] }),
      reviewed({ word: "coverage", translation: "تغطية إعلامية", pos: "noun", ipa: "/ˈkʌvərɪdʒ/", definition: "the reporting of an event or subject by the media", example: "The election received extensive coverage across several channels.", exampleTranslation: "حظيت الانتخابات بتغطية واسعة عبر قنوات عدة.", category: "news and media", tags: ["media", "society"], synonyms: ["reporting", "news treatment"] }),
      reviewed({ word: "circulation", translation: "توزيع / انتشار مطبوعة", pos: "noun", ipa: "/ˌsɜːrkjəˈleɪʃən/", definition: "the number of copies of a publication distributed to readers", example: "The newspaper reported a rise in circulation this year.", exampleTranslation: "أفادت الصحيفة بارتفاع توزيعها هذا العام.", category: "news and media", tags: ["media", "business"], synonyms: ["distribution", "reach"] }),
      reviewed({ word: "press release", translation: "بيان صحفي", pos: "noun", ipa: "/ˈpres rɪliːs/", definition: "an official written statement sent to journalists", example: "The organisation issued a press release after the investigation.", exampleTranslation: "أصدرت المنظمة بيانًا صحفيًا بعد التحقيق.", category: "news and media", tags: ["media", "communication"], synonyms: ["official statement", "media release"] }),
      reviewed({ word: "fact-checker", translation: "مدقق حقائق", pos: "noun", ipa: "/ˈfækt ˌtʃekər/", definition: "a person who checks whether public claims are supported by evidence", example: "The fact-checker contacted the source before rating the claim.", exampleTranslation: "تواصل مدقق الحقائق مع المصدر قبل تقييم الادعاء.", category: "news and media", tags: ["media", "evidence"], synonyms: ["verification editor", "claim reviewer"] }),
    ],
    u53: [
      reviewed({ word: "accountability", translation: "مساءلة", pos: "noun", ipa: "/əˌkaʊntəˈbɪləti/", definition: "the responsibility to explain actions and accept their results", example: "Clear accountability helped the project recover from the delay.", exampleTranslation: "ساعدت المساءلة الواضحة المشروع على التعافي من التأخير.", category: "workplace collaboration", tags: ["work", "responsibility"], synonyms: ["responsibility", "answerability"] }),
      reviewed({ word: "initiative", translation: "مبادرة", pos: "noun", ipa: "/ɪˈnɪʃətɪv/", definition: "the ability and willingness to act without waiting to be told what to do", example: "Her initiative improved communication between the two teams.", exampleTranslation: "حسّنت مبادرتها التواصل بين الفريقين.", category: "workplace collaboration", tags: ["work", "leadership"], synonyms: ["enterprise", "independence"] }),
      reviewed({ word: "reliability", translation: "موثوقية", pos: "noun", ipa: "/rɪˌlaɪəˈbɪləti/", definition: "the quality of being dependable and consistent", example: "The team valued his reliability during the busiest weeks.", exampleTranslation: "قدّر الفريق موثوقيته خلال أكثر الأسابيع ازدحامًا.", category: "workplace collaboration", tags: ["work", "performance"], synonyms: ["dependability", "consistency"] }),
      reviewed({ word: "mentoring", translation: "إرشاد مهني", pos: "noun", ipa: "/ˈmentərɪŋ/", definition: "the activity of guiding and supporting a less experienced colleague", example: "Mentoring helped the new employee understand the team’s workflow.", exampleTranslation: "ساعد الإرشاد المهني الموظف الجديد على فهم سير عمل الفريق.", category: "workplace collaboration", tags: ["work", "learning"], synonyms: ["coaching", "guidance"] }),
      reviewed({ word: "ownership", translation: "تحمل المسؤولية", pos: "noun", ipa: "/ˈoʊnərʃɪp/", definition: "personal responsibility for completing or improving something", example: "Taking ownership of the error allowed the team to fix it quickly.", exampleTranslation: "أدى تحمل المسؤولية عن الخطأ إلى إصلاحه بسرعة.", category: "workplace collaboration", tags: ["work", "responsibility"], synonyms: ["responsibility", "commitment"] }),
      reviewed({ word: "workflow", translation: "سير العمل", pos: "noun", ipa: "/ˈwɜːrkfloʊ/", definition: "the sequence of tasks through which work is completed", example: "The revised workflow removed an unnecessary approval step.", exampleTranslation: "أزال سير العمل المعدل خطوة موافقة غير ضرورية.", category: "workplace collaboration", tags: ["work", "organisation"], synonyms: ["process", "work sequence"] }),
      reviewed({ word: "reciprocity", translation: "تبادلية", pos: "noun", ipa: "/ˌresɪˈprɑːsəti/", definition: "a relationship in which people provide similar help or benefits to each other", example: "Reciprocity strengthened trust between the partner organisations.", exampleTranslation: "عززت التبادلية الثقة بين المنظمتين الشريكتين.", category: "workplace collaboration", tags: ["work", "relationships"], synonyms: ["mutual exchange", "give-and-take"] }),
      reviewed({ word: "role clarity", translation: "وضوح الأدوار", pos: "noun", ipa: "/ˈroʊl ˌklærəti/", definition: "a clear understanding of what each person is expected to do", example: "Role clarity prevented two colleagues from working on the same task.", exampleTranslation: "منع وضوح الأدوار زميلين من العمل على المهمة نفسها.", category: "workplace collaboration", tags: ["work", "organisation"], synonyms: ["clear responsibilities", "role definition"] }),
    ],
    u56: [
      reviewed({ word: "empathy", translation: "تعاطف", pos: "noun", ipa: "/ˈempəθi/", definition: "the ability to understand and share another person’s feelings", example: "Empathy helps a team respond well when a colleague is under pressure.", exampleTranslation: "يساعد التعاطف الفريق على الاستجابة جيدًا عندما يكون زميل تحت الضغط.", category: "teamwork", tags: ["work", "relationships"], synonyms: ["understanding", "compassion"] }),
      reviewed({ word: "cohesion", translation: "تماسك", pos: "noun", ipa: "/koʊˈhiːʒən/", definition: "the quality of forming a united and effective group", example: "Shared goals improved cohesion across the department.", exampleTranslation: "حسّنت الأهداف المشتركة تماسك القسم.", category: "teamwork", tags: ["work", "relationships"], synonyms: ["unity", "solidarity"] }),
      reviewed({ word: "interdependence", translation: "اعتماد متبادل", pos: "noun", ipa: "/ˌɪntərdɪˈpendəns/", definition: "a situation in which people or groups depend on one another", example: "The project showed the interdependence of design and engineering.", exampleTranslation: "أظهر المشروع الاعتماد المتبادل بين التصميم والهندسة.", category: "teamwork", tags: ["work", "collaboration"], synonyms: ["mutual dependence", "connectedness"] }),
      reviewed({ word: "constructive", translation: "بنّاء", pos: "adjective", ipa: "/kənˈstrʌktɪv/", definition: "useful and intended to improve a situation rather than simply criticise it", example: "The manager gave constructive advice after the presentation.", exampleTranslation: "قدم المدير نصيحة بناءة بعد العرض.", category: "teamwork", tags: ["work", "communication"], synonyms: ["helpful", "productive"], antonyms: ["destructive"] }),
      reviewed({ word: "conflict resolution", translation: "حل النزاعات", pos: "noun", ipa: "/ˈkɑːnflɪkt ˌrezəˈluːʃən/", definition: "the process of addressing disagreement and reaching a workable solution", example: "The training focused on conflict resolution between departments.", exampleTranslation: "ركز التدريب على حل النزاعات بين الأقسام.", category: "teamwork", tags: ["work", "communication"], synonyms: ["dispute settlement", "mediation"] }),
      reviewed({ word: "team charter", translation: "ميثاق الفريق", pos: "noun", ipa: "/ˈtiːm ˌtʃɑːrtər/", definition: "an agreement that sets out a team’s goals, roles, and ways of working", example: "The team charter explained how decisions would be made.", exampleTranslation: "وضح ميثاق الفريق كيفية اتخاذ القرارات.", category: "teamwork", tags: ["work", "planning"], synonyms: ["team agreement", "working agreement"] }),
      reviewed({ word: "adaptability", translation: "قدرة على التكيف", pos: "noun", ipa: "/əˌdæptəˈbɪləti/", definition: "the ability to change effectively in response to new conditions", example: "Adaptability is essential when a project changes direction.", exampleTranslation: "تُعد قدرة التكيف أساسية عندما يغير المشروع اتجاهه.", category: "teamwork", tags: ["work", "change"], synonyms: ["flexibility", "versatility"] }),
      reviewed({ word: "peer support", translation: "دعم الزملاء", pos: "noun", ipa: "/ˈpɪr səˌpɔːrt/", definition: "help and encouragement provided by people with similar roles or experience", example: "Peer support helped the trainee handle difficult customer calls.", exampleTranslation: "ساعد دعم الزملاء المتدرب على التعامل مع مكالمات العملاء الصعبة.", category: "teamwork", tags: ["work", "learning"], synonyms: ["colleague support", "mutual assistance"] }),
    ],
        u57: [
      reviewed({ word: "workaround", translation: "حل بديل مؤقت", pos: "noun", ipa: "/ˈwɜːrkəraʊnd/", definition: "a temporary method of dealing with a problem when the ideal solution is unavailable", example: "We found a workaround while the software was being repaired.", exampleTranslation: "وجدنا حلًا بديلًا مؤقتًا أثناء إصلاح البرنامج.", category: "problem solving", tags: ["work", "solutions"], synonyms: ["alternative", "temporary fix"] }),
      reviewed({ word: "setback", translation: "انتكاسة / عائق", pos: "noun", ipa: "/ˈsetbæk/", definition: "a problem that delays or prevents progress", example: "The cancelled shipment was a setback, but the team adapted.", exampleTranslation: "كانت الشحنة الملغاة انتكاسة، لكن الفريق تكيّف.", category: "progress", tags: ["work", "challenges"], synonyms: ["obstacle", "delay"], antonyms: ["advance"] }),
      reviewed({ word: "prioritise", translation: "يحدد الأولويات", pos: "verb", ipa: "/praɪˈɔːrətaɪz/", definition: "to decide which tasks or needs are most important", example: "We must prioritise urgent repairs before routine upgrades.", exampleTranslation: "يجب أن نحدد أولوية الإصلاحات العاجلة قبل التحسينات الروتينية.", category: "planning", tags: ["work", "decisions"], synonyms: ["rank", "organise"] }),
      reviewed({ word: "misconception", translation: "مفهوم خاطئ", pos: "noun", ipa: "/ˌmɪskənˈsepʃən/", definition: "an idea that is wrong because it is based on a misunderstanding", example: "The demonstration corrected a common misconception about the device.", exampleTranslation: "صحح العرض مفهومًا خاطئًا شائعًا عن الجهاز.", category: "thinking", tags: ["learning", "communication"], synonyms: ["false belief", "misunderstanding"] }),
      reviewed({ word: "persistence", translation: "المثابرة", pos: "noun", ipa: "/pərˈsɪstəns/", definition: "continued effort despite difficulty or delay", example: "Her persistence helped the team solve the complex fault.", exampleTranslation: "ساعدت مثابرتها الفريق على حل العطل المعقد.", category: "personal growth", tags: ["work", "learning"], synonyms: ["determination", "perseverance"], antonyms: ["giving up"] }),
      reviewed({ word: "reassess", translation: "يعيد التقييم", pos: "verb", ipa: "/ˌriːəˈses/", definition: "to consider a situation again in order to make a better judgement", example: "After the test failed, we reassessed the original plan.", exampleTranslation: "بعد فشل الاختبار، أعدنا تقييم الخطة الأصلية.", category: "analysis", tags: ["thinking", "planning"], synonyms: ["review", "reevaluate"] }),
      reviewed({ word: "contingency", translation: "خطة طوارئ / احتمال", pos: "noun", ipa: "/kənˈtɪndʒənsi/", definition: "a possible future event and a plan for dealing with it", example: "The project includes a contingency for further delays.", exampleTranslation: "يتضمن المشروع خطة طوارئ لمزيد من التأخير.", category: "planning", tags: ["work", "risk"], synonyms: ["backup plan", "possibility"] }),
    ],
    u58: [
      reviewed({ word: "alignment", translation: "توافق / مواءمة", pos: "noun", ipa: "/əˈlaɪnmənt/", definition: "a shared understanding of aims, priorities, or decisions", example: "The workshop created alignment across the project teams.", exampleTranslation: "أنشأت ورشة العمل توافقًا بين فرق المشروع.", category: "teamwork", tags: ["work", "collaboration"], synonyms: ["agreement", "coordination"] }),
      reviewed({ word: "rapport", translation: "ألفة / انسجام", pos: "noun", ipa: "/ræˈpɔːr/", definition: "a friendly and trusting relationship that supports communication", example: "The supervisor built rapport with the new team.", exampleTranslation: "بنى المشرف علاقة من الألفة مع الفريق الجديد.", category: "relationships", tags: ["work", "communication"], synonyms: ["connection", "understanding"], antonyms: ["tension"] }),
      reviewed({ word: "inclusive", translation: "شامل", pos: "adjective", ipa: "/ɪnˈkluːsɪv/", definition: "making sure that people with different backgrounds can participate", example: "An inclusive meeting gives every colleague a chance to contribute.", exampleTranslation: "يمنح الاجتماع الشامل كل زميل فرصة للمشاركة.", category: "teamwork", tags: ["work", "society"], synonyms: ["open", "welcoming"], antonyms: ["exclusive"] }),
      reviewed({ word: "coordination", translation: "تنسيق", pos: "noun", ipa: "/koʊˌɔːrdɪˈneɪʃən/", definition: "the organisation of people or activities so that they work effectively together", example: "Good coordination prevented two departments from repeating the same task.", exampleTranslation: "منع التنسيق الجيد قسمين من تكرار المهمة نفسها.", category: "teamwork", tags: ["work", "organisation"], synonyms: ["cooperation", "organisation"] }),
      reviewed({ word: "consensus", translation: "إجماع", pos: "noun", ipa: "/kənˈsensəs/", definition: "general agreement reached by a group", example: "The team reached a consensus after discussing the evidence.", exampleTranslation: "توصل الفريق إلى إجماع بعد مناقشة الأدلة.", category: "decision making", tags: ["work", "communication"], synonyms: ["agreement", "common ground"], antonyms: ["disagreement"] }),
      reviewed({ word: "contribution", translation: "مساهمة", pos: "noun", ipa: "/ˌkɑːntrɪˈbjuːʃən/", definition: "something that a person does or provides to help a group", example: "Everyone’s contribution improved the final presentation.", exampleTranslation: "حسّنت مساهمة الجميع العرض النهائي.", category: "teamwork", tags: ["work", "participation"], synonyms: ["input", "support"] }),
      reviewed({ word: "morale", translation: "معنويات", pos: "noun", ipa: "/məˈræl/", definition: "the confidence and enthusiasm of a person or group", example: "Regular recognition helped maintain team morale.", exampleTranslation: "ساعد التقدير المنتظم على الحفاظ على معنويات الفريق.", category: "teamwork", tags: ["work", "feelings"], synonyms: ["confidence", "spirit"], antonyms: ["discouragement"] }),
      reviewed({ word: "psychological safety", translation: "الأمان النفسي", pos: "noun", ipa: "/ˌsaɪkəˈlɑːdʒɪkəl ˈseɪfti/", definition: "a shared belief that people can speak up without fear of humiliation or punishment", example: "Psychological safety encourages staff to report mistakes early.", exampleTranslation: "يشجع الأمان النفسي الموظفين على الإبلاغ عن الأخطاء مبكرًا.", category: "teamwork", tags: ["work", "communication"], synonyms: ["safe participation", "trust"] }),
    ],
    u59: [
      reviewed({ word: "outreach", translation: "تواصل مجتمعي", pos: "noun", ipa: "/ˈaʊtriːtʃ/", definition: "organised work that brings information or support to people in the wider community", example: "The charity expanded its outreach to rural neighbourhoods.", exampleTranslation: "وسعت الجمعية تواصلها المجتمعي إلى الأحياء الريفية.", category: "community", tags: ["society", "volunteering"], synonyms: ["community contact", "engagement"] }),
      reviewed({ word: "fundraiser", translation: "فعالية لجمع التبرعات", pos: "noun", ipa: "/ˈfʌndreɪzər/", definition: "an event or activity organised to collect money for a cause", example: "The school held a fundraiser for the local shelter.", exampleTranslation: "أقامت المدرسة فعالية لجمع التبرعات للمأوى المحلي.", category: "charity", tags: ["community", "events"], synonyms: ["benefit event", "charity event"] }),
      reviewed({ word: "donation", translation: "تبرع", pos: "noun", ipa: "/doʊˈneɪʃən/", definition: "money or goods given to help a person or organisation", example: "Every donation helped provide meals for families.", exampleTranslation: "ساعد كل تبرع على توفير وجبات للعائلات.", category: "charity", tags: ["community", "money"], synonyms: ["gift", "contribution"], antonyms: ["withdrawal"] }),
      reviewed({ word: "advocate", translation: "يدافع عن / مناصر", pos: "verb", ipa: "/ˈædvəkeɪt/", definition: "to publicly support a particular idea, group, or cause", example: "Volunteers advocate for better access to public libraries.", exampleTranslation: "يدافع المتطوعون عن وصول أفضل إلى المكتبات العامة.", category: "civic action", tags: ["society", "communication"], synonyms: ["support", "campaign for"] }),
      reviewed({ word: "civic engagement", translation: "مشاركة مدنية", pos: "noun", ipa: "/ˌsɪvɪk ɪnˈɡeɪdʒmənt/", definition: "participation in activities that improve or influence community life", example: "Civic engagement can strengthen trust between residents and councils.", exampleTranslation: "يمكن للمشاركة المدنية أن تعزز الثقة بين السكان والمجالس.", category: "community", tags: ["society", "citizenship"], synonyms: ["public participation", "civic participation"] }),
      reviewed({ word: "grassroots", translation: "قاعدي / نابع من المجتمع", pos: "adjective", ipa: "/ˈɡræsruːts/", definition: "organised by ordinary people rather than by established leaders", example: "A grassroots campaign changed the council’s priorities.", exampleTranslation: "غيّرت حملة قاعدية أولويات المجلس.", category: "community", tags: ["society", "campaigns"], synonyms: ["community-led", "local"] }),
      reviewed({ word: "beneficiary", translation: "مستفيد", pos: "noun", ipa: "/ˌbenɪˈfɪʃəri/", definition: "a person or group that receives help or an advantage", example: "The beneficiaries helped decide how the grant should be used.", exampleTranslation: "ساعد المستفيدون في تحديد كيفية استخدام المنحة.", category: "charity", tags: ["community", "support"], synonyms: ["recipient", "receiver"] }),
      reviewed({ word: "mobilise", translation: "يعبّئ / يحشد", pos: "verb", ipa: "/ˈmoʊbəlaɪz/", definition: "to organise people or resources so that they can act", example: "The organisers mobilised volunteers after the storm.", exampleTranslation: "حشد المنظمون المتطوعين بعد العاصفة.", category: "community", tags: ["volunteering", "action"], synonyms: ["organise", "rally"] }),
    ],
    u60: [
      reviewed({ word: "agenda", translation: "جدول أعمال", pos: "noun", ipa: "/əˈdʒendə/", definition: "a list of items to be discussed at a meeting", example: "The chair sent the agenda before the meeting.", exampleTranslation: "أرسل رئيس الاجتماع جدول الأعمال قبل الاجتماع.", category: "meetings", tags: ["work", "communication"], synonyms: ["programme", "schedule"] }),
      reviewed({ word: "facilitate", translation: "يسهّل / يدير", pos: "verb", ipa: "/fəˈsɪləteɪt/", definition: "to help a discussion or process happen effectively", example: "Maya will facilitate the discussion and keep it focused.", exampleTranslation: "ستدير مايا النقاش وتحافظ على تركيزه.", category: "meetings", tags: ["work", "communication"], synonyms: ["enable", "guide"] }),
      reviewed({ word: "clarify", translation: "يوضح", pos: "verb", ipa: "/ˈklærəfaɪ/", definition: "to make an idea or statement easier to understand", example: "Could you clarify the final recommendation?", exampleTranslation: "هل يمكنك توضيح التوصية النهائية؟", category: "communication", tags: ["work", "meetings"], synonyms: ["explain", "make clear"], antonyms: ["confuse"] }),
      reviewed({ word: "minutes", translation: "محضر الاجتماع", pos: "noun", ipa: "/ˈmɪnɪts/", definition: "an official written record of what was discussed and decided at a meeting", example: "The secretary circulated the minutes on Friday.", exampleTranslation: "وزع السكرتير محضر الاجتماع يوم الجمعة.", category: "meetings", tags: ["work", "documents"], synonyms: ["meeting record", "notes"] }),
      reviewed({ word: "chairperson", translation: "رئيس الاجتماع", pos: "noun", ipa: "/ˈtʃerˌpɜːrsən/", definition: "the person who leads and organises a meeting", example: "The chairperson invited quieter members to speak.", exampleTranslation: "دعا رئيس الاجتماع الأعضاء الأقل كلامًا إلى المشاركة.", category: "meetings", tags: ["work", "leadership"], synonyms: ["chair", "meeting leader"] }),
      reviewed({ word: "action point", translation: "إجراء متفق عليه", pos: "noun", ipa: "/ˈækʃən pɔɪnt/", definition: "a task that someone agrees to complete after a meeting", example: "Each action point has an owner and a deadline.", exampleTranslation: "لكل إجراء متفق عليه مسؤول وموعد نهائي.", category: "meetings", tags: ["work", "planning"], synonyms: ["assigned task", "follow-up task"] }),
      reviewed({ word: "decision log", translation: "سجل القرارات", pos: "noun", ipa: "/dɪˈsɪʒən lɔːɡ/", definition: "a record of important decisions and the reasons for making them", example: "The decision log prevented the team from reopening settled questions.", exampleTranslation: "منع سجل القرارات الفريق من إعادة فتح مسائل حُسمت.", category: "meetings", tags: ["work", "documentation"], synonyms: ["decision record", "audit trail"] }),
      reviewed({ word: "timekeeper", translation: "مراقب الوقت", pos: "noun", ipa: "/ˈtaɪmkiːpər/", definition: "a person who monitors how much time a meeting or activity uses", example: "The timekeeper warned us when five minutes remained.", exampleTranslation: "حذرنا مراقب الوقت عندما تبقت خمس دقائق.", category: "meetings", tags: ["work", "planning"], synonyms: ["time monitor", "clock watcher"] }),
    ],
    u61: [
      reviewed({ word: "respectfully", translation: "باحترام", pos: "adverb", ipa: "/rɪˈspektfəli/", definition: "in a polite way that shows consideration for another person", example: "She respectfully challenged the assumption in the report.", exampleTranslation: "تحدت الافتراض الوارد في التقرير باحترام.", category: "communication", tags: ["discussion", "relationships"], synonyms: ["politely", "courteously"] }),
      reviewed({ word: "counterargument", translation: "حجة مضادة", pos: "noun", ipa: "/ˈkaʊntərˌɑːrɡjəmənt/", definition: "an argument that opposes or responds to another argument", example: "He presented a strong counterargument supported by data.", exampleTranslation: "قدم حجة مضادة قوية مدعومة بالبيانات.", category: "argument", tags: ["communication", "thinking"], synonyms: ["opposing argument", "rebuttal"] }),
      reviewed({ word: "acknowledge", translation: "يقرّ / يعترف بـ", pos: "verb", ipa: "/əkˈnɑːlɪdʒ/", definition: "to accept that something is true or that someone has a valid point", example: "It is important to acknowledge the limits of the evidence.", exampleTranslation: "من المهم الإقرار بحدود الأدلة.", category: "discussion", tags: ["communication", "thinking"], synonyms: ["recognise", "admit"] }),
      reviewed({ word: "premise", translation: "مقدمة منطقية", pos: "noun", ipa: "/ˈpremɪs/", definition: "a statement or idea on which an argument is based", example: "The conclusion is weak because its central premise is false.", exampleTranslation: "الاستنتاج ضعيف لأن مقدمته المنطقية الأساسية خاطئة.", category: "argument", tags: ["thinking", "logic"], synonyms: ["assumption", "starting point"] }),
      reviewed({ word: "rebuttal", translation: "تفنيد / رد حجاجي", pos: "noun", ipa: "/rɪˈbʌtəl/", definition: "a response that shows why an opposing argument is not convincing", example: "Her rebuttal addressed each claim rather than attacking the speaker.", exampleTranslation: "تناول تفنيدها كل ادعاء بدلًا من مهاجمة المتحدث.", category: "argument", tags: ["communication", "debate"], synonyms: ["refutation", "response"] }),
      reviewed({ word: "concession", translation: "إقرار بجزء من حجة الخصم", pos: "noun", ipa: "/kənˈseʃən/", definition: "an admission that part of another person’s argument is reasonable", example: "The concession made his criticism more balanced.", exampleTranslation: "جعل الإقرار بجزء من الحجة نقده أكثر توازنًا.", category: "argument", tags: ["communication", "rhetoric"], synonyms: ["admission", "acknowledgement"] }),
      reviewed({ word: "nuance", translation: "فارق دقيق / دلالة دقيقة", pos: "noun", ipa: "/ˈnuːɑːns/", definition: "a small difference in meaning, feeling, or expression", example: "The debate requires attention to the nuance of each claim.", exampleTranslation: "يتطلب النقاش الانتباه إلى الفروق الدقيقة في كل ادعاء.", category: "communication", tags: ["language", "thinking"], synonyms: ["subtlety", "distinction"] }),
      reviewed({ word: "tactful", translation: "لبق", pos: "adjective", ipa: "/ˈtæktfəl/", definition: "careful not to upset or embarrass people when expressing an opinion", example: "A tactful reply kept the disagreement productive.", exampleTranslation: "حافظ الرد اللبق على فائدة الخلاف.", category: "communication", tags: ["relationships", "discussion"], synonyms: ["diplomatic", "considerate"], antonyms: ["insensitive"] }),
    ],
    u54: [
      {
        word: "academic",
        translation: "أكاديمي",
        translationLang: "ar",
        pos: "adjective",
        ipa: "/ˌækəˈdemɪk/",
        definition: "connected with education, study, or research",
        example: "The applicant described her academic experience clearly.",
        exampleTranslation: "وصفت المتقدمة خبرتها الأكاديمية بوضوح.",
        synonyms: ["educational", "scholarly"],
        antonyms: ["practical"],
        collocations: ["academic experience", "academic qualification"],
        wordFamily: ["academy", "academic", "academically"],
        tags: ["work", "education"],
        category: "education",
      },
    ],
    u55: [
      {
        word: "access",
        translation: "يصل إلى / إمكانية الوصول",
        translationLang: "ar",
        pos: "verb",
        ipa: "/ˈækses/",
        definition: "to reach, enter, or use something",
        example: "Employees can access the shared document after the meeting.",
        exampleTranslation: "يمكن للموظفين الوصول إلى المستند المشترك بعد الاجتماع.",
        synonyms: ["reach", "enter"],
        antonyms: ["block", "restrict"],
        collocations: ["access information", "access a document"],
        wordFamily: ["access", "accessible", "inaccessible"],
        tags: ["work", "communication"],
        category: "communication",
      },
      {
        word: "absolutely",
        translation: "تمامًا / بالتأكيد",
        translationLang: "ar",
        pos: "adverb",
        ipa: "/ˌæbsəˈluːtli/",
        definition: "completely or used to strongly agree with something",
        example: "I absolutely agree that the team needs a clear plan.",
        exampleTranslation: "أوافق تمامًا على أن الفريق يحتاج إلى خطة واضحة.",
        synonyms: ["completely", "certainly"],
        antonyms: ["partly", "possibly"],
        collocations: ["absolutely agree", "absolutely necessary"],
        wordFamily: ["absolute", "absolutely"],
        tags: ["communication", "work"],
        category: "agreement",
      },
    ],
  },
  B2: {
    u52: [
      reviewed({ word: "legislation", translation: "تشريع", pos: "noun", ipa: "/ˌledʒɪˈsleɪʃən/", definition: "a law or set of laws made by a government", example: "The new legislation requires companies to publish safety data.", exampleTranslation: "يُلزم التشريع الجديد الشركات بنشر بيانات السلامة.", category: "policy and regulation", tags: ["government", "law"], synonyms: ["law", "statute"] }),
      reviewed({ word: "mandate", translation: "تفويض / إلزام قانوني", pos: "noun", ipa: "/ˈmændeɪt/", definition: "an official order or authority to do something", example: "The agency received a mandate to inspect public facilities.", exampleTranslation: "تلقت الوكالة تفويضًا لتفتيش المرافق العامة.", category: "policy and regulation", tags: ["government", "law"], synonyms: ["instruction", "authority"] }),
      reviewed({ word: "statute", translation: "قانون مكتوب", pos: "noun", ipa: "/ˈstætʃuːt/", definition: "a formal written law passed by a legislative body", example: "The statute sets a maximum period for processing applications.", exampleTranslation: "يحدد القانون المكتوب مدة قصوى لمعالجة الطلبات.", category: "policy and regulation", tags: ["government", "law"], synonyms: ["act", "written law"] }),
      reviewed({ word: "oversight", translation: "رقابة وإشراف", pos: "noun", ipa: "/ˈoʊvərsaɪt/", definition: "official supervision of an activity to ensure that it is done properly", example: "Independent oversight increased public confidence in the regulator.", exampleTranslation: "زادت الرقابة المستقلة ثقة الجمهور بالجهة المنظمة.", category: "policy and regulation", tags: ["government", "accountability"], synonyms: ["supervision", "scrutiny"] }),
      reviewed({ word: "sanction", translation: "عقوبة / جزاء رسمي", pos: "noun", ipa: "/ˈsæŋkʃən/", definition: "an official penalty imposed for breaking a rule or law", example: "The regulator imposed a sanction after repeated violations.", exampleTranslation: "فرضت الجهة المنظمة جزاءً رسميًا بعد مخالفات متكررة.", category: "policy and regulation", tags: ["government", "law"], synonyms: ["penalty", "punishment"] }),
      reviewed({ word: "jurisdiction", translation: "اختصاص قانوني", pos: "noun", ipa: "/ˌdʒʊrɪsˈdɪkʃən/", definition: "the authority of a court or official body to make legal decisions", example: "The dispute falls within the jurisdiction of the national court.", exampleTranslation: "يقع النزاع ضمن الاختصاص القانوني للمحكمة الوطنية.", category: "policy and regulation", tags: ["law", "government"], synonyms: ["legal authority", "legal territory"] }),
      reviewed({ word: "provision", translation: "بند قانوني", pos: "noun", ipa: "/prəˈvɪʒən/", definition: "a condition or requirement included in a law, agreement, or plan", example: "The provision protects small businesses from sudden fee increases.", exampleTranslation: "يحمي البند القانوني الشركات الصغيرة من الزيادات المفاجئة في الرسوم.", category: "policy and regulation", tags: ["law", "business"], synonyms: ["clause", "requirement"] }),
      reviewed({ word: "enactment", translation: "إقرار قانون", pos: "noun", ipa: "/ɪˈnæktmənt/", definition: "the process of making a proposal into an official law", example: "The enactment of the reform followed months of public debate.", exampleTranslation: "جاء إقرار الإصلاح بعد أشهر من النقاش العام.", category: "policy and regulation", tags: ["government", "law"], synonyms: ["passing of a law", "legislation"] }),
    ],
    u53: [
      reviewed({ word: "indicator", translation: "مؤشر", pos: "noun", ipa: "/ˈɪndɪkeɪtər/", definition: "a sign or measurement that shows the condition or development of something", example: "The employment rate is an important economic indicator.", exampleTranslation: "يُعد معدل التوظيف مؤشرًا اقتصاديًا مهمًا.", category: "data and evidence", tags: ["research", "economy"], synonyms: ["measure", "signal"] }),
      reviewed({ word: "baseline", translation: "خط أساس", pos: "noun", ipa: "/ˈbeɪslaɪn/", definition: "a starting level used for comparison when measuring change", example: "The survey established a baseline before the programme began.", exampleTranslation: "حدد الاستطلاع خط أساس قبل بدء البرنامج.", category: "data and evidence", tags: ["research", "measurement"], synonyms: ["starting point", "reference level"] }),
      reviewed({ word: "estimate", translation: "تقدير", pos: "noun", ipa: "/ˈestɪmət/", definition: "a calculation or judgement of an amount that is not known exactly", example: "The estimate includes a margin for unexpected costs.", exampleTranslation: "يتضمن التقدير هامشًا للتكاليف غير المتوقعة.", category: "data and evidence", tags: ["research", "analysis"], synonyms: ["approximation", "calculation"] }),
      reviewed({ word: "inference", translation: "استدلال / استنتاج", pos: "noun", ipa: "/ˈɪnfərəns/", definition: "a conclusion reached from evidence and reasoning", example: "That inference is reasonable, but more data would strengthen it.", exampleTranslation: "ذلك الاستنتاج معقول، لكن مزيدًا من البيانات سيقويه.", category: "data and evidence", tags: ["research", "thinking"], synonyms: ["deduction", "conclusion"] }),
      reviewed({ word: "distribution", translation: "توزيع إحصائي", pos: "noun", ipa: "/ˌdɪstrɪˈbjuːʃən/", definition: "the way values or observations are spread across a set of data", example: "The distribution of scores was wider than expected.", exampleTranslation: "كان توزيع الدرجات أوسع من المتوقع.", category: "data and evidence", tags: ["research", "statistics"], synonyms: ["spread", "pattern"] }),
      reviewed({ word: "data point", translation: "نقطة بيانات", pos: "noun", ipa: "/ˈdeɪtə pɔɪnt/", definition: "a single piece of information in a dataset or measurement", example: "One unusual data point should be checked before it is removed.", exampleTranslation: "ينبغي التحقق من نقطة بيانات غير معتادة قبل حذفها.", category: "data and evidence", tags: ["research", "statistics"], synonyms: ["observation", "record"] }),
      reviewed({ word: "measurement scale", translation: "مقياس القياس", pos: "noun", ipa: "/ˈmeʒərmənt skeɪl/", definition: "a system used to assign values to qualities or quantities", example: "The researchers explained why they chose this measurement scale.", exampleTranslation: "شرح الباحثون سبب اختيارهم مقياس القياس هذا.", category: "data and evidence", tags: ["research", "measurement"], synonyms: ["scoring system", "measurement system"] }),
      reviewed({ word: "confidence level", translation: "مستوى الثقة الإحصائية", pos: "noun", ipa: "/ˈkɑːnfɪdəns ˌlevəl/", definition: "a statistical indication of how certain an estimate is", example: "The report presents the estimate with a ninety-five percent confidence level.", exampleTranslation: "يعرض التقرير التقدير بمستوى ثقة يبلغ خمسة وتسعين بالمئة.", category: "data and evidence", tags: ["research", "statistics"], synonyms: ["degree of certainty", "statistical confidence"] }),
    ],
    u54: [
      reviewed({ word: "aesthetic", translation: "جمالي", pos: "adjective", ipa: "/iːsˈθetɪk/", definition: "concerned with beauty, style, or the appreciation of art", example: "The exhibition has both historical and aesthetic value.", exampleTranslation: "للمعرض قيمة تاريخية وجمالية معًا.", category: "cultural trends", tags: ["culture", "art"], synonyms: ["artistic", "visual"] }),
      reviewed({ word: "curator", translation: "قيّم فني / أمين معرض", pos: "noun", ipa: "/kjʊˈreɪtər/", definition: "a person who selects, organises, and cares for objects in a museum or collection", example: "The curator explained how the collection represented changing tastes.", exampleTranslation: "شرح أمين المعرض كيف عكست المجموعة الأذواق المتغيرة.", category: "cultural trends", tags: ["culture", "art"], synonyms: ["collection manager", "exhibition organiser"] }),
      reviewed({ word: "commodity", translation: "سلعة", pos: "noun", ipa: "/kəˈmɑːdəti/", definition: "a product that can be bought and sold, especially a basic material", example: "Coffee became a valuable commodity in the global market.", exampleTranslation: "أصبحت القهوة سلعة ذات قيمة في السوق العالمية.", category: "cultural trends", tags: ["economy", "society"], synonyms: ["product", "trade good"] }),
      reviewed({ word: "diaspora", translation: "شتات", pos: "noun", ipa: "/daɪˈæspərə/", definition: "a group of people who live outside their historic homeland", example: "The diaspora maintained cultural traditions through food and music.", exampleTranslation: "حافظ الشتات على التقاليد الثقافية عبر الطعام والموسيقى.", category: "cultural trends", tags: ["culture", "migration"], synonyms: ["dispersed community", "exile community"] }),
      reviewed({ word: "cultural appropriation", translation: "استيلاء ثقافي", pos: "noun", ipa: "/ˈkʌltʃərəl əˌproʊpriˈeɪʃən/", definition: "the unacknowledged or inappropriate adoption of elements from another culture", example: "The debate asked whether the campaign showed appreciation or cultural appropriation.", exampleTranslation: "ناقش الجدل ما إذا كانت الحملة تقديرًا أم استيلاءً ثقافيًا.", category: "cultural trends", tags: ["culture", "ethics"], synonyms: ["cultural borrowing", "uncredited adoption"] }),
      reviewed({ word: "heritage site", translation: "موقع تراثي", pos: "noun", ipa: "/ˈherɪtɪdʒ saɪt/", definition: "a place valued for its historical, cultural, or natural importance", example: "Tourism can support a heritage site when visitors are managed responsibly.", exampleTranslation: "يمكن للسياحة أن تدعم موقعًا تراثيًا عندما يُدار الزوار بمسؤولية.", category: "cultural trends", tags: ["culture", "travel"], synonyms: ["historic site", "cultural landmark"] }),
      reviewed({ word: "consumerism", translation: "النزعة الاستهلاكية", pos: "noun", ipa: "/kənˈsuːmərɪzəm/", definition: "the belief that buying more goods leads to a better or more successful life", example: "The documentary questions the environmental cost of consumerism.", exampleTranslation: "يتساءل الفيلم الوثائقي عن الكلفة البيئية للنزعة الاستهلاكية.", category: "cultural trends", tags: ["society", "economy"], synonyms: ["consumer culture", "materialism"] }),
      reviewed({ word: "social mobility", translation: "حراك اجتماعي", pos: "noun", ipa: "/ˌsoʊʃəl moʊˈbɪləti/", definition: "the movement of people or groups between social or economic positions", example: "Education is often discussed as a route to social mobility.", exampleTranslation: "غالبًا ما يُناقش التعليم بوصفه طريقًا إلى الحراك الاجتماعي.", category: "cultural trends", tags: ["society", "education"], synonyms: ["class mobility", "social movement"] }),
    ],
    u44: [
      reviewed({ word: "mediation", translation: "وساطة", pos: "noun", ipa: "/ˌmiːdiˈeɪʃən/", definition: "the process of helping people in conflict reach an agreement", example: "Mediation helped the two departments settle the dispute.", exampleTranslation: "ساعدت الوساطة القسمين على تسوية النزاع.", category: "negotiation", tags: ["conflict", "communication"], synonyms: ["conciliation", "facilitated discussion"] }),
      reviewed({ word: "grievance", translation: "شكوى رسمية", pos: "noun", ipa: "/ˈɡriːvəns/", definition: "a formal complaint about unfair treatment or a problem", example: "The employee submitted a grievance through the proper channel.", exampleTranslation: "قدم الموظف شكوى رسمية عبر القناة المناسبة.", category: "negotiation", tags: ["work", "conflict"], synonyms: ["complaint", "objection"] }),
      reviewed({ word: "de-escalate", translation: "يخفف التصعيد", pos: "verb", ipa: "/ˌdiːˈeskəleɪt/", definition: "to make a conflict or difficult situation less intense", example: "The manager used a calm tone to de-escalate the argument.", exampleTranslation: "استخدم المدير نبرة هادئة لتخفيف تصعيد الجدال.", category: "negotiation", tags: ["conflict", "communication"], synonyms: ["calm", "defuse"] }),
      reviewed({ word: "bargaining", translation: "مساومة وتفاوض", pos: "noun", ipa: "/ˈbɑːrɡənɪŋ/", definition: "the process of negotiating the terms of an agreement", example: "The bargaining continued until both sides accepted the revised price.", exampleTranslation: "استمرت المساومة حتى قبل الطرفان السعر المعدل.", category: "negotiation", tags: ["business", "communication"], synonyms: ["negotiation", "deal-making"] }),
      reviewed({ word: "contentious", translation: "مثير للخلاف", pos: "adjective", ipa: "/kənˈtenʃəs/", definition: "likely to cause disagreement or argument", example: "The meeting postponed the most contentious issue.", exampleTranslation: "أجل الاجتماع أكثر المسائل إثارة للخلاف.", category: "negotiation", tags: ["conflict", "society"], synonyms: ["controversial", "disputed"] }),
      reviewed({ word: "settlement", translation: "تسوية", pos: "noun", ipa: "/ˈsetəlmənt/", definition: "an agreement that ends a dispute", example: "The settlement gave both parties a practical way forward.", exampleTranslation: "منحت التسوية الطرفين طريقًا عمليًا للمضي قدمًا.", category: "negotiation", tags: ["conflict", "law"], synonyms: ["agreement", "resolution"] }),
      reviewed({ word: "deadlock", translation: "حالة جمود تفاوضي", pos: "noun", ipa: "/ˈdedlɑːk/", definition: "a situation in which no progress is possible because sides cannot agree", example: "The mediator proposed a new option to break the deadlock.", exampleTranslation: "اقترح الوسيط خيارًا جديدًا لكسر حالة الجمود التفاوضي.", category: "negotiation", tags: ["conflict", "decision making"], synonyms: ["stalemate", "impasse"] }),
      reviewed({ word: "conciliatory", translation: "تصالحي", pos: "adjective", ipa: "/kənˈsɪliətɔːri/", definition: "intended to end disagreement by showing willingness to compromise", example: "Her conciliatory message reopened the conversation.", exampleTranslation: "أعادت رسالتها التصالحية فتح الحوار.", category: "negotiation", tags: ["conflict", "communication"], synonyms: ["peace-making", "appeasing"] }),
    ],
    u45: [
      reviewed({ word: "data breach", translation: "اختراق بيانات", pos: "noun", ipa: "/ˈdeɪtə briːtʃ/", definition: "an incident in which protected information is accessed or released without permission", example: "The company notified users after the data breach.", exampleTranslation: "أبلغت الشركة المستخدمين بعد اختراق البيانات.", category: "digital responsibility", tags: ["technology", "security"], synonyms: ["security breach", "data leak"] }),
      reviewed({ word: "access control", translation: "التحكم في الوصول", pos: "noun", ipa: "/ˈækses kənˌtroʊl/", definition: "rules and tools that decide who may use information or systems", example: "Strong access control limits sensitive files to authorised staff.", exampleTranslation: "يحد التحكم القوي في الوصول الملفات الحساسة بالموظفين المصرح لهم.", category: "digital responsibility", tags: ["technology", "security"], synonyms: ["permission management", "authorisation control"] }),
      reviewed({ word: "facial recognition", translation: "التعرف على الوجه", pos: "noun", ipa: "/ˈfeɪʃəl ˌrekəɡˈnɪʃən/", definition: "technology that identifies or verifies people by analysing facial features", example: "Facial recognition raises questions about consent and accuracy.", exampleTranslation: "يثير التعرف على الوجه أسئلة حول الموافقة والدقة.", category: "digital responsibility", tags: ["technology", "privacy"], synonyms: ["face identification", "biometric recognition"] }),
      reviewed({ word: "digital footprint", translation: "البصمة الرقمية", pos: "noun", ipa: "/ˌdɪdʒɪtəl ˈfʊtprɪnt/", definition: "the record of activities and information a person leaves online", example: "Students should understand that posts contribute to a digital footprint.", exampleTranslation: "ينبغي للطلاب فهم أن المنشورات تسهم في بصمة رقمية.", category: "digital responsibility", tags: ["technology", "privacy"], synonyms: ["online trace", "digital record"] }),
      reviewed({ word: "cyberbullying", translation: "تنمر إلكتروني", pos: "noun", ipa: "/ˈsaɪbərˌbʊliɪŋ/", definition: "the use of digital communication to threaten or humiliate someone", example: "The school created a policy to report cyberbullying safely.", exampleTranslation: "أنشأت المدرسة سياسة للإبلاغ عن التنمر الإلكتروني بأمان.", category: "digital responsibility", tags: ["technology", "society"], synonyms: ["online harassment", "digital bullying"] }),
      reviewed({ word: "authentication", translation: "مصادقة رقمية", pos: "noun", ipa: "/ɔːˌθentɪˈkeɪʃən/", definition: "the process of proving that a user is who they claim to be", example: "Two-factor authentication protects the account from stolen passwords.", exampleTranslation: "تحمي المصادقة الثنائية الحساب من كلمات المرور المسروقة.", category: "digital responsibility", tags: ["technology", "security"], synonyms: ["identity verification", "login verification"] }),
      reviewed({ word: "algorithmic accountability", translation: "مساءلة الخوارزميات", pos: "noun", ipa: "/ˌælɡəˈrɪðmɪk əˌkaʊntəˈbɪləti/", definition: "the responsibility to explain and evaluate the effects of an automated system", example: "Algorithmic accountability requires an appeal process for users.", exampleTranslation: "تتطلب مساءلة الخوارزميات عملية اعتراض للمستخدمين.", category: "digital responsibility", tags: ["technology", "governance"], synonyms: ["automated-system oversight", "algorithm governance"] }),
      reviewed({ word: "digital consent", translation: "موافقة رقمية", pos: "noun", ipa: "/ˈdɪdʒɪtəl kənˈsent/", definition: "informed permission for the collection or use of information online", example: "The app explains digital consent before requesting location data.", exampleTranslation: "يشرح التطبيق الموافقة الرقمية قبل طلب بيانات الموقع.", category: "digital responsibility", tags: ["technology", "privacy"], synonyms: ["online permission", "informed digital permission"] }),
    ],
    u46: [
      reviewed({ word: "reproducibility", translation: "قابلية إعادة الإنتاج", pos: "noun", ipa: "/ˌriːprəˌduːsəˈbɪləti/", definition: "the ability to obtain consistent results using the same data and method", example: "The researchers shared their code to improve reproducibility.", exampleTranslation: "شارك الباحثون شفرتهم لتحسين قابلية إعادة الإنتاج.", category: "research and data", tags: ["research", "methods"], synonyms: ["repeatability", "reproducibility"] }),
      reviewed({ word: "sampling frame", translation: "إطار أخذ العينات", pos: "noun", ipa: "/ˈsæmplɪŋ freɪm/", definition: "a list or source from which a research sample is selected", example: "An incomplete sampling frame can exclude important groups.", exampleTranslation: "يمكن لإطار أخذ عينات غير مكتمل أن يستبعد مجموعات مهمة.", category: "research and data", tags: ["research", "statistics"], synonyms: ["sampling list", "population list"] }),
      reviewed({ word: "outlier", translation: "قيمة شاذة", pos: "noun", ipa: "/ˈaʊtlaɪər/", definition: "a value that is unusually far from the other values in a dataset", example: "The analyst investigated the outlier instead of deleting it immediately.", exampleTranslation: "حقق المحلل في القيمة الشاذة بدل حذفها فورًا.", category: "research and data", tags: ["research", "statistics"], synonyms: ["extreme value", "anomalous value"] }),
      reviewed({ word: "missing data", translation: "بيانات مفقودة", pos: "noun", ipa: "/ˈmɪsɪŋ ˈdeɪtə/", definition: "information that should have been collected but is not available", example: "The report explains how missing data affected the analysis.", exampleTranslation: "يشرح التقرير كيف أثرت البيانات المفقودة في التحليل.", category: "research and data", tags: ["research", "data quality"], synonyms: ["incomplete data", "unobserved values"] }),
      reviewed({ word: "statistical power", translation: "القوة الإحصائية", pos: "noun", ipa: "/stəˌtɪstɪkəl ˈpaʊər/", definition: "the likelihood that a study will detect an effect if a real effect exists", example: "A larger sample can increase statistical power.", exampleTranslation: "يمكن لعينة أكبر أن تزيد القوة الإحصائية.", category: "research and data", tags: ["research", "statistics"], synonyms: ["detection power", "study power"] }),
      reviewed({ word: "operational definition", translation: "تعريف إجرائي", pos: "noun", ipa: "/ˌɑːpəˈreɪʃənəl ˌdefɪˈnɪʃən/", definition: "a precise statement of how a concept will be measured or identified", example: "The paper gives an operational definition of academic success.", exampleTranslation: "تقدم الورقة تعريفًا إجرائيًا للنجاح الأكاديمي.", category: "research and data", tags: ["research", "measurement"], synonyms: ["measurement definition", "working definition"] }),
      reviewed({ word: "metadata", translation: "بيانات وصفية", pos: "noun", ipa: "/ˈmetədeɪtə/", definition: "information that describes the origin, format, or context of other data", example: "Metadata showed when the survey responses were collected.", exampleTranslation: "أظهرت البيانات الوصفية متى جُمعت إجابات الاستطلاع.", category: "research and data", tags: ["research", "data"], synonyms: ["data description", "descriptive data"] }),
      reviewed({ word: "data cleaning", translation: "تنظيف البيانات", pos: "noun", ipa: "/ˈdeɪtə ˌkliːnɪŋ/", definition: "the process of finding and correcting errors or inconsistencies in data", example: "Data cleaning removed duplicate records before modelling.", exampleTranslation: "أزال تنظيف البيانات السجلات المكررة قبل بناء النموذج.", category: "research and data", tags: ["research", "data quality"], synonyms: ["data preparation", "data validation"] }),
    ],
    u57: [
      reviewed({ word: "decarbonise", translation: "يزيل الكربون / يخفض الانبعاثات", pos: "verb", ipa: "/ˌdiːˈkɑːrbənaɪz/", definition: "to reduce or remove carbon emissions from an activity or system", example: "The industry must decarbonise without abandoning affected workers.", exampleTranslation: "يجب على الصناعة خفض انبعاثاتها دون التخلي عن العمال المتضررين.", category: "climate policy", tags: ["environment", "industry"], synonyms: ["clean up", "reduce carbon"] }),
      reviewed({ word: "net zero", translation: "صافي الصفر", pos: "noun", ipa: "/ˌnet ˈzɪroʊ/", definition: "a balance in which greenhouse-gas emissions are matched by removals", example: "The country set a legally backed net-zero target.", exampleTranslation: "حددت الدولة هدفًا مدعومًا قانونيًا لصافي الصفر.", category: "climate policy", tags: ["environment", "policy"], synonyms: ["zero balance", "carbon neutrality"] }),
      reviewed({ word: "climate justice", translation: "العدالة المناخية", pos: "noun", ipa: "/ˈklaɪmət ˈdʒʌstɪs/", definition: "the principle that climate action should fairly distribute responsibilities and impacts", example: "Climate justice considers communities that contributed least to the crisis.", exampleTranslation: "تراعي العدالة المناخية المجتمعات الأقل مساهمة في الأزمة.", category: "climate policy", tags: ["environment", "society"], synonyms: ["environmental justice", "fair transition"] }),
      reviewed({ word: "greenwashing", translation: "التضليل البيئي", pos: "noun", ipa: "/ˈɡriːnwɑːʃɪŋ/", definition: "the practice of presenting an activity as more environmentally responsible than it is", example: "Independent labels can expose greenwashing in advertising.", exampleTranslation: "يمكن للعلامات المستقلة كشف التضليل البيئي في الإعلانات.", category: "climate policy", tags: ["environment", "media"], synonyms: ["false sustainability", "eco-pretence"] }),
      reviewed({ word: "energy transition", translation: "تحول الطاقة", pos: "noun", ipa: "/ˈenərdʒi trænˈzɪʃən/", definition: "a large-scale shift from high-carbon energy to cleaner sources", example: "The energy transition will affect jobs, prices, and infrastructure.", exampleTranslation: "سيؤثر تحول الطاقة في الوظائف والأسعار والبنية التحتية.", category: "climate policy", tags: ["environment", "economy"], synonyms: ["energy shift", "clean-energy transition"] }),
      reviewed({ word: "fossil fuel", translation: "وقود أحفوري", pos: "noun", ipa: "/ˈfɑːsəl fjuːəl/", definition: "coal, oil, or gas formed from ancient organic matter", example: "The proposal would reduce dependence on fossil fuel.", exampleTranslation: "سيقلل الاقتراح الاعتماد على الوقود الأحفوري.", category: "environment", tags: ["climate", "energy"], synonyms: ["coal, oil, and gas", "carbon fuel"] }),
      reviewed({ word: "policy instrument", translation: "أداة من أدوات السياسة العامة", pos: "noun", ipa: "/ˈpɑːləsi ˈɪnstrəmənt/", definition: "a mechanism a government uses to achieve a policy goal", example: "A tax is one policy instrument among several alternatives.", exampleTranslation: "تُعد الضريبة أداة من أدوات السياسة العامة من بين بدائل عدة.", category: "governance", tags: ["policy", "economy"], synonyms: ["policy tool", "government measure"] }),
    ],
    u58: [
      reviewed({ word: "urban sprawl", translation: "التمدد العمراني", pos: "noun", ipa: "/ˈɜːrbən sprɔːl/", definition: "the spread of a city into surrounding land in a low-density way", example: "Urban sprawl increases commuting distances and infrastructure costs.", exampleTranslation: "يزيد التمدد العمراني مسافات التنقل وتكاليف البنية التحتية.", category: "urban planning", tags: ["cities", "environment"], synonyms: ["suburban expansion", "outward growth"] }),
      reviewed({ word: "pedestrianisation", translation: "تحويل المنطقة إلى ممر للمشاة", pos: "noun", ipa: "/pəˌdestriənaɪˈzeɪʃən/", definition: "the process of making a street or area mainly for people walking", example: "Pedestrianisation made the historic centre quieter and safer.", exampleTranslation: "جعل تحويل المركز التاريخي إلى منطقة للمشاة أكثر هدوءًا وأمانًا.", category: "urban planning", tags: ["cities", "transport"], synonyms: ["car-free planning", "walkable design"] }),
      reviewed({ word: "congestion charge", translation: "رسم الازدحام", pos: "noun", ipa: "/kənˈdʒestʃən tʃɑːrdʒ/", definition: "a fee charged to vehicles entering a busy area", example: "The congestion charge funds improvements to public transport.", exampleTranslation: "يمول رسم الازدحام تحسينات النقل العام.", category: "urban planning", tags: ["cities", "transport"], synonyms: ["traffic fee", "road-use charge"] }),
      reviewed({ word: "affordable housing", translation: "سكن ميسور التكلفة", pos: "noun", ipa: "/əˈfɔːrdəbəl ˈhaʊzɪŋ/", definition: "housing that people on ordinary incomes can reasonably pay for", example: "The plan reserves land for affordable housing.", exampleTranslation: "تخصص الخطة أرضًا للسكن الميسور التكلفة.", category: "urban planning", tags: ["cities", "housing"], synonyms: ["low-cost housing", "accessible housing"] }),
      reviewed({ word: "public transit", translation: "النقل العام", pos: "noun", ipa: "/ˌpʌblɪk ˈtrænzɪt/", definition: "buses, trains, and other shared services that carry passengers", example: "Reliable public transit connects workers with jobs.", exampleTranslation: "يربط النقل العام الموثوق العمال بالوظائف.", category: "urban planning", tags: ["cities", "transport"], synonyms: ["public transport", "mass transit"] }),
      reviewed({ word: "mixed-use", translation: "متعدد الاستخدامات", pos: "adjective", ipa: "/ˌmɪkst ˈjuːs/", definition: "combining homes, shops, offices, or services in one development", example: "The mixed-use district keeps daily services close to residents.", exampleTranslation: "يبقي الحي متعدد الاستخدامات الخدمات اليومية قريبة من السكان.", category: "urban planning", tags: ["cities", "housing"], synonyms: ["combined-use", "integrated"] }),
      reviewed({ word: "water treatment", translation: "معالجة المياه", pos: "noun", ipa: "/ˈwɔːtər ˈtriːtmənt/", definition: "the process of making water safe for use or release", example: "Investment in water treatment protects public health.", exampleTranslation: "يحمي الاستثمار في معالجة المياه الصحة العامة.", category: "urban planning", tags: ["cities", "health"], synonyms: ["water purification", "water processing"] }),
      reviewed({ word: "land-use plan", translation: "خطة استخدام الأراضي", pos: "noun", ipa: "/ˈlænd juːs plæn/", definition: "a document that sets out how different areas may be developed", example: "The land-use plan protects wetlands from construction.", exampleTranslation: "تحمي خطة استخدام الأراضي الأراضي الرطبة من البناء.", category: "urban planning", tags: ["cities", "environment"], synonyms: ["development plan", "spatial plan"] }),
    ],
    u59: [
      reviewed({ word: "budgeting", translation: "إعداد الميزانية", pos: "noun", ipa: "/ˈbʌdʒɪtɪŋ/", definition: "the practice of planning how money will be earned and spent", example: "Careful budgeting helped the family manage rising costs.", exampleTranslation: "ساعد إعداد الميزانية بعناية الأسرة على إدارة التكاليف المتزايدة.", category: "personal finance", tags: ["money", "planning"], synonyms: ["financial planning", "money management"] }),
      reviewed({ word: "transaction", translation: "معاملة مالية", pos: "noun", ipa: "/trænˈzækʃən/", definition: "an act of buying, selling, or transferring money", example: "The bank flagged an unusual transaction.", exampleTranslation: "رصد البنك معاملة مالية غير معتادة.", category: "personal finance", tags: ["money", "banking"], synonyms: ["deal", "payment"] }),
      reviewed({ word: "liability", translation: "التزام مالي", pos: "noun", ipa: "/ˌlaɪəˈbɪləti/", definition: "a debt or responsibility that must be paid or dealt with", example: "The loan is recorded as a long-term liability.", exampleTranslation: "يُسجل القرض بوصفه التزامًا ماليًا طويل الأجل.", category: "personal finance", tags: ["money", "business"], synonyms: ["debt", "obligation"], antonyms: ["asset"] }),
      reviewed({ word: "pension", translation: "معاش تقاعدي", pos: "noun", ipa: "/ˈpenʃən/", definition: "money paid regularly after someone stops working", example: "She increased her pension contribution this year.", exampleTranslation: "زادت مساهمتها في المعاش التقاعدي هذا العام.", category: "personal finance", tags: ["money", "future"], synonyms: ["retirement income", "retirement fund"] }),
      reviewed({ word: "liquidity", translation: "سيولة", pos: "noun", ipa: "/lɪˈkwɪdəti/", definition: "the availability of cash or assets that can quickly become cash", example: "The business kept enough liquidity to cover its bills.", exampleTranslation: "احتفظت الشركة بسيولة كافية لتغطية فواتيرها.", category: "personal finance", tags: ["money", "business"], synonyms: ["cash availability", "cash flow"], antonyms: ["illiquidity"] }),
      reviewed({ word: "instalment", translation: "قسط", pos: "noun", ipa: "/ɪnˈstɔːlmənt/", definition: "one of several payments made over a period of time", example: "The customer paid the final instalment on schedule.", exampleTranslation: "دفع العميل القسط الأخير في الموعد.", category: "personal finance", tags: ["money", "payments"], synonyms: ["regular payment", "part-payment"] }),
      reviewed({ word: "creditworthiness", translation: "الجدارة الائتمانية", pos: "noun", ipa: "/ˈkredɪtwɜːrðinəs/", definition: "an assessment of how likely someone is to repay borrowed money", example: "Banks assess creditworthiness before approving a loan.", exampleTranslation: "تقيّم البنوك الجدارة الائتمانية قبل الموافقة على القرض.", category: "personal finance", tags: ["money", "banking"], synonyms: ["credit reliability", "financial reliability"] }),
      reviewed({ word: "collateral", translation: "ضمان القرض", pos: "noun", ipa: "/kəˈlætərəl/", definition: "property or another asset promised as security for a loan", example: "The lender required collateral before offering the business credit.", exampleTranslation: "طلب المقرض ضمانًا قبل منح الشركة ائتمانًا.", category: "personal finance", tags: ["money", "loans"], synonyms: ["security", "guarantee"] }),
    ],
    u60: [
      reviewed({ word: "clickbait", translation: "عنوان مضلل لجذب النقرات", pos: "noun", ipa: "/ˈklɪkbeɪt/", definition: "content designed to attract clicks with an exaggerated or misleading title", example: "The article looked like clickbait rather than serious reporting.", exampleTranslation: "بدا المقال عنوانًا مضللًا لجذب النقرات لا تقريرًا جادًا.", category: "media literacy", tags: ["media", "technology"], synonyms: ["attention-grabbing content", "bait headline"] }),
      reviewed({ word: "corroborate", translation: "يؤكد بأدلة مستقلة", pos: "verb", ipa: "/kəˈrɑːbəreɪt/", definition: "to support a statement with additional evidence", example: "Two independent sources corroborated the claim.", exampleTranslation: "أكد مصدران مستقلان الادعاء بأدلة إضافية.", category: "media literacy", tags: ["media", "research"], synonyms: ["confirm", "substantiate"], antonyms: ["contradict"] }),
      reviewed({ word: "source attribution", translation: "نَسْب المعلومات إلى مصدرها", pos: "noun", ipa: "/sɔːrs ˌætrɪˈbjuːʃən/", definition: "the practice of clearly identifying where information came from", example: "Accurate source attribution lets readers check the evidence.", exampleTranslation: "يتيح نسب المعلومات إلى مصدرها بدقة للقراء التحقق من الأدلة.", category: "media literacy", tags: ["media", "writing"], synonyms: ["crediting sources", "source citation"] }),
      reviewed({ word: "misleading", translation: "مضلل", pos: "adjective", ipa: "/mɪsˈliːdɪŋ/", definition: "giving a wrong idea or impression, often without being completely false", example: "The graph was technically correct but visually misleading.", exampleTranslation: "كان الرسم صحيحًا تقنيًا لكنه مضلل بصريًا.", category: "media literacy", tags: ["media", "data"], synonyms: ["deceptive", "distorting"], antonyms: ["accurate"] }),
      reviewed({ word: "primary source", translation: "مصدر أولي", pos: "noun", ipa: "/ˈpraɪmeri sɔːrs/", definition: "an original document, statement, or record produced close to an event", example: "The archive contains a primary source from the election.", exampleTranslation: "يحتوي الأرشيف على مصدر أولي من الانتخابات.", category: "media literacy", tags: ["media", "research"], synonyms: ["original record", "first-hand source"] }),
      reviewed({ word: "editorialise", translation: "يُدخل رأيًا في الخبر", pos: "verb", ipa: "/ˌedɪˈtɔːriəlaɪz/", definition: "to express opinions in a report that should mainly present facts", example: "A reporter should distinguish analysis from editorialising.", exampleTranslation: "ينبغي للصحفي أن يميز التحليل عن إدخال الرأي في الخبر.", category: "media literacy", tags: ["media", "journalism"], synonyms: ["comment", "express an opinion"] }),
      reviewed({ word: "contextualise", translation: "يضع في سياقه", pos: "verb", ipa: "/kənˈtekstʃuəlaɪz/", definition: "to explain information by showing the situation surrounding it", example: "The article contextualised the statistic with a ten-year comparison.", exampleTranslation: "وضع المقال الإحصائية في سياقها بمقارنة تمتد عشر سنوات.", category: "media literacy", tags: ["media", "analysis"], synonyms: ["situate", "frame"] }),
      reviewed({ word: "viral claim", translation: "ادعاء واسع الانتشار", pos: "noun", ipa: "/ˈvaɪrəl kleɪm/", definition: "a statement shared rapidly online, whether or not it is true", example: "The fact-checker investigated the viral claim before publication.", exampleTranslation: "حقق مدقق الحقائق في الادعاء واسع الانتشار قبل النشر.", category: "media literacy", tags: ["media", "internet"], synonyms: ["widely shared assertion", "online claim"] }),
    ],
    u61: [
      reviewed({ word: "heatwave", translation: "موجة حر", pos: "noun", ipa: "/ˈhiːtweɪv/", definition: "a period of unusually hot weather", example: "The heatwave placed extra pressure on the water supply.", exampleTranslation: "وضعت موجة الحر ضغطًا إضافيًا على إمدادات المياه.", category: "climate adaptation", tags: ["environment", "weather"], synonyms: ["hot spell", "extreme heat"] }),
      reviewed({ word: "floodplain", translation: "سهل فيضي", pos: "noun", ipa: "/ˈflʌdpleɪn/", definition: "flat land beside a river that may be covered by water during floods", example: "New buildings are restricted on the floodplain.", exampleTranslation: "تُقيّد المباني الجديدة في السهل الفيضي.", category: "climate adaptation", tags: ["environment", "planning"], synonyms: ["flood zone", "river plain"] }),
      reviewed({ word: "water scarcity", translation: "ندرة المياه", pos: "noun", ipa: "/ˈwɔːtər ˈskersəti/", definition: "a shortage of enough clean water for people or ecosystems", example: "Water scarcity is changing farming practices in the region.", exampleTranslation: "تغير ندرة المياه ممارسات الزراعة في المنطقة.", category: "climate adaptation", tags: ["environment", "resources"], synonyms: ["water shortage", "limited supply"] }),
      reviewed({ word: "nature-based", translation: "قائم على الطبيعة", pos: "adjective", ipa: "/ˈneɪtʃər beɪst/", definition: "using natural systems to address an environmental or social challenge", example: "The city funded a nature-based solution for stormwater.", exampleTranslation: "مولت المدينة حلًا قائمًا على الطبيعة لمياه الأمطار.", category: "climate adaptation", tags: ["environment", "cities"], synonyms: ["ecological", "natural-system"] }),
      reviewed({ word: "early-warning system", translation: "نظام إنذار مبكر", pos: "noun", ipa: "/ˌɜːrli ˈwɔːrnɪŋ ˌsɪstəm/", definition: "a system that detects danger early enough for people to prepare", example: "An early-warning system gave residents time to evacuate.", exampleTranslation: "منح نظام إنذار مبكر السكان وقتًا للإخلاء.", category: "climate adaptation", tags: ["environment", "safety"], synonyms: ["advance alert", "risk warning"] }),
      reviewed({ word: "relocation", translation: "إعادة توطين / نقل", pos: "noun", ipa: "/ˌriːloʊˈkeɪʃən/", definition: "the act of moving people, homes, or activities to another place", example: "Planned relocation may be necessary in the most exposed coastal areas.", exampleTranslation: "قد تكون إعادة التوطين المخططة ضرورية في المناطق الساحلية الأكثر تعرضًا.", category: "climate adaptation", tags: ["environment", "society"], synonyms: ["resettlement", "relocation"] }),
      reviewed({ word: "habitat restoration", translation: "استعادة الموائل الطبيعية", pos: "noun", ipa: "/ˈhæbɪtæt ˌrestəˈreɪʃən/", definition: "the process of repairing a natural environment so that species can live there", example: "Habitat restoration reduced erosion along the river.", exampleTranslation: "قللت استعادة الموائل الطبيعية التعرية على طول النهر.", category: "climate adaptation", tags: ["environment", "nature"], synonyms: ["ecological repair", "habitat recovery"] }),
      reviewed({ word: "risk assessment", translation: "تقييم المخاطر", pos: "noun", ipa: "/rɪsk əˈsesmənt/", definition: "a systematic examination of possible dangers and their effects", example: "The council completed a risk assessment before approving the project.", exampleTranslation: "أكمل المجلس تقييم المخاطر قبل الموافقة على المشروع.", category: "climate adaptation", tags: ["environment", "planning"], synonyms: ["hazard analysis", "risk review"] }),
    ],
    u55: [
      {
        word: "abandon",
        translation: "يتخلى عن / يهجر",
        translationLang: "ar",
        pos: "verb",
        ipa: "/əˈbændən/",
        definition: "to leave someone or something permanently or stop doing something",
        example: "The company abandoned the plan after the costs increased.",
        exampleTranslation: "تخلت الشركة عن الخطة بعد ارتفاع التكاليف.",
        synonyms: ["leave", "give up"],
        antonyms: ["keep", "continue"],
        collocations: ["abandon a plan", "abandon an idea"],
        wordFamily: ["abandon", "abandoned", "abandonment"],
        tags: ["business", "decisions"],
        category: "decision",
      },
      {
        word: "absorb",
        translation: "يمتص / يستوعب",
        translationLang: "ar",
        pos: "verb",
        ipa: "/əbˈzɔːrb/",
        definition: "to take in a liquid, energy, or information",
        example: "The training helped new staff absorb complex information.",
        exampleTranslation: "ساعد التدريب الموظفين الجدد على استيعاب المعلومات المعقدة.",
        synonyms: ["take in", "learn"],
        antonyms: ["release", "ignore"],
        collocations: ["absorb information", "absorb knowledge"],
        wordFamily: ["absorb", "absorption", "absorbed"],
        tags: ["learning", "business"],
        category: "learning",
      },
      {
        word: "abstract",
        translation: "مجرد / تجريدي",
        translationLang: "ar",
        pos: "adjective",
        ipa: "/ˈæbstrækt/",
        definition: "based on ideas rather than physical things or particular examples",
        example: "The report explains an abstract concept with a practical example.",
        exampleTranslation: "يشرح التقرير مفهومًا مجردًا بمثال عملي.",
        synonyms: ["theoretical", "conceptual"],
        antonyms: ["concrete", "practical"],
        collocations: ["abstract concept", "abstract idea"],
        wordFamily: ["abstract", "abstractly", "abstraction"],
        tags: ["thinking", "education"],
        category: "concept",
      },
      {
        word: "acceptable",
        translation: "مقبول",
        translationLang: "ar",
        pos: "adjective",
        ipa: "/əkˈseptəbəl/",
        definition: "good enough or allowed according to a rule or standard",
        example: "The revised proposal is acceptable to both sides.",
        exampleTranslation: "الاقتراح المعدل مقبول لدى الطرفين.",
        synonyms: ["satisfactory", "approved"],
        antonyms: ["unacceptable"],
        collocations: ["acceptable solution", "acceptable standard"],
        wordFamily: ["accept", "acceptable", "acceptance"],
        tags: ["business", "negotiation"],
        category: "evaluation",
      },
    ],
    u56: [
      {
        word: "accidentally",
        translation: "عن طريق الخطأ",
        translationLang: "ar",
        pos: "adverb",
        ipa: "/ˌæksɪˈdentəli/",
        definition: "in a way that is not planned or intended",
        example: "The researcher accidentally deleted the first draft.",
        exampleTranslation: "حذف الباحث المسودة الأولى عن طريق الخطأ.",
        synonyms: ["by mistake", "unintentionally"],
        antonyms: ["deliberately", "intentionally"],
        collocations: ["accidentally delete", "accidentally change"],
        wordFamily: ["accident", "accidental", "accidentally"],
        tags: ["research", "technology"],
        category: "manner",
      },
    ],
  },
  C1: {
    u57: [
      reviewed({ word: "biometric", translation: "بيومتري / حيوي", pos: "adjective", ipa: "/ˌbaɪoʊˈmetrɪk/", definition: "relating to measurements of a person’s physical or behavioural features", example: "Biometric systems should be tested for unequal error rates.", exampleTranslation: "ينبغي اختبار الأنظمة البيومترية بحثًا عن معدلات أخطاء غير متساوية.", category: "digital ethics", tags: ["technology", "privacy"], synonyms: ["identity-measuring", "biological"] }),
      reviewed({ word: "anonymity", translation: "إخفاء الهوية", pos: "noun", ipa: "/ˌænəˈnɪməti/", definition: "the state of not being identified or named", example: "Anonymity can protect people who report wrongdoing.", exampleTranslation: "يمكن لإخفاء الهوية حماية من يبلغون عن المخالفات.", category: "digital ethics", tags: ["technology", "privacy"], synonyms: ["namelessness", "privacy"] }),
      reviewed({ word: "encryption", translation: "تشفير", pos: "noun", ipa: "/ɪnˈkrɪpʃən/", definition: "the process of changing data into a form that only authorised users can read", example: "Strong encryption protects sensitive medical records.", exampleTranslation: "يحمي التشفير القوي السجلات الطبية الحساسة.", category: "digital ethics", tags: ["technology", "security"], synonyms: ["data coding", "secure encoding"] }),
      reviewed({ word: "explainability", translation: "قابلية التفسير", pos: "noun", ipa: "/ɪkˌspleɪnəˈbɪləti/", definition: "the quality of allowing people to understand how a system reaches a result", example: "Explainability is essential when an automated decision affects rights.", exampleTranslation: "تُعد قابلية التفسير أساسية عندما يؤثر قرار آلي في الحقوق.", category: "digital ethics", tags: ["technology", "governance"], synonyms: ["interpretability", "clarity"] }),
      reviewed({ word: "data minimisation", translation: "تقليل جمع البيانات", pos: "noun", ipa: "/ˈdeɪtə ˌmɪnɪməˈzeɪʃən/", definition: "the principle of collecting only the personal data that is genuinely needed", example: "Data minimisation limits the damage caused by a security breach.", exampleTranslation: "يحد تقليل جمع البيانات من الضرر الناتج عن خرق أمني.", category: "digital ethics", tags: ["technology", "privacy"], synonyms: ["limited collection", "data reduction"] }),
      reviewed({ word: "due process", translation: "الإجراءات القانونية الواجبة", pos: "noun", ipa: "/ˌdjuː ˈprɑːses/", definition: "fair legal procedures that protect a person’s rights before a decision is made", example: "Automated screening must not replace due process.", exampleTranslation: "يجب ألا يحل الفرز الآلي محل الإجراءات القانونية الواجبة.", category: "digital ethics", tags: ["law", "rights"], synonyms: ["fair procedure", "legal safeguards"] }),
      reviewed({ word: "redress", translation: "إنصاف / جبر الضرر", pos: "noun", ipa: "/rɪˈdres/", definition: "a remedy or process for correcting unfair treatment or harm", example: "Users need a clear route to redress when a system harms them.", exampleTranslation: "يحتاج المستخدمون إلى طريق واضح للإنصاف عندما يسبب لهم نظام ضررًا.", category: "digital ethics", tags: ["rights", "governance"], synonyms: ["remedy", "compensation"] }),
      reviewed({ word: "privacy-preserving", translation: "حافظ على الخصوصية", pos: "adjective", ipa: "/ˈpraɪvəsi prɪˈzɜːrvɪŋ/", definition: "designed to use or analyse information while reducing exposure of personal details", example: "The researchers developed a privacy-preserving method for sharing data.", exampleTranslation: "طور الباحثون طريقة تحافظ على الخصوصية لمشاركة البيانات.", category: "digital ethics", tags: ["technology", "privacy"], synonyms: ["privacy-protective", "confidential"] }),
    ],
    u58: [
      reviewed({ word: "preregistration", translation: "التسجيل المسبق للبحث", pos: "noun", ipa: "/ˌpriːredʒɪˈstreɪʃən/", definition: "the public recording of a study’s methods and hypotheses before data collection", example: "Preregistration reduces the temptation to change the hypothesis later.", exampleTranslation: "يقلل التسجيل المسبق للبحث إغراء تغيير الفرضية لاحقًا.", category: "research integrity", tags: ["research", "methods"], synonyms: ["pre-study registration", "study registration"] }),
      reviewed({ word: "peer review", translation: "مراجعة الأقران", pos: "noun", ipa: "/ˌpɪr rɪˈvjuː/", definition: "the evaluation of research by other specialists in the same field", example: "Peer review identified a weakness in the sampling method.", exampleTranslation: "كشفت مراجعة الأقران ضعفًا في طريقة أخذ العينات.", category: "research integrity", tags: ["research", "academic"], synonyms: ["scholarly review", "expert review"] }),
      reviewed({ word: "plagiarism", translation: "انتحال علمي", pos: "noun", ipa: "/ˈpleɪdʒərɪzəm/", definition: "presenting another person’s words or ideas as your own", example: "Clear citation rules help students avoid plagiarism.", exampleTranslation: "تساعد قواعد الاقتباس الواضحة الطلاب على تجنب الانتحال العلمي.", category: "research integrity", tags: ["academic", "writing"], synonyms: ["intellectual theft", "copying"] }),
      reviewed({ word: "authorship", translation: "تأليف علمي", pos: "noun", ipa: "/ˈɔːθərʃɪp/", definition: "the status or responsibility of being credited as a writer of research", example: "The team agreed on authorship before submitting the paper.", exampleTranslation: "اتفق الفريق على التأليف العلمي قبل تقديم الورقة.", category: "research integrity", tags: ["research", "academic"], synonyms: ["credit", "authorship status"] }),
      reviewed({ word: "data provenance", translation: "مصدر البيانات وتاريخها", pos: "noun", ipa: "/ˈdeɪtə ˈprɑːvənəns/", definition: "a record of where data came from and how it was changed or handled", example: "Data provenance made the analysis easier to audit.", exampleTranslation: "جعل توثيق مصدر البيانات وتاريخها التحليل أسهل للمراجعة.", category: "research integrity", tags: ["research", "data"], synonyms: ["data lineage", "origin record"] }),
      reviewed({ word: "replication", translation: "تكرار الدراسة", pos: "noun", ipa: "/ˌreplɪˈkeɪʃən/", definition: "the repetition of a study to see whether similar results are obtained", example: "Independent replication strengthened confidence in the finding.", exampleTranslation: "عزز تكرار الدراسة بصورة مستقلة الثقة في النتيجة.", category: "research integrity", tags: ["research", "methods"], synonyms: ["repeat study", "reproduction"] }),
      reviewed({ word: "p-hacking", translation: "التلاعب الإحصائي بالبحث", pos: "noun", ipa: "/ˈpiː ˌhækɪŋ/", definition: "repeatedly testing analyses until a result appears statistically significant", example: "A transparent analysis plan can reduce p-hacking.", exampleTranslation: "يمكن لخطة تحليل شفافة أن تقلل التلاعب الإحصائي بالبحث.", category: "research integrity", tags: ["research", "statistics"], synonyms: ["significance hunting", "selective analysis"] }),
      reviewed({ word: "research misconduct", translation: "سوء السلوك البحثي", pos: "noun", ipa: "/rɪˈsɜːrtʃ mɪsˌkɑːndʌkt/", definition: "serious dishonest or irresponsible behaviour in conducting or reporting research", example: "The institution investigated allegations of research misconduct.", exampleTranslation: "حققت المؤسسة في ادعاءات سوء السلوك البحثي.", category: "research integrity", tags: ["research", "ethics"], synonyms: ["academic misconduct", "research wrongdoing"] }),
    ],
    u59: [
      reviewed({ word: "anchoring", translation: "الترسيخ الذهني", pos: "noun", ipa: "/ˈæŋkərɪŋ/", definition: "the tendency to rely too heavily on the first information encountered", example: "Anchoring influenced the negotiator’s estimate of the price.", exampleTranslation: "أثر الترسيخ الذهني في تقدير المفاوض للسعر.", category: "cognitive bias", tags: ["thinking", "decisions"], synonyms: ["anchoring effect", "first-number effect"] }),
      reviewed({ word: "confirmation bias", translation: "انحياز التأكيد", pos: "noun", ipa: "/ˌkɑːnfərˈmeɪʃən baɪəs/", definition: "the tendency to notice evidence that supports existing beliefs more than evidence against them", example: "Confirmation bias can distort how people read political news.", exampleTranslation: "يمكن لانحياز التأكيد أن يشوه طريقة قراءة الناس للأخبار السياسية.", category: "cognitive bias", tags: ["thinking", "media"], synonyms: ["belief bias", "selective attention"] }),
      reviewed({ word: "availability heuristic", translation: "الاستدلال بالتوافر", pos: "noun", ipa: "/əˌveɪləˈbɪləti hjʊˈrɪstɪk/", definition: "a mental shortcut that judges likelihood by how easily examples come to mind", example: "The availability heuristic made the rare event seem common.", exampleTranslation: "جعل الاستدلال بالتوافر الحدث النادر يبدو شائعًا.", category: "cognitive bias", tags: ["thinking", "psychology"], synonyms: ["memory shortcut", "salience heuristic"] }),
      reviewed({ word: "hindsight bias", translation: "انحياز الإدراك المتأخر", pos: "noun", ipa: "/ˈhaɪndsaɪt baɪəs/", definition: "the tendency to see an event as predictable after it has happened", example: "Hindsight bias made the failed forecast appear obviously wrong.", exampleTranslation: "جعل انحياز الإدراك المتأخر التوقع الفاشل يبدو خاطئًا بوضوح.", category: "cognitive bias", tags: ["thinking", "decisions"], synonyms: ["knew-it-all-along effect"] }),
      reviewed({ word: "overconfidence", translation: "ثقة مفرطة", pos: "noun", ipa: "/ˌoʊvərˈkɑːnfɪdəns/", definition: "unjustified belief that one’s judgement or ability is more accurate than it is", example: "Overconfidence led the team to ignore the warning signs.", exampleTranslation: "أدت الثقة المفرطة إلى تجاهل الفريق إشارات التحذير.", category: "cognitive bias", tags: ["thinking", "decisions"], synonyms: ["excessive confidence", "self-assurance"], antonyms: ["humility"] }),
      reviewed({ word: "base rate", translation: "المعدل الأساسي", pos: "noun", ipa: "/ˈbeɪs reɪt/", definition: "the general frequency of an event before considering specific evidence", example: "The analyst ignored the base rate when assessing the risk.", exampleTranslation: "تجاهل المحلل المعدل الأساسي عند تقييم الخطر.", category: "cognitive bias", tags: ["statistics", "thinking"], synonyms: ["prior probability", "background frequency"] }),
      reviewed({ word: "motivated reasoning", translation: "الاستدلال بدافع مسبق", pos: "noun", ipa: "/ˈmoʊtɪveɪtɪd ˈriːzənɪŋ/", definition: "using reasoning selectively to reach a preferred conclusion", example: "Motivated reasoning can make a person defend a weak policy.", exampleTranslation: "يمكن للاستدلال بدافع مسبق أن يجعل الشخص يدافع عن سياسة ضعيفة.", category: "cognitive bias", tags: ["thinking", "politics"], synonyms: ["goal-directed reasoning", "biased reasoning"] }),
      reviewed({ word: "debiasing", translation: "تقليل الانحياز", pos: "noun", ipa: "/diːˈbaɪəsɪŋ/", definition: "the use of methods that reduce the influence of cognitive bias", example: "Structured checklists are a simple debiasing technique.", exampleTranslation: "تُعد قوائم التحقق المنظمة تقنية بسيطة لتقليل الانحياز.", category: "cognitive bias", tags: ["thinking", "decisions"], synonyms: ["bias reduction", "critical checking"] }),
    ],
    u60: [
      reviewed({ word: "rollout", translation: "طرح تدريجي", pos: "noun", ipa: "/ˈroʊlaʊt/", definition: "the organised introduction of a new policy, product, or system", example: "The department began a phased rollout of the new service.", exampleTranslation: "بدأ القسم طرحًا تدريجيًا للخدمة الجديدة.", category: "policy implementation", tags: ["government", "planning"], synonyms: ["launch", "introduction"] }),
      reviewed({ word: "compliance", translation: "امتثال", pos: "noun", ipa: "/kəmˈplaɪəns/", definition: "the act of obeying a law, rule, or requirement", example: "The regulator monitors compliance with the safety standard.", exampleTranslation: "تراقب الجهة المنظمة الامتثال لمعيار السلامة.", category: "policy implementation", tags: ["government", "law"], synonyms: ["conformity", "observance"], antonyms: ["violation"] }),
      reviewed({ word: "regulation", translation: "لائحة تنظيمية", pos: "noun", ipa: "/ˌreɡjəˈleɪʃən/", definition: "an official rule made by an authority to control an activity", example: "The regulation sets minimum standards for care.", exampleTranslation: "تحدد اللائحة التنظيمية الحد الأدنى لمعايير الرعاية.", category: "policy implementation", tags: ["government", "law"], synonyms: ["rule", "requirement"] }),
      reviewed({ word: "enforcement", translation: "إنفاذ", pos: "noun", ipa: "/ɪnˈfɔːrsmənt/", definition: "the process of making sure that a law or rule is obeyed", example: "Effective enforcement requires trained inspectors.", exampleTranslation: "يتطلب الإنفاذ الفعال مفتشين مدربين.", category: "policy implementation", tags: ["government", "law"], synonyms: ["execution", "application"] }),
      reviewed({ word: "mandate", translation: "تكليف رسمي / إلزام", pos: "noun", ipa: "/ˈmændeɪt/", definition: "an official order or authority to do something", example: "The agency received a mandate to improve access.", exampleTranslation: "تلقت الوكالة تكليفًا رسميًا لتحسين الوصول.", category: "policy implementation", tags: ["government", "law"], synonyms: ["order", "authority"] }),
      reviewed({ word: "evaluation", translation: "تقييم", pos: "noun", ipa: "/ɪˌvæljuˈeɪʃən/", definition: "a careful judgement of the effectiveness or value of something", example: "The evaluation found that the programme reached fewer people than expected.", exampleTranslation: "وجد التقييم أن البرنامج وصل إلى عدد أقل من المتوقع.", category: "policy implementation", tags: ["government", "research"], synonyms: ["assessment", "review"] }),
      reviewed({ word: "unintended consequence", translation: "نتيجة غير مقصودة", pos: "noun", ipa: "/ˌʌnɪnˈtendɪd ˈkɑːnsəkwens/", definition: "an effect of an action that was not planned or expected", example: "The subsidy had the unintended consequence of raising rents.", exampleTranslation: "كان لِلإعانة نتيجة غير مقصودة تمثلت في رفع الإيجارات.", category: "policy implementation", tags: ["government", "thinking"], synonyms: ["side effect", "unexpected result"] }),
      reviewed({ word: "public consultation", translation: "تشاور عام", pos: "noun", ipa: "/ˈpʌblɪk ˌkɑːnsəlˈteɪʃən/", definition: "a process of asking the public for views before making a decision", example: "The council opened a public consultation on the transport plan.", exampleTranslation: "فتح المجلس تشاورًا عامًا حول خطة النقل.", category: "policy implementation", tags: ["government", "society"], synonyms: ["public feedback", "community consultation"] }),
    ],
    u61: [
      reviewed({ word: "longitudinal", translation: "طولي / ممتد زمنيًا", pos: "adjective", ipa: "/ˌlɑːndʒəˈtuːdənəl/", definition: "following the same people or subjects over a period of time", example: "A longitudinal study tracked changes in wellbeing for five years.", exampleTranslation: "تابعت دراسة طولية تغيرات الرفاه لمدة خمس سنوات.", category: "research design", tags: ["research", "methods"], synonyms: ["long-term", "over-time"] }),
      reviewed({ word: "triangulate", translation: "يثلث الأدلة / يقارن مصادر متعددة", pos: "verb", ipa: "/traɪˈæŋɡjəleɪt/", definition: "to use several methods or sources to check a finding", example: "The researchers triangulated interviews with survey data.", exampleTranslation: "قارن الباحثون المقابلات ببيانات الاستبيان للتحقق من النتيجة.", category: "research design", tags: ["research", "methods"], synonyms: ["cross-check", "corroborate"] }),
      reviewed({ word: "generalisability", translation: "قابلية التعميم", pos: "noun", ipa: "/ˌdʒenərələˈzaɪəbɪləti/", definition: "the extent to which findings apply beyond the particular study sample", example: "The small sample limits the generalisability of the conclusion.", exampleTranslation: "تحد العينة الصغيرة من قابلية تعميم الاستنتاج.", category: "research design", tags: ["research", "statistics"], synonyms: ["transferability", "wider applicability"] }),
      reviewed({ word: "operationalise", translation: "يحوّل المفهوم إلى مقياس عملي", pos: "verb", ipa: "/ˌɑːpəˈreɪʃənəlaɪz/", definition: "to define an abstract concept in a way that can be measured", example: "The team operationalised trust through three survey questions.", exampleTranslation: "حوّل الفريق الثقة إلى مقياس عملي عبر ثلاثة أسئلة في الاستبيان.", category: "research design", tags: ["research", "measurement"], synonyms: ["measure", "define operationally"] }),
      reviewed({ word: "measurement error", translation: "خطأ القياس", pos: "noun", ipa: "/ˈmeʒərmənt ˈerər/", definition: "a difference between a measured value and the true value", example: "Repeated observations helped estimate measurement error.", exampleTranslation: "ساعدت الملاحظات المتكررة على تقدير خطأ القياس.", category: "research design", tags: ["research", "statistics"], synonyms: ["measurement inaccuracy", "observational error"] }),
      reviewed({ word: "sampling frame", translation: "إطار المعاينة", pos: "noun", ipa: "/ˈsæmplɪŋ freɪm/", definition: "the list or source from which a research sample is selected", example: "An incomplete sampling frame can exclude important groups.", exampleTranslation: "يمكن لإطار معاينة غير مكتمل أن يستبعد مجموعات مهمة.", category: "research design", tags: ["research", "statistics"], synonyms: ["sample list", "sampling register"] }),
      reviewed({ word: "causal inference", translation: "استدلال سببي", pos: "noun", ipa: "/ˈkɔːzəl ˈɪnfərəns/", definition: "a reasoned conclusion that one factor produces a change in another", example: "The design was strengthened to support causal inference.", exampleTranslation: "عُزز التصميم لدعم الاستدلال السببي.", category: "research design", tags: ["research", "thinking"], synonyms: ["cause-effect reasoning", "causal conclusion"] }),
      reviewed({ word: "external validity", translation: "الصدق الخارجي", pos: "noun", ipa: "/ɪkˈstɜːrnəl vəˈlɪdəti/", definition: "the extent to which study results apply to other people or settings", example: "Researchers discussed external validity before applying the results nationally.", exampleTranslation: "ناقش الباحثون الصدق الخارجي قبل تطبيق النتائج على المستوى الوطني.", category: "research design", tags: ["research", "methods"], synonyms: ["generalisability", "wider validity"] }),
    ],
    u54: [
      {
        word: "abolish",
        translation: "يلغي",
        translationLang: "ar",
        pos: "verb",
        ipa: "/əˈbɑːlɪʃ/",
        definition: "to officially end a law, system, or practice",
        example: "The reform aims to abolish an outdated regulation.",
        exampleTranslation: "يهدف الإصلاح إلى إلغاء لائحة قديمة.",
        synonyms: ["eliminate", "end"],
        antonyms: ["establish", "introduce"],
        collocations: ["abolish a law", "abolish a system"],
        wordFamily: ["abolish", "abolition", "abolitionist"],
        tags: ["government", "law"],
        category: "politics",
      },
      {
        word: "absent",
        translation: "غائب / غير موجود",
        translationLang: "ar",
        pos: "adjective",
        ipa: "/ˈæbsənt/",
        definition: "not present in a place or situation",
        example: "Several important voices were absent from the public debate.",
        exampleTranslation: "كانت عدة أصوات مهمة غائبة عن النقاش العام.",
        synonyms: ["missing", "away"],
        antonyms: ["present"],
        collocations: ["absent from a debate", "noticeably absent"],
        wordFamily: ["absent", "absence", "absentee"],
        tags: ["government", "communication"],
        category: "condition",
      },
      {
        word: "abuse",
        translation: "إساءة استعمال / انتهاك",
        translationLang: "ar",
        pos: "noun",
        ipa: "/əˈbjuːs/",
        definition: "the improper or harmful use of power, authority, or a person",
        example: "Independent oversight can help prevent abuse of public power.",
        exampleTranslation: "يمكن للرقابة المستقلة أن تساعد على منع إساءة استعمال السلطة العامة.",
        synonyms: ["misuse", "mistreatment"],
        antonyms: ["protection", "care"],
        collocations: ["abuse of power", "prevent abuse"],
        wordFamily: ["abuse", "abusive"],
        tags: ["government", "society"],
        category: "ethics",
      },
    ],
    u55: [
      {
        word: "absurd",
        translation: "سخيف / غير منطقي",
        translationLang: "ar",
        pos: "adjective",
        ipa: "/əbˈsɜːrd/",
        definition: "completely unreasonable, illogical, or ridiculous",
        example: "The article challenges an absurd assumption about research.",
        exampleTranslation: "يتحدى المقال افتراضًا غير منطقي حول البحث.",
        synonyms: ["ridiculous", "illogical"],
        antonyms: ["reasonable", "logical"],
        collocations: ["absurd assumption", "absurd argument"],
        wordFamily: ["absurd", "absurdity", "absurdly"],
        tags: ["research", "critical thinking"],
        category: "evaluation",
      },
      {
        word: "abundance",
        translation: "وفرة",
        translationLang: "ar",
        pos: "noun",
        ipa: "/əˈbʌndəns/",
        definition: "a large quantity of something",
        example: "The study provides an abundance of evidence for the conclusion.",
        exampleTranslation: "تقدم الدراسة وفرة من الأدلة على الاستنتاج.",
        synonyms: ["plenty", "wealth"],
        antonyms: ["scarcity", "shortage"],
        collocations: ["abundance of evidence", "in abundance"],
        wordFamily: ["abound", "abundant", "abundance"],
        tags: ["research", "academic"],
        category: "quantity",
      },
    ],
  },
};
