// Additional Finnish curriculum units u32-u33 for every CEFR level.
// Deterministic local curriculum data; APIs may enrich it but never generate it.
type Word = { word: string; translation: string; pos: string; example: string; exampleTranslation: string };
type Unit = { id: string; title: string; description: string; words: Word[]; phrases: { phrase: string; translation: string }[]; dialogue: { speaker: string; text: string; translation: string }[]; reading: { title: string; text: string; translation: string } };
const w = (word: string, translation: string, pos: string, example: string, exampleTranslation: string): Word => ({ word, translation, pos, example, exampleTranslation });
const u = (id: string, title: string, description: string, words: Word[]): Unit => ({
  id, title, description, words,
  phrases: words.slice(0, 4).map((item) => ({ phrase: item.example, translation: item.exampleTranslation })),
  dialogue: [
    { speaker: "A", text: words[0]!.example, translation: words[0]!.exampleTranslation },
    { speaker: "B", text: words[1]!.example, translation: words[1]!.exampleTranslation },
    { speaker: "A", text: words[2]!.example, translation: words[2]!.exampleTranslation },
    { speaker: "B", text: words[3]!.example, translation: words[3]!.exampleTranslation },
  ],
  reading: { title, text: words.slice(0, 4).map((item) => item.example).join(" "), translation: words.slice(0, 4).map((item) => item.exampleTranslation).join(" ") },
});

export const ADDITIONAL_FI_PART5_UNITS: Record<string, Unit[]> = {
  A0: [
    u("u32", "Päivän aika", "Kerro kellonaika ja kuvaile päivän osia.", [
      w("aamu", "morning", "noun", "Opiskelen aamulla.", "I study in the morning."),
      w("iltapäivä", "afternoon", "noun", "Tapaamme iltapäivällä.", "We meet in the afternoon."),
      w("ilta", "evening", "noun", "Ilta on rauhallinen.", "The evening is quiet."),
      w("yö", "night", "noun", "Nukun yöllä.", "I sleep at night."),
      w("tänään", "today", "adverb", "Tänään on maanantai.", "Today is Monday."),
      w("huomenna", "tomorrow", "adverb", "Nähdään huomenna.", "See you tomorrow."),
      w("aikaisin", "early", "adverb", "Herään aikaisin.", "I wake up early."),
      w("myöhässä", "late", "adverb", "Bussi on myöhässä.", "The bus is late."),
    ]),
    u("u33", "Helppoja tunteita", "Ilmaise muutamia perustunteita ja tarpeita.", [
      w("onnellinen", "happy", "adjective", "Olen tänään onnellinen.", "I am happy today."),
      w("surullinen", "sad", "adjective", "Hän on surullinen.", "She feels sad."),
      w("väsynyt", "tired", "adjective", "Olen töiden jälkeen väsynyt.", "I am tired after work."),
      w("nälkäinen", "hungry", "adjective", "Lapset ovat nälkäisiä.", "The children are hungry."),
      w("janoinen", "thirsty", "adjective", "Olen janoinen.", "I am thirsty."),
      w("kylmä", "cold", "adjective", "Käteni ovat kylmät.", "My hands are cold."),
      w("kuuma", "hot", "adjective", "Tee on kuumaa.", "The tea is hot."),
      w("pelokas", "afraid", "adjective", "Lapsi on pelokas.", "The child is afraid."),
    ]),
  ],
  A1: [
    u("u32", "Kodin rutiinit", "Kuvaile kotitöitä ja helppoja rutiineja kotona.", [
      w("siivota", "clean", "verb", "Siivoan keittiön lauantaina.", "I clean the kitchen on Saturday."),
      w("pestä", "wash", "verb", "Pesemme astiat päivällisen jälkeen.", "We wash the dishes after dinner."),
      w("laittaa ruokaa", "cook", "verb", "Veljeni laittaa lounasta.", "My brother cooks lunch."),
      w("järjestää", "tidy", "verb", "Järjestä huoneesi, ole hyvä.", "Please tidy your room."),
      w("lattia", "floor", "noun", "Lattia on puhdas.", "The floor is clean."),
      w("ikkuna", "window", "noun", "Avaa ikkuna, ole hyvä.", "Open the window, please."),
      w("pyyhe", "towel", "noun", "Pyyhe on kylpyhuoneessa.", "The towel is in the bathroom."),
      w("avain", "key", "noun", "Jätin avaimeni kotiin.", "I left my key at home."),
    ]),
    u("u33", "Vapaa-aika", "Kerro harrastuksista ja tekemisestä koulun tai työn jälkeen.", [
      w("harrastus", "hobby", "noun", "Lukeminen on lempiharrastukseni.", "Reading is my favourite hobby."),
      w("musiikki", "music", "noun", "Kuuntelen musiikkia joka päivä.", "I listen to music every day."),
      w("elokuva", "film", "noun", "Katsoimme hauskan elokuvan.", "We watched a funny film."),
      w("tanssia", "dance", "verb", "He tanssivat viikonloppuna.", "They dance at the weekend."),
      w("piirtää", "draw", "verb", "Hän piirtää mielellään eläimiä.", "She likes to draw animals."),
      w("leikkiä", "play", "verb", "Lapset leikkivät ulkona.", "The children play outside."),
      w("rentoutua", "relax", "verb", "Rentoudun kirjan kanssa.", "I relax with a book."),
      w("viikonloppu", "weekend", "noun", "Viikonloppumme alkaa perjantaina.", "Our weekend starts on Friday."),
    ]),
  ],
  A2: [
    u("u32", "Oppimisstrategiat", "Keskustele tavoista oppia ja muistaa uutta tietoa.", [
      w("menetelmä", "method", "noun", "Tämä menetelmä auttaa muistamaan sanat.", "This method helps me remember words."),
      w("harjoittelu", "practice", "noun", "Säännöllinen harjoittelu lisää itsevarmuutta.", "Regular practice builds confidence."),
      w("virhe", "mistake", "noun", "Jokainen virhe voi opettaa jotakin.", "Every mistake can teach us something."),
      w("edistyminen", "progress", "noun", "Näen edistymiseni tässä kuussa.", "I can see my progress this month."),
      w("kerrata", "review", "verb", "Kertaan oppitunnin ennen nukkumaanmenoa.", "I review the lesson before bed."),
      w("muistaa ulkoa", "memorise", "verb", "Hän muistaa viisi sanaa ulkoa päivässä.", "She memorises five words a day."),
      w("kuvitella", "imagine", "verb", "Kuvittele sana lauseessa.", "Imagine the word in a sentence."),
      w("keskittyä", "concentrate", "verb", "Hiljaisessa huoneessa on helpompi keskittyä.", "It is easier to concentrate in a quiet room."),
    ]),
    u("u33", "Matkakokemukset", "Kuvaile matkoja, nähtävyyksiä ja kokemuksia ulkomailla.", [
      w("nähtävyys", "sight", "noun", "Vanha silta on kuuluisa nähtävyys.", "The old bridge is a famous sight."),
      w("matka", "journey", "noun", "Matka kesti neljä tuntia.", "The journey took four hours."),
      w("opas", "guide", "noun", "Oppaamme kertoi historiasta.", "Our guide explained the history."),
      w("väkijoukko", "crowd", "noun", "Suuri väkijoukko odotti ulkona.", "A large crowd waited outside."),
      w("tutkia", "explore", "verb", "Tutkimme vanhaa kaupunkia jalan.", "We explored the old town on foot."),
      w("suositella", "recommend", "verb", "Suosittelen tätä pientä museota.", "I recommend this small museum."),
      w("uskoa", "believe", "verb", "En voinut uskoa näkymää.", "I could not believe the view."),
      w("palata", "return", "verb", "Palasimme kotiin sunnuntaina.", "We returned home on Sunday."),
    ]),
  ],
  B1: [
    u("u32", "Viestintä työssä", "Hoitakaa työviestejä, kokouksia ja määräaikoja.", [
      w("määräaika", "deadline", "noun", "Määräaika on ensi perjantaina.", "The deadline is next Friday."),
      w("sopia", "schedule", "verb", "Sovimme kokouksen keskipäiväksi.", "We scheduled a meeting for noon."),
      w("esityslista", "agenda", "noun", "Esityslistalla on kolme kohtaa.", "The agenda has three points."),
      w("päivitys", "update", "noun", "Lähetä minulle päivitys.", "Please send me an update."),
      w("selventää", "clarify", "verb", "Voisitko selventää viimeisen kohdan?", "Could you clarify the last point?"),
      w("vahvistaa", "confirm", "verb", "Vahvista saatavuutesi.", "Please confirm your availability."),
      w("siirtää", "postpone", "verb", "Meidän piti siirtää kokousta.", "We had to postpone the meeting."),
      w("osallistua", "attend", "verb", "Kaikki tiimin jäsenet osallistuivat puheluun.", "All team members attended the call."),
    ]),
    u("u33", "Terveys ja elämäntapa", "Keskustele fyysistä ja henkistä terveyttä tukevista tavoista.", [
      w("hyvinvointi", "well-being", "noun", "Uni on tärkeää hyvinvoinnille.", "Sleep is important for well-being."),
      w("stressi", "stress", "noun", "Liika stressi vaikuttaa keskittymiseen.", "Too much stress affects concentration."),
      w("rutiini", "routine", "noun", "Vakaa rutiini voi auttaa.", "A stable routine can help."),
      w("tasapaino", "balance", "noun", "Työn ja elämän tasapaino on tärkeä.", "Work-life balance matters."),
      w("ehkäistä", "prevent", "verb", "Liikunta voi ehkäistä ongelmia.", "Exercise can prevent some problems."),
      w("toipua", "recover", "verb", "Hän toipui nopeasti sairauden jälkeen.", "She recovered quickly after the illness."),
      w("vähentää", "reduce", "verb", "Kävely voi vähentää stressiä.", "Walking can reduce stress."),
      w("ylläpitää", "maintain", "verb", "Uuden tavan ylläpitäminen on vaikeaa.", "It is hard to maintain a new habit."),
    ]),
  ],
  B2: [
    u("u32", "Kaupunkikehitys", "Väitelkää siitä, miten kaupungit voivat kasvaa oikeudenmukaisesti ja kestävästi.", [
      w("infrastruktuuri", "infrastructure", "noun", "Kaupunki tarvitsee paremman infrastruktuurin.", "The city needs better infrastructure."),
      w("asuminen", "housing", "noun", "Kohtuuhintaista asumista on vaikea löytää.", "Affordable housing is difficult to find."),
      w("tiheys", "density", "noun", "Suuri tiheys muuttaa kaupunginosia.", "High density changes neighbourhoods."),
      w("työmatka", "commute", "noun", "Työmatkani kestää neljäkymmentä minuuttia.", "My commute takes forty minutes."),
      w("laajentaa", "expand", "verb", "Kaupunki aikoo laajentaa raitiotieverkostoa.", "The city plans to expand the tram network."),
      w("uudistaa", "regenerate", "verb", "Hanke uudistaa vanhan kaupunginosan.", "The project will regenerate an old district."),
      w("syrjäyttää", "displace", "verb", "Uudet rakennukset voivat syrjäyttää paikallisia asukkaita.", "New buildings may displace local residents."),
      w("priorisoida", "prioritise", "verb", "Suunnittelijoiden pitäisi priorisoida jalankulkijoita.", "Planners should prioritise pedestrians."),
    ]),
    u("u33", "Digitaalinen kansalaisuus", "Arvioi vastuuta, yksityisyyttä ja käyttäytymistä verkossa.", [
      w("identiteetti", "identity", "noun", "Suojaa digitaalinen identiteettisi.", "Protect your digital identity."),
      w("yksityisyys", "privacy", "noun", "Verkkoyksityisyys vaatii huomiota.", "Online privacy requires attention."),
      w("suostumus", "consent", "noun", "Sovelluksen täytyy pyytää suostumus.", "The app must ask for consent."),
      w("väärä tieto", "misinformation", "noun", "Väärä tieto leviää nopeasti.", "Misinformation spreads quickly."),
      w("varmistaa", "verify", "verb", "Varmista aina yllättävä väite.", "Always verify a surprising claim."),
      w("ilmoittaa", "report", "verb", "Käyttäjät voivat ilmoittaa haitallisesta sisällöstä.", "Users can report harmful content."),
      w("salata", "encrypt", "verb", "Palvelu salaa henkilötiedot.", "The service encrypts personal data."),
      w("valvoa", "moderate", "verb", "Alustojen täytyy valvoa loukkaavia kommentteja.", "Platforms must moderate abusive comments."),
    ]),
  ],
  C1: [
    u("u32", "Koulutus ja mahdollisuudet", "Analysoi, miten koulutus luo mahdollisuuksia tai eriarvoisuutta.", [
      w("koulutustaso", "attainment", "noun", "Koulutustaso vaihtelee paljon.", "Educational attainment varies widely."),
      w("opetussuunnitelma", "curriculum", "noun", "Opetussuunnitelma sisältää käytännön taitoja.", "The curriculum includes practical skills."),
      w("yhdenvertaisuus", "equity", "noun", "Yhdenvertaisuus ei tarkoita kaikkien kohtelua täysin samalla tavalla.", "Equity is different from treating everyone identically."),
      w("este", "barrier", "noun", "Hinta on edelleen opiskelun este.", "Cost remains a barrier to study."),
      w("helpottaa", "facilitate", "verb", "Kirjastot helpottavat itsenäistä oppimista.", "Libraries facilitate independent learning."),
      w("laajentaa", "broaden", "verb", "Matkustaminen voi laajentaa opiskelijan näkökulmaa.", "Travel can broaden a student's perspective."),
      w("arvioida", "assess", "verb", "Opettajat arvioivat edistymistä monella tavalla.", "Teachers assess progress in several ways."),
      w("syrjiä", "discriminate", "verb", "Oikeudenmukainen järjestelmä ei saa syrjiä.", "A fair system must not discriminate."),
    ]),
    u("u33", "Ilmastoon sopeutuminen", "Keskustele siitä, miten yhteisöt vastaavat ympäristön muutoksiin.", [
      w("sopeutuminen", "adaptation", "noun", "Ilmastoon sopeutuminen vaatii pitkän aikavälin suunnittelua.", "Climate adaptation needs long-term planning."),
      w("kuivuus", "drought", "noun", "Alue kärsi vakavasta kuivuudesta.", "The region suffered a severe drought."),
      w("tulviminen", "flooding", "noun", "Tulviminen vahingoitti useita teitä.", "Flooding damaged several roads."),
      w("päästö", "emission", "noun", "Politiikan tavoitteena on vähentää päästöjä.", "The policy aims to cut emissions."),
      w("ennakoida", "anticipate", "verb", "Kaupunkien täytyy ennakoida äärisäätä.", "Cities must anticipate extreme weather."),
      w("lieventää", "mitigate", "verb", "Puut voivat lieventää kaupunkien kuumuutta.", "Trees can mitigate urban heat."),
      w("ennallistaa", "restore", "verb", "Kosteikot auttavat ennallistamaan luonnollista suojaa.", "Wetlands help restore natural protection."),
      w("toteuttaa", "implement", "verb", "Viranomaiset toteuttivat varoitusjärjestelmän.", "Local authorities implemented a warning system."),
    ]),
  ],
  C2: [
    u("u32", "Tulkinta ja valta", "Tutki, miten tulkinta muovaa instituutioita ja julkista elämää.", [
      w("diskurssi", "discourse", "noun", "Poliittinen diskurssi voi rajata ongelman näkökulmaa.", "Political discourse can frame a problem narrowly."),
      w("ideologia", "ideology", "noun", "Ideologia vaikuttaa siihen, mitä pidetään todisteena.", "Ideology influences what counts as evidence."),
      w("kertomus", "narrative", "noun", "Kertomus hallitsi julkista keskustelua.", "The narrative dominated public debate."),
      w("legitimiteetti", "legitimacy", "noun", "Instituutiot tarvitsevat julkista legitimiteettiä.", "Institutions need public legitimacy."),
      w("paljastaa", "expose", "verb", "Raportti paljastaa piilevän oletuksen.", "The report exposes a hidden assumption."),
      w("kiistää", "contest", "verb", "Kansalaiset kiistivät virallisen kertomuksen.", "Citizens contested the official narrative."),
      w("oikeuttaa", "legitimise", "verb", "Tilastot voivat oikeuttaa politiikan.", "Statistics can legitimise a policy."),
      w("kehystää uudelleen", "reframe", "verb", "Essee kehystää keskustelun uudelleen.", "The essay reframes the debate."),
    ]),
    u("u33", "Teknologian etiikka", "Arvioi edistyneen teknologian synnyttämiä vaikeita valintoja.", [
      w("autonomia", "autonomy", "noun", "Automaatio voi haastaa ihmisen autonomian.", "Automation can challenge human autonomy."),
      w("harha", "bias", "noun", "Malli voi toistaa yhteiskunnallista harhaa.", "The model may reproduce social bias."),
      w("läpinäkyvyys", "transparency", "noun", "Läpinäkyvyys on välttämätöntä vastuuvelvollisuudelle.", "Transparency is essential for accountability."),
      w("valvonta", "surveillance", "noun", "Massavalvonta herättää vakavia huolia.", "Mass surveillance raises serious concerns."),
      w("säännellä", "regulate", "verb", "Hallitusten on vaikea säännellä uusia järjestelmiä.", "Governments struggle to regulate new systems."),
      w("suojata", "safeguard", "verb", "Sääntöjen pitäisi suojata haavoittuvia ihmisiä.", "Rules should safeguard vulnerable people."),
      w("paljastaa", "disclose", "verb", "Yritysten pitäisi paljastaa, miten tietoja käytetään.", "Companies should disclose how data is used."),
      w("punnita", "weigh", "verb", "Päättäjien täytyy punnita ristiriitaisia arvoja.", "Decision-makers must weigh competing values."),
    ]),
  ],
};
