import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/**
 * Focused C1 enrichment for the existing Institutions and Reform, Memory and
 * Identity, and Ethics and Technology units. This bank is intentionally kept
 * separate from the larger reviewed bank while its placement is audited.
 */
export const ENGLISH_C1_FOCUSED_ENRICHMENTS: Record<string, VocabularyItem[]> = {
  u44: [
    reviewed({ word: "bureaucracy", translation: "بيروقراطية", pos: "noun", ipa: "/bjʊˈrɑːkrəsi/", definition: "a system of administration with many official rules, procedures, and layers of authority", example: "The reform was designed to reduce bureaucracy without weakening public accountability.", exampleTranslation: "صُمم الإصلاح لتقليل البيروقراطية من دون إضعاف المساءلة العامة.", category: "institutions and reform", tags: ["government", "society"], synonyms: ["administration", "officialdom"] }),
    reviewed({ word: "decentralise", translation: "يلامركز", pos: "verb", ipa: "/ˌdiːˈsentrəlaɪz/", definition: "to distribute power, decision-making, or responsibility away from a central authority", example: "The proposal would decentralise services so local communities could respond faster.", exampleTranslation: "من شأن المقترح أن يوزع الخدمات لامركزيًا كي تستجيب المجتمعات المحلية بسرعة أكبر.", category: "institutions and reform", tags: ["government", "reform"], synonyms: ["devolve", "distribute authority"] }),
    reviewed({ word: "streamline", translation: "يبسط الإجراءات", pos: "verb", ipa: "/ˈstriːmlaɪn/", definition: "to simplify a process by removing unnecessary steps or delays", example: "The agency streamlined applications while keeping the final review independent.", exampleTranslation: "بسّطت الوكالة طلبات التقديم مع إبقاء المراجعة النهائية مستقلة.", category: "institutions and reform", tags: ["government", "efficiency"], synonyms: ["simplify", "rationalise"] }),
    reviewed({ word: "watchdog", translation: "جهة رقابية", pos: "noun", ipa: "/ˈwɑːtʃdɔːɡ/", definition: "an organisation that monitors an activity to protect the public interest", example: "The watchdog published a report on unequal access to public services.", exampleTranslation: "نشرت الجهة الرقابية تقريرًا عن عدم تكافؤ الوصول إلى الخدمات العامة.", category: "institutions and reform", tags: ["government", "accountability"], synonyms: ["monitoring body", "oversight organisation"] }),
    reviewed({ word: "red tape", translation: "تعقيدات إدارية", pos: "noun", ipa: "/ˌred ˈteɪp/", definition: "excessive official rules and procedures that delay action", example: "Small organisations struggled to obtain funding because of red tape.", exampleTranslation: "واجهت المنظمات الصغيرة صعوبة في الحصول على التمويل بسبب التعقيدات الإدارية.", category: "institutions and reform", tags: ["government", "administration"], synonyms: ["administrative obstacles", "procedural delay"] }),
    reviewed({ word: "policy coherence", translation: "اتساق السياسات", pos: "noun", ipa: "/ˈpɑːləsi koʊˌhɪrəns/", definition: "the quality of different policies fitting together rather than creating contradictions", example: "Policy coherence is essential when housing, transport, and climate plans overlap.", exampleTranslation: "يُعد اتساق السياسات أساسيًا عندما تتداخل خطط الإسكان والنقل والمناخ.", category: "institutions and reform", tags: ["government", "planning"], synonyms: ["policy consistency", "strategic alignment"] }),
    reviewed({ word: "institutional trust", translation: "الثقة بالمؤسسات", pos: "noun", ipa: "/ˌɪnstɪˈtuːʃənəl trʌst/", definition: "public confidence that institutions act competently, fairly, and in the public interest", example: "Transparent investigations can rebuild institutional trust after a crisis.", exampleTranslation: "يمكن للتحقيقات الشفافة أن تعيد بناء الثقة بالمؤسسات بعد أزمة.", category: "institutions and reform", tags: ["government", "society"], synonyms: ["public confidence", "confidence in institutions"] }),
    reviewed({ word: "legislative scrutiny", translation: "تدقيق تشريعي", pos: "noun", ipa: "/ˈledʒɪsleɪtɪv ˈskruːtəni/", definition: "careful examination of proposed laws by a legislature or its committees", example: "The bill changed substantially after legislative scrutiny.", exampleTranslation: "تغير مشروع القانون بصورة كبيرة بعد التدقيق التشريعي.", category: "institutions and reform", tags: ["government", "law"], synonyms: ["parliamentary review", "legal examination"] }),
  ],
  u45: [
    reviewed({ word: "autobiographical memory", translation: "ذاكرة السيرة الذاتية", pos: "noun", ipa: "/ˌɔːtoʊˌbaɪəˈɡræfɪkəl ˈmeməri/", definition: "memory for experiences and events from one’s own life", example: "Autobiographical memory helps people connect present choices with earlier experiences.", exampleTranslation: "تساعد ذاكرة السيرة الذاتية الناس على ربط اختياراتهم الحالية بتجارب سابقة.", category: "memory and identity", tags: ["psychology", "identity"], synonyms: ["personal memory", "life-event memory"] }),
    reviewed({ word: "recollection", translation: "تذكّر / ذكرى", pos: "noun", ipa: "/ˌrekəˈlekʃən/", definition: "the act of remembering something or a memory of a past event", example: "Her recollection of the conversation differed from the written record.", exampleTranslation: "اختلف تذكرها للمحادثة عن السجل المكتوب.", category: "memory and identity", tags: ["psychology", "communication"], synonyms: ["remembrance", "memory"] }),
    reviewed({ word: "reminiscence", translation: "استرجاع ذكريات", pos: "noun", ipa: "/ˌremɪˈnɪsns/", definition: "a story or reflection about an experience from the past", example: "The interview became a reminiscence about life in the old neighbourhood.", exampleTranslation: "تحولت المقابلة إلى استرجاع لذكريات الحياة في الحي القديم.", category: "memory and identity", tags: ["memory", "storytelling"], synonyms: ["recollection", "memory story"] }),
    reviewed({ word: "mnemonic", translation: "وسيلة تذكّر", pos: "noun", ipa: "/nɪˈmɑːnɪk/", definition: "a word, image, pattern, or technique that helps someone remember information", example: "The learner invented a mnemonic for the order of the historical periods.", exampleTranslation: "ابتكر المتعلم وسيلة تذكر لترتيب الفترات التاريخية.", category: "memory and identity", tags: ["learning", "psychology"], synonyms: ["memory aid", "memory technique"] }),
    reviewed({ word: "narrative identity", translation: "الهوية السردية", pos: "noun", ipa: "/ˈnærətɪv aɪˈdentəti/", definition: "the sense of self formed through the story a person tells about their life", example: "Migration can reshape a person’s narrative identity without erasing earlier attachments.", exampleTranslation: "يمكن للهجرة أن تعيد تشكيل الهوية السردية للشخص من دون محو ارتباطاته السابقة.", category: "memory and identity", tags: ["identity", "society"], synonyms: ["life-story identity", "self-narrative"] }),
    reviewed({ word: "self-concept", translation: "مفهوم الذات", pos: "noun", ipa: "/ˌself ˈkɑːnsept/", definition: "the beliefs and ideas a person has about their own character and abilities", example: "Supportive feedback can improve a learner’s self-concept.", exampleTranslation: "يمكن للتغذية الراجعة الداعمة أن تحسن مفهوم المتعلم لذاته.", category: "memory and identity", tags: ["psychology", "learning"], synonyms: ["self-image", "sense of self"] }),
    reviewed({ word: "traumatic recall", translation: "استرجاع صادم للذكرى", pos: "noun", ipa: "/trəˈmætɪk rɪˈkɔːl/", definition: "the remembering of an extremely distressing event or experience", example: "The counsellor explained that traumatic recall may be fragmented and unpredictable.", exampleTranslation: "شرح المستشار أن استرجاع الذكرى الصادمة قد يكون متقطعًا وغير متوقع.", category: "memory and identity", tags: ["psychology", "wellbeing"], synonyms: ["distressing recollection", "trauma memory"] }),
    reviewed({ word: "collective memory", translation: "ذاكرة جماعية", pos: "noun", ipa: "/kəˌlektɪv ˈmeməri/", definition: "the shared understanding of past events held by a community or society", example: "Museums influence collective memory by choosing which stories to preserve.", exampleTranslation: "تؤثر المتاحف في الذاكرة الجماعية من خلال اختيار القصص التي تحفظها.", category: "memory and identity", tags: ["society", "history"], synonyms: ["shared memory", "social remembrance"] }),
  ],
  u46: [
    reviewed({ word: "data governance", translation: "حوكمة البيانات", pos: "noun", ipa: "/ˈdeɪtə ˈɡʌvərnəns/", definition: "the rules, responsibilities, and processes used to manage data responsibly", example: "Good data governance clarifies who may use research records and for what purpose.", exampleTranslation: "توضح حوكمة البيانات الجيدة من يجوز له استخدام السجلات البحثية ولأي غرض.", category: "ethics and technology", tags: ["technology", "governance"], synonyms: ["data stewardship", "information governance"] }),
    reviewed({ word: "human oversight", translation: "إشراف بشري", pos: "noun", ipa: "/ˈhjuːmən ˈoʊvərsaɪt/", definition: "people’s active supervision of an automated or technical system", example: "Human oversight is necessary when an automated recommendation may affect someone’s rights.", exampleTranslation: "يصبح الإشراف البشري ضروريًا عندما قد تؤثر توصية آلية في حقوق شخص ما.", category: "ethics and technology", tags: ["technology", "ethics"], synonyms: ["human supervision", "manual review"] }),
    reviewed({ word: "informed consent", translation: "موافقة مستنيرة", pos: "noun", ipa: "/ɪnˌfɔːrmd kənˈsent/", definition: "permission given after a person has understood the relevant risks, benefits, and alternatives", example: "Researchers must obtain informed consent before collecting sensitive personal data.", exampleTranslation: "يجب على الباحثين الحصول على موافقة مستنيرة قبل جمع بيانات شخصية حساسة.", category: "ethics and technology", tags: ["research", "rights"], synonyms: ["informed permission", "voluntary consent"] }),
    reviewed({ word: "surveillance capitalism", translation: "رأسمالية المراقبة", pos: "noun", ipa: "/sərˈveɪləns ˈkæpɪtəlɪzəm/", definition: "an economic model in which personal behaviour data is collected and monetised", example: "The lecture examined how surveillance capitalism turns everyday activity into a commercial resource.", exampleTranslation: "بحثت المحاضرة كيف تحول رأسمالية المراقبة النشاط اليومي إلى مورد تجاري.", category: "ethics and technology", tags: ["technology", "economy"], synonyms: ["data-driven exploitation", "behavioural data economy"] }),
    reviewed({ word: "digital dignity", translation: "كرامة رقمية", pos: "noun", ipa: "/ˈdɪdʒɪtəl ˈdɪɡnəti/", definition: "the right to be treated with respect and agency in digital environments", example: "Digital dignity requires platforms to avoid humiliating or manipulative design.", exampleTranslation: "تتطلب الكرامة الرقمية من المنصات تجنب التصميم المهين أو التلاعبي.", category: "ethics and technology", tags: ["technology", "rights"], synonyms: ["online dignity", "digital respect"] }),
    reviewed({ word: "ethical dilemma", translation: "معضلة أخلاقية", pos: "noun", ipa: "/ˈeθɪkəl dɪˈlemə/", definition: "a situation in which important moral principles appear to conflict", example: "The case presents an ethical dilemma between privacy and public safety.", exampleTranslation: "تعرض الحالة معضلة أخلاقية بين الخصوصية والسلامة العامة.", category: "ethics and technology", tags: ["ethics", "decision making"], synonyms: ["moral dilemma", "ethical quandary"] }),
    reviewed({ word: "unintended harm", translation: "ضرر غير مقصود", pos: "noun", ipa: "/ˌʌnɪnˈtendɪd hɑːrm/", definition: "negative damage or suffering caused without being the intended outcome", example: "A safety review should consider unintended harm before the system is deployed.", exampleTranslation: "ينبغي لمراجعة السلامة أن تراعي الضرر غير المقصود قبل تشغيل النظام.", category: "ethics and technology", tags: ["technology", "risk"], synonyms: ["unforeseen damage", "unplanned harm"] }),
    reviewed({ word: "model transparency", translation: "شفافية النموذج", pos: "noun", ipa: "/ˈmɑːdəl trænsˈperənsi/", definition: "the degree to which the design, limits, and operation of a computational model can be examined", example: "Model transparency helps reviewers identify weak assumptions before deployment.", exampleTranslation: "تساعد شفافية النموذج المراجعين على تحديد الافتراضات الضعيفة قبل النشر.", category: "ethics and technology", tags: ["technology", "accountability"], synonyms: ["system transparency", "model openness"] }),
  ],
};
