import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/** Reviewed vocabulary for the six existing B1/B2/C1 u12 and u13 units. */
export const ENGLISH_B1_B2_C1_U12_U13_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u12: [
      reviewed({ word: "travel itinerary", translation: "خطة الرحلة", pos: "noun", ipa: "/ˈtrævəl aɪˌtɪnəreri/", definition: "a detailed plan showing the places and activities in a journey", example: "Our travel itinerary includes two days in the mountains.", exampleTranslation: "تتضمن خطة رحلتنا يومين في الجبال.", category: "travel and routes", tags: ["travel", "planning"], synonyms: ["trip plan", "journey schedule"] }),
      reviewed({ word: "departure lounge", translation: "صالة المغادرة", pos: "noun", ipa: "/dɪˈpɑːrtʃər laʊndʒ/", definition: "the area at an airport where passengers wait before boarding", example: "We found seats in the departure lounge near our gate.", exampleTranslation: "وجدنا مقاعد في صالة المغادرة قرب بوابتنا.", category: "travel and routes", tags: ["travel", "airport"], synonyms: ["boarding lounge", "departure waiting area"] }),
      reviewed({ word: "return ticket", translation: "تذكرة ذهاب وإياب", pos: "noun", ipa: "/rɪˈtɜːrn ˌtɪkɪt/", definition: "a ticket that allows travel to a place and back again", example: "I bought a return ticket because I know when I will come home.", exampleTranslation: "اشتريت تذكرة ذهاب وإياب لأنني أعرف موعد عودتي إلى المنزل.", category: "travel and routes", tags: ["travel", "transport"], synonyms: ["round-trip ticket", "two-way ticket"] }),
      reviewed({ word: "guided excursion", translation: "رحلة بصحبة مرشد", pos: "noun", ipa: "/ˈɡaɪdɪd ɪkˈskɜːrʒən/", definition: "a short organised journey led by a guide", example: "The hotel offers a guided excursion to the ancient ruins.", exampleTranslation: "يقدم الفندق رحلة بصحبة مرشد إلى الآثار القديمة.", category: "travel and routes", tags: ["travel", "tourism"], synonyms: ["guided tour", "organised outing"] }),
      reviewed({ word: "local landmark", translation: "معلم محلي", pos: "noun", ipa: "/ˈloʊkəl ˈlændmɑːrk/", definition: "a well-known building, place, or feature in a particular area", example: "The old bridge is a local landmark that visitors always photograph.", exampleTranslation: "الجسر القديم معلم محلي يصوره الزوار دائمًا.", category: "travel and routes", tags: ["travel", "places"], synonyms: ["local attraction", "regional landmark"] }),
      reviewed({ word: "scenic viewpoint", translation: "نقطة مشاهدة خلابة", pos: "noun", ipa: "/ˈsiːnɪk ˈvjuːpɔɪnt/", definition: "a place from which an attractive natural view can be seen", example: "We stopped at a scenic viewpoint above the valley.", exampleTranslation: "توقفنا عند نقطة مشاهدة خلابة فوق الوادي.", category: "travel and routes", tags: ["travel", "nature"], synonyms: ["viewing point", "scenic overlook"] }),
      reviewed({ word: "railway connection", translation: "وصلة سكك حديدية", pos: "noun", ipa: "/ˈreɪlweɪ kəˌnekʃən/", definition: "a train service or link that connects one place with another", example: "The new railway connection makes the coastal town easier to reach.", exampleTranslation: "تجعل وصلة السكك الحديدية الجديدة الوصول إلى البلدة الساحلية أسهل.", category: "travel and routes", tags: ["travel", "transport"], synonyms: ["rail link", "train connection"] }),
      reviewed({ word: "route planning", translation: "تخطيط المسار", pos: "noun", ipa: "/ruːt ˈplænɪŋ/", definition: "the process of deciding the best way to travel between places", example: "Route planning helped us avoid the busiest roads.", exampleTranslation: "ساعدنا تخطيط المسار على تجنب أكثر الطرق ازدحامًا.", category: "travel and routes", tags: ["travel", "planning"], synonyms: ["journey planning", "route mapping"] }),
    ],
    u13: [
      reviewed({ word: "culinary tradition", translation: "تقليد طهوي", pos: "noun", ipa: "/ˈkʌləneri trəˈdɪʃən/", definition: "a customary way of preparing or enjoying food in a culture", example: "The festival celebrates the region’s culinary tradition.", exampleTranslation: "يحتفي المهرجان بالتقليد الطهوي للمنطقة.", category: "food and culture", tags: ["food", "culture"], synonyms: ["food tradition", "culinary heritage"] }),
      reviewed({ word: "seasonal ingredient", translation: "مكوّن موسمي", pos: "noun", ipa: "/ˈsiːzənəl ɪnˈɡriːdiənt/", definition: "a food ingredient that is naturally available during a particular season", example: "The chef changes the menu whenever a seasonal ingredient becomes available.", exampleTranslation: "يغير الطاهي القائمة كلما أصبح مكوّن موسمي متاحًا.", category: "food and culture", tags: ["food", "nature"], synonyms: ["seasonal produce", "in-season ingredient"] }),
      reviewed({ word: "regional speciality", translation: "طبق إقليمي مميز", pos: "noun", ipa: "/ˈriːdʒənəl ˌspeʃiˈæləti/", definition: "a food or product that is especially associated with a particular region", example: "The market sells a regional speciality made from local cheese.", exampleTranslation: "يبيع السوق طبقًا إقليميًا مميزًا مصنوعًا من الجبن المحلي.", category: "food and culture", tags: ["food", "regions"], synonyms: ["local speciality", "regional delicacy"] }),
      reviewed({ word: "street food stall", translation: "كشك طعام الشارع", pos: "noun", ipa: "/striːt fuːd stɔːl/", definition: "a small outdoor place where prepared food is sold", example: "We bought noodles from a busy street food stall.", exampleTranslation: "اشترينا المعكرونة من كشك طعام شارع مزدحم.", category: "food and culture", tags: ["food", "city life"], synonyms: ["street food stand", "food kiosk"] }),
      reviewed({ word: "family recipe", translation: "وصفة عائلية", pos: "noun", ipa: "/ˈfæməli ˈresəpi/", definition: "a set of cooking instructions passed down within a family", example: "She used her grandmother’s family recipe for the celebration.", exampleTranslation: "استخدمت وصفة عائلية لجدتها في الاحتفال.", category: "food and culture", tags: ["food", "family"], synonyms: ["heritage recipe", "family cooking formula"] }),
      reviewed({ word: "traditional feast", translation: "وليمة تقليدية", pos: "noun", ipa: "/trəˈdɪʃənəl fiːst/", definition: "a large special meal prepared for a cultural or religious occasion", example: "The village prepares a traditional feast at the end of the harvest.", exampleTranslation: "تعد القرية وليمة تقليدية في نهاية موسم الحصاد.", category: "food and culture", tags: ["food", "celebrations"], synonyms: ["festive meal", "ceremonial feast"] }),
      reviewed({ word: "food preservation", translation: "حفظ الطعام", pos: "noun", ipa: "/fuːd ˌprezərˈveɪʃən/", definition: "the process of keeping food safe and usable for longer", example: "Drying fruit is an old method of food preservation.", exampleTranslation: "يعد تجفيف الفاكهة طريقة قديمة لحفظ الطعام.", category: "food and culture", tags: ["food", "tradition"], synonyms: ["food storage", "preserving food"] }),
      reviewed({ word: "flavour profile", translation: "خصائص النكهة", pos: "noun", ipa: "/ˈfleɪvər ˌproʊfaɪl/", definition: "the particular combination of tastes and smells in a food or drink", example: "The herbs give the soup a fresh and distinctive flavour profile.", exampleTranslation: "تمنح الأعشاب الحساء خصائص نكهة طازجة ومميزة.", category: "food and culture", tags: ["food", "taste"], synonyms: ["taste profile", "flavour character"] }),
    ],
  },
  B2: {
    u12: [
      reviewed({ word: "media bias", translation: "تحيز إعلامي", pos: "noun", ipa: "/ˈmiːdiə ˌbaɪəs/", definition: "a tendency for media coverage to favour one viewpoint over others", example: "Readers should consider possible media bias when comparing reports.", exampleTranslation: "ينبغي للقراء مراعاة التحيز الإعلامي المحتمل عند مقارنة التقارير.", category: "media and propaganda", tags: ["media", "critical thinking"], synonyms: ["press bias", "editorial bias"] }),
      reviewed({ word: "disinformation campaign", translation: "حملة تضليل إعلامي", pos: "noun", ipa: "/ˌdɪsɪnfərˈmeɪʃən kæmˈpeɪn/", definition: "an organised attempt to spread false information in order to influence people", example: "The investigation traced the rumours to a coordinated disinformation campaign.", exampleTranslation: "تتبعت التحقيقات الشائعات إلى حملة تضليل إعلامي منسقة.", category: "media and propaganda", tags: ["media", "politics"], synonyms: ["false-information campaign", "propaganda campaign"] }),
      reviewed({ word: "source verification", translation: "التحقق من المصدر", pos: "noun", ipa: "/sɔːrs ˌverɪfɪˈkeɪʃən/", definition: "the process of checking whether a source is reliable and genuine", example: "Source verification is essential before a report is shared online.", exampleTranslation: "يعد التحقق من المصدر ضروريًا قبل مشاركة تقرير عبر الإنترنت.", category: "media and propaganda", tags: ["media", "verification"], synonyms: ["source checking", "source authentication"] }),
      reviewed({ word: "news framing", translation: "تأطير الأخبار", pos: "noun", ipa: "/njuːz ˈfreɪmɪŋ/", definition: "the way a news story is presented to shape how people understand it", example: "Different news framing can make the same event appear either positive or negative.", exampleTranslation: "يمكن لتأطير الأخبار المختلف أن يجعل الحدث نفسه يبدو إيجابيًا أو سلبيًا.", category: "media and propaganda", tags: ["media", "analysis"], synonyms: ["story framing", "news presentation"] }),
      reviewed({ word: "information manipulation", translation: "التلاعب بالمعلومات", pos: "noun", ipa: "/ˌɪnfərˈmeɪʃən məˌnɪpjəˈleɪʃən/", definition: "the deliberate alteration or selective use of information to influence opinion", example: "The report examined how information manipulation can weaken public trust.", exampleTranslation: "فحص التقرير كيف يمكن للتلاعب بالمعلومات أن يضعف ثقة الجمهور.", category: "media and propaganda", tags: ["media", "trust"], synonyms: ["data manipulation", "information distortion"] }),
      reviewed({ word: "editorial scrutiny", translation: "تدقيق تحريري", pos: "noun", ipa: "/ˌedɪˈtɔːriəl ˈskruːtəni/", definition: "careful examination of content before it is published", example: "The newspaper applies strict editorial scrutiny to anonymous claims.", exampleTranslation: "تطبق الصحيفة تدقيقًا تحريريًا صارمًا على الادعاءات المجهولة المصدر.", category: "media and propaganda", tags: ["media", "quality"], synonyms: ["editorial review", "publication scrutiny"] }),
      reviewed({ word: "narrative distortion", translation: "تشويه السرد", pos: "noun", ipa: "/ˈnærətɪv dɪˈstɔːrʃən/", definition: "a misleading change in the way events or facts are described", example: "Omitting key evidence can create a serious narrative distortion.", exampleTranslation: "يمكن أن يؤدي حذف الأدلة الأساسية إلى تشويه خطير للسرد.", category: "media and propaganda", tags: ["media", "truth"], synonyms: ["story distortion", "distorted narrative"] }),
      reviewed({ word: "propaganda technique", translation: "أسلوب دعائي", pos: "noun", ipa: "/ˌprɑːpəˈɡændə tekˈniːk/", definition: "a method used to influence people through selective or persuasive information", example: "The lesson identifies each propaganda technique in the video.", exampleTranslation: "يحدد الدرس كل أسلوب دعائي في الفيديو.", category: "media and propaganda", tags: ["media", "persuasion"], synonyms: ["propaganda method", "persuasive technique"] }),
    ],
    u13: [
      reviewed({ word: "business model", translation: "نموذج أعمال", pos: "noun", ipa: "/ˈbɪznəs ˌmɑːdəl/", definition: "the way an organisation creates value and earns income", example: "The startup changed its business model after studying customer needs.", exampleTranslation: "غيرت الشركة الناشئة نموذج أعمالها بعد دراسة احتياجات العملاء.", category: "innovation and entrepreneurship", tags: ["business", "innovation"], synonyms: ["commercial model", "operating model"] }),
      reviewed({ word: "seed funding", translation: "تمويل أولي", pos: "noun", ipa: "/siːd ˈfʌndɪŋ/", definition: "early financial support used to develop a new business or idea", example: "The team used seed funding to build its first prototype.", exampleTranslation: "استخدم الفريق التمويل الأولي لبناء نموذجه الأول.", category: "innovation and entrepreneurship", tags: ["business", "finance"], synonyms: ["early-stage funding", "initial capital"] }),
      reviewed({ word: "product launch", translation: "إطلاق منتج", pos: "noun", ipa: "/ˈprɑːdʌkt lɔːntʃ/", definition: "the planned introduction of a new product to the market", example: "The product launch attracted attention from several technology websites.", exampleTranslation: "جذب إطلاق المنتج اهتمام عدة مواقع تقنية.", category: "innovation and entrepreneurship", tags: ["business", "marketing"], synonyms: ["product release", "market launch"] }),
      reviewed({ word: "market disruption", translation: "اضطراب السوق", pos: "noun", ipa: "/ˈmɑːrkɪt dɪsˌrʌpʃən/", definition: "a major change that alters how an industry operates or competes", example: "Online banking caused significant market disruption.", exampleTranslation: "تسببَت الخدمات المصرفية عبر الإنترنت في اضطراب كبير للسوق.", category: "innovation and entrepreneurship", tags: ["business", "change"], synonyms: ["industry disruption", "market transformation"] }),
      reviewed({ word: "venture capital", translation: "رأس مال مغامر", pos: "noun", ipa: "/ˈventʃər ˌkæpɪtəl/", definition: "money invested in new businesses that may grow quickly but involve risk", example: "The founders attracted venture capital after demonstrating strong demand.", exampleTranslation: "جذب المؤسسون رأس مال مغامر بعد إثبات وجود طلب قوي.", category: "innovation and entrepreneurship", tags: ["business", "finance"], synonyms: ["risk capital", "startup investment"] }),
      reviewed({ word: "scalable solution", translation: "حل قابل للتوسع", pos: "noun", ipa: "/ˈskeɪləbəl səˈluːʃən/", definition: "a solution that can grow to serve more users without losing effectiveness", example: "The engineers are looking for a scalable solution to the transport problem.", exampleTranslation: "يبحث المهندسون عن حل قابل للتوسع لمشكلة النقل.", category: "innovation and entrepreneurship", tags: ["business", "technology"], synonyms: ["expandable solution", "growth-ready solution"] }),
      reviewed({ word: "intellectual property", translation: "ملكية فكرية", pos: "noun", ipa: "/ɪnˌteləktʃuəl ˈprɑːpərti/", definition: "creative or technical work legally protected from unauthorised use", example: "The company registered its intellectual property before the public launch.", exampleTranslation: "سجلت الشركة ملكيتها الفكرية قبل الإطلاق العام.", category: "innovation and entrepreneurship", tags: ["business", "law"], synonyms: ["intangible property", "protected creation"] }),
      reviewed({ word: "growth strategy", translation: "استراتيجية نمو", pos: "noun", ipa: "/ɡroʊθ ˈstrætədʒi/", definition: "a plan for increasing an organisation’s size, reach, or revenue", example: "The new growth strategy focuses on international customers.", exampleTranslation: "تركز استراتيجية النمو الجديدة على العملاء الدوليين.", category: "innovation and entrepreneurship", tags: ["business", "planning"], synonyms: ["expansion strategy", "growth plan"] }),
    ],
  },
  C1: {
    u12: [
      reviewed({ word: "ethical principle", translation: "مبدأ أخلاقي", pos: "noun", ipa: "/ˈeθɪkəl ˈprɪnsəpəl/", definition: "a basic rule about what is morally right or wrong", example: "Respect for autonomy is a central ethical principle in medical research.", exampleTranslation: "يعد احترام الاستقلالية مبدأً أخلاقيًا أساسيًا في البحث الطبي.", category: "moral philosophy", tags: ["ethics", "philosophy"], synonyms: ["moral principle", "ethical rule"] }),
      reviewed({ word: "normative theory", translation: "نظرية معيارية", pos: "noun", ipa: "/ˈnɔːrmətɪv ˌθɪəri/", definition: "a theory that explains how people or institutions ought to act", example: "The essay compares two approaches within normative theory.", exampleTranslation: "تقارن المقالة بين نهجين ضمن النظرية المعيارية.", category: "moral philosophy", tags: ["ethics", "theory"], synonyms: ["normative framework", "theory of obligation"] }),
      reviewed({ word: "moral obligation", translation: "التزام أخلاقي", pos: "noun", ipa: "/ˈmɔːrəl ˌɑːbləˈɡeɪʃən/", definition: "a duty to act in a way considered morally right", example: "The author argues that citizens have a moral obligation to protect vulnerable people.", exampleTranslation: "يجادل الكاتب بأن على المواطنين التزامًا أخلاقيًا بحماية الفئات الضعيفة.", category: "moral philosophy", tags: ["ethics", "duty"], synonyms: ["moral duty", "ethical responsibility"] }),
      reviewed({ word: "ethical judgement", translation: "حكم أخلاقي", pos: "noun", ipa: "/ˈeθɪkəl ˈdʒʌdʒmənt/", definition: "an assessment of whether an action or decision is morally acceptable", example: "The case requires careful ethical judgement rather than a quick reaction.", exampleTranslation: "تتطلب القضية حكمًا أخلاقيًا دقيقًا لا رد فعل سريعًا.", category: "moral philosophy", tags: ["ethics", "decision-making"], synonyms: ["moral judgement", "ethical assessment"] }),
      reviewed({ word: "philosophical premise", translation: "مقدمة فلسفية", pos: "noun", ipa: "/ˌfɪləˈsɑːfɪkəl ˈpremɪs/", definition: "a basic idea or assumption on which a philosophical argument is based", example: "The conclusion depends on a philosophical premise about human freedom.", exampleTranslation: "تعتمد الخلاصة على مقدمة فلسفية حول حرية الإنسان.", category: "moral philosophy", tags: ["philosophy", "argument"], synonyms: ["philosophical assumption", "argument premise"] }),
      reviewed({ word: "competing values", translation: "قيم متعارضة", pos: "noun", ipa: "/kəmˈpiːtɪŋ ˈvæljuːz/", definition: "different principles that cannot all be fully followed in the same situation", example: "The policy debate involves competing values such as freedom and security.", exampleTranslation: "ينطوي نقاش السياسة على قيم متعارضة مثل الحرية والأمن.", category: "moral philosophy", tags: ["ethics", "society"], synonyms: ["conflicting values", "opposing principles"] }),
      reviewed({ word: "ethical deliberation", translation: "مداولة أخلاقية", pos: "noun", ipa: "/ˈeθɪkəl dɪˌlɪbəˈreɪʃən/", definition: "the careful process of considering reasons before making a moral decision", example: "The course develops ethical deliberation through difficult case studies.", exampleTranslation: "يطور المقرر المداولة الأخلاقية من خلال دراسات حالات صعبة.", category: "moral philosophy", tags: ["ethics", "reasoning"], synonyms: ["moral deliberation", "ethical consideration"] }),
      reviewed({ word: "ethical pluralism", translation: "تعددية أخلاقية", pos: "noun", ipa: "/ˈeθɪkəl ˈplʊrəlɪzəm/", definition: "the view that several different moral values or principles may be valid", example: "Ethical pluralism recognises that one solution may not fit every culture.", exampleTranslation: "تعترف التعددية الأخلاقية بأن حلًا واحدًا قد لا يناسب كل ثقافة.", category: "moral philosophy", tags: ["ethics", "culture"], synonyms: ["moral pluralism", "pluralist ethics"] }),
    ],
    u13: [
      reviewed({ word: "resource depletion", translation: "استنزاف الموارد", pos: "noun", ipa: "/rɪˈsɔːrs dɪˌpliːʃən/", definition: "the reduction of natural resources through continued use", example: "Resource depletion can threaten the stability of food and energy systems.", exampleTranslation: "يمكن أن يهدد استنزاف الموارد استقرار أنظمة الغذاء والطاقة.", category: "climate and sustainability", tags: ["climate", "resources"], synonyms: ["resource exhaustion", "natural-resource decline"] }),
      reviewed({ word: "carbon neutrality", translation: "الحياد الكربوني", pos: "noun", ipa: "/ˈkɑːrbən nuːˈtræləti/", definition: "a balance in which carbon emissions are matched by their removal or offsetting", example: "The university has set a target of carbon neutrality by 2040.", exampleTranslation: "حددت الجامعة هدفًا لتحقيق الحياد الكربوني بحلول عام 2040.", category: "climate and sustainability", tags: ["climate", "policy"], synonyms: ["net-zero emissions", "carbon balance"] }),
      reviewed({ word: "adaptation strategy", translation: "استراتيجية التكيف", pos: "noun", ipa: "/ˌædæpˈteɪʃən ˈstrætədʒi/", definition: "a planned response that helps people or ecosystems cope with environmental change", example: "The coastal city needs an adaptation strategy for rising sea levels.", exampleTranslation: "تحتاج المدينة الساحلية إلى استراتيجية تكيف مع ارتفاع مستوى البحر.", category: "climate and sustainability", tags: ["climate", "planning"], synonyms: ["climate adaptation plan", "resilience strategy"] }),
      reviewed({ word: "environmental governance", translation: "حوكمة بيئية", pos: "noun", ipa: "/ɪnˌvaɪrənˈmentəl ˈɡʌvərnəns/", definition: "the systems and institutions used to make and enforce environmental decisions", example: "Effective environmental governance requires cooperation across national borders.", exampleTranslation: "تتطلب الحوكمة البيئية الفعالة تعاونًا عبر الحدود الوطنية.", category: "climate and sustainability", tags: ["climate", "governance"], synonyms: ["environmental administration", "ecological governance"] }),
      reviewed({ word: "social vulnerability", translation: "هشاشة اجتماعية", pos: "noun", ipa: "/ˈsoʊʃəl ˌvʌlnərəˈbɪləti/", definition: "the degree to which a group is exposed to harm because of social or economic conditions", example: "The report maps social vulnerability during extreme heat events.", exampleTranslation: "ترسم الدراسة خريطة الهشاشة الاجتماعية أثناء موجات الحر الشديد.", category: "climate and sustainability", tags: ["climate", "society"], synonyms: ["social exposure", "community vulnerability"] }),
      reviewed({ word: "intergenerational equity", translation: "الإنصاف بين الأجيال", pos: "noun", ipa: "/ˌɪntərˌdʒenəˈreɪʃənəl ˈekwəti/", definition: "the principle that present decisions should treat future generations fairly", example: "Intergenerational equity is central to debates about long-term environmental policy.", exampleTranslation: "يعد الإنصاف بين الأجيال محوريًا في النقاشات حول السياسة البيئية طويلة الأمد.", category: "climate and sustainability", tags: ["climate", "ethics"], synonyms: ["fairness between generations", "generational justice"] }),
      reviewed({ word: "ecological transition", translation: "التحول البيئي", pos: "noun", ipa: "/ˌiːkəˈlɑːdʒɪkəl trænˈzɪʃən/", definition: "a broad change towards systems that place less pressure on the natural world", example: "The ecological transition will require investment in clean transport and housing.", exampleTranslation: "سيتطلب التحول البيئي استثمارًا في النقل النظيف والإسكان.", category: "climate and sustainability", tags: ["climate", "change"], synonyms: ["green transition", "sustainability transition"] }),
      reviewed({ word: "mitigation pathway", translation: "مسار التخفيف", pos: "noun", ipa: "/ˌmɪtəˈɡeɪʃən ˈpæθweɪ/", definition: "a planned sequence of actions for reducing the causes or severity of climate change", example: "The report presents a mitigation pathway based on renewable energy.", exampleTranslation: "يعرض التقرير مسار تخفيف قائمًا على الطاقة المتجددة.", category: "climate and sustainability", tags: ["climate", "policy"], synonyms: ["emissions-reduction pathway", "decarbonisation route"] }),
    ],
  },
};
