import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/** Reviewed vocabulary for the six existing B1/B2/C1 u1 and u2 units. */
export const ENGLISH_B1_B2_C1_U1_U2_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u1: [
      reviewed({ word: "news bulletin", translation: "نشرة أخبار", pos: "noun", ipa: "/ˈnuːz ˌbʊlətɪn/", definition: "a short broadcast giving the latest news", example: "The evening news bulletin led with a report about the election.", exampleTranslation: "بدأت نشرة الأخبار المسائية بتقرير عن الانتخابات.", category: "news and media", tags: ["media", "communication"], synonyms: ["news update", "news broadcast"] }),
      reviewed({ word: "eyewitness account", translation: "شهادة شاهد عيان", pos: "noun", ipa: "/ˈaɪwɪtnəs əˌkaʊnt/", definition: "a description given by someone who saw an event happen", example: "The reporter compared the eyewitness account with official records.", exampleTranslation: "قارن الصحفي شهادة شاهد العيان بالسجلات الرسمية.", category: "news and media", tags: ["media", "evidence"], synonyms: ["first-hand account", "witness report"] }),
      reviewed({ word: "breaking story", translation: "خبر عاجل", pos: "noun", ipa: "/ˈbreɪkɪŋ ˌstɔːri/", definition: "a news event that is currently developing and being reported", example: "The channel interrupted the programme to cover the breaking story.", exampleTranslation: "أوقفت القناة البرنامج لتغطية الخبر العاجل.", category: "news and media", tags: ["media", "events"], synonyms: ["breaking news", "developing story"] }),
      reviewed({ word: "editorial stance", translation: "موقف تحريري", pos: "noun", ipa: "/ˌedɪˈtɔːriəl stæns/", definition: "the viewpoint or position expressed by a publication", example: "The newspaper made its editorial stance clear in an opinion article.", exampleTranslation: "أوضحت الصحيفة موقفها التحريري في مقال رأي.", category: "news and media", tags: ["media", "opinion"], synonyms: ["editorial position", "publication viewpoint"] }),
      reviewed({ word: "media coverage", translation: "تغطية إعلامية", pos: "noun", ipa: "/ˈmiːdiə ˌkʌvərɪdʒ/", definition: "the way an event or subject is reported by the media", example: "The charity received wide media coverage after the campaign.", exampleTranslation: "حصلت الجمعية على تغطية إعلامية واسعة بعد الحملة.", category: "news and media", tags: ["media", "communication"], synonyms: ["press coverage", "news reporting"] }),
      reviewed({ word: "news verification", translation: "التحقق من الأخبار", pos: "noun", ipa: "/ˈnuːz ˌverɪfɪˈkeɪʃən/", definition: "the process of checking whether a news claim is accurate", example: "News verification prevented the website from sharing the false report.", exampleTranslation: "منع التحقق من الأخبار الموقع من نشر التقرير الكاذب.", category: "news and media", tags: ["media", "accuracy"], synonyms: ["fact checking", "news checking"] }),
      reviewed({ word: "media briefing", translation: "إحاطة إعلامية", pos: "noun", ipa: "/ˈmiːdiə ˌbriːfɪŋ/", definition: "a meeting or statement that gives journalists information", example: "The minister gave a media briefing before the summit.", exampleTranslation: "قدم الوزير إحاطة إعلامية قبل القمة.", category: "news and media", tags: ["media", "government"], synonyms: ["press briefing", "journalist briefing"] }),
      reviewed({ word: "public reaction", translation: "رد فعل عام", pos: "noun", ipa: "/ˈpʌblɪk riˌækʃən/", definition: "the response of ordinary people to an event or decision", example: "The station reported the public reaction to the new policy.", exampleTranslation: "نقلت المحطة رد الفعل العام على السياسة الجديدة.", category: "news and media", tags: ["media", "society"], synonyms: ["popular response", "public response"] }),
    ],
    u2: [
      reviewed({ word: "habitat loss", translation: "فقدان الموائل الطبيعية", pos: "noun", ipa: "/ˈhæbɪtæt lɔːs/", definition: "the reduction or destruction of the natural home of a plant or animal", example: "Habitat loss is putting pressure on several local species.", exampleTranslation: "يضع فقدان الموائل الطبيعية ضغطًا على عدة أنواع محلية.", category: "environment", tags: ["environment", "nature"], synonyms: ["loss of habitat", "habitat destruction"] }),
      reviewed({ word: "conservation effort", translation: "جهد للحفاظ على البيئة", pos: "noun", ipa: "/ˌkɑːnsərˈveɪʃən ˌefərt/", definition: "an action intended to protect nature, resources, or wildlife", example: "The conservation effort restored a wetland near the town.", exampleTranslation: "أعاد جهد الحفاظ على البيئة تأهيل أرض رطبة قرب البلدة.", category: "environment", tags: ["environment", "nature"], synonyms: ["environmental initiative", "protection effort"] }),
      reviewed({ word: "climate resilience", translation: "القدرة على الصمود أمام تغير المناخ", pos: "noun", ipa: "/ˈklaɪmət rɪˌzɪliəns/", definition: "the ability to withstand and recover from climate-related effects", example: "The project aims to improve climate resilience in coastal villages.", exampleTranslation: "يهدف المشروع إلى تحسين القدرة على الصمود أمام تغير المناخ في القرى الساحلية.", category: "environment", tags: ["environment", "climate"], synonyms: ["climate readiness", "resilience to climate change"] }),
      reviewed({ word: "single-use plastic", translation: "بلاستيك أحادي الاستخدام", pos: "noun", ipa: "/ˌsɪŋɡəl juːs ˈplæstɪk/", definition: "plastic made to be used once before being thrown away", example: "The school replaced single-use plastic with reusable containers.", exampleTranslation: "استبدلت المدرسة البلاستيك أحادي الاستخدام بعبوات قابلة لإعادة الاستخدام.", category: "environment", tags: ["environment", "waste"], synonyms: ["disposable plastic", "single-use packaging"] }),
      reviewed({ word: "ecological footprint", translation: "البصمة البيئية", pos: "noun", ipa: "/ˌiːkəˈlɑːdʒɪkəl ˈfʊtprɪnt/", definition: "a measure of the effect a person or activity has on natural resources", example: "Cycling to work can reduce your ecological footprint.", exampleTranslation: "يمكن لركوب الدراجة إلى العمل أن يقلل بصمتك البيئية.", category: "environment", tags: ["environment", "sustainability"], synonyms: ["environmental footprint", "ecological impact"] }),
      reviewed({ word: "environmental impact", translation: "أثر بيئي", pos: "noun", ipa: "/ɪnˌvaɪrənˈmentəl ˈɪmpækt/", definition: "the effect that an activity has on the natural world", example: "The developers published a report on the environmental impact of the road.", exampleTranslation: "نشر المطورون تقريرًا عن الأثر البيئي للطريق.", category: "environment", tags: ["environment", "planning"], synonyms: ["environmental effect", "impact on nature"] }),
      reviewed({ word: "green infrastructure", translation: "بنية تحتية خضراء", pos: "noun", ipa: "/ɡriːn ˈɪnfrəˌstrʌktʃər/", definition: "natural features designed to manage water, heat, or pollution in a town", example: "Green infrastructure can make streets cooler and reduce flooding.", exampleTranslation: "يمكن للبنية التحتية الخضراء أن تجعل الشوارع أبرد وتقلل الفيضانات.", category: "environment", tags: ["environment", "cities"], synonyms: ["nature-based infrastructure", "green urban design"] }),
      reviewed({ word: "biodiversity loss", translation: "فقدان التنوع الحيوي", pos: "noun", ipa: "/ˌbaɪoʊdaɪˈvɜːrsəti lɔːs/", definition: "the reduction in the variety of living species in an area", example: "Biodiversity loss can weaken the whole food chain.", exampleTranslation: "يمكن لفقدان التنوع الحيوي أن يضعف السلسلة الغذائية بأكملها.", category: "environment", tags: ["environment", "nature"], synonyms: ["loss of biodiversity", "decline in species diversity"] }),
    ],
  },
  B2: {
    u1: [
      reviewed({ word: "narrative voice", translation: "صوت السرد", pos: "noun", ipa: "/ˈnærətɪv vɔɪs/", definition: "the distinctive perspective from which a story is told", example: "The novel’s narrative voice changes when the child becomes an adult.", exampleTranslation: "يتغير صوت السرد في الرواية عندما يصبح الطفل بالغًا.", category: "literature and art", tags: ["literature", "analysis"], synonyms: ["narrator’s voice", "storytelling voice"] }),
      reviewed({ word: "literary device", translation: "أسلوب أدبي", pos: "noun", ipa: "/ˈlɪtəreri dɪˌvaɪs/", definition: "a technique used by a writer to create a particular effect", example: "The writer uses irony as a literary device throughout the story.", exampleTranslation: "يستخدم الكاتب السخرية أسلوبًا أدبيًا في القصة كلها.", category: "literature and art", tags: ["literature", "writing"], synonyms: ["literary technique", "writing device"] }),
      reviewed({ word: "character development", translation: "تطور الشخصية", pos: "noun", ipa: "/ˈkærəktər dɪˌveləpmənt/", definition: "the way a fictional character changes during a story", example: "The film is praised for its convincing character development.", exampleTranslation: "يحظى الفيلم بالثناء بسبب تطور شخصياته المقنع.", category: "literature and art", tags: ["literature", "film"], synonyms: ["character arc", "development of a character"] }),
      reviewed({ word: "visual composition", translation: "تكوين بصري", pos: "noun", ipa: "/ˈvɪʒuəl ˌkɑːmpəˈzɪʃən/", definition: "the arrangement of visual elements in an artwork or image", example: "The painting’s visual composition guides the eye towards the window.", exampleTranslation: "يوجه التكوين البصري للوحة العين نحو النافذة.", category: "literature and art", tags: ["art", "analysis"], synonyms: ["image composition", "visual arrangement"] }),
      reviewed({ word: "artistic movement", translation: "تيار فني", pos: "noun", ipa: "/ɑːrˈtɪstɪk ˈmuːvmənt/", definition: "a group of artists who share a style or set of ideas", example: "Impressionism was an influential artistic movement.", exampleTranslation: "كانت الانطباعية تيارًا فنيًا مؤثرًا.", category: "literature and art", tags: ["art", "history"], synonyms: ["art movement", "school of art"] }),
      reviewed({ word: "critical interpretation", translation: "تفسير نقدي", pos: "noun", ipa: "/ˈkrɪtɪkəl ɪnˌtɜːrprəˈteɪʃən/", definition: "an explanation of an artwork based on close analysis and judgement", example: "Her critical interpretation connects the poem with social change.", exampleTranslation: "يربط تفسيرها النقدي القصيدة بالتغير الاجتماعي.", category: "literature and art", tags: ["literature", "analysis"], synonyms: ["critical reading", "analytical interpretation"] }),
      reviewed({ word: "symbolic imagery", translation: "صور رمزية", pos: "noun", ipa: "/sɪmˈbɑːlɪk ˈɪmɪdʒəri/", definition: "images that represent ideas beyond their literal meaning", example: "The artist uses symbolic imagery to suggest freedom and confinement.", exampleTranslation: "يستخدم الفنان صورًا رمزية للإيحاء بالحرية والاحتجاز.", category: "literature and art", tags: ["art", "literature"], synonyms: ["symbolic images", "metaphorical imagery"] }),
      reviewed({ word: "cultural context", translation: "سياق ثقافي", pos: "noun", ipa: "/ˈkʌltʃərəl ˈkɑːntekst/", definition: "the social and historical setting that helps explain a work", example: "Understanding the cultural context makes the play easier to interpret.", exampleTranslation: "يجعل فهم السياق الثقافي تفسير المسرحية أسهل.", category: "literature and art", tags: ["culture", "analysis"], synonyms: ["cultural background", "social context"] }),
    ],
    u2: [
      reviewed({ word: "household expenditure", translation: "إنفاق الأسرة", pos: "noun", ipa: "/ˈhaʊshoʊld ɪkˌspendɪtʃər/", definition: "the money spent by a household on goods and services", example: "Rising food prices have increased household expenditure.", exampleTranslation: "أدت أسعار الغذاء المرتفعة إلى زيادة إنفاق الأسرة.", category: "economy and society", tags: ["economy", "finance"], synonyms: ["household spending", "family expenditure"] }),
      reviewed({ word: "labour productivity", translation: "إنتاجية العمل", pos: "noun", ipa: "/ˈleɪbər ˌproʊdʌkˈtɪvəti/", definition: "the amount produced by workers in a given period", example: "Training and better equipment can raise labour productivity.", exampleTranslation: "يمكن للتدريب والمعدات الأفضل أن يرفعا إنتاجية العمل.", category: "economy and society", tags: ["economy", "work"], synonyms: ["worker productivity", "productivity of labour"] }),
      reviewed({ word: "income distribution", translation: "توزيع الدخل", pos: "noun", ipa: "/ˈɪnkʌm ˌdɪstrɪˈbjuːʃən/", definition: "the way income is shared among people or groups in a society", example: "The report examines income distribution across different regions.", exampleTranslation: "يفحص التقرير توزيع الدخل بين المناطق المختلفة.", category: "economy and society", tags: ["economy", "society"], synonyms: ["distribution of income", "income pattern"] }),
      reviewed({ word: "public expenditure", translation: "الإنفاق العام", pos: "noun", ipa: "/ˈpʌblɪk ɪkˌspendɪtʃər/", definition: "money spent by a government on public services and projects", example: "The budget limits public expenditure on new buildings.", exampleTranslation: "تحد الميزانية الإنفاق العام على المباني الجديدة.", category: "economy and society", tags: ["economy", "government"], synonyms: ["government spending", "state expenditure"] }),
      reviewed({ word: "social inequality", translation: "عدم المساواة الاجتماعية", pos: "noun", ipa: "/ˈsoʊʃəl ˌɪnɪˈkwɑːləti/", definition: "unfair differences in wealth, rights, or opportunities between groups", example: "Education alone cannot solve every form of social inequality.", exampleTranslation: "لا يستطيع التعليم وحده حل كل أشكال عدم المساواة الاجتماعية.", category: "economy and society", tags: ["society", "policy"], synonyms: ["social disparity", "unequal opportunities"] }),
      reviewed({ word: "fiscal measure", translation: "إجراء مالي حكومي", pos: "noun", ipa: "/ˈfɪskəl ˌmeʒər/", definition: "a government action involving taxation or public spending", example: "The minister announced a fiscal measure to support small businesses.", exampleTranslation: "أعلن الوزير إجراءً ماليًا حكوميًا لدعم الشركات الصغيرة.", category: "economy and society", tags: ["economy", "policy"], synonyms: ["budgetary measure", "tax or spending measure"] }),
      reviewed({ word: "social safety net", translation: "شبكة أمان اجتماعي", pos: "noun", ipa: "/ˈsoʊʃəl ˈseɪfti net/", definition: "public support intended to protect people from severe financial hardship", example: "A reliable social safety net can reduce the effects of unemployment.", exampleTranslation: "يمكن لشبكة أمان اجتماعي موثوقة أن تقلل آثار البطالة.", category: "economy and society", tags: ["society", "welfare"], synonyms: ["welfare safety net", "social protection system"] }),
      reviewed({ word: "economic forecast", translation: "توقع اقتصادي", pos: "noun", ipa: "/ˌiːkəˈnɑːmɪk ˈfɔːrkæst/", definition: "a statement about likely future economic conditions", example: "The latest economic forecast predicts slower growth next year.", exampleTranslation: "يتوقع أحدث توقع اقتصادي نموًا أبطأ في العام المقبل.", category: "economy and society", tags: ["economy", "analysis"], synonyms: ["economic projection", "financial outlook"] }),
    ],
  },
  C1: {
    u1: [
      reviewed({ word: "citation practice", translation: "ممارسة التوثيق العلمي", pos: "noun", ipa: "/saɪˈteɪʃən ˈpræktɪs/", definition: "the established way of acknowledging sources in academic work", example: "Consistent citation practice helps readers trace the evidence.", exampleTranslation: "تساعد ممارسة التوثيق العلمي المتسقة القراء على تتبع الأدلة.", category: "academic writing", tags: ["writing", "research"], synonyms: ["source citation", "referencing practice"] }),
      reviewed({ word: "scholarly argument", translation: "حجة علمية", pos: "noun", ipa: "/ˈskɑːlərli ˈɑːrɡjumənt/", definition: "a reasoned claim supported by academic evidence and analysis", example: "A scholarly argument must distinguish evidence from personal opinion.", exampleTranslation: "يجب أن تميز الحجة العلمية بين الدليل والرأي الشخصي.", category: "academic writing", tags: ["writing", "research"], synonyms: ["academic argument", "research argument"] }),
      reviewed({ word: "conceptual distinction", translation: "تمييز مفاهيمي", pos: "noun", ipa: "/kənˈseptʃuəl dɪˈstɪŋkʃən/", definition: "a clear difference between two related ideas", example: "The essay makes a conceptual distinction between equality and fairness.", exampleTranslation: "تجري المقالة تمييزًا مفاهيميًا بين المساواة والإنصاف.", category: "academic writing", tags: ["writing", "analysis"], synonyms: ["conceptual difference", "distinction between concepts"] }),
      reviewed({ word: "analytical framework", translation: "إطار تحليلي", pos: "noun", ipa: "/ˌænəˈlɪtɪkəl ˈfreɪmwɜːrk/", definition: "a structured set of ideas used to examine a subject", example: "The researchers developed an analytical framework for comparing the policies.", exampleTranslation: "طور الباحثون إطارًا تحليليًا لمقارنة السياسات.", category: "academic writing", tags: ["writing", "research"], synonyms: ["analysis framework", "conceptual framework"] }),
      reviewed({ word: "methodological transparency", translation: "شفافية منهجية", pos: "noun", ipa: "/ˌmeθədəˈlɑːdʒɪkəl trænˈspærənsi/", definition: "the clear reporting of how a research study was designed and carried out", example: "Methodological transparency allows readers to assess the study’s reliability.", exampleTranslation: "تتيح الشفافية المنهجية للقراء تقييم موثوقية الدراسة.", category: "academic writing", tags: ["research", "quality"], synonyms: ["transparent methodology", "clear research method"] }),
      reviewed({ word: "evidence synthesis", translation: "تركيب الأدلة", pos: "noun", ipa: "/ˈevɪdəns ˌsɪnθəsɪs/", definition: "the process of combining findings from several sources", example: "The review provides an evidence synthesis rather than a single case study.", exampleTranslation: "تقدم المراجعة تركيبًا للأدلة لا دراسة حالة واحدة.", category: "academic writing", tags: ["research", "analysis"], synonyms: ["synthesis of evidence", "evidence integration"] }),
      reviewed({ word: "qualifying statement", translation: "عبارة تقييدية", pos: "noun", ipa: "/ˈkwɑːləfaɪɪŋ ˌsteɪtmənt/", definition: "a phrase that limits or carefully defines a claim", example: "The author added a qualifying statement to avoid overgeneralisation.", exampleTranslation: "أضاف المؤلف عبارة تقييدية لتجنب التعميم الزائد.", category: "academic writing", tags: ["writing", "precision"], synonyms: ["qualification", "limiting statement"] }),
      reviewed({ word: "argument structure", translation: "بنية الحجة", pos: "noun", ipa: "/ˈɑːrɡjumənt ˌstrʌktʃər/", definition: "the organised progression of claims, reasons, and evidence in a text", example: "The tutor helped improve the argument structure of the dissertation.", exampleTranslation: "ساعد المدرس في تحسين بنية الحجة في الأطروحة.", category: "academic writing", tags: ["writing", "dissertation"], synonyms: ["structure of an argument", "reasoning structure"] }),
    ],
    u2: [
      reviewed({ word: "geopolitical tension", translation: "توتر جيوسياسي", pos: "noun", ipa: "/ˌdʒiːoʊpəˈlɪtɪkəl ˈtenʃən/", definition: "strained relations between countries or regions linked to power and territory", example: "Geopolitical tension disrupted trade across the border.", exampleTranslation: "عطل التوتر الجيوسياسي التجارة عبر الحدود.", category: "global politics", tags: ["politics", "international relations"], synonyms: ["geopolitical strain", "international tension"] }),
      reviewed({ word: "multilateral cooperation", translation: "تعاون متعدد الأطراف", pos: "noun", ipa: "/ˌmʌltiˈlætərəl koʊˌɑːpəˈreɪʃən/", definition: "cooperation involving several countries or organisations", example: "The crisis requires multilateral cooperation rather than isolated action.", exampleTranslation: "تتطلب الأزمة تعاونًا متعدد الأطراف لا إجراءً منفردًا.", category: "global politics", tags: ["politics", "diplomacy"], synonyms: ["multinational cooperation", "cooperation among states"] }),
      reviewed({ word: "electoral mandate", translation: "تفويض انتخابي", pos: "noun", ipa: "/ɪˈlektərəl ˈmændeɪt/", definition: "the authority a government is considered to receive from winning an election", example: "The new administration claimed an electoral mandate for reform.", exampleTranslation: "ادعت الإدارة الجديدة امتلاك تفويض انتخابي للإصلاح.", category: "global politics", tags: ["politics", "elections"], synonyms: ["election mandate", "popular mandate"] }),
      reviewed({ word: "territorial dispute", translation: "نزاع إقليمي", pos: "noun", ipa: "/ˌterəˈtɔːriəl dɪˌspjuːt/", definition: "a disagreement between parties over control of an area of land or sea", example: "The territorial dispute has remained unresolved for decades.", exampleTranslation: "ظل النزاع الإقليمي دون حل لعقود.", category: "global politics", tags: ["politics", "conflict"], synonyms: ["border dispute", "land dispute"] }),
      reviewed({ word: "humanitarian intervention", translation: "تدخل إنساني", pos: "noun", ipa: "/hjuːˌmænɪˈteriən ˌɪntərˈvenʃən/", definition: "action taken to protect people from severe harm during a crisis", example: "The debate focused on whether humanitarian intervention would save lives.", exampleTranslation: "ركز النقاش على ما إذا كان التدخل الإنساني سينقذ الأرواح.", category: "global politics", tags: ["politics", "human rights"], synonyms: ["humanitarian action", "crisis intervention"] }),
      reviewed({ word: "peacekeeping mission", translation: "مهمة حفظ السلام", pos: "noun", ipa: "/ˈpiːsˌkiːpɪŋ ˌmɪʃən/", definition: "an international operation intended to help maintain peace", example: "The peacekeeping mission monitored the ceasefire.", exampleTranslation: "راقبت مهمة حفظ السلام وقف إطلاق النار.", category: "global politics", tags: ["politics", "conflict"], synonyms: ["peace mission", "peacekeeping operation"] }),
      reviewed({ word: "strategic dialogue", translation: "حوار استراتيجي", pos: "noun", ipa: "/strəˈtiːdʒɪk ˈdaɪəlɔːɡ/", definition: "formal discussion between parties about long-term shared interests", example: "The two governments resumed strategic dialogue after the crisis.", exampleTranslation: "استأنفت الحكومتان الحوار الاستراتيجي بعد الأزمة.", category: "global politics", tags: ["politics", "diplomacy"], synonyms: ["strategic talks", "long-term diplomatic dialogue"] }),
      reviewed({ word: "diplomatic protocol", translation: "بروتوكول دبلوماسي", pos: "noun", ipa: "/ˌdɪpləˈmætɪk ˈproʊtəkɑːl/", definition: "the accepted rules and procedures governing diplomatic conduct", example: "The ambassador followed diplomatic protocol during the formal visit.", exampleTranslation: "اتبع السفير البروتوكول الدبلوماسي خلال الزيارة الرسمية.", category: "global politics", tags: ["politics", "diplomacy"], synonyms: ["diplomatic procedure", "protocol of diplomacy"] }),
    ],
  },
};
