import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/** Reviewed vocabulary for existing C1 rhetorical-analysis and research-ethics units. */
export const ENGLISH_C1_U52_U53_ENRICHMENTS: Record<string, VocabularyItem[]> = {
  u52: [
    reviewed({ word: "rhetorical strategy", translation: "استراتيجية خطابية", pos: "noun", ipa: "/rɪˈtɔːrɪkəl ˈstrætədʒi/", definition: "a deliberate way of using language to influence how an audience thinks or feels", example: "Repetition was the speaker’s main rhetorical strategy for making the demand memorable.", exampleTranslation: "كان التكرار استراتيجية المتحدث الخطابية الرئيسية لجعل المطلب سهل التذكر.", category: "rhetorical analysis", tags: ["rhetoric", "argument"], synonyms: ["rhetorical technique", "persuasive strategy"] }),
    reviewed({ word: "rhetorical question", translation: "سؤال بلاغي", pos: "noun", ipa: "/rɪˌtɔːrɪkəl ˈkwestʃən/", definition: "a question asked to make a point rather than to obtain an answer", example: "The article ends with a rhetorical question that challenges the reader’s assumptions.", exampleTranslation: "تنتهي المقالة بسؤال بلاغي يتحدى افتراضات القارئ.", category: "rhetorical analysis", tags: ["rhetoric", "writing"], synonyms: ["persuasive question", "question for effect"] }),
    reviewed({ word: "analogy", translation: "قياس / تشبيه توضيحي", pos: "noun", ipa: "/əˈnælədʒi/", definition: "a comparison used to explain an idea or show that two situations are similar", example: "The author uses an analogy between a river and an information network.", exampleTranslation: "يستخدم المؤلف قياسًا بين النهر وشبكة المعلومات.", category: "rhetorical analysis", tags: ["rhetoric", "comparison"], synonyms: ["comparison", "parallel"] }),
    reviewed({ word: "metaphorical framing", translation: "التأطير الاستعاري", pos: "noun", ipa: "/ˌmetəˈfɔːrɪkəl ˈfreɪmɪŋ/", definition: "the use of metaphor to shape how an issue is understood", example: "Metaphorical framing presents the reform as a journey rather than a conflict.", exampleTranslation: "يقدم التأطير الاستعاري الإصلاح بوصفه رحلة لا صراعًا.", category: "rhetorical analysis", tags: ["rhetoric", "metaphor"], synonyms: ["metaphorical presentation", "figurative framing"] }),
    reviewed({ word: "qualifying language", translation: "لغة التقييد والتحفظ", pos: "noun", ipa: "/ˈkwɑːlɪfaɪɪŋ ˈlæŋɡwɪdʒ/", definition: "words that limit, soften, or specify the strength of a statement", example: "Qualifying language makes the conclusion more accurate when the evidence is incomplete.", exampleTranslation: "تجعل لغة التقييد الاستنتاج أكثر دقة عندما تكون الأدلة غير مكتملة.", category: "rhetorical analysis", tags: ["rhetoric", "academic writing"], synonyms: ["cautious wording", "hedging language"] }),
    reviewed({ word: "argumentative structure", translation: "البنية الحجاجية", pos: "noun", ipa: "/ˌɑːrɡjəˈmentətɪv ˈstrʌktʃər/", definition: "the way claims, reasons, evidence, and conclusions are arranged in an argument", example: "The argumentative structure becomes clear once the central claim is separated from the examples.", exampleTranslation: "تتضح البنية الحجاجية عندما يُفصل الادعاء المركزي عن الأمثلة.", category: "rhetorical analysis", tags: ["argument", "analysis"], synonyms: ["argument structure", "reasoning structure"] }),
    reviewed({ word: "persuasive appeal", translation: "أسلوب إقناعي", pos: "noun", ipa: "/pərˈsweɪsɪv əˈpiːl/", definition: "an aspect of a message intended to attract agreement or support", example: "The speech combines emotional and logical persuasive appeals.", exampleTranslation: "يجمع الخطاب بين أساليب إقناعية عاطفية ومنطقية.", category: "rhetorical analysis", tags: ["rhetoric", "persuasion"], synonyms: ["appeal to the audience", "persuasive device"] }),
    reviewed({ word: "discourse strategy", translation: "استراتيجية خطابية", pos: "noun", ipa: "/ˈdɪskɔːrs ˌstrætədʒi/", definition: "a planned way of organising language in a social or public discussion", example: "The writer’s discourse strategy shifts from describing the problem to assigning responsibility.", exampleTranslation: "تنتقل استراتيجية الكاتب الخطابية من وصف المشكلة إلى تحديد المسؤولية.", category: "rhetorical analysis", tags: ["discourse", "analysis"], synonyms: ["discursive strategy", "communication strategy"] }),
  ],
  u53: [
    reviewed({ word: "ethical approval", translation: "موافقة أخلاقية", pos: "noun", ipa: "/ˈeθɪkəl əˈpruːvəl/", definition: "formal permission confirming that a research project meets required ethical standards", example: "The study could not begin until ethical approval had been granted.", exampleTranslation: "لم تتمكن الدراسة من البدء حتى مُنحت الموافقة الأخلاقية.", category: "research ethics", tags: ["research", "ethics"], synonyms: ["ethics clearance", "ethical authorisation"] }),
    reviewed({ word: "research participant", translation: "مشارك في البحث", pos: "noun", ipa: "/rɪˈsɜːrtʃ pɑːrˌtɪsɪpənt/", definition: "a person who provides information or takes part in a research study", example: "Every research participant received a clear explanation of the interview process.", exampleTranslation: "تلقى كل مشارك في البحث شرحًا واضحًا لعملية المقابلة.", category: "research ethics", tags: ["research", "participants"], synonyms: ["study participant", "research subject"] }),
    reviewed({ word: "data protection", translation: "حماية البيانات", pos: "noun", ipa: "/ˈdeɪtə prəˌtekʃən/", definition: "the practice of keeping personal or sensitive information secure and properly used", example: "The protocol explains how data protection will be maintained after the study ends.", exampleTranslation: "يوضح البروتوكول كيفية الحفاظ على حماية البيانات بعد انتهاء الدراسة.", category: "research ethics", tags: ["research", "privacy"], synonyms: ["information protection", "data security"] }),
    reviewed({ word: "conflict of interest", translation: "تضارب المصالح", pos: "noun", ipa: "/ˌkɑːnflɪkt əv ˈɪntrəst/", definition: "a situation in which a personal or financial interest could influence professional judgement", example: "The author disclosed a possible conflict of interest before publication.", exampleTranslation: "كشف المؤلف عن تضارب محتمل في المصالح قبل النشر.", category: "research ethics", tags: ["research", "transparency"], synonyms: ["competing interest", "divided interest"] }),
    reviewed({ word: "informed consent form", translation: "نموذج موافقة مستنيرة", pos: "noun", ipa: "/ɪnˌfɔːrmd kənˈsent fɔːrm/", definition: "a document recording that a participant understood the study and agreed to take part", example: "Participants signed an informed consent form before any recording took place.", exampleTranslation: "وقع المشاركون نموذج موافقة مستنيرة قبل بدء أي تسجيل.", category: "research ethics", tags: ["research", "consent"], synonyms: ["consent document", "participant consent form"] }),
    reviewed({ word: "ethics committee", translation: "لجنة أخلاقيات", pos: "noun", ipa: "/ˈeθɪks kəˌmɪti/", definition: "a group that reviews research plans to protect participants and uphold ethical standards", example: "The ethics committee requested clearer information about data storage.", exampleTranslation: "طلبت لجنة الأخلاقيات معلومات أوضح عن تخزين البيانات.", category: "research ethics", tags: ["research", "governance"], synonyms: ["research ethics board", "ethics review panel"] }),
    reviewed({ word: "vulnerable population", translation: "فئة سكانية هشة", pos: "noun", ipa: "/ˈvʌlnərəbəl ˌpɑːpjəˈleɪʃən/", definition: "a group that may face increased risk of harm or reduced ability to protect its interests", example: "Research involving a vulnerable population requires additional safeguards.", exampleTranslation: "يتطلب البحث الذي يشمل فئة سكانية هشة ضمانات إضافية.", category: "research ethics", tags: ["research", "protection"], synonyms: ["at-risk group", "protected population"] }),
    reviewed({ word: "research transparency", translation: "شفافية البحث", pos: "noun", ipa: "/rɪˈsɜːrtʃ trænˈspærənsi/", definition: "the practice of clearly reporting methods, decisions, limitations, and sources in research", example: "Research transparency helps readers assess how the findings were produced.", exampleTranslation: "تساعد شفافية البحث القراء على تقييم كيفية إنتاج النتائج.", category: "research ethics", tags: ["research", "integrity"], synonyms: ["methodological openness", "research openness"] }),
  ],
};
