// Professional English enrichment unit u56 for every CEFR level.
// English-only continuation; Finnish curriculum files are intentionally untouched.
import type { ReadingText, VocabularyItem } from "./learn-data";

type PhraseSpec = { phrase: string; translation: string };
type LineSpec = { speaker: string; text: string; translation: string };
type UnitSeed = { id: string; title: string; description: string; words: VocabularyItem[]; phrases: PhraseSpec[]; dialogue: LineSpec[]; reading: ReadingText & { title: string } };
type WordSpec = { word: string; translation: string; pos: string; ipa: string; definition: string; example: string; exampleTranslation: string; synonyms: string[]; antonyms: string[]; collocations: string[]; wordFamily: string[]; tags: string[]; category: string };

const w = (spec: WordSpec): VocabularyItem => ({ ...spec });
const u = (id: string, title: string, description: string, words: VocabularyItem[], phrases: PhraseSpec[], dialogue: LineSpec[], reading: ReadingText & { title: string }): UnitSeed => ({ id, title, description, words, phrases, dialogue, reading });

export const ADDITIONAL_EN_PART17_UNITS: Record<string, UnitSeed[]> = {
  A0: [
    u("u56", "The Classroom", "Name common classroom objects and follow simple instructions.", [
      w({ word: "classroom", translation: "aula", pos: "noun", ipa: "/ˈklæsruːm/", definition: "a room where students learn", example: "Our classroom is bright.", exampleTranslation: "Nuestra aula es luminosa.", synonyms: ["class", "schoolroom"], antonyms: [], collocations: ["English classroom", "in the classroom"], wordFamily: ["class", "classroom"], tags: ["school", "places"], category: "place" }),
      w({ word: "desk", translation: "pupitre", pos: "noun", ipa: "/desk/", definition: "a table used for studying or working", example: "My book is on the desk.", exampleTranslation: "Mi libro está sobre el pupitre.", synonyms: ["table", "workstation"], antonyms: [], collocations: ["school desk", "sit at a desk"], wordFamily: ["desk", "desktop"], tags: ["school", "objects"], category: "object" }),
      w({ word: "pencil", translation: "lápiz", pos: "noun", ipa: "/ˈpensəl/", definition: "a tool used for writing or drawing", example: "I write with a pencil.", exampleTranslation: "Escribo con un lápiz.", synonyms: ["lead pencil"], antonyms: [], collocations: ["sharp pencil", "pencil case"], wordFamily: ["pencil", "pencilled"], tags: ["school", "objects"], category: "object" }),
      w({ word: "paper", translation: "papel", pos: "noun", ipa: "/ˈpeɪpər/", definition: "thin material used for writing or drawing", example: "Put the paper on the desk.", exampleTranslation: "Pon el papel sobre el pupitre.", synonyms: ["sheet", "page"], antonyms: [], collocations: ["sheet of paper", "writing paper"], wordFamily: ["paper", "paperwork"], tags: ["school", "objects"], category: "material" }),
      w({ word: "book", translation: "libro", pos: "noun", ipa: "/bʊk/", definition: "a set of pages used for reading or studying", example: "Open your book, please.", exampleTranslation: "Abre tu libro, por favor.", synonyms: ["textbook", "volume"], antonyms: [], collocations: ["open a book", "school book"], wordFamily: ["book", "booklet"], tags: ["school", "reading"], category: "object" }),
      w({ word: "listen", translation: "escuchar", pos: "verb", ipa: "/ˈlɪsən/", definition: "to pay attention to a sound", example: "Listen to the teacher.", exampleTranslation: "Escucha al profesor.", synonyms: ["hear", "pay attention"], antonyms: ["ignore"], collocations: ["listen carefully", "listen to instructions"], wordFamily: ["listen", "listener"], tags: ["school", "communication"], category: "action" }),
      w({ word: "write", translation: "escribir", pos: "verb", ipa: "/raɪt/", definition: "to make words with a pen or pencil", example: "Write your name here.", exampleTranslation: "Escribe tu nombre aquí.", synonyms: ["record", "note"], antonyms: [], collocations: ["write a sentence", "write your name"], wordFamily: ["write", "writer", "writing"], tags: ["school", "communication"], category: "action" }),
      w({ word: "answer", translation: "respuesta", pos: "noun", ipa: "/ˈænsər/", definition: "something said or written in response to a question", example: "I know the answer.", exampleTranslation: "Sé la respuesta.", synonyms: ["reply", "response"], antonyms: ["question"], collocations: ["correct answer", "give an answer"], wordFamily: ["answer", "answerable"], tags: ["school", "communication"], category: "communication" }),
    ],
    [{ phrase: "Open your book, please.", translation: "Abre tu libro, por favor." }, { phrase: "Listen and repeat.", translation: "Escucha y repite." }, { phrase: "Write your name here.", translation: "Escribe tu nombre aquí." }, { phrase: "I know the answer.", translation: "Sé la respuesta." }],
    [{ speaker: "A", text: "Where is my pencil?", translation: "¿Dónde está mi lápiz?" }, { speaker: "B", text: "It is on your desk.", translation: "Está sobre tu pupitre." }, { speaker: "A", text: "What do we do now?", translation: "¿Qué hacemos ahora?" }, { speaker: "B", text: "Listen and write the answer.", translation: "Escucha y escribe la respuesta." }],
    { title: "A New Lesson", text: "The teacher welcomes the class and puts a book, paper, and pencils on each desk. The students listen carefully, write their names, and answer a simple question.", translation: "El profesor da la bienvenida a la clase y pone un libro, papel y lápices en cada pupitre. Los estudiantes escuchan atentamente, escriben sus nombres y responden a una pregunta sencilla." }),
  ],
  A1: [
    u("u56", "Making an Appointment", "Arrange a simple appointment and confirm the time and place.", [
      w({ word: "appointment", translation: "cita", pos: "noun", ipa: "/əˈpɔɪntmənt/", definition: "an arrangement to meet someone at a particular time", example: "I have a dentist appointment on Friday.", exampleTranslation: "Tengo una cita con el dentista el viernes.", synonyms: ["meeting", "booking"], antonyms: [], collocations: ["make an appointment", "cancel an appointment"], wordFamily: ["appoint", "appointment"], tags: ["time", "health"], category: "arrangement" }),
      w({ word: "available", translation: "disponible", pos: "adjective", ipa: "/əˈveɪləbəl/", definition: "free and ready to be used or scheduled", example: "Are you available at three?", exampleTranslation: "¿Estás disponible a las tres?", synonyms: ["free", "open"], antonyms: ["busy", "unavailable"], collocations: ["available time", "available tomorrow"], wordFamily: ["avail, available, availability"], tags: ["time", "communication"], category: "schedule" }),
      w({ word: "confirm", translation: "confirmar", pos: "verb", ipa: "/kənˈfɜːrm/", definition: "to say that something is definitely arranged or true", example: "Please confirm the appointment by email.", exampleTranslation: "Confirma la cita por correo electrónico.", synonyms: ["verify", "approve"], antonyms: ["cancel"], collocations: ["confirm a booking", "confirm the time"], wordFamily: ["confirm, confirmation"], tags: ["communication", "time"], category: "action" }),
      w({ word: "cancel", translation: "cancelar", pos: "verb", ipa: "/ˈkænsəl/", definition: "to decide that an arranged event will not happen", example: "I need to cancel my appointment.", exampleTranslation: "Necesito cancelar mi cita.", synonyms: ["call off", "withdraw"], antonyms: ["arrange", "confirm"], collocations: ["cancel a meeting", "cancel an appointment"], wordFamily: ["cancel, cancellation"], tags: ["communication", "time"], category: "action" }),
      w({ word: "clinic", translation: "clínica", pos: "noun", ipa: "/ˈklɪnɪk/", definition: "a place where people receive medical care", example: "The clinic is near the station.", exampleTranslation: "La clínica está cerca de la estación.", synonyms: ["medical centre", "practice"], antonyms: [], collocations: ["local clinic", "visit a clinic"], wordFamily: ["clinic", "clinical"], tags: ["health", "places"], category: "place" }),
      w({ word: "delay", translation: "retraso", pos: "noun", ipa: "/dɪˈleɪ/", definition: "a period when something happens later than planned", example: "There was a delay because of traffic.", exampleTranslation: "Hubo un retraso por el tráfico.", synonyms: ["hold-up", "wait"], antonyms: ["promptness"], collocations: ["traffic delay", "unexpected delay"], wordFamily: ["delay", "delayed"], tags: ["time", "travel"], category: "problem" }),
      w({ word: "morning", translation: "mañana", pos: "noun", ipa: "/ˈmɔːrnɪŋ/", definition: "the part of the day before midday", example: "I prefer a morning appointment.", exampleTranslation: "Prefiero una cita por la mañana.", synonyms: ["early day"], antonyms: ["evening"], collocations: ["tomorrow morning", "early morning"], wordFamily: ["morning"], tags: ["time", "routine"], category: "time" }),
      w({ word: "address", translation: "dirección", pos: "noun", ipa: "/ˈædres/", definition: "the details of where a person or place is", example: "Could you send me the clinic address?", exampleTranslation: "¿Podrías enviarme la dirección de la clínica?", synonyms: ["location", "place"], antonyms: [], collocations: ["home address", "email address"], wordFamily: ["address", "addressed"], tags: ["places", "communication"], category: "information" }),
    ],
    [{ phrase: "Are you available tomorrow morning?", translation: "¿Estás disponible mañana por la mañana?" }, { phrase: "I would like to make an appointment.", translation: "Me gustaría pedir una cita." }, { phrase: "Could you confirm the address?", translation: "¿Podrías confirmar la dirección?" }, { phrase: "I am sorry, I need to cancel.", translation: "Lo siento, necesito cancelar." }],
    [{ speaker: "A", text: "Are you available on Thursday morning?", translation: "¿Estás disponible el jueves por la mañana?" }, { speaker: "B", text: "Yes. What time is the appointment?", translation: "Sí. ¿A qué hora es la cita?" }, { speaker: "A", text: "At ten, at the clinic near the station.", translation: "A las diez, en la clínica cerca de la estación." }, { speaker: "B", text: "Please confirm the address by email.", translation: "Confirma la dirección por correo electrónico, por favor." }],
    { title: "A Confirmed Appointment", text: "Maya calls a local clinic to arrange an appointment. The receptionist offers Thursday morning, confirms the time and address, and warns Maya that traffic may cause a short delay.", translation: "Maya llama a una clínica local para concertar una cita. La recepcionista ofrece el jueves por la mañana, confirma la hora y la dirección, y advierte a Maya que el tráfico puede causar un pequeño retraso." }),
  ],
  A2: [
    u("u56", "Digital Communication", "Write clear messages, discuss online habits, and manage digital communication.", [
      w({ word: "message", translation: "mensaje", pos: "noun", ipa: "/ˈmesɪdʒ/", definition: "a piece of information sent to someone", example: "I left a message on your phone.", exampleTranslation: "Dejé un mensaje en tu teléfono.", synonyms: ["note", "communication"], antonyms: [], collocations: ["send a message", "voice message"], wordFamily: ["message, messenger"], tags: ["technology", "communication"], category: "communication" }),
      w({ word: "attachment", translation: "archivo adjunto", pos: "noun", ipa: "/əˈtætʃmənt/", definition: "a file sent together with an email", example: "The report is in the attachment.", exampleTranslation: "El informe está en el archivo adjunto.", synonyms: ["enclosure", "file"], antonyms: [], collocations: ["email attachment", "open an attachment"], wordFamily: ["attach", "attachment"], tags: ["technology", "work"], category: "digital object" }),
      w({ word: "privacy", translation: "privacidad", pos: "noun", ipa: "/ˈpraɪvəsi/", definition: "the right to keep personal information away from others", example: "Check your privacy settings regularly.", exampleTranslation: "Revisa tus ajustes de privacidad con regularidad.", synonyms: ["confidentiality", "seclusion"], antonyms: ["exposure"], collocations: ["online privacy", "protect privacy"], wordFamily: ["private, privacy"], tags: ["technology", "safety"], category: "digital life" }),
      w({ word: "password", translation: "contraseña", pos: "noun", ipa: "/ˈpæswɜːrd/", definition: "a secret word used to access an account", example: "Create a strong password.", exampleTranslation: "Crea una contraseña segura.", synonyms: ["passcode", "access code"], antonyms: [], collocations: ["strong password", "reset a password"], wordFamily: ["pass, password"], tags: ["technology", "safety"], category: "security" }),
      w({ word: "notification", translation: "notificación", pos: "noun", ipa: "/ˌnoʊtɪfɪˈkeɪʃən/", definition: "a message that tells you about a new event or action", example: "I turned off social media notifications.", exampleTranslation: "Desactivé las notificaciones de las redes sociales.", synonyms: ["alert", "notice"], antonyms: [], collocations: ["push notification", "receive a notification"], wordFamily: ["notify, notification"], tags: ["technology", "routine"], category: "digital object" }),
      w({ word: "reliable", translation: "fiable", pos: "adjective", ipa: "/rɪˈlaɪəbəl/", definition: "working well and able to be trusted", example: "This is a reliable news source.", exampleTranslation: "Esta es una fuente de noticias fiable.", synonyms: ["dependable", "trustworthy"], antonyms: ["unreliable"], collocations: ["reliable source", "reliable connection"], wordFamily: ["rely, reliable, reliability"], tags: ["technology", "quality"], category: "quality" }),
      w({ word: "upload", translation: "subir", pos: "verb", ipa: "/ˈʌploʊd/", definition: "to send a file from your device to the internet", example: "Please upload the completed form.", exampleTranslation: "Sube el formulario completado, por favor.", synonyms: ["send", "post"], antonyms: ["download"], collocations: ["upload a file", "upload a photo"], wordFamily: ["upload, uploader"], tags: ["technology", "work"], category: "action" }),
      w({ word: "download", translation: "descargar", pos: "verb", ipa: "/ˈdaʊnloʊd/", definition: "to copy a file from the internet to your device", example: "Download the guide before the trip.", exampleTranslation: "Descarga la guía antes del viaje.", synonyms: ["save", "copy"], antonyms: ["upload"], collocations: ["download a file", "download an app"], wordFamily: ["download"], tags: ["technology", "work"], category: "action" }),
    ],
    [{ phrase: "I have attached the document.", translation: "He adjuntado el documento." }, { phrase: "Please protect your privacy.", translation: "Protege tu privacidad, por favor." }, { phrase: "I will upload the form today.", translation: "Subiré el formulario hoy." }, { phrase: "The connection is not reliable.", translation: "La conexión no es fiable." }],
    [{ speaker: "A", text: "Did you receive my message?", translation: "¿Recibiste mi mensaje?" }, { speaker: "B", text: "Yes, but the attachment would not download.", translation: "Sí, pero el archivo adjunto no se pudo descargar." }, { speaker: "A", text: "I will upload it again.", translation: "Lo subiré otra vez." }, { speaker: "B", text: "Thanks. I will check my notifications.", translation: "Gracias. Revisaré mis notificaciones." }],
    { title: "A Clear Digital Message", text: "Leo sends a short work message with an attachment. When the file fails to download, he uploads it again and checks that the recipient can open it. Both colleagues keep their passwords and privacy settings secure.", translation: "Leo envía un mensaje breve de trabajo con un archivo adjunto. Cuando el archivo no se puede descargar, lo vuelve a subir y comprueba que el destinatario pueda abrirlo. Ambos colegas mantienen seguras sus contraseñas y sus opciones de privacidad." }),
  ],
  B1: [
    u("u56", "Effective Teamwork", "Explain roles, feedback, and decisions in a professional team.", [
      w({ word: "collaborate", translation: "colaborar", pos: "verb", ipa: "/kəˈlæbəreɪt/", definition: "to work with other people to achieve something", example: "The designers collaborate with the engineers.", exampleTranslation: "Los diseñadores colaboran con los ingenieros.", synonyms: ["cooperate", "work together"], antonyms: ["compete"], collocations: ["collaborate closely", "collaborate on a project"], wordFamily: ["collaborate, collaboration, collaborative"], tags: ["work", "communication"], category: "action" }),
      w({ word: "feedback", translation: "comentarios", pos: "noun", ipa: "/ˈfiːdbæk/", definition: "advice or opinions about how something can improve", example: "The manager gave helpful feedback.", exampleTranslation: "El gerente dio comentarios útiles.", synonyms: ["response", "evaluation"], antonyms: [], collocations: ["constructive feedback", "give feedback"], wordFamily: ["feedback"], tags: ["work", "communication"], category: "communication" }),
      w({ word: "deadline", translation: "fecha límite", pos: "noun", ipa: "/ˈdedlaɪn/", definition: "the latest time by which something must be finished", example: "We must meet the deadline.", exampleTranslation: "Debemos cumplir la fecha límite.", synonyms: ["due date", "time limit"], antonyms: [], collocations: ["meet a deadline", "tight deadline"], wordFamily: ["deadline"], tags: ["work", "time"], category: "planning" }),
      w({ word: "delegate", translation: "delegar", pos: "verb", ipa: "/ˈdelɪɡeɪt/", definition: "to give a task or responsibility to another person", example: "A good leader knows when to delegate.", exampleTranslation: "Un buen líder sabe cuándo delegar.", synonyms: ["assign", "entrust"], antonyms: ["retain"], collocations: ["delegate a task", "delegate responsibility"], wordFamily: ["delegate, delegation"], tags: ["work", "management"], category: "action" }),
      w({ word: "agenda", translation: "orden del día", pos: "noun", ipa: "/əˈdʒendə/", definition: "a list of topics to discuss at a meeting", example: "The first item on the agenda is the budget.", exampleTranslation: "El primer punto del orden del día es el presupuesto.", synonyms: ["schedule", "plan"], antonyms: [], collocations: ["meeting agenda", "set an agenda"], wordFamily: ["agenda"], tags: ["work", "planning"], category: "document" }),
      w({ word: "consensus", translation: "consenso", pos: "noun", ipa: "/kənˈsensəs/", definition: "general agreement in a group", example: "The team reached a consensus.", exampleTranslation: "El equipo llegó a un consenso.", synonyms: ["agreement", "accord"], antonyms: ["disagreement"], collocations: ["reach consensus", "broad consensus"], wordFamily: ["consensus"], tags: ["work", "communication"], category: "agreement" }),
      w({ word: "contribute", translation: "contribuir", pos: "verb", ipa: "/kənˈtrɪbjuːt/", definition: "to give ideas, time, or work to a shared activity", example: "Everyone contributed an idea.", exampleTranslation: "Todos contribuyeron con una idea.", synonyms: ["participate", "add"], antonyms: ["withhold"], collocations: ["contribute ideas", "contribute to a project"], wordFamily: ["contribute, contribution, contributor"], tags: ["work", "communication"], category: "action" }),
      w({ word: "outcome", translation: "resultado", pos: "noun", ipa: "/ˈaʊtkʌm/", definition: "the final result of an action or process", example: "The meeting produced a positive outcome.", exampleTranslation: "La reunión produjo un resultado positivo.", synonyms: ["result", "consequence"], antonyms: [], collocations: ["positive outcome", "expected outcome"], wordFamily: ["outcome"], tags: ["work", "planning"], category: "result" }),
    ],
    [{ phrase: "Let us add that to the agenda.", translation: "Añadamos eso al orden del día." }, { phrase: "Could you give me some feedback?", translation: "¿Podrías darme algunos comentarios?" }, { phrase: "Who will take responsibility for this task?", translation: "¿Quién asumirá la responsabilidad de esta tarea?" }, { phrase: "We need to meet the deadline.", translation: "Tenemos que cumplir la fecha límite." }],
    [{ speaker: "A", text: "Can we meet the deadline?", translation: "¿Podemos cumplir la fecha límite?" }, { speaker: "B", text: "Yes, if we delegate two tasks and collaborate closely.", translation: "Sí, si delegamos dos tareas y colaboramos estrechamente." }, { speaker: "A", text: "What is the expected outcome?", translation: "¿Cuál es el resultado esperado?" }, { speaker: "B", text: "A clear plan and consensus on the next step.", translation: "Un plan claro y consenso sobre el siguiente paso." }],
    { title: "One Team, One Plan", text: "A project team begins its meeting with a clear agenda. Members contribute ideas, give constructive feedback, and delegate tasks according to their strengths. By the end, they reach consensus and agree on an achievable deadline.", translation: "Un equipo de proyecto comienza su reunión con un orden del día claro. Los miembros aportan ideas, ofrecen comentarios constructivos y delegan tareas según sus fortalezas. Al final, llegan a un consenso y acuerdan una fecha límite alcanzable." }),
  ],
  B2: [
    u("u56", "Research Methods", "Evaluate evidence, hypotheses, and the limits of a research study.", [
      w({ word: "hypothesis", translation: "hipótesis", pos: "noun", ipa: "/haɪˈpɑːθəsɪs/", definition: "an idea that is tested through research", example: "The experiment supports the original hypothesis.", exampleTranslation: "El experimento respalda la hipótesis original.", synonyms: ["proposition", "theory"], antonyms: [], collocations: ["test a hypothesis", "working hypothesis"], wordFamily: ["hypothesise, hypothesis, hypothetical"], tags: ["science", "research"], category: "research" }),
      w({ word: "evidence", translation: "evidencia", pos: "noun", ipa: "/ˈevɪdəns/", definition: "facts or information that show whether something is true", example: "The evidence is not conclusive.", exampleTranslation: "La evidencia no es concluyente.", synonyms: ["proof", "indication"], antonyms: [], collocations: ["strong evidence", "evidence suggests"], wordFamily: ["evident, evidence"], tags: ["science", "thinking"], category: "research" }),
      w({ word: "sample", translation: "muestra", pos: "noun", ipa: "/ˈsæmpəl/", definition: "a small group chosen to represent a larger group", example: "The sample included five hundred participants.", exampleTranslation: "La muestra incluyó a quinientos participantes.", synonyms: ["selection", "cross-section"], antonyms: [], collocations: ["representative sample", "sample size"], wordFamily: ["sample, sampling"], tags: ["science", "data"], category: "research" }),
      w({ word: "bias", translation: "sesgo", pos: "noun", ipa: "/ˈbaɪəs/", definition: "an unfair preference that can influence a result", example: "The researchers tried to reduce selection bias.", exampleTranslation: "Los investigadores intentaron reducir el sesgo de selección.", synonyms: ["prejudice", "partiality"], antonyms: ["objectivity"], collocations: ["avoid bias", "research bias"], wordFamily: ["bias, biased"], tags: ["science", "ethics"], category: "quality" }),
      w({ word: "variable", translation: "variable", pos: "noun", ipa: "/ˈveriəbəl/", definition: "a factor that can change in a study", example: "Age was the main independent variable.", exampleTranslation: "La edad fue la principal variable independiente.", synonyms: ["factor", "element"], antonyms: ["constant"], collocations: ["independent variable", "control a variable"], wordFamily: ["vary, variable, variation"], tags: ["science", "data"], category: "research" }),
      w({ word: "correlation", translation: "correlación", pos: "noun", ipa: "/ˌkɔːrəˈleɪʃən/", definition: "a relationship in which two things change together", example: "The study found a correlation between sleep and memory.", exampleTranslation: "El estudio encontró una correlación entre el sueño y la memoria.", synonyms: ["association", "relationship"], antonyms: [], collocations: ["strong correlation", "correlation between"], wordFamily: ["correlate, correlation"], tags: ["science", "data"], category: "relationship" }),
      w({ word: "replicate", translation: "replicar", pos: "verb", ipa: "/ˈreplɪkeɪt/", definition: "to repeat a study or result to check it", example: "Another team failed to replicate the finding.", exampleTranslation: "Otro equipo no pudo replicar el hallazgo.", synonyms: ["repeat", "reproduce"], antonyms: [], collocations: ["replicate a study", "replicate results"], wordFamily: ["replicate, replication"], tags: ["science", "research"], category: "action" }),
      w({ word: "limitation", translation: "limitación", pos: "noun", ipa: "/ˌlɪmɪˈteɪʃən/", definition: "a factor that reduces what a study can show", example: "The small sample is an important limitation.", exampleTranslation: "La muestra pequeña es una limitación importante.", synonyms: ["constraint", "shortcoming"], antonyms: ["strength"], collocations: ["study limitation", "acknowledge a limitation"], wordFamily: ["limit, limitation"], tags: ["science", "thinking"], category: "quality" }),
    ],
    [{ phrase: "The evidence is not conclusive.", translation: "La evidencia no es concluyente." }, { phrase: "The sample may contain bias.", translation: "La muestra puede contener sesgo." }, { phrase: "Correlation does not prove causation.", translation: "La correlación no demuestra causalidad." }, { phrase: "The result should be replicated.", translation: "El resultado debería replicarse." }],
    [{ speaker: "A", text: "What is the main limitation of the study?", translation: "¿Cuál es la principal limitación del estudio?" }, { speaker: "B", text: "The sample is small and may contain selection bias.", translation: "La muestra es pequeña y puede contener sesgo de selección." }, { speaker: "A", text: "Does the evidence support the hypothesis?", translation: "¿La evidencia respalda la hipótesis?" }, { speaker: "B", text: "It suggests a correlation, but the result needs replication.", translation: "Sugiere una correlación, pero el resultado necesita replicarse." }],
    { title: "Reading a Study Carefully", text: "A responsible reader examines a study's hypothesis, sample, variables, and evidence. A correlation may be interesting without proving causation. Researchers should describe limitations, reduce bias, and replicate important results before making strong claims.", translation: "Un lector responsable examina la hipótesis, la muestra, las variables y la evidencia de un estudio. Una correlación puede ser interesante sin demostrar causalidad. Los investigadores deben describir las limitaciones, reducir el sesgo y replicar los resultados importantes antes de hacer afirmaciones contundentes." }),
  ],
  C1: [
    u("u56", "Media Literacy", "Assess sources, framing, and uncertainty in modern media.", [
      w({ word: "framing", translation: "encuadre", pos: "noun", ipa: "/ˈfreɪmɪŋ/", definition: "the way information is selected and presented to shape interpretation", example: "The article's framing emphasises conflict.", exampleTranslation: "El encuadre del artículo enfatiza el conflicto.", synonyms: ["presentation", "angle"], antonyms: [], collocations: ["media framing", "political framing"], wordFamily: ["frame, framing"], tags: ["media", "thinking"], category: "analysis" }),
      w({ word: "misinformation", translation: "desinformación", pos: "noun", ipa: "/ˌmɪsɪnfərˈmeɪʃən/", definition: "false or inaccurate information, whether spread deliberately or not", example: "Readers need tools to recognise misinformation.", exampleTranslation: "Los lectores necesitan herramientas para reconocer la desinformación.", synonyms: ["false information", "inaccuracy"], antonyms: ["accurate information"], collocations: ["spread misinformation", "combat misinformation"], wordFamily: ["inform, information, misinformation"], tags: ["media", "society"], category: "information" }),
      w({ word: "source", translation: "fuente", pos: "noun", ipa: "/sɔːrs/", definition: "a person or record that provides information", example: "The journalist protected the source.", exampleTranslation: "El periodista protegió a la fuente.", synonyms: ["origin", "reference"], antonyms: [], collocations: ["reliable source", "anonymous source"], wordFamily: ["source, sourced"], tags: ["media", "research"], category: "information" }),
      w({ word: "credibility", translation: "credibilidad", pos: "noun", ipa: "/ˌkredəˈbɪləti/", definition: "the quality of being trusted or believed", example: "The correction restored the paper's credibility.", exampleTranslation: "La corrección restauró la credibilidad del periódico.", synonyms: ["trustworthiness", "reliability"], antonyms: ["unreliability"], collocations: ["professional credibility", "question credibility"], wordFamily: ["credible, credibility"], tags: ["media", "ethics"], category: "quality" }),
      w({ word: "contextualise", translation: "contextualizar", pos: "verb", ipa: "/kənˈtekstʃuəlaɪz/", definition: "to explain information by showing its wider situation", example: "Good reporting contextualises a quotation.", exampleTranslation: "El buen periodismo contextualiza una cita.", synonyms: ["situate", "interpret"], antonyms: [], collocations: ["contextualise evidence", "contextualise a debate"], wordFamily: ["context, contextual, contextualise"], tags: ["media", "thinking"], category: "action" }),
      w({ word: "sensationalism", translation: "sensacionalismo", pos: "noun", ipa: "/senˈseɪʃənəlɪzəm/", definition: "the use of shocking details to attract attention", example: "Sensationalism can weaken public debate.", exampleTranslation: "El sensacionalismo puede debilitar el debate público.", synonyms: ["hype", "exaggeration"], antonyms: ["restraint"], collocations: ["media sensationalism", "avoid sensationalism"], wordFamily: ["sensation, sensational, sensationalism"], tags: ["media", "ethics"], category: "style" }),
      w({ word: "editorialise", translation: "editorializar", pos: "verb", ipa: "/ˌedɪˈtɔːriəlaɪz/", definition: "to express an opinion instead of reporting facts neutrally", example: "The report informs without editorialising.", exampleTranslation: "El informe informa sin editorializar.", synonyms: ["comment", "interpret"], antonyms: ["report neutrally"], collocations: ["editorialise about", "avoid editorialising"], wordFamily: ["editor, editorial, editorialise"], tags: ["media", "writing"], category: "communication" }),
      w({ word: "provenance", translation: "procedencia", pos: "noun", ipa: "/ˈprɑːvənəns/", definition: "the history or origin of information or an object", example: "The database records the provenance of each image.", exampleTranslation: "La base de datos registra la procedencia de cada imagen.", synonyms: ["origin", "background"], antonyms: [], collocations: ["data provenance", "uncertain provenance"], wordFamily: ["provenance"], tags: ["media", "research"], category: "information" }),
    ],
    [{ phrase: "Check the provenance of the claim.", translation: "Comprueba la procedencia de la afirmación." }, { phrase: "The article needs more context.", translation: "El artículo necesita más contexto." }, { phrase: "This framing may influence readers.", translation: "Este encuadre puede influir en los lectores." }, { phrase: "Avoid sensationalism in reporting.", translation: "Evita el sensacionalismo al informar." }],
    [{ speaker: "A", text: "Why should we question the article?", translation: "¿Por qué debemos cuestionar el artículo?" }, { speaker: "B", text: "Its source is unclear and its framing is highly sensationalist.", translation: "Su fuente no está clara y su encuadre es muy sensacionalista." }, { speaker: "A", text: "How can we assess its credibility?", translation: "¿Cómo podemos evaluar su credibilidad?" }, { speaker: "B", text: "Check the provenance, compare sources, and read the wider context.", translation: "Comprueba la procedencia, compara las fuentes y lee el contexto más amplio." }],
    { title: "Beyond the Headline", text: "Media literacy requires more than spotting an incorrect fact. Readers should examine provenance, identify framing, and distinguish reporting from editorialising. Contextualising evidence can reveal uncertainty, while sensationalism may obscure the issues that matter most.", translation: "La alfabetización mediática exige más que detectar un dato incorrecto. Los lectores deben examinar la procedencia, identificar el encuadre y distinguir la información de la editorialización. Contextualizar la evidencia puede revelar incertidumbre, mientras que el sensacionalismo puede ocultar los asuntos más importantes." }),
  ],
  C2: [
    u("u56", "Discourse Analysis", "Analyse how language, presupposition, and stance shape meaning in texts.", [
      w({ word: "presupposition", translation: "presuposición", pos: "noun", ipa: "/ˌpriːsʌpəˈzɪʃən/", definition: "an assumption implied by a statement rather than directly expressed", example: "The question contains a controversial presupposition.", exampleTranslation: "La pregunta contiene una presuposición controvertida.", synonyms: ["assumption", "implication"], antonyms: [], collocations: ["underlying presupposition", "challenge a presupposition"], wordFamily: ["presuppose, presupposition"], tags: ["linguistics", "rhetoric"], category: "analysis" }),
      w({ word: "stance", translation: "postura discursiva", pos: "noun", ipa: "/stæns/", definition: "the attitude or position expressed by a speaker or writer", example: "The author's stance becomes clearer in the final paragraph.", exampleTranslation: "La postura del autor se vuelve más clara en el último párrafo.", synonyms: ["position", "attitude"], antonyms: [], collocations: ["political stance", "adopt a stance"], wordFamily: ["stand, stance"], tags: ["linguistics", "communication"], category: "discourse" }),
      w({ word: "register", translation: "registro lingüístico", pos: "noun", ipa: "/ˈredʒɪstər/", definition: "a style of language suitable for a particular situation", example: "The formal register suits the legal document.", exampleTranslation: "El registro formal es adecuado para el documento jurídico.", synonyms: ["style", "level"], antonyms: [], collocations: ["formal register", "academic register"], wordFamily: ["register, registered"], tags: ["linguistics", "writing"], category: "language" }),
      w({ word: "cohesion", translation: "cohesión", pos: "noun", ipa: "/koʊˈhiːʒən/", definition: "the way parts of a text connect grammatically and lexically", example: "Pronouns improve cohesion between sentences.", exampleTranslation: "Los pronombres mejoran la cohesión entre frases.", synonyms: ["unity", "connectedness"], antonyms: ["incoherence"], collocations: ["textual cohesion", "cohesion device"], wordFamily: ["cohere, cohesion, cohesive"], tags: ["linguistics", "writing"], category: "text" }),
      w({ word: "coherence", translation: "coherencia", pos: "noun", ipa: "/koʊˈhɪrəns/", definition: "the quality of being logical and easy to understand as a whole", example: "The conclusion gives the essay coherence.", exampleTranslation: "La conclusión da coherencia al ensayo.", synonyms: ["clarity", "logic"], antonyms: ["confusion"], collocations: ["logical coherence", "lack coherence"], wordFamily: ["cohere, coherent, coherence"], tags: ["linguistics", "thinking"], category: "text" }),
      w({ word: "implicature", translation: "implicatura", pos: "noun", ipa: "/ˈɪmplɪkətʃər/", definition: "a meaning suggested by what is said but not explicitly stated", example: "The reply carries an implicature of refusal.", exampleTranslation: "La respuesta contiene una implicatura de rechazo.", synonyms: ["implication", "suggestion"], antonyms: [], collocations: ["conversational implicature", "infer an implicature"], wordFamily: ["imply, implication, implicature"], tags: ["linguistics", "pragmatics"], category: "meaning" }),
      w({ word: "mitigate", translation: "atenuar", pos: "verb", ipa: "/ˈmɪtɪɡeɪt/", definition: "to make an effect or statement less strong", example: "The speaker mitigates the criticism with a concession.", exampleTranslation: "El hablante atenúa la crítica con una concesión.", synonyms: ["soften", "moderate"], antonyms: ["intensify"], collocations: ["mitigate criticism", "mitigate a claim"], wordFamily: ["mitigate, mitigation"], tags: ["rhetoric", "communication"], category: "action" }),
      w({ word: "ambiguity", translation: "ambigüedad", pos: "noun", ipa: "/ˌæmbɪˈɡjuːəti/", definition: "the presence of more than one possible meaning", example: "The ambiguity is deliberate rather than accidental.", exampleTranslation: "La ambigüedad es deliberada y no accidental.", synonyms: ["uncertainty", "equivocation"], antonyms: ["clarity"], collocations: ["deliberate ambiguity", "resolve ambiguity"], wordFamily: ["ambiguous, ambiguity"], tags: ["linguistics", "literature"], category: "meaning" }),
    ],
    [{ phrase: "What is the implied stance?", translation: "¿Cuál es la postura implícita?" }, { phrase: "The phrase carries an implicature.", translation: "La frase contiene una implicatura." }, { phrase: "The register is deliberately formal.", translation: "El registro es deliberadamente formal." }, { phrase: "The ambiguity is open to interpretation.", translation: "La ambigüedad está abierta a interpretación." }],
    [{ speaker: "A", text: "Why is the final question difficult to interpret?", translation: "¿Por qué es difícil interpretar la pregunta final?" }, { speaker: "B", text: "It contains a presupposition and a possible implicature.", translation: "Contiene una presuposición y una posible implicatura." }, { speaker: "A", text: "Does the register affect its meaning?", translation: "¿Afecta el registro a su significado?" }, { speaker: "B", text: "Yes. The formal register mitigates the criticism but preserves the stance.", translation: "Sí. El registro formal atenúa la crítica, pero conserva la postura." }],
    { title: "Meaning Between the Lines", text: "Discourse analysis examines how a text creates meaning through register, cohesion, coherence, and stance. A statement may carry an implicature or presupposition beyond its literal wording. Careful readers therefore attend to ambiguity rather than treating every sentence as transparent.", translation: "El análisis del discurso examina cómo un texto crea significado mediante el registro, la cohesión, la coherencia y la postura. Una afirmación puede contener una implicatura o presuposición más allá de sus palabras literales. Por eso, los lectores atentos prestan atención a la ambigüedad en lugar de considerar transparente cada frase." }),
  ],
};
