import type { VocabularyItem } from "./learn-data";

/**
 * Additional English vocabulary keyed by existing CEFR level and unit id.
 * This bank enriches lessons in place; it never creates or renames units.
 */
export const ENGLISH_UNIT_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  A0: {
    u54: [
      { word: "raincoat", translation: "impermeable", pos: "noun", ipa: "/ˈreɪnkoʊt/", definition: "a coat that keeps you dry in the rain", example: "Take your raincoat because the sky is dark.", exampleTranslation: "Lleva tu impermeable porque el cielo está oscuro.", synonyms: ["waterproof coat"], antonyms: [], collocations: ["wear a raincoat", "yellow raincoat"], wordFamily: ["rain", "raincoat", "rainy"], tags: ["weather", "clothes"], category: "clothing" },
      { word: "breeze", translation: "brisa", pos: "noun", ipa: "/briːz/", definition: "a light wind", example: "A cool breeze comes through the window.", exampleTranslation: "Una brisa fresca entra por la ventana.", synonyms: ["light wind", "wind"], antonyms: ["stillness"], collocations: ["cool breeze", "gentle breeze"], wordFamily: ["breeze", "breezy"], tags: ["weather", "nature"], category: "weather" },
    ],
    u55: [
      { word: "drawer", translation: "cajón", pos: "noun", ipa: "/drɔːr/", definition: "a sliding box in a piece of furniture used for storage", example: "The scissors are in the top drawer.", exampleTranslation: "Las tijeras están en el cajón de arriba.", synonyms: ["compartment"], antonyms: [], collocations: ["desk drawer", "open a drawer"], wordFamily: ["draw", "drawer"], tags: ["home", "objects"], category: "furniture" },
      { word: "umbrella", translation: "paraguas", pos: "noun", ipa: "/ʌmˈbrelə/", definition: "a folding object used to protect you from rain", example: "I keep an umbrella by the door.", exampleTranslation: "Guardo un paraguas junto a la puerta.", synonyms: ["parasol"], antonyms: [], collocations: ["carry an umbrella", "folding umbrella"], wordFamily: ["umbrella"], tags: ["weather", "objects"], category: "object" },
    ],
    u56: [
      { word: "ruler", translation: "regla", pos: "noun", ipa: "/ˈruːlər/", definition: "a straight tool used to measure or draw lines", example: "The ruler is next to my pencil.", exampleTranslation: "La regla está junto a mi lápiz.", synonyms: ["measuring stick"], antonyms: [], collocations: ["school ruler", "use a ruler"], wordFamily: ["rule", "ruler"], tags: ["school", "objects"], category: "object" },
      { word: "notebook", translation: "cuaderno", pos: "noun", ipa: "/ˈnoʊtbʊk/", definition: "a book of blank pages for writing notes", example: "I write new words in my notebook.", exampleTranslation: "Escribo palabras nuevas en mi cuaderno.", synonyms: ["exercise book", "notepad"], antonyms: [], collocations: ["school notebook", "open a notebook"], wordFamily: ["note", "notebook"], tags: ["school", "writing"], category: "object" },
      { word: "eraser", translation: "goma de borrar", pos: "noun", ipa: "/ɪˈreɪsər/", definition: "a small object used to remove pencil marks", example: "Use an eraser for this mark.", exampleTranslation: "Usa una goma de borrar para esta marca.", synonyms: ["rubber"], antonyms: [], collocations: ["pencil eraser", "use an eraser"], wordFamily: ["erase", "eraser", "erasable"], tags: ["school", "objects"], category: "object" },
      { word: "question", translation: "pregunta", pos: "noun", ipa: "/ˈkwestʃən/", definition: "words used to ask for information", example: "The student asks a question.", exampleTranslation: "El estudiante hace una pregunta.", synonyms: ["query", "inquiry"], antonyms: ["answer"], collocations: ["ask a question", "simple question"], wordFamily: ["question", "questioner", "questioning"], tags: ["school", "communication"], category: "communication" },
    ],
  },
  A1: {
    u54: [
      { word: "destination", translation: "destino", pos: "noun", ipa: "/ˌdestɪˈneɪʃən/", definition: "the place where someone or something is going", example: "Our destination is the city centre.", exampleTranslation: "Nuestro destino es el centro de la ciudad.", synonyms: ["endpoint", "arrival point"], antonyms: ["departure"], collocations: ["final destination", "reach a destination"], wordFamily: ["destine", "destination"], tags: ["travel", "places"], category: "travel" },
      { word: "cancellation", translation: "cancelación", pos: "noun", ipa: "/ˌkænsəˈleɪʃən/", definition: "the act of stopping an event or service that was planned", example: "The airline sent a message about the flight cancellation.", exampleTranslation: "La aerolínea envió un mensaje sobre la cancelación del vuelo.", synonyms: ["call-off", "withdrawal"], antonyms: ["confirmation"], collocations: ["flight cancellation", "cancellation notice"], wordFamily: ["cancel", "cancellation", "cancelled"], tags: ["travel", "communication"], category: "event" },
    ],
    u55: [
      { word: "bandage", translation: "vendaje", pos: "noun", ipa: "/ˈbændɪdʒ/", definition: "a strip of material used to cover and protect a wound", example: "Put a clean bandage on the cut.", exampleTranslation: "Pon un vendaje limpio sobre el corte.", synonyms: ["dressing", "strip"], antonyms: [], collocations: ["clean bandage", "apply a bandage"], wordFamily: ["bandage", "bandaged"], tags: ["health", "body"], category: "medical object" },
      { word: "syrup", translation: "jarabe", pos: "noun", ipa: "/ˈsɪrəp/", definition: "a thick sweet liquid, often used as medicine", example: "The pharmacist recommended a cough syrup.", exampleTranslation: "El farmacéutico recomendó un jarabe para la tos.", synonyms: ["medicine", "liquid medicine"], antonyms: [], collocations: ["cough syrup", "a spoonful of syrup"], wordFamily: ["syrup"], tags: ["health", "medicine"], category: "medicine" },
    ],
    u56: [
      { word: "reschedule", translation: "reprogramar", pos: "verb", ipa: "/ˌriːˈskedʒuːl/", definition: "to arrange an event for a different time", example: "Can we reschedule the appointment for Friday?", exampleTranslation: "¿Podemos reprogramar la cita para el viernes?", synonyms: ["rearrange", "rebook"], antonyms: [], collocations: ["reschedule a meeting", "reschedule an appointment"], wordFamily: ["schedule", "reschedule", "rescheduling"], tags: ["time", "communication"], category: "action" },
      { word: "reception", translation: "recepción", pos: "noun", ipa: "/rɪˈsepʃən/", definition: "the place where visitors are welcomed and helped", example: "Please ask at reception.", exampleTranslation: "Pregunta en recepción, por favor.", synonyms: ["front desk", "welcome desk"], antonyms: [], collocations: ["clinic reception", "reception desk"], wordFamily: ["receive", "reception", "receptionist"], tags: ["places", "communication"], category: "place" },
      { word: "afternoon", translation: "tarde", pos: "noun", ipa: "/ˌæftərˈnuːn/", definition: "the part of the day between midday and evening", example: "The clinic is open in the afternoon.", exampleTranslation: "La clínica está abierta por la tarde.", synonyms: ["after lunch"], antonyms: ["morning"], collocations: ["this afternoon", "afternoon appointment"], wordFamily: ["afternoon"], tags: ["time", "routine"], category: "time" },
      { word: "reminder", translation: "recordatorio", pos: "noun", ipa: "/rɪˈmaɪndər/", definition: "a message that helps you remember something", example: "The clinic sent a reminder by text.", exampleTranslation: "La clínica envió un recordatorio por mensaje.", synonyms: ["prompt", "notice"], antonyms: [], collocations: ["send a reminder", "appointment reminder"], wordFamily: ["remind", "reminder"], tags: ["time", "communication"], category: "message" },
    ],
  },
  A2: {
    u54: [
      { word: "landmark", translation: "monumento", pos: "noun", ipa: "/ˈlændmɑːrk/", definition: "a well-known place or building that helps people recognise a location", example: "The bridge is a famous city landmark.", exampleTranslation: "El puente es un monumento famoso de la ciudad.", synonyms: ["monument", "reference point"], antonyms: [], collocations: ["historic landmark", "famous landmark"], wordFamily: ["land", "landmark"], tags: ["travel", "places"], category: "place" },
      { word: "overnight", translation: "durante la noche", pos: "adverb", ipa: "/ˌoʊvərˈnaɪt/", definition: "during one night or from one evening until the next morning", example: "We took an overnight train to the coast.", exampleTranslation: "Tomamos un tren nocturno hasta la costa.", synonyms: ["at night", "night-long"], antonyms: ["during the day"], collocations: ["overnight stay", "overnight train"], wordFamily: ["night", "overnight"], tags: ["travel", "time"], category: "time" },
    ],
    u55: [
      { word: "concentrate", translation: "concentrarse", pos: "verb", ipa: "/ˈkɑːnsəntreɪt/", definition: "to give all your attention to one thing", example: "I concentrate better in a quiet room.", exampleTranslation: "Me concentro mejor en una habitación tranquila.", synonyms: ["focus", "pay attention"], antonyms: ["distract"], collocations: ["concentrate on a task", "concentrate fully"], wordFamily: ["concentrate", "concentration", "concentrated"], tags: ["learning", "thinking"], category: "mental action" },
      { word: "distraction", translation: "distracción", pos: "noun", ipa: "/dɪˈstrækʃən/", definition: "something that takes your attention away from what you are doing", example: "Put your phone away to avoid distraction.", exampleTranslation: "Guarda el teléfono para evitar distracciones.", synonyms: ["interruption", "diversion"], antonyms: ["focus", "concentration"], collocations: ["avoid distraction", "major distraction"], wordFamily: ["distract", "distraction", "distracted"], tags: ["learning", "routine"], category: "challenge" },
    ],
    u56: [
      { word: "browser", translation: "navegador", pos: "noun", ipa: "/ˈbraʊzər/", definition: "a program used to view websites", example: "Open the link in your browser.", exampleTranslation: "Abre el enlace en tu navegador.", synonyms: ["web browser"], antonyms: [], collocations: ["web browser", "browser window"], wordFamily: ["browse", "browser", "browsing"], tags: ["technology", "internet"], category: "software" },
      { word: "screen", translation: "pantalla", pos: "noun", ipa: "/skriːn/", definition: "the flat surface on a device that shows images and text", example: "The message appears on my screen.", exampleTranslation: "El mensaje aparece en mi pantalla.", synonyms: ["display", "monitor"], antonyms: [], collocations: ["phone screen", "screen size"], wordFamily: ["screen", "screening"], tags: ["technology", "devices"], category: "object" },
      { word: "secure", translation: "seguro", pos: "adjective", ipa: "/sɪˈkjʊər/", definition: "protected from danger, loss, or unwanted access", example: "Use a secure connection for online banking.", exampleTranslation: "Usa una conexión segura para la banca en línea.", synonyms: ["safe", "protected"], antonyms: ["unsafe", "vulnerable"], collocations: ["secure connection", "secure account"], wordFamily: ["secure", "security", "securely"], tags: ["technology", "safety"], category: "quality" },
      { word: "subscribe", translation: "suscribirse", pos: "verb", ipa: "/səbˈskraɪb/", definition: "to agree to receive a service or regular updates", example: "You can subscribe to the weekly newsletter.", exampleTranslation: "Puedes suscribirte al boletín semanal.", synonyms: ["sign up", "enrol"], antonyms: ["unsubscribe"], collocations: ["subscribe to a newsletter", "subscribe online"], wordFamily: ["subscribe", "subscriber", "subscription"], tags: ["technology", "communication"], category: "action" },
    ],
  },
  B1: {
    u54: [
      { word: "portfolio", translation: "portafolio", pos: "noun", ipa: "/pɔːrtˈfoʊlioʊ/", definition: "a collection of work that shows someone's skills or experience", example: "She brought a design portfolio to the interview.", exampleTranslation: "Llevó un portafolio de diseño a la entrevista.", synonyms: ["body of work", "collection"], antonyms: [], collocations: ["design portfolio", "professional portfolio"], wordFamily: ["portfolio"], tags: ["work", "education"], category: "career" },
      { word: "vacancy", translation: "puesto vacante", pos: "noun", ipa: "/ˈveɪkənsi/", definition: "a job that is available for someone to fill", example: "The company advertised a vacancy in sales.", exampleTranslation: "La empresa anunció un puesto vacante en ventas.", synonyms: ["opening", "available position"], antonyms: ["appointment"], collocations: ["job vacancy", "fill a vacancy"], wordFamily: ["vacant", "vacancy"], tags: ["work", "jobs"], category: "career" },
    ],
    u55: [
      { word: "clarify", translation: "aclarar", pos: "verb", ipa: "/ˈklærəfaɪ/", definition: "to make an idea or situation easier to understand", example: "Could you clarify the final requirement?", exampleTranslation: "¿Podrías aclarar el último requisito?", synonyms: ["explain", "clear up"], antonyms: ["confuse"], collocations: ["clarify a point", "clarify expectations"], wordFamily: ["clear", "clarify", "clarification"], tags: ["communication", "work"], category: "action" },
      { word: "stakeholder", translation: "parte interesada", pos: "noun", ipa: "/ˈsteɪkhoʊldər/", definition: "a person or group affected by a project or decision", example: "We invited every stakeholder to the planning meeting.", exampleTranslation: "Invitamos a todas las partes interesadas a la reunión de planificación.", synonyms: ["interested party", "participant"], antonyms: [], collocations: ["key stakeholder", "stakeholder interest"], wordFamily: ["stake", "stakeholder"], tags: ["work", "groups"], category: "person" },
    ],
    u56: [
      { word: "milestone", translation: "hito", pos: "noun", ipa: "/ˈmaɪlstoʊn/", definition: "an important stage or event in a process", example: "Finishing the prototype was an important milestone.", exampleTranslation: "Terminar el prototipo fue un hito importante.", synonyms: ["landmark", "turning point"], antonyms: [], collocations: ["major milestone", "reach a milestone"], wordFamily: ["milestone"], tags: ["work", "planning"], category: "progress" },
      { word: "negotiate", translation: "negociar", pos: "verb", ipa: "/nɪˈɡoʊʃieɪt/", definition: "to discuss in order to reach an agreement", example: "The teams negotiated a realistic deadline.", exampleTranslation: "Los equipos negociaron una fecha límite realista.", synonyms: ["bargain", "discuss"], antonyms: ["refuse"], collocations: ["negotiate a contract", "negotiate terms"], wordFamily: ["negotiate", "negotiation", "negotiator"], tags: ["work", "communication"], category: "action" },
      { word: "facilitate", translation: "facilitar", pos: "verb", ipa: "/fəˈsɪlɪteɪt/", definition: "to make an action or process easier", example: "The shared document facilitated collaboration.", exampleTranslation: "El documento compartido facilitó la colaboración.", synonyms: ["enable", "assist"], antonyms: ["hinder", "obstruct"], collocations: ["facilitate discussion", "facilitate learning"], wordFamily: ["facilitate", "facilitation", "facilitator"], tags: ["work", "communication"], category: "action" },
      { word: "efficient", translation: "eficiente", pos: "adjective", ipa: "/ɪˈfɪʃənt/", definition: "working well without wasting time or resources", example: "The new process is more efficient.", exampleTranslation: "El nuevo proceso es más eficiente.", synonyms: ["effective", "productive"], antonyms: ["inefficient", "wasteful"], collocations: ["efficient system", "work efficiently"], wordFamily: ["efficiency", "efficient", "efficiently"], tags: ["work", "quality"], category: "quality" },
    ],
  },
  B2: {
    u54: [
      { word: "inflation", translation: "inflación", pos: "noun", ipa: "/ɪnˈfleɪʃən/", definition: "a general rise in prices that reduces the value of money", example: "High inflation makes everyday goods more expensive.", exampleTranslation: "La inflación alta encarece los productos cotidianos.", synonyms: ["price rise", "rising prices"], antonyms: ["deflation"], collocations: ["high inflation", "control inflation"], wordFamily: ["inflate", "inflation", "inflationary"], tags: ["economy", "money"], category: "economy" },
      { word: "revenue", translation: "ingresos", pos: "noun", ipa: "/ˈrevənuː/", definition: "money received by a business or organisation from its activities", example: "Online sales increased the company's revenue.", exampleTranslation: "Las ventas en línea aumentaron los ingresos de la empresa.", synonyms: ["income", "turnover"], antonyms: ["expenditure"], collocations: ["annual revenue", "generate revenue"], wordFamily: ["revenue"], tags: ["economy", "business"], category: "finance" },
    ],
    u55: [
      { word: "incentive", translation: "incentivo", pos: "noun", ipa: "/ɪnˈsentɪv/", definition: "something that encourages a person to act in a particular way", example: "The discount is an incentive to buy early.", exampleTranslation: "El descuento es un incentivo para comprar pronto.", synonyms: ["motivation", "encouragement"], antonyms: ["deterrent"], collocations: ["financial incentive", "offer an incentive"], wordFamily: ["incentivise", "incentive"], tags: ["economy", "work"], category: "motivation" },
      { word: "compliance", translation: "cumplimiento", pos: "noun", ipa: "/kəmˈplaɪəns/", definition: "the act of following a rule, law, or request", example: "The audit checks compliance with safety regulations.", exampleTranslation: "La auditoría comprueba el cumplimiento de las normas de seguridad.", synonyms: ["obedience", "conformity"], antonyms: ["defiance"], collocations: ["regulatory compliance", "ensure compliance"], wordFamily: ["comply", "compliance", "compliant"], tags: ["law", "business"], category: "policy" },
    ],
    u56: [
      { word: "generalisability", translation: "generalización", pos: "noun", ipa: "/ˌdʒenərəlaɪzəˈbɪləti/", definition: "the extent to which a study's results apply beyond its sample", example: "The diverse sample improves the generalisability of the findings.", exampleTranslation: "La muestra diversa mejora la generalización de los resultados.", synonyms: ["applicability", "transferability"], antonyms: [], collocations: ["limited generalisability", "assess generalisability"], wordFamily: ["generalise", "generalisation", "generalisable"], tags: ["science", "research"], category: "quality" },
      { word: "robustness", translation: "solidez", pos: "noun", ipa: "/ˈroʊbʌstnəs/", definition: "the ability to remain reliable under different conditions", example: "The researchers tested the robustness of the result.", exampleTranslation: "Los investigadores comprobaron la solidez del resultado.", synonyms: ["reliability", "strength"], antonyms: ["fragility"], collocations: ["test robustness", "robustness check"], wordFamily: ["robust", "robustness"], tags: ["science", "thinking"], category: "quality" },
      { word: "dataset", translation: "conjunto de datos", pos: "noun", ipa: "/ˈdeɪtəset/", definition: "a structured collection of information used for analysis", example: "The dataset contains results from three surveys.", exampleTranslation: "El conjunto de datos contiene resultados de tres encuestas.", synonyms: ["data set", "data collection"], antonyms: [], collocations: ["large dataset", "analyse a dataset"], wordFamily: ["data", "dataset"], tags: ["science", "data"], category: "research" },
      { word: "finding", translation: "hallazgo", pos: "noun", ipa: "/ˈfaɪndɪŋ/", definition: "a result or conclusion discovered through research", example: "The main finding was unexpected.", exampleTranslation: "El hallazgo principal fue inesperado.", synonyms: ["result", "discovery"], antonyms: [], collocations: ["key finding", "research finding"], wordFamily: ["find", "finding"], tags: ["science", "research"], category: "result" },
    ],
  },
  C1: {
    u54: [
      { word: "diplomatic", translation: "diplomático", pos: "adjective", ipa: "/ˌdɪpləˈmætɪk/", definition: "connected with relations between countries or careful communication", example: "The minister used diplomatic language during the meeting.", exampleTranslation: "El ministro utilizó un lenguaje diplomático durante la reunión.", synonyms: ["tactful", "international"], antonyms: ["undiplomatic"], collocations: ["diplomatic relations", "diplomatic response"], wordFamily: ["diplomat", "diplomatic", "diplomacy"], tags: ["politics", "communication"], category: "quality" },
      { word: "coalition", translation: "coalición", pos: "noun", ipa: "/ˌkoʊəˈlɪʃən/", definition: "a temporary alliance of people, groups, or countries", example: "Several parties formed a coalition government.", exampleTranslation: "Varios partidos formaron un gobierno de coalición.", synonyms: ["alliance", "partnership"], antonyms: ["opposition"], collocations: ["coalition government", "form a coalition"], wordFamily: ["coalition"], tags: ["politics", "society"], category: "governance" },
    ],
    u55: [
      { word: "questionnaire", translation: "cuestionario", pos: "noun", ipa: "/ˌkwestʃəˈner/", definition: "a written set of questions used to collect information", example: "The researchers sent a questionnaire to every participant.", exampleTranslation: "Los investigadores enviaron un cuestionario a cada participante.", synonyms: ["survey", "form"], antonyms: [], collocations: ["research questionnaire", "complete a questionnaire"], wordFamily: ["question", "questionnaire", "questioning"], tags: ["research", "communication"], category: "research" },
      { word: "reliability", translation: "fiabilidad", pos: "noun", ipa: "/rɪˌlaɪəˈbɪləti/", definition: "the quality of being dependable and consistent", example: "The study discusses the reliability of its measurements.", exampleTranslation: "El estudio analiza la fiabilidad de sus mediciones.", synonyms: ["dependability", "consistency"], antonyms: ["unreliability"], collocations: ["test reliability", "measurement reliability"], wordFamily: ["rely", "reliable", "reliability"], tags: ["research", "quality"], category: "quality" },
    ],
    u56: [
      { word: "verification", translation: "verificación", pos: "noun", ipa: "/ˌverɪfɪˈkeɪʃən/", definition: "the process of checking that information is accurate", example: "The claim requires independent verification.", exampleTranslation: "La afirmación requiere una verificación independiente.", synonyms: ["confirmation", "validation"], antonyms: [], collocations: ["fact verification", "independent verification"], wordFamily: ["verify", "verification"], tags: ["media", "research"], category: "process" },
      { word: "allegation", translation: "acusación", pos: "noun", ipa: "/ˌæləˈɡeɪʃən/", definition: "a claim that someone has done something wrong, not yet proved", example: "The newspaper reported the allegation cautiously.", exampleTranslation: "El periódico informó de la acusación con cautela.", synonyms: ["claim", "accusation"], antonyms: [], collocations: ["serious allegation", "deny an allegation"], wordFamily: ["allege", "allegation"], tags: ["media", "law"], category: "claim" },
      { word: "impartial", translation: "imparcial", pos: "adjective", ipa: "/ɪmˈpɑːrʃəl/", definition: "not supporting one side more than another", example: "A credible report should be accurate and impartial.", exampleTranslation: "Un informe creíble debe ser preciso e imparcial.", synonyms: ["neutral", "unbiased"], antonyms: ["partial", "biased"], collocations: ["impartial analysis", "remain impartial"], wordFamily: ["part", "partial", "impartiality"], tags: ["media", "ethics"], category: "quality" },
      { word: "transparency", translation: "transparencia", pos: "noun", ipa: "/trænsˈperənsi/", definition: "the practice of making processes and information open to inspection", example: "Transparency helps readers evaluate a source.", exampleTranslation: "La transparencia ayuda a los lectores a evaluar una fuente.", synonyms: ["openness", "clarity"], antonyms: ["secrecy", "opacity"], collocations: ["editorial transparency", "greater transparency"], wordFamily: ["transparent", "transparency"], tags: ["media", "ethics"], category: "principle" },
    ],
  },
  C2: {
    u54: [
      { word: "paradox", translation: "paradoja", pos: "noun", ipa: "/ˈpærədɑːks/", definition: "a statement or situation that seems contradictory but may contain a truth", example: "The paradox challenges a simple explanation.", exampleTranslation: "La paradoja desafía una explicación sencilla.", synonyms: ["contradiction", "puzzle"], antonyms: ["consistency"], collocations: ["apparent paradox", "logical paradox"], wordFamily: ["paradox", "paradoxical"], tags: ["philosophy", "thinking"], category: "reasoning" },
      { word: "axiom", translation: "axioma", pos: "noun", ipa: "/ˈæksiəm/", definition: "a principle accepted as true and used as a basis for reasoning", example: "The theory begins with a simple axiom.", exampleTranslation: "La teoría comienza con un axioma sencillo.", synonyms: ["principle", "self-evident truth"], antonyms: ["hypothesis"], collocations: ["fundamental axiom", "accept an axiom"], wordFamily: ["axiom", "axiomatic"], tags: ["philosophy", "logic"], category: "principle" },
    ],
    u55: [
      { word: "incongruity", translation: "incongruencia", pos: "noun", ipa: "/ˌɪnkənˈɡruːəti/", definition: "a lack of harmony or agreement between things", example: "The incongruity between the words and the action was striking.", exampleTranslation: "La incongruencia entre las palabras y la acción era llamativa.", synonyms: ["mismatch", "inconsistency"], antonyms: ["harmony"], collocations: ["striking incongruity", "notice an incongruity"], wordFamily: ["congruent", "incongruity"], tags: ["rhetoric", "thinking"], category: "analysis" },
      { word: "counterargument", translation: "contraargumento", pos: "noun", ipa: "/ˌkaʊntərˈɑːrɡjəmənt/", definition: "an argument made to oppose or challenge another argument", example: "The essay presents a strong counterargument.", exampleTranslation: "El ensayo presenta un contraargumento sólido.", synonyms: ["rebuttal", "objection"], antonyms: ["supporting argument"], collocations: ["address a counterargument", "strong counterargument"], wordFamily: ["argue", "argument", "counterargument"], tags: ["rhetoric", "writing"], category: "argument" },
    ],
    u56: [
      { word: "deixis", translation: "deixis", pos: "noun", ipa: "/ˈdeɪksɪs/", definition: "the use of words whose meaning depends on the situation or speaker", example: "Words such as 'here' and 'now' are examples of deixis.", exampleTranslation: "Palabras como «aquí» y «ahora» son ejemplos de deixis.", synonyms: ["indexical reference", "contextual reference"], antonyms: [], collocations: ["spatial deixis", "temporal deixis"], wordFamily: ["deictic", "deixis"], tags: ["linguistics", "pragmatics"], category: "meaning" },
      { word: "presuppose", translation: "presuponer", pos: "verb", ipa: "/ˌpriːsəˈpoʊz/", definition: "to assume that something is true before it is proved", example: "The argument presupposes that the data is complete.", exampleTranslation: "El argumento presupone que los datos están completos.", synonyms: ["assume", "take for granted"], antonyms: ["question"], collocations: ["presuppose a condition", "presuppose knowledge"], wordFamily: ["presuppose", "presupposition"], tags: ["linguistics", "thinking"], category: "reasoning" },
      { word: "entailment", translation: "implicación lógica", pos: "noun", ipa: "/ɪnˈteɪlmənt/", definition: "a meaning or conclusion that must follow from a statement", example: "The entailment depends on the meaning of the verb.", exampleTranslation: "La implicación lógica depende del significado del verbo.", synonyms: ["implication", "consequence"], antonyms: [], collocations: ["logical entailment", "semantic entailment"], wordFamily: ["entail", "entailment"], tags: ["linguistics", "logic"], category: "meaning" },
      { word: "polysemy", translation: "polisemia", pos: "noun", ipa: "/pəˈlɪsəmi/", definition: "the fact that one word has several related meanings", example: "The polysemy of the word makes the sentence interesting.", exampleTranslation: "La polisemia de la palabra hace interesante la oración.", synonyms: ["multiple meaning", "semantic variation"], antonyms: [], collocations: ["lexical polysemy", "polysemy in language"], wordFamily: ["polysemous", "polysemy"], tags: ["linguistics", "semantics"], category: "meaning" },
    ],
  },
};
