import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/** Reviewed vocabulary for the existing B1/B2/C1 u22 and u23 units. */
export const ENGLISH_B1_B2_C1_U22_U23_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u22: [
      reviewed({ word: "work placement", translation: "تدريب عملي", pos: "noun", ipa: "/wɜːrk ˈpleɪsmənt/", definition: "a period of practical work experience, often arranged for a learner or new employee", example: "Her work placement gave her useful experience in a busy office.", exampleTranslation: "منحها التدريب العملي خبرة مفيدة في مكتب مزدحم.", category: "career and work experience", tags: ["career", "experience"], synonyms: ["work experience placement", "practical placement"] }),
      reviewed({ word: "job description", translation: "وصف وظيفي", pos: "noun", ipa: "/dʒɑːb dɪˈskrɪpʃən/", definition: "a written explanation of the duties and requirements of a job", example: "Read the job description carefully before completing the application.", exampleTranslation: "اقرأ الوصف الوظيفي بعناية قبل إكمال الطلب.", category: "career and work experience", tags: ["jobs", "applications"], synonyms: ["role description", "position specification"] }),
      reviewed({ word: "applicant profile", translation: "ملف المتقدم", pos: "noun", ipa: "/ˈæplɪkənt ˈproʊfaɪl/", definition: "a summary of a person’s skills, experience, and suitability for a job", example: "The recruiter compared each applicant profile with the role requirements.", exampleTranslation: "قارن مسؤول التوظيف كل ملف للمتقدم بمتطلبات الوظيفة.", category: "career and work experience", tags: ["jobs", "recruitment"], synonyms: ["candidate profile", "employment profile"] }),
      reviewed({ word: "employment referee", translation: "مرجع وظيفي", pos: "noun", ipa: "/ɪmˈplɔɪmənt ˌrefəˈriː/", definition: "a person who can provide information about someone’s work ability and character", example: "The employer contacted her employment referee after the interview.", exampleTranslation: "اتصل صاحب العمل بمرجعها الوظيفي بعد المقابلة.", category: "career and work experience", tags: ["jobs", "references"], synonyms: ["professional referee", "work reference contact"] }),
      reviewed({ word: "career development pathway", translation: "مسار التطور المهني", pos: "noun", ipa: "/kəˈrɪər dɪˈveləpmənt ˈpæθweɪ/", definition: "a planned sequence of roles, skills, and learning opportunities in a career", example: "The company offered a career development pathway for new graduates.", exampleTranslation: "قدمت الشركة مسارًا للتطور المهني للخريجين الجدد.", category: "career and work experience", tags: ["career", "development"], synonyms: ["career progression route", "professional growth pathway"] }),
      reviewed({ word: "trial employment period", translation: "فترة عمل تجريبية", pos: "noun", ipa: "/traɪəl ɪmˈplɔɪmənt ˈpɪriəd/", definition: "an initial period in which an employer and employee assess whether a job is suitable", example: "The trial employment period lasted three months.", exampleTranslation: "استمرت فترة العمل التجريبية ثلاثة أشهر.", category: "career and work experience", tags: ["work", "contracts"], synonyms: ["initial employment period", "trial work period"] }),
      reviewed({ word: "shift work", translation: "عمل بنظام الورديات", pos: "noun", ipa: "/ʃɪft wɜːrk/", definition: "a work pattern in which employees work at different times of day or night", example: "Shift work can be difficult when the schedule changes every week.", exampleTranslation: "قد يكون العمل بنظام الورديات صعبًا عندما يتغير الجدول كل أسبوع.", category: "career and work experience", tags: ["work", "schedules"], synonyms: ["rotating shifts", "shift-based work"] }),
      reviewed({ word: "skills portfolio", translation: "ملف المهارات", pos: "noun", ipa: "/skɪlz pɔːrtˈfoʊlioʊ/", definition: "a collection of evidence showing a person’s abilities and achievements", example: "She used a skills portfolio to demonstrate her design experience.", exampleTranslation: "استخدمت ملف مهارات لإظهار خبرتها في التصميم.", category: "career and work experience", tags: ["career", "skills"], synonyms: ["competency portfolio", "achievement portfolio"] }),
    ],
    u23: [
      reviewed({ word: "study grant", translation: "منحة دراسية", pos: "noun", ipa: "/ˈstʌdi ɡrænt/", definition: "money provided to support a learner’s education", example: "The study grant covered part of her travel and course costs.", exampleTranslation: "غطت المنحة الدراسية جزءًا من تكاليف السفر والدورة.", category: "education and learning objectives", tags: ["education", "finance"], synonyms: ["education grant", "learning award"] }),
      reviewed({ word: "coursework task", translation: "مهمة دراسية", pos: "noun", ipa: "/ˈkɔːrswɜːrk tɑːsk/", definition: "a piece of work completed as part of a course", example: "The coursework task required students to compare two learning methods.", exampleTranslation: "تطلبت المهمة الدراسية من الطلاب مقارنة طريقتين للتعلم.", category: "education and learning objectives", tags: ["education", "assessment"], synonyms: ["course assignment", "academic task"] }),
      reviewed({ word: "academic credential", translation: "اعتماد أكاديمي", pos: "noun", ipa: "/ˌækəˈdemɪk krəˈdenʃəl/", definition: "a qualification or official record showing educational achievement", example: "The application asks for evidence of every academic credential.", exampleTranslation: "يطلب الطلب دليلًا على كل اعتماد أكاديمي.", category: "education and learning objectives", tags: ["education", "qualifications"], synonyms: ["educational credential", "academic certificate"] }),
      reviewed({ word: "study adviser", translation: "مرشد دراسي", pos: "noun", ipa: "/ˈstʌdi ədˌvaɪzər/", definition: "a person who helps learners plan courses and make educational decisions", example: "The study adviser helped him choose subjects for the next term.", exampleTranslation: "ساعده المرشد الدراسي على اختيار مواد الفصل المقبل.", category: "education and learning objectives", tags: ["education", "guidance"], synonyms: ["academic adviser", "study counsellor"] }),
      reviewed({ word: "extracurricular activity", translation: "نشاط لا منهجي", pos: "noun", ipa: "/ˌekstrəkəˈrɪkjələr ækˈtɪvəti/", definition: "an activity connected with education but outside the formal course programme", example: "The debate club is a popular extracurricular activity.", exampleTranslation: "نادي المناظرة نشاط لا منهجي شائع.", category: "education and learning objectives", tags: ["education", "activities"], synonyms: ["after-school activity", "out-of-class activity"] }),
      reviewed({ word: "peer assessment", translation: "تقييم الأقران", pos: "noun", ipa: "/pɪr əˈsesmənt/", definition: "the process of learners reviewing and commenting on one another’s work", example: "Peer assessment taught the class to give specific and respectful feedback.", exampleTranslation: "علّم تقييم الأقران الصف تقديم ملاحظات محددة ومحترمة.", category: "education and learning objectives", tags: ["education", "assessment"], synonyms: ["peer review", "student-to-student assessment"] }),
      reviewed({ word: "competency target", translation: "هدف الكفاءة", pos: "noun", ipa: "/ˈkɑːmpɪtənsi ˈtɑːrɡɪt/", definition: "a specific ability that a learner is expected to develop through a course", example: "The teacher linked each activity to a clear competency target.", exampleTranslation: "ربط المعلم كل نشاط بهدف كفاءة واضح.", category: "education and learning objectives", tags: ["education", "planning"], synonyms: ["skill target", "learning goal"] }),
      reviewed({ word: "study workload", translation: "عبء الدراسة", pos: "noun", ipa: "/ˈstʌdi ˌwɜːrkˈloʊd/", definition: "the amount of work a learner is expected to complete", example: "The tutor helped students organise their study workload before the exams.", exampleTranslation: "ساعد المدرس الطلاب على تنظيم عبء الدراسة قبل الامتحانات.", category: "education and learning objectives", tags: ["education", "planning"], synonyms: ["academic workload", "course workload"] }),
    ],
  },
  B2: {
    u22: [
      reviewed({ word: "defendant", translation: "المدعى عليه", pos: "noun", ipa: "/dɪˈfendənt/", definition: "a person or organisation accused of a crime or involved in a legal case", example: "The defendant denied the charge during the hearing.", exampleTranslation: "أنكر المدعى عليه التهمة أثناء الجلسة.", category: "law and justice", tags: ["law", "courts"], synonyms: ["accused person", "respondent"] }),
      reviewed({ word: "prosecution", translation: "الادعاء العام", pos: "noun", ipa: "/ˌprɑːsɪˈkjuːʃən/", definition: "the legal process of bringing a criminal case against someone", example: "The prosecution presented several documents to the court.", exampleTranslation: "قدم الادعاء العام عدة وثائق إلى المحكمة.", category: "law and justice", tags: ["law", "courts"], synonyms: ["criminal proceedings", "state case"] }),
      reviewed({ word: "testimony", translation: "شهادة", pos: "noun", ipa: "/ˈtestəmoʊni/", definition: "a formal statement given by a witness in a legal case", example: "The witness gave testimony about what happened that evening.", exampleTranslation: "قدم الشاهد شهادة عما حدث في ذلك المساء.", category: "law and justice", tags: ["law", "evidence"], synonyms: ["witness statement", "evidence from a witness"] }),
      reviewed({ word: "acquittal", translation: "تبرئة", pos: "noun", ipa: "/əˈkwɪtəl/", definition: "a formal decision that someone is not guilty of a crime", example: "The acquittal ended the case after the evidence was found unreliable.", exampleTranslation: "أنهت التبرئة القضية بعد اعتبار الأدلة غير موثوقة.", category: "law and justice", tags: ["law", "courts"], synonyms: ["not-guilty verdict", "clearing of charges"] }),
      reviewed({ word: "penalty", translation: "عقوبة", pos: "noun", ipa: "/ˈpenəlti/", definition: "a punishment imposed for breaking a law or rule", example: "The law sets a heavy penalty for repeated fraud.", exampleTranslation: "يفرض القانون عقوبة شديدة على الاحتيال المتكرر.", category: "law and justice", tags: ["law", "punishment"], synonyms: ["punishment", "sanction"] }),
      reviewed({ word: "litigation", translation: "تقاضٍ", pos: "noun", ipa: "/ˌlɪtəˈɡeɪʃən/", definition: "the process of resolving a dispute through a court", example: "The company tried mediation before beginning expensive litigation.", exampleTranslation: "جربت الشركة الوساطة قبل بدء تقاضٍ مكلف.", category: "law and justice", tags: ["law", "disputes"], synonyms: ["legal action", "court proceedings"] }),
      reviewed({ word: "case-law principle", translation: "مبدأ من السوابق القضائية", pos: "noun", ipa: "/ˈkeɪs lɔː ˈprɪnsəpəl/", definition: "a legal rule developed through decisions made in earlier court cases", example: "The lawyer argued that a case-law principle supported her client’s claim.", exampleTranslation: "جادل المحامي بأن مبدأً من السوابق القضائية يدعم مطالبة موكلته.", category: "law and justice", tags: ["law", "courts"], synonyms: ["judicial principle", "common-law rule"] }),
      reviewed({ word: "court injunction", translation: "أمر قضائي", pos: "noun", ipa: "/kɔːrt ɪnˈdʒʌŋkʃən/", definition: "an official court order requiring someone to do or stop doing something", example: "The court injunction prevented the company from destroying the records.", exampleTranslation: "منع الأمر القضائي الشركة من إتلاف السجلات.", category: "law and justice", tags: ["law", "courts"], synonyms: ["judicial order", "court order"] }),
    ],
    u23: [
      reviewed({ word: "public petition", translation: "عريضة عامة", pos: "noun", ipa: "/ˈpʌblɪk pəˈtɪʃən/", definition: "a formal request signed by members of the public and sent to an authority", example: "A public petition called for safer streets near the school.", exampleTranslation: "طالبت عريضة عامة بشوارع أكثر أمانًا قرب المدرسة.", category: "change and protest", tags: ["protest", "citizenship"], synonyms: ["community petition", "public appeal"] }),
      reviewed({ word: "policy renewal", translation: "تجديد السياسات", pos: "noun", ipa: "/ˈpɑːləsi rɪˈnuːəl/", definition: "the process of changing a policy so that it responds to new needs", example: "The movement demanded policy renewal rather than a symbolic announcement.", exampleTranslation: "طالبت الحركة بتجديد السياسات بدلًا من إعلان رمزي.", category: "change and protest", tags: ["change", "policy"], synonyms: ["policy reform", "renewal of policy"] }),
      reviewed({ word: "mutual solidarity", translation: "تضامن متبادل", pos: "noun", ipa: "/ˈmjuːtʃuəl ˌsɑːləˈderəti/", definition: "shared support among people or groups facing a common problem", example: "Mutual solidarity helped the workers continue the campaign peacefully.", exampleTranslation: "ساعد التضامن المتبادل العمال على مواصلة الحملة بسلام.", category: "change and protest", tags: ["protest", "community"], synonyms: ["shared solidarity", "collective support"] }),
      reviewed({ word: "boycott", translation: "مقاطعة", pos: "noun", ipa: "/ˈbɔɪkɑːt/", definition: "an organised refusal to buy, use, or deal with something as a form of protest", example: "The boycott pressured the company to publish its environmental report.", exampleTranslation: "ضغطت المقاطعة على الشركة لنشر تقريرها البيئي.", category: "change and protest", tags: ["protest", "consumer action"], synonyms: ["consumer boycott", "refusal to purchase"] }),
      reviewed({ word: "civil disobedience", translation: "عصيان مدني", pos: "noun", ipa: "/ˌsɪvəl ˌdɪsəˈbiːdiəns/", definition: "the peaceful refusal to obey a law that is considered unjust", example: "The group used civil disobedience to draw attention to the unfair rule.", exampleTranslation: "استخدمت المجموعة العصيان المدني للفت الانتباه إلى القاعدة غير العادلة.", category: "change and protest", tags: ["protest", "justice"], synonyms: ["nonviolent resistance", "peaceful law-breaking"] }),
      reviewed({ word: "mobilisation", translation: "تعبئة جماهيرية", pos: "noun", ipa: "/ˌmoʊbələˈzeɪʃən/", definition: "the process of organising people to support a cause or take action", example: "Online mobilisation brought thousands of people to the public meeting.", exampleTranslation: "جلبت التعبئة الجماهيرية عبر الإنترنت آلاف الأشخاص إلى الاجتماع العام.", category: "change and protest", tags: ["protest", "organisation"], synonyms: ["mass organising", "collective mobilisation"] }),
      reviewed({ word: "uprising", translation: "انتفاضة", pos: "noun", ipa: "/ˈʌpraɪzɪŋ/", definition: "an organised or widespread attempt to oppose those in power", example: "The history course examined how the uprising changed the government.", exampleTranslation: "بحثت دورة التاريخ كيف غيرت الانتفاضة الحكومة.", category: "change and protest", tags: ["change", "politics"], synonyms: ["revolt", "popular revolt"] }),
      reviewed({ word: "grassroots campaign", translation: "حملة شعبية قاعدية", pos: "noun", ipa: "/ˈɡræsruːts kæmˈpeɪn/", definition: "a campaign organised by ordinary people rather than by established leaders", example: "A grassroots campaign persuaded the council to protect the local park.", exampleTranslation: "أقنعت حملة شعبية قاعدية المجلس بحماية الحديقة المحلية.", category: "change and protest", tags: ["community", "activism"], synonyms: ["community-led campaign", "bottom-up campaign"] }),
    ],
  },
  C1: {
    u22: [
      reviewed({ word: "rite of passage", translation: "طقس عبور", pos: "noun", ipa: "/raɪt əv ˈpæsɪdʒ/", definition: "a ceremony marking an important stage in a person’s life", example: "The coming-of-age ceremony is an important rite of passage in the community.", exampleTranslation: "يعد احتفال بلوغ سن الرشد طقس عبور مهمًا في المجتمع.", category: "culture and ritual", tags: ["culture", "ceremonies"], synonyms: ["life-stage ceremony", "transition ritual"] }),
      reviewed({ word: "inherited tradition", translation: "تقليد موروث", pos: "noun", ipa: "/ɪnˈherɪtɪd trəˈdɪʃən/", definition: "a custom or belief passed from earlier generations", example: "The festival combines an inherited tradition with new artistic ideas.", exampleTranslation: "يجمع المهرجان بين تقليد موروث وأفكار فنية جديدة.", category: "culture and ritual", tags: ["culture", "traditions"], synonyms: ["ancestral tradition", "handed-down custom"] }),
      reviewed({ word: "cultural assimilation", translation: "استيعاب ثقافي", pos: "noun", ipa: "/ˈkʌltʃərəl əˌsɪməˈleɪʃən/", definition: "the process by which a group gradually adopts the culture of another group", example: "The novel questions whether cultural assimilation always leads to belonging.", exampleTranslation: "تتساءل الرواية عما إذا كان الاستيعاب الثقافي يؤدي دائمًا إلى الانتماء.", category: "culture and ritual", tags: ["culture", "identity"], synonyms: ["cultural absorption", "cultural convergence"] }),
      reviewed({ word: "ethnocentrism", translation: "التمركز العرقي", pos: "noun", ipa: "/ˌeθnoʊˈsentrɪzəm/", definition: "the belief that one’s own culture is the normal or superior standard", example: "Ethnocentrism can prevent researchers from understanding unfamiliar rituals fairly.", exampleTranslation: "يمكن للتمركز العرقي أن يمنع الباحثين من فهم الطقوس غير المألوفة بإنصاف.", category: "culture and ritual", tags: ["culture", "society"], synonyms: ["cultural superiority", "culture-centred judgement"] }),
      reviewed({ word: "folklore", translation: "الفولكلور والتراث الشعبي", pos: "noun", ipa: "/ˈfoʊklɔːr/", definition: "the traditional stories, beliefs, and customs of a community", example: "Local folklore explains why the river is considered sacred.", exampleTranslation: "يفسر التراث الشعبي المحلي سبب اعتبار النهر مقدسًا.", category: "culture and ritual", tags: ["culture", "stories"], synonyms: ["traditional lore", "folk tradition"] }),
      reviewed({ word: "social taboo", translation: "محرّم اجتماعيًا", pos: "noun", ipa: "/ˈsoʊʃəl təˈbuː/", definition: "a behaviour or subject that a society strongly discourages people from discussing or doing", example: "The documentary explores how a social taboo changes across generations.", exampleTranslation: "يستكشف الفيلم الوثائقي كيف يتغير المحرّم الاجتماعي عبر الأجيال.", category: "culture and ritual", tags: ["culture", "society"], synonyms: ["cultural prohibition", "social prohibition"] }),
      reviewed({ word: "secularisation", translation: "علمنة", pos: "noun", ipa: "/ˌsekjələrəˈzeɪʃən/", definition: "the process by which religion becomes less central to public and social life", example: "Secularisation changed the role of the ceremony in public institutions.", exampleTranslation: "غيرت العلمنة دور الاحتفال في المؤسسات العامة.", category: "culture and ritual", tags: ["culture", "society"], synonyms: ["secular transformation", "decline of religious influence"] }),
      reviewed({ word: "commemoration", translation: "إحياء ذكرى", pos: "noun", ipa: "/kəˌmeməˈreɪʃən/", definition: "an event or action that honours the memory of a person or historical event", example: "The annual commemoration brings different generations together.", exampleTranslation: "يجمع إحياء الذكرى السنوي أجيالًا مختلفة.", category: "culture and ritual", tags: ["culture", "history"], synonyms: ["memorial ceremony", "remembrance event"] }),
    ],
    u23: [
      reviewed({ word: "grammatical morpheme", translation: "مورفيم نحوي", pos: "noun", ipa: "/ɡrəˈmætɪkəl ˈmɔːrfiːm/", definition: "a smallest meaningful language unit that expresses a grammatical function", example: "The plural ending is a grammatical morpheme in this example.", exampleTranslation: "تمثل نهاية الجمع مورفيمًا نحويًا في هذا المثال.", category: "phonology and morphology", tags: ["morphology", "grammar"], synonyms: ["grammatical unit", "functional morpheme"] }),
      reviewed({ word: "phonetic variant", translation: "متغير صوتي", pos: "noun", ipa: "/fəˈnetɪk ˈveriənt/", definition: "a different pronunciation of a sound that does not change a word’s meaning", example: "The speaker’s phonetic variant reflects the pronunciation of the region.", exampleTranslation: "يعكس المتغير الصوتي لدى المتحدث نطق المنطقة.", category: "phonology and morphology", tags: ["phonology", "pronunciation"], synonyms: ["sound variant", "pronunciation variant"] }),
      reviewed({ word: "affixation", translation: "الإلصاق الصرفي", pos: "noun", ipa: "/ˌæfɪkˈseɪʃən/", definition: "the process of adding a prefix or suffix to a word or root", example: "Affixation creates new words and can change their grammatical category.", exampleTranslation: "ينشئ الإلصاق الصرفي كلمات جديدة ويمكن أن يغير فئتها النحوية.", category: "phonology and morphology", tags: ["morphology", "word formation"], synonyms: ["adding an affix", "affix formation"] }),
      reviewed({ word: "intonation", translation: "تنغيم", pos: "noun", ipa: "/ˌɪntəˈneɪʃən/", definition: "the rise and fall of the voice while speaking", example: "A change in intonation can turn a statement into a question.", exampleTranslation: "يمكن لتغير التنغيم أن يحول الجملة الخبرية إلى سؤال.", category: "phonology and morphology", tags: ["phonology", "speech"], synonyms: ["speech melody", "voice contour"] }),
      reviewed({ word: "inflection", translation: "تصريف صرفي", pos: "noun", ipa: "/ɪnˈflekʃən/", definition: "a change in the form of a word to show tense, number, case, or another grammatical feature", example: "The inflection of the verb shows that the action happened in the past.", exampleTranslation: "يوضح التصريف الصرفي للفعل أن الحدث وقع في الماضي.", category: "phonology and morphology", tags: ["morphology", "grammar"], synonyms: ["grammatical modification", "word inflection"] }),
      reviewed({ word: "syllable structure", translation: "بنية المقطع", pos: "noun", ipa: "/ˈsɪləbəl ˈstrʌktʃər/", definition: "the arrangement of consonants and vowels within a syllable", example: "The language has a simple syllable structure with few final consonants.", exampleTranslation: "تتميز اللغة ببنية مقطع بسيطة مع عدد قليل من الصوامت النهائية.", category: "phonology and morphology", tags: ["phonology", "syllables"], synonyms: ["syllabic pattern", "syllable pattern"] }),
      reviewed({ word: "phonemic contrast", translation: "تقابل فونيمي", pos: "noun", ipa: "/foʊˈniːmɪk ˈkɑːntræst/", definition: "a difference between sounds that can distinguish one word from another", example: "The pair demonstrates a phonemic contrast between two vowel sounds.", exampleTranslation: "يوضح الزوج تقابلًا فونيميًا بين صوتي علة.", category: "phonology and morphology", tags: ["phonology", "sounds"], synonyms: ["sound contrast", "phonological contrast"] }),
      reviewed({ word: "derivational morphology", translation: "الصرف الاشتقاقي", pos: "noun", ipa: "/ˌderəˈveɪʃənəl mɔːrˈfɑːlədʒi/", definition: "the study of how affixes create new words or change word classes", example: "Derivational morphology explains how a noun becomes an adjective.", exampleTranslation: "يشرح الصرف الاشتقاقي كيف يتحول الاسم إلى صفة.", category: "phonology and morphology", tags: ["morphology", "word formation"], synonyms: ["word-forming morphology", "derivation system"] }),
    ],
  },
};
