// Professional English enrichment units u50-u51 for every CEFR level.
// English-only continuation; Finnish curriculum files are intentionally untouched.
import type { ReadingText, VocabularyItem } from "./learn-data";

type PhraseSpec = { phrase: string; translation: string };
type LineSpec = { speaker: string; text: string; translation: string };
type UnitSeed = { id: string; title: string; description: string; words: VocabularyItem[]; phrases: PhraseSpec[]; dialogue: LineSpec[]; reading: ReadingText & { title: string } };

const w = (word: string, translation: string, pos: string, ipa: string, definition: string, example: string, exampleTranslation: string, synonyms: string[], antonyms: string[], collocations: string[], wordFamily: string[], tags: string[], category: string): VocabularyItem => ({ word, translation, pos, ipa, definition, example, exampleTranslation, synonyms, antonyms, collocations, wordFamily, tags, category });
const u = (id: string, title: string, description: string, words: VocabularyItem[], phrases: PhraseSpec[], dialogue: LineSpec[], reading: ReadingText & { title: string }): UnitSeed => ({ id, title, description, words, phrases, dialogue, reading });

export const ADDITIONAL_EN_PART14_UNITS: Record<string, UnitSeed[]> = {
  A0: [
    u("u50", "Kitchen Things", "Name simple kitchen objects and describe where they are.", [
      w("bowl", "cuenco", "noun", "/boʊl/", "a round container used for food", "The bowl is on the table.", "El cuenco está sobre la mesa.", ["dish", "basin"], [], ["mixing bowl", "bowl of soup"], ["bowl, bowlful"], ["home", "food"], "kitchen object"),
      w("fork", "tenedor", "noun", "/fɔːrk/", "a tool with points used for eating", "I use a fork for the salad.", "Uso un tenedor para la ensalada.", ["table fork", "utensil"], [], ["use a fork", "fork and knife"], ["fork, forked"], ["home", "food"], "kitchen object"),
      w("spoon", "cuchara", "noun", "/spuːn/", "a tool with a small round part used for eating or serving", "The spoon is beside the bowl.", "La cuchara está junto al cuenco.", ["utensil", "ladle"], [], ["wooden spoon", "spoonful of sugar"], ["spoon, spoonful"], ["home", "food"], "kitchen object"),
      w("napkin", "servilleta", "noun", "/ˈnæpkɪn/", "a small piece of cloth or paper used while eating", "Please put a napkin next to my plate.", "Pon una servilleta junto a mi plato, por favor.", ["serviette", "tissue"], [], ["paper napkin", "fold a napkin"], ["napkin"], ["home", "food"], "kitchen object"),
      w("soap", "jabón", "noun", "/soʊp/", "a substance used with water to clean things", "There is soap by the sink.", "Hay jabón junto al fregadero.", ["cleanser", "detergent"], [], ["bar of soap", "wash with soap"], ["soap, soapy"], ["home", "cleaning"], "household item"),
      w("towel", "toalla", "noun", "/ˈtaʊəl/", "a piece of cloth used for drying", "The towel is hanging in the kitchen.", "La toalla está colgada en la cocina.", ["cloth", "drying cloth"], [], ["clean towel", "dry with a towel"], ["towel, towelling"], ["home", "cleaning"], "household item"),
      w("pour", "verter", "verb", "/pɔːr/", "to make liquid flow from one container into another", "Pour the water into the bowl.", "Vierte el agua en el cuenco.", ["tip", "empty"], ["spill"], ["pour water", "pour a drink"], ["pour, pouring"], ["home", "food"], "kitchen action"),
      w("rinse", "enjuagar", "verb", "/rɪns/", "to clean something quickly with clean water", "Rinse the spoon after lunch.", "Enjuaga la cuchara después del almuerzo.", ["flush", "wash"], ["soil"], ["rinse the dishes", "rinse with water"], ["rinse, rinsed, rinsing"], ["home", "cleaning"], "cleaning action"),
    ], [{ phrase: "Where is the spoon?", translation: "¿Dónde está la cuchara?" }, { phrase: "Pour the water slowly.", translation: "Vierte el agua despacio." }, { phrase: "Wash your hands.", translation: "Lávate las manos." }, { phrase: "Use a clean napkin.", translation: "Usa una servilleta limpia." }], [{ speaker: "A", text: "Can I have a spoon?", translation: "¿Puedo tomar una cuchara?" }, { speaker: "B", text: "It is beside the bowl.", translation: "Está junto al cuenco." }, { speaker: "A", text: "Where is the soap?", translation: "¿Dónde está el jabón?" }, { speaker: "B", text: "It is by the sink.", translation: "Está junto al fregadero." }], { title: "Setting the Table", text: "A bowl, a fork, and a spoon are on the table. There is a napkin beside each place. After eating, people wash the dishes and dry them with a towel.", translation: "Hay un cuenco, un tenedor y una cuchara sobre la mesa. Hay una servilleta junto a cada lugar. Después de comer, las personas lavan los platos y los secan con una toalla." }),
    u("u51", "Pets", "Talk about small animals and simple ways to care for them.", [
      w("puppy", "cachorro", "noun", "/ˈpʌpi/", "a young dog", "The puppy sleeps in a small bed.", "El cachorro duerme en una cama pequeña.", ["young dog", "pup"], [], ["play with a puppy", "feed a puppy"], ["pup, puppy"], ["animals", "home"], "pet"),
      w("kitten", "gatito", "noun", "/ˈkɪtn/", "a young cat", "The kitten is hiding under the chair.", "El gatito se esconde debajo de la silla.", ["young cat", "kit"], [], ["play with a kitten", "small kitten"], ["kitten, kitty"], ["animals", "home"], "pet"),
      w("leash", "correa", "noun", "/liːʃ/", "a strap used to control an animal while walking", "The dog has a red leash.", "El perro tiene una correa roja.", ["lead", "strap"], [], ["dog leash", "hold a leash"], ["leash, unleashed"], ["animals", "walking"], "pet item"),
      w("cage", "jaula", "noun", "/keɪdʒ/", "a structure with bars for keeping an animal inside", "The bird has a clean cage.", "El pájaro tiene una jaula limpia.", ["enclosure", "pen"], [], ["bird cage", "clean a cage"], ["cage, caged"], ["animals", "home"], "pet item"),
      w("tail", "cola", "noun", "/teɪl/", "the part that extends from the back of an animal", "The puppy has a short tail.", "El cachorro tiene una cola corta.", ["rear", "appendage"], [], ["wag a tail", "long tail"], ["tail, tailed"], ["animals", "body"], "animal body"),
      w("paw", "pata", "noun", "/pɔː/", "the foot of an animal with claws or soft toes", "The kitten lifted its paw.", "El gatito levantó la pata.", ["foot", "claw"], [], ["animal paw", "dirty paws"], ["paw, pawed"], ["animals", "body"], "animal body"),
      w("brush", "cepillar", "verb", "/brʌʃ/", "to clean or smooth with a brush", "I brush the puppy's coat.", "Cepillo el pelo del cachorro.", ["groom", "comb"], ["tangle"], ["brush a pet", "brush the coat"], ["brush, brushed, brushing"], ["animals", "care"], "care action"),
      w("gentle", "suave", "adjective", "/ˈdʒentəl/", "kind and careful rather than rough", "Be gentle with the kitten.", "Sé suave con el gatito.", ["mild", "tender"], ["rough"], ["gentle touch", "be gentle"], ["gentle, gently, gentleness"], ["animals", "care"], "quality"),
    ], [{ phrase: "Be gentle with the kitten.", translation: "Sé suave con el gatito." }, { phrase: "Hold the leash carefully.", translation: "Sujeta la correa con cuidado." }, { phrase: "The puppy has a short tail.", translation: "El cachorro tiene una cola corta." }, { phrase: "Clean the bird cage.", translation: "Limpia la jaula del pájaro." }], [{ speaker: "A", text: "Can I walk the puppy?", translation: "¿Puedo pasear al cachorro?" }, { speaker: "B", text: "Yes, but hold the leash.", translation: "Sí, pero sujeta la correa." }, { speaker: "A", text: "What does the kitten need?", translation: "¿Qué necesita el gatito?" }, { speaker: "B", text: "A quiet bed and gentle care.", translation: "Una cama tranquila y cuidados suaves." }], { title: "Caring for a Pet", text: "A pet needs food, water, and care. A puppy may need a leash for a walk, while a kitten needs a quiet place to sleep. People should be gentle and keep a cage or bed clean.", translation: "Una mascota necesita comida, agua y cuidados. Un cachorro puede necesitar una correa para pasear, mientras que un gatito necesita un lugar tranquilo para dormir. Las personas deben ser suaves y mantener limpia una jaula o una cama." }),
  ],
  A1: [
    u("u50", "City Services", "Ask for help and find everyday services in a town.", [
      w("bakery", "panadería", "noun", "/ˈbeɪkəri/", "a shop that makes and sells bread and cakes", "The bakery opens early.", "La panadería abre temprano.", ["bakehouse", "bread shop"], [], ["local bakery", "visit a bakery"], ["bake, baker, bakery"], ["city", "food"], "service"),
      w("pharmacy", "farmacia", "noun", "/ˈfɑːrməsi/", "a shop where medicines are prepared and sold", "The pharmacy is next to the clinic.", "La farmacia está junto a la clínica.", ["chemist", "drugstore"], [], ["local pharmacy", "pharmacy counter"], ["pharmacist, pharmacy"], ["city", "health"], "service"),
      w("museum", "museo", "noun", "/mjuːˈziːəm/", "a building where objects of artistic or historical interest are displayed", "The museum is free on Sundays.", "El museo es gratis los domingos.", ["gallery", "collection"], [], ["visit a museum", "museum entrance"], ["museum, museumgoer"], ["city", "culture"], "place"),
      w("theatre", "teatro", "noun", "/ˈθiːətər/", "a building where plays and performances are shown", "We are going to the theatre tonight.", "Vamos al teatro esta noche.", ["playhouse", "stage"], [], ["theatre show", "go to the theatre"], ["theatre, theatrical"], ["city", "culture"], "place"),
      w("sidewalk", "acera", "noun", "/ˈsaɪdwɔːk/", "a path beside a road for people walking", "Please stay on the sidewalk.", "Quédate en la acera, por favor.", ["pavement", "footpath"], [], ["walk on the sidewalk", "wide sidewalk"], ["sidewalk"], ["city", "safety"], "street"),
      w("crosswalk", "paso de peatones", "noun", "/ˈkrɔːswɔːk/", "a marked place where people can cross a road", "Use the crosswalk to cross the street.", "Usa el paso de peatones para cruzar la calle.", ["pedestrian crossing", "zebra crossing"], [], ["crosswalk sign", "use a crosswalk"], ["cross, crosswalk"], ["city", "safety"], "street"),
      w("traffic light", "semáforo", "noun", "/ˈtræfɪk laɪt/", "a light that controls traffic at a road junction", "The traffic light is red.", "El semáforo está en rojo.", ["signal", "stoplight"], [], ["red traffic light", "wait at a traffic light"], ["traffic, light"], ["city", "transport"], "street"),
      w("ask", "preguntar", "verb", "/æsk/", "to say something in order to get information", "Ask the pharmacist for help.", "Pide ayuda al farmacéutico.", ["question", "inquire"], ["answer"], ["ask for help", "ask a question"], ["ask, asking"], ["city", "communication"], "communication action"),
    ], [{ phrase: "Where is the pharmacy?", translation: "¿Dónde está la farmacia?" }, { phrase: "Use the crosswalk.", translation: "Usa el paso de peatones." }, { phrase: "The museum is near the theatre.", translation: "El museo está cerca del teatro." }, { phrase: "Ask for help.", translation: "Pide ayuda." }], [{ speaker: "A", text: "Excuse me, where is the pharmacy?", translation: "Disculpe, ¿dónde está la farmacia?" }, { speaker: "B", text: "It is across from the museum.", translation: "Está enfrente del museo." }, { speaker: "A", text: "How do I cross the road?", translation: "¿Cómo cruzo la carretera?" }, { speaker: "B", text: "Use the crosswalk by the traffic light.", translation: "Usa el paso de peatones junto al semáforo." }], { title: "Finding a Service", text: "A town has many useful services. People may visit a bakery, pharmacy, museum, or theatre. They walk on the sidewalk, wait at a traffic light, and use a crosswalk to cross safely.", translation: "Una ciudad tiene muchos servicios útiles. Las personas pueden visitar una panadería, farmacia, museo o teatro. Caminan por la acera, esperan en un semáforo y usan un paso de peatones para cruzar con seguridad." }),
    u("u51", "Outdoor Plans", "Make simple plans for free time and invite another person.", [
      w("picnic", "picnic", "noun", "/ˈpɪknɪk/", "a meal eaten outdoors, often on a blanket", "We are having a picnic in the park.", "Vamos a hacer un picnic en el parque.", ["outdoor meal", "al fresco meal"], [], ["have a picnic", "picnic blanket"], ["picnic, picnicker"], ["free time", "food"], "activity"),
      w("hiking", "senderismo", "noun", "/ˈhaɪkɪŋ/", "the activity of taking long walks in the countryside", "Hiking is good exercise.", "El senderismo es un buen ejercicio.", ["walking", "trekking"], ["rest"], ["go hiking", "hiking trail"], ["hike, hiker, hiking"], ["free time", "nature"], "activity"),
      w("concert", "concierto", "noun", "/ˈkɑːnsərt/", "a public performance of music", "The concert starts at eight.", "El concierto empieza a las ocho.", ["performance", "gig"], [], ["attend a concert", "live concert"], ["concert, concertgoer"], ["free time", "music"], "event"),
      w("invite", "invitar", "verb", "/ɪnˈvaɪt/", "to ask someone to come to an event or place", "I will invite my neighbour to the picnic.", "Invitaré a mi vecino al picnic.", ["ask", "welcome"], ["exclude"], ["invite a friend", "invite someone over"], ["invite, invitation, inviting"], ["free time", "relationships"], "social action"),
      w("gather", "reunirse", "verb", "/ˈɡæðər/", "to come together in one place", "Friends gather for a picnic.", "Los amigos se reúnen para un picnic.", ["meet", "assemble"], ["scatter"], ["gather together", "gather in a park"], ["gather, gathering"], ["free time", "relationships"], "social action"),
      w("sunshine", "luz del sol", "noun", "/ˈsʌnʃaɪn/", "bright light from the sun", "The sunshine makes the afternoon warm.", "La luz del sol hace cálida la tarde.", ["sunlight", "daylight"], ["darkness"], ["bright sunshine", "enjoy the sunshine"], ["sun, sunny, sunshine"], ["free time", "weather"], "nature"),
      w("trail", "sendero", "noun", "/treɪl/", "a path through the countryside or a place", "The trail leads to a small lake.", "El sendero lleva a un lago pequeño.", ["path", "track"], [], ["hiking trail", "follow a trail"], ["trail, trailer"], ["free time", "nature"], "place"),
      w("bring", "llevar", "verb", "/brɪŋ/", "to take something with you to a place", "Please bring a blanket to the picnic.", "Trae una manta al picnic, por favor.", ["take", "carry"], ["leave"], ["bring food", "bring a blanket"], ["bring, brought, bringing"], ["free time", "planning"], "movement action"),
    ], [{ phrase: "Would you like to join us?", translation: "¿Te gustaría unirte a nosotros?" }, { phrase: "Bring a blanket.", translation: "Trae una manta." }, { phrase: "The trail leads to the lake.", translation: "El sendero lleva al lago." }, { phrase: "The concert starts at eight.", translation: "El concierto empieza a las ocho." }], [{ speaker: "A", text: "Would you like to join our picnic?", translation: "¿Te gustaría unirte a nuestro picnic?" }, { speaker: "B", text: "Yes. What should I bring?", translation: "Sí. ¿Qué debo llevar?" }, { speaker: "A", text: "Bring a blanket and some fruit.", translation: "Trae una manta y algo de fruta." }, { speaker: "B", text: "Great. I can invite Sam too.", translation: "Genial. También puedo invitar a Sam." }], { title: "A Weekend Invitation", text: "On Saturday, friends plan a picnic near a hiking trail. One person brings food and another brings a blanket. On Sunday, they may attend a concert if the sunshine continues.", translation: "El sábado, unos amigos planean un picnic cerca de un sendero. Una persona lleva comida y otra lleva una manta. El domingo pueden asistir a un concierto si continúa la luz del sol." }),
  ],
  A2: [
    u("u50", "Digital Messages", "Write clearer messages and manage everyday online communication.", [
      w("attachment", "archivo adjunto", "noun", "/əˈtætʃmənt/", "a file sent together with an email or message", "I forgot to add the attachment.", "Olvidé añadir el archivo adjunto.", ["enclosure", "file"], [], ["email attachment", "open an attachment"], ["attach, attachment"], ["technology", "communication"], "digital communication"),
      w("browser", "navegador", "noun", "/ˈbraʊzər/", "a computer program used to view websites", "Open the page in your browser.", "Abre la página en tu navegador.", ["web browser", "internet app"], [], ["web browser", "browser window"], ["browse, browser, browsing"], ["technology", "internet"], "software"),
      w("notification", "notificación", "noun", "/ˌnoʊtɪfɪˈkeɪʃən/", "a message that tells you something has happened", "I received a notification about the meeting.", "Recibí una notificación sobre la reunión.", ["alert", "message"], ["silence"], ["push notification", "receive a notification"], ["notify, notification"], ["technology", "communication"], "digital communication"),
      w("recipient", "destinatario", "noun", "/rɪˈsɪpiənt/", "a person who receives something", "Check the recipient before sending the email.", "Comprueba el destinatario antes de enviar el correo.", ["receiver", "addressee"], ["sender"], ["email recipient", "intended recipient"], ["receive, recipient, reception"], ["technology", "communication"], "person"),
      w("draft", "borrador", "noun", "/dræft/", "a first version of a piece of writing", "I saved the message as a draft.", "Guardé el mensaje como borrador.", ["outline", "rough copy"], ["final version"], ["save a draft", "draft message"], ["draft, drafted, drafting"], ["technology", "writing"], "writing"),
      w("forward", "reenviar", "verb", "/ˈfɔːrwərd/", "to send a message received to another person", "Please forward the information to the team.", "Reenvía la información al equipo, por favor.", ["send on", "pass on"], ["withhold"], ["forward an email", "forward a message"], ["forward, forwarded"], ["technology", "communication"], "digital action"),
      w("subscribe", "suscribirse", "verb", "/səbˈskraɪb/", "to agree to receive a service or regular content", "I subscribe to a weekly science newsletter.", "Estoy suscrito a un boletín científico semanal.", ["enrol", "sign up"], ["unsubscribe"], ["subscribe to a service", "subscribe online"], ["subscribe, subscription, subscriber"], ["technology", "media"], "digital action"),
      w("delete", "borrar", "verb", "/dɪˈliːt/", "to remove information from a computer or account", "Delete the old message after checking it.", "Borra el mensaje antiguo después de comprobarlo.", ["remove", "erase"], ["save"], ["delete a file", "delete an account"], ["delete, deletion"], ["technology", "privacy"], "digital action"),
    ], [{ phrase: "Please check the attachment.", translation: "Comprueba el archivo adjunto, por favor." }, { phrase: "I saved it as a draft.", translation: "Lo guardé como borrador." }, { phrase: "Forward this to the recipient.", translation: "Reenvía esto al destinatario." }, { phrase: "Turn off the notification.", translation: "Desactiva la notificación." }], [{ speaker: "A", text: "Did you receive my email?", translation: "¿Recibiste mi correo?" }, { speaker: "B", text: "Yes, but the attachment was missing.", translation: "Sí, pero faltaba el archivo adjunto." }, { speaker: "A", text: "I will forward it again.", translation: "Lo reenviaré." }, { speaker: "B", text: "Thanks. I will check it in my browser.", translation: "Gracias. Lo comprobaré en mi navegador." }], { title: "A Clear Email", text: "Before sending a digital message, check the recipient, subject, and attachment. A draft can be edited, while an old notification can be deleted. Useful messages may be forwarded or shared through a subscription service.", translation: "Antes de enviar un mensaje digital, comprueba el destinatario, el asunto y el archivo adjunto. Un borrador se puede editar, mientras que una notificación antigua se puede borrar. Los mensajes útiles se pueden reenviar o compartir mediante un servicio de suscripción." }),
    u("u51", "Cooking Methods", "Describe basic cooking methods and give practical instructions.", [
      w("marinate", "marinar", "verb", "/ˈmærəneɪt/", "to leave food in a seasoned liquid before cooking", "Marinate the vegetables for an hour.", "Marina las verduras durante una hora.", ["season", "soak"], ["dry"], ["marinate meat", "marinate overnight"], ["marinate, marinade"], ["food", "cooking"], "cooking action"),
      w("stir", "remover", "verb", "/stɜːr/", "to move a liquid or mixture around with a spoon", "Stir the soup gently.", "Remueve la sopa suavemente.", ["mix", "agitate"], ["leave still"], ["stir the sauce", "stir gently"], ["stir, stirring"], ["food", "cooking"], "cooking action"),
      w("grill", "asar a la parrilla", "verb", "/ɡrɪl/", "to cook food under or over direct heat", "Grill the peppers until they are soft.", "Asa los pimientos hasta que estén blandos.", ["barbecue", "broil"], ["freeze"], ["grill vegetables", "grill over heat"], ["grill, grilled, grilling"], ["food", "cooking"], "cooking action"),
      w("peel", "pelar", "verb", "/piːl/", "to remove the outer skin from fruit or vegetables", "Peel the potatoes before boiling them.", "Pela las patatas antes de hervirlas.", ["skin", "pare"], ["cover"], ["peel a potato", "peel the fruit"], ["peel, peeler, peeled"], ["food", "cooking"], "cooking action"),
      w("season", "condimentar", "verb", "/ˈsiːzən/", "to add salt, herbs, or spices to food", "Season the soup with a little salt.", "Condimenta la sopa con un poco de sal.", ["flavour", "spice"], ["bland"], ["season a dish", "season to taste"], ["season, seasoning"], ["food", "cooking"], "cooking action"),
      w("simmer", "cocer a fuego lento", "verb", "/ˈsɪmər/", "to cook gently in liquid just below boiling point", "Let the sauce simmer for ten minutes.", "Deja que la salsa cueza a fuego lento diez minutos.", ["cook gently", "stew"], ["boil rapidly"], ["simmer the sauce", "simmer gently"], ["simmer, simmering"], ["food", "cooking"], "cooking action"),
      w("texture", "textura", "noun", "/ˈtekstʃər/", "the way food feels in the mouth", "The soup has a smooth texture.", "La sopa tiene una textura suave.", ["consistency", "feel"], [], ["smooth texture", "crisp texture"], ["textural, texture"], ["food", "senses"], "food quality"),
      w("portion", "porción", "noun", "/ˈpɔːrʃən/", "an amount of food served to one person", "The restaurant serves a large portion.", "El restaurante sirve una porción grande.", ["serving", "helping"], [], ["small portion", "portion size"], ["portion, portioned"], ["food", "health"], "food quantity"),
    ], [{ phrase: "Season the soup to taste.", translation: "Condimenta la sopa al gusto." }, { phrase: "Let the sauce simmer.", translation: "Deja que la salsa cueza a fuego lento." }, { phrase: "Peel the potatoes first.", translation: "Pela primero las patatas." }, { phrase: "The portion is large.", translation: "La porción es grande." }], [{ speaker: "A", text: "How should I prepare the vegetables?", translation: "¿Cómo debo preparar las verduras?" }, { speaker: "B", text: "Peel them, then marinate and grill them.", translation: "Pélalas, después marínalas y ásalas." }, { speaker: "A", text: "What about the sauce?", translation: "¿Y la salsa?" }, { speaker: "B", text: "Stir it and let it simmer gently.", translation: "Remuévela y deja que cueza suavemente." }], { title: "Following a Recipe", text: "Good cooking depends on method and timing. Food can be marinated, peeled, seasoned, grilled, or simmered. A cook also considers texture and portion size when preparing a meal.", translation: "Una buena cocina depende del método y del tiempo. La comida se puede marinar, pelar, condimentar, asar o cocer a fuego lento. Un cocinero también tiene en cuenta la textura y el tamaño de la porción al preparar una comida." }),
  ],
  B1: [
    u("u50", "Community Decisions", "Discuss local decisions, participation, and practical improvements.", [
      w("petition", "petición", "noun", "/pəˈtɪʃən/", "a formal written request signed by many people", "Residents started a petition for a safer crossing.", "Los residentes iniciaron una petición para un cruce más seguro.", ["appeal", "request"], [], ["sign a petition", "online petition"], ["petition, petitioner"], ["community", "government"], "civic action"),
      w("council", "ayuntamiento", "noun", "/ˈkaʊnsəl/", "a group that manages a town or local area", "The council approved the new park.", "El ayuntamiento aprobó el nuevo parque.", ["local authority", "committee"], [], ["local council", "council meeting"], ["council, councillor"], ["community", "government"], "institution"),
      w("resident", "residente", "noun", "/ˈrezɪdənt/", "a person who lives in a particular place", "Every resident could attend the meeting.", "Cada residente podía asistir a la reunión.", ["inhabitant", "local"], ["visitor"], ["local resident", "residents' group"], ["reside, resident, residential"], ["community", "people"], "person"),
      w("amenity", "servicio público", "noun", "/əˈmiːnəti/", "a useful feature or service provided for people", "The new library is an important amenity.", "La nueva biblioteca es un servicio público importante.", ["facility", "service"], ["inconvenience"], ["public amenity", "local amenities"], ["amenity, amenities"], ["community", "city"], "community service"),
      w("consultation", "consulta", "noun", "/ˌkɑːnsəlˈteɪʃən/", "a process of asking people for their views", "The council held a public consultation.", "El ayuntamiento celebró una consulta pública.", ["discussion", "hearing"], ["exclusion"], ["public consultation", "consultation process"], ["consult, consultation, consultant"], ["community", "government"], "civic process"),
      w("mobilise", "movilizar", "verb", "/ˈmoʊbəlaɪz/", "to organise people to take action", "The campaign mobilised volunteers.", "La campaña movilizó a voluntarios.", ["organise", "activate"], ["demobilise"], ["mobilise support", "mobilise volunteers"], ["mobile, mobilise, mobilisation"], ["community", "activism"], "social action"),
      w("advocate", "defender", "noun", "/ˈædvəkeɪt/", "a person who publicly supports a cause or policy", "She is an advocate for accessible transport.", "Ella es defensora del transporte accesible.", ["supporter", "campaigner"], ["opponent"], ["human rights advocate", "advocate for change"], ["advocate, advocacy"], ["community", "rights"], "person"),
      w("feasible", "viable", "adjective", "/ˈfiːzəbəl/", "possible and practical to achieve", "The council needs a feasible plan.", "El ayuntamiento necesita un plan viable.", ["practical", "workable"], ["impossible"], ["feasible option", "financially feasible"], ["feasibility, feasible"], ["community", "planning"], "quality"),
    ], [{ phrase: "Residents signed a petition.", translation: "Los residentes firmaron una petición." }, { phrase: "The council held a consultation.", translation: "El ayuntamiento celebró una consulta." }, { phrase: "We need a feasible plan.", translation: "Necesitamos un plan viable." }, { phrase: "The campaign mobilised support.", translation: "La campaña movilizó apoyo." }], [{ speaker: "A", text: "What does the petition ask for?", translation: "¿Qué pide la petición?" }, { speaker: "B", text: "A safer road and better local amenities.", translation: "Una carretera más segura y mejores servicios locales." }, { speaker: "A", text: "Will the council listen?", translation: "¿Escuchará el ayuntamiento?" }, { speaker: "B", text: "It has promised a public consultation.", translation: "Ha prometido una consulta pública." }], { title: "Improving the Neighbourhood", text: "Residents can influence local decisions by signing a petition, attending a consultation, or speaking through an advocate. A council must balance different needs and choose a feasible plan for the community.", translation: "Los residentes pueden influir en las decisiones locales firmando una petición, asistiendo a una consulta o hablando mediante un defensor. Un ayuntamiento debe equilibrar distintas necesidades y elegir un plan viable para la comunidad." }),
    u("u51", "Learning from Experience", "Reflect on setbacks, feedback, and changes that improve future work.", [
      w("setback", "contratiempo", "noun", "/ˈsetbæk/", "a problem that delays or prevents progress", "The delay was a temporary setback.", "El retraso fue un contratiempo temporal.", ["obstacle", "difficulty"], ["breakthrough"], ["major setback", "recover from a setback"], ["setback, set back"], ["learning", "work"], "challenge"),
      w("reflection", "reflexión", "noun", "/rɪˈflekʃən/", "careful thought about an experience or result", "The teacher asked for a short reflection.", "El profesor pidió una breve reflexión.", ["thought", "review"], ["inattention"], ["personal reflection", "write a reflection"], ["reflect, reflection, reflective"], ["learning", "thinking"], "evaluation"),
      w("insight", "perspicacia", "noun", "/ˈɪnsaɪt/", "a clear understanding of a complex situation", "The interview gave me insight into the problem.", "La entrevista me dio perspicacia sobre el problema.", ["understanding", "awareness"], ["confusion"], ["valuable insight", "gain insight"], ["insightful, insight"], ["learning", "thinking"], "understanding"),
      w("lesson", "lección", "noun", "/ˈlesən/", "knowledge gained from an experience", "The mistake taught us an important lesson.", "El error nos enseñó una lección importante.", ["teaching", "learning"], ["ignorance"], ["learn a lesson", "valuable lesson"], ["lesson, lessons"], ["learning", "experience"], "learning"),
      w("adjustment", "ajuste", "noun", "/əˈdʒʌstmənt/", "a small change made to improve something", "The plan needs a minor adjustment.", "El plan necesita un ajuste menor.", ["change", "modification"], ["continuation"], ["make an adjustment", "minor adjustment"], ["adjust, adjustment"], ["learning", "planning"], "change"),
      w("reflect", "reflexionar", "verb", "/rɪˈflekt/", "to think carefully about an experience or idea", "Take time to reflect on the result.", "Tómate tiempo para reflexionar sobre el resultado.", ["consider", "think over"], ["ignore"], ["reflect on experience", "reflect carefully"], ["reflect, reflection, reflective"], ["learning", "thinking"], "thinking action"),
      w("overcome", "superar", "verb", "/ˌoʊvərˈkʌm/", "to succeed in dealing with a difficulty", "She overcame her fear of speaking.", "Ella superó su miedo a hablar.", ["conquer", "surmount"], ["surrender"], ["overcome a challenge", "overcome an obstacle"], ["overcome, overcoming"], ["learning", "resilience"], "progress action"),
      w("adaptable", "adaptable", "adjective", "/əˈdæptəbəl/", "able to change successfully in new conditions", "An adaptable learner can use new methods.", "Un estudiante adaptable puede usar nuevos métodos.", ["flexible", "versatile"], ["rigid"], ["highly adaptable", "adaptable approach"], ["adapt, adaptable, adaptation"], ["learning", "work"], "quality"),
    ], [{ phrase: "Learn from the setback.", translation: "Aprende del contratiempo." }, { phrase: "Could you give me feedback?", translation: "¿Podrías darme comentarios?" }, { phrase: "Reflect on the experience.", translation: "Reflexiona sobre la experiencia." }, { phrase: "An adaptable plan can improve.", translation: "Un plan adaptable puede mejorar." }], [{ speaker: "A", text: "What did you learn from the setback?", translation: "¿Qué aprendiste del contratiempo?" }, { speaker: "B", text: "The feedback showed that we needed an adjustment.", translation: "Los comentarios mostraron que necesitábamos un ajuste." }, { speaker: "A", text: "Was it difficult to change the plan?", translation: "¿Fue difícil cambiar el plan?" }, { speaker: "B", text: "Yes, but we overcame the problem.", translation: "Sí, pero superamos el problema." }], { title: "A Better Second Attempt", text: "A setback can become a useful lesson when people reflect on what happened. Feedback offers insight, and a small adjustment may improve the next attempt. Adaptable learners overcome difficulties by changing their approach.", translation: "Un contratiempo puede convertirse en una lección útil cuando las personas reflexionan sobre lo ocurrido. Los comentarios ofrecen perspicacia y un pequeño ajuste puede mejorar el siguiente intento. Los estudiantes adaptables superan las dificultades cambiando su enfoque." }),
  ],
  B2: [
    u("u50", "Business Strategy", "Analyse growth, competition, and decisions in a changing market.", [
      w("acquisition", "adquisición", "noun", "/ˌækwɪˈzɪʃən/", "the purchase of one company or asset by another", "The acquisition expanded the company abroad.", "La adquisición expandió la empresa en el extranjero.", ["purchase", "takeover"], ["sale"], ["company acquisition", "complete an acquisition"], ["acquire, acquisition"], ["business", "economy"], "business"),
      w("diversify", "diversificar", "verb", "/daɪˈvɜːrsəfaɪ/", "to develop different products or activities to reduce risk", "The firm plans to diversify its services.", "La empresa planea diversificar sus servicios.", ["vary", "broaden"], ["concentrate"], ["diversify a portfolio", "diversify revenue"], ["diverse, diversify, diversification"], ["business", "strategy"], "strategy action"),
      w("viable", "viable", "adjective", "/ˈvaɪəbəl/", "able to work successfully and provide a practical solution", "The proposal is financially viable.", "La propuesta es viable financieramente.", ["workable", "feasible"], ["unworkable"], ["viable business", "commercially viable"], ["viability, viable"], ["business", "planning"], "quality"),
      w("benchmark", "referencia comparativa", "noun", "/ˈbentʃmɑːrk/", "a standard used to compare performance or quality", "The report sets a benchmark for efficiency.", "El informe establece una referencia comparativa para la eficiencia.", ["standard", "yardstick"], [], ["industry benchmark", "set a benchmark"], ["benchmark, benchmarking"], ["business", "measurement"], "business"),
      w("leverage", "aprovechar", "verb", "/ˈlevərɪdʒ/", "to use an advantage or resource effectively", "The start-up leveraged its local knowledge.", "La empresa emergente aprovechó su conocimiento local.", ["use", "exploit"], ["waste"], ["leverage expertise", "leverage technology"], ["lever, leverage"], ["business", "strategy"], "strategy action"),
      w("retention", "retención", "noun", "/rɪˈtenʃən/", "the ability to keep customers or employees", "Staff retention improved after the change.", "La retención del personal mejoró después del cambio.", ["preservation", "continuity"], ["turnover"], ["customer retention", "employee retention"], ["retain, retention"], ["business", "people"], "business"),
      w("outsource", "externalizar", "verb", "/ˈaʊtsɔːrs/", "to pay another organisation to do work for you", "The company decided to outsource delivery.", "La empresa decidió externalizar la entrega.", ["contract out", "subcontract"], ["internalise"], ["outsource work", "outsource production"], ["source, outsource, outsourcing"], ["business", "operations"], "business action"),
      w("turnover", "rotación", "noun", "/ˈtɜːrnoʊvər/", "the rate at which people leave an organisation or goods are sold", "High staff turnover can be expensive.", "Una alta rotación del personal puede ser cara.", ["revenue", "replacement rate"], ["retention"], ["staff turnover", "annual turnover"], ["turn over, turnover"], ["business", "people"], "business"),
    ], [{ phrase: "The proposal is financially viable.", translation: "La propuesta es viable financieramente." }, { phrase: "The company will diversify its services.", translation: "La empresa diversificará sus servicios." }, { phrase: "Customer retention is improving.", translation: "La retención de clientes está mejorando." }, { phrase: "The report sets a benchmark.", translation: "El informe establece una referencia comparativa." }], [{ speaker: "A", text: "Why is the company diversifying?", translation: "¿Por qué está diversificando la empresa?" }, { speaker: "B", text: "It wants to reduce risk and improve retention.", translation: "Quiere reducir el riesgo y mejorar la retención." }, { speaker: "A", text: "Will it outsource delivery?", translation: "¿Externalizará la entrega?" }, { speaker: "B", text: "Possibly, if the business case is viable.", translation: "Es posible, si el caso de negocio es viable." }], { title: "Choosing a Strategy", text: "A business can diversify its services, leverage its strengths, or outsource selected operations. Managers compare performance with a benchmark and consider whether an acquisition will improve retention without creating excessive turnover.", translation: "Una empresa puede diversificar sus servicios, aprovechar sus puntos fuertes o externalizar algunas operaciones. Los directivos comparan el rendimiento con una referencia y consideran si una adquisición mejorará la retención sin crear una rotación excesiva." }),
    u("u51", "Negotiating an Agreement", "Use precise language to negotiate terms, obligations, and acceptable compromises.", [
      w("clause", "cláusula", "noun", "/klɔːz/", "a separate part of a legal or formal agreement", "The contract contains a confidentiality clause.", "El contrato contiene una cláusula de confidencialidad.", ["provision", "condition"], [], ["contract clause", "include a clause"], ["clause, clauseless"], ["work", "law"], "agreement"),
      w("obligation", "obligación", "noun", "/ˌɑːbləˈɡeɪʃən/", "a duty to do something because of a rule or agreement", "The agreement creates a financial obligation.", "El acuerdo crea una obligación financiera.", ["duty", "requirement"], ["option"], ["legal obligation", "meet an obligation"], ["oblige, obligation, obligatory"], ["work", "law"], "agreement"),
      w("concession", "concesión", "noun", "/kənˈseʃən/", "something accepted or given up during a negotiation", "Both sides made a concession.", "Ambas partes hicieron una concesión.", ["compromise", "yield"], ["demand"], ["make a concession", "major concession"], ["concede, concession"], ["work", "negotiation"], "negotiation"),
      w("counteroffer", "contraoferta", "noun", "/ˈkaʊntərˌɔːfər/", "a new offer made in response to an earlier one", "The buyer submitted a counteroffer.", "El comprador presentó una contraoferta.", ["alternative offer", "reply offer"], [], ["make a counteroffer", "accept a counteroffer"], ["offer, counteroffer"], ["work", "money"], "negotiation"),
      w("timescale", "plazo", "noun", "/ˈtaɪmskeɪl/", "the period allowed for completing a project or task", "We need to agree on a realistic timescale.", "Tenemos que acordar un plazo realista.", ["time frame", "schedule"], ["indefinite period"], ["realistic timescale", "project timescale"], ["time, timescale"], ["work", "planning"], "time"),
      w("stipulate", "estipular", "verb", "/ˈstɪpjəleɪt/", "to state a condition or requirement clearly in an agreement", "The contract stipulates a monthly review.", "El contrato estipula una revisión mensual.", ["specify", "require"], ["omit"], ["stipulate a condition", "stipulate that"], ["stipulate, stipulation"], ["work", "law"], "legal action"),
      w("comply", "cumplir", "verb", "/kəmˈplaɪ/", "to act according to a rule, request, or agreement", "All suppliers must comply with the standard.", "Todos los proveedores deben cumplir la norma.", ["obey", "follow"], ["breach"], ["comply with a rule", "comply fully"], ["comply, compliance, compliant"], ["work", "law"], "legal action"),
      w("binding", "vinculante", "adjective", "/ˈbaɪndɪŋ/", "legally or officially requiring someone to act", "The decision is legally binding.", "La decisión es jurídicamente vinculante.", ["compulsory", "enforceable"], ["optional"], ["binding agreement", "legally binding"], ["bind, binding"], ["work", "law"], "quality"),
    ], [{ phrase: "The clause is legally binding.", translation: "La cláusula es jurídicamente vinculante." }, { phrase: "Both sides made a concession.", translation: "Ambas partes hicieron una concesión." }, { phrase: "We must meet the deadline.", translation: "Debemos cumplir la fecha límite." }, { phrase: "The supplier must comply.", translation: "El proveedor debe cumplir." }], [{ speaker: "A", text: "Can we change the deadline?", translation: "¿Podemos cambiar la fecha límite?" }, { speaker: "B", text: "Only if the counteroffer includes a clear reason.", translation: "Solo si la contraoferta incluye una razón clara." }, { speaker: "A", text: "What does the clause stipulate?", translation: "¿Qué estipula la cláusula?" }, { speaker: "B", text: "It makes the review binding on both sides.", translation: "Hace que la revisión sea vinculante para ambas partes." }], { title: "Reaching Terms", text: "Successful negotiation requires clear terms. Parties may make a concession, submit a counteroffer, and agree on a deadline. A contract can stipulate obligations, and a binding clause explains what each side must do.", translation: "Una negociación exitosa requiere términos claros. Las partes pueden hacer una concesión, presentar una contraoferta y acordar una fecha límite. Un contrato puede estipular obligaciones y una cláusula vinculante explica lo que debe hacer cada parte." }),
  ],
  C1: [
    u("u50", "Political Institutions", "Discuss constitutional structures, representation, and the distribution of power.", [
      w("constitutional", "constitucional", "adjective", "/ˌkɑːnstəˈtuːʃənəl/", "relating to the basic principles and structure of a state", "The court examined the constitutional question.", "El tribunal examinó la cuestión constitucional.", ["fundamental", "legal"], ["unconstitutional"], ["constitutional law", "constitutional reform"], ["constitute, constitution, constitutional"], ["politics", "law"], "politics"),
      w("legislature", "legislatura", "noun", "/ˈledʒɪsleɪtʃər/", "the part of government that makes laws", "The legislature debated the proposal.", "La legislatura debatió la propuesta.", ["parliament", "law-making body"], ["executive"], ["national legislature", "elected legislature"], ["legislate, legislature, legislative"], ["politics", "government"], "institution"),
      w("executive", "poder ejecutivo", "noun", "/ɪɡˈzekjətɪv/", "the branch of government that puts laws and policies into action", "The executive announced a new programme.", "El poder ejecutivo anunció un nuevo programa.", ["administration", "government"], ["legislature"], ["executive power", "executive branch"], ["execute, executive"], ["politics", "government"], "institution"),
      w("judiciary", "poder judicial", "noun", "/ˈdʒuːdɪʃəri/", "the system of courts and judges in a country", "An independent judiciary protects rights.", "Un poder judicial independiente protege los derechos.", ["court system", "bench"], ["lawlessness"], ["independent judiciary", "judiciary review"], ["judge, judicial, judiciary"], ["politics", "law"], "institution"),
      w("mandate", "mandato", "noun", "/ˈmændeɪt/", "the authority given to an elected person or group to act", "The election gave the party a clear mandate.", "Las elecciones dieron al partido un mandato claro.", ["authority", "commission"], ["prohibition"], ["electoral mandate", "public mandate"], ["mandate, mandated"], ["politics", "elections"], "politics"),
      w("coalition", "coalición", "noun", "/ˌkoʊəˈlɪʃən/", "a temporary alliance of groups or parties", "The parties formed a coalition government.", "Los partidos formaron un gobierno de coalición.", ["alliance", "partnership"], ["division"], ["coalition government", "form a coalition"], ["coalition"], ["politics", "government"], "politics"),
      w("electorate", "electorado", "noun", "/ɪˈlektərət/", "all the people who have the right to vote", "The electorate demanded change.", "El electorado exigió cambios.", ["voters", "voting public"], ["non-voters"], ["the national electorate", "appeal to the electorate"], ["elect, election, electorate"], ["politics", "elections"], "people"),
      w("pluralism", "pluralismo", "noun", "/ˈplʊrəlɪzəm/", "the acceptance of many different groups and ideas in society", "Political pluralism encourages debate.", "El pluralismo político fomenta el debate.", ["diversity", "variety"], ["uniformity"], ["political pluralism", "social pluralism"], ["plural, pluralist, pluralism"], ["politics", "society"], "social concept"),
    ], [{ phrase: "The legislature debated the proposal.", translation: "La legislatura debatió la propuesta." }, { phrase: "The judiciary must remain independent.", translation: "El poder judicial debe seguir siendo independiente." }, { phrase: "The party has a clear mandate.", translation: "El partido tiene un mandato claro." }, { phrase: "Pluralism encourages public debate.", translation: "El pluralismo fomenta el debate público." }], [{ speaker: "A", text: "Who makes the laws?", translation: "¿Quién hace las leyes?" }, { speaker: "B", text: "The legislature makes laws, while the executive applies them.", translation: "La legislatura hace las leyes, mientras el ejecutivo las aplica." }, { speaker: "A", text: "What protects constitutional rights?", translation: "¿Qué protege los derechos constitucionales?" }, { speaker: "B", text: "An independent judiciary and an active electorate.", translation: "Un poder judicial independiente y un electorado activo." }], { title: "Balancing Power", text: "A constitutional system distributes power among a legislature, an executive, and a judiciary. Elections give a mandate, but a coalition may be needed to govern. Political pluralism allows the electorate to compare different ideas.", translation: "Un sistema constitucional distribuye el poder entre una legislatura, un ejecutivo y un poder judicial. Las elecciones otorgan un mandato, pero puede ser necesaria una coalición para gobernar. El pluralismo político permite al electorado comparar distintas ideas." }),
    u("u51", "Research Design", "Evaluate academic methods, evidence, and the limits of a study.", [
      w("qualitative", "cualitativo", "adjective", "/ˈkwɑːlɪteɪtɪv/", "concerned with meanings, experiences, or qualities rather than numbers", "The researchers used qualitative interviews.", "Los investigadores usaron entrevistas cualitativas.", ["interpretive", "descriptive"], ["quantitative"], ["qualitative research", "qualitative data"], ["quality, qualitative"], ["research", "education"], "research"),
      w("quantitative", "cuantitativo", "adjective", "/ˈkwɑːntəteɪtɪv/", "concerned with numbers, measurement, or amounts", "The report includes quantitative evidence.", "El informe incluye evidencia cuantitativa.", ["numerical", "statistical"], ["qualitative"], ["quantitative analysis", "quantitative data"], ["quantity, quantitative"], ["research", "science"], "research"),
      w("sampling", "muestreo", "noun", "/ˈsæmplɪŋ/", "the process of selecting a smaller group for study", "The sampling method affected the results.", "El método de muestreo afectó los resultados.", ["selection", "surveying"], [], ["random sampling", "sampling method"], ["sample, sampling"], ["research", "statistics"], "research"),
      w("anonymise", "anonimizar", "verb", "/əˈnɑːnəmaɪz/", "to remove names or details that identify a person", "The team anonymised the interview data.", "El equipo anonimizó los datos de las entrevistas.", ["de-identify", "protect identity"], ["identify"], ["anonymise data", "anonymise participants"], ["anonymous, anonymise, anonymisation"], ["research", "privacy"], "research action"),
      w("replication", "replicación", "noun", "/ˌreplɪˈkeɪʃən/", "the act of repeating a study or experiment", "The replication produced a similar result.", "La replicación produjo un resultado similar.", ["repetition", "reproduction"], ["originality"], ["study replication", "successful replication"], ["replicate, replication, replicable"], ["research", "science"], "research"),
      w("confounder", "factor de confusión", "noun", "/kənˈfaʊndər/", "a factor that affects both variables and makes a relationship unclear", "Age was a possible confounder in the study.", "La edad fue un posible factor de confusión en el estudio.", ["confounding factor", "interfering variable"], [], ["potential confounder", "control for a confounder"], ["confound, confounding, confounder"], ["research", "statistics"], "research"),
      w("operationalise", "operacionalizar", "verb", "/ˌɑːpəˈreɪʃənəlaɪz/", "to define a concept in a way that can be measured", "The study operationalises trust through survey questions.", "El estudio operacionaliza la confianza mediante preguntas de encuesta.", ["define", "measure"], ["generalise"], ["operationalise a concept", "operationalise a variable"], ["operate, operational, operationalise"], ["research", "methodology"], "research action"),
      w("robust", "sólido", "adjective", "/roʊˈbʌst/", "strong and reliable enough to remain valid in different conditions", "The conclusion is based on robust evidence.", "La conclusión se basa en evidencia sólida.", ["strong", "reliable"], ["weak"], ["robust evidence", "robust method"], ["robust, robustness"], ["research", "quality"], "quality"),
    ], [{ phrase: "The study uses qualitative interviews.", translation: "El estudio usa entrevistas cualitativas." }, { phrase: "The sample was selected randomly.", translation: "La muestra fue seleccionada al azar." }, { phrase: "The data was anonymised.", translation: "Los datos fueron anonimizados." }, { phrase: "The conclusion is robust.", translation: "La conclusión es sólida." }], [{ speaker: "A", text: "Why does sampling matter?", translation: "¿Por qué importa el muestreo?" }, { speaker: "B", text: "A biased sample can weaken the conclusion.", translation: "Una muestra sesgada puede debilitar la conclusión." }, { speaker: "A", text: "How did the team protect participants?", translation: "¿Cómo protegió el equipo a los participantes?" }, { speaker: "B", text: "They anonymised the data and controlled for confounders.", translation: "Anonimizaron los datos y controlaron los factores de confusión." }], { title: "Reading a Study", text: "A strong research design explains its sampling method and defines its concepts clearly. Qualitative and quantitative evidence answer different questions. Researchers anonymise participants, consider confounders, and seek replication before making robust conclusions.", translation: "Un diseño de investigación sólido explica su método de muestreo y define sus conceptos con claridad. La evidencia cualitativa y cuantitativa responde a preguntas diferentes. Los investigadores anonimizan a los participantes, consideran factores de confusión y buscan replicación antes de formular conclusiones sólidas." }),
  ],
  C2: [
    u("u50", "Advanced Linguistics", "Analyse sound, structure, and meaning in sophisticated language use.", [
      w("polysemy", "polisemia", "noun", "/pəˈlɪsəmi/", "the condition of a word having several related meanings", "Polysemy allows one word to develop a network of meanings.", "La polisemia permite que una palabra desarrolle una red de significados.", ["multiple meaning", "semantic range"], ["monosemy"], ["lexical polysemy", "patterns of polysemy"], ["polysemy, polysemous"], ["linguistics", "meaning"], "linguistics"),
      w("homonymy", "homonimia", "noun", "/həˈmɑːnəmi/", "the relationship between words that sound or look alike but differ in meaning", "Homonymy can create ambiguity in a sentence.", "La homonimia puede crear ambigüedad en una oración.", ["word coincidence", "lexical overlap"], ["contrast"], ["lexical homonymy", "homonymy and polysemy"], ["homonym, homonymy"], ["linguistics", "meaning"], "linguistics"),
      w("morphology", "morfología", "noun", "/mɔːrˈfɑːlədʒi/", "the study of the forms and parts of words", "Morphology explains how prefixes change meaning.", "La morfología explica cómo los prefijos cambian el significado.", ["word structure", "inflection"], [], ["English morphology", "morphological analysis"], ["morpheme, morphology, morphological"], ["linguistics", "grammar"], "linguistics"),
      w("syntax", "sintaxis", "noun", "/ˈsɪntæks/", "the rules for arranging words into phrases and sentences", "Syntax determines the order of words.", "La sintaxis determina el orden de las palabras.", ["sentence structure", "grammar"], [], ["syntactic structure", "syntax rules"], ["syntactic, syntax"], ["linguistics", "grammar"], "linguistics"),
      w("phonology", "fonología", "noun", "/fəˈnɑːlədʒi/", "the study of how sounds function in a particular language", "Phonology describes contrasts between English sounds.", "La fonología describe los contrastes entre los sonidos ingleses.", ["sound system", "speech science"], [], ["English phonology", "phonological system"], ["phoneme, phonology, phonological"], ["linguistics", "pronunciation"], "linguistics"),
      w("prosody", "prosodia", "noun", "/ˈprɑːsədi/", "the rhythm, stress, and intonation of spoken language", "Prosody can signal irony or uncertainty.", "La prosodia puede señalar ironía o incertidumbre.", ["intonation", "rhythm"], [], ["speech prosody", "prosodic pattern"], ["prosodic, prosody"], ["linguistics", "speech"], "linguistics"),
      w("lexicon", "léxico", "noun", "/ˈleksɪkɑːn/", "the complete set of words used in a language or by a speaker", "Technical writing has a specialised lexicon.", "La escritura técnica tiene un léxico especializado.", ["vocabulary", "word stock"], [], ["mental lexicon", "specialised lexicon"], ["lexical, lexicon"], ["linguistics", "vocabulary"], "linguistics"),
      w("morpheme", "morfema", "noun", "/ˈmɔːrfiːm/", "the smallest part of a word that carries meaning or grammar", "The plural ending is a grammatical morpheme.", "La terminación plural es un morfema gramatical.", ["word part", "unit of meaning"], [], ["free morpheme", "bound morpheme"], ["morph, morpheme, morphological"], ["linguistics", "grammar"], "linguistics"),
    ], [{ phrase: "Syntax determines word order.", translation: "La sintaxis determina el orden de las palabras." }, { phrase: "Prosody carries social meaning.", translation: "La prosodia transmite significado social." }, { phrase: "The word has several related meanings.", translation: "La palabra tiene varios significados relacionados." }, { phrase: "The ending is a grammatical morpheme.", translation: "La terminación es un morfema gramatical." }], [{ speaker: "A", text: "How are polysemy and homonymy different?", translation: "¿En qué se diferencian la polisemia y la homonimia?" }, { speaker: "B", text: "Polysemy links related meanings, while homonymy involves unrelated ones.", translation: "La polisemia relaciona significados, mientras que la homonimia implica significados no relacionados." }, { speaker: "A", text: "What does prosody add to speech?", translation: "¿Qué añade la prosodia al habla?" }, { speaker: "B", text: "It adds rhythm, stress, and subtle attitude.", translation: "Añade ritmo, acento y actitud sutil." }], { title: "Language beneath the Words", text: "Linguistics examines language at several levels. Morphology studies morphemes, syntax studies structure, and phonology studies sound systems. Prosody shapes spoken meaning, while the lexicon contains the words that speakers can select.", translation: "La lingüística examina el lenguaje en varios niveles. La morfología estudia los morfemas, la sintaxis estudia la estructura y la fonología estudia los sistemas de sonidos. La prosodia da forma al significado hablado, mientras que el léxico contiene las palabras que los hablantes pueden seleccionar." }),
    u("u51", "Philosophy of Possibility", "Discuss necessity, contingency, values, and the limits of certainty.", [
      w("teleology", "teleología", "noun", "/ˌtelɪˈɑːlədʒi/", "the study of purposes or goals as explanations of events", "Teleology asks whether history has a direction.", "La teleología pregunta si la historia tiene una dirección.", ["study of purpose", "goal theory"], ["mechanism"], ["teleological explanation", "teleology of history"], ["teleology, teleological"], ["philosophy", "history"], "philosophy"),
      w("contingency", "contingencia", "noun", "/kənˈtɪndʒənsi/", "the condition of depending on chance or circumstances rather than necessity", "The theory emphasises the contingency of social institutions.", "La teoría enfatiza la contingencia de las instituciones sociales.", ["chance", "dependence"], ["necessity"], ["historical contingency", "contingency of events"], ["contingent, contingency"], ["philosophy", "society"], "philosophy"),
      w("necessity", "necesidad", "noun", "/nəˈsesəti/", "the state of being required or unable to be otherwise", "The argument distinguishes necessity from possibility.", "El argumento distingue la necesidad de la posibilidad.", ["requirement", "inevitability"], ["possibility"], ["logical necessity", "necessity and possibility"], ["necessary, necessity"], ["philosophy", "logic"], "philosophy"),
      w("immanence", "inmanencia", "noun", "/ˈɪmənəns/", "the quality of being contained within a system or experience", "The theory focuses on immanence rather than external causes.", "La teoría se centra en la inmanencia y no en causas externas.", ["internality", "presence"], ["transcendence"], ["plane of immanence", "immanence of value"], ["immanent, immanence"], ["philosophy", "metaphysics"], "philosophy"),
      w("transcendence", "trascendencia", "noun", "/trænˈsendəns/", "the state of going beyond ordinary limits or experience", "The poem suggests transcendence through silence.", "El poema sugiere trascendencia mediante el silencio.", ["surpassing", "elevation"], ["immanence"], ["religious transcendence", "seek transcendence"], ["transcend, transcendent, transcendence"], ["philosophy", "religion"], "philosophy"),
      w("normativity", "normatividad", "noun", "/ˌnɔːrməˈtɪvəti/", "the quality of expressing or establishing standards of value or behaviour", "The essay examines the normativity of social rules.", "El ensayo examina la normatividad de las reglas sociales.", ["prescription", "standard-setting"], ["description"], ["moral normativity", "normativity of values"], ["norm, normative, normativity"], ["philosophy", "ethics"], "philosophy"),
      w("subjectivity", "subjetividad", "noun", "/ˌsʌbdʒekˈtɪvəti/", "the influence of personal experience or viewpoint", "The account reveals the subjectivity of memory.", "El relato revela la subjetividad de la memoria.", ["personal perspective", "individuality"], ["objectivity"], ["human subjectivity", "subjectivity of experience"], ["subject, subjective, subjectivity"], ["philosophy", "mind"], "philosophy"),
      w("indeterminate", "indeterminado", "adjective", "/ˌɪndɪˈtɜːrmɪnət/", "not fixed, certain, or limited to one clear result", "The meaning remains indeterminate.", "El significado sigue siendo indeterminado.", ["uncertain", "open-ended"], ["determinate"], ["indeterminate outcome", "remain indeterminate"], ["determine, determination, indeterminate"], ["philosophy", "language"], "quality"),
    ], [{ phrase: "The outcome is contingent.", translation: "El resultado es contingente." }, { phrase: "The argument distinguishes necessity from possibility.", translation: "El argumento distingue la necesidad de la posibilidad." }, { phrase: "The text explores moral normativity.", translation: "El texto explora la normatividad moral." }, { phrase: "The meaning remains indeterminate.", translation: "El significado sigue siendo indeterminado." }], [{ speaker: "A", text: "Is history governed by necessity?", translation: "¿Está la historia gobernada por la necesidad?" }, { speaker: "B", text: "A teleological account may say so, but contingency allows other readings.", translation: "Una explicación teleológica puede decirlo, pero la contingencia permite otras lecturas." }, { speaker: "A", text: "Can experience be objective?", translation: "¿Puede la experiencia ser objetiva?" }, { speaker: "B", text: "It may include both subjectivity and a search for shared standards.", translation: "Puede incluir tanto subjetividad como una búsqueda de normas compartidas." }], { title: "Beyond Certainty", text: "Philosophical questions about possibility distinguish what is necessary from what is contingent. Teleology asks about purpose, while theories of immanence and transcendence describe different limits of experience. Normativity and subjectivity shape how people judge values and meaning.", translation: "Las preguntas filosóficas sobre la posibilidad distinguen lo necesario de lo contingente. La teleología pregunta por el propósito, mientras que las teorías de la inmanencia y la trascendencia describen distintos límites de la experiencia. La normatividad y la subjetividad determinan cómo las personas juzgan los valores y el significado." }),
  ],
};
