import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/**
 * Reviewed enrichment for the next existing B1/B2/C1 units. This is an
 * enrichment bank only: it does not declare or create curriculum units.
 */
export const ENGLISH_B1_B2_C1_FOCUSED_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u47: [
      reviewed({ word: "heritage trail", translation: "مسار التراث", pos: "noun", ipa: "/ˈherɪtɪdʒ treɪl/", definition: "a route connecting places of historical or cultural importance", example: "The heritage trail connects the museum with several historic houses.", exampleTranslation: "يربط مسار التراث المتحف بعدة بيوت تاريخية.", category: "culture and travel", tags: ["travel", "heritage"], synonyms: ["historic route", "cultural route"] }),
      reviewed({ word: "authentic", translation: "أصيل / حقيقي", pos: "adjective", ipa: "/ɔːˈθentɪk/", definition: "genuine and representative of the original culture or source", example: "The guide introduced us to an authentic family recipe.", exampleTranslation: "عرّفنا المرشد بوصفة عائلية أصيلة.", category: "culture and travel", tags: ["culture", "food"], synonyms: ["genuine", "real"] }),
      reviewed({ word: "ecotourism", translation: "السياحة البيئية", pos: "noun", ipa: "/ˌiːkoʊˈtʊrɪzəm/", definition: "travel that aims to protect nature and benefit local communities", example: "Responsible ecotourism can support conservation and local employment.", exampleTranslation: "يمكن للسياحة البيئية المسؤولة أن تدعم حماية الطبيعة وفرص العمل المحلية.", category: "culture and travel", tags: ["travel", "environment"], synonyms: ["sustainable tourism", "nature tourism"] }),
      reviewed({ word: "cultural site", translation: "موقع ثقافي", pos: "noun", ipa: "/ˈkʌltʃərəl saɪt/", definition: "a place valued for its historical, artistic, or social importance", example: "The temple is protected as an important cultural site.", exampleTranslation: "يحظى المعبد بالحماية بوصفه موقعًا ثقافيًا مهمًا.", category: "culture and travel", tags: ["travel", "culture"], synonyms: ["heritage site", "place of cultural importance"] }),
      reviewed({ word: "cultural exchange", translation: "تبادل ثقافي", pos: "noun", ipa: "/ˈkʌltʃərəl ɪksˈtʃeɪndʒ/", definition: "the sharing of ideas, customs, and experiences between cultures", example: "The student programme encourages cultural exchange through shared projects.", exampleTranslation: "يشجع برنامج الطلاب التبادل الثقافي من خلال المشاريع المشتركة.", category: "culture and travel", tags: ["culture", "communication"], synonyms: ["cross-cultural exchange", "cultural sharing"] }),
      reviewed({ word: "off-season", translation: "خارج الموسم", pos: "noun", ipa: "/ˌɔːf ˈsiːzən/", definition: "the period when a place receives fewer visitors than usual", example: "Travelling in the off-season is often cheaper and quieter.", exampleTranslation: "يكون السفر خارج الموسم غالبًا أرخص وأكثر هدوءًا.", category: "culture and travel", tags: ["travel", "planning"], synonyms: ["low season", "quiet season"] }),
      reviewed({ word: "preservation", translation: "حفظ / صون", pos: "noun", ipa: "/ˌprezərˈveɪʃən/", definition: "the protection of a place, tradition, or object from damage or loss", example: "The preservation of historic buildings requires long-term funding.", exampleTranslation: "يتطلب صون المباني التاريخية تمويلًا طويل الأمد.", category: "culture and travel", tags: ["heritage", "community"], synonyms: ["conservation", "protection"] }),
      reviewed({ word: "responsible traveller", translation: "مسافر مسؤول", pos: "noun", ipa: "/rɪˈspɑːnsəbəl ˈtrævələr/", definition: "a traveller who considers the environmental and social effects of their choices", example: "A responsible traveller respects local customs and reduces unnecessary waste.", exampleTranslation: "يحترم المسافر المسؤول العادات المحلية ويقلل النفايات غير الضرورية.", category: "culture and travel", tags: ["travel", "ethics"], synonyms: ["conscientious tourist", "ethical traveller"] }),
    ],
    u48: [
      reviewed({ word: "culinary", translation: "متعلق بالطهي", pos: "adjective", ipa: "/ˈkʌləneri/", definition: "relating to cooking, food, or the preparation of meals", example: "The course explores the culinary traditions of several regions.", exampleTranslation: "تستكشف الدورة تقاليد الطهي في عدة مناطق.", category: "food and wellbeing", tags: ["food", "culture"], synonyms: ["cooking-related", "gastronomic"] }),
      reviewed({ word: "allergen", translation: "مادة مسببة للحساسية", pos: "noun", ipa: "/ˈælədʒən/", definition: "a substance that can cause an allergic reaction", example: "The menu clearly identifies each common allergen.", exampleTranslation: "تحدد القائمة بوضوح كل مادة شائعة مسببة للحساسية.", category: "food and wellbeing", tags: ["food", "health"], synonyms: ["allergy trigger", "allergenic substance"] }),
      reviewed({ word: "balanced meal", translation: "وجبة متوازنة", pos: "noun", ipa: "/ˌbælənst ˈmiːl/", definition: "a meal containing appropriate amounts of different nutrients", example: "A balanced meal can include vegetables, protein, whole grains, and fruit.", exampleTranslation: "يمكن أن تشمل الوجبة المتوازنة الخضروات والبروتين والحبوب الكاملة والفواكه.", category: "food and wellbeing", tags: ["food", "health"], synonyms: ["nutritionally balanced meal", "healthy meal"] }),
      reviewed({ word: "moderation", translation: "اعتدال", pos: "noun", ipa: "/ˌmɑːdəˈreɪʃən/", definition: "the practice of avoiding excess in the amount or frequency of something", example: "The advice is to enjoy sweet foods in moderation.", exampleTranslation: "النصيحة هي الاستمتاع بالأطعمة الحلوة باعتدال.", category: "food and wellbeing", tags: ["health", "habits"], synonyms: ["restraint", "balance"] }),
      reviewed({ word: "locally sourced", translation: "من مصادر محلية", pos: "adjective", ipa: "/ˌloʊkəli ˈsɔːrst/", definition: "obtained from producers or suppliers in the nearby area", example: "The restaurant uses locally sourced vegetables whenever possible.", exampleTranslation: "يستخدم المطعم الخضروات من مصادر محلية كلما أمكن.", category: "food and wellbeing", tags: ["food", "community"], synonyms: ["local", "regionally produced"] }),
      reviewed({ word: "food waste", translation: "هدر الطعام", pos: "noun", ipa: "/ˈfuːd weɪst/", definition: "food that is discarded instead of being eaten or used", example: "Planning portions carefully can reduce food waste at home.", exampleTranslation: "يمكن لتخطيط الحصص بعناية أن يقلل هدر الطعام في المنزل.", category: "food and wellbeing", tags: ["food", "environment"], synonyms: ["discarded food", "food loss"] }),
      reviewed({ word: "hydration", translation: "ترطيب الجسم", pos: "noun", ipa: "/haɪˈdreɪʃən/", definition: "the process of providing the body with enough water", example: "Good hydration helps people stay focused during a long day.", exampleTranslation: "يساعد ترطيب الجسم الجيد الناس على الحفاظ على التركيز خلال يوم طويل.", category: "food and wellbeing", tags: ["health", "habits"], synonyms: ["fluid intake", "water balance"] }),
      reviewed({ word: "wholegrain", translation: "حبوب كاملة", pos: "noun", ipa: "/ˈhoʊlɡreɪn/", definition: "a grain that retains the outer layers containing fibre and nutrients", example: "Wholegrain bread usually contains more fibre than refined white bread.", exampleTranslation: "يحتوي خبز الحبوب الكاملة عادةً على ألياف أكثر من الخبز الأبيض المكرر.", category: "food and wellbeing", tags: ["food", "nutrition"], synonyms: ["whole cereal", "unrefined grain"] }),
    ],
    u49: [
      reviewed({ word: "community-led", translation: "بقيادة المجتمع", pos: "adjective", ipa: "/kəˈmjuːnəti led/", definition: "organised and directed by members of the local community", example: "A community-led campaign persuaded the council to improve the park.", exampleTranslation: "أقنعت حملة بقيادة المجتمع المجلس بتحسين الحديقة.", category: "community projects", tags: ["community", "activism"], synonyms: ["grassroots", "locally directed"] }),
      reviewed({ word: "project partner", translation: "شريك المشروع", pos: "noun", ipa: "/ˈprɑːdʒekt ˌpɑːrtnər/", definition: "a person or organisation that works with others to deliver a project", example: "Every project partner was invited to comment on the proposal.", exampleTranslation: "دُعي كل شريك في المشروع للتعليق على المقترح.", category: "community projects", tags: ["community", "planning"], synonyms: ["collaborating organisation", "project participant"] }),
      reviewed({ word: "community liaison", translation: "حلقة وصل مجتمعية", pos: "noun", ipa: "/kəˈmjuːnəti liˈeɪzɑːn/", definition: "a person who connects a project or organisation with local residents", example: "The community liaison listened to residents before the service was redesigned.", exampleTranslation: "استمع مسؤول التواصل المجتمعي إلى السكان قبل إعادة تصميم الخدمة.", category: "community projects", tags: ["community", "support"], synonyms: ["community contact", "local link"] }),
      reviewed({ word: "grant", translation: "منحة", pos: "noun", ipa: "/ɡrænt/", definition: "money given by an organisation to support a particular project or purpose", example: "The group received a grant to renovate the community centre.", exampleTranslation: "حصلت المجموعة على منحة لتجديد المركز المجتمعي.", category: "community projects", tags: ["community", "funding"], synonyms: ["award", "funding"] }),
      reviewed({ word: "public participation", translation: "مشاركة عامة", pos: "noun", ipa: "/ˌpʌblɪk pɑːrˌtɪsɪˈpeɪʃən/", definition: "the involvement of residents in decisions that affect public life", example: "The project gives young people practical experience of public participation.", exampleTranslation: "يمنح المشروع الشباب خبرة عملية في المشاركة العامة.", category: "community projects", tags: ["community", "citizenship"], synonyms: ["civic engagement", "public involvement"] }),
      reviewed({ word: "social cohesion", translation: "تماسك اجتماعي", pos: "noun", ipa: "/ˌsoʊʃəl koʊˈhiːʒən/", definition: "the degree to which members of a society cooperate and feel connected", example: "Shared community spaces can strengthen social cohesion.", exampleTranslation: "يمكن للأماكن المجتمعية المشتركة أن تعزز التماسك الاجتماعي.", category: "community projects", tags: ["community", "society"], synonyms: ["social unity", "community solidarity"] }),
      reviewed({ word: "mutual aid", translation: "مساعدة متبادلة", pos: "noun", ipa: "/ˌmjuːtʃuəl ˈeɪd/", definition: "a system in which people support one another directly", example: "Neighbours organised mutual aid during the extended power cut.", exampleTranslation: "نظم الجيران مساعدة متبادلة خلال انقطاع الكهرباء الطويل.", category: "community projects", tags: ["community", "support"], synonyms: ["reciprocal support", "neighbour support"] }),
      reviewed({ word: "underserved", translation: "محروم من الخدمات الكافية", pos: "adjective", ipa: "/ˌʌndərˈsɜːrvd/", definition: "not receiving enough access to services, resources, or opportunities", example: "The programme prioritises underserved neighbourhoods.", exampleTranslation: "يعطي البرنامج الأولوية للأحياء المحرومة من الخدمات الكافية.", category: "community projects", tags: ["community", "equality"], synonyms: ["under-resourced", "neglected"] }),
    ],
  },
  B2: {
    u47: [
      reviewed({ word: "product range", translation: "مجموعة المنتجات", pos: "noun", ipa: "/ˈprɑːdʌkt reɪndʒ/", definition: "the complete selection of products offered by a company", example: "The company expanded its product range before entering a new market.", exampleTranslation: "وسعت الشركة مجموعة منتجاتها قبل دخول سوق جديد.", category: "business strategy", tags: ["business", "planning"], synonyms: ["product line", "range of products"] }),
      reviewed({ word: "performance yardstick", translation: "مقياس الأداء", pos: "noun", ipa: "/pərˈfɔːrməns ˈjɑːrdstɪk/", definition: "a standard used to assess how well a person, team, or organisation performs", example: "Customer retention became the main performance yardstick for the new strategy.", exampleTranslation: "أصبح الاحتفاظ بالعملاء مقياس الأداء الرئيسي للاستراتيجية الجديدة.", category: "business strategy", tags: ["business", "measurement"], synonyms: ["performance standard", "benchmark"] }),
      reviewed({ word: "scalability", translation: "قابلية التوسع", pos: "noun", ipa: "/ˌskeɪləˈbɪləti/", definition: "the ability of a system or business to grow without losing effectiveness", example: "The founders tested the platform’s scalability before expanding abroad.", exampleTranslation: "اختبر المؤسسون قابلية المنصة للتوسع قبل التوسع خارج البلاد.", category: "business strategy", tags: ["business", "technology"], synonyms: ["expandability", "growth capacity"] }),
      reviewed({ word: "diversify", translation: "ينوع", pos: "verb", ipa: "/daɪˈvɜːrsɪfaɪ/", definition: "to develop a wider range of products, markets, or activities", example: "The firm diversified its services to reduce dependence on one client.", exampleTranslation: "نوّعت الشركة خدماتها لتقليل اعتمادها على عميل واحد.", category: "business strategy", tags: ["business", "risk"], synonyms: ["broaden", "vary"] }),
      reviewed({ word: "value proposition", translation: "عرض القيمة", pos: "noun", ipa: "/ˈvæljuː ˌprɑːpəˈzɪʃən/", definition: "the clear benefit a product or service promises to provide", example: "The value proposition must explain why the service is worth the price.", exampleTranslation: "يجب أن يوضح عرض القيمة سبب استحقاق الخدمة لسعرها.", category: "business strategy", tags: ["business", "marketing"], synonyms: ["customer promise", "benefit statement"] }),
      reviewed({ word: "due diligence", translation: "العناية الواجبة", pos: "noun", ipa: "/ˌduː ˈdɪlɪdʒəns/", definition: "careful investigation before making an agreement or investment", example: "The investors completed due diligence before buying the company.", exampleTranslation: "أكمل المستثمرون العناية الواجبة قبل شراء الشركة.", category: "business strategy", tags: ["business", "risk"], synonyms: ["careful investigation", "background review"] }),
      reviewed({ word: "market share", translation: "الحصة السوقية", pos: "noun", ipa: "/ˈmɑːrkɪt ʃer/", definition: "the proportion of total sales in a market held by a company or product", example: "The redesigned product helped the company increase its market share.", exampleTranslation: "ساعد المنتج المعاد تصميمه الشركة على زيادة حصتها السوقية.", category: "business strategy", tags: ["business", "competition"], synonyms: ["sales share", "market position"] }),
      reviewed({ word: "strategic alignment", translation: "مواءمة استراتيجية", pos: "noun", ipa: "/strəˌtiːdʒɪk əˈlaɪnmənt/", definition: "the consistency between an organisation’s goals, actions, and resources", example: "Strategic alignment keeps separate teams focused on the same priorities.", exampleTranslation: "تحافظ المواءمة الاستراتيجية على تركيز الفرق المنفصلة على الأولويات نفسها.", category: "business strategy", tags: ["business", "planning"], synonyms: ["goal alignment", "strategic coherence"] }),
    ],
    u48: [
      reviewed({ word: "carbon pricing", translation: "تسعير الكربون", pos: "noun", ipa: "/ˈkɑːrbən ˈpraɪsɪŋ/", definition: "putting a financial cost on greenhouse-gas emissions", example: "Carbon pricing can encourage industries to invest in cleaner technology.", exampleTranslation: "يمكن لتسعير الكربون أن يشجع الصناعات على الاستثمار في التكنولوجيا الأنظف.", category: "climate policy", tags: ["climate", "economy"], synonyms: ["emissions pricing", "carbon cost"] }),
      reviewed({ word: "climate finance", translation: "تمويل المناخ", pos: "noun", ipa: "/ˈklaɪmət faɪˈnæns/", definition: "funding for reducing emissions or adapting to climate change", example: "Developing countries need predictable climate finance for resilient infrastructure.", exampleTranslation: "تحتاج البلدان النامية إلى تمويل مناخي يمكن التنبؤ به للبنية التحتية القادرة على الصمود.", category: "climate policy", tags: ["climate", "finance"], synonyms: ["climate funding", "green finance"] }),
      reviewed({ word: "adaptation pathway", translation: "مسار التكيف", pos: "noun", ipa: "/ˌædæpˈteɪʃən ˈpæθweɪ/", definition: "a planned sequence of actions for responding to future climate risks", example: "The city published an adaptation pathway for managing rising heat.", exampleTranslation: "نشرت المدينة مسار تكيف لإدارة ارتفاع درجات الحرارة.", category: "climate policy", tags: ["climate", "planning"], synonyms: ["adaptation strategy", "resilience pathway"] }),
      reviewed({ word: "nature-based solution", translation: "حل قائم على الطبيعة", pos: "noun", ipa: "/ˈneɪtʃər beɪst səˈluːʃən/", definition: "an action that uses natural processes to address social or environmental challenges", example: "Wetland restoration is a nature-based solution for flood protection.", exampleTranslation: "تعد استعادة الأراضي الرطبة حلًا قائمًا على الطبيعة للحماية من الفيضانات.", category: "climate policy", tags: ["climate", "environment"], synonyms: ["ecosystem-based measure", "natural solution"] }),
      reviewed({ word: "climate equity", translation: "إنصاف مناخي", pos: "noun", ipa: "/ˈklaɪmət ˈekwəti/", definition: "the principle that climate burdens, responsibilities, and benefits should be shared fairly", example: "Climate equity asks who caused the emissions and who faces the greatest risks.", exampleTranslation: "يسأل الإنصاف المناخي من تسبب في الانبعاثات ومن يواجه أكبر المخاطر.", category: "climate policy", tags: ["climate", "equality"], synonyms: ["fair climate policy", "environmental fairness"] }),
      reviewed({ word: "loss and damage", translation: "الخسائر والأضرار", pos: "noun", ipa: "/ˌlɔːs ənd ˈdæmɪdʒ/", definition: "climate-related harm that remains after adaptation cannot prevent it", example: "Negotiations considered how to fund loss and damage after extreme events.", exampleTranslation: "بحثت المفاوضات كيفية تمويل الخسائر والأضرار بعد الأحداث المتطرفة.", category: "climate policy", tags: ["climate", "policy"], synonyms: ["climate harm", "residual climate damage"] }),
      reviewed({ word: "green transition", translation: "التحول الأخضر", pos: "noun", ipa: "/ˌɡriːn trænˈzɪʃən/", definition: "the shift towards an economy with lower environmental impact", example: "A fair green transition must support workers in carbon-intensive industries.", exampleTranslation: "يجب أن يدعم التحول الأخضر العادل العاملين في الصناعات كثيفة الكربون.", category: "climate policy", tags: ["climate", "economy"], synonyms: ["low-carbon transition", "sustainable transition"] }),
      reviewed({ word: "energy efficiency", translation: "كفاءة الطاقة", pos: "noun", ipa: "/ˈenərdʒi ɪˈfɪʃənsi/", definition: "the ability to provide a service while using less energy", example: "Improving energy efficiency can reduce bills as well as emissions.", exampleTranslation: "يمكن لتحسين كفاءة الطاقة أن يقلل الفواتير والانبعاثات معًا.", category: "climate policy", tags: ["climate", "energy"], synonyms: ["efficient energy use", "energy conservation"] }),
    ],
    u49: [
      reviewed({ word: "metacognition", translation: "ما وراء المعرفة", pos: "noun", ipa: "/ˌmetəkɑːɡˈnɪʃən/", definition: "awareness and regulation of one’s own thinking and learning", example: "Metacognition helps learners notice which strategies work for them.", exampleTranslation: "تساعد ما وراء المعرفة المتعلمين على ملاحظة الاستراتيجيات التي تنجح معهم.", category: "psychology and behaviour", tags: ["psychology", "learning"], synonyms: ["self-monitoring", "thinking about thinking"] }),
      reviewed({ word: "emotional regulation", translation: "تنظيم المشاعر", pos: "noun", ipa: "/ɪˈmoʊʃənəl ˌreɡjəˈleɪʃən/", definition: "the ability to manage emotional responses in a useful and appropriate way", example: "Emotional regulation can prevent a brief frustration from becoming a serious conflict.", exampleTranslation: "يمكن لتنظيم المشاعر أن يمنع الإحباط العابر من التحول إلى نزاع خطير.", category: "psychology and behaviour", tags: ["psychology", "wellbeing"], synonyms: ["emotion management", "emotional control"] }),
      reviewed({ word: "cognitive load", translation: "العبء المعرفي", pos: "noun", ipa: "/ˈkɑːɡnətɪv loʊd/", definition: "the amount of mental effort required to process information", example: "Clear instructions reduce cognitive load during a complex task.", exampleTranslation: "تقلل التعليمات الواضحة العبء المعرفي أثناء مهمة معقدة.", category: "psychology and behaviour", tags: ["psychology", "learning"], synonyms: ["mental demand", "processing load"] }),
      reviewed({ word: "behavioural pattern", translation: "نمط سلوكي", pos: "noun", ipa: "/bɪˈheɪvjərəl ˈpætərn/", definition: "a repeated and recognisable way in which someone acts", example: "The study identified a behavioural pattern associated with late-night use.", exampleTranslation: "حددت الدراسة نمطًا سلوكيًا مرتبطًا بالاستخدام ليلًا.", category: "psychology and behaviour", tags: ["psychology", "research"], synonyms: ["behaviour pattern", "recurrent behaviour"] }),
      reviewed({ word: "intrinsic motivation", translation: "دافع جوهري", pos: "noun", ipa: "/ɪnˌtrɪnsɪk moʊtɪˈveɪʃən/", definition: "the desire to do something because it is personally meaningful or enjoyable", example: "Intrinsic motivation often supports learning beyond the end of a course.", exampleTranslation: "يدعم الدافع الجوهري التعلم غالبًا حتى بعد انتهاء الدورة.", category: "psychology and behaviour", tags: ["psychology", "learning"], synonyms: ["internal motivation", "self-driven motivation"] }),
      reviewed({ word: "self-efficacy", translation: "الكفاءة الذاتية", pos: "noun", ipa: "/ˌself ˈefɪkəsi/", definition: "a person’s belief that they can successfully perform a particular task", example: "Small achievements can strengthen a learner’s self-efficacy.", exampleTranslation: "يمكن للإنجازات الصغيرة أن تقوي الكفاءة الذاتية لدى المتعلم.", category: "psychology and behaviour", tags: ["psychology", "learning"], synonyms: ["perceived competence", "confidence in ability"] }),
      reviewed({ word: "attentional bias", translation: "انحياز الانتباه", pos: "noun", ipa: "/əˈtenʃənəl baɪəs/", definition: "the tendency to notice some kinds of information more readily than others", example: "Attentional bias can make threatening images seem more common than they are.", exampleTranslation: "يمكن لانحياز الانتباه أن يجعل الصور المهددة تبدو أكثر شيوعًا مما هي عليه.", category: "psychology and behaviour", tags: ["psychology", "thinking"], synonyms: ["selective attention", "attention bias"] }),
      reviewed({ word: "delayed gratification", translation: "تأجيل الإشباع", pos: "noun", ipa: "/dɪˌleɪd ˌɡrætɪfɪˈkeɪʃən/", definition: "the ability to wait for a greater future benefit instead of choosing an immediate reward", example: "Saving regularly requires delayed gratification and a clear goal.", exampleTranslation: "يتطلب الادخار المنتظم تأجيل الإشباع ووجود هدف واضح.", category: "psychology and behaviour", tags: ["psychology", "decisions"], synonyms: ["deferred reward", "self-control"] }),
    ],
  },
  C1: {
    u47: [
      reviewed({ word: "literature review", translation: "مراجعة الأدبيات", pos: "noun", ipa: "/ˈlɪtərətʃər rɪˌvjuː/", definition: "a critical survey of existing research on a particular question", example: "The literature review revealed a gap that the new study aims to address.", exampleTranslation: "كشفت مراجعة الأدبيات فجوة تسعى الدراسة الجديدة إلى معالجتها.", category: "academic writing", tags: ["research", "writing"], synonyms: ["research review", "scholarly survey"] }),
      reviewed({ word: "research question", translation: "سؤال بحثي", pos: "noun", ipa: "/rɪˈsɜːrtʃ ˌkwestʃən/", definition: "a focused question that a study is designed to investigate", example: "A precise research question keeps the project within a manageable scope.", exampleTranslation: "يحافظ السؤال البحثي الدقيق على نطاق المشروع ضمن حدود يمكن إدارتها.", category: "academic writing", tags: ["research", "planning"], synonyms: ["study question", "research problem"] }),
      reviewed({ word: "theoretical framework", translation: "إطار نظري", pos: "noun", ipa: "/ˌθiːəˈretɪkəl ˈfreɪmwɜːrk/", definition: "the set of concepts used to interpret and organise a study", example: "The theoretical framework links the observations to wider debates in the field.", exampleTranslation: "يربط الإطار النظري الملاحظات بالنقاشات الأوسع في المجال.", category: "academic writing", tags: ["research", "theory"], synonyms: ["conceptual framework", "theoretical model"] }),
      reviewed({ word: "methodological rigour", translation: "صرامة منهجية", pos: "noun", ipa: "/ˌmeθədəˈlɑːdʒɪkəl ˈrɪɡər/", definition: "the care and precision with which a study is designed and carried out", example: "The paper’s conclusions are persuasive because of its methodological rigour.", exampleTranslation: "تبدو استنتاجات البحث مقنعة بفضل صرامته المنهجية.", category: "academic writing", tags: ["research", "quality"], synonyms: ["methodological strictness", "research rigour"] }),
      reviewed({ word: "academic register", translation: "السجل الأكاديمي", pos: "noun", ipa: "/ˌækəˈdemɪk ˈredʒɪstər/", definition: "the vocabulary, grammar, and tone typical of formal scholarly communication", example: "The editor helped the author maintain an appropriate academic register.", exampleTranslation: "ساعد المحرر المؤلف على الحفاظ على سجل أكاديمي مناسب.", category: "academic writing", tags: ["writing", "register"], synonyms: ["scholarly style", "formal academic language"] }),
      reviewed({ word: "refereed article", translation: "مقال مُحكَّم", pos: "noun", ipa: "/rɪˈfɪərd ˈɑːrtɪkəl/", definition: "an academic article evaluated by specialists in the same field before publication", example: "The argument is supported by several refereed articles.", exampleTranslation: "تدعم الحجة عدة مقالات أكاديمية محكّمة.", category: "academic writing", tags: ["research", "evidence"], synonyms: ["peer-reviewed article", "scholarly article"] }),
      reviewed({ word: "epistemic stance", translation: "موقف معرفي", pos: "noun", ipa: "/ɪˈpɪstəmɪk stæns/", definition: "the way a writer signals certainty, doubt, or commitment to a claim", example: "The author’s epistemic stance becomes more cautious when the evidence is limited.", exampleTranslation: "يصبح موقف المؤلف المعرفي أكثر حذرًا عندما تكون الأدلة محدودة.", category: "academic writing", tags: ["writing", "argument"], synonyms: ["stance toward knowledge", "degree of certainty"] }),
      reviewed({ word: "quantify", translation: "يُكمّي / يحدد كميًا", pos: "verb", ipa: "/ˈkwɑːntɪfaɪ/", definition: "to express an amount or effect using numbers or measurable terms", example: "The researchers quantified wellbeing through several observable indicators.", exampleTranslation: "حدّد الباحثون الرفاه كميًا من خلال عدة مؤشرات قابلة للملاحظة.", category: "academic writing", tags: ["research", "measurement"], synonyms: ["measure", "express numerically"] }),
    ],
    u48: [
      reviewed({ word: "constitutional", translation: "دستوري", pos: "adjective", ipa: "/ˌkɑːnstəˈtuːʃənəl/", definition: "relating to the fundamental principles by which a state is governed", example: "The court considered whether the measure was constitutional.", exampleTranslation: "نظرت المحكمة فيما إذا كان الإجراء دستوريًا.", category: "law and rights", tags: ["law", "government"], synonyms: ["fundamental-law", "charter-based"] }),
      reviewed({ word: "injunction", translation: "أمر قضائي", pos: "noun", ipa: "/ɪnˈdʒʌŋkʃən/", definition: "a court order requiring someone to do or stop doing something", example: "The judge issued an injunction preventing the demolition until the case was heard.", exampleTranslation: "أصدر القاضي أمرًا قضائيًا يمنع الهدم حتى تُنظر القضية.", category: "law and rights", tags: ["law", "courts"], synonyms: ["court order", "restraining order"] }),
      reviewed({ word: "case law", translation: "السوابق القضائية", pos: "noun", ipa: "/ˈkeɪs lɔː/", definition: "law developed through decisions made by courts in earlier cases", example: "The lawyer relied on case law from several comparable disputes.", exampleTranslation: "اعتمد المحامي على السوابق القضائية في عدة نزاعات مماثلة.", category: "law and rights", tags: ["law", "courts"], synonyms: ["judicial precedent", "court decisions"] }),
      reviewed({ word: "legal standing", translation: "الصفة القانونية للتقاضي", pos: "noun", ipa: "/ˈliːɡəl ˈstændɪŋ/", definition: "the right to bring a legal action because one is sufficiently affected by the issue", example: "The organisation had legal standing to challenge the decision.", exampleTranslation: "كانت للمنظمة الصفة القانونية للطعن في القرار.", category: "law and rights", tags: ["law", "rights"], synonyms: ["right to sue", "standing to bring a case"] }),
      reviewed({ word: "judicial review", translation: "مراجعة قضائية", pos: "noun", ipa: "/dʒuːˈdɪʃəl rɪˌvjuː/", definition: "the examination by a court of whether a public decision was lawful", example: "The policy was challenged through judicial review.", exampleTranslation: "طُعن في السياسة من خلال مراجعة قضائية.", category: "law and rights", tags: ["law", "government"], synonyms: ["court review", "review of legality"] }),
      reviewed({ word: "burden of proof", translation: "عبء الإثبات", pos: "noun", ipa: "/ˌbɜːrdən əv ˈpruːf/", definition: "the duty to provide enough evidence to establish a claim", example: "In a civil case, the burden of proof generally rests with the claimant.", exampleTranslation: "يقع عبء الإثبات في القضية المدنية عمومًا على عاتق المدعي.", category: "law and rights", tags: ["law", "evidence"], synonyms: ["onus of proof", "evidential burden"] }),
      reviewed({ word: "non-discrimination", translation: "عدم التمييز", pos: "noun", ipa: "/ˌnɑːndɪˌskrɪməˈneɪʃən/", definition: "the principle that people should not receive unfair treatment because of identity or status", example: "The policy includes a clear commitment to non-discrimination.", exampleTranslation: "تتضمن السياسة التزامًا واضحًا بعدم التمييز.", category: "law and rights", tags: ["law", "equality"], synonyms: ["equal treatment", "freedom from discrimination"] }),
      reviewed({ word: "legal redress", translation: "إنصاف قانوني", pos: "noun", ipa: "/ˈliːɡəl rɪˈdres/", definition: "a legal solution or form of compensation for a wrong", example: "The claimant sought effective legal redress for the violation.", exampleTranslation: "سعى المدعي إلى إنصاف قانوني فعال للانتهاك.", category: "law and rights", tags: ["law", "rights"], synonyms: ["legal remedy", "relief"] }),
    ],
    u49: [
      reviewed({ word: "media framing", translation: "تأطير إعلامي", pos: "noun", ipa: "/ˈmiːdiə ˈfreɪmɪŋ/", definition: "the way media select and present aspects of an issue to shape interpretation", example: "Different media framing can make the same event appear either hopeful or threatening.", exampleTranslation: "يمكن للتأطير الإعلامي المختلف أن يجعل الحدث نفسه يبدو واعدًا أو مهددًا.", category: "media and public trust", tags: ["media", "rhetoric"], synonyms: ["news framing", "interpretive framing"] }),
      reviewed({ word: "editorial independence", translation: "استقلالية التحرير", pos: "noun", ipa: "/ˌedɪˈtɔːriəl ˌɪndɪˈpendəns/", definition: "the freedom of journalists and editors to make content decisions without improper pressure", example: "Public trust depends partly on visible editorial independence.", exampleTranslation: "تعتمد ثقة الجمهور جزئيًا على استقلالية التحرير الواضحة.", category: "media and public trust", tags: ["media", "ethics"], synonyms: ["editorial autonomy", "journalistic independence"] }),
      reviewed({ word: "public broadcaster", translation: "هيئة بث عامة", pos: "noun", ipa: "/ˈpʌblɪk ˈbrɔːdkæstər/", definition: "a broadcaster established to provide services for the public rather than to maximise private profit", example: "The public broadcaster explained how it verifies election information.", exampleTranslation: "شرحت هيئة البث العامة كيف تتحقق من معلومات الانتخابات.", category: "media and public trust", tags: ["media", "society"], synonyms: ["public-service broadcaster", "state-funded broadcaster"] }),
      reviewed({ word: "fact-checking", translation: "تدقيق الحقائق", pos: "noun", ipa: "/ˈfækt ˌtʃekɪŋ/", definition: "the process of testing public claims against reliable evidence", example: "Independent fact-checking can correct a false claim before it spreads widely.", exampleTranslation: "يمكن لتدقيق الحقائق المستقل أن يصحح الادعاء الكاذب قبل انتشاره على نطاق واسع.", category: "media and public trust", tags: ["media", "evidence"], synonyms: ["claim verification", "accuracy checking"] }),
      reviewed({ word: "agenda-setting", translation: "تحديد الأجندة الإعلامية", pos: "noun", ipa: "/əˈdʒendə ˌsetɪŋ/", definition: "the influence of media attention on which issues the public considers important", example: "Agenda-setting can elevate a local issue into a national debate.", exampleTranslation: "يمكن لتحديد الأجندة الإعلامية أن يرفع قضية محلية إلى نقاش وطني.", category: "media and public trust", tags: ["media", "society"], synonyms: ["issue prioritisation", "news agenda formation"] }),
      reviewed({ word: "filter bubble", translation: "فقاعة التصفية", pos: "noun", ipa: "/ˈfɪltər ˌbʌbəl/", definition: "an information environment shaped by personalised systems that limit exposure to different views", example: "A filter bubble may make a narrow political feed feel like a complete picture.", exampleTranslation: "قد تجعل فقاعة التصفية الموجز السياسي الضيق يبدو كأنه صورة كاملة.", category: "media and public trust", tags: ["media", "technology"], synonyms: ["personalised information bubble", "algorithmic bubble"] }),
      reviewed({ word: "echo chamber", translation: "غرفة صدى", pos: "noun", ipa: "/ˈekoʊ ˌtʃeɪmbər/", definition: "an environment where people mainly encounter opinions that repeat and reinforce their own", example: "An echo chamber can intensify certainty without improving the quality of evidence.", exampleTranslation: "قد تزيد غرفة الصدى اليقين من دون تحسين جودة الأدلة.", category: "media and public trust", tags: ["media", "society"], synonyms: ["closed opinion loop", "reinforcing information space"] }),
      reviewed({ word: "source triangulation", translation: "تثليث المصادر", pos: "noun", ipa: "/sɔːrs traɪˌæŋɡjəˈleɪʃən/", definition: "the practice of comparing several independent sources to strengthen verification", example: "Source triangulation reduced the risk of repeating an unverified report.", exampleTranslation: "قلل تثليث المصادر خطر تكرار تقرير غير متحقق منه.", category: "media and public trust", tags: ["media", "research"], synonyms: ["cross-source verification", "independent source comparison"] }),
    ],
  },
};
