import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/** Reviewed vocabulary for the six existing B1/B2/C1 u16 and u17 units. */
export const ENGLISH_B1_B2_C1_U16_U17_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u16: [
      reviewed({ word: "school curriculum", translation: "منهج دراسي", pos: "noun", ipa: "/skuːl kəˈrɪkjələm/", definition: "the subjects and learning content taught in a school", example: "The school curriculum includes practical science and creative writing.", exampleTranslation: "يتضمن المنهج الدراسي العلوم التطبيقية والكتابة الإبداعية.", category: "education and learning", tags: ["education", "curriculum"], synonyms: ["school programme", "educational curriculum"] }),
      reviewed({ word: "academic guidance", translation: "توجيه أكاديمي", pos: "noun", ipa: "/ˌækəˈdemɪk ˈɡaɪdəns/", definition: "advice that helps a student choose courses or plan their education", example: "Students can receive academic guidance before selecting their subjects.", exampleTranslation: "يمكن للطلاب تلقي توجيه أكاديمي قبل اختيار موادهم.", category: "education and learning", tags: ["education", "support"], synonyms: ["academic advice", "study guidance"] }),
      reviewed({ word: "classroom participation", translation: "مشاركة صفية", pos: "noun", ipa: "/ˈklæsruːm pɑːrˌtɪsəˈpeɪʃən/", definition: "the act of taking part in discussions and activities during a lesson", example: "Classroom participation helps learners practise explaining their ideas.", exampleTranslation: "تساعد المشاركة الصفية المتعلمين على التدرب على شرح أفكارهم.", category: "education and learning", tags: ["education", "communication"], synonyms: ["class participation", "lesson involvement"] }),
      reviewed({ word: "vocational pathway", translation: "مسار مهني", pos: "noun", ipa: "/voʊˈkeɪʃənəl ˈpæθweɪ/", definition: "a course of education and training leading to a particular occupation", example: "A vocational pathway can prepare learners for skilled technical work.", exampleTranslation: "يمكن للمسار المهني إعداد المتعلمين للعمل التقني الماهر.", category: "education and learning", tags: ["education", "careers"], synonyms: ["career pathway", "vocational route"] }),
      reviewed({ word: "teacher training", translation: "تدريب المعلمين", pos: "noun", ipa: "/ˈtiːtʃər ˌtreɪnɪŋ/", definition: "education and practice that prepare people to teach effectively", example: "Regular teacher training can improve the quality of classroom feedback.", exampleTranslation: "يمكن لتدريب المعلمين المنتظم أن يحسن جودة الملاحظات الصفية.", category: "education and learning", tags: ["education", "teaching"], synonyms: ["teacher education", "teaching development"] }),
      reviewed({ word: "educational inequality", translation: "عدم المساواة التعليمية", pos: "noun", ipa: "/ˌedʒəˈkeɪʃənəl ˌɪnɪˈkwɑːləti/", definition: "unequal access to educational opportunities or outcomes", example: "Affordable internet access may reduce educational inequality.", exampleTranslation: "قد يقلل الوصول الميسور إلى الإنترنت من عدم المساواة التعليمية.", category: "education and learning", tags: ["education", "society"], synonyms: ["education gap", "inequality in education"] }),
      reviewed({ word: "student assessment", translation: "تقييم الطلاب", pos: "noun", ipa: "/ˈstuːdənt əˌsesmənt/", definition: "the process of measuring a learner’s knowledge, progress, or skills", example: "Student assessment should measure understanding rather than memorisation alone.", exampleTranslation: "ينبغي لتقييم الطلاب أن يقيس الفهم لا الحفظ وحده.", category: "education and learning", tags: ["education", "assessment"], synonyms: ["learner assessment", "student evaluation"] }),
      reviewed({ word: "learning strategy", translation: "استراتيجية تعلم", pos: "noun", ipa: "/ˈlɜːrnɪŋ ˌstrætədʒi/", definition: "a planned method for learning information or developing a skill", example: "Spaced review is an effective learning strategy for vocabulary.", exampleTranslation: "تعد المراجعة المتباعدة استراتيجية تعلم فعالة للمفردات.", category: "education and learning", tags: ["education", "learning"], synonyms: ["study strategy", "learning method"] }),
    ],
    u17: [
      reviewed({ word: "delegation of tasks", translation: "تفويض المهام", pos: "noun", ipa: "/ˌdeləˈɡeɪʃən əv tæsks/", definition: "the act of giving particular responsibilities to different people", example: "Clear delegation of tasks helped the team finish the event on time.", exampleTranslation: "ساعد تفويض المهام بوضوح الفريق على إنهاء الفعالية في موعدها.", category: "workplace and team", tags: ["work", "teamwork"], synonyms: ["task delegation", "allocation of duties"] }),
      reviewed({ word: "collaborative leadership", translation: "قيادة تعاونية", pos: "noun", ipa: "/kəˈlæbərətɪv ˈliːdərʃɪp/", definition: "a style of leadership that involves people in decisions and shared work", example: "Collaborative leadership gives team members more responsibility for results.", exampleTranslation: "تمنح القيادة التعاونية أعضاء الفريق مسؤولية أكبر عن النتائج.", category: "workplace and team", tags: ["work", "leadership"], synonyms: ["shared leadership", "participatory leadership"] }),
      reviewed({ word: "team cohesion", translation: "تماسك الفريق", pos: "noun", ipa: "/tiːm koʊˈhiːʒən/", definition: "the degree to which members of a team trust and support one another", example: "Regular informal meetings strengthened team cohesion.", exampleTranslation: "عززت الاجتماعات غير الرسمية المنتظمة تماسك الفريق.", category: "workplace and team", tags: ["work", "teamwork"], synonyms: ["team unity", "group cohesion"] }),
      reviewed({ word: "feedback culture", translation: "ثقافة الملاحظات", pos: "noun", ipa: "/ˈfiːdbæk ˌkʌltʃər/", definition: "a workplace habit of giving and receiving useful comments openly", example: "A healthy feedback culture helps employees improve without fear.", exampleTranslation: "تساعد ثقافة الملاحظات الصحية الموظفين على التحسن دون خوف.", category: "workplace and team", tags: ["work", "communication"], synonyms: ["feedback environment", "culture of feedback"] }),
      reviewed({ word: "workplace responsibility", translation: "مسؤولية في مكان العمل", pos: "noun", ipa: "/ˈwɜːrkpleɪs rɪˌspɑːnsəˈbɪləti/", definition: "a duty that an employee is expected to carry out at work", example: "Each person understood their workplace responsibility before the project began.", exampleTranslation: "فهم كل شخص مسؤوليته في مكان العمل قبل بدء المشروع.", category: "workplace and team", tags: ["work", "responsibility"], synonyms: ["professional duty", "work responsibility"] }),
      reviewed({ word: "meeting objective", translation: "هدف الاجتماع", pos: "noun", ipa: "/ˈmiːtɪŋ əbˈdʒektɪv/", definition: "the result or purpose that a meeting is intended to achieve", example: "The chair stated the meeting objective before the discussion started.", exampleTranslation: "ذكر رئيس الاجتماع هدف الاجتماع قبل بدء النقاش.", category: "workplace and team", tags: ["work", "meetings"], synonyms: ["meeting goal", "discussion objective"] }),
      reviewed({ word: "task ownership", translation: "تحمل مسؤولية المهمة", pos: "noun", ipa: "/tɑːsk ˈoʊnərʃɪp/", definition: "clear responsibility for completing and following up a particular task", example: "Task ownership prevented important details from being forgotten.", exampleTranslation: "منع تحمل مسؤولية المهمة نسيان التفاصيل المهمة.", category: "workplace and team", tags: ["work", "responsibility"], synonyms: ["task responsibility", "ownership of duties"] }),
      reviewed({ word: "peer collaboration", translation: "تعاون بين الزملاء", pos: "noun", ipa: "/pɪr kəˌlæbəˈreɪʃən/", definition: "cooperation between people who have a similar role or level of experience", example: "Peer collaboration helped the new employees learn the process quickly.", exampleTranslation: "ساعد التعاون بين الزملاء الموظفين الجدد على تعلم العملية بسرعة.", category: "workplace and team", tags: ["work", "teamwork"], synonyms: ["colleague collaboration", "peer teamwork"] }),
    ],
  },
  B2: {
    u16: [
      reviewed({ word: "laboratory finding", translation: "نتيجة مخبرية", pos: "noun", ipa: "/ˈlæbrətɔːri ˈfaɪndɪŋ/", definition: "a result or observation obtained during laboratory research", example: "The laboratory finding requires confirmation in a larger study.", exampleTranslation: "تتطلب النتيجة المخبرية تأكيدًا في دراسة أكبر.", category: "science and research", tags: ["science", "research"], synonyms: ["lab result", "research finding"] }),
      reviewed({ word: "technical innovation", translation: "ابتكار تقني", pos: "noun", ipa: "/ˈteknɪkəl ˌɪnəˈveɪʃən/", definition: "a new technical idea or method that improves a process or product", example: "The technical innovation reduced the time needed to analyse samples.", exampleTranslation: "قلل الابتكار التقني الوقت اللازم لتحليل العينات.", category: "science and research", tags: ["science", "technology"], synonyms: ["technological innovation", "technical advance"] }),
      reviewed({ word: "evidence-based practice", translation: "ممارسة قائمة على الأدلة", pos: "noun", ipa: "/ˈevɪdəns beɪst ˈpræktɪs/", definition: "a professional method based on reliable research and observed results", example: "Evidence-based practice helps clinics choose effective treatments.", exampleTranslation: "تساعد الممارسة القائمة على الأدلة العيادات على اختيار علاجات فعالة.", category: "science and research", tags: ["research", "evidence"], synonyms: ["research-informed practice", "evidence-informed practice"] }),
      reviewed({ word: "research institution", translation: "مؤسسة بحثية", pos: "noun", ipa: "/rɪˈsɜːrtʃ ˌɪnstəˈtuːʃən/", definition: "an organisation whose main work includes conducting and supporting research", example: "The research institution opened a centre for renewable materials.", exampleTranslation: "افتتحت المؤسسة البحثية مركزًا للمواد المتجددة.", category: "science and research", tags: ["research", "institutions"], synonyms: ["research organisation", "scientific institution"] }),
      reviewed({ word: "experimental result", translation: "نتيجة تجريبية", pos: "noun", ipa: "/ɪkˌsperɪˈmentəl rɪˈzʌlt/", definition: "a result produced by a controlled test or experiment", example: "The experimental result supported the original prediction only partly.", exampleTranslation: "دعمت النتيجة التجريبية التوقع الأصلي جزئيًا فقط.", category: "science and research", tags: ["research", "experiments"], synonyms: ["test result", "experimental finding"] }),
      reviewed({ word: "scientific consensus", translation: "إجماع علمي", pos: "noun", ipa: "/ˌsaɪənˈtɪfɪk kənˈsensəs/", definition: "a broad agreement among experts based on the available evidence", example: "Scientific consensus can change when strong new evidence appears.", exampleTranslation: "يمكن أن يتغير الإجماع العلمي عندما تظهر أدلة جديدة قوية.", category: "science and research", tags: ["science", "evidence"], synonyms: ["expert consensus", "research consensus"] }),
      reviewed({ word: "scientific observation", translation: "ملاحظة علمية", pos: "noun", ipa: "/ˌsaɪənˈtɪfɪk ˌɑːbzərˈveɪʃən/", definition: "information carefully noticed and recorded during scientific study", example: "The researcher recorded each scientific observation in a shared log.", exampleTranslation: "سجل الباحث كل ملاحظة علمية في سجل مشترك.", category: "science and research", tags: ["science", "research"], synonyms: ["research observation", "observational record"] }),
      reviewed({ word: "reproducible methodology", translation: "منهجية قابلة لإعادة التطبيق", pos: "noun", ipa: "/ˌriːprəˈduːsəbəl ˌmeθəˈdɑːlədʒi/", definition: "a research method described clearly enough for others to apply it again", example: "A reproducible methodology makes the study easier to evaluate.", exampleTranslation: "تجعل المنهجية القابلة لإعادة التطبيق تقييم الدراسة أسهل.", category: "science and research", tags: ["research", "quality"], synonyms: ["repeatable methodology", "replicable method"] }),
    ],
    u17: [
      reviewed({ word: "trade agreement", translation: "اتفاقية تجارية", pos: "noun", ipa: "/treɪd əˈɡriːmənt/", definition: "a formal arrangement that sets rules for trade between countries or organisations", example: "The trade agreement removed tariffs on several agricultural products.", exampleTranslation: "ألغت الاتفاقية التجارية الرسوم على عدة منتجات زراعية.", category: "globalization and trade", tags: ["trade", "policy"], synonyms: ["commercial agreement", "trade pact"] }),
      reviewed({ word: "cross-border investment", translation: "استثمار عابر للحدود", pos: "noun", ipa: "/ˌkrɔːs ˈbɔːrdər ɪnˈvestmənt/", definition: "investment made in a business or project located in another country", example: "Cross-border investment can create jobs but may also increase dependence.", exampleTranslation: "يمكن للاستثمار العابر للحدود خلق وظائف لكنه قد يزيد الاعتماد.", category: "globalization and trade", tags: ["trade", "finance"], synonyms: ["international investment", "foreign investment"] }),
      reviewed({ word: "export market", translation: "سوق التصدير", pos: "noun", ipa: "/ˈekspɔːrt ˌmɑːrkɪt/", definition: "a foreign market where a country or company sells its goods", example: "The company entered a new export market in Southeast Asia.", exampleTranslation: "دخلت الشركة سوق تصدير جديدًا في جنوب شرق آسيا.", category: "globalization and trade", tags: ["trade", "business"], synonyms: ["foreign market", "international market"] }),
      reviewed({ word: "economic integration", translation: "تكامل اقتصادي", pos: "noun", ipa: "/ˌiːkəˈnɑːmɪk ˌɪntəˈɡreɪʃən/", definition: "the process of making economies work more closely through shared rules or institutions", example: "Economic integration has increased trade between neighbouring countries.", exampleTranslation: "زاد التكامل الاقتصادي التجارة بين الدول المتجاورة.", category: "globalization and trade", tags: ["trade", "economy"], synonyms: ["economic cooperation", "market integration"] }),
      reviewed({ word: "trade barrier", translation: "حاجز تجاري", pos: "noun", ipa: "/treɪd ˈbæriər/", definition: "a rule, tax, or restriction that makes international trade more difficult", example: "A trade barrier can protect local producers but raise prices for consumers.", exampleTranslation: "يمكن للحاجز التجاري حماية المنتجين المحليين لكنه يرفع الأسعار على المستهلكين.", category: "globalization and trade", tags: ["trade", "policy"], synonyms: ["trade restriction", "commercial barrier"] }),
      reviewed({ word: "commercial partner", translation: "شريك تجاري", pos: "noun", ipa: "/kəˈmɜːrʃəl ˈpɑːrtnər/", definition: "a company or organisation that works with another in business", example: "The firm selected a reliable commercial partner for distribution.", exampleTranslation: "اختارت الشركة شريكًا تجاريًا موثوقًا للتوزيع.", category: "globalization and trade", tags: ["trade", "business"], synonyms: ["business partner", "trade partner"] }),
      reviewed({ word: "logistics network", translation: "شبكة لوجستية", pos: "noun", ipa: "/ləˈdʒɪstɪks ˈnetwɜːrk/", definition: "the connected system used to move goods from producers to customers", example: "A resilient logistics network can respond quickly to a port closure.", exampleTranslation: "يمكن لشبكة لوجستية مرنة أن تستجيب سريعًا لإغلاق ميناء.", category: "globalization and trade", tags: ["trade", "transport"], synonyms: ["distribution network", "supply network"] }),
      reviewed({ word: "global competition", translation: "منافسة عالمية", pos: "noun", ipa: "/ˈɡloʊbəl ˌkɑːmpəˈtɪʃən/", definition: "competition between businesses or economies operating in different countries", example: "Global competition encourages firms to improve quality and efficiency.", exampleTranslation: "تشجع المنافسة العالمية الشركات على تحسين الجودة والكفاءة.", category: "globalization and trade", tags: ["trade", "business"], synonyms: ["international competition", "worldwide competition"] }),
    ],
  },
  C1: {
    u16: [
      reviewed({ word: "judicial reasoning", translation: "استدلال قضائي", pos: "noun", ipa: "/dʒuːˈdɪʃəl ˈriːzənɪŋ/", definition: "the logical process a court uses to explain a legal decision", example: "The judgement sets out the judicial reasoning behind the ruling.", exampleTranslation: "يوضح الحكم الاستدلال القضائي وراء القرار.", category: "justice and law", tags: ["law", "analysis"], synonyms: ["legal reasoning", "judicial analysis"] }),
      reviewed({ word: "court procedure", translation: "إجراءات المحكمة", pos: "noun", ipa: "/kɔːrt prəˈsiːdʒər/", definition: "the formal process and rules followed in a court case", example: "The lawyer explained the court procedure to the witness.", exampleTranslation: "شرح المحامي إجراءات المحكمة للشاهد.", category: "justice and law", tags: ["law", "courts"], synonyms: ["legal procedure", "court process"] }),
      reviewed({ word: "sentencing principle", translation: "مبدأ إصدار الحكم", pos: "noun", ipa: "/ˈsentənsɪŋ ˈprɪnsəpəl/", definition: "a rule or consideration used when deciding a legal punishment", example: "Proportionality is an important sentencing principle.", exampleTranslation: "تعد التناسبية مبدأً مهمًا في إصدار الحكم.", category: "justice and law", tags: ["law", "sentencing"], synonyms: ["sentencing rule", "punishment principle"] }),
      reviewed({ word: "access to justice", translation: "الوصول إلى العدالة", pos: "noun", ipa: "/ˈækses tə ˈdʒʌstɪs/", definition: "the ability to obtain legal advice, fair procedures, and an effective remedy", example: "Legal aid can improve access to justice for low-income families.", exampleTranslation: "يمكن للمساعدة القانونية تحسين الوصول إلى العدالة للأسر منخفضة الدخل.", category: "justice and law", tags: ["law", "rights"], synonyms: ["access to legal remedies", "justice accessibility"] }),
      reviewed({ word: "evidentiary assessment", translation: "تقييم الأدلة", pos: "noun", ipa: "/ˌevɪˈdenʃəri əˈsesmənt/", definition: "the careful evaluation of the reliability and relevance of evidence", example: "The judge’s evidentiary assessment considered both the testimony and the documents.", exampleTranslation: "راعى تقييم القاضي للأدلة الشهادة والوثائق معًا.", category: "justice and law", tags: ["law", "evidence"], synonyms: ["evidence assessment", "evaluation of evidence"] }),
      reviewed({ word: "constitutional interpretation", translation: "تفسير دستوري", pos: "noun", ipa: "/ˌkɑːnstəˈtuːʃənəl ɪnˌtɜːrprəˈteɪʃən/", definition: "the process of explaining what the principles and wording of a constitution mean", example: "The case raised a difficult question of constitutional interpretation.", exampleTranslation: "أثارت القضية سؤالًا صعبًا يتعلق بالتفسير الدستوري.", category: "justice and law", tags: ["law", "constitution"], synonyms: ["constitutional analysis", "interpretation of the constitution"] }),
      reviewed({ word: "legal remedy", translation: "انتصاف قانوني", pos: "noun", ipa: "/ˈliːɡəl ˈremədi/", definition: "a legal solution or form of relief available to a person whose rights were harmed", example: "The court considered whether compensation was an adequate legal remedy.", exampleTranslation: "نظرت المحكمة فيما إذا كان التعويض انتصافًا قانونيًا كافيًا.", category: "justice and law", tags: ["law", "rights"], synonyms: ["legal relief", "judicial remedy"] }),
      reviewed({ word: "judicial impartiality", translation: "حياد قضائي", pos: "noun", ipa: "/dʒuːˈdɪʃəl ˌɪmpɑːrʃiˈæləti/", definition: "the quality of deciding a case fairly without favouring either side", example: "Public confidence depends on judicial impartiality.", exampleTranslation: "تعتمد ثقة الجمهور على الحياد القضائي.", category: "justice and law", tags: ["law", "courts"], synonyms: ["judicial neutrality", "impartial judging"] }),
    ],
    u17: [
      reviewed({ word: "moral responsibility", translation: "مسؤولية أخلاقية", pos: "noun", ipa: "/ˈmɔːrəl rɪˌspɑːnsəˈbɪləti/", definition: "the duty to answer for the moral consequences of one’s actions", example: "The debate asks whether institutions have a moral responsibility to future generations.", exampleTranslation: "يسأل النقاش عما إذا كانت المؤسسات تتحمل مسؤولية أخلاقية تجاه الأجيال القادمة.", category: "ethics and morality", tags: ["ethics", "responsibility"], synonyms: ["ethical responsibility", "moral accountability"] }),
      reviewed({ word: "ethical conduct", translation: "سلوك أخلاقي", pos: "noun", ipa: "/ˈeθɪkəl ˈkɑːndʌkt/", definition: "behaviour that follows accepted moral principles", example: "The professional code sets standards for ethical conduct.", exampleTranslation: "يضع المدونة المهنية معايير للسلوك الأخلاقي.", category: "ethics and morality", tags: ["ethics", "behaviour"], synonyms: ["ethical behaviour", "moral conduct"] }),
      reviewed({ word: "principled action", translation: "تصرف قائم على مبدأ", pos: "noun", ipa: "/ˈprɪnsəpəld ˈækʃən/", definition: "an action guided by a clear moral or political principle", example: "Refusing the unfair request was a principled action.", exampleTranslation: "كان رفض الطلب غير العادل تصرفًا قائمًا على مبدأ.", category: "ethics and morality", tags: ["ethics", "decision-making"], synonyms: ["principled behaviour", "morally guided action"] }),
      reviewed({ word: "normative conflict", translation: "تعارض معياري", pos: "noun", ipa: "/ˈnɔːrmətɪv ˈkɑːnflɪkt/", definition: "a disagreement between different ideas about what ought to be done", example: "The policy creates a normative conflict between equality and individual choice.", exampleTranslation: "تخلق السياسة تعارضًا معياريًا بين المساواة والاختيار الفردي.", category: "ethics and morality", tags: ["ethics", "philosophy"], synonyms: ["moral conflict", "conflict of norms"] }),
      reviewed({ word: "ethical reflection", translation: "تأمل أخلاقي", pos: "noun", ipa: "/ˈeθɪkəl rɪˈflekʃən/", definition: "careful thought about the moral meaning of an action or decision", example: "Ethical reflection is necessary when every available option has costs.", exampleTranslation: "يصبح التأمل الأخلاقي ضروريًا عندما تكون لكل الخيارات المتاحة تكاليف.", category: "ethics and morality", tags: ["ethics", "reasoning"], synonyms: ["moral reflection", "ethical consideration"] }),
      reviewed({ word: "moral evaluation", translation: "تقييم أخلاقي", pos: "noun", ipa: "/ˈmɔːrəl ɪˌvæljuˈeɪʃən/", definition: "an assessment of whether an action, policy, or character is morally acceptable", example: "The essay separates factual description from moral evaluation.", exampleTranslation: "تفصل المقالة بين الوصف الواقعي والتقييم الأخلاقي.", category: "ethics and morality", tags: ["ethics", "analysis"], synonyms: ["ethical evaluation", "moral assessment"] }),
      reviewed({ word: "duty of care", translation: "واجب الرعاية", pos: "noun", ipa: "/ˌdjuːti əv ˈker/", definition: "a responsibility to take reasonable steps to protect another person from harm", example: "The organisation has a duty of care towards its employees.", exampleTranslation: "تتحمل المنظمة واجب الرعاية تجاه موظفيها.", category: "ethics and morality", tags: ["ethics", "responsibility"], synonyms: ["care obligation", "protective duty"] }),
      reviewed({ word: "moral uncertainty", translation: "عدم يقين أخلاقي", pos: "noun", ipa: "/ˈmɔːrəl ʌnˈsɜːrtənti/", definition: "uncertainty about which action is morally right in a difficult situation", example: "Moral uncertainty can make public decisions slower but more careful.", exampleTranslation: "يمكن لعدم اليقين الأخلاقي أن يجعل القرارات العامة أبطأ لكنها أكثر حذرًا.", category: "ethics and morality", tags: ["ethics", "decision-making"], synonyms: ["ethical uncertainty", "moral doubt"] }),
    ],
  },
};
