// Professional English enrichment units u46-u47 for every CEFR level.
// Finnish curriculum is intentionally untouched. APIs may enrich these records later,
// but they never generate the local curriculum.
import type { ReadingText, VocabularyItem } from "./learn-data";

type PhraseSpec = { phrase: string; translation: string };
type LineSpec = { speaker: string; text: string; translation: string };
type UnitSeed = { id: string; title: string; description: string; words: VocabularyItem[]; phrases: PhraseSpec[]; dialogue: LineSpec[]; reading: ReadingText & { title: string } };

const w = (word: string, translation: string, pos: string, ipa: string, definition: string, example: string, exampleTranslation: string, synonyms: string[], antonyms: string[], collocations: string[], wordFamily: string[], tags: string[], category: string): VocabularyItem => ({ word, translation, pos, ipa, definition, example, exampleTranslation, synonyms, antonyms, collocations, wordFamily, tags, category });
const u = (id: string, title: string, description: string, words: VocabularyItem[], phrases: PhraseSpec[], dialogue: LineSpec[], reading: ReadingText & { title: string }): UnitSeed => ({ id, title, description, words, phrases, dialogue, reading });

export const ADDITIONAL_EN_PART12_UNITS: Record<string, UnitSeed[]> = {
  A0: [
    u("u46", "Morning and Evening", "Talk about simple daily actions and parts of the day.", [
      w("morning", "mañana", "noun", "/ˈmɔːrnɪŋ/", "the early part of the day", "I drink water in the morning.", "Bebo agua por la mañana.", ["early day"], ["evening"], ["good morning", "morning walk"], ["morning"], ["time", "routine"], "time"),
      w("evening", "tarde-noche", "noun", "/ˈiːvnɪŋ/", "the part of the day before night", "We eat together in the evening.", "Comemos juntos por la tarde-noche.", ["nightfall"], ["morning"], ["this evening", "evening meal"], ["evening"], ["time", "routine"], "time"),
      w("today", "hoy", "adverb", "/təˈdeɪ/", "on this day", "Today is a sunny day.", "Hoy es un día soleado.", ["this day"], ["yesterday"], ["today's lesson", "later today"], ["today"], ["time", "daily life"], "time"),
      w("tomorrow", "mañana", "adverb", "/təˈmɑːroʊ/", "on the day after today", "Tomorrow is my birthday.", "Mañana es mi cumpleaños.", ["the next day"], ["yesterday"], ["see you tomorrow", "tomorrow morning"], ["tomorrow"], ["time", "planning"], "time"),
      w("yesterday", "ayer", "adverb", "/ˈjestərdeɪ/", "on the day before today", "Yesterday was very busy.", "Ayer fue muy ajetreado.", ["the day before"], ["tomorrow"], ["yesterday afternoon", "since yesterday"], ["yesterday"], ["time", "daily life"], "time"),
      w("wake", "despertarse", "verb", "/weɪk/", "to stop sleeping", "I wake at seven.", "Me despierto a las siete.", ["awaken", "get up"], ["sleep"], ["wake early", "wake suddenly"], ["wake, awake, waking"], ["routine", "time"], "daily action"),
      w("wash", "lavarse", "verb", "/wɑːʃ/", "to clean with water", "I wash my hands before breakfast.", "Me lavo las manos antes del desayuno.", ["clean", "rinse"], ["soil"], ["wash your hands", "wash your face"], ["wash, washer, washing"], ["routine", "health"], "daily action"),
      w("dress", "vestirse", "verb", "/dres/", "to put clothes on your body", "I dress before I leave home.", "Me visto antes de salir de casa.", ["clothe", "get dressed"], ["undress"], ["dress quickly", "dress for school"], ["dress, dressed, dressing"], ["routine", "clothes"], "daily action"),
    ], [{ phrase: "Good morning!", translation: "¡Buenos días!" }, { phrase: "See you tomorrow.", translation: "Hasta mañana." }, { phrase: "I wash my hands.", translation: "Me lavo las manos." }, { phrase: "I get dressed at seven.", translation: "Me visto a las siete." }], [{ speaker: "A", text: "What do you do in the morning?", translation: "¿Qué haces por la mañana?" }, { speaker: "B", text: "I wake, wash, and get dressed.", translation: "Me despierto, me lavo y me visto." }, { speaker: "A", text: "What about the evening?", translation: "¿Y por la tarde-noche?" }, { speaker: "B", text: "I eat with my family.", translation: "Como con mi familia." }], { title: "A Simple Day", text: "Today I wake in the morning and wash my hands. I get dressed before breakfast. In the evening, I eat with my family and prepare for tomorrow.", translation: "Hoy me despierto por la mañana y me lavo las manos. Me visto antes del desayuno. Por la tarde-noche, como con mi familia y me preparo para mañana." }),
    u("u47", "Weather and Seasons", "Name common weather conditions and the four seasons.", [
      w("sunny", "soleado", "adjective", "/ˈsʌni/", "with a lot of bright sunlight", "It is sunny today.", "Hoy hace sol.", ["bright", "clear"], ["cloudy"], ["sunny day", "sunny weather"], ["sun, sunny, sunshine"], ["weather", "nature"], "weather"),
      w("rainy", "lluvioso", "adjective", "/ˈreɪni/", "with a lot of rain", "It is rainy in spring.", "Es lluvioso en primavera.", ["wet", "showery"], ["dry"], ["rainy day", "rainy season"], ["rain, rainy, rainfall"], ["weather", "seasons"], "weather"),
      w("snow", "nieve", "noun", "/snoʊ/", "soft white ice that falls from the sky", "The snow is clean and white.", "La nieve está limpia y blanca.", ["snowfall", "flakes"], ["heat"], ["fresh snow", "snow falls"], ["snow, snowy, snowfall"], ["weather", "nature"], "weather"),
      w("hot", "caliente", "adjective", "/hɑːt/", "having a high temperature", "The summer day is hot.", "El día de verano es caluroso.", ["warm", "heated"], ["cold"], ["hot weather", "hot day"], ["heat, hot, hotter"], ["weather", "temperature"], "weather"),
      w("cold", "frío", "adjective", "/koʊld/", "having a low temperature", "My hands are cold.", "Mis manos están frías.", ["chilly", "cool"], ["hot"], ["cold weather", "feel cold"], ["cold, colder, coldness"], ["weather", "body"], "weather"),
      w("spring", "primavera", "noun", "/sprɪŋ/", "the season after winter", "Flowers grow in spring.", "Las flores crecen en primavera.", ["springtime"], ["autumn"], ["early spring", "in spring"], ["spring, springtime"], ["seasons", "nature"], "season"),
      w("summer", "verano", "noun", "/ˈsʌmər/", "the warmest season of the year", "We swim in summer.", "Nadamos en verano.", ["summertime"], ["winter"], ["summer holiday", "in summer"], ["summer, summertime"], ["seasons", "leisure"], "season"),
      w("winter", "invierno", "noun", "/ˈwɪntər/", "the coldest season of the year", "It gets dark early in winter.", "Anochece temprano en invierno.", ["wintertime"], ["summer"], ["cold winter", "in winter"], ["winter, wintertime"], ["seasons", "weather"], "season"),
    ], [{ phrase: "What is the weather like?", translation: "¿Qué tiempo hace?" }, { phrase: "It is sunny today.", translation: "Hoy hace sol." }, { phrase: "Winter is cold.", translation: "El invierno es frío." }, { phrase: "I like warm summer days.", translation: "Me gustan los días cálidos de verano." }], [{ speaker: "A", text: "What season do you like?", translation: "¿Qué estación te gusta?" }, { speaker: "B", text: "I like summer because it is hot.", translation: "Me gusta el verano porque hace calor." }, { speaker: "A", text: "Is it sunny today?", translation: "¿Hace sol hoy?" }, { speaker: "B", text: "Yes, but snow is coming tomorrow.", translation: "Sí, pero mañana llegará nieve." }], { title: "Four Seasons", text: "Every season has different weather. Spring can be rainy, summer is often hot, and winter can bring snow. On a sunny autumn day, people enjoy walking outside.", translation: "Cada estación tiene un tiempo diferente. La primavera puede ser lluviosa, el verano suele ser caluroso y el invierno puede traer nieve. En un día soleado de otoño, las personas disfrutan caminando fuera." }),
  ],
  A1: [
    u("u46", "Directions", "Ask for and give simple directions around a town.", [
      w("map", "mapa", "noun", "/mæp/", "a drawing that shows places and roads", "Look at the map, please.", "Mira el mapa, por favor.", ["plan", "chart"], [], ["read a map", "street map"], ["map, mapping"], ["travel", "city"], "navigation"),
      w("corner", "esquina", "noun", "/ˈkɔːrnər/", "the place where two streets meet", "The shop is on the corner.", "La tienda está en la esquina.", ["street corner", "turning"], [], ["on the corner", "around the corner"], ["corner, cornered"], ["city", "directions"], "place"),
      w("straight", "recto", "adverb", "/streɪt/", "in a direct line without turning", "Go straight for two minutes.", "Sigue recto durante dos minutos.", ["directly", "ahead"], ["back"], ["go straight", "straight ahead"], ["straight, straighten"], ["directions", "movement"], "direction"),
      w("turn", "girar", "verb", "/tɜːrn/", "to move in a different direction", "Turn left at the bank.", "Gira a la izquierda en el banco.", ["change direction", "bend"], ["continue"], ["turn left", "turn right"], ["turn, turning, turnabout"], ["directions", "movement"], "movement"),
      w("left", "izquierda", "noun", "/left/", "the side opposite the right", "The museum is on the left.", "El museo está a la izquierda.", ["left-hand side"], ["right"], ["on the left", "turn left"], ["left, left-hand"], ["directions", "city"], "direction"),
      w("right", "derecha", "noun", "/raɪt/", "the side opposite the left", "Turn right after the bridge.", "Gira a la derecha después del puente.", ["right-hand side"], ["left"], ["on the right", "turn right"], ["right, right-hand"], ["directions", "city"], "direction"),
      w("bridge", "puente", "noun", "/brɪdʒ/", "a structure that lets people cross a river or road", "The bridge is near the station.", "El puente está cerca de la estación.", ["overpass", "crossing"], [], ["cross a bridge", "stone bridge"], ["bridge, bridging"], ["city", "travel"], "place"),
      w("entrance", "entrada", "noun", "/ˈentrəns/", "a place where people enter", "The entrance is beside the lift.", "La entrada está junto al ascensor.", ["entry", "doorway"], ["exit"], ["main entrance", "entrance to a building"], ["enter, entrance"], ["city", "buildings"], "place"),
    ], [{ phrase: "Could you show me on the map?", translation: "¿Podría mostrármelo en el mapa?" }, { phrase: "Go straight to the corner.", translation: "Sigue recto hasta la esquina." }, { phrase: "Turn right after the bridge.", translation: "Gira a la derecha después del puente." }, { phrase: "The entrance is on the left.", translation: "La entrada está a la izquierda." }], [{ speaker: "A", text: "Excuse me, where is the museum?", translation: "Disculpe, ¿dónde está el museo?" }, { speaker: "B", text: "Go straight and turn left at the corner.", translation: "Siga recto y gire a la izquierda en la esquina." }, { speaker: "A", text: "Is it near the bridge?", translation: "¿Está cerca del puente?" }, { speaker: "B", text: "Yes. The entrance is on the right.", translation: "Sí. La entrada está a la derecha." }], { title: "Finding a Place", text: "A map can make a town easier to understand. Walk straight, turn at a corner, and look for a bridge or a clear entrance. Simple direction words help visitors travel with confidence.", translation: "Un mapa puede hacer que una ciudad sea más fácil de entender. Camina recto, gira en una esquina y busca un puente o una entrada clara. Las palabras sencillas de dirección ayudan a los visitantes a viajar con confianza." }),
    u("u47", "Food Shopping", "Buy food, ask about quantities, and pay at a supermarket.", [
      w("basket", "cesta", "noun", "/ˈbæskɪt/", "a container used for carrying things", "Put the bread in the basket.", "Pon el pan en la cesta.", ["container", "hamper"], [], ["shopping basket", "carry a basket"], ["basket, basketwork"], ["shopping", "food"], "shopping"),
      w("packet", "paquete", "noun", "/ˈpækɪt/", "a small container or package", "I need a packet of rice.", "Necesito un paquete de arroz.", ["pack", "package"], [], ["packet of rice", "small packet"], ["pack, packet, packaging"], ["shopping", "food"], "container"),
      w("bottle", "botella", "noun", "/ˈbɑːtəl/", "a container for liquids", "Please buy a bottle of water.", "Compra una botella de agua, por favor.", ["container", "flask"], [], ["water bottle", "glass bottle"], ["bottle, bottled"], ["shopping", "food"], "container"),
      w("kilo", "kilo", "noun", "/ˈkiːloʊ/", "a unit of weight equal to one thousand grams", "I would like a kilo of apples.", "Quisiera un kilo de manzanas.", ["kilogram"], [], ["a kilo of fruit", "half a kilo"], ["kilo, kilogram"], ["shopping", "measurement"], "measurement"),
      w("cashier", "cajero", "noun", "/kæˈʃɪr/", "a person who takes payment in a shop", "The cashier gave me my change.", "El cajero me dio el cambio.", ["checkout worker", "teller"], [], ["ask the cashier", "friendly cashier"], ["cash, cashier"], ["shopping", "work"], "person"),
      w("supermarket", "supermercado", "noun", "/ˈsuːpərmɑːrkɪt/", "a large shop selling food and household goods", "The supermarket is open late.", "El supermercado abre hasta tarde.", ["grocery store", "market"], [], ["local supermarket", "supermarket aisle"], ["market, supermarket"], ["shopping", "city"], "place"),
      w("frozen", "congelado", "adjective", "/ˈfroʊzən/", "kept very cold so it becomes solid", "The frozen vegetables are cheap.", "Las verduras congeladas son baratas.", ["iced", "chilled"], ["fresh"], ["frozen food", "frozen vegetables"], ["freeze, frozen, freezing"], ["food", "shopping"], "food"),
      w("shelf", "estantería", "noun", "/ʃelf/", "a flat surface used for keeping things", "The cereal is on the top shelf.", "Los cereales están en la estantería de arriba.", ["rack", "ledge"], [], ["top shelf", "shop shelf"], ["shelf, shelving"], ["shopping", "home"], "furniture"),
    ], [{ phrase: "How much does this cost?", translation: "¿Cuánto cuesta esto?" }, { phrase: "I need a packet of rice.", translation: "Necesito un paquete de arroz." }, { phrase: "Please pay at the cashier.", translation: "Paga en la caja, por favor." }, { phrase: "The frozen food is on that shelf.", translation: "La comida congelada está en esa estantería." }], [{ speaker: "A", text: "Where can I find the rice?", translation: "¿Dónde puedo encontrar el arroz?" }, { speaker: "B", text: "It is on the middle shelf.", translation: "Está en la estantería del medio." }, { speaker: "A", text: "I also need a bottle of water.", translation: "También necesito una botella de agua." }, { speaker: "B", text: "You can pay at the cashier.", translation: "Puedes pagar en la caja." }], { title: "A Supermarket Visit", text: "At the supermarket, shoppers use a basket and choose packets, bottles, and fresh or frozen food. They check the shelf, take their shopping to the cashier, and pay before leaving.", translation: "En el supermercado, los compradores usan una cesta y eligen paquetes, botellas y comida fresca o congelada. Revisan la estantería, llevan la compra a la caja y pagan antes de salir." }),
  ],
  A2: [
    u("u46", "Personal Finance", "Discuss everyday banking, payments, and saving money.", [
      w("account", "cuenta", "noun", "/əˈkaʊnt/", "a record of money held by a bank or organisation", "I opened a new bank account.", "Abrí una nueva cuenta bancaria.", ["bank record", "profile"], [], ["bank account", "open an account"], ["account, accountant, accounting"], ["money", "banking"], "finance"),
      w("payment", "pago", "noun", "/ˈpeɪmənt/", "money given for something", "The payment was made online.", "El pago se hizo por internet.", ["fee", "settlement"], ["refund"], ["make a payment", "monthly payment"], ["pay, payment, payable"], ["money", "shopping"], "finance"),
      w("invoice", "factura", "noun", "/ˈɪnvɔɪs/", "a document showing what must be paid for goods or services", "The company sent an invoice.", "La empresa envió una factura.", ["bill", "statement"], [], ["send an invoice", "invoice number"], ["invoice, invoicing"], ["work", "money"], "document"),
      w("transfer", "transferencia", "noun", "/ˈtrænsfɜːr/", "an act of moving money from one account to another", "The transfer arrived this morning.", "La transferencia llegó esta mañana.", ["transaction", "movement"], [], ["bank transfer", "transfer money"], ["transfer, transferable"], ["money", "banking"], "finance"),
      w("balance", "saldo", "noun", "/ˈbæləns/", "the amount of money in an account", "Check your balance before you buy it.", "Comprueba tu saldo antes de comprarlo.", ["credit", "amount"], ["debt"], ["bank balance", "check the balance"], ["balance, balanced"], ["money", "banking"], "finance"),
      w("afford", "poder permitirse", "verb", "/əˈfɔːrd/", "to have enough money or time for something", "We cannot afford a larger flat.", "No podemos permitirnos un piso más grande.", ["manage", "pay for"], ["lack"], ["afford to buy", "cannot afford"], ["afford, affordable, affordability"], ["money", "housing"], "finance action"),
      w("charge", "cobrar", "verb", "/tʃɑːrdʒ/", "to ask someone to pay a particular amount", "The hotel charged us for breakfast.", "El hotel nos cobró el desayuno.", ["bill", "cost"], ["refund"], ["charge a fee", "charge a customer"], ["charge, charger, chargeable"], ["money", "services"], "finance action"),
      w("save", "ahorrar", "verb", "/seɪv/", "to keep money instead of spending it", "I save a little every month.", "Ahorro un poco cada mes.", ["put aside", "reserve"], ["spend"], ["save money", "save for a holiday"], ["save, saver, savings"], ["money", "planning"], "finance action"),
    ], [{ phrase: "I need to check my balance.", translation: "Necesito comprobar mi saldo." }, { phrase: "Can you send the invoice?", translation: "¿Puedes enviar la factura?" }, { phrase: "We cannot afford it yet.", translation: "Todavía no podemos permitírnoslo." }, { phrase: "I am saving for a holiday.", translation: "Estoy ahorrando para unas vacaciones." }], [{ speaker: "A", text: "Did you make the payment?", translation: "¿Hiciste el pago?" }, { speaker: "B", text: "Yes, I transferred the money this morning.", translation: "Sí, transferí el dinero esta mañana." }, { speaker: "A", text: "Can you afford the new laptop?", translation: "¿Puedes permitirte el portátil nuevo?" }, { speaker: "B", text: "Not yet. I am saving for it.", translation: "Todavía no. Estoy ahorrando para ello." }], { title: "Managing Money", text: "Good financial habits include checking a bank balance, paying invoices on time, and saving regularly. Before making a purchase, people consider whether they can afford it and whether an extra charge may apply.", translation: "Los buenos hábitos financieros incluyen comprobar el saldo bancario, pagar las facturas a tiempo y ahorrar con regularidad. Antes de hacer una compra, las personas consideran si pueden permitírsela y si puede aplicarse un cargo adicional." }),
    u("u47", "Communication and Plans", "Make arrangements, respond politely, and discuss changes to plans.", [
      w("invite", "invitar", "verb", "/ɪnˈvaɪt/", "to ask someone to come to an event or place", "I will invite my neighbours to dinner.", "Invitaré a mis vecinos a cenar.", ["ask", "welcome"], ["exclude"], ["invite someone to dinner", "invite a guest"], ["invite, invitation, invited"], ["social life", "communication"], "social action"),
      w("arrange", "organizar", "verb", "/əˈreɪndʒ/", "to plan or organise something", "We arranged a meeting for Friday.", "Organizamos una reunión para el viernes.", ["organise", "plan"], ["cancel"], ["arrange a meeting", "arrange transport"], ["arrange, arrangement"], ["planning", "work"], "planning action"),
      w("postpone", "posponer", "verb", "/poʊˈspoʊn/", "to move an event to a later time", "We had to postpone the match.", "Tuvimos que posponer el partido.", ["delay", "put off"], ["advance"], ["postpone a meeting", "postpone until Friday"], ["postpone, postponement"], ["planning", "time"], "planning action"),
      w("respond", "responder", "verb", "/rɪˈspɑːnd/", "to answer or react to something", "Please respond to my message.", "Responde a mi mensaje, por favor.", ["reply", "react"], ["ignore"], ["respond quickly", "respond to a request"], ["respond, response, responsive"], ["communication", "work"], "communication action"),
      w("mention", "mencionar", "verb", "/ˈmenʃən/", "to speak or write about something briefly", "She mentioned a change of plan.", "Mencionó un cambio de planes.", ["refer to", "note"], ["omit"], ["mention a name", "mention briefly"], ["mention, mentioned"], ["communication", "conversation"], "communication action"),
      w("suggest", "sugerir", "verb", "/səˈdʒest/", "to offer an idea for consideration", "I suggest meeting earlier.", "Sugiero reunirnos antes.", ["propose", "recommend"], ["reject"], ["suggest an idea", "suggest a solution"], ["suggest, suggestion, suggestive"], ["communication", "planning"], "communication action"),
      w("explain", "explicar", "verb", "/ɪkˈspleɪn/", "to make an idea clear to someone", "Could you explain the problem?", "¿Podrías explicar el problema?", ["clarify", "describe"], ["confuse"], ["explain clearly", "explain a reason"], ["explain, explanation, explanatory"], ["communication", "learning"], "communication action"),
      w("agree", "estar de acuerdo", "verb", "/əˈɡriː/", "to have the same opinion or accept a proposal", "We agree to meet at six.", "Estamos de acuerdo en reunirnos a las seis.", ["accept", "concur"], ["disagree"], ["agree with someone", "agree on a date"], ["agree, agreement, agreeable"], ["communication", "relationships"], "communication action"),
    ], [{ phrase: "I suggest meeting earlier.", translation: "Sugiero reunirnos antes." }, { phrase: "Could you explain the change?", translation: "¿Podrías explicar el cambio?" }, { phrase: "We had to postpone the meeting.", translation: "Tuvimos que posponer la reunión." }, { phrase: "Please respond by Friday.", translation: "Responde antes del viernes, por favor." }], [{ speaker: "A", text: "Can we arrange dinner for Thursday?", translation: "¿Podemos organizar una cena para el jueves?" }, { speaker: "B", text: "I am busy, so I suggest Friday.", translation: "Estoy ocupado, así que sugiero el viernes." }, { speaker: "A", text: "That works. I will invite Maya.", translation: "Me parece bien. Invitaré a Maya." }, { speaker: "B", text: "Great. Please respond when she agrees.", translation: "Perfecto. Responde cuando ella esté de acuerdo." }], { title: "Changing a Plan", text: "Plans sometimes change. People can suggest another time, explain the reason, and arrange a new meeting. A clear response helps everyone agree and prevents confusion.", translation: "Los planes a veces cambian. Las personas pueden sugerir otra hora, explicar el motivo y organizar una nueva reunión. Una respuesta clara ayuda a todos a ponerse de acuerdo y evita la confusión." }),
  ],
  B1: [
    u("u46", "Health and Lifestyle", "Discuss habits, prevention, and how people feel in daily life.", [
      w("nutrition", "nutrición", "noun", "/nuˈtrɪʃən/", "the process of getting what the body needs from food", "Good nutrition supports the immune system.", "Una buena nutrición apoya el sistema inmunitario.", ["nourishment", "diet"], ["malnutrition"], ["healthy nutrition", "nutrition advice"], ["nourish, nutrition, nutritional"], ["health", "food"], "health"),
      w("exercise", "ejercicio", "noun", "/ˈeksərsaɪz/", "physical activity done to improve health or strength", "Regular exercise improves my mood.", "El ejercicio regular mejora mi estado de ánimo.", ["training", "workout"], ["inactivity"], ["regular exercise", "do exercise"], ["exercise, exercising"], ["health", "fitness"], "health"),
      w("prevention", "prevención", "noun", "/prɪˈvenʃən/", "action taken to stop something harmful from happening", "Prevention is better than emergency treatment.", "La prevención es mejor que el tratamiento de emergencia.", ["protection", "avoidance"], ["neglect"], ["disease prevention", "prevention programme"], ["prevent, prevention, preventive"], ["health", "safety"], "health"),
      w("diagnose", "diagnosticar", "verb", "/ˈdaɪəɡnoʊz/", "to identify an illness or problem", "The doctor diagnosed a minor infection.", "El médico diagnosticó una infección leve.", ["identify", "detect"], ["misdiagnose"], ["diagnose a condition", "diagnose accurately"], ["diagnose, diagnosis, diagnostic"], ["health", "science"], "health action"),
      w("prescription", "receta médica", "noun", "/prɪˈskrɪpʃən/", "an instruction from a doctor for medicine", "The doctor gave me a prescription.", "El médico me dio una receta médica.", ["medical order", "drug instruction"], [], ["write a prescription", "prescription medicine"], ["prescribe, prescription"], ["health", "medicine"], "health"),
      w("balanced", "equilibrado", "adjective", "/ˈbælənst/", "including a sensible range of different things", "She follows a balanced diet.", "Ella sigue una dieta equilibrada.", ["healthy", "moderate"], ["unbalanced"], ["balanced diet", "balanced lifestyle"], ["balance, balanced"], ["health", "food"], "quality"),
      w("active", "activo", "adjective", "/ˈæktɪv/", "regularly doing physical or useful activities", "An active lifestyle can reduce stress.", "Un estilo de vida activo puede reducir el estrés.", ["energetic", "dynamic"], ["inactive"], ["stay active", "active lifestyle"], ["act, active, activity"], ["health", "fitness"], "quality"),
      w("exhausted", "agotado", "adjective", "/ɪɡˈzɔːstɪd/", "extremely tired", "I felt exhausted after the long walk.", "Me sentí agotado después de la larga caminata.", ["worn out", "drained"], ["refreshed"], ["feel exhausted", "completely exhausted"], ["exhaust, exhausted, exhaustion"], ["health", "emotion"], "feeling"),
    ], [{ phrase: "Prevention can protect your health.", translation: "La prevención puede proteger tu salud." }, { phrase: "The doctor wrote a prescription.", translation: "El médico escribió una receta." }, { phrase: "Exercise improves my mood.", translation: "El ejercicio mejora mi estado de ánimo." }, { phrase: "I feel exhausted today.", translation: "Hoy me siento agotado." }], [{ speaker: "A", text: "How can people prevent illness?", translation: "¿Cómo pueden las personas prevenir las enfermedades?" }, { speaker: "B", text: "With balanced nutrition and regular exercise.", translation: "Con una nutrición equilibrada y ejercicio regular." }, { speaker: "A", text: "Did the doctor diagnose the problem?", translation: "¿Diagnosticó el médico el problema?" }, { speaker: "B", text: "Yes, and she gave me a prescription.", translation: "Sí, y me dio una receta." }], { title: "A Healthier Routine", text: "Health depends on many daily choices. Balanced nutrition, regular exercise, and prevention can protect the body. When a problem appears, a doctor can diagnose it and recommend appropriate treatment.", translation: "La salud depende de muchas decisiones diarias. Una nutrición equilibrada, el ejercicio regular y la prevención pueden proteger el cuerpo. Cuando aparece un problema, un médico puede diagnosticarlo y recomendar un tratamiento adecuado." }),
    u("u47", "Culture and Travel", "Describe cultural experiences, places, and respectful travel.", [
      w("tradition", "tradición", "noun", "/trəˈdɪʃən/", "a custom or belief passed through generations", "The festival follows a local tradition.", "El festival sigue una tradición local.", ["custom", "practice"], ["innovation"], ["cultural tradition", "family tradition"], ["tradition, traditional"], ["culture", "community"], "culture"),
      w("heritage", "patrimonio", "noun", "/ˈherɪtɪdʒ/", "important cultural history and traditions", "The town protects its architectural heritage.", "La ciudad protege su patrimonio arquitectónico.", ["legacy", "inheritance"], ["forgetting"], ["cultural heritage", "world heritage"], ["heritage, hereditary"], ["culture", "history"], "culture"),
      w("festival", "festival", "noun", "/ˈfestɪvəl/", "a special event celebrating a person, idea, or tradition", "The town holds a music festival each year.", "La ciudad celebra un festival de música cada año.", ["celebration", "fair"], ["ordinary day"], ["music festival", "annual festival"], ["festive, festival"], ["culture", "leisure"], "culture"),
      w("local", "local", "adjective", "/ˈloʊkəl/", "connected with a particular area or community", "We tried local food.", "Probamos comida local.", ["regional", "nearby"], ["foreign"], ["local people", "local culture"], ["locate, local, locality"], ["travel", "community"], "place"),
      w("landscape", "paisaje", "noun", "/ˈlændskeɪp/", "the visible features of an area of land", "The mountain landscape was beautiful.", "El paisaje montañoso era hermoso.", ["scenery", "view"], ["cityscape"], ["mountain landscape", "landscape painting"], ["landscape, landscaped"], ["travel", "nature"], "nature"),
      w("destination", "destino", "noun", "/ˌdestɪˈneɪʃən/", "a place where someone is going", "The island is a popular destination.", "La isla es un destino popular.", ["goal", "endpoint"], ["departure"], ["holiday destination", "final destination"], ["destination, destined"], ["travel", "planning"], "travel"),
      w("explore", "explorar", "verb", "/ɪkˈsplɔːr/", "to travel around or examine a place or idea", "We explored the old city on foot.", "Exploramos la ciudad antigua a pie.", ["investigate", "discover"], ["ignore"], ["explore a city", "explore an idea"], ["explore, explorer, exploration"], ["travel", "learning"], "travel action"),
      w("encounter", "encontrarse con", "verb", "/ɪnˈkaʊntər/", "to meet someone or experience something unexpectedly", "We encountered a local guide.", "Nos encontramos con un guía local.", ["meet", "come across"], ["avoid"], ["encounter a problem", "encounter a culture"], ["encounter, encounter"], ["travel", "experience"], "experience action"),
    ], [{ phrase: "We want to respect local traditions.", translation: "Queremos respetar las tradiciones locales." }, { phrase: "The landscape is remarkable.", translation: "El paisaje es extraordinario." }, { phrase: "This island is our destination.", translation: "Esta isla es nuestro destino." }, { phrase: "We explored the city on foot.", translation: "Exploramos la ciudad a pie." }], [{ speaker: "A", text: "What did you enjoy about the destination?", translation: "¿Qué disfrutaste del destino?" }, { speaker: "B", text: "The landscape and the local festival.", translation: "El paisaje y el festival local." }, { speaker: "A", text: "Did you learn about its heritage?", translation: "¿Aprendiste sobre su patrimonio?" }, { speaker: "B", text: "Yes, and we respected every tradition we encountered.", translation: "Sí, y respetamos cada tradición con la que nos encontramos." }], { title: "Travel with Respect", text: "Travel becomes richer when visitors learn about local culture. A destination may offer a beautiful landscape, an annual festival, and a deep heritage. Respectful travellers explore with curiosity and listen to the people they encounter.", translation: "Viajar se vuelve más enriquecedor cuando los visitantes aprenden sobre la cultura local. Un destino puede ofrecer un paisaje hermoso, un festival anual y un patrimonio profundo. Los viajeros respetuosos exploran con curiosidad y escuchan a las personas que encuentran." }),
  ],
  B2: [
    u("u46", "Research and Data", "Evaluate evidence, methods, and the limits of research findings.", [
      w("dataset", "conjunto de datos", "noun", "/ˈdeɪtəset/", "a structured collection of information", "The researchers released the dataset.", "Los investigadores publicaron el conjunto de datos.", ["data collection", "database"], [], ["large dataset", "analyse a dataset"], ["data, dataset"], ["research", "technology"], "research"),
      w("correlation", "correlación", "noun", "/ˌkɔːrəˈleɪʃən/", "a relationship in which two things change together", "The study found a correlation between sleep and memory.", "El estudio encontró una correlación entre el sueño y la memoria.", ["connection", "association"], ["independence"], ["strong correlation", "correlation between"], ["correlate, correlation"], ["research", "statistics"], "research"),
      w("statistic", "dato estadístico", "noun", "/stəˈtɪstɪk/", "a number that describes a set of information", "This statistic reveals a significant difference.", "Este dato estadístico revela una diferencia significativa.", ["figure", "measure"], [], ["official statistic", "publish a statistic"], ["state, statistic, statistical"], ["research", "numbers"], "statistics"),
      w("survey", "encuesta", "noun", "/ˈsɜːrveɪ/", "a study that collects answers from a group of people", "The survey included five hundred participants.", "La encuesta incluyó a quinientos participantes.", ["questionnaire", "poll"], [], ["conduct a survey", "survey results"], ["survey, surveyor"], ["research", "society"], "research"),
      w("methodology", "metodología", "noun", "/ˌmeθəˈdɑːlədʒi/", "a system of methods used in a study", "The methodology is clearly explained.", "La metodología está explicada claramente.", ["method", "procedure"], ["improvisation"], ["research methodology", "methodology section"], ["method, methodology, methodological"], ["research", "academic"], "research"),
      w("replicate", "replicar", "verb", "/ˈreplɪkeɪt/", "to repeat a study or result to test whether it is reliable", "Other teams could not replicate the result.", "Otros equipos no pudieron replicar el resultado.", ["repeat", "reproduce"], ["alter"], ["replicate a study", "replicate findings"], ["replicate, replication"], ["research", "science"], "research action"),
      w("finding", "hallazgo", "noun", "/ˈfaɪndɪŋ/", "a result or conclusion discovered through research", "The main finding surprised the team.", "El hallazgo principal sorprendió al equipo.", ["result", "discovery"], ["assumption"], ["research finding", "key finding"], ["find, finding"], ["research", "analysis"], "research"),
      w("limitation", "limitación", "noun", "/ˌlɪmɪˈteɪʃən/", "a weakness or boundary that restricts something", "The report acknowledges its limitation.", "El informe reconoce su limitación.", ["constraint", "restriction"], ["freedom"], ["study limitation", "acknowledge a limitation"], ["limit, limitation, limited"], ["research", "evaluation"], "evaluation"),
    ], [{ phrase: "The survey produced an important finding.", translation: "La encuesta produjo un hallazgo importante." }, { phrase: "The methodology has one limitation.", translation: "La metodología tiene una limitación." }, { phrase: "Can another team replicate the study?", translation: "¿Puede otro equipo replicar el estudio?" }, { phrase: "Correlation does not prove causation.", translation: "La correlación no demuestra causalidad." }], [{ speaker: "A", text: "What does the dataset show?", translation: "¿Qué muestra el conjunto de datos?" }, { speaker: "B", text: "It shows a correlation, but not necessarily causation.", translation: "Muestra una correlación, pero no necesariamente causalidad." }, { speaker: "A", text: "Can the result be replicated?", translation: "¿Puede replicarse el resultado?" }, { speaker: "B", text: "Perhaps, although the methodology has limitations.", translation: "Quizá, aunque la metodología tiene limitaciones." }], { title: "Reading Research Carefully", text: "A research finding is only as strong as the methods behind it. A dataset and a survey can reveal a correlation, but researchers must consider methodology, replication, and limitation before making a broad claim.", translation: "Un hallazgo de investigación es tan sólido como los métodos que lo sustentan. Un conjunto de datos y una encuesta pueden revelar una correlación, pero los investigadores deben considerar la metodología, la replicación y las limitaciones antes de hacer una afirmación general." }),
    u("u47", "Business Strategy", "Discuss markets, competition, and responsible business growth.", [
      w("revenue", "ingresos", "noun", "/ˈrevənuː/", "money earned by a business", "The company increased its revenue.", "La empresa aumentó sus ingresos.", ["income", "turnover"], ["loss"], ["annual revenue", "generate revenue"], ["revenue, revenue-generating"], ["business", "money"], "business"),
      w("competitor", "competidor", "noun", "/kəmˈpetɪtər/", "a person or organisation competing with another", "A new competitor entered the market.", "Un nuevo competidor entró en el mercado.", ["rival", "challenger"], ["partner"], ["main competitor", "compete with a competitor"], ["compete, competitor, competitive"], ["business", "markets"], "business"),
      w("market", "mercado", "noun", "/ˈmɑːrkɪt/", "the people and organisations that buy or sell a product", "The company understands its target market.", "La empresa entiende su mercado objetivo.", ["trade", "sector"], [], ["target market", "market share"], ["market, marketing, marketer"], ["business", "shopping"], "business"),
      w("forecast", "previsión", "noun", "/ˈfɔːrkæst/", "a statement about what is likely to happen in the future", "The sales forecast is optimistic.", "La previsión de ventas es optimista.", ["prediction", "projection"], ["history"], ["sales forecast", "economic forecast"], ["forecast, forecasting"], ["business", "planning"], "planning"),
      w("launch", "lanzar", "verb", "/lɔːntʃ/", "to introduce a new product or service", "They will launch the app in June.", "Lanzarán la aplicación en junio.", ["introduce", "release"], ["withdraw"], ["launch a product", "product launch"], ["launch, launcher, launching"], ["business", "technology"], "business action"),
      w("profit", "beneficio", "noun", "/ˈprɑːfɪt/", "money left after costs have been paid", "The business made a small profit.", "El negocio obtuvo un pequeño beneficio.", ["gain", "return"], ["loss"], ["make a profit", "profit margin"], ["profit, profitable, profitability"], ["business", "money"], "business"),
      w("merger", "fusión", "noun", "/ˈmɜːrdʒər/", "the joining of two organisations into one", "The merger created a larger company.", "La fusión creó una empresa más grande.", ["combination", "union"], ["separation"], ["business merger", "announce a merger"], ["merge, merger"], ["business", "organisations"], "business"),
      w("profitable", "rentable", "adjective", "/ˈprɑːfɪtəbəl/", "producing more money than it costs", "The service became profitable within a year.", "El servicio se volvió rentable en un año.", ["successful", "lucrative"], ["unprofitable"], ["profitable business", "remain profitable"], ["profit, profitable, profitability"], ["business", "money"], "quality"),
    ], [{ phrase: "The company is entering a new market.", translation: "La empresa está entrando en un nuevo mercado." }, { phrase: "The sales forecast is optimistic.", translation: "La previsión de ventas es optimista." }, { phrase: "They will launch the product soon.", translation: "Lanzarán el producto pronto." }, { phrase: "The business must remain profitable.", translation: "El negocio debe seguir siendo rentable." }], [{ speaker: "A", text: "What is the company's strategy?", translation: "¿Cuál es la estrategia de la empresa?" }, { speaker: "B", text: "We will launch a service for a new market.", translation: "Lanzaremos un servicio para un nuevo mercado." }, { speaker: "A", text: "Will it be profitable?", translation: "¿Será rentable?" }, { speaker: "B", text: "The forecast is positive, but competition is strong.", translation: "La previsión es positiva, pero la competencia es fuerte." }], { title: "Growing Responsibly", text: "A business needs more than a good product. It studies its market, watches competitors, forecasts revenue, and controls costs. Responsible growth aims for profit without ignoring customers, workers, or the wider community.", translation: "Un negocio necesita más que un buen producto. Estudia su mercado, observa a los competidores, prevé los ingresos y controla los costes. El crecimiento responsable busca beneficios sin ignorar a los clientes, los trabajadores o la comunidad más amplia." }),
  ],
  C1: [
    u("u46", "Ethics and Technology", "Evaluate autonomy, fairness, and the consequences of digital systems.", [
      w("dignity", "dignidad", "noun", "/ˈdɪɡnəti/", "the quality of being worthy of respect", "Technology should protect human dignity.", "La tecnología debe proteger la dignidad humana.", ["worth", "honour"], ["humiliation"], ["human dignity", "preserve dignity"], ["dignity, dignified"], ["ethics", "society"], "ethics"),
      w("privacy", "privacidad", "noun", "/ˈpraɪvəsi/", "the right to keep personal information and life from public view", "Users deserve privacy online.", "Los usuarios merecen privacidad en internet.", ["confidentiality", "secrecy"], ["exposure"], ["protect privacy", "privacy rights"], ["private, privacy"], ["technology", "rights"], "ethics"),
      w("agency", "capacidad de actuar", "noun", "/ˈeɪdʒənsi/", "the ability to make choices and act independently", "People need agency over their data.", "Las personas necesitan capacidad de decisión sobre sus datos.", ["autonomy", "independence"], ["powerlessness"], ["human agency", "exercise agency"], ["agent, agency"], ["ethics", "psychology"], "ethics"),
      w("fairness", "imparcialidad", "noun", "/ˈfernəs/", "the quality of treating people equally and reasonably", "The system must be tested for fairness.", "El sistema debe probarse para comprobar su imparcialidad.", ["justice", "equity"], ["injustice"], ["procedural fairness", "fairness assessment"], ["fair, fairness"], ["ethics", "law"], "ethics"),
      w("exploit", "explotar", "verb", "/ɪkˈsplɔɪt/", "to use someone or something unfairly for advantage", "The platform should not exploit vulnerable users.", "La plataforma no debe explotar a los usuarios vulnerables.", ["take advantage of", "use"], ["protect"], ["exploit a weakness", "exploit workers"], ["exploit, exploitation, exploitative"], ["ethics", "work"], "ethics action"),
      w("regulate", "regular", "verb", "/ˈreɡjəleɪt/", "to control an activity through rules", "Governments regulate high-risk technology.", "Los gobiernos regulan la tecnología de alto riesgo.", ["control", "govern"], ["deregulate"], ["regulate an industry", "regulate access"], ["regulate, regulation, regulatory"], ["government", "technology"], "policy action"),
      w("ethical", "ético", "adjective", "/ˈeθɪkəl/", "relating to principles about right and wrong", "The team faced an ethical question.", "El equipo se enfrentó a una cuestión ética.", ["moral", "principled"], ["unethical"], ["ethical principle", "ethical question"], ["ethics, ethical, ethically"], ["ethics", "decision-making"], "quality"),
      w("consequence", "consecuencia", "noun", "/ˈkɑːnsəkwens/", "a result that follows an action or event", "Every design choice has a consequence.", "Cada decisión de diseño tiene una consecuencia.", ["result", "effect"], ["cause"], ["unintended consequence", "long-term consequence"], ["consequence, consequential"], ["ethics", "planning"], "reasoning"),
    ], [{ phrase: "Users deserve privacy and agency.", translation: "Los usuarios merecen privacidad y capacidad de decisión." }, { phrase: "The design raises an ethical question.", translation: "El diseño plantea una cuestión ética." }, { phrase: "Regulators must protect fairness.", translation: "Los reguladores deben proteger la imparcialidad." }, { phrase: "Every system has consequences.", translation: "Todo sistema tiene consecuencias." }], [{ speaker: "A", text: "What is the main ethical concern?", translation: "¿Cuál es la principal preocupación ética?" }, { speaker: "B", text: "Users may lose privacy and agency.", translation: "Los usuarios pueden perder privacidad y capacidad de decisión." }, { speaker: "A", text: "How should governments respond?", translation: "¿Cómo deberían responder los gobiernos?" }, { speaker: "B", text: "They should regulate harmful systems fairly.", translation: "Deberían regular justamente los sistemas perjudiciales." }], { title: "Designing with Responsibility", text: "Digital systems shape choices and distribute power. Ethical design protects privacy, fairness, dignity, and human agency. Regulation cannot remove every risk, but it can limit exploitation and make consequences more visible.", translation: "Los sistemas digitales moldean las decisiones y distribuyen el poder. El diseño ético protege la privacidad, la imparcialidad, la dignidad y la capacidad de actuar de las personas. La regulación no puede eliminar todos los riesgos, pero puede limitar la explotación y hacer más visibles las consecuencias." }),
    u("u47", "Academic Writing", "Build precise arguments with evidence, structure, and careful qualification.", [
      w("thesis", "tesis", "noun", "/ˈθiːsɪs/", "the central claim of an academic argument", "The thesis is stated in the introduction.", "La tesis se expone en la introducción.", ["argument", "proposition"], ["digression"], ["central thesis", "support a thesis"], ["thesis, thesis statement"], ["academic", "writing"], "writing"),
      w("citation", "cita bibliográfica", "noun", "/saɪˈteɪʃən/", "a reference to a source used in academic work", "Every quotation needs a citation.", "Cada cita necesita una referencia bibliográfica.", ["reference", "source note"], [], ["academic citation", "citation style"], ["cite, citation, citable"], ["academic", "research"], "writing"),
      w("paragraph", "párrafo", "noun", "/ˈpærəɡræf/", "a group of sentences about one main idea", "Each paragraph develops one point.", "Cada párrafo desarrolla un punto.", ["section", "passage"], [], ["opening paragraph", "paragraph structure"], ["paragraph, paragraphing"], ["writing", "learning"], "writing"),
      w("evidence", "evidencia", "noun", "/ˈevɪdəns/", "information that supports whether something is true", "The conclusion is based on evidence.", "La conclusión se basa en evidencia.", ["proof", "support"], ["claim"], ["strong evidence", "evidence suggests"], ["evident, evidence"], ["research", "reasoning"], "research"),
      w("qualify", "matizar", "verb", "/ˈkwɑːlɪfaɪ/", "to limit or make a statement more precise", "The author qualifies the main claim.", "El autor matiza la afirmación principal.", ["moderate", "restrict"], ["exaggerate"], ["qualify a claim", "carefully qualify"], ["qualify, qualification, qualified"], ["academic", "writing"], "writing action"),
      w("reference", "referencia", "noun", "/ˈrefrəns/", "a mention of a source or another text", "The reference appears in the final section.", "La referencia aparece en la sección final.", ["citation", "mention"], ["omission"], ["reference list", "reference a study"], ["refer, reference, referential"], ["academic", "research"], "writing"),
      w("revise", "revisar", "verb", "/rɪˈvaɪz/", "to improve writing by changing and correcting it", "I revised the final paragraph.", "Revisé el párrafo final.", ["edit", "redraft"], ["neglect"], ["revise an essay", "revise carefully"], ["revise, revision, revised"], ["writing", "learning"], "writing action"),
      w("precise", "preciso", "adjective", "/prɪˈsaɪs/", "exact and clear rather than general", "Choose a precise term.", "Elige un término preciso.", ["exact", "specific"], ["vague"], ["precise language", "precise definition"], ["precision, precise, precisely"], ["academic", "language"], "quality"),
    ], [{ phrase: "The thesis needs stronger evidence.", translation: "La tesis necesita evidencia más sólida." }, { phrase: "Add a citation to the paragraph.", translation: "Añade una cita bibliográfica al párrafo." }, { phrase: "The author qualifies the claim.", translation: "El autor matiza la afirmación." }, { phrase: "Revise the essay for precise language.", translation: "Revisa el ensayo para usar un lenguaje preciso." }], [{ speaker: "A", text: "Is the thesis clear?", translation: "¿Está clara la tesis?" }, { speaker: "B", text: "Yes, but the evidence needs more citations.", translation: "Sí, pero la evidencia necesita más citas." }, { speaker: "A", text: "Should I revise the paragraph?", translation: "¿Debería revisar el párrafo?" }, { speaker: "B", text: "Yes, qualify the claim and use a precise term.", translation: "Sí, matiza la afirmación y usa un término preciso." }], { title: "Building an Argument", text: "Academic writing presents a thesis and supports it with evidence. Clear paragraphs, accurate citations, and precise language help readers follow the argument. A careful writer revises and qualifies claims rather than overstating them.", translation: "La escritura académica presenta una tesis y la apoya con evidencia. Los párrafos claros, las citas exactas y el lenguaje preciso ayudan a los lectores a seguir el argumento. Un escritor cuidadoso revisa y matiza las afirmaciones en lugar de exagerarlas." }),
  ],
  C2: [
    u("u46", "Philosophy of Language", "Analyse meaning, reference, context, and the logic of utterances.", [
      w("signifier", "significante", "noun", "/ˈsɪɡnɪfaɪər/", "the form that carries meaning in a sign", "The signifier is not identical to the concept.", "El significante no es idéntico al concepto.", ["symbol", "expression"], ["signified"], ["linguistic signifier", "relationship between signifier and signified"], ["signify, signifier, signification"], ["linguistics", "philosophy"], "language"),
      w("reference", "referencia", "noun", "/ˈrefrəns/", "the relation between an expression and what it indicates", "Reference depends on context.", "La referencia depende del contexto.", ["denotation", "indication"], ["irrelevance"], ["direct reference", "reference point"], ["refer, reference, referential"], ["language", "logic"], "language"),
      w("utterance", "enunciado", "noun", "/ˈʌtərəns/", "a piece of spoken or written language produced in context", "The utterance has more than one possible meaning.", "El enunciado tiene más de un significado posible.", ["statement", "expression"], ["silence"], ["spoken utterance", "meaning of an utterance"], ["utter, utterance"], ["linguistics", "communication"], "language"),
      w("truth", "verdad", "noun", "/truːθ/", "the quality of being in agreement with facts or reality", "The theory distinguishes truth from belief.", "La teoría distingue la verdad de la creencia.", ["accuracy", "veracity"], ["falsehood"], ["truth claim", "seek the truth"], ["true, truth, truthful"], ["philosophy", "reasoning"], "reasoning"),
      w("context", "contexto", "noun", "/ˈkɑːntekst/", "the situation that gives meaning to an expression or event", "The phrase changes meaning in another context.", "La frase cambia de significado en otro contexto.", ["setting", "circumstance"], ["isolation"], ["social context", "historical context"], ["context, contextualize, contextual"], ["language", "society"], "meaning"),
      w("literal", "literal", "adjective", "/ˈlɪtərəl/", "using the exact basic meaning of words", "The literal reading misses the irony.", "La lectura literal pierde la ironía.", ["exact", "word-for-word"], ["figurative"], ["literal meaning", "literal interpretation"], ["literal, literally, literalism"], ["language", "literature"], "meaning"),
      w("entailment", "implicación lógica", "noun", "/ɪnˈteɪlmənt/", "a relation in which one statement logically follows from another", "The argument contains a clear entailment.", "El argumento contiene una implicación lógica clara.", ["implication", "consequence"], ["contradiction"], ["logical entailment", "semantic entailment"], ["entail, entailment"], ["logic", "linguistics"], "reasoning"),
      w("paradox", "paradoja", "noun", "/ˈpærədɑːks/", "a statement that seems contradictory but may reveal a truth", "The paradox challenges ordinary assumptions.", "La paradoja desafía las suposiciones habituales.", ["contradiction", "puzzle"], ["certainty"], ["logical paradox", "apparent paradox"], ["paradox, paradoxical"], ["philosophy", "logic"], "reasoning"),
    ], [{ phrase: "Meaning depends on context.", translation: "El significado depende del contexto." }, { phrase: "The literal reading misses the point.", translation: "La lectura literal no capta el sentido." }, { phrase: "The premise entails the conclusion.", translation: "La premisa implica la conclusión." }, { phrase: "The paradox challenges a familiar belief.", translation: "La paradoja desafía una creencia conocida." }], [{ speaker: "A", text: "What gives the utterance its meaning?", translation: "¿Qué da significado al enunciado?" }, { speaker: "B", text: "Its context, reference, and relation to other expressions.", translation: "Su contexto, referencia y relación con otras expresiones." }, { speaker: "A", text: "Is the reading literal?", translation: "¿Es la lectura literal?" }, { speaker: "B", text: "No. The paradox suggests a deeper entailment.", translation: "No. La paradoja sugiere una implicación más profunda." }], { title: "Meaning in Context", text: "Words do not carry meaning in isolation. A signifier, an utterance, and a reference operate within a context. Literal readings can be useful, but paradoxes and entailments show how language may exceed its most obvious interpretation.", translation: "Las palabras no tienen significado de forma aislada. Un significante, un enunciado y una referencia funcionan dentro de un contexto. Las lecturas literales pueden ser útiles, pero las paradojas y las implicaciones muestran cómo el lenguaje puede superar su interpretación más obvia." }),
    u("u47", "Critical Inquiry", "Assess arguments through objections, inference, and rigorous distinctions.", [
      w("critique", "crítica", "noun", "/krɪˈtiːk/", "a careful judgement about the strengths and weaknesses of an idea", "The critique identifies a hidden assumption.", "La crítica identifica una suposición oculta.", ["analysis", "review"], ["praise"], ["critical critique", "offer a critique"], ["critic, critique, critical"], ["philosophy", "academic"], "analysis"),
      w("objection", "objeción", "noun", "/əbˈdʒekʃən/", "a reason for disagreeing with a proposal or argument", "The strongest objection concerns evidence.", "La objeción más fuerte se refiere a la evidencia.", ["challenge", "protest"], ["support"], ["raise an objection", "serious objection"], ["object, objection, objective"], ["reasoning", "debate"], "reasoning"),
      w("inference", "inferencia", "noun", "/ˈɪnfərəns/", "a conclusion reached from evidence and reasoning", "The inference is not fully justified.", "La inferencia no está completamente justificada.", ["deduction", "conclusion"], ["guess"], ["draw an inference", "logical inference"], ["infer, inference, inferential"], ["logic", "research"], "reasoning"),
      w("counterexample", "contraejemplo", "noun", "/ˈkaʊntərɪɡzæmpəl/", "an example that shows a general claim is not always true", "One counterexample weakens the universal claim.", "Un contraejemplo debilita la afirmación universal.", ["disproof", "exception"], ["confirmation"], ["provide a counterexample", "single counterexample"], ["counter, example, counterexample"], ["logic", "academic"], "reasoning"),
      w("validity", "validez", "noun", "/vəˈlɪdəti/", "the quality of being logically sound or well-founded", "The paper questions the validity of the measure.", "El artículo cuestiona la validez de la medida.", ["soundness", "legitimacy"], ["invalidity"], ["logical validity", "assess validity"], ["valid, validity, validate"], ["logic", "research"], "reasoning"),
      w("dialectical", "dialéctico", "adjective", "/ˌdaɪəˈlektɪkəl/", "involving the exchange and resolution of opposing ideas", "The essay follows a dialectical structure.", "El ensayo sigue una estructura dialéctica.", ["dialogical", "argumentative"], ["one-sided"], ["dialectical method", "dialectical tension"], ["dialectic, dialectical"], ["philosophy", "debate"], "reasoning"),
      w("skeptical", "escéptico", "adjective", "/ˈskeptɪkəl/", "not easily convinced and requiring strong evidence", "The reviewer remains skeptical of the claim.", "El revisor sigue siendo escéptico ante la afirmación.", ["doubtful", "questioning"], ["credulous"], ["skeptical attitude", "remain skeptical"], ["skeptic, skeptical, skepticism"], ["reasoning", "research"], "attitude"),
      w("rigorous", "riguroso", "adjective", "/ˈrɪɡərəs/", "careful, thorough, and based on strict standards", "The study uses a rigorous method.", "El estudio utiliza un método riguroso.", ["thorough", "strict"], ["careless"], ["rigorous analysis", "rigorous standard"], ["rigour, rigorous, rigorously"], ["academic", "research"], "quality"),
    ], [{ phrase: "The objection concerns the validity of the inference.", translation: "La objeción se refiere a la validez de la inferencia." }, { phrase: "A counterexample can weaken a universal claim.", translation: "Un contraejemplo puede debilitar una afirmación universal." }, { phrase: "The reviewer remains skeptical.", translation: "El revisor sigue siendo escéptico." }, { phrase: "The analysis must be rigorous.", translation: "El análisis debe ser riguroso." }], [{ speaker: "A", text: "What is the strongest objection?", translation: "¿Cuál es la objeción más fuerte?" }, { speaker: "B", text: "The inference lacks validity because the evidence is limited.", translation: "La inferencia carece de validez porque la evidencia es limitada." }, { speaker: "A", text: "Could a counterexample help?", translation: "¿Podría ayudar un contraejemplo?" }, { speaker: "B", text: "Yes, especially in a rigorous dialectical analysis.", translation: "Sí, especialmente en un análisis dialéctico riguroso." }], { title: "Testing an Argument", text: "Critical inquiry does not reject an argument simply because it is unfamiliar. It identifies objections, examines inference, and tests validity. A counterexample may reveal a hidden weakness, while a rigorous and dialectical method keeps debate open.", translation: "La investigación crítica no rechaza un argumento simplemente porque sea desconocido. Identifica objeciones, examina las inferencias y prueba la validez. Un contraejemplo puede revelar una debilidad oculta, mientras que un método riguroso y dialéctico mantiene abierto el debate." }),
  ],
};
