// Professional English enrichment units u48-u49 for every CEFR level.
// Finnish curriculum is intentionally untouched. APIs may enrich these records later,
// but they never generate the local curriculum.
import type { ReadingText, VocabularyItem } from "./learn-data";

type PhraseSpec = { phrase: string; translation: string };
type LineSpec = { speaker: string; text: string; translation: string };
type UnitSeed = { id: string; title: string; description: string; words: VocabularyItem[]; phrases: PhraseSpec[]; dialogue: LineSpec[]; reading: ReadingText & { title: string } };

const w = (word: string, translation: string, pos: string, ipa: string, definition: string, example: string, exampleTranslation: string, synonyms: string[], antonyms: string[], collocations: string[], wordFamily: string[], tags: string[], category: string): VocabularyItem => ({ word, translation, pos, ipa, definition, example, exampleTranslation, synonyms, antonyms, collocations, wordFamily, tags, category });
const u = (id: string, title: string, description: string, words: VocabularyItem[], phrases: PhraseSpec[], dialogue: LineSpec[], reading: ReadingText & { title: string }): UnitSeed => ({ id, title, description, words, phrases, dialogue, reading });

export const ADDITIONAL_EN_PART13_UNITS: Record<string, UnitSeed[]> = {
  A0: [
    u("u48", "Things at Home", "Name familiar objects and describe simple actions with them.", [
      w("pillow", "almohada", "noun", "/ˈpɪloʊ/", "a soft thing used to support your head in bed", "My pillow is on the bed.", "Mi almohada está sobre la cama.", ["cushion", "headrest"], [], ["soft pillow", "sleep on a pillow"], ["pillow, pillowcase"], ["home", "sleep"], "home object"),
      w("blanket", "manta", "noun", "/ˈblæŋkɪt/", "a warm cover used on a bed", "The baby needs a warm blanket.", "El bebé necesita una manta caliente.", ["cover", "quilt"], [], ["warm blanket", "under a blanket"], ["blanket, blanketed"], ["home", "sleep"], "home object"),
      w("mirror", "espejo", "noun", "/ˈmɪrər/", "a surface that shows a reflection", "I look in the mirror.", "Me miro en el espejo.", ["looking glass", "reflection"], [], ["bathroom mirror", "look in a mirror"], ["mirror, mirrored"], ["home", "body"], "home object"),
      w("lamp", "lámpara", "noun", "/læmp/", "a device that gives light", "The lamp is beside the bed.", "La lámpara está junto a la cama.", ["light", "lantern"], [], ["desk lamp", "turn on a lamp"], ["lamp, lamplight"], ["home", "light"], "home object"),
      w("key", "llave", "noun", "/kiː/", "a small object used to open a lock", "My key is in my pocket.", "Mi llave está en mi bolsillo.", ["opener", "passkey"], [], ["house key", "find a key"], ["key, keyed, keyhole"], ["home", "security"], "object"),
      w("lock", "cerradura", "noun", "/lɑːk/", "a device that keeps a door closed", "The lock is on the door.", "La cerradura está en la puerta.", ["fastener", "bolt"], [], ["door lock", "open a lock"], ["lock, locked, locker"], ["home", "security"], "object"),
      w("open", "abrir", "verb", "/ˈoʊpən/", "to move something so that it is not closed", "Please open the window.", "Abre la ventana, por favor.", ["unlock", "uncover"], ["close"], ["open a door", "open a box"], ["open, opening, openness"], ["home", "actions"], "daily action"),
      w("close", "cerrar", "verb", "/kloʊz/", "to move something into a position that blocks it", "Close the door quietly.", "Cierra la puerta en silencio.", ["shut", "seal"], ["open"], ["close a window", "close the door"], ["close, closed, closure"], ["home", "actions"], "daily action"),
    ], [{ phrase: "Where is my key?", translation: "¿Dónde está mi llave?" }, { phrase: "Look in the mirror.", translation: "Mírate en el espejo." }, { phrase: "Please close the door.", translation: "Cierra la puerta, por favor." }, { phrase: "The blanket is warm.", translation: "La manta está caliente." }], [{ speaker: "A", text: "Where is the lamp?", translation: "¿Dónde está la lámpara?" }, { speaker: "B", text: "It is beside the bed.", translation: "Está junto a la cama." }, { speaker: "A", text: "Can you open the window?", translation: "¿Puedes abrir la ventana?" }, { speaker: "B", text: "Yes, but please close the door.", translation: "Sí, pero cierra la puerta, por favor." }], { title: "A Comfortable Room", text: "A comfortable room has a bed, a pillow, and a warm blanket. A lamp gives light, and a mirror shows a face. Before leaving, people find their key and close the door.", translation: "Una habitación cómoda tiene una cama, una almohada y una manta caliente. Una lámpara da luz y un espejo muestra un rostro. Antes de salir, las personas encuentran su llave y cierran la puerta." }),
    u("u49", "Farm Animals", "Name familiar animals and describe simple care and movement.", [
      w("rabbit", "conejo", "noun", "/ˈræbɪt/", "a small animal with long ears", "The rabbit is eating a carrot.", "El conejo está comiendo una zanahoria.", ["bunny", "hare"], [], ["pet rabbit", "feed a rabbit"], ["rabbit, rabbit-like"], ["animals", "farm"], "animal"),
      w("horse", "caballo", "noun", "/hɔːrs/", "a large animal that people can ride", "The horse runs across the field.", "El caballo corre por el campo.", ["pony", "mount"], [], ["ride a horse", "strong horse"], ["horse, horseback"], ["animals", "farm"], "animal"),
      w("cow", "vaca", "noun", "/kaʊ/", "a large farm animal that gives milk", "The cow is in the field.", "La vaca está en el campo.", ["cattle", "bovine"], [], ["milk a cow", "farm cow"], ["cow, cattle"], ["animals", "farm"], "animal"),
      w("sheep", "oveja", "noun", "/ʃiːp/", "a farm animal with thick wool", "The sheep are on the hill.", "Las ovejas están en la colina.", ["lamb", "flock"], [], ["flock of sheep", "woolly sheep"], ["sheep, sheepdog"], ["animals", "farm"], "animal"),
      w("bird", "pájaro", "noun", "/bɜːrd/", "an animal with wings and feathers", "A small bird is in the tree.", "Hay un pájaro pequeño en el árbol.", ["fowl", "avian"], [], ["singing bird", "watch a bird"], ["bird, birdhouse"], ["animals", "nature"], "animal"),
      w("feed", "alimentar", "verb", "/fiːd/", "to give food to a person or animal", "We feed the animals every morning.", "Alimentamos a los animales cada mañana.", ["give food", "nourish"], ["starve"], ["feed a pet", "feed the animals"], ["feed, feeder, feeding"], ["animals", "care"], "care action"),
      w("chase", "perseguir", "verb", "/tʃeɪs/", "to run after someone or something", "The dog chases the ball.", "El perro persigue la pelota.", ["follow", "pursue"], ["avoid"], ["chase a bird", "chase a ball"], ["chase, chaser, chasing"], ["animals", "movement"], "movement"),
      w("quiet", "tranquilo", "adjective", "/ˈkwaɪət/", "making little or no noise", "The farm is quiet at night.", "La granja está tranquila por la noche.", ["silent", "peaceful"], ["noisy"], ["quiet place", "stay quiet"], ["quiet, quietly, quietness"], ["animals", "places"], "quality"),
    ], [{ phrase: "The rabbit is eating.", translation: "El conejo está comiendo." }, { phrase: "Please feed the animals.", translation: "Alimenta a los animales, por favor." }, { phrase: "The horse can run fast.", translation: "El caballo puede correr rápido." }, { phrase: "The farm is quiet.", translation: "La granja está tranquila." }], [{ speaker: "A", text: "What animals live on the farm?", translation: "¿Qué animales viven en la granja?" }, { speaker: "B", text: "A horse, a cow, and some sheep.", translation: "Un caballo, una vaca y algunas ovejas." }, { speaker: "A", text: "Who feeds the rabbit?", translation: "¿Quién alimenta al conejo?" }, { speaker: "B", text: "The farmer feeds it every morning.", translation: "El granjero lo alimenta cada mañana." }], { title: "A Visit to the Farm", text: "A farm has many animals. A horse runs in a field, a cow eats grass, and sheep stay together. A farmer feeds the rabbit and watches a small bird in a tree.", translation: "Una granja tiene muchos animales. Un caballo corre por un campo, una vaca come hierba y las ovejas permanecen juntas. Un granjero alimenta al conejo y observa un pájaro pequeño en un árbol." }),
  ],
  A1: [
    u("u48", "School Life", "Talk about classes, materials, homework, and simple results.", [
      w("classmate", "compañero de clase", "noun", "/ˈklæsmeɪt/", "a student in the same class", "My classmate helped me with the exercise.", "Mi compañero de clase me ayudó con el ejercicio.", ["schoolmate", "peer"], [], ["classmate at school", "help a classmate"], ["class, classmate"], ["school", "relationships"], "person"),
      w("subject", "asignatura", "noun", "/ˈsʌbdʒɪkt/", "an area of study at school", "English is my favourite subject.", "El inglés es mi asignatura favorita.", ["course", "field"], [], ["school subject", "study a subject"], ["subject, subjective"], ["school", "learning"], "education"),
      w("homework", "deberes", "noun", "/ˈhoʊmwɜːrk/", "work that a student does at home", "I finished my homework early.", "Terminé mis deberes temprano.", ["assignment", "schoolwork"], ["play"], ["do homework", "homework task"], ["homework"], ["school", "routine"], "education"),
      w("notebook", "cuaderno", "noun", "/ˈnoʊtbʊk/", "a book for writing notes", "Write the answer in your notebook.", "Escribe la respuesta en tu cuaderno.", ["exercise book", "journal"], [], ["school notebook", "open a notebook"], ["note, notebook, noted"], ["school", "writing"], "school object"),
      w("exam", "examen", "noun", "/ɪɡˈzæm/", "an organised test of knowledge or ability", "The exam starts at nine.", "El examen empieza a las nueve.", ["test", "assessment"], [], ["take an exam", "pass an exam"], ["examine, exam, examiner"], ["school", "assessment"], "education"),
      w("grade", "nota", "noun", "/ɡreɪd/", "a mark that shows the quality of work", "She received a high grade.", "Ella recibió una nota alta.", ["mark", "score"], ["failure"], ["get a grade", "high grade"], ["grade, grading"], ["school", "assessment"], "assessment"),
      w("study", "estudiar", "verb", "/ˈstʌdi/", "to spend time learning about a subject", "I study English after school.", "Estudio inglés después de la escuela.", ["learn", "revise"], ["ignore"], ["study hard", "study for an exam"], ["study, student, studying"], ["school", "learning"], "learning action"),
      w("pass", "aprobar", "verb", "/pæs/", "to succeed in a test or examination", "I hope to pass the exam.", "Espero aprobar el examen.", ["succeed", "qualify"], ["fail"], ["pass an exam", "pass a test"], ["pass, passing, passable"], ["school", "success"], "assessment action"),
    ], [{ phrase: "What is your favourite subject?", translation: "¿Cuál es tu asignatura favorita?" }, { phrase: "I have homework tonight.", translation: "Tengo deberes esta noche." }, { phrase: "Write it in your notebook.", translation: "Escríbelo en tu cuaderno." }, { phrase: "I hope I pass the exam.", translation: "Espero aprobar el examen." }], [{ speaker: "A", text: "Are you ready for the exam?", translation: "¿Estás preparado para el examen?" }, { speaker: "B", text: "Almost. I am studying with my classmate.", translation: "Casi. Estoy estudiando con mi compañero de clase." }, { speaker: "A", text: "What subject is it?", translation: "¿De qué asignatura es?" }, { speaker: "B", text: "Science. I hope to get a good grade.", translation: "De ciencias. Espero sacar una buena nota." }], { title: "Preparing for School", text: "Students study different subjects at school. They write in a notebook, complete homework, and prepare for an exam. A classmate can offer help, and a good grade shows successful work.", translation: "Los estudiantes estudian diferentes asignaturas en la escuela. Escriben en un cuaderno, hacen los deberes y se preparan para un examen. Un compañero de clase puede ofrecer ayuda y una buena nota muestra un trabajo exitoso." }),
    u("u49", "At the Station", "Use practical language for trains, tickets, routes, and delays.", [
      w("route", "ruta", "noun", "/ruːt/", "the way between two places", "This bus route goes to the centre.", "Esta ruta de autobús va al centro.", ["way", "path"], [], ["bus route", "train route"], ["route, reroute"], ["travel", "transport"], "navigation"),
      w("timetable", "horario", "noun", "/ˈtaɪmteɪbəl/", "a list showing when transport arrives and leaves", "Check the train timetable.", "Consulta el horario del tren.", ["schedule", "programme"], [], ["train timetable", "timetable information"], ["time, timetable"], ["travel", "time"], "transport"),
      w("fare", "tarifa", "noun", "/fer/", "the money paid for a journey", "The bus fare is two euros.", "La tarifa del autobús es de dos euros.", ["fee", "price"], ["refund"], ["bus fare", "pay the fare"], ["fare, fair"], ["travel", "money"], "transport"),
      w("delay", "retraso", "noun", "/dɪˈleɪ/", "a period when something happens later than planned", "There is a delay on the line.", "Hay un retraso en la línea.", ["holdup", "wait"], ["advance"], ["train delay", "long delay"], ["delay, delayed"], ["travel", "time"], "transport"),
      w("platform", "andén", "noun", "/ˈplætfɔːrm/", "the raised area beside a railway track where passengers wait", "The train leaves from platform three.", "El tren sale del andén tres.", ["station area", "stand"], [], ["platform number", "wait on a platform"], ["platform, platforming"], ["travel", "stations"], "transport"),
      w("passenger", "pasajero", "noun", "/ˈpæsɪndʒər/", "a person travelling in a vehicle", "Every passenger needs a ticket.", "Cada pasajero necesita un billete.", ["traveller", "rider"], ["driver"], ["train passenger", "passenger seat"], ["pass, passenger"], ["travel", "people"], "person"),
      w("board", "subir a bordo", "verb", "/bɔːrd/", "to get onto a ship, aircraft, or public vehicle", "Passengers can board the train now.", "Los pasajeros pueden subir al tren ahora.", ["embark", "get on"], ["leave"], ["board a train", "board a plane"], ["board, boarding"], ["travel", "transport"], "travel action"),
      w("depart", "salir", "verb", "/dɪˈpɑːrt/", "to leave a place, especially to begin a journey", "The train departs at ten.", "El tren sale a las diez.", ["leave", "set off"], ["arrive"], ["depart from a station", "depart on time"], ["depart, departure"], ["travel", "time"], "travel action"),
    ], [{ phrase: "Where is platform three?", translation: "¿Dónde está el andén tres?" }, { phrase: "Please check the timetable.", translation: "Consulta el horario, por favor." }, { phrase: "There is a short delay.", translation: "Hay un pequeño retraso." }, { phrase: "Passengers may now board.", translation: "Los pasajeros ya pueden subir." }], [{ speaker: "A", text: "Does this train go to Oxford?", translation: "¿Este tren va a Oxford?" }, { speaker: "B", text: "Yes, but check the timetable for a delay.", translation: "Sí, pero consulta el horario por si hay un retraso." }, { speaker: "A", text: "Which platform should I use?", translation: "¿Qué andén debo usar?" }, { speaker: "B", text: "Platform three. The train departs soon.", translation: "El andén tres. El tren sale pronto." }], { title: "A Train Journey", text: "Travellers check a route and timetable before going to a station. They buy a ticket, find the right platform, and listen for announcements. If there is a delay, passengers wait until they can board and depart.", translation: "Los viajeros consultan una ruta y un horario antes de ir a una estación. Compran un billete, encuentran el andén correcto y escuchan los avisos. Si hay un retraso, los pasajeros esperan hasta poder subir y salir." }),
  ],
  A2: [
    u("u48", "Household Responsibilities", "Explain chores, shared tasks, and practical arrangements at home.", [
      w("chore", "tarea doméstica", "noun", "/tʃɔːr/", "a routine task that keeps a home clean or organised", "I do one chore before dinner.", "Hago una tarea doméstica antes de cenar.", ["housework", "task"], ["leisure"], ["household chore", "daily chores"], ["chore, choreographer"], ["home", "routine"], "home"),
      w("laundry", "ropa para lavar", "noun", "/ˈlɔːndri/", "clothes and other items that need washing", "The laundry is in the basket.", "La ropa para lavar está en la cesta.", ["washing", "wash"], ["clean clothes"], ["do the laundry", "laundry basket"], ["launder, laundry"], ["home", "routine"], "home"),
      w("dishes", "platos", "noun", "/ˈdɪʃɪz/", "plates, cups, and other things used for eating", "I will wash the dishes.", "Lavaré los platos.", ["tableware", "crockery"], [], ["wash the dishes", "dirty dishes"], ["dish, dishes"], ["home", "food"], "home"),
      w("repair", "reparación", "noun", "/rɪˈper/", "work done to fix something that is damaged", "The repair will take two days.", "La reparación tardará dos días.", ["fix", "restoration"], ["damage"], ["home repair", "repair work"], ["repair, repairable, repairer"], ["home", "maintenance"], "maintenance"),
      w("responsibility", "responsabilidad", "noun", "/rɪˌspɑːnsəˈbɪləti/", "a duty to deal with something or someone", "Sharing responsibility makes life easier.", "Compartir la responsabilidad hace la vida más fácil.", ["duty", "role"], ["irresponsibility"], ["take responsibility", "shared responsibility"], ["responsible, responsibility"], ["home", "relationships"], "social concept"),
      w("tidy", "ordenar", "verb", "/ˈtaɪdi/", "to make a place neat and organised", "Please tidy your room.", "Ordena tu habitación, por favor.", ["organise", "straighten"], ["mess"], ["tidy a room", "tidy up"], ["tidy, tidiness"], ["home", "routine"], "home action"),
      w("share", "compartir", "verb", "/ʃer/", "to use or divide something with another person", "We share the household tasks.", "Compartimos las tareas domésticas.", ["divide", "contribute"], ["keep"], ["share a task", "share responsibility"], ["share, shared, sharing"], ["home", "relationships"], "social action"),
      w("replace", "reemplazar", "verb", "/rɪˈpleɪs/", "to put a new thing where an old one was", "We need to replace the broken bulb.", "Tenemos que reemplazar la bombilla rota.", ["substitute", "renew"], ["keep"], ["replace a part", "replace an appliance"], ["replace, replacement"], ["home", "maintenance"], "maintenance action"),
    ], [{ phrase: "We share the household tasks.", translation: "Compartimos las tareas domésticas." }, { phrase: "I need to do the laundry.", translation: "Tengo que lavar la ropa." }, { phrase: "Please tidy your room.", translation: "Ordena tu habitación, por favor." }, { phrase: "The repair will take two days.", translation: "La reparación tardará dos días." }], [{ speaker: "A", text: "Who is responsible for the laundry?", translation: "¿Quién es responsable de la ropa?" }, { speaker: "B", text: "We share it. I wash, and you tidy the room.", translation: "La compartimos. Yo lavo y tú ordenas la habitación." }, { speaker: "A", text: "What about the broken lamp?", translation: "¿Y la lámpara rota?" }, { speaker: "B", text: "We need to replace it or repair it.", translation: "Tenemos que reemplazarla o repararla." }], { title: "Sharing a Home", text: "A home works well when people share responsibility. They divide chores, wash the dishes, do the laundry, and keep rooms tidy. When something breaks, they arrange a repair or replace it.", translation: "Una casa funciona bien cuando las personas comparten la responsabilidad. Dividen las tareas, lavan los platos, hacen la colada y mantienen las habitaciones ordenadas. Cuando algo se rompe, organizan una reparación o lo reemplazan." }),
    u("u49", "Workplace Meetings", "Participate in meetings, give updates, and agree on next steps.", [
      w("minutes", "acta", "noun", "/ˈmɪnɪts/", "a written record of what was discussed in a meeting", "I will send the meeting minutes.", "Enviaré el acta de la reunión.", ["record", "notes"], [], ["meeting minutes", "write the minutes"], ["minute, minutes"], ["work", "meetings"], "work"),
      w("update", "actualización", "noun", "/ˈʌpdeɪt/", "the latest information about a situation or task", "Here is an update on the project.", "Aquí está la actualización del proyecto.", ["news", "progress report"], ["outdated information"], ["project update", "give an update"], ["update, updated"], ["work", "communication"], "work"),
      w("agenda", "orden del día", "noun", "/əˈdʒendə/", "a list of topics to discuss in a meeting", "The first item on the agenda is the budget.", "El primer punto del orden del día es el presupuesto.", ["schedule", "programme"], [], ["meeting agenda", "item on the agenda"], ["agenda, agendum"], ["work", "planning"], "meetings"),
      w("attendee", "asistente", "noun", "/əˌtenˈdiː/", "a person who attends an event or meeting", "Every attendee received the slides.", "Cada asistente recibió las diapositivas.", ["participant", "guest"], ["absentee"], ["meeting attendee", "registered attendee"], ["attend, attendee, attendance"], ["work", "meetings"], "person"),
      w("proposal", "propuesta", "noun", "/prəˈpoʊzəl/", "a plan or suggestion offered for consideration", "The team discussed my proposal.", "El equipo discutió mi propuesta.", ["suggestion", "plan"], ["rejection"], ["make a proposal", "project proposal"], ["propose, proposal"], ["work", "planning"], "work"),
      w("clarify", "aclarar", "verb", "/ˈklærəfaɪ/", "to make something easier to understand", "Could you clarify the deadline?", "¿Podrías aclarar el plazo?", ["explain", "make clear"], ["confuse"], ["clarify a point", "clarify expectations"], ["clear, clarify, clarification"], ["work", "communication"], "communication action"),
      w("summarize", "resumir", "verb", "/ˈsʌməraɪz/", "to give the main points in a shorter form", "Can you summarize the discussion?", "¿Puedes resumir la discusión?", ["outline", "recap"], ["expand"], ["summarize a report", "summarize the meeting"], ["summary, summarize"], ["work", "writing"], "communication action"),
      w("follow-up", "seguimiento", "noun", "/ˈfɑːloʊ ʌp/", "an action or message that comes after an earlier one", "I will send a follow-up tomorrow.", "Enviaré un seguimiento mañana.", ["next step", "continuation"], ["first contact"], ["follow-up email", "follow-up meeting"], ["follow, follow-up"], ["work", "communication"], "work"),
    ], [{ phrase: "What is on the agenda?", translation: "¿Qué hay en el orden del día?" }, { phrase: "Could you clarify the deadline?", translation: "¿Podrías aclarar el plazo?" }, { phrase: "I will send a follow-up.", translation: "Enviaré un seguimiento." }, { phrase: "Please summarize the discussion.", translation: "Resume la discusión, por favor." }], [{ speaker: "A", text: "What is the first agenda item?", translation: "¿Cuál es el primer punto del orden del día?" }, { speaker: "B", text: "A project update and a new proposal.", translation: "Una actualización del proyecto y una nueva propuesta." }, { speaker: "A", text: "Could you clarify the next step?", translation: "¿Podrías aclarar el siguiente paso?" }, { speaker: "B", text: "I will summarize it in the follow-up email.", translation: "Lo resumiré en el correo de seguimiento." }], { title: "A Productive Meeting", text: "A clear agenda helps a meeting stay focused. Attendees share updates, discuss a proposal, and clarify questions. At the end, someone summarizes the decisions, records the minutes, and sends a follow-up.", translation: "Un orden del día claro ayuda a que una reunión se mantenga centrada. Los asistentes comparten actualizaciones, discuten una propuesta y aclaran preguntas. Al final, alguien resume las decisiones, registra el acta y envía un seguimiento." }),
  ],
  B1: [
    u("u48", "Food and Wellbeing", "Discuss eating habits, choices, and the social role of food.", [
      w("ingredient", "ingrediente", "noun", "/ɪnˈɡriːdiənt/", "one of the foods used to make a dish", "Fresh ingredients improve the flavour.", "Los ingredientes frescos mejoran el sabor.", ["component", "element"], [], ["main ingredient", "fresh ingredients"], ["ingredient"], ["food", "cooking"], "food"),
      w("flavour", "sabor", "noun", "/ˈfleɪvər/", "the particular taste of food or drink", "The soup has a rich flavour.", "La sopa tiene un sabor intenso.", ["taste", "savour"], ["blandness"], ["rich flavour", "add flavour"], ["flavour, flavourful"], ["food", "senses"], "food"),
      w("portion", "porción", "noun", "/ˈpɔːrʃən/", "an amount of food served to one person", "The restaurant serves large portions.", "El restaurante sirve porciones grandes.", ["serving", "helping"], [], ["small portion", "portion size"], ["portion, portioned"], ["food", "health"], "food"),
      w("dietary", "dietético", "adjective", "/ˈdaɪəteri/", "relating to the food someone eats or should eat", "The menu includes dietary information.", "El menú incluye información dietética.", ["nutritional", "food-related"], [], ["dietary choice", "dietary needs"], ["diet, dietary"], ["food", "health"], "quality"),
      w("sustainable", "sostenible", "adjective", "/səˈsteɪnəbəl/", "able to continue without causing serious harm or using resources up", "Local food can be more sustainable.", "La comida local puede ser más sostenible.", ["durable", "responsible"], ["wasteful"], ["sustainable farming", "sustainable food"], ["sustain, sustainable, sustainability"], ["food", "environment"], "quality"),
      w("consume", "consumir", "verb", "/kənˈsuːm/", "to eat, drink, use, or buy something", "People consume less sugar when labels are clear.", "Las personas consumen menos azúcar cuando las etiquetas son claras.", ["use", "eat"], ["produce"], ["consume food", "consume energy"], ["consume, consumer, consumption"], ["food", "economy"], "action"),
      w("prepare", "preparar", "verb", "/prɪˈper/", "to make something ready for use or eating", "We prepare the vegetables together.", "Preparamos las verduras juntos.", ["make ready", "arrange"], ["neglect"], ["prepare a meal", "prepare ingredients"], ["prepare, preparation, prepared"], ["food", "routine"], "cooking action"),
      w("nutritious", "nutritivo", "adjective", "/nuˈtrɪʃəs/", "containing substances that are good for health", "Beans are cheap and nutritious.", "Las judías son baratas y nutritivas.", ["healthy", "nourishing"], ["unhealthy"], ["nutritious meal", "nutritious food"], ["nutrition, nutritious"], ["food", "health"], "quality"),
    ], [{ phrase: "The dish contains fresh ingredients.", translation: "El plato contiene ingredientes frescos." }, { phrase: "The portions are quite large.", translation: "Las porciones son bastante grandes." }, { phrase: "We want a sustainable diet.", translation: "Queremos una dieta sostenible." }, { phrase: "This meal is nutritious.", translation: "Esta comida es nutritiva." }], [{ speaker: "A", text: "Why did you choose this dish?", translation: "¿Por qué elegiste este plato?" }, { speaker: "B", text: "It has nutritious ingredients and a good flavour.", translation: "Tiene ingredientes nutritivos y buen sabor." }, { speaker: "A", text: "Is the portion too large?", translation: "¿Es demasiado grande la porción?" }, { speaker: "B", text: "No, we can share it and avoid waste.", translation: "No, podemos compartirla y evitar el desperdicio." }], { title: "Choosing Food Wisely", text: "Food choices affect health, culture, and the environment. A nutritious meal can use local ingredients and a sensible portion. People can prepare food carefully, consume less waste, and consider whether their diet is sustainable.", translation: "Las decisiones alimentarias afectan a la salud, la cultura y el medio ambiente. Una comida nutritiva puede utilizar ingredientes locales y una porción razonable. Las personas pueden preparar la comida con cuidado, consumir menos desperdicio y considerar si su dieta es sostenible." }),
    u("u49", "Community Projects", "Describe volunteering, cooperation, and practical local change.", [
      w("volunteer", "voluntario", "noun", "/ˌvɑːlənˈtɪr/", "a person who offers time or work without payment", "A volunteer helped clean the river.", "Un voluntario ayudó a limpiar el río.", ["helper", "unpaid worker"], ["employee"], ["community volunteer", "volunteer work"], ["volunteer, voluntary"], ["community", "work"], "person"),
      w("neighbourhood", "barrio", "noun", "/ˈneɪbərhʊd/", "an area where people live near one another", "The neighbourhood organised a clean-up.", "El barrio organizó una limpieza.", ["district", "community"], [], ["local neighbourhood", "neighbourhood project"], ["neighbour, neighbourhood"], ["community", "city"], "place"),
      w("funding", "financiación", "noun", "/ˈfʌndɪŋ/", "money provided for a project or organisation", "The project needs public funding.", "El proyecto necesita financiación pública.", ["finance", "support"], ["debt"], ["public funding", "secure funding"], ["fund, funding, funded"], ["community", "money"], "finance"),
      w("campaign", "campaña", "noun", "/kæmˈpeɪn/", "an organised effort to achieve a social or political goal", "The campaign raised awareness about recycling.", "La campaña concienció sobre el reciclaje.", ["drive", "movement"], ["inaction"], ["public campaign", "launch a campaign"], ["campaign, campaigner"], ["community", "society"], "social action"),
      w("access", "acceso", "noun", "/ˈækses/", "the opportunity or right to use or reach something", "The project improves access to sport.", "El proyecto mejora el acceso al deporte.", ["entry", "availability"], ["exclusion"], ["equal access", "access to services"], ["access, accessible, accessibility"], ["community", "rights"], "social concept"),
      w("organise", "organizar", "verb", "/ˈɔːrɡənaɪz/", "to plan and arrange an activity or event", "Residents organised a food drive.", "Los residentes organizaron una recogida de alimentos.", ["arrange", "coordinate"], ["disorganise"], ["organise an event", "organise a campaign"], ["organise, organisation, organised"], ["community", "planning"], "planning action"),
      w("contribute", "contribuir", "verb", "/kənˈtrɪbjuːt/", "to give time, money, or ideas to something", "Everyone can contribute an idea.", "Todos pueden contribuir con una idea.", ["give", "add"], ["withhold"], ["contribute to a project", "contribute money"], ["contribute, contribution, contributor"], ["community", "work"], "social action"),
      w("inclusive", "inclusivo", "adjective", "/ɪnˈkluːsɪv/", "welcoming and involving all kinds of people", "The new centre is inclusive.", "El nuevo centro es inclusivo.", ["welcoming", "open"], ["exclusive"], ["inclusive community", "inclusive policy"], ["include, inclusive, inclusion"], ["community", "rights"], "quality"),
    ], [{ phrase: "The campaign raised awareness.", translation: "La campaña concienció." }, { phrase: "Everyone can contribute.", translation: "Todos pueden contribuir." }, { phrase: "The project improves access.", translation: "El proyecto mejora el acceso." }, { phrase: "We need inclusive services.", translation: "Necesitamos servicios inclusivos." }], [{ speaker: "A", text: "How can residents help?", translation: "¿Cómo pueden ayudar los residentes?" }, { speaker: "B", text: "They can volunteer or contribute ideas.", translation: "Pueden hacer voluntariado o contribuir con ideas." }, { speaker: "A", text: "How will the project get funding?", translation: "¿Cómo conseguirá financiación el proyecto?" }, { speaker: "B", text: "A campaign will ask for public support.", translation: "Una campaña pedirá apoyo público." }], { title: "A Stronger Neighbourhood", text: "Community projects grow when people cooperate. Volunteers organise campaigns, contribute ideas, and improve access to services. With fair funding, an inclusive neighbourhood can solve practical problems and build trust.", translation: "Los proyectos comunitarios crecen cuando las personas cooperan. Los voluntarios organizan campañas, aportan ideas y mejoran el acceso a los servicios. Con una financiación justa, un barrio inclusivo puede resolver problemas prácticos y construir confianza." }),
  ],
  B2: [
    u("u48", "Climate Policy", "Analyse policy choices, adaptation, and the distribution of environmental costs.", [
      w("emission", "emisión", "noun", "/ɪˈmɪʃən/", "a gas or substance released into the environment", "The policy aims to reduce carbon emissions.", "La política pretende reducir las emisiones de carbono.", ["discharge", "release"], ["absorption"], ["carbon emission", "reduce emissions"], ["emit, emission, emissive"], ["environment", "policy"], "environment"),
      w("adaptation", "adaptación", "noun", "/ˌædæpˈteɪʃən/", "a change made to suit new conditions", "Climate adaptation requires long-term planning.", "La adaptación climática requiere planificación a largo plazo.", ["adjustment", "modification"], ["rigidity"], ["climate adaptation", "adaptation strategy"], ["adapt, adaptation, adaptive"], ["environment", "planning"], "policy"),
      w("mitigation", "mitigación", "noun", "/ˌmɪtɪˈɡeɪʃən/", "action that reduces the harmful effects of something", "Mitigation can slow the rise in temperature.", "La mitigación puede ralentizar el aumento de la temperatura.", ["reduction", "relief"], ["aggravation"], ["risk mitigation", "mitigation measure"], ["mitigate, mitigation"], ["environment", "policy"], "policy"),
      w("resilience", "resiliencia", "noun", "/rɪˈzɪliəns/", "the ability to recover from difficulty or change", "Cities need resilience against floods.", "Las ciudades necesitan resiliencia frente a las inundaciones.", ["strength", "robustness"], ["fragility"], ["build resilience", "community resilience"], ["resilient, resilience"], ["environment", "society"], "quality"),
      w("subsidy", "subsidio", "noun", "/ˈsʌbsədi/", "money given by an organisation to support an activity", "The subsidy supports renewable energy.", "El subsidio apoya la energía renovable.", ["grant", "allowance"], ["tax"], ["government subsidy", "energy subsidy"], ["subsidise, subsidy"], ["policy", "money"], "policy"),
      w("decarbonize", "descarbonizar", "verb", "/diːˈkɑːrbənaɪz/", "to reduce or remove carbon emissions from an activity", "Industries must decarbonize gradually.", "Las industrias deben descarbonizarse gradualmente.", ["clean up", "reduce carbon"], ["pollute"], ["decarbonize transport", "decarbonize industry"], ["carbon, decarbonize, decarbonization"], ["environment", "industry"], "policy action"),
      w("allocate", "asignar", "verb", "/ˈæləkeɪt/", "to decide how money, time, or resources will be used", "Governments allocate funds for adaptation.", "Los gobiernos asignan fondos para la adaptación.", ["assign", "distribute"], ["withhold"], ["allocate resources", "allocate funding"], ["allocate, allocation"], ["policy", "planning"], "policy action"),
      w("equitable", "equitativo", "adjective", "/ˈekwɪtəbəl/", "fair and reasonable for different people or groups", "The transition should be equitable.", "La transición debe ser equitativa.", ["fair", "just"], ["unfair"], ["equitable transition", "equitable access"], ["equity, equitable"], ["policy", "rights"], "quality"),
    ], [{ phrase: "The policy targets carbon emissions.", translation: "La política se dirige a las emisiones de carbono." }, { phrase: "Adaptation needs reliable funding.", translation: "La adaptación necesita financiación fiable." }, { phrase: "Resources must be allocated equitably.", translation: "Los recursos deben asignarse equitativamente." }, { phrase: "Cities are building resilience.", translation: "Las ciudades están construyendo resiliencia." }], [{ speaker: "A", text: "Should policy focus on mitigation or adaptation?", translation: "¿Debe la política centrarse en la mitigación o la adaptación?" }, { speaker: "B", text: "Both. Emissions must fall, but communities also need resilience.", translation: "En ambas. Las emisiones deben bajar, pero las comunidades también necesitan resiliencia." }, { speaker: "A", text: "How should funding be allocated?", translation: "¿Cómo deben asignarse los fondos?" }, { speaker: "B", text: "In an equitable way, with support for vulnerable regions.", translation: "De forma equitativa, con apoyo para las regiones vulnerables." }], { title: "A Fair Climate Transition", text: "Climate policy combines mitigation with adaptation. Governments can reduce emissions, subsidise clean energy, and allocate funds to communities facing risk. A resilient transition must also be equitable, because environmental costs are not shared equally.", translation: "La política climática combina la mitigación con la adaptación. Los gobiernos pueden reducir las emisiones, subvencionar la energía limpia y asignar fondos a las comunidades expuestas al riesgo. Una transición resiliente también debe ser equitativa, porque los costes ambientales no se comparten por igual." }),
    u("u49", "Psychology and Behaviour", "Discuss motivation, habits, and how people make decisions.", [
      w("cognition", "cognición", "noun", "/kɑːɡˈnɪʃən/", "the mental processes involved in knowing and thinking", "The study examines cognition and attention.", "El estudio examina la cognición y la atención.", ["thinking", "mental process"], ["unconsciousness"], ["human cognition", "cognitive process"], ["cognitive, cognition"], ["psychology", "mind"], "psychology"),
      w("bias", "sesgo", "noun", "/ˈbaɪəs/", "an unfair preference that influences judgement", "The experiment tried to reduce bias.", "El experimento intentó reducir el sesgo.", ["prejudice", "inclination"], ["objectivity"], ["cognitive bias", "reduce bias"], ["bias, biased"], ["psychology", "reasoning"], "reasoning"),
      w("stimulus", "estímulo", "noun", "/ˈstɪmjələs/", "something that causes a reaction or response", "The sound was a strong stimulus.", "El sonido fue un estímulo fuerte.", ["prompt", "trigger"], ["response"], ["external stimulus", "visual stimulus"], ["stimulate, stimulus, stimulation"], ["psychology", "science"], "psychology"),
      w("reward", "recompensa", "noun", "/rɪˈwɔːrd/", "something given in recognition of effort or achievement", "A small reward can reinforce a habit.", "Una pequeña recompensa puede reforzar un hábito.", ["prize", "benefit"], ["penalty"], ["give a reward", "reward system"], ["reward, rewarding"], ["psychology", "motivation"], "psychology"),
      w("impulse", "impulso", "noun", "/ˈɪmpʌls/", "a sudden strong desire to act", "He bought it on impulse.", "Lo compró por impulso.", ["urge", "instinct"], ["restraint"], ["act on impulse", "impulse purchase"], ["impulse, impulsive, impulsively"], ["psychology", "shopping"], "psychology"),
      w("reinforce", "reforzar", "verb", "/ˌriːɪnˈfɔːrs/", "to make a behaviour or idea stronger", "Praise can reinforce good habits.", "Los elogios pueden reforzar los buenos hábitos.", ["strengthen", "support"], ["weaken"], ["reinforce a habit", "reinforce a belief"], ["force, reinforce, reinforcement"], ["psychology", "learning"], "psychology action"),
      w("internalize", "interiorizar", "verb", "/ɪnˈtɜːrnəlaɪz/", "to accept an idea or value as part of your own thinking", "Children internalize social expectations.", "Los niños interiorizan las expectativas sociales.", ["absorb", "adopt"], ["reject"], ["internalize a value", "internalize a rule"], ["internal, internalize, internalization"], ["psychology", "society"], "thinking action"),
      w("deliberate", "deliberado", "adjective", "/dɪˈlɪbərət/", "done after careful thought rather than suddenly", "She made a deliberate decision.", "Tomó una decisión deliberada.", ["intentional", "considered"], ["accidental"], ["deliberate choice", "deliberate action"], ["deliberate, deliberately, deliberation"], ["psychology", "decision-making"], "quality"),
    ], [{ phrase: "Cognitive bias can affect judgement.", translation: "El sesgo cognitivo puede afectar al juicio." }, { phrase: "A reward can reinforce a habit.", translation: "Una recompensa puede reforzar un hábito." }, { phrase: "Do not act on impulse.", translation: "No actúes por impulso." }, { phrase: "Make a deliberate decision.", translation: "Toma una decisión deliberada." }], [{ speaker: "A", text: "Why do people act on impulse?", translation: "¿Por qué actúan las personas por impulso?" }, { speaker: "B", text: "A strong stimulus can trigger a quick reward response.", translation: "Un estímulo fuerte puede provocar una respuesta rápida de recompensa." }, { speaker: "A", text: "How can we make better choices?", translation: "¿Cómo podemos tomar mejores decisiones?" }, { speaker: "B", text: "We can notice bias and make a deliberate pause.", translation: "Podemos reconocer el sesgo y hacer una pausa deliberada." }], { title: "Understanding Choices", text: "Human behaviour is shaped by cognition, emotion, and context. A stimulus may trigger an impulse, while a reward can reinforce a habit. By noticing bias and pausing before action, people can make more deliberate choices.", translation: "El comportamiento humano está formado por la cognición, la emoción y el contexto. Un estímulo puede provocar un impulso, mientras que una recompensa puede reforzar un hábito. Al reconocer el sesgo y hacer una pausa antes de actuar, las personas pueden tomar decisiones más deliberadas." }),
  ],
  C1: [
    u("u48", "Law and Rights", "Analyse legal principles, protections, and access to justice.", [
      w("jurisdiction", "jurisdicción", "noun", "/ˌdʒʊrɪsˈdɪkʃən/", "the authority of a court or institution over a matter", "The case falls within national jurisdiction.", "El caso está dentro de la jurisdicción nacional.", ["authority", "legal power"], [], ["court jurisdiction", "within jurisdiction"], ["jurisprudence, jurisdiction"], ["law", "government"], "law"),
      w("legislation", "legislación", "noun", "/ˌledʒɪˈsleɪʃən/", "laws considered together or the process of making laws", "New legislation protects tenants.", "La nueva legislación protege a los inquilinos.", ["law", "statute"], ["lawlessness"], ["pass legislation", "new legislation"], ["legislate, legislation, legislative"], ["law", "policy"], "law"),
      w("consent", "consentimiento", "noun", "/kənˈsent/", "permission given freely after understanding what will happen", "The procedure requires informed consent.", "El procedimiento requiere consentimiento informado.", ["permission", "approval"], ["refusal"], ["informed consent", "give consent"], ["consent, consensual"], ["law", "ethics"], "law"),
      w("remedy", "recurso", "noun", "/ˈremədi/", "a way to correct a legal wrong or problem", "The court ordered an effective remedy.", "El tribunal ordenó un recurso efectivo.", ["solution", "redress"], ["harm"], ["legal remedy", "seek a remedy"], ["remedy, remedial"], ["law", "justice"], "law"),
      w("precedent", "precedente", "noun", "/ˈpresɪdənt/", "an earlier decision that may guide a later one", "The judgement established an important precedent.", "La sentencia estableció un precedente importante.", ["example", "model"], ["novelty"], ["legal precedent", "set a precedent"], ["precede, precedent"], ["law", "history"], "law"),
      w("litigate", "litigar", "verb", "/ˈlɪtɪɡeɪt/", "to take a disagreement to court", "The parties decided to litigate the dispute.", "Las partes decidieron litigar la disputa.", ["take to court", "sue"], ["settle"], ["litigate a claim", "litigate in court"], ["litigate, litigation, litigator"], ["law", "conflict"], "law action"),
      w("uphold", "mantener", "verb", "/ʌpˈhoʊld/", "to support or confirm a decision or principle", "The court upheld the right to appeal.", "El tribunal mantuvo el derecho de apelación.", ["support", "confirm"], ["overturn"], ["uphold a decision", "uphold rights"], ["hold, uphold"], ["law", "justice"], "law action"),
      w("arbitrary", "arbitrario", "adjective", "/ˈɑːrbətreri/", "based on personal choice rather than a fair reason", "The rule appears arbitrary.", "La regla parece arbitraria.", ["random", "unreasoned"], ["rational"], ["arbitrary decision", "arbitrary power"], ["arbitrate, arbitrary, arbitrarily"], ["law", "government"], "quality"),
    ], [{ phrase: "The case falls within the court's jurisdiction.", translation: "El caso está dentro de la jurisdicción del tribunal." }, { phrase: "The law requires informed consent.", translation: "La ley requiere consentimiento informado." }, { phrase: "The court upheld the decision.", translation: "El tribunal mantuvo la decisión." }, { phrase: "The rule seems arbitrary.", translation: "La regla parece arbitraria." }], [{ speaker: "A", text: "What remedy is available?", translation: "¿Qué recurso está disponible?" }, { speaker: "B", text: "The court can order compensation under the legislation.", translation: "El tribunal puede ordenar una compensación conforme a la legislación." }, { speaker: "A", text: "Is there a legal precedent?", translation: "¿Existe un precedente legal?" }, { speaker: "B", text: "Yes, and the court upheld it in a later case.", translation: "Sí, y el tribunal lo mantuvo en un caso posterior." }], { title: "Rights in Practice", text: "Legal rights depend on more than formal legislation. People need access to a court within the correct jurisdiction, informed consent in sensitive cases, and an effective remedy when a right is breached. Precedent can guide decisions, but arbitrary power must be challenged.", translation: "Los derechos legales dependen de algo más que la legislación formal. Las personas necesitan acceso a un tribunal dentro de la jurisdicción correcta, consentimiento informado en los casos sensibles y un recurso efectivo cuando se vulnera un derecho. El precedente puede guiar las decisiones, pero el poder arbitrario debe ser cuestionado." }),
    u("u49", "Media and Public Trust", "Evaluate credibility, misinformation, and responsible public communication.", [
      w("misinformation", "información falsa", "noun", "/ˌmɪsɪnfərˈmeɪʃən/", "false or inaccurate information shared without necessarily intending harm", "Misinformation spreads quickly online.", "La información falsa se propaga rápidamente en internet.", ["inaccuracy", "false information"], ["verified information"], ["combat misinformation", "misinformation campaign"], ["inform, information, misinformation"], ["media", "society"], "media"),
      w("credibility", "credibilidad", "noun", "/ˌkredəˈbɪləti/", "the quality of being trusted or believed", "The source has strong credibility.", "La fuente tiene mucha credibilidad.", ["trustworthiness", "reliability"], ["unreliability"], ["source credibility", "question credibility"], ["credible, credibility"], ["media", "research"], "quality"),
      w("editorial", "editorial", "adjective", "/ˌedɪˈtɔːriəl/", "relating to the opinions or decisions of an editor or publication", "The editorial policy is publicly available.", "La política editorial está disponible públicamente.", ["journalistic", "publishing"], ["personal"], ["editorial policy", "editorial decision"], ["edit, editor, editorial"], ["media", "writing"], "media"),
      w("verification", "verificación", "noun", "/ˌverɪfɪˈkeɪʃən/", "the process of checking that something is true or accurate", "The report requires independent verification.", "El informe requiere verificación independiente.", ["confirmation", "checking"], ["assumption"], ["fact verification", "independent verification"], ["verify, verification, verifiable"], ["media", "research"], "research"),
      w("accountability", "rendición de cuentas", "noun", "/əˌkaʊntəˈbɪləti/", "the duty to explain actions and accept responsibility", "Public accountability strengthens institutions.", "La rendición de cuentas pública fortalece las instituciones.", ["responsibility", "answerability"], ["impunity"], ["public accountability", "demand accountability"], ["account, accountable, accountability"], ["media", "government"], "public life"),
      w("distort", "distorsionar", "verb", "/dɪˈstɔːrt/", "to change information so that it gives a false impression", "A short clip can distort the context.", "Un clip corto puede distorsionar el contexto.", ["misrepresent", "twist"], ["clarify"], ["distort information", "distort a message"], ["distort, distortion"], ["media", "communication"], "communication action"),
      w("corroborate", "corroborar", "verb", "/kəˈrɑːbəreɪt/", "to support a statement with additional evidence", "The second source corroborates the claim.", "La segunda fuente corrobora la afirmación.", ["confirm", "support"], ["contradict"], ["corroborate evidence", "corroborate a report"], ["corroborate, corroboration"], ["media", "research"], "research action"),
      w("transparent", "transparente", "adjective", "/trænsˈperənt/", "open and easy to understand or examine", "The organisation has a transparent process.", "La organización tiene un proceso transparente.", ["open", "clear"], ["secretive"], ["transparent process", "transparent communication"], ["transparency, transparent"], ["media", "government"], "quality"),
    ], [{ phrase: "Check the source before sharing it.", translation: "Comprueba la fuente antes de compartirlo." }, { phrase: "The claim needs independent verification.", translation: "La afirmación necesita verificación independiente." }, { phrase: "The clip distorts the context.", translation: "El clip distorsiona el contexto." }, { phrase: "Public communication should be transparent.", translation: "La comunicación pública debe ser transparente." }], [{ speaker: "A", text: "Why is source credibility important?", translation: "¿Por qué es importante la credibilidad de una fuente?" }, { speaker: "B", text: "It helps people distinguish evidence from misinformation.", translation: "Ayuda a las personas a distinguir la evidencia de la información falsa." }, { speaker: "A", text: "How can journalists corroborate a claim?", translation: "¿Cómo pueden los periodistas corroborar una afirmación?" }, { speaker: "B", text: "They can use independent sources and transparent verification.", translation: "Pueden usar fuentes independientes y una verificación transparente." }], { title: "Trustworthy Information", text: "Public trust is difficult to build and easy to lose. Responsible media verifies claims, explains its editorial choices, and avoids distorting context. Accountability and transparent correction help communities respond to misinformation.", translation: "La confianza pública es difícil de construir y fácil de perder. Los medios responsables verifican las afirmaciones, explican sus decisiones editoriales y evitan distorsionar el contexto. La rendición de cuentas y la corrección transparente ayudan a las comunidades a responder a la información falsa." }),
  ],
  C2: [
    u("u48", "Aesthetics and Art", "Discuss artistic value, interpretation, and the experience of beauty.", [
      w("aesthetics", "estética", "noun", "/esˈθetɪks/", "the study of beauty, art, and artistic experience", "The course introduces aesthetics and criticism.", "El curso introduce la estética y la crítica.", ["philosophy of art", "art theory"], [], ["aesthetic judgement", "aesthetics of form"], ["aesthetic, aesthetics"], ["philosophy", "arts"], "philosophy"),
      w("beauty", "belleza", "noun", "/ˈbjuːti/", "a quality that gives pleasure through the senses or mind", "The poem finds beauty in ordinary life.", "El poema encuentra belleza en la vida cotidiana.", ["loveliness", "grace"], ["ugliness"], ["sense of beauty", "natural beauty"], ["beautiful, beauty, beautify"], ["arts", "emotion"], "arts"),
      w("sublime", "sublime", "adjective", "/səˈblaɪm/", "so impressive or powerful that it inspires awe", "The landscape had a sublime quality.", "El paisaje tenía una cualidad sublime.", ["majestic", "awe-inspiring"], ["ordinary"], ["sublime beauty", "the sublime"], ["sublime, sublimity"], ["arts", "nature"], "quality"),
      w("form", "forma", "noun", "/fɔːrm/", "the visible or organised structure of an artistic work", "The form of the sonnet shapes its meaning.", "La forma del soneto determina su significado.", ["shape", "structure"], ["content"], ["artistic form", "formal analysis"], ["form, formal, formation"], ["arts", "language"], "arts"),
      w("medium", "medio artístico", "noun", "/ˈmiːdiəm/", "the material or method used to create art", "Oil paint is her preferred medium.", "La pintura al óleo es su medio artístico preferido.", ["material", "channel"], [], ["artistic medium", "mixed media"], ["mediate, medium, multimedia"], ["arts", "technology"], "arts"),
      w("evoke", "evocar", "verb", "/ɪˈvoʊk/", "to bring a feeling, memory, or image into the mind", "The music evokes a sense of loss.", "La música evoca una sensación de pérdida.", ["summon", "recall"], ["suppress"], ["evoke emotion", "evoke a memory"], ["evoke, evocation"], ["arts", "emotion"], "arts action"),
      w("depict", "representar", "verb", "/dɪˈpɪkt/", "to show or represent someone or something in art", "The painting depicts a crowded street.", "La pintura representa una calle abarrotada.", ["portray", "represent"], ["hide"], ["depict a scene", "depict a figure"], ["depict, depiction"], ["arts", "visual culture"], "arts action"),
      w("ambiguous", "ambiguo", "adjective", "/æmˈbɪɡjuəs/", "having more than one possible meaning or interpretation", "The ending remains deliberately ambiguous.", "El final sigue siendo deliberadamente ambiguo.", ["unclear", "equivocal"], ["unambiguous"], ["ambiguous image", "deliberately ambiguous"], ["ambiguity, ambiguous"], ["arts", "language"], "quality"),
    ], [{ phrase: "The work evokes a powerful memory.", translation: "La obra evoca un recuerdo poderoso." }, { phrase: "The painting depicts an ordinary street.", translation: "La pintura representa una calle cotidiana." }, { phrase: "Form shapes the meaning of the poem.", translation: "La forma determina el significado del poema." }, { phrase: "The ending is deliberately ambiguous.", translation: "El final es deliberadamente ambiguo." }], [{ speaker: "A", text: "What makes the landscape sublime?", translation: "¿Qué hace sublime al paisaje?" }, { speaker: "B", text: "Its scale evokes awe beyond ordinary beauty.", translation: "Su escala evoca un asombro que supera la belleza común." }, { speaker: "A", text: "Does the medium affect interpretation?", translation: "¿Afecta el medio a la interpretación?" }, { speaker: "B", text: "Yes. Form and medium shape what the work depicts.", translation: "Sí. La forma y el medio determinan lo que representa la obra." }], { title: "Seeing Art Differently", text: "Aesthetic experience depends on form, medium, and interpretation. Art can depict the familiar while making it strange, evoke memories, or approach the sublime. An ambiguous work may resist one final explanation and invite several ways of seeing.", translation: "La experiencia estética depende de la forma, el medio y la interpretación. El arte puede representar lo familiar mientras lo vuelve extraño, evocar recuerdos o acercarse a lo sublime. Una obra ambigua puede resistirse a una explicación final e invitar a varias formas de ver." }),
    u("u49", "Science and Explanation", "Evaluate models, theories, and the difference between explanation and prediction.", [
      w("paradigm", "paradigma", "noun", "/ˈpærədaɪm/", "a general model that shapes how a field understands problems", "The discovery challenged the prevailing paradigm.", "El descubrimiento desafió el paradigma dominante.", ["model", "framework"], [], ["scientific paradigm", "paradigm shift"], ["paradigm, paradigmatic"], ["science", "philosophy"], "science"),
      w("causality", "causalidad", "noun", "/kɔːˈzæləti/", "the relationship in which one event produces another", "The study separates correlation from causality.", "El estudio separa la correlación de la causalidad.", ["cause and effect", "causal connection"], ["coincidence"], ["causal relationship", "establish causality"], ["cause, causal, causality"], ["science", "reasoning"], "reasoning"),
      w("observation", "observación", "noun", "/ˌɑːbzərˈveɪʃən/", "the act of carefully noticing or measuring something", "The theory began with an observation.", "La teoría comenzó con una observación.", ["notice", "monitoring"], ["inattention"], ["direct observation", "make an observation"], ["observe, observation, observational"], ["science", "research"], "research"),
      w("model", "modelo", "noun", "/ˈmɑːdəl/", "a simplified representation used to explain or predict something", "The model predicts changes in temperature.", "El modelo predice cambios de temperatura.", ["representation", "framework"], ["reality"], ["mathematical model", "predictive model"], ["model, modelling"], ["science", "research"], "science"),
      w("explanation", "explicación", "noun", "/ˌekspləˈneɪʃən/", "a description of why or how something happens", "The explanation fits the available evidence.", "La explicación encaja con la evidencia disponible.", ["account", "interpretation"], ["mystery"], ["scientific explanation", "offer an explanation"], ["explain, explanation, explanatory"], ["science", "language"], "reasoning"),
      w("falsifiable", "falsable", "adjective", "/ˈfæl səfaɪəbəl/", "able to be tested and shown to be false", "A useful hypothesis should be falsifiable.", "Una hipótesis útil debe ser falsable.", ["testable", "disprovable"], ["untestable"], ["falsifiable hypothesis", "falsifiable claim"], ["falsify, falsifiable, falsification"], ["science", "philosophy"], "quality"),
      w("infer", "inferir", "verb", "/ɪnˈfɜːr/", "to reach a conclusion from evidence rather than direct information", "We can infer the cause from the pattern.", "Podemos inferir la causa a partir del patrón.", ["deduce", "conclude"], ["observe directly"], ["infer a result", "infer from evidence"], ["infer, inference, inferential"], ["science", "reasoning"], "reasoning action"),
      w("replicable", "replicable", "adjective", "/ˈreplɪkəbəl/", "able to be repeated with similar results", "The experiment must be replicable.", "El experimento debe ser replicable.", ["repeatable", "reproducible"], ["unique"], ["replicable result", "replicable experiment"], ["replicate, replication, replicable"], ["science", "research"], "quality"),
    ], [{ phrase: "The model helps explain the observation.", translation: "El modelo ayuda a explicar la observación." }, { phrase: "Correlation is not causality.", translation: "La correlación no es causalidad." }, { phrase: "A hypothesis should be falsifiable.", translation: "Una hipótesis debe ser falsable." }, { phrase: "The result must be replicable.", translation: "El resultado debe ser replicable." }], [{ speaker: "A", text: "What does the model explain?", translation: "¿Qué explica el modelo?" }, { speaker: "B", text: "It explains the pattern observed in the data.", translation: "Explica el patrón observado en los datos." }, { speaker: "A", text: "Can we infer causality from it?", translation: "¿Podemos inferir causalidad a partir de él?" }, { speaker: "B", text: "Only if the hypothesis is testable and the result replicable.", translation: "Solo si la hipótesis es comprobable y el resultado replicable." }], { title: "What Counts as an Explanation?", text: "Science uses observation, models, and theories to explain and predict phenomena. A model may reveal a pattern without proving causality. Strong explanations make testable claims, allow inference from evidence, and produce replicable results.", translation: "La ciencia utiliza observaciones, modelos y teorías para explicar y predecir fenómenos. Un modelo puede revelar un patrón sin demostrar la causalidad. Las explicaciones sólidas hacen afirmaciones comprobables, permiten inferencias a partir de la evidencia y producen resultados replicables." }),
  ],
};
