import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/** Reviewed vocabulary for the existing B1/B2/C1 u24 and u25 units. */
export const ENGLISH_B1_B2_C1_U24_U25_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u24: [
      reviewed({ word: "anchor", translation: "مذيع أخبار", pos: "noun", ipa: "/ˈæŋkər/", definition: "a person who presents a television or radio news programme", example: "The evening anchor reported on the local elections.", exampleTranslation: "قدم مذيع الأخبار المسائي تقريرًا عن الانتخابات المحلية.", category: "media and news", tags: ["news", "broadcasting"], synonyms: ["presenter", "news host"] }),
      reviewed({ word: "press briefing", translation: "إحاطة صحفية", pos: "noun", ipa: "/pres ˈbriːfɪŋ/", definition: "a meeting at which an official gives information to journalists", example: "The minister held a press briefing after the meeting.", exampleTranslation: "عقد الوزير إحاطة صحفية بعد الاجتماع.", category: "media and news", tags: ["news", "journalism"], synonyms: ["media briefing", "press meeting"] }),
      reviewed({ word: "media outlet", translation: "وسيلة إعلامية", pos: "noun", ipa: "/ˈmiːdiə ˈaʊtlet/", definition: "an organisation that publishes or broadcasts news and information", example: "Several media outlets covered the environmental protest.", exampleTranslation: "غطت عدة وسائل إعلامية الاحتجاج البيئي.", category: "media and news", tags: ["media", "journalism"], synonyms: ["news organisation", "media organisation"] }),
      reviewed({ word: "copy desk", translation: "قسم التدقيق والتحرير", pos: "noun", ipa: "/ˌedɪˈtɔːriəl desk/", definition: "the part of a news organisation responsible for checking language, facts, and style before publication", example: "The copy desk checked the report before publication.", exampleTranslation: "راجع قسم التدقيق والتحرير التقرير قبل نشره.", category: "media and news", tags: ["news", "publishing"], synonyms: ["copy-editing department", "proofreading desk"] }),
      reviewed({ word: "eyewitness report", translation: "تقرير شاهد عيان", pos: "noun", ipa: "/ˈaɪwɪtnəs rɪˈpɔːrt/", definition: "an account of an event given by someone who saw it happen", example: "The website published an eyewitness report from the scene.", exampleTranslation: "نشر الموقع تقرير شاهد عيان من مكان الحدث.", category: "media and news", tags: ["news", "evidence"], synonyms: ["first-hand account", "witness account"] }),
      reviewed({ word: "broadcast licence", translation: "ترخيص بث", pos: "noun", ipa: "/ˈbrɔːdkæst ˈlaɪsəns/", definition: "official permission to transmit radio or television programmes", example: "The station renewed its broadcast licence for another year.", exampleTranslation: "جددت المحطة ترخيص البث لعام آخر.", category: "media and news", tags: ["broadcasting", "regulation"], synonyms: ["broadcast permit", "transmission licence"] }),
      reviewed({ word: "news agency", translation: "وكالة أنباء", pos: "noun", ipa: "/njuːz ˈeɪdʒənsi/", definition: "an organisation that collects news and supplies it to newspapers and broadcasters", example: "The news agency sent a correspondent to the border.", exampleTranslation: "أرسلت وكالة الأنباء مراسلًا إلى الحدود.", category: "media and news", tags: ["news", "journalism"], synonyms: ["press agency", "wire service"] }),
      reviewed({ word: "publication standards", translation: "معايير النشر", pos: "noun", ipa: "/ˌedɪˈtɔːriəl ˈpɑːləsi/", definition: "the rules that guide the accuracy, fairness, and quality of published content", example: "The newspaper explained its publication standards to readers.", exampleTranslation: "شرحت الصحيفة معايير النشر للقراء.", category: "media and news", tags: ["news", "ethics"], synonyms: ["publishing standards", "quality guidelines"] }),
    ],
    u25: [
      reviewed({ word: "food chain", translation: "سلسلة غذائية", pos: "noun", ipa: "/fuːd tʃeɪn/", definition: "a series of living things in which each one feeds on the next one", example: "Removing one species can disturb the entire food chain.", exampleTranslation: "يمكن أن تؤدي إزالة نوع واحد إلى اضطراب السلسلة الغذائية بأكملها.", category: "nature and environment", tags: ["nature", "ecology"], synonyms: ["trophic chain", "feeding chain"] }),
      reviewed({ word: "invasive species", translation: "نوع دخيل", pos: "noun", ipa: "/ɪnˈveɪsɪv ˈspiːʃiːz/", definition: "a plant or animal that spreads in a place where it is not native and harms local life", example: "The lake is threatened by an invasive species.", exampleTranslation: "تتعرض البحيرة للتهديد بسبب نوع دخيل.", category: "nature and environment", tags: ["nature", "ecology"], synonyms: ["introduced species", "non-native species"] }),
      reviewed({ word: "reforestation", translation: "إعادة التشجير", pos: "noun", ipa: "/ˌriːfɔːrəˈsteɪʃən/", definition: "the process of planting trees again in an area where forests have been removed", example: "Reforestation can restore habitats and reduce soil erosion.", exampleTranslation: "يمكن لإعادة التشجير استعادة المواطن الطبيعية وتقليل تآكل التربة.", category: "nature and environment", tags: ["nature", "forests"], synonyms: ["forest restoration", "tree planting"] }),
      reviewed({ word: "wetland", translation: "أرض رطبة", pos: "noun", ipa: "/ˈwetlənd/", definition: "land covered by or saturated with water, such as a marsh or swamp", example: "The wetland provides shelter for hundreds of birds.", exampleTranslation: "توفر الأرض الرطبة مأوى لمئات الطيور.", category: "nature and environment", tags: ["nature", "habitats"], synonyms: ["marshland", "swamp"] }),
      reviewed({ word: "drought-resistant", translation: "مقاوم للجفاف", pos: "adjective", ipa: "/draʊt rɪˈzɪstənt/", definition: "able to survive with very little water", example: "Farmers are testing drought-resistant crops.", exampleTranslation: "يختبر المزارعون محاصيل مقاومة للجفاف.", category: "nature and environment", tags: ["climate", "farming"], synonyms: ["water-efficient", "arid-tolerant"] }),
      reviewed({ word: "greenhouse gas", translation: "غاز دفيئة", pos: "noun", ipa: "/ˈɡriːnhaʊs ɡæs/", definition: "a gas that traps heat in the atmosphere and contributes to global warming", example: "Methane is a powerful greenhouse gas.", exampleTranslation: "الميثان غاز دفيئة قوي.", category: "nature and environment", tags: ["climate", "pollution"], synonyms: ["heat-trapping gas", "atmospheric gas"] }),
      reviewed({ word: "landfill", translation: "مكب نفايات", pos: "noun", ipa: "/ˈlændfɪl/", definition: "a site where waste is buried under the ground", example: "The town wants to reduce the amount of rubbish sent to landfill.", exampleTranslation: "تريد البلدة تقليل كمية النفايات المرسلة إلى مكب النفايات.", category: "nature and environment", tags: ["waste", "pollution"], synonyms: ["waste site", "dump"] }),
      reviewed({ word: "nature reserve", translation: "محمية طبيعية", pos: "noun", ipa: "/ˈneɪtʃər rɪˈzɜːrv/", definition: "an area of land protected so that its plants and animals can live safely", example: "The island was declared a nature reserve.", exampleTranslation: "أُعلنت الجزيرة محمية طبيعية.", category: "nature and environment", tags: ["nature", "protection"], synonyms: ["wildlife reserve", "protected area"] }),
    ],
  },
  B2: {
    u24: [
      reviewed({ word: "gross domestic product", translation: "الناتج المحلي الإجمالي", pos: "noun", ipa: "/ɡroʊs dəˈmestɪk ˈprɑːdʌkt/", definition: "the total value of goods and services produced in a country during a period", example: "The report compares gross domestic product across the region.", exampleTranslation: "يقارن التقرير الناتج المحلي الإجمالي في أنحاء المنطقة.", category: "economy and money", tags: ["economy", "statistics"], synonyms: ["GDP", "national output"] }),
      reviewed({ word: "tax incentive", translation: "حافز ضريبي", pos: "noun", ipa: "/tæks ɪnˈsentɪv/", definition: "a reduction in tax intended to encourage a particular activity or investment", example: "The tax incentive attracted clean-energy companies.", exampleTranslation: "جذب الحافز الضريبي شركات الطاقة النظيفة.", category: "economy and money", tags: ["tax", "investment"], synonyms: ["tax break", "fiscal incentive"] }),
      reviewed({ word: "credit rating", translation: "تصنيف ائتماني", pos: "noun", ipa: "/ˈkredɪt ˌreɪtɪŋ/", definition: "an assessment of how likely a person or organisation is to repay borrowed money", example: "A strong credit rating helped the company borrow at a lower cost.", exampleTranslation: "ساعد التصنيف الائتماني القوي الشركة على الاقتراض بتكلفة أقل.", category: "economy and money", tags: ["finance", "risk"], synonyms: ["credit score", "financial rating"] }),
      reviewed({ word: "countercyclical spending", translation: "إنفاق مضاد للدورة الاقتصادية", pos: "noun", ipa: "/ˈfɪskəl ˈstɪmjələs/", definition: "government spending that increases during an economic slowdown to support demand", example: "The government used countercyclical spending during the downturn.", exampleTranslation: "استخدمت الحكومة إنفاقًا مضادًا للدورة الاقتصادية أثناء التراجع.", category: "economy and money", tags: ["economy", "government"], synonyms: ["countercyclical policy", "stabilising expenditure"] }),
      reviewed({ word: "household income", translation: "دخل الأسرة", pos: "noun", ipa: "/ˈhaʊshoʊld ˈɪnkʌm/", definition: "the total money earned by the people living in one home", example: "Rising rents have reduced household income available for saving.", exampleTranslation: "قللت الإيجارات المرتفعة دخل الأسرة المتاح للادخار.", category: "economy and money", tags: ["money", "society"], synonyms: ["family income", "domestic income"] }),
      reviewed({ word: "capital gain", translation: "ربح رأسمالي", pos: "noun", ipa: "/ˈkæpɪtəl ɡeɪn/", definition: "a profit made when an asset is sold for more than it cost", example: "The investor paid tax on the capital gain from the sale.", exampleTranslation: "دفع المستثمر ضريبة على الربح الرأسمالي من البيع.", category: "economy and money", tags: ["finance", "investment"], synonyms: ["investment profit", "asset gain"] }),
      reviewed({ word: "output efficiency", translation: "كفاءة الإنتاج", pos: "noun", ipa: "/ˈleɪbər ˌprɑːdʌkˈtɪvəti/", definition: "the amount of useful production achieved with a given level of time, labour, or resources", example: "Training can improve output efficiency without extending the working day.", exampleTranslation: "يمكن للتدريب تحسين كفاءة الإنتاج دون تمديد يوم العمل.", category: "economy and money", tags: ["work", "economy"], synonyms: ["production efficiency", "resource efficiency"] }),
      reviewed({ word: "growth projection", translation: "توقع النمو", pos: "noun", ipa: "/ˌiːkəˈnɑːmɪk ˈfɔːrkæst/", definition: "an estimate of how much an economy is expected to expand during a future period", example: "The latest growth projection predicts slower expansion.", exampleTranslation: "يتوقع آخر توقع للنمو توسعًا أبطأ.", category: "economy and money", tags: ["economy", "planning"], synonyms: ["expansion estimate", "growth estimate"] }),
    ],
    u25: [
      reviewed({ word: "autonomous", translation: "ذاتي التحكم", pos: "adjective", ipa: "/ɔːˈtɑːnəməs/", definition: "able to operate without being directly controlled by humans", example: "Researchers are testing autonomous vehicles in a controlled area.", exampleTranslation: "يختبر الباحثون مركبات ذاتية التحكم في منطقة مضبوطة.", category: "artificial intelligence and robotics", tags: ["AI", "robots"], synonyms: ["self-governing", "self-driving"] }),
      reviewed({ word: "technological singularity", translation: "التفرد التكنولوجي", pos: "noun", ipa: "/ˌteknəˈlɑːdʒɪkəl ˌsɪŋɡjəˈlerəti/", definition: "a hypothetical point when artificial intelligence becomes more capable than human intelligence", example: "The technological singularity remains a subject of debate among researchers.", exampleTranslation: "يبقى التفرد التكنولوجي موضوعًا للنقاش بين الباحثين.", category: "artificial intelligence and robotics", tags: ["AI", "future"], synonyms: ["AI singularity", "intelligence explosion"] }),
      reviewed({ word: "humanoid", translation: "شبيه بالإنسان", pos: "noun", ipa: "/ˈhjuːmənɔɪd/", definition: "a machine or creature with a human-like appearance or structure", example: "The laboratory demonstrated a humanoid that could climb stairs.", exampleTranslation: "عرض المختبر روبوتًا شبيهًا بالإنسان يستطيع صعود السلالم.", category: "artificial intelligence and robotics", tags: ["robots", "engineering"], synonyms: ["android", "human-like robot"] }),
      reviewed({ word: "cybernetics", translation: "علم التحكم الآلي", pos: "noun", ipa: "/ˌsaɪbərˈnetɪks/", definition: "the study of communication and control in machines, organisms, and systems", example: "Cybernetics connects ideas from biology, engineering, and computing.", exampleTranslation: "يربط علم التحكم الآلي بين أفكار من الأحياء والهندسة والحوسبة.", category: "artificial intelligence and robotics", tags: ["AI", "science"], synonyms: ["control theory", "systems science"] }),
      reviewed({ word: "computer vision", translation: "رؤية حاسوبية", pos: "noun", ipa: "/kəmˈpjuːtər ˈvɪʒən/", definition: "the use of computers to identify and understand images or video", example: "Computer vision helps the robot recognise obstacles.", exampleTranslation: "تساعد الرؤية الحاسوبية الروبوت على التعرف على العوائق.", category: "artificial intelligence and robotics", tags: ["AI", "images"], synonyms: ["machine vision", "visual computing"] }),
      reviewed({ word: "speech synthesis", translation: "توليد الكلام", pos: "noun", ipa: "/spiːtʃ ˈsɪnθəsɪs/", definition: "the artificial production of human speech by a computer", example: "The assistant uses speech synthesis to read the answer aloud.", exampleTranslation: "يستخدم المساعد توليد الكلام لقراءة الإجابة بصوت عالٍ.", category: "artificial intelligence and robotics", tags: ["AI", "language"], synonyms: ["text-to-speech", "synthetic speech"] }),
      reviewed({ word: "reinforcement learning", translation: "التعلم بالتعزيز", pos: "noun", ipa: "/ˌriːɪnˈfɔːrsmənt ˈlɜːrnɪŋ/", definition: "a method in which a system learns by receiving rewards or penalties for its actions", example: "The robot improved its route through reinforcement learning.", exampleTranslation: "حسن الروبوت مساره من خلال التعلم بالتعزيز.", category: "artificial intelligence and robotics", tags: ["AI", "learning"], synonyms: ["reward-based learning", "feedback learning"] }),
      reviewed({ word: "predictive model", translation: "نموذج تنبؤي", pos: "noun", ipa: "/prɪˈdɪktɪv ˈmɑːdəl/", definition: "a computer-based representation used to estimate what may happen in the future", example: "The hospital uses a predictive model to identify patients at risk.", exampleTranslation: "يستخدم المستشفى نموذجًا تنبؤيًا لتحديد المرضى المعرضين للخطر.", category: "artificial intelligence and robotics", tags: ["AI", "data"], synonyms: ["forecasting model", "prediction system"] }),
    ],
  },
  C1: {
    u24: [
      reviewed({ word: "egalitarian", translation: "قائم على المساواة", pos: "adjective", ipa: "/ɪˌɡælɪˈteriən/", definition: "believing that all people should have equal rights and opportunities", example: "The movement promotes an egalitarian vision of society.", exampleTranslation: "تروج الحركة لرؤية قائمة على المساواة للمجتمع.", category: "state and civil society", tags: ["politics", "society"], synonyms: ["equal", "fair-minded"] }),
      reviewed({ word: "disenfranchise", translation: "يحرم من حق التصويت", pos: "verb", ipa: "/ˌdɪsɪnˈfræntʃaɪz/", definition: "to take away a person’s right or privilege, especially the right to vote", example: "The new rule could disenfranchise thousands of rural voters.", exampleTranslation: "قد تحرم القاعدة الجديدة آلاف الناخبين في المناطق الريفية من حق التصويت.", category: "state and civil society", tags: ["politics", "rights"], synonyms: ["deprive", "marginalise"] }),
      reviewed({ word: "constituency", translation: "دائرة انتخابية", pos: "noun", ipa: "/kənˈstɪtʃuənsi/", definition: "a group of voters represented by an elected politician", example: "The representative returned to her constituency to hear local concerns.", exampleTranslation: "عادت النائبة إلى دائرتها الانتخابية للاستماع إلى المخاوف المحلية.", category: "state and civil society", tags: ["elections", "politics"], synonyms: ["electorate", "voting district"] }),
      reviewed({ word: "sovereign", translation: "سيادي", pos: "adjective", ipa: "/ˈsɑːvrən/", definition: "having the highest power or being fully independent", example: "A sovereign state controls its own laws and borders.", exampleTranslation: "تتحكم الدولة السيادية في قوانينها وحدودها.", category: "state and civil society", tags: ["government", "power"], synonyms: ["independent", "self-governing"] }),
      reviewed({ word: "constitutionalism", translation: "دستورية", pos: "noun", ipa: "/ˌkɑːnstəˈtuːʃənəlɪzəm/", definition: "the belief that government power should be limited by a constitution", example: "Constitutionalism protects citizens from unlimited executive power.", exampleTranslation: "تحمي الدستورية المواطنين من السلطة التنفيذية غير المحدودة.", category: "state and civil society", tags: ["law", "government"], synonyms: ["constitutional government", "limited government"] }),
      reviewed({ word: "rule of law", translation: "سيادة القانون", pos: "noun", ipa: "/ruːl əv lɔː/", definition: "the principle that everyone, including officials, must obey the law", example: "An independent court is essential to the rule of law.", exampleTranslation: "تعد المحكمة المستقلة ضرورية لسيادة القانون.", category: "state and civil society", tags: ["law", "justice"], synonyms: ["legal equality", "law-based government"] }),
      reviewed({ word: "federalism", translation: "فيدرالية", pos: "noun", ipa: "/ˈfedərəlɪzəm/", definition: "a system in which power is shared between a central government and regional governments", example: "Federalism allows regions to make decisions about local services.", exampleTranslation: "تتيح الفيدرالية للمناطق اتخاذ قرارات بشأن الخدمات المحلية.", category: "state and civil society", tags: ["government", "politics"], synonyms: ["federal system", "shared governance"] }),
      reviewed({ word: "institutional legitimacy", translation: "شرعية مؤسسية", pos: "noun", ipa: "/ˌɪnstəˈtuːʃənəl ləˈdʒɪtəməsi/", definition: "the public belief that an institution has a rightful and acceptable authority", example: "Transparency can strengthen institutional legitimacy.", exampleTranslation: "يمكن للشفافية أن تعزز الشرعية المؤسسية.", category: "state and civil society", tags: ["government", "trust"], synonyms: ["official legitimacy", "institutional authority"] }),
    ],
    u25: [
      reviewed({ word: "avant-garde", translation: "طليعي", pos: "adjective", ipa: "/ˌævɑːnˈɡɑːrd/", definition: "using new and experimental ideas in art, music, or literature", example: "The gallery is known for exhibiting avant-garde photography.", exampleTranslation: "يشتهر المعرض بعرض التصوير الفوتوغرافي الطليعي.", category: "aesthetics and art criticism", tags: ["art", "modernism"], synonyms: ["experimental", "pioneering"] }),
      reviewed({ word: "kitsch", translation: "فن مبتذل", pos: "noun", ipa: "/kɪtʃ/", definition: "art or design considered cheap, sentimental, or lacking serious style", example: "Some critics dismissed the colourful sculptures as kitsch.", exampleTranslation: "رفض بعض النقاد المنحوتات الملونة باعتبارها فنًا مبتذلًا.", category: "aesthetics and art criticism", tags: ["art", "taste"], synonyms: ["tackiness", "bad taste"] }),
      reviewed({ word: "eclectic", translation: "انتقائي", pos: "adjective", ipa: "/ɪˈklektɪk/", definition: "combining ideas or styles from a wide range of sources", example: "Her eclectic style mixes classical furniture with modern sculpture.", exampleTranslation: "يمزج أسلوبها الانتقائي بين الأثاث الكلاسيكي والمنحوتات الحديثة.", category: "aesthetics and art criticism", tags: ["art", "style"], synonyms: ["varied", "diverse"] }),
      reviewed({ word: "aestheticism", translation: "مذهب الجمال", pos: "noun", ipa: "/iːsˈθetɪsɪzəm/", definition: "the belief that art and beauty are more important than moral or practical purposes", example: "The novel reflects the aestheticism of the late nineteenth century.", exampleTranslation: "تعكس الرواية مذهب الجمال في أواخر القرن التاسع عشر.", category: "aesthetics and art criticism", tags: ["art", "philosophy"], synonyms: ["art for art’s sake", "aesthetic movement"] }),
      reviewed({ word: "iconography", translation: "دراسة الرموز والصور", pos: "noun", ipa: "/ˌaɪkəˈnɑːɡrəfi/", definition: "the study or use of images and symbols in art", example: "The lecture examined the religious iconography of the painting.", exampleTranslation: "فحصت المحاضرة الرموز الدينية في اللوحة.", category: "aesthetics and art criticism", tags: ["art", "symbols"], synonyms: ["symbolism", "visual imagery"] }),
      reviewed({ word: "chiaroscuro", translation: "تباين الضوء والظل", pos: "noun", ipa: "/kiˌɑːrəˈskʊroʊ/", definition: "the use of strong contrasts between light and dark in visual art", example: "The painter used chiaroscuro to give the portrait dramatic depth.", exampleTranslation: "استخدم الرسام تباين الضوء والظل لمنح الصورة عمقًا دراميًا.", category: "aesthetics and art criticism", tags: ["art", "painting"], synonyms: ["light-and-shade contrast", "tonal contrast"] }),
      reviewed({ word: "installation art", translation: "فن تركيبي", pos: "noun", ipa: "/ˌɪnstəˈleɪʃən ɑːrt/", definition: "art made by arranging objects or materials in a particular space", example: "The installation art transformed the empty hall into an immersive environment.", exampleTranslation: "حوّل الفن التركيبي القاعة الفارغة إلى بيئة غامرة.", category: "aesthetics and art criticism", tags: ["art", "gallery"], synonyms: ["art installation", "spatial artwork"] }),
      reviewed({ word: "artistic merit", translation: "قيمة فنية", pos: "noun", ipa: "/ɑːrˈtɪstɪk ˈmerɪt/", definition: "the quality or value that makes a work deserving of artistic recognition", example: "The committee debated the artistic merit of the controversial film.", exampleTranslation: "ناقشت اللجنة القيمة الفنية للفيلم المثير للجدل.", category: "aesthetics and art criticism", tags: ["art", "evaluation"], synonyms: ["artistic value", "creative quality"] }),
    ],
  },
};
