import type { VocabularyItem } from "./learn-data";

const reviewed = (item: VocabularyItem): VocabularyItem => ({
  ...item,
  translationLang: "ar",
  synonyms: item.synonyms ?? [item.word],
  antonyms: item.antonyms ?? [],
  collocations: item.collocations ?? [item.word],
  wordFamily: item.wordFamily ?? [item.word],
});

/**
 * Reviewed enrichment for the six existing B1/B2/C1 units with the smallest
 * runtime vocabulary banks. This file contains vocabulary only and never
 * declares, creates, renames, or removes curriculum units.
 */
export const ENGLISH_B1_B2_C1_U10_U11_ENRICHMENTS: Record<string, Record<string, VocabularyItem[]>> = {
  B1: {
    u10: [
      reviewed({ word: "current account", translation: "حساب جارٍ", pos: "noun", ipa: "/ˌkɜːrənt əˈkaʊnt/", definition: "a bank account used for everyday payments and money management", example: "She checks her current account before paying the monthly bills.", exampleTranslation: "تتحقق من حسابها الجاري قبل دفع الفواتير الشهرية.", category: "banking", tags: ["money", "banking"], synonyms: ["everyday bank account", "checking account"] }),
      reviewed({ word: "credit score", translation: "درجة ائتمانية", pos: "noun", ipa: "/ˈkredɪt skɔːr/", definition: "a numerical assessment of how reliably someone has borrowed and repaid money", example: "A good credit score may help him obtain a more affordable loan.", exampleTranslation: "قد تساعد الدرجة الائتمانية الجيدة في الحصول على قرض أقل تكلفة.", category: "banking", tags: ["money", "borrowing"], synonyms: ["credit rating", "credit record"] }),
      reviewed({ word: "debit card", translation: "بطاقة خصم", pos: "noun", ipa: "/ˈdebɪt kɑːrd/", definition: "a bank card that takes money directly from the holder's account", example: "I used my debit card to pay for the groceries.", exampleTranslation: "استخدمت بطاقة الخصم لدفع ثمن البقالة.", category: "banking", tags: ["money", "payments"], synonyms: ["bank card", "payment card"] }),
      reviewed({ word: "contactless payment", translation: "دفع دون تلامس", pos: "noun", ipa: "/ˈkɑːntæktləs ˈpeɪmənt/", definition: "a payment made by tapping a card or device near a reader", example: "Contactless payment is convenient, but I still check the receipt.", exampleTranslation: "الدفع دون تلامس مريح، لكنني ما زلت أتحقق من الإيصال.", category: "banking", tags: ["money", "technology"], synonyms: ["tap-to-pay", "contact-free payment"] }),
      reviewed({ word: "bank transfer", translation: "تحويل مصرفي", pos: "noun", ipa: "/ˈbæŋk ˌtrænsfɜːr/", definition: "the movement of money electronically from one bank account to another", example: "The landlord asked for the rent by bank transfer.", exampleTranslation: "طلب مالك المنزل دفع الإيجار عن طريق تحويل مصرفي.", category: "banking", tags: ["money", "payments"], synonyms: ["electronic transfer", "account transfer"] }),
      reviewed({ word: "standing order", translation: "أمر دفع دائم", pos: "noun", ipa: "/ˈstændɪŋ ˌɔːrdər/", definition: "an instruction to a bank to make regular fixed payments", example: "He set up a standing order for the monthly charity donation.", exampleTranslation: "أنشأ أمر دفع دائمًا للتبرع الشهري للجمعية الخيرية.", category: "banking", tags: ["money", "planning"], synonyms: ["recurring payment instruction", "scheduled bank payment"] }),
      reviewed({ word: "overdraft facility", translation: "تسهيل السحب على المكشوف", pos: "noun", ipa: "/ˈoʊvərdræft fəˈsɪləti/", definition: "an arrangement allowing a customer to spend more money than is currently in an account", example: "The overdraft facility helped her manage a short-term cash-flow problem.", exampleTranslation: "ساعدها تسهيل السحب على المكشوف في إدارة مشكلة نقدية قصيرة الأجل.", category: "banking", tags: ["money", "borrowing"], synonyms: ["overdraft arrangement", "authorised overdraft"] }),
      reviewed({ word: "identity verification", translation: "التحقق من الهوية", pos: "noun", ipa: "/aɪˈdentəti ˌverɪfɪˈkeɪʃən/", definition: "the process of confirming that a person is who they claim to be", example: "The bank requested identity verification before opening the account.", exampleTranslation: "طلب البنك التحقق من الهوية قبل فتح الحساب.", category: "banking", tags: ["money", "security"], synonyms: ["identity check", "customer verification"] }),
    ],
    u11: [
      reviewed({ word: "traffic congestion", translation: "ازدحام مروري", pos: "noun", ipa: "/ˈtræfɪk kənˌdʒestʃən/", definition: "a situation in which too many vehicles make traffic move slowly", example: "Traffic congestion makes the bus journey much longer during rush hour.", exampleTranslation: "يجعل الازدحام المروري رحلة الحافلة أطول بكثير خلال ساعة الذروة.", category: "transport", tags: ["city", "travel"], synonyms: ["traffic jam", "road congestion"] }),
      reviewed({ word: "bus lane", translation: "مسار حافلات", pos: "noun", ipa: "/ˈbʌs leɪn/", definition: "a part of a road reserved mainly for buses", example: "The new bus lane has made public transport more reliable.", exampleTranslation: "جعل مسار الحافلات الجديد النقل العام أكثر موثوقية.", category: "transport", tags: ["city", "buses"], synonyms: ["bus-only lane", "dedicated bus lane"] }),
      reviewed({ word: "road diversion", translation: "تحويلة طريق", pos: "noun", ipa: "/ˈroʊd daɪˌvɜːrʒən/", definition: "a temporary route used when the usual road is closed or unsuitable", example: "We followed the road diversion around the construction work.", exampleTranslation: "اتبعنا تحويلة الطريق حول أعمال البناء.", category: "transport", tags: ["travel", "roads"], synonyms: ["detour", "alternative route"] }),
      reviewed({ word: "fare evasion", translation: "التهرب من دفع الأجرة", pos: "noun", ipa: "/ˈfer ɪˌveɪʒən/", definition: "the act of travelling without paying the required transport fare", example: "The campaign explains why fare evasion increases costs for other passengers.", exampleTranslation: "توضح الحملة لماذا يزيد التهرب من دفع الأجرة التكاليف على الركاب الآخرين.", category: "transport", tags: ["buses", "rules"], synonyms: ["ticket evasion", "travelling without a fare"] }),
      reviewed({ word: "commuter rail", translation: "قطارات ضواحي للركاب", pos: "noun", ipa: "/kəˈmjuːtər reɪl/", definition: "a rail service designed mainly for regular journeys between suburbs and a city", example: "Commuter rail connects the outer suburbs with the central station.", exampleTranslation: "تربط قطارات الضواحي المناطق الخارجية بالمحطة المركزية.", category: "transport", tags: ["city", "rail"], synonyms: ["suburban rail", "commuter train service"] }),
      reviewed({ word: "rush-hour delay", translation: "تأخير ساعة الذروة", pos: "noun", ipa: "/ˈrʌʃ aʊər dɪˈleɪ/", definition: "extra travel time caused by heavy demand during the busiest period", example: "A rush-hour delay caused me to miss the beginning of the meeting.", exampleTranslation: "تسبب تأخير ساعة الذروة في تفويتي بداية الاجتماع.", category: "transport", tags: ["city", "time"], synonyms: ["peak-time delay", "commuting delay"] }),
      reviewed({ word: "route planner", translation: "مخطط المسار", pos: "noun", ipa: "/ˈruːt ˌplænər/", definition: "a tool or person that helps choose the best way to travel", example: "The route planner suggested changing buses at the main interchange.", exampleTranslation: "اقترح مخطط المسار تغيير الحافلة عند محطة التبديل الرئيسية.", category: "transport", tags: ["travel", "technology"], synonyms: ["journey planner", "travel planner"] }),
      reviewed({ word: "park-and-ride", translation: "موقف سيارات مع مواصلة النقل العام", pos: "noun", ipa: "/ˌpɑːrk ən ˈraɪd/", definition: "a system where drivers leave cars outside a busy centre and continue by public transport", example: "The park-and-ride scheme reduces the number of cars entering the city centre.", exampleTranslation: "يقلل نظام موقف السيارات مع مواصلة النقل العام عدد السيارات الداخلة إلى وسط المدينة.", category: "transport", tags: ["city", "planning"], synonyms: ["park-and-continue", "outer parking interchange"] }),
    ],
  },
  B2: {
    u10: [
      reviewed({ word: "consumer confidence", translation: "ثقة المستهلك", pos: "noun", ipa: "/kənˈsuːmər ˈkɑːnfɪdəns/", definition: "the degree to which people feel optimistic about their finances and the economy", example: "Consumer confidence fell after households heard the news about rising costs.", exampleTranslation: "انخفضت ثقة المستهلك بعد أن سمعت الأسر أخبار ارتفاع التكاليف.", category: "economics", tags: ["economy", "money"], synonyms: ["consumer optimism", "household confidence"] }),
      reviewed({ word: "price ceiling", translation: "سقف سعري", pos: "noun", ipa: "/ˈpraɪs ˌsiːlɪŋ/", definition: "a legal maximum price that sellers are allowed to charge", example: "The government introduced a price ceiling on essential medicines.", exampleTranslation: "فرضت الحكومة سقفًا سعريًا على الأدوية الأساسية.", category: "economics", tags: ["economy", "policy"], synonyms: ["maximum legal price", "price cap"] }),
      reviewed({ word: "household budget pressure", translation: "ضغط ميزانية الأسرة", pos: "noun", ipa: "/ˈhaʊshoʊld ˈbʌdʒɪt ˌpreʃər/", definition: "the financial strain created when essential costs take up more of a household’s income", example: "Household budget pressure increased as energy bills rose faster than wages.", exampleTranslation: "ازداد ضغط ميزانية الأسرة مع ارتفاع فواتير الطاقة أسرع من الأجور.", category: "economics", tags: ["economy", "households"], synonyms: ["household financial strain", "family budget stress"] }),
      reviewed({ word: "cost-push inflation", translation: "تضخم ناتج عن ارتفاع التكاليف", pos: "noun", ipa: "/ˈkɔːst pʊʃ ɪnˌfleɪʃən/", definition: "inflation caused by higher production costs being passed on to consumers", example: "A rise in fuel prices can contribute to cost-push inflation.", exampleTranslation: "يمكن أن تسهم زيادة أسعار الوقود في تضخم ناتج عن ارتفاع التكاليف.", category: "economics", tags: ["economy", "prices"], synonyms: ["supply-side inflation", "cost-driven inflation"] }),
      reviewed({ word: "demand-pull inflation", translation: "تضخم ناتج عن زيادة الطلب", pos: "noun", ipa: "/dɪˈmænd pʊl ɪnˌfleɪʃən/", definition: "inflation that occurs when demand grows faster than the supply of goods and services", example: "Strong spending after the crisis contributed to demand-pull inflation.", exampleTranslation: "أسهم الإنفاق القوي بعد الأزمة في تضخم ناتج عن زيادة الطلب.", category: "economics", tags: ["economy", "prices"], synonyms: ["demand-driven inflation", "excess-demand inflation"] }),
      reviewed({ word: "fiscal stimulus", translation: "تحفيز مالي", pos: "noun", ipa: "/ˈfɪskəl ˈstɪmjələs/", definition: "government spending or tax reductions intended to support economic activity", example: "The fiscal stimulus was designed to protect jobs during the downturn.", exampleTranslation: "صُمم التحفيز المالي لحماية الوظائف أثناء التراجع الاقتصادي.", category: "economics", tags: ["economy", "government"], synonyms: ["government stimulus", "expansionary fiscal policy"] }),
      reviewed({ word: "economic downturn", translation: "تباطؤ اقتصادي", pos: "noun", ipa: "/ˌiːkəˈnɑːmɪk ˈdaʊntɜːrn/", definition: "a period in which economic activity, production, or employment declines", example: "Small firms often need support during an economic downturn.", exampleTranslation: "تحتاج الشركات الصغيرة غالبًا إلى دعم أثناء التباطؤ الاقتصادي.", category: "economics", tags: ["economy", "work"], synonyms: ["economic decline", "recessionary period"] }),
      reviewed({ word: "wage stagnation", translation: "ركود الأجور", pos: "noun", ipa: "/ˈweɪdʒ stæɡˌneɪʃən/", definition: "a long period in which pay fails to grow significantly", example: "Wage stagnation can make it difficult for families to cope with higher prices.", exampleTranslation: "يمكن لركود الأجور أن يجعل مواجهة الأسر لارتفاع الأسعار صعبة.", category: "economics", tags: ["economy", "work"], synonyms: ["stagnant wages", "pay stagnation"] }),
      reviewed({ word: "price stability", translation: "استقرار الأسعار", pos: "noun", ipa: "/ˈpraɪs stəˌbɪləti/", definition: "a situation in which prices change slowly and remain broadly predictable", example: "Price stability helps businesses plan investment and employment.", exampleTranslation: "يساعد استقرار الأسعار الشركات على التخطيط للاستثمار والتوظيف.", category: "economics", tags: ["economy", "prices"], synonyms: ["stable prices", "low price volatility"] }),
    ],
    u11: [
      reviewed({ word: "emotional resilience", translation: "المرونة العاطفية", pos: "noun", ipa: "/ɪˈmoʊʃənəl rɪˈzɪliəns/", definition: "the ability to recover emotionally after stress, disappointment, or difficulty", example: "Emotional resilience can help a person respond calmly to unexpected criticism.", exampleTranslation: "يمكن للمرونة العاطفية أن تساعد الشخص على الاستجابة بهدوء للنقد غير المتوقع.", category: "psychology", tags: ["emotions", "wellbeing"], synonyms: ["emotional strength", "psychological resilience"] }),
      reviewed({ word: "stress response", translation: "استجابة التوتر", pos: "noun", ipa: "/ˈstres rɪˌspɑːns/", definition: "the physical and mental reaction to a demanding or threatening situation", example: "Slow breathing can reduce the intensity of a stress response.", exampleTranslation: "يمكن للتنفس البطيء أن يقلل شدة استجابة التوتر.", category: "psychology", tags: ["emotions", "health"], synonyms: ["stress reaction", "fight-or-flight response"] }),
      reviewed({ word: "coping strategy", translation: "استراتيجية للتكيف", pos: "noun", ipa: "/ˈkoʊpɪŋ ˌstrætədʒi/", definition: "a method used to manage a difficult emotion, problem, or situation", example: "Writing a short plan became her coping strategy during busy weeks.", exampleTranslation: "أصبحت كتابة خطة قصيرة استراتيجية للتكيف خلال الأسابيع المزدحمة.", category: "psychology", tags: ["emotions", "habits"], synonyms: ["coping method", "self-management strategy"] }),
      reviewed({ word: "burnout prevention", translation: "الوقاية من الاحتراق الوظيفي", pos: "noun", ipa: "/ˈbɜːrnaʊt prɪˌvenʃən/", definition: "actions intended to prevent prolonged stress from causing exhaustion and loss of motivation", example: "Regular breaks are part of effective burnout prevention.", exampleTranslation: "تعد الاستراحات المنتظمة جزءًا من الوقاية الفعالة من الاحتراق الوظيفي.", category: "psychology", tags: ["stress", "work"], synonyms: ["burnout reduction", "exhaustion prevention"] }),
      reviewed({ word: "emotional trigger", translation: "محفز عاطفي", pos: "noun", ipa: "/ɪˈmoʊʃənəl ˈtrɪɡər/", definition: "an event, word, or situation that causes a strong emotional reaction", example: "The therapist helped him recognise an emotional trigger before it led to anger.", exampleTranslation: "ساعده المعالج على التعرف إلى محفز عاطفي قبل أن يؤدي إلى الغضب.", category: "psychology", tags: ["emotions", "awareness"], synonyms: ["emotional cue", "reaction trigger"] }),
      reviewed({ word: "social anxiety", translation: "قلق اجتماعي", pos: "noun", ipa: "/ˈsoʊʃəl æŋˌzaɪəti/", definition: "strong fear or worry about being judged in social situations", example: "Social anxiety made it difficult for her to speak in large meetings.", exampleTranslation: "جعل القلق الاجتماعي من الصعب عليها التحدث في الاجتماعات الكبيرة.", category: "psychology", tags: ["emotions", "relationships"], synonyms: ["social fear", "fear of social judgement"] }),
      reviewed({ word: "self-compassion", translation: "تعاطف مع الذات", pos: "noun", ipa: "/ˌself kəmˈpæʃən/", definition: "a kind and understanding attitude towards oneself during difficulty or failure", example: "Self-compassion can make it easier to learn from a mistake without giving up.", exampleTranslation: "يمكن للتعاطف مع الذات أن يجعل التعلم من الخطأ أسهل من دون الاستسلام.", category: "psychology", tags: ["emotions", "wellbeing"], synonyms: ["self-kindness", "understanding oneself"] }),
      reviewed({ word: "resilience building", translation: "بناء القدرة على الصمود", pos: "noun", ipa: "/rɪˈzɪliəns ˌbɪldɪŋ/", definition: "the gradual development of skills and support that help someone recover from difficulty", example: "Resilience building often involves supportive relationships and realistic goals.", exampleTranslation: "يتضمن بناء القدرة على الصمود غالبًا علاقات داعمة وأهدافًا واقعية.", category: "psychology", tags: ["emotions", "development"], synonyms: ["resilience training", "strength-building"] }),
    ],
  },
  C1: {
    u10: [
      reviewed({ word: "multinational corporation", translation: "شركة متعددة الجنسيات", pos: "noun", ipa: "/ˌmʌltiˈnæʃənəl ˌkɔːrpəˈreɪʃən/", definition: "a company that owns or controls operations in more than one country", example: "A multinational corporation may coordinate research across several continents.", exampleTranslation: "قد تنسق شركة متعددة الجنسيات الأبحاث عبر عدة قارات.", category: "globalization", tags: ["business", "globalization"], synonyms: ["multinational company", "global corporation"] }),
      reviewed({ word: "foreign direct investment", translation: "استثمار أجنبي مباشر", pos: "noun", ipa: "/ˌfɔːrən dəˈrekt ɪnˌvestmənt/", definition: "investment by an individual or company in a business located in another country", example: "Foreign direct investment created jobs but also raised questions about local ownership.", exampleTranslation: "أنشأ الاستثمار الأجنبي المباشر وظائف، لكنه أثار أيضًا أسئلة حول الملكية المحلية.", category: "globalization", tags: ["economy", "investment"], synonyms: ["overseas direct investment", "cross-border business investment"] }),
      reviewed({ word: "cross-border regulation", translation: "تنظيم عابر للحدود", pos: "noun", ipa: "/ˌkrɔːs ˈbɔːrdər ˌreɡjəˈleɪʃən/", definition: "rules governing activities that involve more than one national jurisdiction", example: "Cross-border regulation is needed when digital services operate in many markets.", exampleTranslation: "هناك حاجة إلى تنظيم عابر للحدود عندما تعمل الخدمات الرقمية في أسواق كثيرة.", category: "globalization", tags: ["law", "globalization"], synonyms: ["transnational regulation", "international oversight"] }),
      reviewed({ word: "corporate headquarters", translation: "المقر الرئيسي للشركة", pos: "noun", ipa: "/ˈkɔːrpərət ˌhedˈkwɔːrtərz/", definition: "the main office from which a company is directed", example: "The corporate headquarters announced a new policy for all regional offices.", exampleTranslation: "أعلن المقر الرئيسي للشركة سياسة جديدة لجميع المكاتب الإقليمية.", category: "globalization", tags: ["business", "organisation"], synonyms: ["company headquarters", "corporate main office"] }),
      reviewed({ word: "labour mobility", translation: "حركية العمل", pos: "noun", ipa: "/ˈleɪbər moʊˈbɪləti/", definition: "the ability of workers to move between jobs, regions, or countries", example: "Labour mobility can help fill skill shortages across a regional market.", exampleTranslation: "يمكن لحركية العمل أن تساعد في سد نقص المهارات عبر سوق إقليمية.", category: "globalization", tags: ["work", "migration"], synonyms: ["worker mobility", "employment mobility"] }),
      reviewed({ word: "global value chain", translation: "سلسلة قيمة عالمية", pos: "noun", ipa: "/ˈɡloʊbəl ˈvæljuː tʃeɪn/", definition: "the international sequence of activities through which a product or service is designed, made, and delivered", example: "A disruption at one factory can affect an entire global value chain.", exampleTranslation: "يمكن لتعطل مصنع واحد أن يؤثر في سلسلة قيمة عالمية كاملة.", category: "globalization", tags: ["business", "trade"], synonyms: ["international value chain", "global production chain"] }),
      reviewed({ word: "trade interdependence", translation: "اعتماد تجاري متبادل", pos: "noun", ipa: "/ˈtreɪd ˌɪntərdɪˈpendəns/", definition: "a condition in which economies rely on one another for goods, services, or markets", example: "Trade interdependence can create prosperity while increasing exposure to external shocks.", exampleTranslation: "يمكن للاعتماد التجاري المتبادل أن يخلق الازدهار ويزيد في الوقت نفسه التعرض للصدمات الخارجية.", category: "globalization", tags: ["trade", "economy"], synonyms: ["economic interdependence", "mutual trade reliance"] }),
      reviewed({ word: "offshore production", translation: "إنتاج خارج البلاد", pos: "noun", ipa: "/ˌɔːfʃɔːr prəˈdʌkʃən/", definition: "the manufacture of goods in another country, often to reduce costs or access skills", example: "Offshore production lowered costs but complicated the company’s supply oversight.", exampleTranslation: "خفض الإنتاج خارج البلاد التكاليف، لكنه عقد الإشراف على سلسلة التوريد.", category: "globalization", tags: ["business", "trade"], synonyms: ["overseas manufacturing", "foreign production"] }),
    ],
    u11: [
      reviewed({ word: "state censorship", translation: "رقابة حكومية", pos: "noun", ipa: "/ˌsteɪt ˈsensərʃɪp/", definition: "official control over information, expression, or media by a government", example: "State censorship can prevent citizens from comparing competing accounts of an event.", exampleTranslation: "قد تمنع الرقابة الحكومية المواطنين من مقارنة روايات متنافسة لحدث ما.", category: "media and power", tags: ["media", "politics"], synonyms: ["government censorship", "official information control"] }),
      reviewed({ word: "information control", translation: "التحكم في المعلومات", pos: "noun", ipa: "/ˌɪnfərˈmeɪʃən kənˈtroʊl/", definition: "the deliberate management of what information is available, visible, or suppressed", example: "Information control can shape public debate without changing the facts themselves.", exampleTranslation: "يمكن للتحكم في المعلومات أن يشكل النقاش العام من دون تغيير الحقائق نفسها.", category: "media and power", tags: ["media", "power"], synonyms: ["information management", "control of information"] }),
      reviewed({ word: "propaganda campaign", translation: "حملة دعائية", pos: "noun", ipa: "/ˌprɑːpəˈɡændə kæmˈpeɪn/", definition: "an organised effort to spread persuasive information that serves a political or ideological aim", example: "The propaganda campaign repeated a simple slogan across every available channel.", exampleTranslation: "كررت الحملة الدعائية شعارًا بسيطًا عبر كل قناة متاحة.", category: "media and power", tags: ["media", "politics"], synonyms: ["persuasion campaign", "political messaging campaign"] }),
      reviewed({ word: "newsroom autonomy", translation: "استقلالية غرفة الأخبار", pos: "noun", ipa: "/ˈnuːzruːm ɔːˈtɑːnəmi/", definition: "the ability of a news organisation to make editorial decisions without improper outside pressure", example: "Newsroom autonomy allows reporters to investigate powerful institutions fairly.", exampleTranslation: "تتيح استقلالية غرفة الأخبار للصحفيين التحقيق مع المؤسسات القوية بعدل.", category: "media and power", tags: ["media", "rights"], synonyms: ["editorial autonomy", "journalistic independence"] }),
      reviewed({ word: "public-service media", translation: "إعلام الخدمة العامة", pos: "noun", ipa: "/ˌpʌblɪk ˈsɜːrvɪs ˈmiːdiə/", definition: "media organised to serve the public interest rather than a purely commercial audience", example: "Public-service media can provide carefully sourced reporting during a crisis.", exampleTranslation: "يمكن لإعلام الخدمة العامة تقديم تقارير موثقة بعناية أثناء الأزمات.", category: "media and power", tags: ["media", "institutions"], synonyms: ["public-interest media", "civic media service"] }),
      reviewed({ word: "press freedom", translation: "حرية الصحافة", pos: "noun", ipa: "/ˈpres ˌfriːdəm/", definition: "the right of journalists and media organisations to report without unjustified interference", example: "Press freedom is weakened when investigative reporters face intimidation.", exampleTranslation: "تضعف حرية الصحافة عندما يواجه الصحفيون الاستقصائيون الترهيب.", category: "media and power", tags: ["media", "rights"], synonyms: ["freedom of the press", "journalistic freedom"] }),
      reviewed({ word: "surveillance state", translation: "دولة رقابية", pos: "noun", ipa: "/sərˈveɪləns steɪt/", definition: "a state that extensively monitors people’s activities and communications", example: "Critics argued that the new system could move the country towards a surveillance state.", exampleTranslation: "جادل المنتقدون بأن النظام الجديد قد يدفع البلاد نحو دولة رقابية.", category: "media and power", tags: ["politics", "privacy"], synonyms: ["monitoring state", "high-surveillance government"] }),
      reviewed({ word: "evidence triangulation", translation: "مقارنة الأدلة من مصادر متعددة", pos: "noun", ipa: "/ˈevɪdəns traɪˌæŋɡjəˈleɪʃən/", definition: "the process of checking a claim against several independent sources or types of evidence", example: "Evidence triangulation is essential before a viral claim is treated as reliable news.", exampleTranslation: "تُعد مقارنة الأدلة من مصادر متعددة ضرورية قبل اعتبار ادعاء واسع الانتشار خبرًا موثوقًا.", category: "media and power", tags: ["media", "education"], synonyms: ["cross-source verification", "multi-source checking"] }),
      reviewed({ word: "internet shutdown", translation: "قطع الإنترنت", pos: "noun", ipa: "/ˈɪntərnet ˌʃʌtdaʊn/", definition: "an official interruption of internet access across a place or population", example: "An internet shutdown made it difficult for residents to verify the circulating reports.", exampleTranslation: "جعل قطع الإنترنت من الصعب على السكان التحقق من التقارير المتداولة.", category: "media and power", tags: ["media", "technology"], synonyms: ["internet blackout", "network shutdown"] }),
      reviewed({ word: "whistleblower protection", translation: "حماية المبلغين عن المخالفات", pos: "noun", ipa: "/ˈwɪsəlbloʊər prəˌtekʃən/", definition: "legal or institutional safeguards for people who expose wrongdoing", example: "Whistleblower protection can encourage employees to report serious misconduct.", exampleTranslation: "يمكن لحماية المبلغين عن المخالفات أن تشجع الموظفين على الإبلاغ عن سوء السلوك الخطير.", category: "media and power", tags: ["rights", "accountability"], synonyms: ["informant protection", "protection for reporting wrongdoing"] }),
      reviewed({ word: "coordinated falsehood", translation: "معلومة كاذبة منسقة", pos: "noun", ipa: "/koʊˈɔːrdɪneɪtɪd ˈfɔːlshʊd/", definition: "a false claim deliberately organised and repeated by several actors to mislead an audience", example: "The investigation traced the coordinated falsehood to a network of anonymous accounts.", exampleTranslation: "تتبعت الدراسة المعلومة الكاذبة المنسقة إلى شبكة من الحسابات المجهولة.", category: "media and power", tags: ["media", "misinformation"], synonyms: ["organised deception", "coordinated false claim"] }),
      reviewed({ word: "algorithmic moderation", translation: "إشراف خوارزمي على المحتوى", pos: "noun", ipa: "/ˌælɡəˈrɪðmɪk ˌmɑːdəˈreɪʃən/", definition: "the use of automated systems to identify, limit, or remove online content", example: "Algorithmic moderation can reduce harmful content but may also hide legitimate debate.", exampleTranslation: "يمكن للإشراف الخوارزمي على المحتوى أن يقلل المحتوى الضار، لكنه قد يخفي أيضًا نقاشًا مشروعًا.", category: "media and power", tags: ["media", "technology"], synonyms: ["automated content moderation", "machine-led moderation"] }),
    ],
  },
};
