// Professional English enrichment units u44-u45 for every CEFR level.
// Finnish curriculum is intentionally untouched. APIs may enrich these records later,
// but they never generate the local curriculum.
import type { ReadingText, VocabularyItem } from "./learn-data";

type PhraseSpec = { phrase: string; translation: string };
type LineSpec = { speaker: string; text: string; translation: string };
type UnitSeed = { id: string; title: string; description: string; words: VocabularyItem[]; phrases: PhraseSpec[]; dialogue: LineSpec[]; reading: ReadingText & { title: string } };

const w = (word: string, translation: string, pos: string, ipa: string, definition: string, example: string, exampleTranslation: string, synonyms: string[], antonyms: string[], collocations: string[], wordFamily: string[], tags: string[], category: string): VocabularyItem => ({ word, translation, pos, ipa, definition, example, exampleTranslation, synonyms, antonyms, collocations, wordFamily, tags, category });
const u = (id: string, title: string, description: string, words: VocabularyItem[], phrases: PhraseSpec[], dialogue: LineSpec[], reading: ReadingText & { title: string }): UnitSeed => ({ id, title, description, words, phrases, dialogue, reading });

export const ADDITIONAL_EN_PART11_UNITS: Record<string, UnitSeed[]> = {
  A0: [
    u("u44", "Getting Dressed", "Name everyday clothes and describe what people wear.", [
      w("shirt", "camisa", "noun", "/ʃɜːrt/", "a piece of clothing worn on the upper body", "This shirt is blue.", "Esta camisa es azul.", ["top", "blouse"], [], ["wear a shirt", "white shirt"], ["shirt, shirtless"], ["clothes", "daily life"], "clothing"),
      w("trousers", "pantalones", "noun", "/ˈtraʊzərz/", "clothing covering the legs", "These trousers are clean.", "Estos pantalones están limpios.", ["pants", "slacks"], [], ["pair of trousers", "wear trousers"], ["trouser"], ["clothes", "daily life"], "clothing"),
      w("shoe", "zapato", "noun", "/ʃuː/", "a covering for the foot", "My shoe is under the chair.", "Mi zapato está debajo de la silla.", ["footwear", "trainer"], [], ["pair of shoes", "clean your shoes"], ["shoe, shoelace"], ["clothes", "body"], "clothing"),
      w("coat", "abrigo", "noun", "/koʊt/", "a warm piece of clothing worn outside", "Put on your coat.", "Ponte el abrigo.", ["jacket", "overcoat"], [], ["winter coat", "wear a coat"], ["coat, coating"], ["clothes", "weather"], "clothing"),
      w("hat", "sombrero", "noun", "/hæt/", "a covering worn on the head", "He wears a red hat.", "Él lleva un sombrero rojo.", ["cap", "headwear"], [], ["wear a hat", "sun hat"], ["hat, hatless"], ["clothes", "weather"], "clothing"),
      w("wear", "llevar puesto", "verb", "/wer/", "to have clothing on your body", "I wear a warm coat in winter.", "Llevo un abrigo caliente en invierno.", ["put on", "dress in"], ["remove"], ["wear clothes", "wear a uniform"], ["wear, wearer, wearable"], ["clothes", "daily life"], "daily action"),
      w("put on", "ponerse", "phrasal verb", "/pʊt ɑːn/", "to place clothing on your body", "Put on your shoes.", "Ponte los zapatos.", ["dress in", "don"], ["take off"], ["put on a coat", "put on shoes"], ["put, putting"], ["clothes", "routine"], "daily action"),
      w("take off", "quitarse", "phrasal verb", "/teɪk ɔːf/", "to remove clothing from your body", "Take off your wet coat.", "Quítate el abrigo mojado.", ["remove", "undress"], ["put on"], ["take off shoes", "take off a jacket"], ["take, taking"], ["clothes", "routine"], "daily action"),
    ], [{ phrase: "What are you wearing?", translation: "¿Qué llevas puesto?" }, { phrase: "Put on your coat, please.", translation: "Ponte el abrigo, por favor." }, { phrase: "These shoes are comfortable.", translation: "Estos zapatos son cómodos." }, { phrase: "Take off your wet jacket.", translation: "Quítate la chaqueta mojada." }], [{ speaker: "A", text: "What are you wearing today?", translation: "¿Qué llevas puesto hoy?" }, { speaker: "B", text: "A blue shirt and black trousers.", translation: "Una camisa azul y pantalones negros." }, { speaker: "A", text: "Is it cold outside?", translation: "¿Hace frío fuera?" }, { speaker: "B", text: "Yes, I will put on my coat.", translation: "Sí, me pondré el abrigo." }], { title: "Ready for the Day", text: "Before leaving home, people choose clothes for the weather. They put on shoes, a shirt, and a coat when it is cold. At home, they take off their coat and hang it by the door.", translation: "Antes de salir de casa, las personas eligen ropa para el tiempo. Se ponen zapatos, una camisa y un abrigo cuando hace frío. En casa, se quitan el abrigo y lo cuelgan junto a la puerta." }),
    u("u45", "In the Park", "Use simple words for outdoor places, movement, and play.", [
      w("park", "parque", "noun", "/pɑːrk/", "a public green place for walking or relaxing", "The park is near our house.", "El parque está cerca de nuestra casa.", ["green", "garden"], ["building"], ["go to the park", "city park"], ["park, parking"], ["outdoors", "city"], "place"),
      w("tree", "árbol", "noun", "/triː/", "a tall plant with a trunk and branches", "That tree is very old.", "Ese árbol es muy viejo.", ["plant", "wood"], [], ["plant a tree", "under a tree"], ["tree, treetop"], ["nature", "outdoors"], "nature"),
      w("grass", "césped", "noun", "/ɡræs/", "short green plants covering the ground", "The children sit on the grass.", "Los niños se sientan en el césped.", ["lawn", "turf"], [], ["green grass", "cut the grass"], ["grass, grassy"], ["nature", "outdoors"], "nature"),
      w("bench", "banco", "noun", "/bentʃ/", "a long seat for two or more people", "We sit on the bench.", "Nos sentamos en el banco.", ["seat", "pew"], [], ["park bench", "sit on a bench"], ["bench, benched"], ["park", "furniture"], "place"),
      w("ball", "pelota", "noun", "/bɔːl/", "a round object used in games", "The ball is under the tree.", "La pelota está debajo del árbol.", ["sphere", "plaything"], [], ["kick a ball", "throw a ball"], ["ball, ballgame"], ["play", "sports"], "play"),
      w("walk", "caminar", "verb", "/wɔːk/", "to move on foot", "We walk in the park.", "Caminamos en el parque.", ["stroll", "go on foot"], ["run"], ["walk slowly", "walk home"], ["walk, walker, walking"], ["movement", "outdoors"], "movement"),
      w("run", "correr", "verb", "/rʌn/", "to move quickly on your feet", "The dog can run fast.", "El perro puede correr rápido.", ["jog", "race"], ["walk"], ["run fast", "run across"], ["run, runner, running"], ["movement", "sports"], "movement"),
      w("play", "jugar", "verb", "/pleɪ/", "to do an activity for enjoyment", "The children play with a ball.", "Los niños juegan con una pelota.", ["have fun", "enjoy"], ["work"], ["play a game", "play outside"], ["play, player, playful"], ["children", "outdoors"], "play"),
    ], [{ phrase: "Shall we walk to the park?", translation: "¿Caminamos hasta el parque?" }, { phrase: "The children are playing outside.", translation: "Los niños están jugando fuera." }, { phrase: "Please do not run near the road.", translation: "No corras cerca de la carretera." }, { phrase: "Let us sit on the bench.", translation: "Sentémonos en el banco." }], [{ speaker: "A", text: "Where shall we go?", translation: "¿Adónde vamos?" }, { speaker: "B", text: "Let us walk to the park.", translation: "Caminemos hasta el parque." }, { speaker: "A", text: "Can we play with the ball?", translation: "¿Podemos jugar con la pelota?" }, { speaker: "B", text: "Yes, but stay away from the road.", translation: "Sí, pero aléjate de la carretera." }], { title: "An Afternoon Outside", text: "A park has trees, grass, and benches. People walk there, sit in the shade, and play simple games. Children can run and throw a ball while adults enjoy the fresh air.", translation: "Un parque tiene árboles, césped y bancos. Las personas caminan allí, se sientan a la sombra y juegan a juegos sencillos. Los niños pueden correr y lanzar una pelota mientras los adultos disfrutan del aire fresco." }),
  ],
  A1: [
    u("u44", "Public Services", "Ask for help at common public places and describe simple services.", [
      w("library", "biblioteca", "noun", "/ˈlaɪbreri/", "a place where people borrow or read books", "The library closes at six.", "La biblioteca cierra a las seis.", ["book centre", "reading room"], [], ["public library", "visit the library"], ["library, librarian"], ["city", "learning"], "public place"),
      w("post office", "oficina de correos", "noun", "/ˈpoʊst ˌɔːfɪs/", "a place that sends letters and parcels", "The post office is on the corner.", "La oficina de correos está en la esquina.", ["mail office"], [], ["go to the post office", "post office counter"], ["post, postal"], ["city", "services"], "public place"),
      w("clinic", "clínica", "noun", "/ˈklɪnɪk/", "a place where people receive medical care", "The clinic opens early.", "La clínica abre temprano.", ["health centre", "practice"], [], ["local clinic", "visit a clinic"], ["clinical, clinician"], ["health", "city"], "health"),
      w("counter", "mostrador", "noun", "/ˈkaʊntər/", "a surface where customers are served", "Please wait at the counter.", "Espera en el mostrador, por favor.", ["desk", "service point"], [], ["service counter", "at the counter"], ["counter, counter-service"], ["services", "shopping"], "public place"),
      w("form", "formulario", "noun", "/fɔːrm/", "a document with spaces for information", "Please complete this form.", "Completa este formulario, por favor.", ["document", "application"], [], ["fill in a form", "application form"], ["form, formal, formation"], ["services", "work"], "document"),
      w("borrow", "pedir prestado", "verb", "/ˈbɑːroʊ/", "to take and use something before returning it", "Can I borrow this book?", "¿Puedo pedir prestado este libro?", ["loan", "take temporarily"], ["return"], ["borrow a book", "borrow from a library"], ["borrow, borrower"], ["library", "learning"], "service action"),
      w("return", "devolver", "verb", "/rɪˈtɜːrn/", "to give something back or go back to a place", "Please return the book next week.", "Devuelve el libro la próxima semana, por favor.", ["give back", "go back"], ["keep"], ["return a book", "return home"], ["return, returning"], ["library", "services"], "service action"),
      w("queue", "hacer cola", "verb", "/kjuː/", "to wait in a line of people", "We queued for ten minutes.", "Hicimos cola durante diez minutos.", ["line up", "wait"], ["skip"], ["queue patiently", "queue at the counter"], ["queue, queuing"], ["services", "time"], "social action"),
    ], [{ phrase: "Where can I fill in this form?", translation: "¿Dónde puedo completar este formulario?" }, { phrase: "Please wait at the counter.", translation: "Espera en el mostrador, por favor." }, { phrase: "Can I borrow this book?", translation: "¿Puedo pedir prestado este libro?" }, { phrase: "You must return it next week.", translation: "Debes devolverlo la próxima semana." }], [{ speaker: "A", text: "Is this the queue for the library?", translation: "¿Es esta la cola de la biblioteca?" }, { speaker: "B", text: "Yes. You can borrow two books.", translation: "Sí. Puedes pedir prestados dos libros." }, { speaker: "A", text: "Where do I complete the form?", translation: "¿Dónde completo el formulario?" }, { speaker: "B", text: "At the counter, please.", translation: "En el mostrador, por favor." }], { title: "Using a Public Service", text: "Public services help people in daily life. At a library, visitors can borrow books and return them later. At another service, they may complete a form, wait in a queue, and speak to someone at a counter.", translation: "Los servicios públicos ayudan a las personas en la vida diaria. En una biblioteca, los visitantes pueden pedir prestados libros y devolverlos después. En otro servicio, pueden completar un formulario, hacer cola y hablar con alguien en un mostrador." }),
    u("u45", "Free Time", "Talk about hobbies, plans, and activities after work or school.", [
      w("hobby", "afición", "noun", "/ˈhɑːbi/", "an activity done regularly for enjoyment", "Reading is my favourite hobby.", "Leer es mi afición favorita.", ["interest", "pastime"], ["work"], ["take up a hobby", "favourite hobby"], ["hobby, hobbyist"], ["leisure", "interests"], "free time"),
      w("music", "música", "noun", "/ˈmjuːzɪk/", "sounds arranged for people to listen to", "I listen to music every day.", "Escucho música todos los días.", ["song", "melody"], ["silence"], ["listen to music", "live music"], ["music, musical, musician"], ["arts", "leisure"], "arts"),
      w("painting", "pintura", "noun", "/ˈpeɪntɪŋ/", "a picture made with paint", "Her painting is colourful.", "Su pintura es colorida.", ["artwork", "picture"], [], ["oil painting", "paint a picture"], ["paint, painter, painting"], ["arts", "leisure"], "arts"),
      w("photograph", "fotografía", "noun", "/ˈfoʊtəɡræf/", "a picture made with a camera", "I took a photograph of the lake.", "Tomé una fotografía del lago.", ["photo", "picture"], [], ["take a photograph", "family photograph"], ["photograph, photographer, photographic"], ["arts", "technology"], "arts"),
      w("club", "club", "noun", "/klʌb/", "a group of people with a shared interest", "She joined a book club.", "Se unió a un club de lectura.", ["group", "association"], ["individual"], ["join a club", "sports club"], ["club, club member"], ["leisure", "community"], "community"),
      w("join", "unirse", "verb", "/dʒɔɪn/", "to become a member of a group or activity", "I want to join the swimming club.", "Quiero unirme al club de natación.", ["enter", "participate"], ["leave"], ["join a club", "join a class"], ["join, joining"], ["leisure", "community"], "social action"),
      w("practise", "practicar", "verb", "/ˈpræktɪs/", "to do something repeatedly to improve", "I practise the piano on Sundays.", "Practico el piano los domingos.", ["train", "rehearse"], ["neglect"], ["practise a skill", "practise regularly"], ["practice, practise, practitioner"], ["learning", "leisure"], "learning action"),
      w("relax", "relajarse", "verb", "/rɪˈlæks/", "to rest and become less worried", "I relax by listening to music.", "Me relajo escuchando música.", ["rest", "unwind"], ["worry"], ["relax after work", "relax at home"], ["relax, relaxed, relaxation"], ["wellbeing", "leisure"], "wellbeing"),
    ], [{ phrase: "What do you do in your free time?", translation: "¿Qué haces en tu tiempo libre?" }, { phrase: "I joined a photography club.", translation: "Me uní a un club de fotografía." }, { phrase: "I practise every Sunday.", translation: "Practico todos los domingos." }, { phrase: "Music helps me relax.", translation: "La música me ayuda a relajarme." }], [{ speaker: "A", text: "What is your new hobby?", translation: "¿Cuál es tu nueva afición?" }, { speaker: "B", text: "I joined a photography club.", translation: "Me uní a un club de fotografía." }, { speaker: "A", text: "Do you practise often?", translation: "¿Practicas a menudo?" }, { speaker: "B", text: "Yes, and it helps me relax.", translation: "Sí, y me ayuda a relajarme." }], { title: "A Balanced Week", text: "Free time gives people a chance to enjoy interests outside work and school. Some join a club, practise music, or take photographs. Others relax with friends. A regular hobby can make a busy week feel more balanced.", translation: "El tiempo libre da a las personas la oportunidad de disfrutar de intereses fuera del trabajo y la escuela. Algunos se unen a un club, practican música o toman fotografías. Otros se relajan con amigos. Una afición habitual puede hacer que una semana ocupada parezca más equilibrada." }),
  ],
  A2: [
    u("u44", "Learning Strategies", "Describe effective ways to study and make progress.", [
      w("goal", "objetivo", "noun", "/ɡoʊl/", "something you want to achieve", "My goal is to speak confidently.", "Mi objetivo es hablar con confianza.", ["aim", "target"], ["failure"], ["set a goal", "reach a goal"], ["goal, goal-setting"], ["learning", "planning"], "learning"),
      w("progress", "progreso", "noun", "/ˈprɑːɡres/", "movement towards a better or more advanced state", "I can see my progress.", "Puedo ver mi progreso.", ["development", "improvement"], ["decline"], ["make progress", "steady progress"], ["progress, progressive"], ["learning", "development"], "learning"),
      w("strategy", "estrategia", "noun", "/ˈstrætədʒi/", "a plan used to achieve a goal", "This strategy helps me remember words.", "Esta estrategia me ayuda a recordar palabras.", ["plan", "method"], ["confusion"], ["learning strategy", "effective strategy"], ["strategic, strategy"], ["learning", "planning"], "learning"),
      w("memory", "memoria", "noun", "/ˈmeməri/", "the ability to remember information", "Practice strengthens your memory.", "La práctica fortalece tu memoria.", ["recall", "recollection"], ["forgetfulness"], ["long-term memory", "memory skill"], ["memorize, memory, memorable"], ["learning", "mind"], "learning"),
      w("mistake", "error", "noun", "/mɪˈsteɪk/", "something done incorrectly", "A mistake can teach you something.", "Un error puede enseñarte algo.", ["error", "fault"], ["success"], ["make a mistake", "correct a mistake"], ["mistake, mistaken"], ["learning", "communication"], "learning"),
      w("review", "repasar", "verb", "/rɪˈvjuː/", "to study or examine something again", "I review new words every evening.", "Repaso palabras nuevas cada tarde.", ["revise", "check"], ["forget"], ["review vocabulary", "review notes"], ["review, reviewer, revision"], ["learning", "routine"], "learning action"),
      w("memorize", "memorizar", "verb", "/ˈmeməraɪz/", "to learn something so you can remember it", "She memorized the phrase.", "Ella memorizó la frase.", ["learn by heart", "remember"], ["forget"], ["memorize a word", "memorize a list"], ["memory, memorize, memorization"], ["learning", "memory"], "learning action"),
      w("concentrate", "concentrarse", "verb", "/ˈkɑːnsəntreɪt/", "to give all your attention to something", "I concentrate better in the morning.", "Me concentro mejor por la mañana.", ["focus", "attend"], ["distract"], ["concentrate on a task", "concentrate fully"], ["concentrate, concentration"], ["learning", "mind"], "learning action"),
    ], [{ phrase: "What is your learning goal?", translation: "¿Cuál es tu objetivo de aprendizaje?" }, { phrase: "Review the words every day.", translation: "Repasa las palabras todos los días." }, { phrase: "Mistakes are part of progress.", translation: "Los errores son parte del progreso." }, { phrase: "I need to concentrate.", translation: "Necesito concentrarme." }], [{ speaker: "A", text: "How do you remember new words?", translation: "¿Cómo recuerdas las palabras nuevas?" }, { speaker: "B", text: "I review them and use them in sentences.", translation: "Las repaso y las uso en frases." }, { speaker: "A", text: "What is your strategy?", translation: "¿Cuál es tu estrategia?" }, { speaker: "B", text: "I set a goal and practise a little every day.", translation: "Me fijo un objetivo y practico un poco cada día." }], { title: "Learning with a Plan", text: "A clear goal gives direction to learning. A useful strategy combines practice, review, and concentration. Learners make mistakes, but they use those mistakes to improve their memory and measure progress.", translation: "Un objetivo claro da dirección al aprendizaje. Una estrategia útil combina práctica, repaso y concentración. Los estudiantes cometen errores, pero usan esos errores para mejorar su memoria y medir su progreso." }),
    u("u45", "City Life", "Describe urban spaces, transport, and changes in a neighbourhood.", [
      w("neighbourhood", "barrio", "noun", "/ˈneɪbərhʊd/", "an area of a town where people live", "Our neighbourhood is quiet.", "Nuestro barrio es tranquilo.", ["district", "area"], [], ["local neighbourhood", "neighbourhood park"], ["neighbour, neighbourhood"], ["city", "community"], "city"),
      w("traffic", "tráfico", "noun", "/ˈtræfɪk/", "the vehicles using a road", "Traffic is heavy at five o'clock.", "El tráfico es intenso a las cinco.", ["vehicles", "congestion"], ["empty road"], ["heavy traffic", "traffic jam"], ["traffic, trafficker"], ["city", "transport"], "transport"),
      w("pedestrian", "peatón", "noun", "/pəˈdestriən/", "a person walking rather than travelling in a vehicle", "The road is safe for pedestrians.", "La carretera es segura para los peatones.", ["walker", "passer-by"], ["driver"], ["pedestrian crossing", "pedestrian area"], ["pedestrian, pedestrianize"], ["city", "safety"], "transport"),
      w("facility", "instalación", "noun", "/fəˈsɪləti/", "a place or equipment provided for a purpose", "The sports facility is open to everyone.", "La instalación deportiva está abierta a todos.", ["service", "amenity"], [], ["public facility", "sports facility"], ["facilitate, facility"], ["city", "community"], "public place"),
      w("commute", "desplazarse al trabajo", "verb", "/kəˈmjuːt/", "to travel regularly between home and work", "I commute by train.", "Me desplazo al trabajo en tren.", ["travel", "journey"], ["stay"], ["daily commute", "commute to work"], ["commute, commuter"], ["work", "transport"], "transport action"),
      w("expand", "expandirse", "verb", "/ɪkˈspænd/", "to become larger or make something larger", "The city continues to expand.", "La ciudad sigue expandiéndose.", ["grow", "extend"], ["contract"], ["expand rapidly", "expand a service"], ["expand, expansion, expansive"], ["city", "change"], "change action"),
      w("renovate", "renovar", "verb", "/ˈrenəveɪt/", "to repair and improve an old building or place", "The council will renovate the market.", "El ayuntamiento renovará el mercado.", ["restore", "modernize"], ["neglect"], ["renovate a building", "renovation project"], ["renovate, renovation"], ["city", "buildings"], "change action"),
      w("convenient", "conveniente", "adjective", "/kənˈviːniənt/", "easy to use or suitable for a situation", "The new station is convenient.", "La nueva estación es conveniente.", ["practical", "handy"], ["inconvenient"], ["convenient location", "convenient service"], ["convenience, convenient"], ["city", "daily life"], "quality"),
    ], [{ phrase: "The neighbourhood has heavy traffic.", translation: "El barrio tiene mucho tráfico." }, { phrase: "The new facility is convenient.", translation: "La nueva instalación es conveniente." }, { phrase: "The council will renovate the market.", translation: "El ayuntamiento renovará el mercado." }, { phrase: "Many people commute by train.", translation: "Muchas personas se desplazan en tren." }], [{ speaker: "A", text: "How has the neighbourhood changed?", translation: "¿Cómo ha cambiado el barrio?" }, { speaker: "B", text: "The old market was renovated and new facilities opened.", translation: "El mercado antiguo fue renovado y se abrieron nuevas instalaciones." }, { speaker: "A", text: "Is it convenient to commute now?", translation: "¿Es conveniente desplazarse ahora?" }, { speaker: "B", text: "Yes, but traffic is still heavy at rush hour.", translation: "Sí, pero el tráfico sigue siendo intenso en hora punta." }], { title: "A Changing Neighbourhood", text: "As a city expands, neighbourhoods change. Old buildings may be renovated and new facilities may appear. Good transport makes commuting convenient, but planners must also protect pedestrians and reduce traffic.", translation: "A medida que una ciudad se expande, los barrios cambian. Los edificios antiguos pueden renovarse y pueden aparecer nuevas instalaciones. Un buen transporte hace cómodo el desplazamiento, pero los planificadores también deben proteger a los peatones y reducir el tráfico." }),
  ],
  B1: [
    u("u44", "Communication Skills", "Discuss listening, clarity, disagreement, and cooperation.", [
      w("clarity", "claridad", "noun", "/ˈklerəti/", "the quality of being easy to understand", "Clarity matters in a difficult discussion.", "La claridad importa en una discusión difícil.", ["clearness", "precision"], ["confusion"], ["clarity of purpose", "speak with clarity"], ["clear, clarity, clarify"], ["communication", "work"], "communication"),
      w("misunderstanding", "malentendido", "noun", "/ˌmɪsʌndərˈstændɪŋ/", "a failure to understand something correctly", "The disagreement began with a misunderstanding.", "El desacuerdo comenzó con un malentendido.", ["confusion", "error"], ["understanding"], ["avoid misunderstanding", "serious misunderstanding"], ["understand, misunderstanding"], ["communication", "relationships"], "communication"),
      w("tone", "tono", "noun", "/toʊn/", "the attitude expressed by a person's voice or writing", "Her tone sounded respectful.", "Su tono sonaba respetuoso.", ["manner", "attitude"], ["silence"], ["friendly tone", "tone of voice"], ["tone, tonal"], ["communication", "emotion"], "communication"),
      w("gesture", "gesto", "noun", "/ˈdʒestʃər/", "a movement that communicates an idea or feeling", "A smile is a friendly gesture.", "Una sonrisa es un gesto amistoso.", ["sign", "movement"], ["stillness"], ["make a gesture", "hand gesture"], ["gesture, gestural"], ["communication", "body"], "communication"),
      w("clarify", "aclarar", "verb", "/ˈklerəfaɪ/", "to make an idea or statement easier to understand", "Could you clarify the final point?", "¿Podrías aclarar el punto final?", ["explain", "specify"], ["obscure"], ["clarify a point", "clarify meaning"], ["clear, clarify, clarification"], ["communication", "learning"], "communication action"),
      w("negotiate", "negociar", "verb", "/nɪˈɡoʊʃieɪt/", "to discuss in order to reach an agreement", "They negotiated a practical solution.", "Negociaron una solución práctica.", ["bargain", "mediate"], ["impose"], ["negotiate a solution", "negotiate terms"], ["negotiate, negotiation, negotiator"], ["work", "relationships"], "social action"),
      w("interrupt", "interrumpir", "verb", "/ˌɪntəˈrʌpt/", "to stop someone while they are speaking or doing something", "Please do not interrupt the speaker.", "No interrumpas al orador, por favor.", ["disturb", "break in"], ["listen"], ["interrupt a conversation", "interrupt politely"], ["interrupt, interruption"], ["communication", "meetings"], "communication action"),
      w("respectful", "respetuoso", "adjective", "/rɪˈspektfəl/", "showing consideration for other people", "They had a respectful disagreement.", "Tuvieron un desacuerdo respetuoso.", ["polite", "considerate"], ["rude"], ["respectful tone", "remain respectful"], ["respect, respectful, respectfully"], ["communication", "relationships"], "character"),
    ], [{ phrase: "Could you clarify your point?", translation: "¿Podrías aclarar tu punto?" }, { phrase: "Please do not interrupt.", translation: "No interrumpas, por favor." }, { phrase: "They negotiated a respectful solution.", translation: "Negociaron una solución respetuosa." }, { phrase: "The tone was calm and clear.", translation: "El tono fue tranquilo y claro." }], [{ speaker: "A", text: "I think we have a misunderstanding.", translation: "Creo que tenemos un malentendido." }, { speaker: "B", text: "Let me clarify what I meant.", translation: "Déjame aclarar lo que quise decir." }, { speaker: "A", text: "I disagree, but I will listen.", translation: "No estoy de acuerdo, pero escucharé." }, { speaker: "B", text: "Thank you. Let us negotiate a solution.", translation: "Gracias. Negociemos una solución." }], { title: "A Productive Conversation", text: "Good communication depends on clarity, tone, and attention. A misunderstanding can be resolved when people clarify their meaning, listen without interrupting, and remain respectful even when they disagree.", translation: "La buena comunicación depende de la claridad, el tono y la atención. Un malentendido puede resolverse cuando las personas aclaran su significado, escuchan sin interrumpir y siguen siendo respetuosas aunque no estén de acuerdo." }),
    u("u45", "Science in Daily Life", "Explain observations, causes, and practical scientific conclusions.", [
      w("observation", "observación", "noun", "/ˌɑːbzərˈveɪʃən/", "something noticed by watching or measuring", "The observation changed our hypothesis.", "La observación cambió nuestra hipótesis.", ["notice", "finding"], ["guess"], ["careful observation", "make an observation"], ["observe, observation, observable"], ["science", "learning"], "science"),
      w("cause", "causa", "noun", "/kɔːz/", "a person or thing that makes something happen", "Scientists looked for the cause.", "Los científicos buscaron la causa.", ["reason", "source"], ["effect"], ["main cause", "possible cause"], ["cause, causal, causation"], ["science", "reasoning"], "reasoning"),
      w("effect", "efecto", "noun", "/ɪˈfekt/", "a change produced by an action or event", "The medicine had a positive effect.", "La medicina tuvo un efecto positivo.", ["result", "consequence"], ["cause"], ["side effect", "long-term effect"], ["effect, effective, effectively"], ["science", "health"], "reasoning"),
      w("variable", "variable", "noun", "/ˈveriəbəl/", "a factor that can change in an experiment or situation", "Temperature was the main variable.", "La temperatura era la variable principal.", ["factor", "condition"], ["constant"], ["independent variable", "control a variable"], ["vary, variable, variation"], ["science", "research"], "science"),
      w("measure", "medir", "verb", "/ˈmeʒər/", "to find the size, amount, or degree of something", "We measured the water carefully.", "Medimos el agua con cuidado.", ["quantify", "calculate"], ["estimate"], ["measure accurately", "measure change"], ["measure, measurement, measurable"], ["science", "data"], "research action"),
      w("predict", "predecir", "verb", "/prɪˈdɪkt/", "to say what will happen before it happens", "The model predicts a warmer summer.", "El modelo predice un verano más cálido.", ["forecast", "anticipate"], ["doubt"], ["predict a result", "predict accurately"], ["predict, prediction, predictable"], ["science", "future"], "thinking action"),
      w("accurate", "exacto", "adjective", "/ˈækjərət/", "correct and without mistakes", "The measurement is accurate.", "La medición es exacta.", ["precise", "correct"], ["inaccurate"], ["accurate result", "highly accurate"], ["accuracy, accurate, accurately"], ["science", "quality"], "quality"),
      w("likely", "probable", "adjective", "/ˈlaɪkli/", "probable or expected to happen", "Rain is likely this evening.", "Es probable que llueva esta tarde.", ["probable", "possible"], ["unlikely"], ["highly likely", "likely cause"], ["like, likely"], ["science", "prediction"], "probability"),
    ], [{ phrase: "What was the main cause?", translation: "¿Cuál fue la causa principal?" }, { phrase: "The effect was easy to measure.", translation: "El efecto fue fácil de medir." }, { phrase: "The model predicts a likely result.", translation: "El modelo predice un resultado probable." }, { phrase: "The measurement is accurate.", translation: "La medición es exacta." }], [{ speaker: "A", text: "What did the observation show?", translation: "¿Qué mostró la observación?" }, { speaker: "B", text: "It suggested that temperature was an important variable.", translation: "Sugirió que la temperatura era una variable importante." }, { speaker: "A", text: "Can we predict the effect?", translation: "¿Podemos predecir el efecto?" }, { speaker: "B", text: "Only if we measure the conditions accurately.", translation: "Solo si medimos las condiciones con exactitud." }], { title: "Testing an Explanation", text: "Science connects observations with causes and effects. Researchers measure variables carefully and use evidence to test a prediction. An accurate result may support a likely explanation, but further observation can always improve understanding.", translation: "La ciencia conecta las observaciones con las causas y los efectos. Los investigadores miden las variables cuidadosamente y usan pruebas para comprobar una predicción. Un resultado exacto puede apoyar una explicación probable, pero más observación siempre puede mejorar la comprensión." }),
  ],
  B2: [
    u("u44", "Negotiation and Conflict", "Analyse disagreement, compromise, and practical resolution.", [
      w("conflict", "conflicto", "noun", "/ˈkɑːnflɪkt/", "a serious disagreement between people or groups", "The conflict lasted for several months.", "El conflicto duró varios meses.", ["dispute", "clash"], ["harmony"], ["resolve a conflict", "armed conflict"], ["conflict, conflicting"], ["society", "relationships"], "society"),
      w("compromise", "compromiso", "noun", "/ˈkɑːmprəmaɪz/", "an agreement in which each side accepts less than it wanted", "Both sides reached a compromise.", "Ambas partes alcanzaron un compromiso.", ["agreement", "settlement"], ["deadlock"], ["reach a compromise", "political compromise"], ["compromise, compromising"], ["communication", "society"], "negotiation"),
      w("grievance", "queja formal", "noun", "/ˈɡriːvəns/", "a complaint about unfair treatment", "Workers submitted a formal grievance.", "Los trabajadores presentaron una queja formal.", ["complaint", "resentment"], ["satisfaction"], ["raise a grievance", "formal grievance"], ["grieve, grievance"], ["work", "justice"], "conflict"),
      w("stakeholder", "parte interesada", "noun", "/ˈsteɪkhoʊldər/", "a person or group affected by a decision", "Every stakeholder was invited to the meeting.", "Se invitó a todas las partes interesadas a la reunión.", ["participant", "interested party"], [], ["key stakeholder", "stakeholder interests"], ["stake, stakeholder"], ["work", "society"], "organisation"),
      w("mediate", "mediar", "verb", "/ˈmiːdieɪt/", "to help people reach an agreement in a dispute", "An independent expert mediated the dispute.", "Un experto independiente medió en la disputa.", ["arbitrate", "intervene"], ["escalate"], ["mediate a conflict", "mediate between parties"], ["mediate, mediation, mediator"], ["law", "relationships"], "social action"),
      w("concede", "conceder", "verb", "/kənˈsiːd/", "to admit that something is true or accept a point", "She conceded that the plan had risks.", "Concedió que el plan tenía riesgos.", ["admit", "acknowledge"], ["deny"], ["concede a point", "concede defeat"], ["concede, concession"], ["argument", "communication"], "reasoning action"),
      w("contentious", "controvertido", "adjective", "/kənˈtenʃəs/", "likely to cause disagreement", "The proposal remains contentious.", "La propuesta sigue siendo controvertida.", ["controversial", "disputed"], ["uncontroversial"], ["contentious issue", "highly contentious"], ["contention, contentious"], ["society", "politics"], "conflict"),
      w("mutual", "mutuo", "adjective", "/ˈmjuːtʃuəl/", "shared by two or more people or groups", "They found a mutual interest.", "Encontraron un interés mutuo.", ["shared", "reciprocal"], ["one-sided"], ["mutual agreement", "mutual respect"], ["mutual, mutually"], ["relationships", "communication"], "relationships"),
    ], [{ phrase: "Both sides need to reach a compromise.", translation: "Ambas partes deben alcanzar un compromiso." }, { phrase: "An independent person can mediate.", translation: "Una persona independiente puede mediar." }, { phrase: "The issue remains contentious.", translation: "El asunto sigue siendo controvertido." }, { phrase: "They reached a mutual agreement.", translation: "Alcanzaron un acuerdo mutuo." }], [{ speaker: "A", text: "Why has the conflict continued?", translation: "¿Por qué ha continuado el conflicto?" }, { speaker: "B", text: "The stakeholders have not found a compromise.", translation: "Las partes interesadas no han encontrado un compromiso." }, { speaker: "A", text: "Could an independent mediator help?", translation: "¿Podría ayudar un mediador independiente?" }, { speaker: "B", text: "Yes, if both sides are willing to concede something.", translation: "Sí, si ambas partes están dispuestas a conceder algo." }], { title: "Finding Common Ground", text: "A contentious issue can damage relationships when stakeholders refuse to listen. Mediation creates space for each side to explain its grievance. A mutual agreement often requires compromise, but it can prevent a conflict from escalating.", translation: "Un asunto controvertido puede dañar las relaciones cuando las partes interesadas se niegan a escuchar. La mediación crea un espacio para que cada parte explique su queja. Un acuerdo mutuo suele requerir compromiso, pero puede evitar que un conflicto se intensifique." }),
    u("u45", "Digital Responsibility", "Debate online behaviour, security, and responsible technology use.", [
      w("algorithm", "algoritmo", "noun", "/ˈælɡərɪðəm/", "a set of rules used to solve a problem or process data", "The algorithm recommends new videos.", "El algoritmo recomienda nuevos vídeos.", ["procedure", "formula"], [], ["computer algorithm", "algorithmic decision"], ["algorithm, algorithmic"], ["technology", "data"], "technology"),
      w("security", "seguridad", "noun", "/sɪˈkjʊrəti/", "protection from danger, loss, or unauthorised access", "Online security requires strong passwords.", "La seguridad en línea requiere contraseñas fuertes.", ["safety", "protection"], ["vulnerability"], ["online security", "security measure"], ["secure, security, securely"], ["technology", "safety"], "digital safety"),
      w("consent", "consentimiento", "noun", "/kənˈsent/", "permission given freely after information is provided", "The app asks for consent before collecting data.", "La aplicación pide consentimiento antes de recoger datos.", ["permission", "agreement"], ["refusal"], ["informed consent", "give consent"], ["consent, consensual"], ["technology", "privacy"], "ethics"),
      w("surveillance", "vigilancia", "noun", "/sərˈveɪləns/", "careful watching of people or places", "Digital surveillance raises privacy concerns.", "La vigilancia digital plantea problemas de privacidad.", ["monitoring", "observation"], ["privacy"], ["mass surveillance", "digital surveillance"], ["survey, surveillance, surveil"], ["technology", "society"], "digital ethics"),
      w("encrypt", "cifrar", "verb", "/ɪnˈkrɪpt/", "to protect information by changing it into a secret code", "The service encrypts personal data.", "El servicio cifra los datos personales.", ["encode", "scramble"], ["decode"], ["encrypt a message", "encrypt data"], ["encrypt, encryption, encrypted"], ["technology", "security"], "digital action"),
      w("moderate", "moderar", "verb", "/ˈmɑːdəreɪt/", "to check and control content or discussion", "Volunteers moderate the online forum.", "Los voluntarios moderan el foro en línea.", ["supervise", "regulate"], ["ignore"], ["moderate content", "moderate a discussion"], ["moderate, moderation, moderator"], ["technology", "communication"], "digital action"),
      w("transparent", "transparente", "adjective", "/trænsˈperənt/", "open and easy to understand", "The company should be transparent about data use.", "La empresa debería ser transparente sobre el uso de datos.", ["open", "clear"], ["secretive"], ["transparent policy", "fully transparent"], ["transparency, transparent"], ["technology", "ethics"], "quality"),
      w("harmful", "perjudicial", "adjective", "/ˈhɑːrmfəl/", "causing damage or injury", "Some online content can be harmful.", "Algunos contenidos en línea pueden ser perjudiciales.", ["damaging", "destructive"], ["beneficial"], ["harmful effect", "potentially harmful"], ["harm, harmful, harmless"], ["technology", "health"], "risk"),
    ], [{ phrase: "The platform must protect user security.", translation: "La plataforma debe proteger la seguridad del usuario." }, { phrase: "Users should give informed consent.", translation: "Los usuarios deberían dar su consentimiento informado." }, { phrase: "The company should be transparent.", translation: "La empresa debería ser transparente." }, { phrase: "Some content may be harmful.", translation: "Algunos contenidos pueden ser perjudiciales." }], [{ speaker: "A", text: "Why does the app need my data?", translation: "¿Por qué necesita la aplicación mis datos?" }, { speaker: "B", text: "The algorithm uses it to personalise recommendations.", translation: "El algoritmo los usa para personalizar recomendaciones." }, { speaker: "A", text: "Does the service encrypt the information?", translation: "¿Cifra el servicio la información?" }, { speaker: "B", text: "It should, and its policy should be transparent.", translation: "Debería hacerlo, y su política debería ser transparente." }], { title: "Using Technology Carefully", text: "Digital services can be useful, but they also create responsibilities. Algorithms process personal data, while surveillance can threaten privacy. Transparent policies, informed consent, encryption, and careful moderation help reduce harmful effects.", translation: "Los servicios digitales pueden ser útiles, pero también crean responsabilidades. Los algoritmos procesan datos personales, mientras que la vigilancia puede amenazar la privacidad. Las políticas transparentes, el consentimiento informado, el cifrado y una moderación cuidadosa ayudan a reducir los efectos perjudiciales." }),
  ],
  C1: [
    u("u44", "Institutions and Reform", "Evaluate institutional power, legitimacy, and long-term reform.", [
      w("institution", "institución", "noun", "/ˌɪnstɪˈtuːʃən/", "an established organisation with an important public role", "The institution published a new report.", "La institución publicó un nuevo informe.", ["organisation", "body"], [], ["public institution", "institutional reform"], ["institute, institution, institutional"], ["society", "government"], "public life"),
      w("legitimacy", "legitimidad", "noun", "/lɪˈdʒɪtɪməsi/", "acceptance that an authority or action is lawful and justified", "The decision damaged the institution's legitimacy.", "La decisión dañó la legitimidad de la institución.", ["validity", "authority"], ["illegitimacy"], ["political legitimacy", "question legitimacy"], ["legitimate, legitimacy"], ["politics", "law"], "public policy"),
      w("reform", "reforma", "noun", "/rɪˈfɔːrm/", "a change intended to improve a system", "The reform aims to increase access.", "La reforma pretende aumentar el acceso.", ["revision", "improvement"], ["stagnation"], ["institutional reform", "reform agenda"], ["reform, reformer, reformist"], ["government", "change"], "public policy"),
      w("inefficiency", "ineficiencia", "noun", "/ˌɪnɪˈfɪʃənsi/", "failure to use time or resources effectively", "The review identified serious inefficiency.", "La revisión identificó una ineficiencia grave.", ["waste", "poor performance"], ["efficiency"], ["administrative inefficiency", "reduce inefficiency"], ["efficient, efficiency, inefficient"], ["work", "government"], "quality"),
      w("legitimate", "legítimo", "adjective", "/lɪˈdʒɪtɪmət/", "reasonable, lawful, or deserving to be accepted", "Citizens raised legitimate concerns.", "Los ciudadanos plantearon preocupaciones legítimas.", ["valid", "justified"], ["illegitimate"], ["legitimate concern", "legitimate authority"], ["legitimacy, legitimate"], ["law", "society"], "quality"),
      w("institutionalize", "institucionalizar", "verb", "/ˌɪnstɪˈtuːʃənəlaɪz/", "to make a practice part of an established system", "The policy institutionalized equal access.", "La política institucionalizó el acceso igualitario.", ["establish", "formalize"], ["dismantle"], ["institutionalize a practice", "institutionalize reform"], ["institution, institutional, institutionalize"], ["government", "change"], "policy action"),
      w("oversee", "supervisar", "verb", "/ˌoʊvərˈsiː/", "to watch and direct a process or organisation", "An independent body oversees the process.", "Un organismo independiente supervisa el proceso.", ["supervise", "monitor"], ["neglect"], ["oversee implementation", "oversee a programme"], ["see, oversee, oversight"], ["government", "work"], "leadership action"),
      w("sustainable", "sostenible", "adjective", "/səˈsteɪnəbəl/", "able to continue over a long period", "The reform needs sustainable funding.", "La reforma necesita financiación sostenible.", ["durable", "viable"], ["temporary"], ["sustainable reform", "sustainable funding"], ["sustain, sustainable, sustainability"], ["policy", "planning"], "quality"),
    ], [{ phrase: "The reform must have legitimate support.", translation: "La reforma debe tener apoyo legítimo." }, { phrase: "An independent body should oversee implementation.", translation: "Un organismo independiente debería supervisar la aplicación." }, { phrase: "The review exposed institutional inefficiency.", translation: "La revisión expuso una ineficiencia institucional." }, { phrase: "Sustainable change requires long-term funding.", translation: "El cambio sostenible requiere financiación a largo plazo." }], [{ speaker: "A", text: "Why did the reform lose legitimacy?", translation: "¿Por qué perdió legitimidad la reforma?" }, { speaker: "B", text: "The institution failed to explain its decisions.", translation: "La institución no explicó sus decisiones." }, { speaker: "A", text: "Who should oversee the new programme?", translation: "¿Quién debería supervisar el nuevo programa?" }, { speaker: "B", text: "An independent body with a clear mandate.", translation: "Un organismo independiente con un mandato claro." }], { title: "Changing an Institution", text: "Institutional reform is difficult because established systems have power and habits. A legitimate reform must address inefficiency, explain its purpose, and create oversight. If change is to last, it needs sustainable funding and public trust.", translation: "La reforma institucional es difícil porque los sistemas establecidos tienen poder y hábitos. Una reforma legítima debe abordar la ineficiencia, explicar su propósito y crear supervisión. Si el cambio ha de durar, necesita financiación sostenible y confianza pública." }),
    u("u45", "Memory and Identity", "Explore how memory, narrative, and experience shape identity.", [
      w("identity", "identidad", "noun", "/aɪˈdentəti/", "the qualities and experiences that make a person or group distinct", "Language is part of cultural identity.", "El idioma forma parte de la identidad cultural.", ["selfhood", "character"], ["anonymity"], ["cultural identity", "sense of identity"], ["identify, identity, identifiable"], ["culture", "psychology"], "identity"),
      w("memory", "memoria", "noun", "/ˈmeməri/", "the ability to store and recall past experiences", "Memory is not always reliable.", "La memoria no siempre es fiable.", ["recollection", "remembrance"], ["forgetting"], ["collective memory", "memory of an event"], ["memorize, memory, memorable"], ["psychology", "history"], "mind"),
      w("narrative", "relato", "noun", "/ˈnerətɪv/", "a spoken or written account of connected events", "The memoir offers a personal narrative.", "Las memorias ofrecen un relato personal.", ["story", "account"], ["silence"], ["personal narrative", "dominant narrative"], ["narrate, narrative, narrator"], ["literature", "identity"], "language"),
      w("belonging", "pertenencia", "noun", "/bɪˈlɔːŋɪŋ/", "the feeling of being accepted as part of a group", "Community can provide a sense of belonging.", "La comunidad puede proporcionar un sentido de pertenencia.", ["inclusion", "connection"], ["isolation"], ["sense of belonging", "create belonging"], ["belong, belonging"], ["society", "emotion"], "relationships"),
      w("reconstruct", "reconstruir", "verb", "/ˌriːkənˈstrʌkt/", "to form an idea of something from evidence or memories", "Historians reconstruct the past from documents.", "Los historiadores reconstruyen el pasado a partir de documentos.", ["rebuild", "recreate"], ["destroy"], ["reconstruct a memory", "reconstruct events"], ["construct, reconstruct, reconstruction"], ["history", "research"], "thinking action"),
      w("recall", "recordar", "verb", "/rɪˈkɔːl/", "to remember something from the past", "She could not recall the exact date.", "No podía recordar la fecha exacta.", ["remember", "retrieve"], ["forget"], ["recall an event", "recall clearly"], ["recall, recallable"], ["memory", "communication"], "thinking action"),
      w("subjective", "subjetivo", "adjective", "/səbˈdʒektɪv/", "based on personal feelings rather than external facts", "Memory is necessarily subjective.", "La memoria es necesariamente subjetiva.", ["personal", "interpretive"], ["objective"], ["subjective experience", "subjective account"], ["subject, subjective, subjectivity"], ["psychology", "philosophy"], "reasoning"),
      w("lasting", "duradero", "adjective", "/ˈlæstɪŋ/", "continuing for a long time", "The experience had a lasting effect.", "La experiencia tuvo un efecto duradero.", ["permanent", "enduring"], ["temporary"], ["lasting memory", "lasting impact"], ["last, lasting"], ["memory", "time"], "time"),
    ], [{ phrase: "Memory helps shape personal identity.", translation: "La memoria ayuda a formar la identidad personal." }, { phrase: "The narrative is partly subjective.", translation: "El relato es parcialmente subjetivo." }, { phrase: "The experience had a lasting impact.", translation: "La experiencia tuvo un impacto duradero." }, { phrase: "Community creates a sense of belonging.", translation: "La comunidad crea un sentido de pertenencia." }], [{ speaker: "A", text: "Can memory be completely reliable?", translation: "¿Puede la memoria ser completamente fiable?" }, { speaker: "B", text: "No. People reconstruct events from a subjective perspective.", translation: "No. Las personas reconstruyen los acontecimientos desde una perspectiva subjetiva." }, { speaker: "A", text: "Does that affect identity?", translation: "¿Afecta eso a la identidad?" }, { speaker: "B", text: "Yes, especially when a shared narrative creates belonging.", translation: "Sí, especialmente cuando un relato compartido crea pertenencia." }], { title: "Remembering Who We Are", text: "Identity is shaped by memory, narrative, and relationships. Personal recollections are subjective, yet they can have a lasting effect. Communities also reconstruct shared stories that give people a sense of belonging.", translation: "La identidad se forma mediante la memoria, el relato y las relaciones. Los recuerdos personales son subjetivos, pero pueden tener un efecto duradero. Las comunidades también reconstruyen historias compartidas que dan a las personas un sentido de pertenencia." }),
  ],
  C2: [
    u("u44", "Interpretive Frameworks", "Analyse how concepts and frameworks shape interpretation.", [
      w("ontology", "ontología", "noun", "/ɑːnˈtɑːlədʒi/", "the study of being and what exists", "Ontology asks what kinds of entities exist.", "La ontología pregunta qué tipos de entidades existen.", ["theory of being", "metaphysics"], [], ["social ontology", "ontological question"], ["ontological, ontology"], ["philosophy", "knowledge"], "philosophy"),
      w("framework", "marco conceptual", "noun", "/ˈfreɪmwɜːrk/", "a structure used to organise thought or analysis", "The framework changes how the text is read.", "El marco cambia cómo se lee el texto.", ["structure", "model"], ["disorder"], ["theoretical framework", "analytical framework"], ["frame, framework"], ["philosophy", "analysis"], "reasoning"),
      w("premise", "premisa", "noun", "/ˈpremɪs/", "a statement used as the basis for an argument", "The conclusion does not follow from the premise.", "La conclusión no se desprende de la premisa.", ["assumption", "proposition"], ["conclusion"], ["major premise", "false premise"], ["premise, premised"], ["logic", "argument"], "reasoning"),
      w("interpretation", "interpretación", "noun", "/ɪnˌtɜːrprəˈteɪʃən/", "an explanation of the meaning of something", "The interpretation remains controversial.", "La interpretación sigue siendo controvertida.", ["reading", "analysis"], ["literalism"], ["textual interpretation", "alternative interpretation"], ["interpret, interpretation, interpretive"], ["language", "philosophy"], "meaning"),
      w("presupposition", "presuposición", "noun", "/ˌpriːsʌpəˈzɪʃən/", "an idea accepted before an argument is examined", "The theory contains a hidden presupposition.", "La teoría contiene una presuposición oculta.", ["assumption", "prior belief"], ["question"], ["hidden presupposition", "shared presupposition"], ["suppose, presuppose, presupposition"], ["language", "reasoning"], "reasoning"),
      w("problematize", "problematizar", "verb", "/ˈprɑːbləmətaɪz/", "to treat an idea as open to critical examination", "The essay problematizes the idea of progress.", "El ensayo problematiza la idea de progreso.", ["question", "challenge"], ["simplify"], ["problematize an assumption", "critically problematize"], ["problem, problematic, problematize"], ["philosophy", "analysis"], "thinking action"),
      w("synthesize", "sintetizar", "verb", "/ˈsɪnθəsaɪz/", "to combine ideas into a coherent whole", "The conclusion synthesizes several arguments.", "La conclusión sintetiza varios argumentos.", ["combine", "integrate"], ["separate"], ["synthesize evidence", "synthesize ideas"], ["synthesis, synthesize, synthetic"], ["research", "writing"], "thinking action"),
      w("interpretive", "interpretativo", "adjective", "/ɪnˈtɜːrprətɪv/", "relating to the explanation of meaning", "The study adopts an interpretive approach.", "El estudio adopta un enfoque interpretativo.", ["analytical", "explanatory"], ["literal"], ["interpretive framework", "interpretive method"], ["interpret, interpretation, interpretive"], ["philosophy", "research"], "quality"),
    ], [{ phrase: "The premise contains a hidden presupposition.", translation: "La premisa contiene una presuposición oculta." }, { phrase: "The framework shapes the interpretation.", translation: "El marco determina la interpretación." }, { phrase: "The essay problematizes a familiar assumption.", translation: "El ensayo problematiza una suposición conocida." }, { phrase: "The conclusion synthesizes the main arguments.", translation: "La conclusión sintetiza los argumentos principales." }], [{ speaker: "A", text: "What framework does the author use?", translation: "¿Qué marco utiliza el autor?" }, { speaker: "B", text: "An interpretive framework based on social ontology.", translation: "Un marco interpretativo basado en la ontología social." }, { speaker: "A", text: "Does the essay accept its premise?", translation: "¿Acepta el ensayo su premisa?" }, { speaker: "B", text: "No. It problematizes the presupposition and synthesizes alternatives.", translation: "No. Problematiza la presuposición y sintetiza alternativas." }], { title: "Reading Through a Framework", text: "Interpretation is never entirely separate from its framework. A premise may carry a hidden presupposition, while an interpretive approach can problematize what appears obvious. Careful analysis synthesizes competing readings rather than pretending that one perspective is neutral.", translation: "La interpretación nunca está completamente separada de su marco. Una premisa puede contener una presuposición oculta, mientras que un enfoque interpretativo puede problematizar lo que parece obvio. Un análisis cuidadoso sintetiza lecturas competidoras en lugar de fingir que una perspectiva es neutral." }),
    u("u45", "Rhetoric and Persuasion", "Evaluate how language, framing, and evidence influence an audience.", [
      w("persuasion", "persuasión", "noun", "/pərˈsweɪʒən/", "the act of convincing someone to think or act differently", "Persuasion depends on trust and evidence.", "La persuasión depende de la confianza y la evidencia.", ["influence", "convincing"], ["deterrence"], ["power of persuasion", "rhetorical persuasion"], ["persuade, persuasion, persuasive"], ["rhetoric", "communication"], "rhetoric"),
      w("framing", "encuadre", "noun", "/ˈfreɪmɪŋ/", "the way an issue is presented to shape how it is understood", "The framing of the debate affected public opinion.", "El encuadre del debate afectó a la opinión pública.", ["presentation", "context"], ["neutrality"], ["political framing", "framing effect"], ["frame, framing, framework"], ["media", "politics"], "rhetoric"),
      w("audience", "audiencia", "noun", "/ˈɔːdiəns/", "the people who hear, read, or watch a communication", "The speaker adapted the argument to the audience.", "El orador adaptó el argumento a la audiencia.", ["public", "listeners"], ["speaker"], ["target audience", "address an audience"], ["audio, audience"], ["rhetoric", "communication"], "communication"),
      w("fallacy", "falacia", "noun", "/ˈfæləsi/", "a mistaken pattern of reasoning that appears convincing", "The argument contains a logical fallacy.", "El argumento contiene una falacia lógica.", ["error", "false reasoning"], ["valid argument"], ["logical fallacy", "commit a fallacy"], ["fallacy, fallacious"], ["logic", "rhetoric"], "reasoning"),
      w("emphasize", "enfatizar", "verb", "/ˈemfəsaɪz/", "to give special importance to an idea or fact", "The report emphasizes long-term effects.", "El informe enfatiza los efectos a largo plazo.", ["stress", "highlight"], ["understate"], ["emphasize a point", "strongly emphasize"], ["emphasis, emphasize, emphatic"], ["writing", "rhetoric"], "communication action"),
      w("appeal", "apelar", "verb", "/əˈpiːl/", "to attract or make a serious request to someone", "The argument appeals to shared values.", "El argumento apela a valores compartidos.", ["attract", "invoke"], ["repel"], ["appeal to reason", "appeal to emotion"], ["appeal, appealing"], ["rhetoric", "emotion"], "rhetoric action"),
      w("compelling", "convincente", "adjective", "/kəmˈpelɪŋ/", "so persuasive that it demands attention or belief", "She presented a compelling case.", "Presentó un caso convincente.", ["convincing", "powerful"], ["unconvincing"], ["compelling evidence", "compelling argument"], ["compel, compelling"], ["rhetoric", "evidence"], "quality"),
      w("ambivalent", "ambivalente", "adjective", "/æmˈbɪvələnt/", "having mixed or uncertain feelings about something", "The public remained ambivalent about the proposal.", "El público siguió ambivalente ante la propuesta.", ["uncertain", "conflicted"], ["decisive"], ["ambivalent attitude", "remain ambivalent"], ["ambivalence, ambivalent"], ["society", "emotion"], "attitude"),
    ], [{ phrase: "The framing influences the audience.", translation: "El encuadre influye en la audiencia." }, { phrase: "The speaker appeals to shared values.", translation: "El orador apela a valores compartidos." }, { phrase: "The evidence is compelling.", translation: "La evidencia es convincente." }, { phrase: "Avoid relying on a logical fallacy.", translation: "Evita basarte en una falacia lógica." }], [{ speaker: "A", text: "Why was the speech so persuasive?", translation: "¿Por qué fue tan persuasivo el discurso?" }, { speaker: "B", text: "Its framing appealed to the audience's shared values.", translation: "Su encuadre apeló a los valores compartidos de la audiencia." }, { speaker: "A", text: "Was the evidence compelling?", translation: "¿Fue convincente la evidencia?" }, { speaker: "B", text: "Partly, although one section contained a fallacy.", translation: "En parte, aunque una sección contenía una falacia." }], { title: "How Arguments Move People", text: "Persuasion depends on more than facts. Framing determines what an audience notices, while emphasis and emotional appeal influence interpretation. A compelling argument can still contain a fallacy, so critical listeners examine both evidence and technique.", translation: "La persuasión depende de algo más que los hechos. El encuadre determina lo que observa una audiencia, mientras que el énfasis y la apelación emocional influyen en la interpretación. Un argumento convincente aún puede contener una falacia, por lo que los oyentes críticos examinan la evidencia y la técnica." }),
  ],
};
