// Professional English enrichment unit u58 for every CEFR level.
// English-only continuation; Finnish curriculum files are intentionally untouched.
import type { ReadingText, VocabularyItem } from "./learn-data";

type PhraseSpec = { phrase: string; translation: string };
type LineSpec = { speaker: string; text: string; translation: string };
type WordSpec = {
  word: string;
  translation: string;
  pos: string;
  ipa: string;
  definition: string;
  example: string;
  exampleTranslation: string;
  synonyms: string[];
  antonyms: string[];
  collocations: string[];
  wordFamily: string[];
  tags: string[];
  category: string;
};
type UnitSeed = {
  id: string;
  title: string;
  description: string;
  words: VocabularyItem[];
  phrases: PhraseSpec[];
  dialogue: LineSpec[];
  reading: ReadingText & { title: string };
};

const w = (spec: WordSpec): VocabularyItem => ({ ...spec });
const u = (title: string, description: string, words: VocabularyItem[], phrases: PhraseSpec[], dialogue: LineSpec[], reading: ReadingText & { title: string }): UnitSeed => ({ id: "u58", title, description, words, phrases, dialogue, reading });

export const ADDITIONAL_EN_PART19_UNITS: Record<string, UnitSeed[]> = {
  A0: [
    u("Home Routines", "Name familiar objects and describe simple actions at home.", [
      w({ word: "pillow", translation: "almohada", pos: "noun", ipa: "/ˈpɪloʊ/", definition: "a soft object used to support your head in bed", example: "My pillow is on the bed.", exampleTranslation: "Mi almohada está en la cama.", synonyms: ["cushion"], antonyms: [], collocations: ["soft pillow", "sleep on a pillow"], wordFamily: ["pillow"], tags: ["home", "sleep"], category: "object" }),
      w({ word: "towel", translation: "toalla", pos: "noun", ipa: "/ˈtaʊəl/", definition: "a piece of cloth used for drying", example: "The clean towel is in the bathroom.", exampleTranslation: "La toalla limpia está en el baño.", synonyms: ["bath towel"], antonyms: [], collocations: ["dry with a towel", "clean towel"], wordFamily: ["towel"], tags: ["home", "objects"], category: "object" }),
      w({ word: "soap", translation: "jabón", pos: "noun", ipa: "/soʊp/", definition: "a substance used with water for washing", example: "Please use the soap.", exampleTranslation: "Usa el jabón, por favor.", synonyms: ["cleanser"], antonyms: [], collocations: ["bar of soap", "wash with soap"], wordFamily: ["soap", "soapy"], tags: ["home", "hygiene"], category: "object" }),
      w({ word: "brush", translation: "cepillar", pos: "verb", ipa: "/brʌʃ/", definition: "to clean or arrange something with a brush", example: "I brush my teeth every morning.", exampleTranslation: "Me cepillo los dientes cada mañana.", synonyms: ["clean", "stroke"], antonyms: [], collocations: ["brush your teeth", "brush your hair"], wordFamily: ["brush", "brushing"], tags: ["routine", "hygiene"], category: "action" }),
      w({ word: "dress", translation: "vestirse", pos: "verb", ipa: "/dres/", definition: "to put clothes on yourself", example: "I dress before breakfast.", exampleTranslation: "Me visto antes del desayuno.", synonyms: ["put on clothes"], antonyms: ["undress"], collocations: ["dress quickly", "get dressed"], wordFamily: ["dress", "dressed", "dressing"], tags: ["routine", "clothes"], category: "action" }),
      w({ word: "fold", translation: "doblar", pos: "verb", ipa: "/foʊld/", definition: "to bend cloth or paper over itself", example: "We fold the clean clothes.", exampleTranslation: "Doblamos la ropa limpia.", synonyms: ["bend"], antonyms: ["unfold"], collocations: ["fold clothes", "fold a towel"], wordFamily: ["fold", "folded"], tags: ["home", "routine"], category: "action" }),
      w({ word: "tidy", translation: "ordenado", pos: "adjective", ipa: "/ˈtaɪdi/", definition: "clean and arranged in the right place", example: "Her room is tidy today.", exampleTranslation: "Su habitación está ordenada hoy.", synonyms: ["neat", "orderly"], antonyms: ["messy"], collocations: ["tidy room", "keep tidy"], wordFamily: ["tidy", "tidily"], tags: ["home", "quality"], category: "quality" }),
      w({ word: "bedroom", translation: "dormitorio", pos: "noun", ipa: "/ˈbedruːm/", definition: "a room where people sleep", example: "The bedroom has one window.", exampleTranslation: "El dormitorio tiene una ventana.", synonyms: ["sleeping room"], antonyms: [], collocations: ["small bedroom", "clean the bedroom"], wordFamily: ["bed", "bedroom"], tags: ["home", "rooms"], category: "place" }),
    ], [
      { phrase: "It is time to get dressed.", translation: "Es hora de vestirse." }, { phrase: "Where is my towel?", translation: "¿Dónde está mi toalla?" }, { phrase: "Please tidy your room.", translation: "Ordena tu habitación, por favor." }, { phrase: "I am ready for breakfast.", translation: "Estoy listo para desayunar." },
    ], [
      { speaker: "A", text: "Where is my towel?", translation: "¿Dónde está mi toalla?" }, { speaker: "B", text: "It is in the bathroom.", translation: "Está en el baño." }, { speaker: "A", text: "I will brush my teeth and dress.", translation: "Me cepillaré los dientes y me vestiré." }, { speaker: "B", text: "Good. Then tidy your bedroom.", translation: "Bien. Luego ordena tu dormitorio." },
    ], { title: "A Tidy Morning", text: "Leo wakes up in his bedroom. He folds his blanket, uses soap and a towel, and brushes his teeth. After he gets dressed, he tidies the room before breakfast.", translation: "Leo se despierta en su dormitorio. Dobla su manta, usa jabón y una toalla y se cepilla los dientes. Después de vestirse, ordena la habitación antes del desayuno." }),
  ],
  A1: [
    u("Shopping for Clothes", "Ask about prices, sizes, payment, and returning an unsuitable item.", [
      w({ word: "receipt", translation: "recibo", pos: "noun", ipa: "/rɪˈsiːt/", definition: "a paper or message showing what you bought and paid for", example: "Keep the receipt in your bag.", exampleTranslation: "Guarda el recibo en tu bolso.", synonyms: ["proof of purchase"], antonyms: [], collocations: ["keep a receipt", "show the receipt"], wordFamily: ["receive", "receipt"], tags: ["shopping", "money"], category: "document" }),
      w({ word: "cashier", translation: "cajero", pos: "noun", ipa: "/kæˈʃɪr/", definition: "a person who takes payment in a shop", example: "The cashier gave me my change.", exampleTranslation: "El cajero me dio el cambio.", synonyms: ["checkout assistant"], antonyms: [], collocations: ["ask the cashier", "friendly cashier"], wordFamily: ["cash", "cashier"], tags: ["shopping", "people"], category: "person" }),
      w({ word: "barcode", translation: "código de barras", pos: "noun", ipa: "/ˈbɑːrkoʊd/", definition: "a pattern of lines that identifies a product", example: "The cashier scanned the barcode.", exampleTranslation: "El cajero escaneó el código de barras.", synonyms: ["product code"], antonyms: [], collocations: ["scan a barcode", "barcode scanner"], wordFamily: ["bar", "barcode"], tags: ["shopping", "technology"], category: "object" }),
      w({ word: "refund", translation: "reembolso", pos: "noun", ipa: "/ˈriːfʌnd/", definition: "money returned when a product is taken back", example: "The shop gave me a full refund.", exampleTranslation: "La tienda me dio un reembolso completo.", synonyms: ["repayment", "reimbursement"], antonyms: ["payment"], collocations: ["get a refund", "full refund"], wordFamily: ["refund", "refundable"], tags: ["shopping", "money"], category: "transaction" }),
      w({ word: "discount", translation: "descuento", pos: "noun", ipa: "/ˈdɪskaʊnt/", definition: "a reduction in the usual price", example: "Students receive a small discount.", exampleTranslation: "Los estudiantes reciben un pequeño descuento.", synonyms: ["reduction", "saving"], antonyms: ["increase"], collocations: ["offer a discount", "discount price"], wordFamily: ["discount", "discounted"], tags: ["shopping", "money"], category: "cost" }),
      w({ word: "aisle", translation: "pasillo", pos: "noun", ipa: "/aɪl/", definition: "a passage between rows of shelves in a shop", example: "The bread is in the next aisle.", exampleTranslation: "El pan está en el pasillo siguiente.", synonyms: ["passage"], antonyms: [], collocations: ["shop aisle", "walk down an aisle"], wordFamily: ["aisle"], tags: ["shopping", "places"], category: "place" }),
      w({ word: "bargain", translation: "ganga", pos: "noun", ipa: "/ˈbɑːrɡən/", definition: "something bought for less than its usual price", example: "This jacket was a real bargain.", exampleTranslation: "Esta chaqueta fue una verdadera ganga.", synonyms: ["good deal", "deal"], antonyms: ["rip-off"], collocations: ["find a bargain", "real bargain"], wordFamily: ["bargain", "bargain-hunter"], tags: ["shopping", "money"], category: "value" }),
      w({ word: "checkout", translation: "caja", pos: "noun", ipa: "/ˈtʃekaʊt/", definition: "the place where you pay for things in a shop", example: "There is a long line at the checkout.", exampleTranslation: "Hay una cola larga en la caja.", synonyms: ["cash desk", "till"], antonyms: [], collocations: ["online checkout", "wait at the checkout"], wordFamily: ["check", "checkout"], tags: ["shopping", "places"], category: "place" }),
    ], [
      { phrase: "Could I try this on?", translation: "¿Podría probarme esto?" }, { phrase: "Do you have it in a larger size?", translation: "¿Lo tienen en una talla más grande?" }, { phrase: "Can I pay by card?", translation: "¿Puedo pagar con tarjeta?" }, { phrase: "I would like a refund, please.", translation: "Quisiera un reembolso, por favor." },
    ], [
      { speaker: "A", text: "Could I try this jacket on?", translation: "¿Podría probarme esta chaqueta?" }, { speaker: "B", text: "Of course. The fitting room is by the next aisle.", translation: "Claro. El probador está junto al pasillo siguiente." }, { speaker: "A", text: "It is too small. Do you have a larger size?", translation: "Es demasiado pequeña. ¿Tiene una talla más grande?" }, { speaker: "B", text: "Yes, and there is a student discount at the checkout.", translation: "Sí, y hay un descuento para estudiantes en la caja." },
    ], { title: "A Careful Purchase", text: "Mina finds a jacket at a good price, but the first one is too small. She checks the barcode and asks for another size. At the checkout, she uses a discount and keeps the receipt in case she needs a refund.", translation: "Mina encuentra una chaqueta a buen precio, pero la primera es demasiado pequeña. Comprueba el código de barras y pide otra talla. En la caja usa un descuento y guarda el recibo por si necesita un reembolso." }),
  ],
  A2: [
    u("At the Clinic", "Describe symptoms, ask about treatment, and follow simple medical advice.", [
      w({ word: "symptom", translation: "síntoma", pos: "noun", ipa: "/ˈsɪmptəm/", definition: "a change in the body that shows an illness", example: "A cough is one of her symptoms.", exampleTranslation: "La tos es uno de sus síntomas.", synonyms: ["sign", "indication"], antonyms: [], collocations: ["common symptom", "describe a symptom"], wordFamily: ["symptom", "symptomatic"], tags: ["health", "body"], category: "health" }),
      w({ word: "prescription", translation: "receta médica", pos: "noun", ipa: "/prɪˈskrɪpʃən/", definition: "written instructions from a doctor for medicine", example: "The doctor wrote a prescription.", exampleTranslation: "El médico escribió una receta.", synonyms: ["doctor's order"], antonyms: [], collocations: ["write a prescription", "prescription medicine"], wordFamily: ["prescribe", "prescription"], tags: ["health", "medicine"], category: "document" }),
      w({ word: "dosage", translation: "dosis", pos: "noun", ipa: "/ˈdoʊsɪdʒ/", definition: "the amount of medicine to take at one time", example: "Read the dosage carefully.", exampleTranslation: "Lee la dosis con cuidado.", synonyms: ["dose", "amount"], antonyms: [], collocations: ["recommended dosage", "correct dosage"], wordFamily: ["dose", "dosage"], tags: ["health", "medicine"], category: "quantity" }),
      w({ word: "dizzy", translation: "mareado", pos: "adjective", ipa: "/ˈdɪzi/", definition: "feeling as if everything is spinning", example: "I felt dizzy after standing up.", exampleTranslation: "Me sentí mareado después de levantarme.", synonyms: ["light-headed", "unsteady"], antonyms: ["steady"], collocations: ["feel dizzy", "dizzy spell"], wordFamily: ["dizzy", "dizziness"], tags: ["health", "feelings"], category: "condition" }),
      w({ word: "clinic", translation: "clínica", pos: "noun", ipa: "/ˈklɪnɪk/", definition: "a place where people receive medical care", example: "The clinic opens at eight.", exampleTranslation: "La clínica abre a las ocho.", synonyms: ["health centre", "practice"], antonyms: [], collocations: ["local clinic", "visit a clinic"], wordFamily: ["clinical", "clinic"], tags: ["health", "places"], category: "place" }),
      w({ word: "treatment", translation: "tratamiento", pos: "noun", ipa: "/ˈtriːtmənt/", definition: "medical care given for an illness or injury", example: "The treatment lasted two weeks.", exampleTranslation: "El tratamiento duró dos semanas.", synonyms: ["therapy", "care"], antonyms: [], collocations: ["medical treatment", "receive treatment"], wordFamily: ["treat", "treatment"], tags: ["health", "medicine"], category: "care" }),
      w({ word: "recover", translation: "recuperarse", pos: "verb", ipa: "/rɪˈkʌvər/", definition: "to become well again after an illness or injury", example: "She recovered quickly from the flu.", exampleTranslation: "Se recuperó rápidamente de la gripe.", synonyms: ["get better", "heal"], antonyms: ["worsen"], collocations: ["recover fully", "recover from an illness"], wordFamily: ["recover", "recovery"], tags: ["health", "time"], category: "change" }),
      w({ word: "swollen", translation: "hinchado", pos: "adjective", ipa: "/ˈswoʊlən/", definition: "larger than normal because of an injury or illness", example: "His ankle is swollen.", exampleTranslation: "Tiene el tobillo hinchado.", synonyms: ["inflamed", "enlarged"], antonyms: [], collocations: ["swollen ankle", "swollen area"], wordFamily: ["swell", "swollen", "swelling"], tags: ["health", "body"], category: "condition" }),
    ], [
      { phrase: "How long have you had this symptom?", translation: "¿Cuánto tiempo has tenido este síntoma?" }, { phrase: "Take the medicine after food.", translation: "Toma el medicamento después de comer." }, { phrase: "Please follow the dosage instructions.", translation: "Sigue las instrucciones de la dosis, por favor." }, { phrase: "I hope you recover soon.", translation: "Espero que te recuperes pronto." },
    ], [
      { speaker: "A", text: "I feel dizzy and my ankle is swollen.", translation: "Me siento mareado y tengo el tobillo hinchado." }, { speaker: "B", text: "The clinician will examine you now.", translation: "El médico te examinará ahora." }, { speaker: "A", text: "Will I need a prescription?", translation: "¿Necesitaré una receta?" }, { speaker: "B", text: "Perhaps. Follow the dosage and you should recover soon.", translation: "Quizás. Sigue la dosis y deberías recuperarte pronto." },
    ], { title: "A Visit to the Clinic", text: "After a fall, Omar visits a local clinic because his ankle is swollen. He explains every symptom to the clinician and receives a treatment plan. He reads the prescription carefully and follows the dosage while he recovers.", translation: "Después de una caída, Omar visita una clínica local porque tiene el tobillo hinchado. Explica cada síntoma al médico y recibe un plan de tratamiento. Lee atentamente la receta y sigue la dosis mientras se recupera." }),
  ],
  B1: [
    u("Effective Teamwork", "Discuss responsibilities, feedback, deadlines, and constructive collaboration.", [
      w({ word: "collaborate", translation: "colaborar", pos: "verb", ipa: "/kəˈlæbəreɪt/", definition: "to work together with other people on a shared task", example: "The designers collaborate with the engineers.", exampleTranslation: "Los diseñadores colaboran con los ingenieros.", synonyms: ["cooperate", "work together"], antonyms: ["compete"], collocations: ["collaborate closely", "collaborate on a project"], wordFamily: ["collaborate", "collaboration", "collaborative"], tags: ["work", "communication"], category: "action" }),
      w({ word: "delegate", translation: "delegar", pos: "verb", ipa: "/ˈdelɪɡeɪt/", definition: "to give a task or responsibility to another person", example: "A good manager knows when to delegate.", exampleTranslation: "Un buen gerente sabe cuándo delegar.", synonyms: ["assign", "entrust"], antonyms: ["retain"], collocations: ["delegate a task", "delegate responsibility"], wordFamily: ["delegate", "delegation"], tags: ["work", "leadership"], category: "management" }),
      w({ word: "feedback", translation: "comentarios", pos: "noun", ipa: "/ˈfiːdbæk/", definition: "advice or information about how well someone is doing", example: "Constructive feedback improved the presentation.", exampleTranslation: "Los comentarios constructivos mejoraron la presentación.", synonyms: ["response", "comment"], antonyms: [], collocations: ["constructive feedback", "give feedback"], wordFamily: ["feed", "feedback"], tags: ["work", "communication"], category: "communication" }),
      w({ word: "deadline", translation: "fecha límite", pos: "noun", ipa: "/ˈdedlaɪn/", definition: "the latest time by which something must be finished", example: "We must meet the deadline on Friday.", exampleTranslation: "Debemos cumplir la fecha límite el viernes.", synonyms: ["due date", "time limit"], antonyms: [], collocations: ["meet a deadline", "tight deadline"], wordFamily: ["dead", "deadline"], tags: ["work", "time"], category: "schedule" }),
      w({ word: "coordinate", translation: "coordinar", pos: "verb", ipa: "/koʊˈɔːrdɪneɪt/", definition: "to organise people or activities so they work well together", example: "I coordinate the weekly team meeting.", exampleTranslation: "Coordino la reunión semanal del equipo.", synonyms: ["organise", "align"], antonyms: ["disorganise"], collocations: ["coordinate efforts", "coordinate a schedule"], wordFamily: ["coordinate", "coordination", "coordinator"], tags: ["work", "planning"], category: "action" }),
      w({ word: "contribute", translation: "contribuir", pos: "verb", ipa: "/kənˈtrɪbjuːt/", definition: "to give time, ideas, or effort to a shared activity", example: "Everyone contributed an idea.", exampleTranslation: "Todos contribuyeron con una idea.", synonyms: ["add", "participate"], antonyms: ["withhold"], collocations: ["contribute to a project", "valuable contribution"], wordFamily: ["contribute", "contribution", "contributor"], tags: ["work", "participation"], category: "action" }),
      w({ word: "reliable", translation: "fiable", pos: "adjective", ipa: "/rɪˈlaɪəbəl/", definition: "able to be trusted to do what is expected", example: "Our reliable colleague never misses a deadline.", exampleTranslation: "Nuestro colega fiable nunca incumple una fecha límite.", synonyms: ["dependable", "trustworthy"], antonyms: ["unreliable"], collocations: ["reliable colleague", "reliable information"], wordFamily: ["rely", "reliable", "reliability"], tags: ["work", "quality"], category: "character" }),
      w({ word: "compromise", translation: "compromiso", pos: "noun", ipa: "/ˈkɑːmprəmaɪz/", definition: "an agreement reached when each side accepts less than it wanted", example: "The team reached a compromise about the schedule.", exampleTranslation: "El equipo alcanzó un compromiso sobre el horario.", synonyms: ["agreement", "middle ground"], antonyms: ["deadlock"], collocations: ["reach a compromise", "mutual compromise"], wordFamily: ["compromise"], tags: ["work", "conflict"], category: "agreement" }),
    ], [
      { phrase: "Who is responsible for this task?", translation: "¿Quién es responsable de esta tarea?" }, { phrase: "Could you give me some feedback?", translation: "¿Podrías darme algunos comentarios?" }, { phrase: "Let us agree on a realistic deadline.", translation: "Acordemos una fecha límite realista." }, { phrase: "Everyone should have a chance to contribute.", translation: "Todos deberían tener la oportunidad de contribuir." },
    ], [
      { speaker: "A", text: "The deadline is close. How should we divide the work?", translation: "La fecha límite se acerca. ¿Cómo debemos dividir el trabajo?" }, { speaker: "B", text: "I can coordinate the research and delegate the design tasks.", translation: "Puedo coordinar la investigación y delegar las tareas de diseño." }, { speaker: "A", text: "I will contribute the first draft and ask for feedback.", translation: "Contribuiré con el primer borrador y pediré comentarios." }, { speaker: "B", text: "Good. A compromise will help us finish on time.", translation: "Bien. Un compromiso nos ayudará a terminar a tiempo." },
    ], { title: "One Team, One Deadline", text: "A project team is under pressure to meet a demanding deadline. Instead of blaming one another, the members coordinate their work, delegate tasks fairly, and contribute different skills. Regular feedback helps them reach a compromise and deliver a reliable result.", translation: "Un equipo de proyecto está bajo presión para cumplir una fecha límite exigente. En lugar de culparse, los miembros coordinan su trabajo, delegan las tareas de manera justa y contribuyen con distintas habilidades. Los comentarios frecuentes les ayudan a alcanzar un compromiso y entregar un resultado fiable." }),
  ],
  B2: [
    u("Planning Better Cities", "Evaluate urban growth, transport, housing, infrastructure, and public space.", [
      w({ word: "zoning", translation: "zonificación", pos: "noun", ipa: "/ˈzoʊnɪŋ/", definition: "the system of controlling what can be built in different areas", example: "New zoning could protect the historic centre.", exampleTranslation: "Una nueva zonificación podría proteger el centro histórico.", synonyms: ["land-use planning"], antonyms: [], collocations: ["zoning rules", "zoning policy"], wordFamily: ["zone", "zoning"], tags: ["urban", "government"], category: "planning" }),
      w({ word: "pedestrian", translation: "peatón", pos: "noun", ipa: "/pəˈdestriən/", definition: "a person who is walking rather than travelling in a vehicle", example: "The new crossing is safer for pedestrians.", exampleTranslation: "El nuevo paso es más seguro para los peatones.", synonyms: ["walker"], antonyms: ["driver"], collocations: ["pedestrian crossing", "pedestrian zone"], wordFamily: ["pedestrian", "pedestrianise"], tags: ["urban", "transport"], category: "person" }),
      w({ word: "density", translation: "densidad", pos: "noun", ipa: "/ˈdensəti/", definition: "the amount of people or things in a particular area", example: "High population density can increase housing costs.", exampleTranslation: "Una alta densidad de población puede aumentar el coste de la vivienda.", synonyms: ["concentration", "compactness"], antonyms: ["sparsity"], collocations: ["population density", "urban density"], wordFamily: ["dense", "density"], tags: ["urban", "society"], category: "measurement" }),
      w({ word: "infrastructure", translation: "infraestructura", pos: "noun", ipa: "/ˈɪnfrəstrʌktʃər/", definition: "the basic systems and facilities a society needs to function", example: "The city needs investment in public infrastructure.", exampleTranslation: "La ciudad necesita inversión en infraestructura pública.", synonyms: ["public works", "framework"], antonyms: [], collocations: ["transport infrastructure", "digital infrastructure"], wordFamily: ["structure", "infrastructure"], tags: ["urban", "government"], category: "systems" }),
      w({ word: "affordable", translation: "asequible", pos: "adjective", ipa: "/əˈfɔːrdəbəl/", definition: "cheap enough for ordinary people to pay for", example: "The plan must include affordable housing.", exampleTranslation: "El plan debe incluir vivienda asequible.", synonyms: ["reasonably priced", "accessible"], antonyms: ["expensive", "unaffordable"], collocations: ["affordable housing", "affordable transport"], wordFamily: ["afford", "affordable", "affordability"], tags: ["urban", "economy"], category: "cost" }),
      w({ word: "commute", translation: "desplazarse al trabajo", pos: "verb", ipa: "/kəˈmjuːt/", definition: "to travel regularly between home and work or study", example: "Many residents commute by train.", exampleTranslation: "Muchos residentes se desplazan en tren.", synonyms: ["travel to work"], antonyms: [], collocations: ["daily commute", "commute by train"], wordFamily: ["commute", "commuter"], tags: ["urban", "transport"], category: "movement" }),
      w({ word: "district", translation: "distrito", pos: "noun", ipa: "/ˈdɪstrɪkt/", definition: "an area of a town or city with particular features", example: "The arts district attracts many visitors.", exampleTranslation: "El distrito artístico atrae a muchos visitantes.", synonyms: ["area", "neighbourhood"], antonyms: [], collocations: ["business district", "residential district"], wordFamily: ["district"], tags: ["urban", "places"], category: "place" }),
      w({ word: "renewal", translation: "renovación", pos: "noun", ipa: "/rɪˈnuːəl/", definition: "the process of improving an old area or building", example: "Urban renewal changed the waterfront.", exampleTranslation: "La renovación urbana cambió la zona del puerto.", synonyms: ["regeneration", "revitalisation"], antonyms: ["decline"], collocations: ["urban renewal", "renewal project"], wordFamily: ["renew", "renewal", "renewable"], tags: ["urban", "change"], category: "development" }),
    ], [
      { phrase: "The plan needs a stronger transport network.", translation: "El plan necesita una red de transporte más sólida." }, { phrase: "How will this affect local residents?", translation: "¿Cómo afectará esto a los residentes locales?" }, { phrase: "We should prioritise affordable housing.", translation: "Deberíamos priorizar la vivienda asequible." }, { phrase: "The proposal balances growth and quality of life.", translation: "La propuesta equilibra el crecimiento y la calidad de vida." },
    ], [
      { speaker: "A", text: "Should the new district have higher density?", translation: "¿Debería tener mayor densidad el nuevo distrito?" }, { speaker: "B", text: "Perhaps, but only with better infrastructure and affordable homes.", translation: "Quizás, pero solo con mejor infraestructura y viviendas asequibles." }, { speaker: "A", text: "Could a pedestrian zone reduce the daily commute?", translation: "¿Podría una zona peatonal reducir el desplazamiento diario?" }, { speaker: "B", text: "Yes, if the renewal plan also improves public transport.", translation: "Sí, si el plan de renovación también mejora el transporte público." },
    ], { title: "A More Liveable District", text: "A growing city is reviewing a renewal proposal for an old industrial district. Planners want more homes, but they also need to protect public space and control housing costs. The final design combines careful zoning, pedestrian routes, reliable infrastructure, and improved transport for commuters.", translation: "Una ciudad en crecimiento está revisando una propuesta de renovación para un antiguo distrito industrial. Los planificadores quieren más viviendas, pero también necesitan proteger el espacio público y controlar los costes de la vivienda. El diseño final combina una zonificación cuidadosa, rutas peatonales, infraestructura fiable y mejor transporte para quienes se desplazan." }),
  ],
  C1: [
    u("Research Integrity", "Evaluate evidence, transparency, reproducibility, and ethical responsibility in research.", [
      w({ word: "hypothesis", translation: "hipótesis", pos: "noun", ipa: "/haɪˈpɑːθəsɪs/", definition: "an idea or explanation that can be tested by research", example: "The experiment was designed to test the hypothesis.", exampleTranslation: "El experimento fue diseñado para comprobar la hipótesis.", synonyms: ["theory", "proposition"], antonyms: [], collocations: ["test a hypothesis", "research hypothesis"], wordFamily: ["hypothesize", "hypothesis", "hypothetical"], tags: ["research", "thinking"], category: "idea" }),
      w({ word: "replicate", translation: "replicar", pos: "verb", ipa: "/ˈreplɪkeɪt/", definition: "to repeat a study or result using the same method", example: "Another laboratory tried to replicate the findings.", exampleTranslation: "Otro laboratorio intentó replicar los resultados.", synonyms: ["repeat", "reproduce"], antonyms: [], collocations: ["replicate findings", "replicate a study"], wordFamily: ["replicate", "replication"], tags: ["research", "science"], category: "method" }),
      w({ word: "citation", translation: "cita bibliográfica", pos: "noun", ipa: "/saɪˈteɪʃən/", definition: "a reference to a source used in academic work", example: "Every borrowed idea needs a citation.", exampleTranslation: "Cada idea tomada necesita una cita bibliográfica.", synonyms: ["reference", "source note"], antonyms: [], collocations: ["academic citation", "citation style"], wordFamily: ["cite", "citation"], tags: ["research", "writing"], category: "source" }),
      w({ word: "plagiarism", translation: "plagio", pos: "noun", ipa: "/ˈpleɪdʒərɪzəm/", definition: "presenting another person's work or ideas as your own", example: "The university investigates plagiarism seriously.", exampleTranslation: "La universidad investiga seriamente el plagio.", synonyms: ["academic theft", "copying"], antonyms: ["originality"], collocations: ["detect plagiarism", "plagiarism policy"], wordFamily: ["plagiarise", "plagiarism"], tags: ["research", "ethics"], category: "misconduct" }),
      w({ word: "dataset", translation: "conjunto de datos", pos: "noun", ipa: "/ˈdeɪtəset/", definition: "a structured collection of information used for analysis", example: "The dataset contains responses from 2,000 participants.", exampleTranslation: "El conjunto de datos contiene respuestas de 2.000 participantes.", synonyms: ["data collection", "database"], antonyms: [], collocations: ["large dataset", "analyse a dataset"], wordFamily: ["data", "dataset"], tags: ["research", "technology"], category: "data" }),
      w({ word: "peer-review", translation: "revisión por pares", pos: "noun", ipa: "/ˈpɪr rɪˌvjuː/", definition: "an evaluation of research by other experts in the field", example: "The article is currently undergoing peer-review.", exampleTranslation: "El artículo está actualmente en revisión por pares.", synonyms: ["expert assessment"], antonyms: [], collocations: ["peer-review process", "peer-reviewed journal"], wordFamily: ["peer", "review", "peer-reviewed"], tags: ["research", "academic"], category: "evaluation" }),
      w({ word: "disclose", translation: "revelar", pos: "verb", ipa: "/dɪˈskloʊz/", definition: "to make important information known", example: "Researchers must disclose possible conflicts of interest.", exampleTranslation: "Los investigadores deben revelar posibles conflictos de interés.", synonyms: ["reveal", "declare"], antonyms: ["conceal"], collocations: ["disclose a conflict", "fully disclose"], wordFamily: ["close", "disclose", "disclosure"], tags: ["research", "ethics"], category: "communication" }),
      w({ word: "methodology", translation: "metodología", pos: "noun", ipa: "/ˌmeθəˈdɑːlədʒi/", definition: "the system of methods used in a particular study", example: "The paper explains its methodology in detail.", exampleTranslation: "El artículo explica su metodología en detalle.", synonyms: ["method", "procedure"], antonyms: [], collocations: ["research methodology", "sound methodology"], wordFamily: ["method", "methodological", "methodology"], tags: ["research", "academic"], category: "method" }),
    ], [
      { phrase: "What evidence supports the hypothesis?", translation: "¿Qué pruebas respaldan la hipótesis?" }, { phrase: "The findings should be independently replicated.", translation: "Los resultados deberían replicarse de forma independiente." }, { phrase: "Please provide a full citation.", translation: "Proporciona una cita bibliográfica completa, por favor." }, { phrase: "The authors disclose a potential conflict of interest.", translation: "Los autores revelan un posible conflicto de interés." },
    ], [
      { speaker: "A", text: "Can we trust the result without seeing the dataset?", translation: "¿Podemos confiar en el resultado sin ver el conjunto de datos?" }, { speaker: "B", text: "The methodology and full citations should be available.", translation: "La metodología y las citas bibliográficas completas deberían estar disponibles." }, { speaker: "A", text: "Has the study passed peer-review?", translation: "¿Ha pasado el estudio la revisión por pares?" }, { speaker: "B", text: "Yes, and the authors disclosed their possible conflicts.", translation: "Sí, y los autores revelaron sus posibles conflictos." },
    ], { title: "Evidence That Can Be Checked", text: "A research group publishes a promising result about learning. To protect the credibility of the claim, the authors describe their methodology, share the dataset, provide accurate citations, and disclose possible conflicts. Other researchers can then replicate the study and test the hypothesis independently.", translation: "Un grupo de investigación publica un resultado prometedor sobre el aprendizaje. Para proteger la credibilidad de la afirmación, los autores describen su metodología, comparten el conjunto de datos, proporcionan citas precisas y revelan posibles conflictos. Otros investigadores pueden entonces replicar el estudio y comprobar la hipótesis de forma independiente." }),
  ],
  C2: [
    u("Discourse Analysis", "Analyse how cohesion, stance, presupposition, and interaction shape meaning beyond sentences.", [
      w({ word: "cohesion", translation: "cohesión", pos: "noun", ipa: "/koʊˈhiːʒən/", definition: "the way linguistic elements connect a text together", example: "Pronouns and linking words create cohesion in the essay.", exampleTranslation: "Los pronombres y conectores crean cohesión en el ensayo.", synonyms: ["connectedness", "unity"], antonyms: ["disconnection"], collocations: ["textual cohesion", "cohesion device"], wordFamily: ["cohere", "cohesive", "cohesion"], tags: ["linguistics", "writing"], category: "text" }),
      w({ word: "presupposition", translation: "presuposición", pos: "noun", ipa: "/ˌpriːsʌpəˈzɪʃən/", definition: "an assumption that a speaker treats as already true", example: "The question carries a presupposition about the decision.", exampleTranslation: "La pregunta contiene una presuposición sobre la decisión.", synonyms: ["assumption", "premise"], antonyms: [], collocations: ["trigger a presupposition", "shared presupposition"], wordFamily: ["presuppose", "presupposition"], tags: ["linguistics", "meaning"], category: "inference" }),
      w({ word: "deixis", translation: "deixis", pos: "noun", ipa: "/ˈdeɪksɪs/", definition: "reference whose meaning depends on the context of speaking", example: "Here, now, and you are classic examples of deixis.", exampleTranslation: "Aquí, ahora y tú son ejemplos clásicos de deixis.", synonyms: ["contextual reference"], antonyms: [], collocations: ["personal deixis", "temporal deixis"], wordFamily: ["deictic", "deixis"], tags: ["linguistics", "context"], category: "reference" }),
      w({ word: "register", translation: "registro lingüístico", pos: "noun", ipa: "/ˈredʒɪstər/", definition: "a style of language appropriate to a particular situation", example: "The email shifts from an informal to a formal register.", exampleTranslation: "El correo cambia de un registro informal a uno formal.", synonyms: ["style", "level"], antonyms: [], collocations: ["formal register", "academic register"], wordFamily: ["register", "registered"], tags: ["linguistics", "society"], category: "style" }),
      w({ word: "stance", translation: "postura", pos: "noun", ipa: "/stæns/", definition: "the attitude or position a speaker expresses", example: "The writer's cautious stance is clear from the qualifiers.", exampleTranslation: "La postura cautelosa del autor queda clara por los matizadores.", synonyms: ["position", "attitude"], antonyms: [], collocations: ["take a stance", "authorial stance"], wordFamily: ["stand", "stance"], tags: ["linguistics", "rhetoric"], category: "attitude" }),
      w({ word: "ellipsis", translation: "elipsis", pos: "noun", ipa: "/ɪˈlɪpsɪs/", definition: "the omission of words that can be understood from context", example: "The second answer uses ellipsis to avoid repetition.", exampleTranslation: "La segunda respuesta usa la elipsis para evitar la repetición.", synonyms: ["omission"], antonyms: [], collocations: ["grammatical ellipsis", "use ellipsis"], wordFamily: ["elliptical", "ellipsis"], tags: ["linguistics", "grammar"], category: "structure" }),
      w({ word: "coherence", translation: "coherencia", pos: "noun", ipa: "/koʊˈhɪrəns/", definition: "the quality of being logical and easy to understand as a whole", example: "The conclusion gives the argument greater coherence.", exampleTranslation: "La conclusión da mayor coherencia al argumento.", synonyms: ["logic", "consistency"], antonyms: ["incoherence"], collocations: ["argumentative coherence", "maintain coherence"], wordFamily: ["cohere", "coherent", "coherence"], tags: ["linguistics", "writing"], category: "text" }),
      w({ word: "turn-taking", translation: "alternancia de turnos", pos: "noun", ipa: "/ˈtɜːrn ˌteɪkɪŋ/", definition: "the way speakers manage who talks and when", example: "Interruptions can disrupt turn-taking in a debate.", exampleTranslation: "Las interrupciones pueden alterar la alternancia de turnos en un debate.", synonyms: ["speaker exchange"], antonyms: [], collocations: ["manage turn-taking", "turn-taking system"], wordFamily: ["turn", "take", "turn-taking"], tags: ["linguistics", "conversation"], category: "interaction" }),
    ], [
      { phrase: "The context changes the interpretation.", translation: "El contexto cambia la interpretación." }, { phrase: "What does the speaker presuppose?", translation: "¿Qué presupone el hablante?" }, { phrase: "The text maintains a formal register.", translation: "El texto mantiene un registro formal." }, { phrase: "The argument lacks coherence at this point.", translation: "El argumento carece de coherencia en este punto." },
    ], [
      { speaker: "A", text: "Why does the reply sound more distant?", translation: "¿Por qué suena más distante la respuesta?" }, { speaker: "B", text: "The speaker changes register and adopts a cautious stance.", translation: "El hablante cambia de registro y adopta una postura cautelosa." }, { speaker: "A", text: "Is the meaning stated directly?", translation: "¿Se expresa directamente el significado?" }, { speaker: "B", text: "Not entirely; deixis and presupposition make the context important.", translation: "No completamente; la deixis y la presuposición hacen importante el contexto." },
    ], { title: "Reading the Conversation", text: "Discourse analysts examine more than isolated sentences. They trace cohesion and coherence across a text, identify presuppositions, and observe how deixis depends on context. In conversation, register, stance, ellipsis, and turn-taking reveal how speakers negotiate meaning and social relationships.", translation: "Los analistas del discurso examinan más que oraciones aisladas. Siguen la cohesión y la coherencia de un texto, identifican presuposiciones y observan cómo la deixis depende del contexto. En la conversación, el registro, la postura, la elipsis y la alternancia de turnos revelan cómo los hablantes negocian el significado y las relaciones sociales." }),
  ],
};
